### ISSUE TITLE
Crash with Mob Catcher on server

### ISSUE THREAD

**Issue by Xplodin** [Teneted/Tenet#1001]
[crash-2021-03-02_06.06.21-server.txt](https://github.com/Mohist-Community/Mohist/files/6066271/crash-2021-03-02_06.06.21-server.txt)

After catching a mob with mob catcher via launcher. The server will crash upon picking up the mob catcher ball

It honestly didnt give a cause in the log but I assume it was this

**Comment by KR33PYK1NG** [comment]
Mod issue.
