### ISSUE TITLE
EssentialsX and mods 

### ISSUE THREAD

**Issue by McNougatt** [Teneted/Tenet#1004]
Hey I've tested on some of the releases but I'm trying to get essentials working with my modpack I can load the mods and everything works.... I can load just the essentials plugin and it works but if I add my mods and essentials at the same time it says essentials is not up to date then was a couple mods that worked with it tho

**Comment by Dokman** [comment]
i wasn't issuing because it has a lot of changes to do, to make it work. it cannot work because is searching for something that isn't implemented. So it cannot work with mods directly.

**Comment by KR33PYK1NG** [comment]
> 
> 
> i wasn't issuing because it has a lot of changes to do, to make it work. it cannot work because is searching for something that isn't implemented. So it cannot work with mods directly.

It's not really the case. The core problem resides in the way Mohist injects enums.

**Comment by Dokman** [comment]
> > i wasn't issuing because it has a lot of changes to do, to make it work. it cannot work because is searching for something that isn't implemented. So it cannot work with mods directly.
> 
> It's not really the case. The core problem resides in the way Mohist injects enums.

It can be fixed?

**Comment by McNougatt** [comment]
Do you need me to send you reports and my mod list

**Comment by Dokman** [comment]
> Do you need me to send you reports and my mod list

i think is another thing, because an enum is a enumerate list of things.

**Comment by kmecpp** [comment]
Any updates on this? What's the problem with the way Mohist injects enums?

**Comment by KR33PYK1NG** [comment]
Mohist-compatible build of EssentialsX 2.19 is released.
Check out the 'plugins'mods'fix' channel on our discord.
