### ISSUE TITLE
[Plugin/Bug] LuckPerms Loading Database Error.

### ISSUE THREAD

**Issue by Dokman** [Teneted/Tenet#1006]
When the plugin loads have problem when tries to load the database.
![image](https://user-images.githubusercontent.com/2290904/109658998-83527800-7b67-11eb-8f30-21cb834e6661.png)

PS: 
![image](https://user-images.githubusercontent.com/2290904/109663492-75ebbc80-7b6c-11eb-858a-a05e633fb9c4.png)

Log file
[Log](https://haste.mohistmc.com/emazacucib.yaml)

**Comment by Xplodin** [comment]
I use spigot luckperms without issue. Id try that

**Comment by Dokman** [comment]
.76 is working +.76 is not working. Confirmed.

**Comment by KR33PYK1NG** [comment]
Check out 'plugins'mods'fix channel on our Discord, there I've posted a fixed LuckPerms v5.3 until the fix (possibly) gets integrated into upstream.
