### ISSUE TITLE
[Plugin/Essentials?] Multiple Essentials command stop working upon player death

### ISSUE THREAD

**Issue by SilentStarling** [Teneted/Tenet#1008]
Hi there, I tried reporting this bug with Essentialsx but apparently they don't like Mohist or something. I'm assuming this is a Mohist/Essentials interaction, because only Essentials commands seem to be affected.

Whenever a player dies, multiple commands stop working, including /back, /warp, and /tp. It doesn't remove permissions or anything, the command runs as normal and runs normal chat dialogue (the /back commands says "returning to previous position" like normal) but then nothing happens. Console doesn't show any bugs when this happens.

In addition, my staff and myself with /fly access find ourselves taking fall damage and even dying from landing from flying, even though /fly is still turned on (happens with both crouching to lower position, and double tapping space to stop flying). This only occurs if the player has already died from something else. 

I did additional testing, and found that if I die, then turn on creative mode when I respawn, I take damage from various sources (died of fall damage like described above, and also drowned while in creative).

If the player logs out and logs back into the server, everything is fixed again. This poses a problem however, as the /back is lost upon relog. So in addition to breaking lots of commands and being a nuisance, it means my players can't /back to get their stuff after they die.

Unsure what to do or what else to try, I've tried making sure my Mohist and all plugins are updated, I've removed any non-necessary plugins, and I've scoured config files to see if I have something set up wrong. As stated above, console never gives me any errors or anything so I don't know of any crash logs/etc to provide. Let me know if I can provide any further helpful information.

Current list of plugins:
Server version: 1.16.5-R0.1-SNAPSHOT 1.16.5-380 (MC: 1.16.5)
02.03 15:44:48 [Server] INFO EssentialsX version: 2.19.0-dev+86-ee5f4b9
02.03 15:44:48 [Server] INFO LuckPerms version: 5.2.67
02.03 15:44:48 [Server] INFO Vault version: 1.7.3-b131
02.03 15:44:48 [Server] INFO EssentialsXChat version: 2.19.0-dev+86-ee5f4b9
02.03 15:44:48 [Server] INFO EssentialsXSpawn version: 2.19.0-dev+86-ee5f4b9

BetterRTP
CoreProtect
GriefDefender
Multiverse-Core
Shopkeepers
Ultimate_Economy
WorldEdit
ChairsReloaded

**Comment by Dokman** [comment]
EssentialsX is not compatible with Mohist

**Comment by SilentStarling** [comment]
Ah I see. Do you know of a similar plugin that is compatible?

**Comment by ghost** [comment]
> Ah I see. Do you know of a similar plugin that is compatible?

CMI

**Comment by WareZ57** [comment]
> Ah I see. Do you know of a similar plugin that is compatible?

Working perfect (same than essentials)  https://www.spigotmc.org/resources/serversystem.78974/ 1.16.5

**Comment by SilentStarling** [comment]
thank you all for the suggestions! I will look at these plugins

**Comment by Janmm14** [comment]
The problem is that Mohist decided to not properly implement the bukkit api.

**Comment by ZoruaFox** [comment]
> The problem is that Mohist decided to not properly implement the bukkit api.

Therefore, the PSA is still on the download page of EssentialsX,also this is the reason that made me stop using Mohist.
