### ISSUE TITLE
[1.7.10] Chunks are not unloaded from memory

### ISSUE THREAD

**Issue by bagomot** [Teneted/Tenet#101]
Mohist build: aaeea53
**Testing steps:**
1. I launched the server with a minimal set of plugins and without modifications (with new map). I didn't visit the server, but I executed the command `/lag` from the console. In the Overworld, **625 chunks** were loaded. Why? 
2. I visited the server and flew there for 5 minutes, loading new chunks. `/lag` showed **1407 loaded chunks**. I left the server.
3. I executed the /lag command from the console every 5 minutes for half an hour. The number of loaded chunks has remained unchanged: **1407**.

This is abnormal behavior. I have a server with 20 online players in 2 hours download **60,000 chunks**! This leads to spawning of huge herds of animals.
I can't pinpoint the source of the problem, but I heard that this happens periodically with PaperSpigot updates. In addition, I had previously encountered a similar problem in Uranium, but there the chunks generated a cyclic loading of objects.

**Comment by Mgazul** [comment]
What plugin do you use? (/lag)

**Comment by bagomot** [comment]
This is Essentials pre-release 2.14.1.3 plugin. The `/lag` command is the `/gc` command alias.

**Comment by perezzloy** [comment]
You have an old version of the library. Delete your `libraries` directory and start the server, it will download and unzip the archive from. After that, restart the server.

**Comment by CraftDream** [comment]
Are your `chunk-gc` in `bukkit.yml` configured correctly?

**Comment by bagomot** [comment]
```
chunk-gc:
  enabled: false
  period-in-ticks: 600
  load-threshold: 0
```
I will enable and test with various parameters and report the results later.

**Comment by Zilacon** [comment]
I can confirm this issue on my end. And my config has chunk GC enabled every 600 ticks above 300 chunks.
Heres what i woke up to:
![Screenshot_324](https://user-images.githubusercontent.com/3002248/75143393-d159b380-56a9-11ea-9416-43b62bbd3d0e.png)

**Comment by bagomot** [comment]
My tests with the option turned on showed that the problem exists. I set the parameters as below and uploaded 3,000 chunks. They remain in memory all the time.
```
chunk-gc:
  enabled: true
  period-in-ticks: 600
  load-threshold: 2000
```

**Comment by CraftDream** [comment]
That should be a bug. So is there a problem in Mohist 1.12.2?

**Comment by bagomot** [comment]
> 
> 
> So is there a problem in Mohist 1.12.2?

No. Mohist 1.12.2 build cee8319 unloads chunks.

**Comment by CraftDream** [comment]
> > So is there a problem in Mohist 1.12.2?
> 
> No. Mohist 1.12.2 build [cee8319](https://github.com/Mohist-Community/Mohist/commit/cee8319b5d5a0ae7a5f81aa9475640ba60378aff) unloads chunks.

OK, please wait for us to fix the bug.

**Comment by bagomot** [comment]
> OK, please wait for us to fix the bug.

The wait is unsuccessful. Ok, thanks for trying.
