### ISSUE TITLE
[Plugin/PlaceholderAPI] Could not load expansion

### ISSUE THREAD

**Issue by Dokman** [Teneted/Tenet#1014]
So when i download from ecloud an expansion i have this error

![image](https://user-images.githubusercontent.com/2290904/109886729-d704b480-7c80-11eb-90a6-08f949ef0d2c.png)

Server Log
[Log](https://haste.mohistmc.com/ejayuhenud.yaml)

**Comment by Dokman** [comment]
with dev build i have this bug
![image](https://user-images.githubusercontent.com/2290904/110941336-78060600-8338-11eb-962b-a88908697235.png)
[Log](https://haste.mohistmc.com/ehibicuziz.yaml)

**Comment by Shawiizz** [comment]
Same as #1073
