### ISSUE TITLE
EntityCulling mod - crash at launch

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1016]
Mohist build: 382
Mod: https://www.curseforge.com/minecraft/mc-mods/entityculling

Crash report:
[crash-2021-03-03_17.56.11-fml.txt](https://github.com/Mohist-Community/Mohist/files/6081051/crash-2021-03-03_17.56.11-fml.txt)

**Comment by KR33PYK1NG** [comment]
This one is mod's issue.
