### ISSUE TITLE
Mohist-1.12.2-192 with mod "B3M" will crash at launch

### ISSUE THREAD

**Issue by zeal9245** [Teneted/Tenet#1022]
The mod is Вращение Земли Майнкрафтская (Accurate day/night-cycles Mod) https://www.curseforge.com/minecraft/mc-mods/time-speed-mod

Crash report:
[crash-2021-03-05_18.46.11-server.txt](https://github.com/Mohist-Community/Mohist/files/6090027/crash-2021-03-05_18.46.11-server.txt)

**Comment by aceman1209** [comment]
Looks like bad bytecode modification.
Probably, Mohist modificate classes that core mod try to modificate.
https://prnt.sc/10njq0a
https://prnt.sc/10njqfs

**Comment by zeal9245** [comment]
Glad to receive your reply.
I tried to contact the MOD‘s author, but no response yet.
And add -noverify on JVM arguments will make the server start normally, but the mod "B3M" runs abnormally, there is fast forward 20 MC days every second.

**Comment by aceman1209** [comment]
-noverify turns off class verification. That like you saying "Hey, just do it, i don't care about things what can happen. Just do it".
Method how mod author make changes is very basic. It doesn't include compatibility.
Please wait response from author and put it here (e.g reference).

**Comment by zeal9245** [comment]
Thanks I see.
