### ISSUE TITLE
1.16.5 | mohist 382 | rats: PlagueDoctor servercrash

### ISSUE THREAD

**Issue by darksoon** [Teneted/Tenet#1023]
[crash-2021-03-05_11.39.34-server.txt](https://github.com/Mohist-Community/Mohist/files/6090059/crash-2021-03-05_11.39.34-server.txt)

The Minecraft Version is 1.16.5
The Mohist Version is 382
Mod: rats-7.1.1-1.16.5 > Plague Doctor

Server crash randomly with or without a player on it.

**Comment by KR33PYK1NG** [comment]
Fixed in 087423d
