### ISSUE TITLE
[1.7.10] Crash with RecurrentComplex (Duplicated issue)

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#103]
_Hello o/_

**Mohist Version:** Build 97
**RecurrentComplex Version:** 0.9.7.1.1
**Crash report:** https://pastebin.com/1Qwfgqqz

Crash during server startup.

_P.S. I know this issue is a duplicate of issue #53. I created a copy because the problem, unfortunately, has not been fixed._

**Comment by Mgazul** [comment]
Crash when starting the server?

**Comment by Mgazul** [comment]
78abed6

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
