### ISSUE TITLE
1.16.5 | Mohist 384 | New forge/vanilla packet splitters cause client/server mod mismatch

### ISSUE THREAD

**Issue by jupjohn** [Teneted/Tenet#1030]
When using the latest build (384) of Mohist 1.16.5 clients are unable to join the server when running the same version of Forge. This is caused by a client/server mismatch where the client does not have `forge:split` (introduced in 0a2048f1747eb610f2eea21618f6a838a26d617e). Builds prior to this commit allow clients to join.

Looks like the introduction of the Vanilla/Forge packet splitter classes are to blame for this. Rolling back the forge version in the latest commit to 36.0.42 does not resolve. Issue is most likely within Mohist.

**Comment by KR33PYK1NG** [comment]
What do you mean?
I can connect to Mohist 384 with Forge 36.0.46 client just fine.

**Comment by jupjohn** [comment]
It seems to be when running a version of forge less than the one in that commit. Happy for you to close this if you'd rather not deal with that but it does mean backwards compatibility is broken with forge.

**Comment by KR33PYK1NG** [comment]
Yes, if you run 36.0.46 server and 36.0.45 or lower client, you can't connect.
That is because Forge 36.0.46 introduced a new net channel called "split" for splitting Vanilla packets.
Broken backwards-compatibility here is not Mohist's fault.
