### ISSUE TITLE
Error when adding a recipe

### ISSUE THREAD

**Issue by Slypy06** [Teneted/Tenet#1031]
I am developing a UHC plugin for myself which uses mods. So I use mohist to run it. However, the server returns me an error coming from the custom recipes. I use the classic method to add recipes to bukkit. The API used during development is the latest build of spigot 1.16.5. There is the exception : https://haste.mohistmc.com/mererarazi.md

**Comment by KR33PYK1NG** [comment]
Fixed in 98086cd
