### ISSUE TITLE
[1.16.5] Mismatched mod list

### ISSUE THREAD

**Issue by gXLg** [Teneted/Tenet#1037]
Soo... I am starting my server and after it loads no one can join. Currently I have no mods installed, only some plugins. When someone tries to connect, it says:

[This server has mods that require Forge to be installed on the client...]

And on server:
`Channels [forge:split] rejected vanilla connections`

Well, earlier I did not need any mods or even Forge.

Edit: if misunderstood:
Earlier I started my server with the same configuration, Minecraft version 1.16.5, just an older Mohist version, and I did not need Forge to join. Now it is starting and I can't join without Forge

**Comment by mteij** [comment]
You need forge to join your server.

**Comment by gXLg** [comment]
> You need forge to join your server.

Why would I need it, if I never needed it before

**Comment by Mgazul** [comment]
1.16.5 works differently from 1.12.2, this is the setting of forge, and has nothing to do with mohist

**Comment by gXLg** [comment]
@Mgazul 
Well, I had my server on 1.16.5 all this time, and could play from Vanilla, Forge, Fabric... Everything worked until I updated to the newest Mohist version
