### ISSUE TITLE
Add StructureLocateEvent from Paper

### ISSUE THREAD

**Issue by bossomeness** [Teneted/Tenet#1040]
When using Mohist to run a few mods alongside plugins, I run into an issue with my world generator. I am using Terra (https://www.spigotmc.org/resources/terra.85151/), and when I load a new world, none of the structures generate (trees, villages, etc). After talking to the Terra devs, they told me I needed the StructureLocateEvent in Mohist for Terra to properly function. This was authored by the main Terra dev dfsek (https://github.com/PaperMC/Paper/commit/193f80148c02700d0a1bf0f28727a89478c5dfb5?branch=193f80148c02700d0a1bf0f28727a89478c5dfb5&diff=unified).

Any chance this could be added in?

**Comment by KR33PYK1NG** [comment]
Implemented in af1f736
