### ISSUE TITLE
bukkit's unknown command's log spam

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1042]
example:
`10.03 16:25:09 [Server] INFO Unknown command. Type "/help" for help.
10.03 16:25:45 [Server] INFO Unknown command. Type "/help" for help.
10.03 16:26:20 [Server] INFO Unknown command. Type "/help" for help.`
**Installed:** 
Mohist 387
Forge 36.0.48
LuckyPerms (5.3.1 fixed for mohist)
GriefDefender 1.5.10
Create mod 0.3e
Jei 1.16.4   7.6.1.66
I had the same issue on multiple re-made servers with different plugins, that's why I post the issue here

**Comment by KR33PYK1NG** [comment]
What commands are you trying to use?

**Comment by muriplz** [comment]
I'm not using nothing, it just triggers every minute or so

**Comment by KR33PYK1NG** [comment]
This doesn't happen for me on the latest build.
