### ISSUE TITLE
Unloaded chunks are not loaded again

### ISSUE THREAD

**Issue by frogden** [Teneted/Tenet#1043]
If you leave the chunk activation zone, then any activity stops its work even after you re-enter this chunk.
Nothing grows, the mechanisms don't work :c
I can provide a list of mods

**Mohist Version: 1.16.5
Build: 376 (mohist-1.16.5-376-server.jar)**

**Comment by KR33PYK1NG** [comment]
You should update to the latest build (mohistmc.com)

**Comment by frogden** [comment]
Thanks a lot!
