### ISSUE TITLE
Server hangs when trying to change locale

### ISSUE THREAD

**Issue by justkowal** [Teneted/Tenet#1044]
Mohist 1.12.2 build 194 - Server hangs after logging
`[13:03:34 INFO]: Locale was restored to en`
Mods used:

- Additional Pipes
- BuildCraft
- Carpenter's Blocks
- CC: Tweaked
- Chameleon
- Chisel Mod
- Chisels and Bits
- CodeChicken Lib
- CTM
- Decocraft
- ExtraBitManipulation
- Flat Colored Blocks
- Forge Multipart CBE
- Fossils and Archeology
- Gravestone Mod
- Just Enough Items
- JourneyMap
- Lightning Bolt
- LLibrary
- MalisisCore
- Malisis Doors
- MrTJPCore
- ProjectE
- Project Red (base, compat, fabrication, integration, lighting, mechanical, world)
- PTRLib
- Storage Drawers
- Twilight Forest
- XL Food Mod

Plugins: 

- AuthMe
- Maintenance MOTD
- Set Home
- Skins Restorer

**Comment by KR33PYK1NG** [comment]
Where exactly are you trying to change locale?

**Comment by Shawiizz** [comment]
Hey, please give details. Which locale are you trying to change ? @hopkuba
