### ISSUE TITLE
Mob spawning stops after a time

### ISSUE THREAD

**Issue by BlackAce21** [Teneted/Tenet#1045]
Modpack: SkyFactory 4
Mohist Version: 1.12.2-192

Basic Overview:

The gist of the problem is that I am encountering what I can only describe as a broken mob spawning object. I haven't been able to lock down the specifics yet of what's going on, I was hoping someone here might be able to shed some light on the problem. It all started when I got to the mob farm stage of this skyblock world. 

I built the thing, closed off all light sources and went away. I've built hundreds of these mob droppers so I am 100% certain this isn't some design problem. A bit of investigation leads me to a post on the spigot forums regarding mob spawn limits and their mechanics. So I figure, no biggy, I'll play with the math and kick the mob spawn rates up to vanilla standard levels and things should be ok. I currently have the monster limit set at 250 and tick delay at 1 so that with spigot mob range of 4 it will mimic vanilla spawn rates of 70 with a high tick rate. I figured this would be high for a server but I'm play testing so I'd rather overkill it and see what breaks first.

The result is strange. The moment the server comes up, I log in, the mob spawner is filled to bursting with mobs and I think everything is great. 10 minutes later, the mob spawner is no longer spawning mobs. I tear it apart bit by bit, remove everything in the immediate area that could potentially be spawning entities, rebuild the thing in other dimensions away from other modded blocks. I've tried everything.

The problem is that mob spawning functions fine for around 10 minutes every restart and sometimes right after I unload the chunks for a while and come back. Its pretty consistent with the 5-10 minute mark although I haven't timed it exactly, and before anyone asks, I coded a spigot event monitor for spawn events just to make sure something wasn't cancelling the spawns and its not. I also tested SP just to make sure it wasn't a mod issue and spawning works fine there.

This is my first go round with a mohist server so I'm not sure if any high level debugging options exist to monitor the tick spawn object but I suspect there is an issue with it. Any information or ideas anyone might have would be most helpful. My next step will be to start tearing apart code and adding my own debug options but I figured coming here first would be the better idea in case its something really stupid I setup wrong. Thanks in advance.

**Comment by KR33PYK1NG** [comment]
Try updating to the latest build and see if it works. (mohistmc.com)

**Comment by BlackAce21** [comment]
Can confirm the issue is persistent in version 195 which seems to be the latest version as of today.

**Comment by BlackAce21** [comment]
I would also like to mention that in Skyfactory 4 there are at least 3 dimensions, probably 4, where there is some form of natural world gen and if you travel across the landscape, spawning seems to work just fine in those dimensions. It's almost as if, if you wait in one spot long enough, the spawner either reaches a cap of some kind or is being removed somehow. I am about to test java args to see if its some sort of aggressive GC settings packaged with the mod pack causing problems. I'll report back if this ends up being the issue.

::edit:: I just realized I am not even using the mod pack java args, just default settings across the board so I have doubts that's part of the problem, but perhaps it will aid in the diagnosis. Next step will probably be removing mods one at a time to see if that triggers anything

**Comment by Paneedah** [comment]
I can confirm that this isn't a modpack related issue. I ran /killall mobs on my server and they only respawned if I placed down spawners or loaded new chunks.

**Comment by BlackAce21** [comment]
That seems to be fairly consistent with the behavior I'm seeing. Spawning will stop in my home chunk but if I go away and unload it for a bit and spawn new mobs in new chunks it'll randomly start spawning again. I also just get the random spawn every now and again where 1 or 2 mobs will spawn randomly and then nothing. I have my mob farm under my base so I've been keeping an eye on it to get a feel for the mechanics of the problem.

**Comment by i128kbps** [comment]
I see the same behavior at stoneblocks 2. After a while all spawning is stopping.

**Comment by Mgazul** [comment]
spigot has an entity cap setting
