### ISSUE TITLE
[1.7.10] LuckPerms not initialized

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#105]
_Hello o/_

**Mohist Version:** Build 99
**LuckPerms Version:** Bukkit-Legacy-5.0.81
**Log:** https://pastebin.com/y4ppf1v5

P.S. I also tried to replace the libraries, as stated on the LuckPerms wiki, but this did not lead to anything.

**Comment by CraftDream** [comment]
Trying to load LuckPerms for forge.

**Comment by GedeonGrays** [comment]
> Trying to load LuckPerms for forge.

Hem, what? Are there really LuckPerms for Forge? Why I did not know about it and did not find information on the official LP page...
Of course, I will try to follow your advice, but it seems to me that the problem still has a place to be.

**Comment by GedeonGrays** [comment]
Unfortunately, there seems to be no LuckPerms for Forge. Therefore, the problem persists.

**Comment by Mgazul** [comment]
#113
