### ISSUE TITLE
Automatically remove ProtocolLib plugin from plugins folder 

### ISSUE THREAD

**Issue by iFeelHealU** [Teneted/Tenet#1050]
It happens at every startup with or without mods and other plugins, but when I paste this plugin into folder after startup and then manually load it, all works great. I need to do that every restrart so this is a bit uncomfortable. I ise it for the entity culling plugin. 
Mohist version is 1.16.5 387

**Comment by Shawiizz** [comment]
You mean that ProtocolLib is fully compatible with Mohist 1.16.5 ?

**Comment by iFeelHealU** [comment]
Looks like it can work sometimes, but it also can crash your server, so I understood the purpose of the "delete" folder where I found that plugin after the server startup
