### ISSUE TITLE
[1.16.5][mod][crash] industrialforegoing crash

### ISSUE THREAD

**Issue by MrLyyy** [Teneted/Tenet#1052]
Fakeplayer
https://paste.ubuntu.com/p/nccV7855Nb/

**Comment by MrLyyy** [comment]
mohist 400 don't fix lis
https://paste.ubuntu.com/p/67sx9Pm38K/

**Comment by TheMartinfer22** [comment]
Fix on **Mohist 403**, but FakePlayer isn't working either.
