### ISSUE TITLE
FAWE plugin

### ISSUE THREAD

**Issue by Chetok3** [Teneted/Tenet#1056]
![image](https://user-images.githubusercontent.com/78810000/111084081-bd395c00-8521-11eb-847e-aa025659a166.png)
Mohist 1.16.5-403

**Comment by KR33PYK1NG** [comment]
This shouldn't occur on the latest build.

**Comment by Chetok3** [comment]
![image](https://user-images.githubusercontent.com/78810000/111349269-090b1300-8692-11eb-97ab-546cc89c38c7.png)
Все еще неа)
