### ISSUE TITLE
[1.7.10] crashes when using the command

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#106]
Mohist Version: Build 99
MobiusCore-1.2.5_1.7.10
Opis-1.2.5_1.7.10
Log: https://hastebin.com/uyibilecuw.sql

crashes when using the command /opis

**Comment by CraftDream** [comment]
This paste cannot be opened.

**Comment by Maks-Haswell** [comment]
> Эту пасту нельзя открыть.
here https://pastebin.com/PRCX2aH7

**Comment by CraftDream** [comment]
`mobiuscore`
This mod has a problem with Mohist.
It should be a bug, waiting to be tested and fixed.
