### ISSUE TITLE
[1.16.5] Entity collision bug

### ISSUE THREAD

**Issue by lunofe** [Teneted/Tenet#1061]
There is a bug that doesn't allow you to stand in the same spot with another entity. Seems to affect animals, monsters and dropped items.

Tested on 400, 403 and 405 without any mods or plugins installed.

![pl](https://user-images.githubusercontent.com/42828197/111178917-e0105280-85ab-11eb-9c4e-e93e219178d0.gif)

**Comment by Scrulius** [comment]
+1, same problem in 405

**Comment by Shawiizz** [comment]
Hi, can you try with older builds please ?

**Comment by Aixiis** [comment]
I tried with 402 and 400, same problem ':D
https://imgur.com/a/uk82kJm

**Comment by Shawiizz** [comment]
I mean with very older builds (like 380 for example)

**Comment by Aixiis** [comment]
I can try !

**Comment by lunofe** [comment]
I've been using 385 before, the bug didn't exist there. 386 & 387 are also working fine.

The builds between **387 & 398** are missing on the website, so I can't pin it down further. **It happens somewhere between them.**

**Comment by Aixiis** [comment]
Yup, tried 380, 375 and 385, unable to reproduce the bug !

**Comment by natsitarz** [comment]
Hey! I don't know but maybe this will help a little bit. When dropping item from eq with Camera Overhaul mod installed, camera goes down and up. I think it can be related. Can confirm too that on 380, 375 and 385 build this issue wasn't occuring (entity collision bug neither cameraoverhaul goes down and up). 
https://user-images.githubusercontent.com/78207063/111432255-14475880-86fd-11eb-9d23-5fda7d8d0248.mp4

**Comment by Dokman** [comment]
same on 411

**Comment by Aixiis** [comment]
> Hey! I don't know but maybe this will help a little bit. When dropping item from eq with Camera Overhaul mod installed, camera goes down and up. I think it can be related. Can confirm too that on 380, 375 and 385 build this issue wasn't occuring (entity collision bug neither cameraoverhaul goes down and up).
> https://user-images.githubusercontent.com/78207063/111432255-14475880-86fd-11eb-9d23-5fda7d8d0248.mp4

actually, it's showed on the video up top of the post ':D, and it's because of the auto-sneak when only 1.5 blocks height is available ^^

**Comment by WareZ57** [comment]
The bug is present on all builds from 1.16.5-398.


Working fine on 1.16.5-387

**Comment by KR33PYK1NG** [comment]
I still haven't succeeded in tracking down the source, so any help is appreciated.

**Comment by lunofe** [comment]
@KR33PY Can you provide me with the .jars from builds 388 - 397? The bug appears in one of them.
(_https://mohistmc.com/ doesn't list them_)

**Comment by Shawiizz** [comment]
It's normal, the builds 388, 389, 390, 391, 392, 393, 394, 395, 396 and 397 are failed and not downloadable.

**Comment by JoaoOlivetti** [comment]
i´m on 412 and this bug is still happening, any updates on this?

**Comment by Scrulius** [comment]
any updates on this?

**Comment by KR33PYK1NG** [comment]
Fixed in 6d96e3d
