### ISSUE TITLE
[ProtocolLib/Bug] Found 8 Bytes extra whilst reading packet 0

### ISSUE THREAD

**Issue by Dokman** [Teneted/Tenet#1062]
![image](https://user-images.githubusercontent.com/2290904/111366359-aca8f300-8693-11eb-864b-e5cc10fd7f30.png)
![image](https://user-images.githubusercontent.com/2290904/111366400-b9c5e200-8693-11eb-8500-3bb5d14dccfd.png)

[Log](https://haste.mohistmc.com/azofelifam.yaml)

**Comment by Dokman** [comment]
fixed deleting protocollib

**Comment by ghost** [comment]
такая же хуйня

**Comment by KR33PYK1NG** [comment]
It is known, ProtocolLib is unsupported at the moment.

**Comment by ghost** [comment]
> It is known, ProtocolLib is unsupported at the moment.

Arclight Solved this problem a long time ago

**Comment by KR33PYK1NG** [comment]
> > It is known, ProtocolLib is unsupported at the moment.
> 
> Arclight Solved this problem a long time ago

Well, good for them.
