### ISSUE TITLE
Player invisible and unable to move

### ISSUE THREAD

**Issue by notkidgamer23** [Teneted/Tenet#1066]
When the client has dynamic surroundings installed, even if the server itself does not have dynamic surroundings installed, it causes the player to be invisible and unable to move. The player can still interact with and break blocks but cannot move or be seen. 

PS Thanks for the hard work on Mohist, you're pushing one of the forefronts of modern modded servers.

**Comment by notkidgamer23** [comment]
Forgot to add, version is mohist-1.16.5-412-server

**Comment by KR33PYK1NG** [comment]
https://github.com/OreCruncher/DynamicSurroundings/issues/696
