### ISSUE TITLE
ViewDistanceCat Crash - What our servers need!

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1067]
![8129_5ff0846ba4370](https://user-images.githubusercontent.com/71688822/111183039-8c5c3400-85c0-11eb-8ddb-eb7ae83cb675.jpg)

**Plugin version**: 4.8.2
**Version Mohist**: 414
**Report**:  [latest.log](https://github.com/Mohist-Community/Mohist/files/6165686/latest.log)

**Mode installed**:
Nope

**Plugin installed**: 
XuanCatAPI-Spigot, ViewDistanceCat

**### ALERT! Spigot server, config.yml can-generate-chunk to false!!**

**Link on error plugin**: [https://www.spigotmc.org/resources/viewdistancecat.84950/](url)
And [https://www.spigotmc.org/resources/xuancatapi-spigot.84949/](url)

**Comment by KR33PYK1NG** [comment]
From what I see in the log, XuanCatAPI tries to load v1_16_R2 implementation class but Mohist uses v1_16_R3, so it expectedly fails.
So plugin-side issue.
