### ISSUE TITLE
crash mod Epic Fight mod

### ISSUE THREAD

**Issue by chakkaebi** [Teneted/Tenet#1068]
![image](https://user-images.githubusercontent.com/80914320/111667353-f6dad180-8857-11eb-895c-04001c79ea7d.png)
Applying Epic Fight Mode and reconnecting after leaving the server causes the mode to fail and cause an image error.
Help plz. I spend many time this problem
ver - 1.16.5-414
mod - epic fight mod(only)

**Comment by chakkaebi** [comment]
![image](https://user-images.githubusercontent.com/80914320/111668186-d9f2ce00-8858-11eb-81ef-17240c1a33c6.png)
To solve this problem, if you die on the server, an error in the image appears and resolves it. But I don't think this is the perfect answer.

**Comment by chakkaebi** [comment]
It works without any problems in a typical forge bukkit.

**Comment by KR33PYK1NG** [comment]
> It works without any problems in a typical forge bukkit.

What do you mean by saying "typical forge bukkit"? Mohist IS a forge+bukkit hybrid.

**Comment by chakkaebi** [comment]
pure forge bukkit. 
ex) installd by forge installer

**Comment by KR33PYK1NG** [comment]
Pure Forge (without Bukkit) is what installed by Forge Installer.

**Comment by chakkaebi** [comment]
Um... I am sorry that I could not deliver the explanation well because I am not good at English. There was no problem when the most popular method was to create a forge server. But I want the mode and plug-in to be simultaneously crashed on 1.16.5 version.

**Comment by archonxgames** [comment]
Can confirm this occurs, but it is most likely an Epic Fight mod internal issue than a Mohist issue.

**Comment by or-n** [comment]
i confirm, happens after a player disconnects and tries to join again
seemed to not occur on a new world though with MultiverseHardcore plugin, but i want to import an old world from a forge server without any plugins

**Comment by Romaindu35** [comment]
Are you always this bug with latest build ?

**Comment by Romaindu35** [comment]
And it's same that #1447
