### ISSUE TITLE
Some console spam 1.16

### ISSUE THREAD

**Issue by avescarelo** [Teneted/Tenet#1069]
I installed several plugins and got a lot of errors in the console
Log: https://gist.github.com/pingvikin/c1d3b6252ae36dd041f181c69020328f

**Comment by KR33PYK1NG** [comment]
I don't see anything unusual in the log.
Can you point out what kind of errors you got?

**Comment by avescarelo** [comment]
> I don't see anything unusual in the log.
> Can you point out what kind of errors you got?

I see a lot of spam in the log, is this normal?

**Comment by KR33PYK1NG** [comment]
What kind of spam exactly?
Screenshot?

**Comment by avescarelo** [comment]
I just see that the console is full of errors, I do not understand what their cause is. Perhaps the problem is in the Mohist.

Sometimes large files are truncated, open them completely
![image](https://user-images.githubusercontent.com/26678843/111855267-f5330b80-8934-11eb-95c5-093e9a618f88.png)


A newer server log (just collected)https://gist.github.com/pingvikin/2493132a4f8758c89ab7de427ae11b44

**Comment by Mgazul** [comment]
Please send the log file directly instead of putting it on any text storage page
