### ISSUE TITLE
Players do not take damage in diamond armor 1.12.2

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1070]
Hello everyone. I noticed one serious bug. Players in diamond armor do not take health away. They can take damage, but they do not take their life even if they blow up 100 dynamite.

**Comment by aceman1209** [comment]
Do you use any modifications or plugins?

**Comment by ghost** [comment]
> Do you use any modifications or plugins?

no tried and without mods and without plugins, the result is the same

**Comment by ghost** [comment]
up

**Comment by KR33PYK1NG** [comment]
This was fixed, try installing the latest build.
