### ISSUE TITLE
Server Hang on Generating Chunks

### ISSUE THREAD

**Issue by JKos4** [Teneted/Tenet#1071]
If I move at creative sprint flying speeds, chunk generation slows down and eventually the server will stop generating chunks and hang. I can provide the mod list as well. In addition, sometimes when this hang happens, even bringing the player back to spawn will continue to hang the server when they join. For some reason it seems to be tied to the number of chunks generated. I even tried pre-generating chunks to alleviate this issue but that hung the server too.

Here's the link for the log:
https://drive.google.com/file/d/1enHtxOuZ1huQrDpUbAWktFCtTqTvKk2B/view?usp=sharing
I would've used pastebin but it exceeded the file size limit.

Here's the link for the modpack I'm using:
https://drive.google.com/file/d/1mlmT8IZdOPD0wOLesVCEFQMk9FhDxYb6/view?usp=sharing

If you want to reproduce this issue just load up the latest version of mohist with the pack installed and fly in a straight line, the server should crash in under a minute. Maybe it's the fault of my pack? Any help is appreciated.

**Comment by KR33PYK1NG** [comment]
First and foremost - stop using OptiFine on server-side, it does nothing.

**Comment by KR33PYK1NG** [comment]
Also, try builds lower than 414. Does this still occur?
https://mohistmc.com/download/

**Comment by JKos4** [comment]
I'll stop using optifine server-side. I updated to see if this issue would be fixed, no luck. though i was having an entity collision rubber banding issue that's fixed in the new update so good job on that :D. So yes i have had this issue in builds lower than 414. and i have tried running without optifine with no luck. For context as well i dont have this issue in singleplayer.

**Comment by KR33PYK1NG** [comment]
Try updating to build 417.

**Comment by JKos4** [comment]
I am out of the house currently but I can get back to you tomorrow!

**Comment by JKos4** [comment]
https://drive.google.com/file/d/1W7LQb9dOUzNCTlXzuQMzDI1WJV1id5dK/view?usp=sharing

Here is the log, unfortunately the update did not work. Though instead of 417 I did 419. I'm just confused by what could cause this hang on the server but not in singleplayer... I also removed Optifine like you said

**Comment by JKos4** [comment]
https://drive.google.com/file/d/19774kirOrUp5bE2QH19wW2fwvilQjI2v/view?usp=sharing

I just ran a test on 422, still hangs when I go far enough, no improvement... I don't expect chunks to load fast but I am wondering what could be causing the server to catastrophically fail...

**Comment by Mgazul** [comment]
Will the problem still be triggered without any mod?

**Comment by JKos4** [comment]
I can check that for you later tonight, I'm taking a midterm right now

**Comment by aurilisdev** [comment]
> I can check that for you later tonight, I'm taking a midterm right now

Did what he said fix it?

**Comment by JKos4** [comment]
I haven't had the time to test it yet but i will check tomorrow morning.
