### ISSUE TITLE
Console Spam on 1.12.2

### ISSUE THREAD

**Issue by SekiAlpha** [Teneted/Tenet#1077]
So I've had this issue for a while, and although it doesn't seem to affect gameplay it is a pain in the ass to deal with in the console.
![image](https://user-images.githubusercontent.com/12445848/111876890-0e5cac00-8977-11eb-973d-86dbe7084d9e.png)
Now to me, it seems like the issue could be that there is another application running that is accessing the world files, but I also tried to run the server on another computer with the same results.

I don't know what other information to give other than the mod pack I'm using.

**Comment by Shawiizz** [comment]
Are you sure that a mod / plugin isn't loading the world 2 times ?

**Comment by SekiAlpha** [comment]
Ah yes, I have already checked via unloading all plugins. I can start with the mods now but I don't know what mod would cause issues like that. I could compile a mod list for you to scan for any mods that seem like they would cause issues.

**Comment by Shawiizz** [comment]
Hey, can you try to remove all mods 1 per 1 and see which is causing that ?

**Comment by SekiAlpha** [comment]
Yes, once I have the time for it.

**Comment by SekiAlpha** [comment]
damn sorry this is taking a while to get done

**Comment by Shawiizz** [comment]
Hi @SekiAlpha, any news on this ? Does this happen today with latest build ?

**Comment by SekiAlpha** [comment]
Yes it happens on the latest build. I would change one mod at a time
however I have quite a large modpack so it isn't very easy to do.

**Comment by Mgazul** [comment]
Provide your modpack

**Comment by SekiAlpha** [comment]
Oh sure.

https://www.justanothergamingsyndicate.com/minecraft/JAGS%20Modpack.zip

That link works with the multiMC launcher.

I can provide server file as well.
