### ISSUE TITLE
1.16.5 Problem plugin IridiumSkyblock 

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1079]
Describer problem: any item placed inside the island, give error on the console, just place an item of any mod.
Also give error to interact with him.

Log: https://mclo.gs/sV5AvjH

This server is running Mohist version 1.16.5-417 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.0)

**Comment by aceman1209** [comment]
It's not Mohist issue, it's plugin incompatibility because plugin supports only vanilla materials and doesn't know about modded materials.

**Comment by joaoespanhol** [comment]
same thing with essentials, also does not work forge.

**Comment by aceman1209** [comment]
In essentials it can be caused by other problems but here it caused by material checking.
https://mclo.gs/sV5AvjH#L52038
`Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: WAYSTONES_WAYSTONE `

**Comment by joaoespanhol** [comment]
all plugins isolate, give this error.

**Comment by aceman1209** [comment]
If you mean that you disable all plugins and enable only IridiumSkyblock - it doesn't matter because IridiumSkyblock generates exception

**Comment by darksoon** [comment]
there is a paid plugin that is perferct working for skyblock, worldedit / worldguard protection with mohist. look at islandworld

**Comment by joaoespanhol** [comment]
> islandworld

no have version 1.16.5

**Comment by darksoon** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/2123049/111912486-12b5c180-8a6a-11eb-8916-20ec34d98972.png)

its works perfect with 1.16.5
