### ISSUE TITLE
[Bug] When you restart the server Console 2 opens

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1082]
when I restart the server the second console opens and the first one stays in place 
https://imgur.com/a/3civPVx

**Comment by avescarelo** [comment]
> when I restart the server the second console opens and the first one stays in place
> https://imgur.com/a/3civPVx

Русские вперёд!

**Comment by aceman1209** [comment]
If you use spigot option restart-script - it fine in windows because new bat file execution runs in other cmd window always.

PS: русские есть и контрибьтерах, и в команде Mohist, необязательно так акцентировать)

**Comment by Shawiizz** [comment]
That's normal if you're using the restart spigot thing. You need to close the first console manually (press something on it)
