### ISSUE TITLE
Failed to install some libraries while installing Mohist

### ISSUE THREAD

**Issue by Haswell49** [Teneted/Tenet#1084]
It's on Mohist 1.16.5 too.

[install.log](https://github.com/Mohist-Community/Mohist/files/6177176/install.log)

**Comment by Haswell49** [comment]
I ran it using this command in shell (Windows):

`java -jar mohist-1.16.5-417-server.jar > install.log`

**Comment by WareZ57** [comment]
Hello, i think the problem is coming from you (antivirus ? Firewall ? Java ? Windows OS ?)

Short tutorial https://streamable.com/yy60gs

Try with : 

```
@echo off
java -jar server.jar nogui
pause
```

**Comment by Shawiizz** [comment]
Everything is fine on my side. The server download libraries and the server can start without any problem

**Comment by Shawiizz** [comment]
Try to disable your anti virus, or reinstalling java properly / set use_custom_java8 to true in mohist-config/mohist.yml.
