### ISSUE TITLE
WG, WE and Mohist on 1.16.5

### ISSUE THREAD

**Issue by avescarelo** [Teneted/Tenet#1091]
Hello, I installed WG and WE on mohist 1.16.5.
But I ran into some strange problems, namely-the plugin crashes when loading the server. I tried installing a special WE for Mohist - but it also won't start. What could be the problem? Please help me

Log: https://gist.github.com/pingvikin/76c07c211105601db540ab0895c14fa9

**Comment by Saabertooth1** [comment]
> 
> 
> Hello, I installed WG and WE on mohist 1.16.5.
> But I ran into some strange problems, namely-the plugin crashes when loading the server. I tried installing a special WE for Mohist - but it also won't start. What could be the problem? Please help me
> 
> Log: https://gist.github.com/pingvikin/76c07c211105601db540ab0895c14fa9

Have you tried bukkit version 7.2.4?
I'm running that one on my server and it seems to work fine with the exception of modded blocks

**Comment by avescarelo** [comment]
> > Hello, I installed WG and WE on mohist 1.16.5.
> > But I ran into some strange problems, namely-the plugin crashes when loading the server. I tried installing a special WE for Mohist - but it also won't start. What could be the problem? Please help me
> > Log: https://gist.github.com/pingvikin/76c07c211105601db540ab0895c14fa9
> 
> Have you tried bukkit version 7.2.4?
> I'm running that one on my server and it seems to work fine with the exception of modded blocks

Yes, no, it works. But with every successful case, it spams errors, it hardly should be so

**Comment by Dokman** [comment]
It's a known bug i reported before
