### ISSUE TITLE
Mohist 1.16.5-425 + Skript 2.5.3 are not functional and when I send /sk reload all command, Skript responds /skript help.

### ISSUE THREAD

**Issue by SidNamo** [Teneted/Tenet#1095]
Mohist 1.16.5-425 + Skript 2.5.3 are not functional and when I send /sk reload all command, Skript responds /skript help.

**Comment by jjyouso** [comment]
I experienced the same symptoms.

I was using mohist-1.16.5-443 +Skript 2.5.3, and I just tried the updated mohist-1.16.5-444 +Skript 2.5.3. again. 

Only use Plugin, skript works fine. but when used with mod, all script command, responds /skript help.

This was the same for the previous release of Mohist, Minecraft Version 1.16.4.

**Comment by joaoespanhol** [comment]
issue oudated

I am using skript my server.

@Romaindu35

**Comment by Romaindu35** [comment]
This issue seems fixed, if you have always this problem, please open new issue.
