### ISSUE TITLE
FTB Utilities rank not working

### ISSUE THREAD

**Issue by myaako-wasure** [Teneted/Tenet#1103]
The rank of FTB Utilities is not working.
The rank is the permission of FTB Utilities.
Normally, the file serverfile/local/ftbutilities/ranks.txt is generated to set the permissions, but it is not generated when using Mohist.
I want to use LuckPerms to set the permissions of FTB Utilities, but some of them can only be set in ranks.txt.
Example: ftbutilities.homes.coldown: 0s
In LuckPerms, I can only set it to true/false, so I have to set it in ranks.txt.

Version
mohist-1.12.2-197-server

Mod
FTBUtilities-5.4.1.130
FTBLib-5.4.7.2

Translated with www.DeepL.com/Translator (free version)

**Comment by FullGreenGN** [comment]
@Mgazul 
Pls patch this its very important for me
Thx
