### ISSUE TITLE
Mixin-related error connected to fabrication

### ISSUE THREAD

**Issue by Sunconure11** [Teneted/Tenet#1104]
https://pastebin.com/GHB2M1f4

**Comment by NocturnalSergal** [comment]
From what i can see in that log, its not related to bees at all, but is related to SpongeForge, which there is no 1.16.5 version of nor is there one compatible with Mohist as far as i know.

**Comment by Sunconure11** [comment]
https://pastebin.com/qEnQzS4U

Still getting it.
