### ISSUE TITLE
Piglins not trading

### ISSUE THREAD

**Issue by tandpfun** [Teneted/Tenet#1107]
Piglins are not trading. You can give them gold but they will never drop anything and will keep holding gold.

Mohist version 1.16.5-414 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.0)

Config is default, no mods or plugins installed.

**Comment by SilentStarling** [comment]
That's been fixed in an updated version. I'm on 427 and they're trading correctly again

**Comment by semenishchev** [comment]
> Piglins are not trading. You can give them gold but they will never drop anything and will keep holding gold.
> 
> Mohist version 1.16.5-414 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.0)
> 
> Config is default, no mods or plugins installed.

Update your mohist to newest version
