### ISSUE TITLE
[1.16.5][mod] electrodynamics crash

### ISSUE THREAD

**Issue by MrLyyy** [Teneted/Tenet#1110]
Crash report
https://paste.ubuntu.com/p/vVSDJk7tFQ/

**Comment by Romaindu35** [comment]
Are you always this bug with latest build ?

**Comment by joaoespanhol** [comment]
issue oudated
![image](https://user-images.githubusercontent.com/22871432/170358048-2dabd6af-6b10-403f-9c23-fdd618921242.png)

**Comment by joaoespanhol** [comment]
@Romaindu35

**Comment by Romaindu35** [comment]
This issue seems fixed, if you have always this problem, please open new issue.
