### ISSUE TITLE
[1.12.2] Encountered an unexpected exception on world loading

### ISSUE THREAD

**Issue by ruslanzelinskyy** [Teneted/Tenet#1112]
[12:16:52 INFO]: "Preparing level "world""
[12:16:54 ERROR]: Encountered an unexpected exception
[12:16:54 ERROR]: This crash report has been saved to: /data/./crash-reports/crash-2021-03-27_12.16.54-server.txt

crash-report:
---- Mohist Crash Report ----

WARNING: coremods are present:
  B3M_CorePlugin (UTILS_B3M-1.12.2-17.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  TransformerLoader (COMPUTERS_OpenComputers-MC1.12.2-1.7.5.192.jar)
  AdvancedRocketryPlugin (SPACE_AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  Inventory Tweaks Coremod (UTILS_InventoryTweaks-1.63.jar)
  ForgelinPlugin (_magneticraft_Forgelin-1.8.3.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (_core_optimization_foamfix-0.10.11-1.12.2.jar)
  MekanismCoremod (IC_CORE_Mekanism-1.12.2-9.8.3.390.jar)
Contact their authors BEFORE contacting forge

Time: 3/27/21 12:21 PM
Description: Exception in server tick loop

java.lang.VerifyError: Inconsistent stackmap frames at branch target 536
Exception Details:
  Location:
    net/minecraft/world/WorldServer.func_72835_b()V @526: ifnull
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @526
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', long, long_2nd, integer }
    stack: { 'net/minecraft/world/WorldServer', 'net/minecraft/village/VillageCollection' }
  Stackmap Frame:
    bci: @536
    flags: { }
    locals: { 'net/minecraft/world/WorldServer', long, long_2nd, integer }
    stack: { }
  Bytecode:
    0x0000000: 2ab7 0257 2ab6 025b b602 5e99 0017 2ab6
    0x0000010: 0262 b202 68a5 000d 2ab6 025b b202 68b6
    0x0000020: 026c 2ab4 00ba b602 70b6 0275 2ab6 0278
    0x0000030: 9900 2e2a b602 7c13 027e b602 8499 001d
    0x0000040: 2ab4 019b b602 8714 0288 6140 2ab4 019b
    0x0000050: 1f1f 1402 8871 65b6 028d 2ab6 0290 2ab4
    0x0000060: 0293 1302 95b6 0298 2ab4 019b b602 9b40
    0x0000070: 2ab6 027c 1302 9db6 0284 9900 a12a b401
    0x0000080: 9bb6 02a1 b202 a7a5 0094 2ab4 02aa 9a00
    0x0000090: 0a2a b402 ad99 0086 2ab4 02b0 b902 b301
    0x00000a0: 009e 007a 2ab4 02b7 b402 bdb9 02c3 0100
    0x00000b0: 572a b400 792a 2ab4 02aa 9900 1b2a b402
    0x00000c0: c709 9499 0012 1f2a b402 c771 0994 9a00
    0x00000d0: 0704 a700 0403 2ab4 02ad 9900 1b2a b402
    0x00000e0: ca09 9499 0012 1f2a b402 ca71 0994 9a00
    0x00000f0: 0704 a700 0403 2ab4 019b b602 9b14 02cb
    0x0000100: 7109 949a 0007 04a7 0004 03b6 02d0 572a
    0x0000110: b402 b7b4 02bd b902 d301 002a b402 b7b4
    0x0000120: 02d6 b902 c301 0057 2ab4 0293 1302 d8b6
    0x0000130: 02db 2ab4 00cf b902 e001 0057 2a0c b602
    0x0000140: e43e 1d2a b602 e79f 0008 2a1d b602 ea2a
    0x0000150: b401 9b2a b401 9bb6 029b 0a61 b602 ed2a
    0x0000160: b602 7c13 027e b602 8499 000f 2a2a 2ab6
    0x0000170: 02f0 b802 f6b6 02f9 2a2a b402 9313 02fb
    0x0000180: b602 db2a b402 b7b4 02fe b902 c301 0057
    0x0000190: 2a03 b603 0257 2ab4 02b7 b402 feb9 02d3
    0x00001a0: 0100 2ab4 0293 1303 04b6 02db 2ab4 02b7
    0x00001b0: b403 07b9 02c3 0100 572a b603 0a2a b402
    0x00001c0: b7b4 0307 b902 d301 002a b402 9313 030c
    0x00001d0: b602 db2a b402 b7b4 030f b902 c301 0057
    0x00001e0: 2ab4 00b6 b603 122a b402 b7b4 030f b902
    0x00001f0: d301 002a b402 9313 0314 b602 db2a b402
    0x0000200: b7b4 0317 b902 c301 0057 2ab4 0130 c600
    0x0000210: 0a2a b401 30b6 031a 2ab4 0080 b603 1d2a
    0x0000220: b402 b7b4 0317 b902 d301 002a b402 9313
    0x0000230: 031f b602 db2a b402 b7b4 0322 b902 c301
    0x0000240: 0057 2ab4 00d4 2ab6 0325 b603 282a b400
    0x0000250: 97b9 032c 0100 3a04 1904 b903 3101 0099
    0x0000260: 001b 1904 b903 3501 00c0 011d 3a05 1905
    0x0000270: 2ab6 0325 b603 28a7 ffe1 2ab4 02b7 b403
    0x0000280: 22b9 02d3 0100 2ab4 0293 b603 382a b402
    0x0000290: b7b4 033b b902 c301 0057 2ab7 033e 2ab4
    0x00002a0: 02b7 b403 3bb9 02d3 0100 2ab4 02b7 b403
    0x00002b0: 41b9 02c3 0100 572a b601 d6b6 0344 2ab4
    0x00002c0: 02b7 b403 41b9 02d3 0100 b1            
  Stackmap Table:
    same_frame(@34)
    same_frame(@90)
    same_frame(@94)
    append_frame(@152,Long)
    full_frame(@213,{Object[#2],Long},{Object[#118],Object[#2]})
    full_frame(@214,{Object[#2],Long},{Object[#118],Object[#2],Integer})
    full_frame(@245,{Object[#2],Long},{Object[#118],Object[#2],Integer})
    full_frame(@246,{Object[#2],Long},{Object[#118],Object[#2],Integer,Integer})
    full_frame(@266,{Object[#2],Long},{Object[#118],Object[#2],Integer,Integer})
    full_frame(@267,{Object[#2],Long},{Object[#118],Object[#2],Integer,Integer,Integer})
    same_frame(@283)
    append_frame(@335,Integer)
    same_frame(@376)
    same_frame_extended(@536)
    append_frame(@600,Object[#814])
    chop_frame(@634,1)

	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:354)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Mohist version: 1.12.2-198
	Operating System: Linux (amd64) version 4.19.128-microsoft-standard
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 379015600 bytes (361 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 3 total; -XX:+UseG1GC -Xms1G -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	CraftBukkit Information: 
   Running: Mohist version git-Mohist-1.12.2-198 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE Signal Dispatcher: [], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], RUNNABLE DestroyJavaVM: [], WAITING Mohist Async Task Handler Thread - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING PR RoutingThread #1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:550), mrtjp.projectred.transportation.TableUpdateThread.run(router.scala:455)], WAITING TerminalConsoleWriter - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442), com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77), org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:29), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], TIMED_WAITING Ender IO Scheduler: [java.lang.Thread.sleep(Native Method), crazypants.enderio.base.scheduler.Scheduler.run(Scheduler.java:41)], WAITING PR RoutingThread #3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:550), mrtjp.projectred.transportation.TableUpdateThread.run(router.scala:455)], TIMED_WAITING Mohist Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:95)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)], RUNNABLE Server console handler: [java.io.FileInputStream.readBytes(Native Method), java.io.FileInputStream.read(FileInputStream.java:255), java.io.BufferedInputStream.fill(BufferedInputStream.java:246), java.io.BufferedInputStream.read(BufferedInputStream.java:265), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:245), jline.internal.InputStreamReader.read(InputStreamReader.java:257), jline.internal.InputStreamReader.read(InputStreamReader.java:194), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126), jline.console.ConsoleReader.readLineSimple(ConsoleReader.java:3228), jline.console.ConsoleReader.readLine(ConsoleReader.java:2441), jline.console.ConsoleReader.readLine(ConsoleReader.java:2372), jline.console.ConsoleReader.readLine(ConsoleReader.java:2360), jline.console.ConsoleReader.readLine(ConsoleReader.java:2348), net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:125)], WAITING PR RoutingThread #2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:550), mrtjp.projectred.transportation.TableUpdateThread.run(router.scala:455)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:97)], RUNNABLE Netty Epoll Server IO #1: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:235), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:252), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:27), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:121), net.minecraft.crash.CrashReport.<init>(CrashReport.java:42), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659), java.lang.Thread.run(Thread.java:748)], WAITING PR RoutingThread #0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.park(LockSupport.java:175), java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039), java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:550), mrtjp.projectred.transportation.TableUpdateThread.run(router.scala:455)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:235), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:252), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], RUNNABLE Netty Epoll Server IO #2: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:235), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:252), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)],}
   
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version                  | Source                                                              | Signature                                |
	|:------ |:------------------------- |:------------------------ |:------------------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                   | minecraft.jar                                                       | None                                     |
	| LCHIJA | mcp                       | 9.42                     | minecraft.jar                                                       | None                                     |
	| LCHIJA | mohist                    | 1.12.2-198               | mohist.jar                                                          | None                                     |
	| LCHIJA | FML                       | 8.0.99.99                | mohist-1.12.2-198-server.jar                                        | None                                     |
	| LCHIJA | forge                     | 14.23.5.2855             | mohist-1.12.2-198-server.jar                                        | None                                     |
	| LCHIJA | advancedrocketrycore      | 1                        | minecraft.jar                                                       | None                                     |
	| LCHIJA | foamfixcore               | 7.7.4                    | minecraft.jar                                                       | None                                     |
	| LCHIJA | opencomputers|core        | 1.7.5.192                | minecraft.jar                                                       | None                                     |
	| LCHIJA | charset                   | 0.5.6.5                  | _Charset-Lib-0.5.6.5.jar                                            | None                                     |
	| LCHIJA | jei                       | 4.16.1.302               | _core_jei.jar                                                       | None                                     |
	| LCHIJA | forestry                  | 5.8.2.422                | AUTOMATION_forestry_1.12.2-5.8.2.422.jar                            | None                                     |
	| LCHIJA | jeibees                   | 0.9.0.5                  | _core_jeibees-0.9.0.5-mc1.12.2.jar                                  | None                                     |
	| LCHIJA | foamfix                   | 0.10.11-1.12.2           | _core_optimization_foamfix-0.10.11-1.12.2.jar                       | None                                     |
	| LCHIJA | redstoneflux              | 2.1.1                    | _Draconic-Evolution_RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
	| LCHIJA | codechickenlib            | 3.2.3.358                | _PROJECT_RED_DRACONIC_CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | brandonscore              | 2.4.19                   | _Draconic-Evolution_BrandonsCore-1.12.2-2.4.19.214-universal.jar    | None                                     |
	| LCHIJA | endercore                 | 1.12.2-0.5.76            | _enderio_EnderCore-1.12.2-0.5.76.jar                                | None                                     |
	| LCHIJA | baubles                   | 1.5.2                    | _MAGICK_CORE_THAUMCRAFT_Baubles-1.12-1.5.2.jar                      | None                                     |
	| LCHIJA | forgelin                  | 1.8.3                    | _magneticraft_Forgelin-1.8.3.jar                                    | None                                     |
	| LCHIJA | numina                    | 1.12.2-1.0.38            | _modpowsuits_Numina-1.12.2-1.0.38.jar                               | None                                     |
	| LCHIJA | forgemultipartcbe         | 2.6.2.83                 | _PROJECT_RED_ForgeMultipart-1.12.2-2.6.2.83-universal.jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe             | 2.6.2.83                 | _PROJECT_RED_ForgeMultipart-1.12.2-2.6.2.83-universal.jar           | None                                     |
	| LCHIJA | minecraftmultipartcbe     | 2.6.2.83                 | _PROJECT_RED_ForgeMultipart-1.12.2-2.6.2.83-universal.jar           | None                                     |
	| LCHIJA | mrtjpcore                 | 2.1.4.43                 | _PROJECT_RED_MrTJPCore-1.12.2-2.1.4.43-universal.jar                | None                                     |
	| LCHIJA | libvulpes                 | 0.4.2.-75                | _space_LibVulpes-1.12.2-0.4.2-75-universal.jar                      | None                                     |
	| LCHIJA | thutcore                  | 5.21.0                   | _thutcore-1.12.2-5.21.0.jar                                         | None                                     |
	| LCHIJA | thutcore_compat           | 1.0                      | _thutcore-1.12.2-5.21.0.jar                                         | None                                     |
	| LCHIJA | mantle                    | 1.12-1.3.3.55            | _tinker_Mantle.jar                                                  | None                                     |
	| LCHIJA | flansmod                  | 5.7.2                    | _titanpack_Flan's+Mod.jar                                           | None                                     |
	| LCHIJA | mechapartspack            | 5.7.2                    | _titanpack_Mecha+Parts-Content+Pack.jar                             | None                                     |
	| LCHIJA | simplepartspack           | 5.7.2                    | _titanpack_Simple+Parts-Content+Pack.jar                            | None                                     |
	| LCHIJA | binniecore                | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | binniedesign              | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | genetics                  | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | botany                    | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | extrabees                 | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | extratrees                | 2.5.1.203                | AUTOMATION_binnie-mods-1.12.2-2.5.1.203.jar                         | None                                     |
	| LCHIJA | thaumcraft                | 6.1.BETA26               | MAGICK_CORE_Thaumcraft-1.12.2-6.1.BETA26.jar                        | None                                     |
	| LCHIJA | enderio                   | 5.2.66                   | AUTOMATION_EnderIO-base-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiobase               | 5.2.66                   | AUTOMATION_EnderIO-base-1.12.2-5.2.66.jar                           | None                                     |
	| LCHIJA | enderiomachines           | 5.2.66                   | AUTOMATION_EnderIO-machines-1.12.2-5.2.66.jar                       | None                                     |
	| LCHIJA | magneticraft              | 2.7.0                    | AUTOMATION_Magneticraft_1.12-2.8.3-dev.jar                          | None                                     |
	| LCHIJA | opencomputers             | 1.7.5.192                | COMPUTERS_OpenComputers-MC1.12.2-1.7.5.192.jar                      | None                                     |
	| LCHIJA | tconstruct                | 1.12.2-2.13.0.183        | IC_CORE__tinker_TConstruct.jar                                      | None                                     |
	| LCHIJA | titanpack                 | 5.7.2                    | IC_CORE__titanpack_Titan-Content+Pack.jar                           | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-7             | IC_CORE_appliedenergistics2-rv6-stable-7.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | backpack                  | 3.0.2                    | IC_CORE_backpack-3.0.2-1.12.2.jar                                   | None                                     |
	| LCHIJA | compactmachines3          | 3.0.18                   | IC_CORE_compactmachines3-1.12.2-3.0.18-b278.jar                     | None                                     |
	| LCHIJA | draconicevolution         | 2.3.27                   | IC_CORE_Draconic-Evolution-1.12.2-2.3.27.353-universal.jar          | None                                     |
	| LCHIJA | ironchest                 | 1.12.2-7.0.67.844        | IC_CORE_ironchest-1.12.2-7.0.72.847.jar                             | None                                     |
	| LCHIJA | mekanism                  | 1.12.2-9.8.3.390         | IC_CORE_Mekanism-1.12.2-9.8.3.390.jar                               | None                                     |
	| LCHIJA | mekanismgenerators        | 1.12.2-9.8.3.390         | IC_CORE_MekanismGenerators-1.12.2-9.8.3.390.jar                     | None                                     |
	| LCHIJA | mekanismtools             | 1.12.2-9.8.3.390         | IC_CORE_MekanismTools-1.12.2-9.8.3.390.jar                          | None                                     |
	| LCHIJA | powersuits                | 1.12.2-1.0.46            | IC_CORE_ModularPowersuits-1.12.2-1.0.46.jar                         | None                                     |
	| LCHIJA | nuclearcraft              | 2.18y                    | IC_CORE_NuclearCraft-2.18y-1.12.2.jar                               | None                                     |
	| LCHIJA | projectred-core           | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-Base.jar                        | None                                     |
	| LCHIJA | projectred-compat         | 1.0                      | IC_CORE_ProjectRed-1.12.2-4.9.4.120-compat.jar                      | None                                     |
	| LCHIJA | projectred-integration    | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
	| LCHIJA | projectred-transmission   | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-integration.jar                 | None                                     |
	| LCHIJA | projectred-fabrication    | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-fabrication.jar                 | None                                     |
	| LCHIJA | projectred-illumination   | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-lighting.jar                    | None                                     |
	| LCHIJA | projectred-expansion      | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-mechanical.jar                  | None                                     |
	| LCHIJA | projectred-relocation     | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-mechanical.jar                  | None                                     |
	| LCHIJA | projectred-transportation | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-mechanical.jar                  | None                                     |
	| LCHIJA | projectred-exploration    | 4.9.4.120                | IC_CORE_ProjectRed-1.12.2-4.9.4.120-world.jar                       | None                                     |
	| LCHIJA | thaumicenergistics        | 2.2.3                    | MAGICK_CORE_thaumicenergistics-2.2.4.jar                            | None                                     |
	| LCHIJA | divinerpg                 | 1.7.1                    | PVE_DivineRPG-1.7.1.jar                                             | None                                     |
	| LCHIJA | modernweaponspack         | 5.7.2                    | PVE_Modern+Warfare-Content+Pack-1.12.2-5.7.2.jar                    | None                                     |
	| LCHIJA | advancedrocketry          | 1.7.0.-232               | SPACE_AdvancedRocketry-1.12.2-1.7.0-232-universal.jar               | None                                     |
	| LCHIJA | B3M                       | 1.12.2-17                | UTILS_B3M-1.12.2-17.jar                                             | None                                     |
	| LCHIJA | buildinggadgets           | 2.8.4                    | UTILS_BuildingGadgets-2.8.4.jar                                     | None                                     |
	| LCHIJA | chickenchunks             | 2.4.2.74                 | UTILS_ChickenChunks-1.12.2-2.4.2.74-universal.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | craftingtweaks            | 8.1.9                    | UTILS_CraftingTweaks_1.12.2-8.1.9.jar                               | None                                     |
	| LCHIJA | extrautils2               | 1.0                      | UTILS_extrautils2-1.12-1.9.9.jar                                    | None                                     |
	| LCHIJA | gravestone                | 1.10.3                   | UTILS_gravestone-1.10.3.jar                                         | None                                     |
	| LCHIJA | waila                     | 1.8.26                   | UTILS_Hwyla-1.8.26-B41_1.12.2.jar                                   | None                                     |
	| LCHIJA | inventorytweaks           | 1.63+release.109.220f184 | UTILS_InventoryTweaks-1.63.jar                                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | journeymap                | 1.12.2-5.7.1             | UTILS_journeymap-1.12.2-5.7.1.jar                                   | None                                     |
	| LCHIJA | jecalculation             | 1.12.2-3.2.5             | UTILS_JustEnoughCalculation-1.12.2-3.2.5.jar                        | None                                     |
	| LCHIJA | naturescompass            | 1.8.5                    | UTILS_NaturesCompass-1.12.2-1.8.5.jar                               | None                                     |
	| LCHIJA | thuttech                  | 6.1.6                    | UTILS_thuttech-1.12.2-6.1.6.jar                                     | None                                     |
	| LCHIJA | trashslot                 | 8.4.10                   | UTILS_TrashSlot_1.12.2-8.4.10.jar                                   | None                                     |
	| LCHIJA | wawla                     | 2.6.275                  | UTILS_Wawla-1.12.2-2.6.275.jar                                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | orelib                    | 3.6.0.1                  | _dynamicsurroundings_OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | matteroverdrive           | 0.7.0.0                  | IC_CORE_MatterOverdrive-1.12.2-0.7.1.0-universal.jar                | None                                     |

	Loaded coremods (and transformers): 
B3M_CorePlugin (UTILS_B3M-1.12.2-17.jar)
  sedridor.B3M.core.B3M_Transformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TransformerLoader (COMPUTERS_OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
AdvancedRocketryPlugin (SPACE_AdvancedRocketry-1.12.2-1.7.0-232-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Inventory Tweaks Coremod (UTILS_InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
ForgelinPlugin (_magneticraft_Forgelin-1.8.3.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (_core_optimization_foamfix-0.10.11-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MekanismCoremod (IC_CORE_Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                 An unsupported base software is installed: 'Mohist'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /data/libraries/net/minecraft/1.12.2/minecraft_server.1.12.2.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)

**Comment by ruslanzelinskyy** [comment]
forge works fine with same setup

**Comment by FranklinMCA** [comment]
> forge works fine with same setup

What forge version do u using?

**Comment by Mgazul** [comment]
#1206
