### ISSUE TITLE
Crash server 1.16.5

### ISSUE THREAD

**Issue by avescarelo** [Teneted/Tenet#1114]
I used a mass of dynamite trolleys at one point and the server crashed

log: https://gist.github.com/avescarelo/02e0ffe1f442a11cfe368bde618333bc

**Comment by joaoespanhol** [comment]
there is no such problem with the latest mohist version

**Comment by joaoespanhol** [comment]
@Romaindu35 , close ticket please.

**Comment by Romaindu35** [comment]
This issue seems fixed, if you have always this problem, please open new issue.
