### ISSUE TITLE
[1.16.5] Plug-in multiverse-core not working when import world

### ISSUE THREAD

**Issue by jeremyVanackere** [Teneted/Tenet#1116]

**Comment by Areenyaw** [comment]
Hello,

I have the same issue. I can't import a map in my server with multiverse core.
Mohist version : 1.6.5 #443
Multiverse-core version : 4.2.2

When I import the map, the new world is generated. This new world not like map origin, it's like executing a command to create a new world.

I try to bypass this issue, by create a new world and replace the file in the folder of a new world. And I replace properties of my import world in "worlds.yml" in plugins > Multiverse-Core, but it doesn't work too. Chunks charged on my world are creating but outside chunks, it's a new world generation.

![Capture d’écran 2021-04-03 073229](https://user-images.githubusercontent.com/81844741/113469568-c8134c80-944e-11eb-99cc-33fceb47c335.png)
