### ISSUE TITLE
1.16.5 Unhandled Exception Crash with Immersive Portals

### ISSUE THREAD

**Issue by digitaltrucker** [Teneted/Tenet#1124]
Mohist 436

[crash-2021-03-30_01.05.57-server.txt](https://github.com/Mohist-Community/Mohist/files/6226522/crash-2021-03-30_01.05.57-server.txt)

**Comment by Romaindu35** [comment]
Files not found (crash report)

**Comment by Romaindu35** [comment]
(You can reopen new issue if you have always this bug)
