### ISSUE TITLE
[1.12] Tile Entities not unloading

### ISSUE THREAD

**Issue by Asek3** [Teneted/Tenet#1125]
Before /rtp:
https://i.ibb.co/FbZS5zC/Qr-Mr-S94d-Nz-U.jpg
After /rtp:
https://i.ibb.co/yPDgL4r/p-FIR1ycn-ZI4.jpg

Chunks are not unloading. With big online this causes very big problems with tps

**Comment by BlackAce21** [comment]
Can confirm this as well. I was coding a spigot plugin to handle chunk loading for my servers launch and went to test on Mohist only to discover....nothing is unloading. I fiddled with a few settings, including chunk-gc and disableforcechunksystem thinking this might have something to do with it as a compatibility fix of some kind. Nothing seems to change the behavior. Is this just a consequence of some under the hood stuff to force compatibility? Is this a proper bug that will get addressed? Would really like to know.

**Comment by ProsperCraft** [comment]
This is a major issue that we have been battling, it crippled our server before we figured out we could add clearlag to run on a timer to clean up, but this shouldn't have to be done, please fix this bug :)

**Comment by KR33PYK1NG** [comment]
It has been reported that this issue occurs somewhere between builds 145-180.
For now you should be safe to use <145, if you want.

**Comment by Malachiel87** [comment]
Issue still present on #244, it seem chunks will never unload, and using lagclear tool chunkunload it help a little, but chunks  will keep to load and load without be never unloaded, as you can see on my timings chunk keep loaded to infinite and the only way is using laggclear unloadchunk https://timings.aikar.co/?id=9bb45f82a6814bed8d763a07aef43d37
