### ISSUE TITLE
server crash while running mohist-1.16.5-439-server.jar no mod and plugins.

### ISSUE THREAD

**Issue by Hypocisy** [Teneted/Tenet#1129]
server crash while running mohist-1.16.5-439-server.jar without mod and plugins.
-------------------------------------------------------------------------------
[Latest.log](https://privatebin.net/?00b9a84a1c681150#AV8UNgnic6qzZpG3pRo2Vfv2L98mQHCoaWRiyE5KKvDQ)
-------------------------------------------------------------------------------
Please fix that, it says "Failed to schedule load callback for chunk [23, -7]".
-------------------------------------------------------------------------------
my java version is 
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

**Comment by semenishchev** [comment]
+, 439 is very unstable. My server also crashes without mods and plugins when player uses stonecutter

**Comment by Hypocisy** [comment]
> +, 439 is very unstable. My server also crashes without mods and plugins when player uses stonecutter

yes, you can use [Mohist-1.16.5-437](https://mohistmc.com/builds/1.16.5/mohist-1.16.5-437-server.jar) this version is stable(maybe).

**Comment by Romaindu35** [comment]
I have the same problem : 
when i start the server it crashes when generating the world, yet i had just done a clean install.
I have the latest build (439)
I don't have mod or plugin

**Comment by Scrulius** [comment]
+1

**Comment by Mgazul** [comment]
Fixed
