### ISSUE TITLE
[1.7.10] SpecialSource and LuckPerms Legacy build bug

### ISSUE THREAD

**Issue by nkomarn** [Teneted/Tenet#113]
LuckPerms Legacy release, which is supposed to be compatible with 1.7.x, doesn't work on Mohist because of an old version of SpecialSource. On [LuckPerms' wiki](https://github.com/lucko/LuckPerms/wiki/Installation), there's a guide for updating SpecialSource manually on Thermos to get LuckPerms to run:

> Cauldron, Thermos, etc
> If you're using Cauldron, Thermos or any other Bukkit-Forge hack, you may encounter errors when trying to load LuckPerms. This is not a LuckPerms issue - but rather due to a bug in the server.
> 
> These issues have been reported to the respective projects, however none are currently being maintained, so this issue will (most likely) never be fixed. In the meantime, you can hack around these problems using the steps outlined below.
> 
> (I offer absolutely no support for these fixes.)
> 
> Navigate to the libraries/net/md-5/SpecialSource/1.7-SNAPSHOT directory
> Delete the SpecialSource-1.7-SNAPSHOT.jar file
> Download SpecialSource v1.7.4 from https://repo1.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
> Copy the jar file to the libraries/net/md-5/SpecialSource/1.7-SNAPSHOT directory
> Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar
> Start up server. If it stops immediately, you have renamed the SpecialSource wrong.

However, this does not work on Mohist because SpecialSource is redownloaded on startup if it's replaced. So either SpecialSource has to be updated to 1.7.4 in Mohist or some kind of patch needs to be implemented to support LuckPerms, because I see this as pretty important ✨

**Comment by Mgazul** [comment]
You can turn off the update detection and replace the 1.7.4 you need
