### ISSUE TITLE
[1.16.5] Multiverse can not work correctly

### ISSUE THREAD

**Issue by SukiYume** [Teneted/Tenet#1133]
The Multiverse-Core read the path of `mohist` as its root path. After a new world created, the world list is like
```
> mv list
[23:14:09 INFO]: ====[ Multiverse World List ]====
[23:14:09 INFO]: world - NORMAL
[23:14:09 INFO]: DIM1 - UNLOADED
[23:14:09 INFO]: DIM-1 - UNLOADED
> mv import DIM1 end
[23:14:23 INFO]: FAILED.
[23:14:23 INFO]: That world folder does not exist. These look like worlds to me:
[23:14:23 INFO]: 
```
As the DIM1 and DIM-1 are not in the root path, the import cannot work.

If a world placed outside, mv import will not work, it will create a new world based on the seed of the original world.

If a nether created externally and then replace the map, even if the portal point is set, a DIM-1 will still be generated in the original world folder, and the externally created nether cannot be used normally, the map will also be refreshed.

**Comment by Scrulius** [comment]
+1

**Comment by MouniaTea** [comment]
Same

**Comment by Shawiizz** [comment]
Please provide useful informations instead of saying "same" or "+1". Thanks :)

**Comment by Areenyaw** [comment]
To bypass this issue, you can replace folder : data, poi and region of your old nether/end in your folder DIM1/DIM-1. _(not replace uuid.dat)_ But yes, I can't import new maps too.

**Comment by Romaindu35** [comment]
Same #1116
