### ISSUE TITLE
[1.16.5] Incorrect operation of the FabledSkyBlock plugin

### ISSUE THREAD

**Issue by Quenteez** [Teneted/Tenet#1134]
**----------------------------------------------------------------------------------------------**

### For English-speaking developers:

**The first part:**

When creating an island (/is create), usually the plugin sends the player to his island without any problems. But on the Mohist 1.16.5 kernel, this doesn't work correctly. I can't say exactly what is causing the error, but I enter /is create, then an island is created. The plugin tries to send me there by teleportation, but something goes wrong (it should be noted that there is a world where the server spawn is located-this is "SkyClassic", and there is a world with islands - "island_normal_world"). During teleportation, I find myself in SkyClassic (where I was originally) at unknown coordinates (roughly speaking, in the void) and fall. The same thing happens even if I am initially in island_normal_world.

The situation is similar with /is home - the command to teleport to your island, /is tp nick - the command to teleport to the player's island.

What is most annoying is that I can't move to the hellish world of skyblock - island_nether_world and to end - island_end_world. I'm just not allowed there and the plugin gives the same message that "the island is gone".

Apparently there are some problems with the methods of teleportation and teleportation between worlds, which is why the plugin does not really understand what to do. It is also true that when you re-enter /is home - it sends me to your island, this is already interesting. But with teleportation to island_nether_world and island_end_world, this doesn't work.

**The second part:**

Islands are usually protected from interference from other players, so other players there can not break / put blocks, open chests, etc. All this works, but half, if you take into account the mod part, because mod chests can be opened by outsiders, you can even poison the foliage with silkworms from ex nihilo and you can collect barrels/sieves/crucibles and everything like that.

If it is possible to fix all this in the kernel, then I would be very happy.

P.S. I would like to add that there are errors with OptiFine on the server side. And also a huge request to release more EssentialsX builds, namely addons: EssentialsXSpawn, EssentialsXProtect and others.

**----------------------------------------------------------------------------------------------**

### Для русскоговорящих разработчиков:

**Первая часть:**

При создании острова (/is create), обычно плагин отправляет игрока на его остров без проблем. Но на ядре Mohist 1.16.5 это работает неправильно. Не могу сказать точно, из-за чего происходит ошибка, но я ввожу /is create, затем создается остров. Плагин меня пытается туда отправить телепортацией, но что-то происходит не так (следует отметить, что есть мир, где расположен спавн сервера - это "SkyClassic", а есть мир с островами - это "island_normal_world"). Во время телепортации я оказываюсь в SkyClassic (где был изначально) на неизвестных координатах (грубо говоря в пустоте) и падаю. Тоже самое происходит даже если я изначально нахожусь в island_normal_world.

Аналогичная ситуация с /is home - команда для телепортации на свой остров, /is tp nick - команда для телепортации на остров игрока.

Что больше всего напрягает, так это то, что я не могу перемещаться в адский мир скайблока - island_nether_world и в эндер - island_end_world. Меня туда просто не пускает и плагин выдаёт то же самое сообщение о том, что "остров пропал".

Видимо есть какие-то проблемы с методами телепортации и телепортации между мирами, из-за чего плагин не особо понимает что делать. Справедливо также, что при повторном вводе /is home - меня отправляет на свой остров, это уже интересно. Но с телепортацией в island_nether_world и  island_end_world это не работает.

**Вторая часть:**

Острова обычно защищены от вмешательства других игроков, следовательно другие игроки там не могут ломать/ставить блоки, открывать сундуки и т.п.. Всё это работает, но наполовину, если учесть модовую часть, т.к. модовые сундуки можно открывать посторонним, даже можно отравлять листву шелкопрядом из ex nihilo и можно набирать бочки/сита/тигели и все в этом роде.

Если возможно это все исправить в ядре, то я был бы очень рад.

P.S. Хотел бы ещё добавить, что возникают ошибки с OptiFine на серверной стороне. А также огромная просьба выпустить ещё билды EssentialsX, а именно аддоны: EssentialsXSpawn, EssentialsXProtect и прочие.

**Comment by Romaindu35** [comment]
Can you send logs ?

**Comment by Quenteez** [comment]
https://pastebin.com/raw/eS1S0MpJ

**Comment by Quenteez** [comment]
Fixed
