### ISSUE TITLE
All the chests in world are gone with the wind~

### ISSUE THREAD

**Issue by dreamaximum** [Teneted/Tenet#1136]
Some chests in player's main chunks to live are invisible unless get close to them. And all items in these chests are disappeared, too.
However, it could also blame to the Multiverse-Core.....I‘m just guessing.

**Comment by muriplz** [comment]
It happened to me too and I dont have multiverse/any other plugin with similar function. Also wiped out of items .Mohist 441

**Comment by dreamaximum** [comment]
Maybe the chunk files are broken. That's a horrible bug.

**Comment by KR33PYK1NG** [comment]
What version are we talking about? I do not encounter this bug on my 1.16.5 servers.

**Comment by muriplz** [comment]
i dont know what more info to give, there is no log errors or anything. With the latest of mohist right now the server crashes when you open this kind of chests for me

**Comment by dreamaximum** [comment]
This event happened on 1.16.5 #436

**Comment by dreamaximum** [comment]
Add in 9 days : 
Maybe it's the problem of the mod "MrCrayfish's Gun"

**Comment by muriplz** [comment]
I still encounter this issue on chunks that arent being used frecuently, I use mohist 457 and I tried opening the world on singleplayer and this does not happen. I use the Create mod and some plugins (LuckPerms, GriefDefender, AdvancedTeleport, MineableSpawners and a custom plugin)

**Comment by Romaindu35** [comment]
This seems fix in latest update, else open new issue
