### ISSUE TITLE
[1.16.5] ExNihilo clientcrash smelting Lava

### ISSUE THREAD

**Issue by darksoon** [Teneted/Tenet#1137]
used mod: [Click me](https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia)

place a Torch, on top the fired crucible and rightclick with cobblestone. SP + forgeserver = works. On mohist = client crash. when all cobble are smelt into lava player can rejoin.

[crash-2021-04-01_18.23.28-client.txt](https://github.com/Mohist-Community/Mohist/files/6245039/crash-2021-04-01_18.23.28-client.txt)

![Screenshot_1](https://user-images.githubusercontent.com/2123049/113328366-7ec2e000-931c-11eb-969a-732adfa84a9f.png)

**Comment by Mgazul** [comment]
Can you provide server logs, I don’t have time to test it myself

**Comment by darksoon** [comment]
sure. at line 91832 ill give me the items, after insert cobble = client crash
[latest.zip](https://github.com/Mohist-Community/Mohist/files/6249196/latest.zip)

**Comment by darksoon** [comment]
hm maybe this is the same bug?

https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/153

**Comment by Romaindu35** [comment]
This issue is close https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/153
So, I think that this issue is also fix (You can reopen new issue if the bug is not fix)
