### ISSUE TITLE
1.16.5 Proxy Not Working

### ISSUE THREAD

**Issue by jrsalata** [Teneted/Tenet#1146]
I am currently running a fork of Bungeecord called Waterfall, (release 403) to connect all of my servers together.  Using the ViaVersion plugins, I am able to connect to a modded 1.12.2 Mohist server from a lobby (1.16.5) and it works just fine.  I am currently trying to add a new 1.16.5 Mohist Server (version: Mohist version 1.16.5-443 (MC: 1.16.5)) to this network, but every time someone tries to connect with a modded client with the proper mods and Forge version, the following error pops up:

`[18:14:51` ERROR]: Channels [epicfight:network_manager] rejected vanilla connections
[18:14:51 INFO]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.`

In the Waterfall settings, forge support and ip forwarding are set to true.  In the 1.16.5 Mohist server that is rejecting the connection,  online mode is set to false, bungeecord is set to true.  The config files are set up in the same way I connected the other vanilla servers on this network.  

We removed all mods and it was able to accept the connection, but when we added one mod back, it would reject the connection saying that it was a vanilla connection.  We are using the correct version of Forge with the correct mods for it. 

This is my first issue on here so if it is improperly formatted, let me know and I will fix it.  If any config files or logs are needed, I will be more than happy to provide them.  Thank you for your time!

**Comment by Mgazul** [comment]
This actually has nothing to do with mohist, it is an error caused by the way BC works
