### ISSUE TITLE
在使用velocity进行跨服时，无法正常显示其他玩家皮肤

### ISSUE THREAD

**Issue by Chino081** [Teneted/Tenet#1152]
在使用正版或伪正版时候，进服服务器时在使用velocity跨服无法显示其他玩家的皮肤只能显示自己的。
我在很久前也给velocity开发者反馈过该问题:https://github.com/VelocityPowered/Velocity/issues/205
同时我也在群里反馈过，但在目前1.12.2最新构建版本依旧还是没解决该问题.

**Comment by CraftDream** [comment]
请使用英文便于其他开发者阅读谢谢。

**Comment by Chino081** [comment]
> 请使用英文便于其他开发者阅读谢谢。

我好像解决问题了，最新velocity版本解决该问题了
