### ISSUE TITLE
1.16.5 plugin banitem

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1156]
log error: https://mclo.gs/uzKm8wO
version plugin: https://www.spigotmc.org/resources/banitem-1-7-1-16.67701/
last version

**Comment by darksoon** [comment]
> Could not pass event FurnaceExtractEvent to BanItem v3.0

update to 3.1 works perfect on our server

**Comment by joaoespanhol** [comment]
> > Could not pass event FurnaceExtractEvent to BanItem v3.0
> 
> update to 3.1 works perfect on our server

i go try :)

**Comment by joaoespanhol** [comment]
> > Could not pass event FurnaceExtractEvent to BanItem v3.0
> 
> update to 3.1 works perfect on our server

same problem.

https://mclo.gs/vf1JnSU
