### ISSUE TITLE
Should I be worried?

### ISSUE THREAD

**Issue by HHAgdss** [Teneted/Tenet#116]
![6c856841f097bb311d8b2081aa7a83ea](https://user-images.githubusercontent.com/61666908/75700565-8eec3400-5cb2-11ea-983f-483ca223fcd8.png)

**Comment by Mgazul** [comment]
Tell me what version of OTG you are using

**Comment by HHAgdss** [comment]
OpenTerrainGenerator-1.12.2+-+v6

**Comment by CraftDream** [comment]
Does OTG support forge version of Mohist?
