### ISSUE TITLE
Citizens Plugin incompatibility

### ISSUE THREAD

**Issue by 1636578433** [Teneted/Tenet#1165]
log:https://mclo.gs/utEvKbz
/npc create not work for Mohist
Mohist version:448
Citizens:Citizens-2.0.27-b2281

**Comment by joaoespanhol** [comment]
Plugin 1.16.5

**Comment by joaoespanhol** [comment]
no have is problem.
I am use a version:: Citizens-2.0.27-b2282.jar

![image](https://user-images.githubusercontent.com/22871432/113520433-f5fdab80-958a-11eb-8993-75659b1025e3.png)

**Comment by 1636578433** [comment]
log:https://mclo.gs/drYH66z
i updated to Citizens-2.0.27-b2282 but problem still here

**Comment by joaoespanhol** [comment]
> log:https://mclo.gs/drYH66z
> i updated to Citizens-2.0.27-b2282 but problem still here

send the full server log

**Comment by 1636578433** [comment]
[2021-04-04-1.log](https://github.com/Mohist-Community/Mohist/files/6255301/2021-04-04-1.log)

**Comment by joaoespanhol** [comment]
> [2021-04-04-1.log](https://github.com/Mohist-Community/Mohist/files/6255301/2021-04-04-1.log)

remove mod  journeymap.
Try again :)
