### ISSUE TITLE
[1.16.5] Gravestone/Corpse don't spawn grave/corpse

### ISSUE THREAD

**Issue by immails** [Teneted/Tenet#1167]
[latest.log](https://github.com/Mohist-Community/Mohist/files/6256421/latest.log)
mods: https://i.imgur.com/F7vV1m9.png

Having Mohist 1.16.5. Tested for Gravestone, Corpse mod, VanillaDeathChest. All of these mod didn't spawn grave/coprse/chest on player death in SERVER, but in singleplayer or forge server these mods works fine.

**Comment by Mgazul** [comment]
#878

**Comment by immails** [comment]
dont using carry on
