### ISSUE TITLE
WorldEdit Forge Edition is not working properly in Mohist at 1.16.5.

### ISSUE THREAD

**Issue by ToreOfficial** [Teneted/Tenet#1177]
Mohist Version:mohist-1.16.5-456-server.jar
Problem description: Though the Worldedit has been loaded actually, commands of the Worldedit cannot be used in game. For example, if I use the command "//wand", it will give me a wooden axe in common, but it just display "Please enter /help to get help." It's normal in Single Player Mode.
Mods: Many, but I just use the Worldedit and its CUI in testing.
The download address of Mods: https://www.curseforge.com/minecraft/mc-mods/worldeditcui-forge-edition-3
https://www.curseforge.com/minecraft/mc-mods/worldedit/

**Comment by KR33PYK1NG** [comment]
Duplicate of #748

**Comment by ToreOfficial** [comment]
OK,I see. However, It won't fix recently?
