### ISSUE TITLE
1.16.5  Rats Mod | rats dont do anything

### ISSUE THREAD

**Issue by darksoon** [Teneted/Tenet#1178]
hey there,

the rats from the mod do nothing after taming. on forge server works on mohist they stand still. No error or any respont on the logs or in console

![image](https://user-images.githubusercontent.com/2123049/114085734-09be5000-98b2-11eb-8bde-6896c2fc240d.png)

[Mod](https://www.curseforge.com/minecraft/mc-mods/rats)

**Comment by VeritasSapere51** [comment]
I have experienced the same issue on Mohist 384

**Comment by joaoespanhol** [comment]
i have this mod, my server testing, i no have this problem.

@darksoon  you can't check update mod and mohist please :)

**Comment by joaoespanhol** [comment]
no have this problem Rats mod, last version 
i have using this mod, my server.
@Romaindu35 , close ticket please.

**Comment by Romaindu35** [comment]
This issue seems fixed, if you have always this problem, please open new issue.
