### ISSUE TITLE
Hex Colors Dont Show Up In Chat

### ISSUE THREAD

**Issue by NFKRZZ** [Teneted/Tenet#1179]
HexColors dont show up in chat for the latest build of Mohist anymore. This is with build version 456 1.16.5. No error is thrown either, but DiscordSRV does show that a message has been sent in chat.

**Comment by KR33PYK1NG** [comment]
Can you check which build was the last one to work with hex colors?

**Comment by NFKRZZ** [comment]
i believe build 443 is the last one that works, shows hex colors in chat

**Comment by Mgazul** [comment]
#1877
