### ISSUE TITLE
1.16.5 Error Encoding Packet

### ISSUE THREAD

**Issue by SirRidiculous** [Teneted/Tenet#1182]
I've been having an issue with the combination of a mod called Immersive Portals and a plugin called HaoNick. I've been told that the issue is that Mohist doesn't have a packet for plugins without a dimension parameter, which for some reason this combination of mod and plugin brings out. The server itself is up with no issues. However, when I attempt to log on, it disconnects me. The server log says "Error Encoding Packet" and the disconnection message is: "java.lang.RuntimeException: Missing Dimension null".

Here's the full log.
[latest.log](https://github.com/Mohist-Community/Mohist/files/6289033/latest.log)

**Comment by joaoespanhol** [comment]
has been fixed with last update
@Romaindu35

**Comment by Romaindu35** [comment]
Yes
