### ISSUE TITLE
1.16.5 server freezer

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1187]
LOG: https://mclo.gs/9WARrMa
List mods: https://mclo.gs/9WARrMa

**Comment by KR33PYK1NG** [comment]
I notified the BanItem dev on this one.
He said he's working on it.

**Comment by KR33PYK1NG** [comment]
@joaoespanhol, please try this build and provide us feedback if the issue is gone: https://cdn.discordapp.com/attachments/831905836523716630/831911671118954566/BanItem-3.1.1.jar

**Comment by joaoespanhol** [comment]
same problem.

**Comment by joaoespanhol** [comment]
about the ban item problem, the plugin you offered me, so far it hasn't generated any errors, I'll let it run all day from the modpack server with the players, to be sure.
#1156

**Comment by joaoespanhol** [comment]
> @joaoespanhol, please try this build and provide us feedback if the issue is gone: https://cdn.discordapp.com/attachments/831905836523716630/831911671118954566/BanItem-3.1.1.jar

i go closed ticket, because is work fine, thanks @KR33PY
