### ISSUE TITLE
[1.16.5] Create mod crash

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1188]
[crash-2021-04-10_04.01.15-server.txt](https://github.com/Mohist-Community/Mohist/files/6289878/crash-2021-04-10_04.01.15-server.txt)
when a player stopped a "mechanical bearing", the server crashed. I don't know anything else and i havent been able to reproduce by myself. 
I use Mohist 457 and Create 0.3.1

**Comment by Romaindu35** [comment]
This seems fix in latest update, else open new issue
