### ISSUE TITLE
Main thread crash using "CMI" plug-in

### ISSUE THREAD

**Issue by Kotori0629** [Teneted/Tenet#1192]
Logs:   https://paste.ubuntu.com/p/xwp6Hy4B9y/

**Comment by Kotori0629** [comment]
I branched out Mohist 1.16.5, but did not change the thread. Craftdream says it's a CMI problem.




------------------&nbsp;Original message&nbsp;------------------
From: "Mgazul"; 
Sendtime: Sunday, Apr 11, 2021 11:52 PM
To: "Mohist-Community/Mohist"; 
Cc: "@***@***.***>; "Author"; 
Subject: Re: [Mohist-Community/Mohist] Main thread crash using &quot;CMI&quot; plug-in (#1192)





 
Reopened #1192.

**Comment by Mgazul** [comment]
This has nothing to do with the thread, there is an error in the holographic function of CMI

**Comment by Kotori0629** [comment]
OK. thank you.




------------------&nbsp;Original message&nbsp;------------------
From: "Mgazul"; 
Sendtime: Monday, Apr 12, 2021 0:01 AM
To: "Mohist-Community/Mohist"; 
Cc: "@***@***.***>; "Author"; 
Subject: Re: [Mohist-Community/Mohist] Main thread crash using &quot;CMI&quot; plug-in (#1192)





 
This has nothing to do with the thread, there is an error in the holographic function of CMI
