### ISSUE TITLE
Ice & Fire Server Crash

### ISSUE THREAD

**Issue by VeritasSapere51** [Teneted/Tenet#1196]
The server crashes whenever encountering a dragon roost, dragon cave, hydra cave or Myrmix Colony (structures with specific mobs) using Mohist 457. I have attached two of such crash reports here:

[IceFireCrashDragonCave.txt](https://github.com/Mohist-Community/Mohist/files/6292458/IceFireCrashDragonCave.txt)
[IceFireCrashHydra.txt](https://github.com/Mohist-Community/Mohist/files/6292459/IceFireCrashHydra.txt)

This seems to be the same issue as : #816 #969 #1144 #1034 #770 #735 

I do not understand why these previous issues have been closed since the problem has definitely not been fixed. #969 seems particularly informative to the underlying problem.

**Comment by KR33PYK1NG** [comment]
fixed in the latest build
