### ISSUE TITLE
Spigot 'entity-activation-range'

### ISSUE THREAD

**Issue by VutkaA** [Teneted/Tenet#1199]
Hello, I know Minecolonies mod is having issues with Sponge due to entity-activation-range.

This can be fixed by disabling entity-activation-range in global.conf however Mohist does not create such a file.

Can you please tell me if there is an option to disable entity-activation-range?

Versions:
mohist-1.16.5-453-server

**Comment by laboriens** [comment]
mohist not sponge

**Comment by VutkaA** [comment]
Sorry trying to solve the problem, I am completely confused.

Mohist creates Spigot.yml file
Spigot.yml has the ability to change the entity-activation-range. Is it possible to give an individual mod an unlimited radius, or is it only necessary to set a very large number as a parameter to misc?

**Comment by KR33PYK1NG** [comment]
Set your ranges to some arbitrary huge number and you should be fine.
