### ISSUE TITLE
Mohist Latest has JNI error

### ISSUE THREAD

**Issue by CanBoy67** [Teneted/Tenet#1209]
The latest version of mohist mohist-1.16.5-471-server down to mohist-1.16.5-469-server all give JNI errors, when I try to run latest on server the error is Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraftforge/server/ServerMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by xenomew2** [comment]
im literally getting the same error, ive been trying to fix it for an hour and i installed the new java but it didnt fix anything

**Comment by KR33PYK1NG** [comment]
> 
> 
> The latest version of mohist mohist-1.16.5-471-server down to mohist-1.16.5-469-server all give JNI errors, when I try to run latest on server the error is Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraftforge/server/ServerMain has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

You must use Java 11 to run Mohist now.
