### ISSUE TITLE
Ironchest, Create and Gravestone mod not working with Mohist

### ISSUE THREAD

**Issue by AngelGamerZ** [Teneted/Tenet#1214]
I've found your Server files and these are incredible! I love it!
But I found out that Iron Chests, Gravestone Mod and Create are not working with Mohist. Iron Chests aren't placeable and Gravestone Mod aren't working. The Chests placed on Create Machines loose their Inside if the Machine starts moving.

**Comment by muriplz** [comment]
Create works and worked perfectly with mohist

**Comment by muriplz** [comment]
Same as #1180 , you can have a workaround with barrels or Create mod crates.

**Comment by kencinder** [comment]
Iron Chests mod works perfectly fine here, can't comment either way on the other 2 aside from the fact Corail Tombstone doesn't work like the Gravestone mod.

**Comment by Shawiizz** [comment]
Create mod issue : #1180
Gravestone issue : #878

**Comment by Shawiizz** [comment]
After testing IronChest works completely fine on my side. I close this
![2021-04-21_21 46 35](https://user-images.githubusercontent.com/55449195/115612104-2fece280-a2eb-11eb-827f-a845c09a5550.png)
