### ISSUE TITLE
Obfuscate mod not working on mohist.

### ISSUE THREAD

**Issue by GazMazk** [Teneted/Tenet#1229]
So there's a problem where i tried playing with my friends with a vehicle mod and i'm trying to use MrCrayfish's Vehicle mod, And it needs a necessary mod called obfuscate. I don't know why but when i try to get a car, it is not letting me ride it or spawn it.

Please Help!

**Comment by KR33PYK1NG** [comment]
Logs/Mohist version?

**Comment by GazMazk** [comment]
Server Version is 1.16.5. Mohist Version is 1.16.5-482. Hosting is Idley Host.

**Comment by joaoespanhol** [comment]
issue oudated

I am using mod my server, no find problem mod.

@Romaindu35

**Comment by Romaindu35** [comment]
This issue seems fixed, if you have always this problem, please open new issue.
