### ISSUE TITLE
Permissions restarting after death

### ISSUE THREAD

**Issue by roxarr** [Teneted/Tenet#1234]
Players after death, they are loosing thier permissions, and they need to relogin. Sorry if i didn't show a precisely write about that but i don't know where i can find this problem i console.

**Comment by KR33PYK1NG** [comment]
What permissions plugin are you using?

**Comment by roxarr** [comment]
Luckperms-bukit 5.3.21

**Comment by KR33PYK1NG** [comment]
Mohist build version?

**Comment by roxarr** [comment]
1.16.5 497

**Comment by roxarr** [comment]
Sorry my bad that was not mohist 497, that was mohist 475.

**Comment by Shawiizz** [comment]
And with the latest version this issue happens too ?

**Comment by roxarr** [comment]
on this 475 is the problem with permissions after death, now after midnight i update to 501 and i will check this. if there are any problems, I will write immediately

**Comment by roxarr** [comment]
i did something wrong i think because i change old  "minecraft_server.jar"(mohist 457) on "minecraft_server.jar"(mohist 501) and server stoped after that.

console:
https://pastebin.com/J1MdHN6e

**Comment by KR33PYK1NG** [comment]
Update to build 529 (and make sure you updated correctly), then tell us if the issue persists. I can't reproduce this.

**Comment by roxarr** [comment]
ok. i check this build and after death, doesn't work /spawn and /home (i mean, there is a text "teleporting....." and nothing but after relogin i can normaly use /spawn and /home) and now i check on /op mode, after death when i use /fly or /gamemode creative when i landing i don't know why i get hurt. If you want you can come in to my server and check on yourself.

**Comment by KR33PYK1NG** [comment]
Try [this version](https://github.com/KR33PY/Essentials/releases/download/essxmohist/EssentialsX-2.19.0-dev+99-fd961d5.jar) of EssentialsX.
