### ISSUE TITLE
Rats 1.12.2

### ISSUE THREAD

**Issue by somnambul1st** [Teneted/Tenet#1235]
Hello ran into this problem on your kernel, version 1.12.2, kernel build latest.
When you enter the server gives an error, here is the console:
![image](https://user-images.githubusercontent.com/53238089/115544716-9baf5b00-a2ab-11eb-9faa-a4e5a7773889.png)
And this writes to the client:
![image](https://user-images.githubusercontent.com/53238089/115544671-905c2f80-a2ab-11eb-9e4d-5dd90be41150.png)

Logs:
Client - [latest_.log](https://github.com/Mohist-Community/Mohist/files/6350362/latest_.log)
Server - [latest.log](https://github.com/Mohist-Community/Mohist/files/6350357/latest.log)

**Comment by SparkGNRK** [comment]
Tested and working on mohist build 307.
