### ISSUE TITLE
Permissions with mohist

### ISSUE THREAD

**Issue by RaiiZou** [Teneted/Tenet#1240]
I created a server with mohist-1.12.2-204-server.jar and added EssentialsX & Groupmanager.
When i'm op and i'm default, i can execute (for exemple : /setspawn or /op) but when i'm owner or other rank, i can't do that however i have the "*" permissions.

After checked a multiple forum, i don't find solutions.

Sorry for my bad english, i'm french.

**Comment by KR33PYK1NG** [comment]
We strongly recommend using LuckPerms as your permission management plugin.

**Comment by RaiiZou** [comment]
Why ?
I have always use Groupmanager =/

**Comment by RaiiZou** [comment]
Ok, it's good
I just see a tutorial video and it's very simple.
