### ISSUE TITLE
1.16.5several mods

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1248]
LOG server : https://mclo.gs/7rhWJpW

**Mohist Version :** {521}

**Concerned mod / plugin** : no have plugin

**Logs :** {Link(s) of logs and crash reports if you have}

**Steps to Reproduce :**
start server

**Comment by KR33PYK1NG** [comment]
What's wrong here?

**Comment by joaoespanhol** [comment]
> O que há de errado aqui?

several console errors appear.

**Comment by KR33PYK1NG** [comment]
Which errors do you mean? Can you point them out exactly?

**Comment by joaoespanhol** [comment]
> Which errors do you mean? Can you point them out exactly?

yes.
https://mclo.gs/s8rLM6U
![image](https://user-images.githubusercontent.com/22871432/115970578-2954aa00-a53b-11eb-9de6-55682c411ec0.png)

**Comment by joaoespanhol** [comment]
fixado last version
