### ISSUE TITLE
[1.16.5] Supplementaries Crash-Server

### ISSUE THREAD

**Issue by DaDiGui** [Teneted/Tenet#1251]
1.16.5

mohist-1.16.5-461-server

https://www.curseforge.com/minecraft/mc-mods/supplementaries

https://mclo.gs/uRthGvk

**Steps to Reproduce :**
1. Place the .jar in the server mods folder
2. Turn on the server
3. After a few seconds the server shuts itself down.

https://pastebin.com/Je0i8UJ1 Link of the content that appears in the console from startup to server shutdown. No crash-server log appears either

**Comment by KR33PYK1NG** [comment]
Update to the latest build (mohistmc.com)

**Comment by DaDiGui** [comment]
New crash with latest version of mohist (mohist-1.16.5-524-server) and Supplementaries
https://pastebin.com/LeyE6WBe

**Comment by KR33PYK1NG** [comment]
Try using build 526.

**Comment by DaDiGui** [comment]
Works
