### ISSUE TITLE
[1.16.5] MrCrayfishVehicleMod not spawning vehicles

### ISSUE THREAD

**Issue by MTalon63** [Teneted/Tenet#1252]
**Minecraft Version :**  1.16.5

**Mohist Version :** 1.16.5 build #517

**Concerned mod / plugin** : https://github.com/MrCrayfish/MrCrayfishVehicleMod

**Logs :** None

**Steps to Reproduce :**
 1. Create a vehicle crate/get one from creative
 2. Try to place it and unpack it

**Description of issue :** When running Mohist you can't really use the mod as it can spawn vehicles, @MrCrayfish in https://github.com/MrCrayfish/MrCrayfishVehicleMod/issues/185 said that it could be `BlockEntityTag`.

**Comment by DaniBTZ** [comment]
Hi i can t spawn a vehicle on mrcrayfish vehicle mod can anyone help me? (1.16.5)
