### ISSUE TITLE
[1.12.2] Weapons disappearance in the 2nd hand

### ISSUE THREAD

**Issue by RaiiZou** [Teneted/Tenet#1258]
On my server i have the **Vic's Modern Warfare Mod** in **1.12.2** and **when i take a weapon in the 2nd hand, the weapon disapear** ..
I search a method for **block the weapon in the 2nd hand** or **solved the problem**.

Minecraft version : _Minecraft 1.12.2_
Mohist version : _mohist-1.12.2-204_

Page of the mod : https://www.curseforge.com/minecraft/mc-mods/vics-modern-warfare-mod

**Comment by SparkGNRK** [comment]
Not a Mohist issue, happent also in singleplayer or on normal forge server.
