### ISSUE TITLE
[1.16.5] Difficulty Not Able To Be Changed In "Non-Default" Worlds

### ISSUE THREAD

**Issue by SilentStarling** [Teneted/Tenet#1259]
**Minecraft Version :** 1.16.5

**Mohist Version :** 528

**Logs :** No crashes, no console errors

**Mod list :** No Mods

**Plugin list :** WorldMania

**Description of issue :** Firstly, I know this isn't a problem with WorldMania because this problem also occured when I had Multiverse instead of Worldmania. When in the "Default" world (the main world of the server, the one that can be accessed without any sort of multi-world plugin), difficulty can be changed as intended by using the /difficulty command. When attempting to change the difficulty in additional worlds, such as those made with a multi-world plugin, the difficulty will not change. 

1: make a new world
2: teleport to that world, the difficulty is set to easy by default
3: do /difficulty normal (issue also occurs with peaceful or hard)
4: chat says the difficulty did not change, as it was already set to normal
5: check Options within the esc menu, difficulty still says Easy. This is confirmed as cave spiders do not deal poison damage, and raids only have 3 waves

So the game is acting like the difficulty should still be what I say it is, but its locked on easy. Again, this occurs within all worlds except that default world. I repeated the above steps using WorldMania and Paper, and the difficulty changes as intended in all worlds.

**Comment by joaoespanhol** [comment]
issue oudated

No have this problem, last version mohist. 

@Romaindu35

**Comment by Romaindu35** [comment]
This issue is fix ?

**Comment by joaoespanhol** [comment]
> This issue is fix ?

I restart the server and the difficulty level remains
article versions, had this problem, most article versions.

But more recently, I don't.

**Comment by joaoespanhol** [comment]
i am using pl: multiverso.

i go testing other plugin, sorry

**Comment by Romaindu35** [comment]
Ok, so this issue seems fixed, if you have always this problem, please open new issue.

**Comment by Romaindu35** [comment]
I doesn't see the last message, so I reopen this issue the time that you test @joaoespanhol

**Comment by Romaindu35** [comment]
The fix is confirmed

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/170361713-5b5e9ef6-a7b3-4282-a93b-1598d9db02f7.png)
after restarting the server and keeping the world difficulty config


the plugin, even keeping the configuration, the problem remains if
Since the server difficulties haven't changed, even the plugin says it has
Reopen @Romaindu35
