### ISSUE TITLE
Temporarily Configuration Flag to disable version checking.

### ISSUE THREAD

**Issue by itb3goose** [Teneted/Tenet#1262]
For large modpacks it's a pain to have users manually install mods when they can't be loaded on the server due to the version checking failing even though a mod is newer than the minimum required.

Seen here
`-- MOD aquaculture --
Details:
        Mod File: Aquaculture-1.16.5-2.1.16.jar
        Failure message: Mod aquaculture only supports biomesoplenty 13.0.0.420 or above
                Currently, biomesoplenty is 1.16.4-13.0.0.431
        Mod Version: 1.16.5-2.1.16
        Mod Issue URL: NOT PROVIDED
        Exception message: MISSING EXCEPTION MESSAGE
`
If there's a way to implement a flag in the mohist server configuration to disable version checking or load mods that fail it for dependencies that'd be great. This would make updating large packs easier until the mod authors fix their mods.

**Comment by KR33PYK1NG** [comment]
Implemented in 8f79ccd
