### ISSUE TITLE
[1.16.5] Multiverse doesn't save gamerules in a second world

### ISSUE THREAD

**Issue by adzukyat** [Teneted/Tenet#1263]
**Minecraft Version :** 1.16.5

**Mohist Version :** 526

**Concerned plugin** : [Multiverse-Core](https://dev.bukkit.org/projects/multiverse-core) 4.2.2

**Logs :** https://paste.ubuntu.com/p/ynkKStYpGZ/

**Steps to Reproduce :**
 1. Start your Mohist server.
 2. Do `mv create testworld NORMAL` to create a second world.
 3. Do `mv gamerule doFireTick false testworld` to change some gamerule.
 4. Do `mv gamerules testworld` to confirm if the gamerule was actually changed.
 5. Do `stop` and restart your server.
 6. Do `mv gamerules testworld` again. The value of "doFireTick" will be reverted to "true".

**Description of issue :**
Multiverse doesn't seem to save any gamerules in a second world.
The official Spigot server built with BuildTools.jar is fine, so it will be a Mohist issue.

I deleted all configuration files so that I can run the server in a plain environment. I checked all the permissions on the file, and they were all correct.
It occurred the same on both Windows and Linux.

Thank you.

**Comment by Scrulius** [comment]
same problem

**Comment by ZeroBloodedge** [comment]
same.
If I restart the server, main world's difficulty will change to easy.
I have to change it to hard every time.
And I can't change difficulty in second world.

**Comment by frogden** [comment]
Same

**Comment by SoaringWyvern** [comment]
Anyone else experiencing the issue where the Multiverse plugin doesn't save gamerules on secondary worlds in mohist can do the following to 'patch' that issue. Find your initial world folder that was generated the first time you ran the server and locate its level.dat. open the server and set the gamerules like you want in another world then save and quit the server. Copy the level.dat and paste it to the folder named after the world you want to change the rules for. Do this for all of your worlds then change the rules in the initial world back to what you desire.  Its a bit of work but Ive been testing it all day on my server and it has worked flawlessly since.

Edit: Alternatively you can paste copies of level.dat into all of your wolrds folders, then open each with NBTExplorer and change the gamerules within with that.

**Comment by SilentStarling** [comment]
I was experiencing the same problem: just tried wyvern's idea and it worked great, for both world difficulties and gamerules. Thanks!!

**Comment by adzukyat** [comment]
I found that the folders "region", "poi" and "data" which should be in the root directory of a world folder are in a "dimensions" folder if it is generated by Multiverse.

### A normal world folder (initially generated by Mohist or a second world folder generated by Multiverse on a Spigot server) is like:
![image](https://user-images.githubusercontent.com/44765629/117562033-d6e8c100-b0d6-11eb-8373-e64fc84b7ade.png)

### A second world folder generated by Multiverse on a Mohist server is like:
![image](https://user-images.githubusercontent.com/44765629/117562597-0e596c80-b0db-11eb-8851-5dccbb28b3b9.png)
It doesn't have level.dat!

![image](https://user-images.githubusercontent.com/44765629/117562627-55476200-b0db-11eb-8431-b72ec008fdfe.png)

### It's also weird that the "dimensions" folder in the main world contains the folder having the second world's name:
![image](https://user-images.githubusercontent.com/44765629/117562859-15817a00-b0dd-11eb-900e-148e56c3260b.png)

I think the issue is caused by the behavior of Forge generating "dimensions" folder.
Official Forge servers which have dimension mods installed generates a "dimensions" folder in a world so that we can play additional dimensions by installing mods such as [Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest).

**Aren't secondary worlds treated as a dimension?**

**Comment by SoaringWyvern** [comment]
Yes. The issue is likely caused by Forge and Spigot each handling dimensions differently. Multiverse is a Spigot plugin, so it seems that forge is causing the server to look look in the wrong location for world details.

**Comment by Rasgnarok** [comment]
> Yes. The issue is likely caused by Forge and Spigot each handling dimensions differently. Multiverse is a Spigot plugin, so it seems that forge is causing the server to look look in the wrong location for world details.

I mean, MV doesn't even make one when I'm testing Mohist 891 1.16.5 and latest MV. Gamerules and other data not stored under MV's config worlds.yml revert to default because there's no file to store them under.
