### ISSUE TITLE
[1.16.5] Incompatible mod?

### ISSUE THREAD

**Issue by dkbhn** [Teneted/Tenet#1264]
**Steps to Reproduce :**
 1. Installed mohist-1.16.5-449-server.jar
 2. add supplementaries-1.16.5-0.12.1.jar to mods folder
 3. Try to start the thing

**Description of issue :** {Give all details about your issue}

I'm trying to run Valhelsia 3 modpack. But one mod is causing an issue.
Mohist ver.: mohist-1.16.5-449-server.jar
Java: Oracle 11.0.11
The mod that is causing the issue is supplementaries-1.16.5-0.12.1.jar
I'm not getting any debug.log or crash report. only thing is latest.log, which is here https://pastebin.com/EK6FURk5

It doeswork with mohist-1.16.5-529-server.jar, but that is an other forge version, so I can't use that since it's not my modpack.

Thanks.

**Comment by KR33PYK1NG** [comment]
Supplementaries startup is broken in builds 479 and lower.
Your best bet is to update to 480+ or implement [the fix](https://github.com/Mohist-Community/Mohist/commit/195538ae74f79e1b3041797a9bb7d7d6b501f8a9) yourself on top of the desired build.
