### ISSUE TITLE
[1.16.5] Errors in logs lastest version worldedit/worldguard + mods.

### ISSUE THREAD

**Issue by RyanCrew** [Teneted/Tenet#1265]
**Minecraft Version :** 1.16.5

**Mohist Version :** Mohist 1.16.5-498

**Concerned mod / plugin** : WorldEdit-6.1.9-0.3-SNAPSHOT-all, Worldguard-bukkit-7.0.4, OuterEnd-0.2.9,Dragon+Mounts+Legacy1.0.10

**Logs :** https://paste.ubuntu.com/p/qwtyTgKp7W/

**Description of issue :** Different errors in console, OuterEnd, Dragon Mounts Legacy Mods, WorldEdit (mohist discord version) and WorldGuard, just have a look in the log

**Comment by KR33PYK1NG** [comment]
This WorldEdit version is for 1.12.2

**Comment by RyanCrew** [comment]
> This WorldEdit version is for 1.12.2

I see, is there any update to 1.16.5?

**Comment by KR33PYK1NG** [comment]
> 
> 
> > This WorldEdit version is for 1.12.2
> 
> I see, is there any update to 1.16.5?

Just use official.

**Comment by RyanCrew** [comment]
Still getting this: https://paste.ubuntu.com/p/PZR5BNr3fW/ 
WorldEdit-bukkit-7.2.5-dist.
WorldGuard warnings are no showing up now

**Comment by KR33PYK1NG** [comment]
> 
> 
> Still getting this: https://paste.ubuntu.com/p/PZR5BNr3fW/
> WorldEdit-bukkit-7.2.5-dist.
> WorldGuard warnings are no showing up now

This error is known and shouldn't interfere with plugin functionality.
