### ISSUE TITLE
1.16.5 Survive-1.16.5-3.2.2

### ISSUE THREAD

**Issue by JEKRUY** [Teneted/Tenet#1266]
1.16.5

530

Survive-1.16.5-3.2.2

https://paste.ubuntu.com/p/x2Rhy2KM7r/

Steps to Reproduce :
 1. Install Survive-1.16.5-3.2.2
 2. Install sereneseasons is 1.16.5-4.0.1.91
 3. Start the server

The problem is indicated in the log itself

**Comment by KR33PYK1NG** [comment]
Install build 531 and set `forge_ignore_optional_mods_version_check` to `true` in `mohist-config/mohist.yml`
