### ISSUE TITLE
[1.16.5] crashing on start

### ISSUE THREAD

**Issue by YaBagro** [Teneted/Tenet#1268]
it`s latest log file can you help me
[latest.log](https://github.com/Mohist-Community/Mohist/files/6394330/latest.log)

**Comment by KR33PYK1NG** [comment]
The issue format is not followed. Again.
[click here](https://github.com/Mohist-Community/Mohist/issues/new?assignees=&labels=waiting&template=unknown-bug-report.md&title=) to create a new formatted issue. Make sure to fill all steps with required info.

**Comment by YaBagro** [comment]
how
