### ISSUE TITLE
[1.16.5] crash on start

### ISSUE THREAD

**Issue by YaBagro** [Teneted/Tenet#1270]
**Minecraft Version :1.16.5**

**Mohist Version :531**

**Logs :https://haste.mohistmc.com/yekeneguni.css** 

**Mod list :none**

**Plugin list :none**
**Description of issue :Crash on start**

**Comment by KR33PYK1NG** [comment]
Judging by the provided log, you're using Java 16. It can be problematic.
Use Java 11 to start your server.

**Comment by YaBagro** [comment]
ok thank
