### ISSUE TITLE
[1.12.2] One commit break MyItems / Stats modifications 

### ISSUE THREAD

**Issue by EpickaMC** [Teneted/Tenet#1279]
**Minecraft Version :** 1.12.2

**Mohist Version :** 196+

**Operating System :** Windows 10 / Ubuntu

**Concerned mod / plugin** : MyItems https://www.spigotmc.org/resources/myitems-premium-1-7-x-1-13-x-under-recode.29028/

**Steps to Reproduce :**
Take a sword and order : //att Stats damage 10

**Description of issue :** Since this : commit https://github.com/Mohist-Community/Mohist/commit/a2c61625cdd00d990ab584b5cc8f9e6fde8e8523 , MyItems has a problem with assigning stats. By adding damage to the sword to the plugin, the command works well and there is no error but the damage remains the basic ones and the modification of the weapon is not taken into account. This problem must be present with other plugins and it is very annoying for MMORPG servers that need to change weapons stats. If you want the plugin for more in-depth testing, ask for it here and I’ll give it on the discord.

**Comment by PierreBouffartigue** [comment]
I have the same problem

**Comment by KR33PYK1NG** [comment]
Please provide the plugin .jar so we could try and reproduce your issue.
Right now we cannot because the plugin from the link you provided is a premium resource.

**Comment by iSoulEs** [comment]
Hi @KR33PY  I have the same problem as him and here I offer the .jar
Myitems premium latest version 6.4.5

**Comment by VoldirFr** [comment]
freaking same, all commands are working nice but it doesn't affect the items, ofr exemple :
./att stats damage 50
The item should deal 50 damages, but it doesn't. Same for all others changes.
Thanks iSoul-Es for the drop, they should be able to test it.

**Comment by iSoulEs** [comment]
mmoitems, and prorpgitems not works,
all damage alteration plugin does not work
pls fix it 
rpg servers are severely affected

**Comment by KR33PYK1NG** [comment]
I reverted the changes made in a2c6162, so MyItems should work again in the latest build.
