### ISSUE TITLE
Problem with modpack

### ISSUE THREAD

**Issue by roxarr** [Teneted/Tenet#1286]
**Minecraft Version : 1.16.5

**Mohist Version :** 535 - 517

**Operating System :** Windows 10 pro

**Logs :** logs- https://pastebin.com/rNQb0zij, crash-report-https://pastebin.com/yTCihwav, https://pastebin.com/MiD4U7W0

**Mod list :** valhelsia 3 version 3.2.4

**Plugin list :** none

**Description of issue :**  when i turn on server with this modpack, after 10 seconds and i get a crash report and problem is the aquaculture, tetra(problem with biomes'o and curios with versions but versions is correct) but after when i delete this mods and restart server, there is another poblem with mod "structurize". I try this newest build and older (535 - 517) and its the same problem. I don't konw its mohist works with modpacks? or i need to make my own modpack for server?

**Comment by roxarr** [comment]
i check normal forge 36.1.0 and server is normaly working.

**Comment by Mgazul** [comment]
This has nothing to do with us, forge has modified the version identification mechanism, you need to update the mod version in the mod package

**Comment by Mgazul** [comment]
This has nothing to do with us, forge has modified the version identification mechanism, you need to update the mod version in the mod package

**Comment by Shawiizz** [comment]
or easy solution : set forge_ignore_optional_mods_version_check to true in mohist-config/mohist.yml (build 531 or above required to have this option work)
