### ISSUE TITLE
1.16.5 WorldEdit | //copy | //regen

### ISSUE THREAD

**Issue by JEKRUY** [Teneted/Tenet#1287]
**Minecraft Version :** 1.16.5

**Mohist Version :** 531

**Operating System :** Ubuntu

**Concerned mod / plugin** : WorldEdit version 7.2.5

**Logs :** https://paste.ubuntu.com/p/QvvX8q6S2X/

**Steps to Reproduce :**
 1. Install the plugin
 2. Use the command //copy
 3. Use the command //regen

**Description of issue :** Errors are displayed inside the log when using two commands

**Comment by Mgazul** [comment]
#997
