### ISSUE TITLE
[1.16.5] McMMO Unable to enable

### ISSUE THREAD

**Issue by nnn950711** [Teneted/Tenet#1290]
**Minecraft Version : 1.16.5

**Mohist Version : mohist-1.16.5-539-server

**Operating System : win10

**Concerned mod / plugin: McMMO

**Logs : [logs.txt](https://github.com/Mohist-Community/Mohist/files/6408722/logs.txt)

**Comment by kakaoen404** [comment]
**Minecraft Version : 1.16.5

**Mohist Version: mohist-1.16.5-539-server

**OS: Ubuntu 20.04
**Concerned mod/ plugin: McMMO
**Logs: [2021-06-15-1.log](https://github.com/MohistMC/Mohist/files/6671822/2021-06-15-1.log)
