### ISSUE TITLE
[1.16.5] Create mod client crash

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1291]
**Minecraft Version :** 1.16.5

**Mohist Version :** 535

**Operating System :** Ubuntu

**Concerned mod / plugin** : Create mod 0.3.1c

**Logs :** 
[crash-2021-04-30_19.04.16-client.txt](https://github.com/Mohist-Community/Mohist/files/6408904/crash-2021-04-30_19.04.16-client.txt)

**Steps to Reproduce :**
 1. Try to place a schematic with belts on it

The error crashes peoples clients, but the server does not give out errors

**Comment by Shawiizz** [comment]
This is a client crash, but Mohist is a server software. I don't think this issue is related to Mohist. If i'm wrong tell me
