### ISSUE TITLE
[1.16.5] Yung's Better Strongholds - Eye of Ender doesn't work

### ISSUE THREAD

**Issue by kencinder** [Teneted/Tenet#1296]
**Minecraft Version :** 1.1.6.5

**Mohist Version :** 537

**Operating System :** Debian

**Concerned mod / plugin** : Yung's Better Strongholds v1.0.1 - https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds

**Logs :** https://gist.github.com/kencinder/236c509bb77b51c8d1d120de74abb450

**Steps to Reproduce :**
 1. Try to use an Eye of Ender, doesn't work and throws errors in log

**Description of issue :** Error in log when trying to use Eye of Ender, works correctly on Forge server.

**Comment by kencinder** [comment]
It works, yay. Also has the added benefit of fixing the /locate command not working with modded structures

**Comment by FweeGamerHD** [comment]
What was necessary to fix this issue?
