### ISSUE TITLE
[1.16.5] error console start server

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1297]
**Minecraft Version :** 1.16.5

**Mohist Version :** 541

**Operating System :** windows 10

**Concerned mod / plugin** : LagAssist v2.23.5 adavanced - https://www.spigotmc.org/resources/lagassist-%E2%9A%A1-advanced-performance-solution-%E2%9A%A1-1-8-1-16-compatible.56399/

**Logs **: https://mclo.gs/j20LxyV

**Steps to Reproduce :**
start server

**Comment by Shawiizz** [comment]
Please edit this issue / create another one and fill the issue template.

**Comment by joaoespanhol** [comment]
> Please edit this issue / create another one and fill the issue template.


calm, I was correcting.
see if it's good like that please

**Comment by Shawiizz** [comment]
Don't worry, I'm not angry ^^. It's ok like that

**Comment by joaoespanhol** [comment]
> Don't worry, I'm not angry ^^. It's ok like that

not use this plugin anymore, but I'll leave the ticket open

**Comment by Shawiizz** [comment]
Okay no problem

**Comment by joaoespanhol** [comment]
has been fixed with last update
