### ISSUE TITLE
[1.16.5] Applied Energistics 2 Seeds Despawn

### ISSUE THREAD

**Issue by kencinder** [Teneted/Tenet#1299]
**Minecraft Version :** 1.16.5

**Mohist Version :** 542

**Operating System :** Debian

**Concerned mod / plugin** : Applied Energistics 2 v8.3.0 beta 2 - https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3286808
**Logs :** N/A

**Steps to Reproduce :**
 1. Create or give yourself any AE2 seed
 2. Throw it in a pool of water
 3. Wait 5 minutes or more, and the seeds despawn

**Description of issue :** The seeds are never supposed to despawn, and never do on a Forge server.

**Comment by Lionear** [comment]
@kencinder did you ever get this issue fixed? I'm trying to set up a server with this mod, but the seeds just keep disappearing.

**Comment by joaoespanhol** [comment]
@kencinder and  @Lionear , i have last version mohist and mod, i no find this problem.
Test 10 minute, no find this problem.

You can't give more information please.
