### ISSUE TITLE
Vanilla Recipes not working

### ISSUE THREAD

**Issue by BlayzerQ** [Teneted/Tenet#13]
When i updated to Mohist-88a5645-server from Mohist-1.0-faaaa38-universal, all vanilla recipes (not edited by CraftTweaker) did not work (show on client side, but did not work on server side.
No errors on console/log.
[latest.log](https://github.com/Mohist-Community/Mohist/files/3667284/latest.log)

**Comment by BlayzerQ** [comment]
On console messages like this:
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:diamond_leggings removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:golden_apple removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:stone_axe removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:wheat removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:iron_boots removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:diamond_axe removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:stone_hoe removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:coarse_dirt removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:hay_block removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:stone_shovel removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:iron_pickaxe removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:stone_stairs removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:shears removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:orange_concrete_powder removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:bone_meal_from_bone removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:diamond_chestplate removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:yellow_concrete_powder removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:acacia_boat removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:torch removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:writable_book removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:black_concrete_powder removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:bookshelf removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:shield removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:dispenser removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:bucket removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:golden_axe removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:golden_shovel removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:iron_sword removed now.
29.09 14:47:19 [Server] INFO Tried to load unrecognized recipe: minecraft:golden_pickaxe removed now.

**Comment by BlayzerQ** [comment]
Without mods all crafts working.

**Comment by Mgazul** [comment]
What is BukkitLoadingPlugin?

**Comment by Mgazul** [comment]
When using Mohist-1.0, everything is normal?

**Comment by BlayzerQ** [comment]
> What is BukkitLoadingPlugin?

Notification mod. 
ClassNotFoundException: ru.stepan1404.notifications.patch.BukkitLoadingPlugin It was a long time ago, but there were no problems because of this.
https://www.dropbox.com/s/jsek16rfwbu024r/MinecraftNotification-1.2-server.jar?dl=0

> When using Mohist-1.0, everything is normal?
Yes
