### ISSUE TITLE
[1.16.5] Crash Server after Respawning (Scaling Health 1.16.5)

### ISSUE THREAD

**Issue by DoDoSov** [Teneted/Tenet#1303]
Minecraft Version : 1.16.5

Mohist Version : 1.16.5-544

Operating System : Windows 10 x64

Concerned mod  : Scaling Health-1.16.5-4.0.5+5 (https://www.curseforge.com/minecraft/mc-mods/scaling-health)
                            Silent Lib-1.16.3-4.9.6 (https://www.curseforge.com/minecraft/mc-mods/silent-lib) (LIB FOR THIS MOD)

Crash-report : https://paste.ubuntu.com/p/VRtw4TQxSD/

Description: When any player die and try to click on button "Respawn" - Server Crash.

**Comment by joaoespanhol** [comment]
there is no such problem with the latest mohist version
