### ISSUE TITLE
Server Timeout Map Issues

### ISSUE THREAD

**Issue by SilentStarling** [Teneted/Tenet#1305]
**Minecraft Version :** 1.16.5

**Mohist Version :** 545

**Operating System :** Windows 10

**Logs :** 
[latest.log](https://github.com/Mohist-Community/Mohist/files/6424774/latest.log)
no crash reports, usually does not "crash" server, just stalls it

**Mod list :** No mods

**Plugin list :** No plugins (usually use plugins, but bug occurs without any plugins present as well)

**Description of issue :** This problem has taken me many days to nail down. On my server, players were experiencing random timeout events. The server would time out all players, and then if they tried to rejoin they would be frozen on the "Encrypting..." screen. Server would either restart by itself, or after ~15 minutes would right itself and let people log on. During this time while everyone is timed out and on the main Minecraft menu screen, the server still lists them as online. Sometimes this issue would happen multiple times one after the other once people could log in again, and sometimes it would not occur for many hours.

I made a copy of all server files and made a test server on my own machine. Through reading bits and pieces from the latest.log, we were able to discover this seemingly random timeout could be triggered by using the /locate command on something far away, usually a mansion as they are rare and frequently over 10k blocks away. This timeout/server freeze occurred on my own test server, so it was not a host issue. I removed all plugins and their related files and tried it again, same issue, so its not a bad plugin. I tried with paper and no plugins, and when i did /locate mansion it simply tells me that there isn't one close enough nearby to locate, and does not time me out. My players do not use the /locate command, so the issue must be related to something else connected to locating structures? Maybe maps. Or maybe the structures themselves. I couldn't find anything linking the issues to a particular structure, or corrupted chunk. If there's anything else you want to look at or have me test please let me know, this issue has been plaguing my server for almost a week now.

Also worth noting, when this issue appeared I had not updated mohist or any plugins in over a week prior. It showed up seemingly randomly.

**Comment by KR33PYK1NG** [comment]
Most likely, your server isn't able to process the amount of chunk loads.
Did you try fully pregenerating your map/play zone? This could potentially help with the problem.

**Comment by SilentStarling** [comment]
That's a good point, I know the server wasn't limited on RAM when I normally check it, but trying to locate a structure in all those chunks would do that. When I was testing, I was specifically locating a mansion. Mohist would tell me it was 14k blocks out and then time me out. Paper would tell me there is not one nearby. That would imply Paper has some sort of limit on how many blocks/chunks out it would search. Is that something Mohist could implement, or a setting I could change? Because even if I pregen everything inside my worldborder, it only goes out to 10k, and I don't wanna pregen way out past my borders if that makes sense.

**Comment by gXLg** [comment]
Same issue with me, it happens, when one player tries to trade with a villager for a location map. It freezes the server and sends "server did not respond for x seconds" errors
![SmartSelect_20210523-173208_Termux](https://user-images.githubusercontent.com/65429873/119267290-2dcdba80-bbee-11eb-9c5c-adf8eb7e3478.jpg)
