### ISSUE TITLE
Using Stonecutter Server Crash

### ISSUE THREAD

**Issue by Teoxex** [Teneted/Tenet#1306]
**Minecraft Version :** 1.16.5

**Mohist Version :** Running Mohist version 1.16.5-434 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.2)

**Operating System :** Windows 10 Pro

**Logs :** 
Logs: https://www.dropbox.com/s/8crow4ylkeb4ev3/latest.log?dl=1
Crash: https://haste.mohistmc.com/liyipagifa.rb
Client Log: https://www.dropbox.com/s/hs5pxz6j57kmzbc/latest_client.log?dl=1

**Mod list :** 
https://haste.mohistmc.com/rokinepafa.apache

**Plugin list :** 
https://haste.mohistmc.com/ehanupuyov

**Description of issue :** 
Hi everyone, I have a little problem: every time I try to use the stonecutter in my modded server, crashes. I can't understand what causes it, can anyone help me? thanks

**Comment by Mgazul** [comment]
Update your mohist version

**Comment by Teoxex** [comment]
Thank you! now works perfectly!
