### ISSUE TITLE
[MC VERSION] Terrain Incognita Crash on Startup

### ISSUE THREAD

**Issue by NFKRZZ** [Teneted/Tenet#1309]
**Minecraft Version :** 1.16.5}

**Mohist Version :** {mohist-1.16.5-546}

**Operating System :** {Windows 10-Pro}

**Concerned mod / plugin** : {terraincognita-1.16.3-1.6.4.1, Modpack: Better Minecraft Plus v4 link: https://www.curseforge.com/minecraft/modpacks/better-minecraft-plus/files  }

**Logs :** {Crash Report: https://haste.mohistmc.com/bayazixuxa
Server Log: https://haste.mohistmc.com/xilumucare }

**Steps to Reproduce :**
 1. Download Better Minecraft Plus v4 Server Pack
 2. Setup Mohist server
 3. drag modpack files in
 4. start server
 5. crash.

**Description of issue :** {The server wont start with this modpack and it is throwing errors related to this mod only. I don't think it even gets past loading all the mods till it just crashes.}

**Comment by Mgazul** [comment]
mohist.yml  
forge_ignore_optional_mods_version_check: true
