### ISSUE TITLE
似乎不兼容GlobalShop全球市场插件。

### ISSUE THREAD

**Issue by Nisekoi5** [Teneted/Tenet#131]
服务端版本1.12.2  GS插件版本最新(1.1.7.5)，前置ProtocolLib版本4.4。
https://www.mcbbs.net/thread-645697-1-1.html
~~表现状况为。下架物品可以直接吧商店里的东西拿到背包里。并且可以正常使用。经多次测试，创造模式才能触发这个bug~~
https://img.moenis.com/images/2020/03/07/image5a189dacb2ce4221.png
https://img.moenis.com/images/2020/03/07/image8e489311d51564fd.png
主要是下面这个
并且收件箱点开gui就会自动关闭 [https://www.mcbbs.net/thread-971184-1-1.html](url) 表现与这个帖子相同，并且下架物品等功能都无法正常使用（点几十次可能会成功一次）
我测试删除所有mod,world文件夹也是重新生成，几乎所有插件（除了ess和前置）。本地开服测试。问题复现
https://img.moenis.com/images/2020/03/07/imageb0a69ed6d618d438.png

**Comment by CraftDream** [comment]
看不太懂你说的什么，请将错误进行简洁地报告。

**Comment by Nisekoi5** [comment]
> 看不太懂你说的什么，请将错误进行简洁地报告。

简洁一点就是这个插件在mohist无法使用。https://www.mcbbs.net/thread-645697-1-1.html
点收件箱会自动退出gui。收件箱不能用也就代表插件基本无用了。


这个问题似乎也不止我一个人出现，，最终的解决方案是更换服务端 https://www.mcbbs.net/thread-971184-1-1.html 
我也不是很清楚这个是服务端的问题，还是插件问题。于是只好两边都提交了一下。。
作者给出了3个解决方案，其他2个我均已使用过（包括删除所有MOD与多余的其他插件）。无效。最后一个解决方案也是更换服务端.
这个插件也是比较知名的了，服务端方面可以做到兼容的话还是比较希望可以兼容下~
