### ISSUE TITLE
Crash with Project Ozone 3 on server startup / 1.12.2

### ISSUE THREAD

**Issue by s3ntin3l8** [Teneted/Tenet#1311]
**Minecraft Version: 1.12.2
**Mohist Version :mohist-1.12.2-211-server
**Crash Report [crash-2021-05-06_22.19.17-server.txt](https://github.com/Mohist-Community/Mohist/files/6437463/crash-2021-05-06_22.19.17-server.txt)
**Logs : [latest.log](https://github.com/Mohist-Community/Mohist/files/6437466/latest.log)
**Mod list : Project Ozone 3 mods
**Plugin list : no plugins
**Description of issue : Crash on first server startup.

**Comment by Mgazul** [comment]
The error does not exist in the latest build
