### ISSUE TITLE
Crash on entering The Abyss dimension "Attempted to load class [...] for invalid dist DEDICATED_SERVER"

### ISSUE THREAD

**Issue by Kinomora** [Teneted/Tenet#1312]
**Minecraft Version :** 1.16.5

**Mohist Version :** The Abyss 1.9.7

**Operating System :** Linux (dedicated server)

**Logs :** https://pastebin.com/1JFpRvEb

**Mod list :** modlist in crash report

**Plugin list :** no plugins

**Description of issue :** Server crashed upon player entering the Abyss dimension

**Comment by Romaindu35** [comment]
This is not mohist problem, this mod seems client side ony
