### ISSUE TITLE
Strange spam in console

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#1319]
**Minecraft Version :** 1.16.5

**Mohist Version :** 549

**Operating System :** Windows 10 Pro

**Logs :** https://pastebin.com/pJjKC5BC

**Mod list :** TerraForged, attributefix, better caves/strongholds/mineshafts

**Plugin list :** LuckPerms, SkinsRestorer, PlaceholderAPI, Trade, MOTD, HolographicDisplays, Vault, Clans, WorldEdit, Essentials, EssentialsChat, TAB, EssentialsSpawn, WorldGuard, WorldEditSUI, AuthMe, WGExtender, GSit, CustomJoinMessages, BetterSleeping3.

**Description of issue :**  I have not yet found out exactly where this spam appears. It looks random to me. Even when there is no one on the server, it appears from time to time.

**Comment by kencinder** [comment]
Caused by MOTD plugin, it's trying to use `LegacyPingHandler` which doesn't even exist anmore, hence the `UnsupportedOperationExceptio`...has nothing to do with Mohist.

**Comment by Exzept1on** [comment]
How can I fix this without removing the Tab plugin? Or can it only be done by the developers of Mohist?

**Comment by kencinder** [comment]
Read what I said again, but the spam is harmless(And not Mohists problem, is the plugin devs to fix)

**Comment by Exzept1on** [comment]
Thanks :)
