### ISSUE TITLE
[1.16.5] issues with small ships mod and astikorcarts mod

### ISSUE THREAD

**Issue by DinoDoesThings** [Teneted/Tenet#1321]
Minecraft Version : 1.16.5

Mohist Version : 551

Concerned Mods : https://www.curseforge.com/minecraft/mc-mods/astikorcarts
https://www.curseforge.com/minecraft/mc-mods/small-ships

Logs : N/A

Steps to Reproduce : Get an animal or any entity able to ride a boat/minecart and try to push them onto a ship or animal cart.

Description of 1st issue : Animals aren't able to ride ships or the animal carts.

Description of 2nd Issue: For Small Ships Mod, when riding the ship, there is an inventory button for the ship assigned to the I button. Pressing the button should normally open up the ship's inventory. Instead nothing happens.

**Comment by KR33PYK1NG** [comment]
Can an animal ride vanilla botes/minecarts, though?

**Comment by DinoDoesThings** [comment]
Yes, vanilla boats and minecarts still work.
