### ISSUE TITLE
[1.16.5] Server crashes at mod loading 

### ISSUE THREAD

**Issue by kellyharry** [Teneted/Tenet#1324]
**Minecraft Version :** 1.16.5

**Mohist Version :** 551

**Operating System :** Windows

**Logs :** https://pastebin.com/LwGPvCHt

**Mod list :** {Pehkui)

**Plugin list :** {None)

**Description of issue :** {Server crashes upon mod loading}

**Comment by KR33PYK1NG** [comment]
Fixed in the latest build.
This was a pain in the ass to fix, though. Pehkui's mixins are very dependant on surrounding code.
