### ISSUE TITLE
[1.16.5] Crash on ATM 6 server startup with latest mohist build

### ISSUE THREAD

**Issue by Saabertooth1** [Teneted/Tenet#1325]
**Minecraft Version :** 1.16.5

**Mohist Version :** 555
**Operating System :** Linux Debian-103-buster-64-minimal 4.19.0-8-amd64 1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

**Logs :** [Crash Report](https://haste.mohistmc.com/ohegekateb.yaml) I can provide latest.log if needed

**Mod list :** [Mod List](https://haste.mohistmc.com/ojerekecit.apache)

**Plugin list :** Plugins (30): LuckPerms, AcceptTheRules, OpenInv, PlaceholderAPI, ClearLag, ArmorStandEditor, IllegalStack, WorldBorder, HolographicDisplays, BuycraftX, Votifier, ConsoleSpamFix, BetterCommandSpy, KixsChatAnnouncer, AdvancedNMotd, Vault, WorldEdit, Essentials, LiteBans, Multiverse-Core, WorldGuard, VotingPlugin, VanishNoPacket, TAB, PvPManager, EssentialsSpawn, Wild, Autorank, CommandSigns, DiscordSRV

**Description of issue :** Server crashes on startup with mod "incompatibility" issues as shown in the crash report. Old mohist builds (Currently tested with build 495) work fine.

**Comment by KR33PYK1NG** [comment]
Set `forge_ignore_optional_mods_version_check` to `true` in `mohist-config/mohist.yml`
