### ISSUE TITLE
[1.12.2] Random patches timeout issue

### ISSUE THREAD

**Issue by Michael-Hozza** [Teneted/Tenet#1327]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-214
**Operating System :** Debian
**Concerned mod / plugin** : RandomPatches : https://www.curseforge.com/minecraft/mc-mods/randompatches-forge

**Logs :** https://paste.ubuntu.com/p/FccFhMCvnb/

**Steps to Reproduce :**
 1. Use mohist core and mod randompatches with timeout patch
 2. Console will report 2 errors
 3. Timeout is set on default value (30s)

**Description of issue :** This Timeout patch worked about 3 builds ago, even back then RP creator made hybrid-compatible update. Now it doesn't work as it should.

**Comment by KR33PYK1NG** [comment]
Should be fixed in the latest build.
