### ISSUE TITLE
[1.16.5] Pehkui crashes server when loading a village

### ISSUE THREAD

**Issue by kellyharry** [Teneted/Tenet#1328]
Minecraft Version : 1.16.5

Mohist Version : 556

Operating System : Windows

Logs : Too big for pastebin, attached
[latest.log](https://github.com/Mohist-Community/Mohist/files/6458630/latest.log)

Mod list : {Pehkui)

Plugin list : {None)

Description of issue : {After my previous issue the server starts now however, upon loading a seed that
 has a village in its spawn radius (or approaching a village on another seed) the server immediately crashes. As long as i don't load a village the server runs fine and the mod works perfectly}

**Comment by KR33PYK1NG** [comment]
Should be fixed in build 557.
