### ISSUE TITLE
[1.12.2] Please implement these optimizations

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#133]
Below is a list of things that would help the performance of the server.
- Ignoring all events for chunks that are generating or populating. Chunks that are generating usually spawn entities in them and start ticking them before completing the chunk generation.
- Have the file IO on its own separate thread.
- REMOVE THE IO LOCK! A IDE hard drive from 1995 can out perform a NVME SSD for world generation because there is a IO LOCK on how fast it can write to disk. I have never seen any server software (MCPC, Cauldron, Thermos, Mohist, and other) go beyond 400kbps. This limit has to be eliminated especially on computers with SSD's. This limit however stacks with Raid Striping. So on my server with 4 Hard Drives in Raid 0 which the files are striped across all 4 drivess, the 400kbps limit becomes 1.6MBps. So this proves its not a CPU limitation by the server.
- Have entities and tile-entities on their own separate threads per world.
- Have a smart threading system that will split a load onto more threads if the load takes longer then 10ms to process, then open another if those 2 threads take longer then 20ms, then again at 40ms. If it isnt helping by then its not going to help period lol. But having such a thing setup for everything like worlds, events, handlers, listeners, io, gzip, entities, tile-entities, etc. Would help a lot. Especially these days when you can get a 64 core desktop cpu.
- ~Have the Chunk Generation using the "max-chunk-load-threads" amount in the paper.yml~
- Make a more optimized biome generator and noise generator for the world. In 1.6.4 worlds generated 1000x faster then 1.7.10 when they changed the world biomes/generation. Somehow make the worlds generate like they should be but using the way it was back in 1.6?
- Fix the tile-entities.yml and entities.yml. They do not populate with entities or tile-entities, making the config file's pointless. These files are supposed to add every entity and tile-entity in a list and allow you to set them to never tick or adjust their individual tick rates. This is EXTREMELY helpful for disabling ticking on things like signs, maps, paintings, workbenches, anvils, and more. And also slowing down the tick rates for things like redstone, doors, chests, hoppers, furnaces, and other modded things.
- Have an option to disable world compression on generation, instead compress the region files on server shutdown. And give an option on how high the compression can be. 0-9, 0 being disabled, and it simply saves a raw uncompressed region file.
- Run gzip compression on a separate thread, this includes mods.
- Force the server to use more then 1 cpu thread by config or to whats set in the java arguments. Fore example in my start script i have ``-XX:ActiveProcessorCount=4``
- Implement lighting changes from Phosphor into Mohist.
- Implement AI changes from AI Improvements into Mohist.
- Implement Math improvements from Better FPS into Mohist.
- Implement all MC fixes from VanillaFix and RandomPatches and FoamFix into Mohist.
- Implement culling improvements from FoamFix into Mohist.
- Implement Multithreaded Noise into Mohist.
- Implement Paper patches up to 1.15 into Mohist, this has additional options like limiting chunk load and generation rates, and packet rates. This was made into a mod for forge as "ChunkGenLimiter".
- ~Implement Performant entity tick improvements.~
- Add support for running TickThreading mod on Mohist.
- Add mob stacking inside of Mohist. There is several plugins that do this but they don't support mods, and end up calling modded entities generic vanilla mob names. Ive seen a dragon be called a villager.
- Add MineTickMod enhancements into Mohist. MineTickMod and Migot were mainly tested and programmed around my networks needs on APOC by PowerUser, many optimizations in MineTick were suggested and implemented for us. Like loading the chunks for a player based on their field of view. This right here optimizes chunk generation speed for players and cutting the amount of packets needed to be sent to the player. If the player isnt looking at the chunk, it isnt loaded for them.
- LoadChunksOnForgeTick, this was a thermos option that allowed chunks to load and generate on the forge thread if the forge thread was not busy. The same thing could be done with the bukkit thread.
- If an optimization is incompatible with a certain mod, work around the problem and find a solution for incompatible mods to run the old way if they don't like the new way. So that mods that DO work with the improvements, get a performance benefit while the ones that don't still work. There's no reason to completely remove an optimization because a certain mod or plugin doesn't work with it. Ive seen you do this A LOT, especially when i report incompatibilities with mods and plugins. Please find a way to get them to work instead of removing the performance improvements.

I know a lot of these are about chunk loading and generation, but when you got a dozen or more players running around your server, popping out those chunks ASAP is the difference of a player playing on your server, or leaving while insulting the server for lag in chat. I have been complaining about the chunk gen/load performance here for over 8 months and still have not seen any improvement at all. I know for the most part its Mojangs fault. Every update they make just craps out more and more problems. But on the server end we should be able to solve those problems.

**Comment by Mgazul** [comment]
Regarding the last one, I didn't eliminate it completely, but I didn't have enough time to fix it, I just temporarily removed it, and added it when he was perfect.

**Comment by ishland** [comment]
There are some issues here: 
- I would not recommend implementing mob stacking inside Mohist. They are more likely to be a forge mod or something. 
- Having entities and tile-entities to be ticked off-thread will cause a lot of compatibility issues which may "delete your server". However, it is still worth to have a try.
- Multi-threading with a dynamic thread count is already implemented by Java itself.
- Too many threads may decrease server performance on a system with very few cores.

**Comment by Zilacon** [comment]
- The mob stacking would have an on/off option like the rest of mohist's settings.
- This is incorrect, https://github.com/MinimallyCorrect/TickThreading has proven tiles and entities can be ticked on different threads and gain an amazing performance boost.
- It may be implemented in java but mojang and the server softwares available do NOT have multithreading support. Multithreading has been the minecraft communities wet dream since 1.3.2.
- This is true if the CPU on the server cannot handle the increased load, but thats why you have settings to set limits on the min to max amount of threads. But a CPU with 8 cores can handle hundreds of threads running in programs. The average CPU these days comes with 4 cores 8 threads (basically 8 cpus). Shattering this performance limitation based on hardware.

**Comment by kaziu687** [comment]
"Having entities and tile-entities to be ticked off-thread will cause a lot of compatibility issues which may "delete your server". However, it is still worth to have a try." I have fork with that feature, for now testing at production server with no huge issues. Average TPS increased from 6 to 19. I will make pull request next week.

**Comment by TansuoTro** [comment]
I don’t know much about multi-threaded development, 
so I need the assistance of other developers : (
The dev responsible for the multi-threaded version(ThreadPool) is currently going to school. 
when he finishes his studies or other developers are willing to participate in the development of the multi-threaded version, we will speed up the development. :D

sorry my english not very good

**Comment by EverNife** [comment]
@kaziu687 
> "Having entities and tile-entities to be ticked off-thread will cause a lot of compatibility issues which may "delete your server". However, it is still worth to have a try." I have fork with that feature, for now testing at production server with no huge issues. Average TPS increased from 6 to 19. I will make pull request next week.

Have you had any progress in this?

**Comment by Trackhe** [comment]
Which of the changes are already in 1.16.4 or which changes would also be possible in 1.16.4? Or are they already included?

**Comment by EverNife** [comment]
(Almost) None of these changes are easy to be done.

(edit)
The one with highest impact on performance is still the Multithread, its the hard one to be achieved as well :D
