### ISSUE TITLE
[1.16.5] Create mod Belts sometimes wipe out items

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#1332]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {561}

**Operating System :** {Ubuntu}

**Concerned mod** : {Create mod 0.3.1c}

**Steps to Reproduce :**
 1. Have a block on the end of the conveyor belt like this
 
![2021-05-12_23 46 52](https://user-images.githubusercontent.com/46825658/118048466-9ca04d80-b37c-11eb-906c-7f120fa47360.png)

 2. Throw an item (with the belt direction going into the block)
 3. Watch until it despawns

**Description of issue :** {The item has a probability of dissapearing, making it impossible to do certain farms, as some items get lost. Not only happens on the display shown on the photo i think, I have had issues with items dissapearing on big farms, which had a lot of belts. So maybe the issue comes from the belts}

**Comment by Mgazul** [comment]
use create-mc1.16.5_v0.3.2a

**Comment by muriplz** [comment]
The problem got solved on 0.3.2x i think, my bad
