### ISSUE TITLE
[Mohist 566 & ProtocolLib] AdvancedGui and Cartographer2 ERROR

### ISSUE THREAD

**Issue by Scrulius** [Teneted/Tenet#1335]
The error appears when you try to create an advancedgui or when you try to get a map from Cartographer2

![image](https://user-images.githubusercontent.com/43689161/118149692-133b5a80-b412-11eb-9cfb-fe959e27004e.png)

**Comment by Shawiizz** [comment]
Hi, please edit your issue to follow the issue template.
