### ISSUE TITLE
the dragon egg dispawn on hit

### ISSUE THREAD

**Issue by starnakin** [Teneted/Tenet#1336]
**Minecraft Version :** {Minecraft version}

**Mohist Version :** {Provide Mohist build number}

**Operating System :** {Provide the name of your OS}

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by KR33PYK1NG** [comment]
Format your issue appropriately.
