### ISSUE TITLE
[MOHIST 575]  You can't dye sheep

### ISSUE THREAD

**Issue by Scrulius** [Teneted/Tenet#1339]
Minecraft Version : 1.16.5

Mohist Version : 575 

Operating System : Debian

Logs : [12:34:04 FATAL]: Error executing task on Server

Steps to Reproduce :
 1. dye sheep
 2. error in console

Description of issue : Try to dye any sheep with any dye and an error will appear on the console.

**Comment by Eriador26** [comment]
I have been testing and on version 549 it was still possible and on version 550 it broke. I hope this helps with searching the error.
