### ISSUE TITLE
[1.12.2] World corrupts at 10k on 3 different servers.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#134]
Ive pregenerated my servers over and over and every time i do it has chunk corruption past the 10k coordinates. This has happened on 3 different servers with different modpacks. RLCraft, Tekxit 3, and 1.12.2 Pack.

The worlds were pre-generated using the mod ChunkPregenerator.

All of the biomes, noise generation (height), weather, etc... Are all screwed up as you can see in this pic.
![Screenshot_411](https://user-images.githubusercontent.com/3002248/76158153-8d15dc80-60c7-11ea-91b5-a0224e137eb5.png)
![Screenshot_412](https://user-images.githubusercontent.com/3002248/76158227-88055d00-60c8-11ea-99a5-1f064cb5ef50.png)
![Screenshot_413](https://user-images.githubusercontent.com/3002248/76158229-89368a00-60c8-11ea-97d4-6bf7cbe917fb.png)

**Comment by ishland** [comment]
Please test with only ChunkPregenerator installed.

**Comment by Zilacon** [comment]
Yeah, you can go do that.
1.56 million chunks.
Took mohist 1 week to complete.

**Comment by Zilacon** [comment]
Generating the world using WorldBorder plugin on Bukkit does not have this issue. Its only with Mohist/ChunkPregenerator mod.

**Comment by Krosta8** [comment]
I just saw your issue and was shocked. I'm using Chunk Pregenerator with Mohist too (200kx200k map) and I looked in to it. I have everything correct, as far as I can see (using Mohist build 435 - 5.4. 13:31)

**Comment by Zilacon** [comment]
@Krosta8 Then it will corrupt beyond the 200k border. Although generating that is going to take you weeks if not months.

Basically whatever size you set the chunkpregenerator to generate to, beyond that set size is corrupted. So 0-200k will look normal but when you get to 200,001 coords the biomes will slive off and height map be completely different, and chunks having their own seperate biomes and stuff.

**Comment by Krosta8** [comment]
For me this is okay as far as I can see. I also tried to travel more then 200 blocks outside of the border, can't see any problem. And my pregenerator is doing around 200 chunks/t
https://imgur.com/a/9OFMHkY
