### ISSUE TITLE
[1.16.5] Mixin Error with Valhelsia Structures

### ISSUE THREAD

**Issue by Charismara** [Teneted/Tenet#1340]
**Minecraft Version :** 1.16.5

**Mohist Version :** 575

**Operating System :** Tested on Windows 10 & Linux

**Concerned mod / plugin** : [Valhelsia Structures 1.16.5-0.1.0](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures/files)

**Logs :** [lastest.log](https://pastebin.com/Kt3yifBy)

**Steps to Reproduce :**
 1. Install the Mod
 2. Start the Server

**Description of issue :** Crashed the Server without crash report.

**Comment by Charismara** [comment]
Still Happening in:
Mohist Version: <=598
Mod Version 0.1.1

**Comment by Charismara** [comment]
Still Happening in:
Mohist Version: 577
Mod Version 0.1.1

**Comment by Charismara** [comment]
Still Happening in:
Mohist Version: 578
Mod Version 0.1.1

**Comment by kencinder** [comment]
Posting that every single build doesn't work doesn't help...it's just annoying, try reading changelogs on builds.

**Comment by kencinder** [comment]
https://github.com/MohistMC/Mohist/issues/1340
