### ISSUE TITLE
Patchwork? Support Forge and Fabric together.

### ISSUE THREAD

**Issue by Trackhe** [Teneted/Tenet#1344]
Is it possible that mohist adopt the Patchwork projekt?
https://patchworkmc.net/

**Comment by Shawiizz** [comment]
What do you mean ?

**Comment by Trackhe** [comment]
I mean support forge and fabric mods together. In mohist
because nice mods like buildcraft make their update fpr 1.16.5 only for fabric

**Comment by Shawiizz** [comment]
We don't plan to make any project about Forge + Fabric or Bukkit + Fabric etc.

**Comment by Shawiizz** [comment]
I think you meant having a software with Forge + Fabric + Bukkit ?

**Comment by Trackhe** [comment]
Why not? I mean you could learn from https://patchworkmc.net/ hot it is possible

> with Forge + Fabric + Bukkit ?

only forge and fabric = https://patchworkmc.net/

And i want forge fabric bukkit yes

**Comment by Trackhe** [comment]
> with Forge + Fabric + Bukkit ?

only forge and fabric = https://patchworkmc.net/

**Comment by Trackhe** [comment]
And i want forge fabric bukkit yes

**Comment by Shawiizz** [comment]
We already have Mohist 1.12.2 and 1.16.5, and that's already a lot of work and Mohist 1.16.5 needs a lot of work too since it's not completely stable. We don't plan to make any Forge fabric bukkit software, but in a very distant future (in few years maybe), why not :shrug:
