### ISSUE TITLE
[1.12.2] ConcurrentModificationException in EntityTracker

### ISSUE THREAD

**Issue by Michael-Hozza** [Teneted/Tenet#1345]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-216

**Operating System :** Debian

**Logs :** https://pastebin.com/HiH6NPNP

**Mod list :** 
noadvancements, moretweaker, buildcraftenergy, bbop, morerefinedstorage, draconicevolution, contenttweaker, thermalinnovation, bettercaves, armoryexpansion-matteroverdrive, jeibees, forgelin, microblockcbe, randompatches, darkutils, morpheus, ftblib, mcmultipart, refinedstorage, industrialforegoing, unidict, openterraingenerator, biomesoplenty, redstoneflux, buildcraftsilicon, modtweaker, gendustry, projectred-core, ic2, buildcraftbuilders, itemblacklist, jepb, buildcraftfactory, topaddons, otgcore, projectred-fabrication, teslacorelib, FML, storagedrawersunlimited, thermalexpansion, projectred-integration, buildcraftcompat, cfm, oredictinit, forgemultipartcbe, armoryexpansion-custommaterials, ic2-classic-spmod, customstartinggear, codechickenlib, fastleafdecay, dynamictrees, netherex, industrialwires, binniedesign, justenoughdimensions, cctweaked, tinkersextras, projectintelligence, supersoundmuffler, jei, attributefix, careerbees, warsftbdynmap, tesseract, bibliocraft, xtones, thermalfoundation, bdlib, notenoughwands, csb_ench_table, plethora-core, sereneseasons, chameleon, alternatingflux, conarm, extrabees, clickmachine, crafttweaker, armoryexpansion, ido, immersivepetroleum, forge, ftbutilities, retrobees, ironchest, minecraft, dupefixproject, logisticsbridge, theoneprobe, ftbquests, thermaldynamics, immersiveengineering, applecore, extrautils2, mantle, tnt_utilities, libraryex, gendustryjei, mrtjpcore, offlineskins, appleskin, minecraftmultipartcbe, login_shield, nevokacore, bookworm, tweakersconstruct, gravisuit, spiceoflife, refinedstoragerequestify, dynmapblockscan, forestry, base, buildcraftlib, cyclopscore, tconevo, p455w0rdslib, netherportalfix, hats, binniecore, universalmodifiers, fantasticlib, cofhcore, lttweaker, tickprofiler, immersivecables, reborncore, cookingforblockheads, placebo, bookshelf, RenderPlayerAPI, uteamcore, projectred-illumination, cofhworld, progressivebosses, sonarcore, gtc_expansion, plethora, mcjtylib_ng, twilightforest, immersivetech, extratrees, rebornstorage, tinkertoolleveling, usefulbackpacks, commoncapabilities, crafttweakerjei, ping, signpost, botany, mtlib, valkyrielib, libnine, energyconverters, sasit, helpfixer, teslacorelib_registries, patchouli, projectred-transmission, endreborn, elevatorid, gunpowderlib, environmentaltech, computercraft, emotes, gtclassic, seasonal_bees, buildcraftcore, danknull, tesla, cucumber, mohist, draconicadditions, extrabitmanipulation, itemfilters, buildcrafttransport, pamscookables, waystones, mcp, clumps, journeymap, morelibs, surge, harvestcraft, foamfixcore, eventhelper, bouncy_creepers, moartinkers, ichunutil, enderstorage, projectred-compat, brandonscore, buildcraftrobotics, armoryexpansion-conarm, tconstruct, dynmap, baubles, genetics, integrationforegoing, vanillafix, jaopca, fluxnetworks, storagedrawers, wrapup, wanionlib, chisel, armoryexpansion-iceandfire, solcarrot, foamfix, tinkersjei, mjrlegendslib, tnt_utilities_core, refinedstorageaddons, practicallogistics2, logisticspipes, tickdynamic, chiselsandbits, morebees

**Plugin list :** 
AnimatedNames, BukkitLogger, BungeeTabListPlus, ChatControlRed, ChestShop, ClearLag, CoreProtect, DiscordSRV, Economy, Essentials, EssentialsSpawn, GAListener, InventoryRollback, IPWhitelist, LiteBans, LuckPerms, MVdWPlaceholderAPI, OpenInv, PlaceholderAPI, Plan, PlugMan, ProtocolLib, RandomTeleports, scriptcraft, skRayFall, Skript, spark, Stats, SuperVanish, Vault, Votifier, WorldEdit, WorldGuard

**Description of issue :** Everyday twice or three times server crashes by this unknown issue, tickdynamic is not an issue because it was not installed when this crash first time occured. I don't know if it's mohist issue, but on plain forge server worked fine. I do have some skills in programming, so if you don't want to dig deeper into this problem, at least i need to know, how to track this kind of issue.

**Comment by Shawiizz** [comment]
Same as #1811
