### ISSUE TITLE
[1.16.5] Pehkui crashing again on startup

### ISSUE THREAD

**Issue by kellyharry** [Teneted/Tenet#1351]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {578}

**Operating System :** {Windows}

**Logs :** {https://pastebin.com/ZMeagX5N

**Mod list :** {Pehkui}

**Plugin list :** {None}

**Description of issue :** {Something to do with a fox from the looks of the logs.}

**Comment by AstralDestiny** [comment]
You're running the beta build of Pehkui. Please try the Release version.

**Comment by kellyharry** [comment]
> You're running the beta build of Pehkui. Please try the Release version.

There is no release version of Pehkui for Forge only beta. The rest of the releases Mohist skips over as they are the fabric versions.

**Comment by AstralDestiny** [comment]
Ah I see, Though there is comments about the forge version being broken currently.

**Comment by kellyharry** [comment]
> Ah I see, Though there is comments about the forge version being broken currently.

Im running a default forge server with Pehkui installed and it works just fine, Though as soon as its in with Mohist it crashes
