### ISSUE TITLE
[1.12.2]Black screen appears

### ISSUE THREAD

**Issue by 1446738647** [Teneted/Tenet#1355]
I edited the server.properties file,change allow-nether to false, but when i enter the nether portal ,i can't move in others' view even thought i move around him.when i leave the server and enter again ,black screen appears and i can't Rotate my angle of view or move，i leave and enter again everything‘s back to normal.

**Comment by SparkGNRK** [comment]
Why entering nether if disabled? You can't enter anymore the nether if disabled on mohist build 307.
