### ISSUE TITLE
Aternos on Mohist 1.16.5(598)

### ISSUE THREAD

**Issue by Miz04** [Teneted/Tenet#1368]
Sorry but Aternos has again upgrade from the 594 to the 598 and now it's not starting again 

https://github.com/MohistMC/Mohist/issues/1365

and it gives me the same crash log as my last bug report...

**Comment by Shawiizz** [comment]
I'm trying that

**Comment by Miz04** [comment]
yes but why does aternos has upgrade that again!?

**Comment by Shawiizz** [comment]
Because we thought the error was fixed, but don't worry, i fix this when I get home

**Comment by Miz04** [comment]
Ah ok!👍

**Comment by Miz04** [comment]
Thank you soooo much now is working perfectly!!!
