### ISSUE TITLE
[1.12.2] error with actually additions worms

### ISSUE THREAD

**Issue by koranoob** [Teneted/Tenet#137]
### Desciption
When you try to place worm on the ground. (Result you can't place them)

### Crashreport
Pastebin: [error](https://pastebin.com/CiVE9ym4)

### Information
Modpack: MC.Eternal
Mohist version: Mohist-a54f23a
Related mod version: ActuallyAdditions-1.12.2-r151-2

**Comment by Irgendwer01** [comment]
Still reproduceable in latest version
