### ISSUE TITLE
[1.16.5]Server crashed with KemonoCraft only.

### ISSUE THREAD

**Issue by sweetapple-233** [Teneted/Tenet#1370]
Just Mohist and KemonoCraft mod,no plugin or anyelse.Then server crashed.
Same problem has been reported to kemonocraft author too.
KemonoCraft : https://www.mcbbs.net/thread-856743-1-1.html /  https://www.curseforge.com/minecraft/mc-mods/kemonocraft
Game version:1.16.5
Forge version:1.16.5-36.1.24
KemonoCraft version:1.16.4-0.3.18
Mohist version:1.16.5-598
There's crash-report and latest log : https://paste.ubuntu.com/p/wvQCk9xjZy/ https://paste.ubuntu.com/p/JVZWFSPjk7/
Thanks for helping!

**Comment by Mgazul** [comment]
https://github.com/MohistMC/Mohist/commit/9f2a9bd7477b42062acacfade9a59ee117293a53
