### ISSUE TITLE
[1.16.5] Entities drop loot, but won't drop XP.

### ISSUE THREAD

**Issue by Dvitash** [Teneted/Tenet#1372]
**Minecraft Version :** 1.16.5

**Mohist Version :** 601

**Operating System :** Win10

**Logs :** no logs

**Mod list :** https://pastebin.com/8TAnx15b

**Plugin list :**none

**Description of issue :** Mobs will drop loot (such as bones and arrows), but no XP

**Comment by dariopf** [comment]
In which version this error is solved?

**Comment by Shawiizz** [comment]
Latest
