### ISSUE TITLE
[1.16.5] Error with func_232644_a_#getDefaultRespawnWorld

### ISSUE THREAD

**Issue by Acult** [Teneted/Tenet#1380]
**Minecraft Version :** 1.16.5

**Mohist Version :** 603

**Concerned mod / plugin** : 
- [LOTR MOD RENEWED 4.0.3](https://www.mediafire.com/file/jd30xwttaibknx1/lotr-1.16-renewed-4.0.1.jar/file)

**Logs :** 
- https://paste.ubuntu.com/p/fyTwFYVpzC/

**Steps to Reproduce :**
 1. Latest mohist 1.16.5 build
 2. Run LOTR MOD RENEWED 4.0.3 (link above)

**Description of issue :** 
A null pointer exception while trying to apply lotr-transformer-respawning.js function PlayerList#func_232644_a_#getDefaultRespawnWorld

**Comment by Acult** [comment]
Each time i join my world, i get respawned 7 blocks under the surface, that's probably related to this issue

**Comment by Mgazul** [comment]
Please use Mohist#594 to test if the problem exists

**Comment by Mgazul** [comment]
Don't use ubuntu
