### ISSUE TITLE
[1.16.5] Critical injection failure: Callback method valhelsia_placeDousedTorch

### ISSUE THREAD

**Issue by milescluce** [Teneted/Tenet#1387]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {606}

**Operating System :** {Windows}

**Concerned mod / plugin** : {Windows}

**Logs :** {https://pastebin.com/G8mKYJ4G}

**Steps to Reproduce :**
 1. Use Mods and Config for Cottage Core 2.2.0 https://www.curseforge.com/minecraft/modpacks/cottage-craft

**Description of issue :** {Seems that Valhesia Structures conflicts with Mohist. When removed, the server works fine. I would like to include the mod, though.}

**Comment by Romaindu35** [comment]
Please update your log link (page not found)

**Comment by GrigLog** [comment]
Ive got the same problem. Logs from clear forge server with just Valhelsia and Mohist installed.
[latest.log](https://github.com/MohistMC/Mohist/files/6565161/latest.log)

**Comment by GrigLog** [comment]
Also the pastebin link is valid, just remove } from the end

**Comment by kencinder** [comment]
https://github.com/MohistMC/Mohist/issues/1340
