### ISSUE TITLE
[1.16.5] Spigot/Paper BlockDropItemEvent does not fire

### ISSUE THREAD

**Issue by KaktuszSok** [Teneted/Tenet#1388]
Hi, I tested this on the newest versions for both spigot and paper mohist (1.16.5-614 and 1.16.5-3 respectively). My function listens for a BlockDropItemEvent and broadcasts a message when it is received. On mohist, this event doesn't seem to fire at all, no errors etc. The event works on normal spigot but is not in a great state as can be seen here https://hub.spigotmc.org/jira/browse/SPIGOT-5719.

My specific problem is that I am trying to make a banner indestructible. In 1.16 and later, banners break when their state is updated and their supporting block is missing. Cancelling the appropriate BlockPhysicsEvent has no effect. This is why I am trying to use the BlockDropItemEvent instead. Even in normal spigot this proves to be an issue due to the reasons outlined in my comment in the aforementioned link. Either way, mohist does not fire this event at all which is even more of a problem. I imagine this is something that will need to be fixed on both sides.

**Comment by Mgazul** [comment]
fixed
