### ISSUE TITLE
[1.16.5] lithium fork crash

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1390]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5 Paper **#4**

**Operating System :** Unbuntu 20

**Concerned mod / plugin** : lithium-forge **`https://github.com/jamierocks/lithium-forge/tree/0.6.3-1`**

**Logs :** https://paste.ubuntu.com/p/ky8n3chMKQ/

**Steps to Reproduce :**
 1. Start server

**Description of issue :** Mod cannot run on Mohist due to mixin error

**Comment by Romaindu35** [comment]
Are you this error with 1.16.5#611 ?

**Comment by ghost** [comment]
> Are you this error with 1.16.5#611 ?

don't work

**Comment by KR33PYK1NG** [comment]
Paper branch is now archived. Use default 1.16.5 branch.
