### ISSUE TITLE
[1.16.5 Paper] Perfomant crash

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1392]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5 Paper **#4**

**Operating System :** Unbuntu 20

**Concerned mod / plugin** : performant-1.16.2-5-3.64m **`https://www.curseforge.com/minecraft/mc-mods/performant`**

**Logs :** https://paste.ubuntu.com/p/y4QYrNnYRt/

**Steps to Reproduce :**
 1. Start server

**Description of issue :** 
crash on laucnh

**Comment by Romaindu35** [comment]
Are you this error with 1.16.5#611 ?

**Comment by ghost** [comment]
> Are you this error with 1.16.5#611 ?

don't work

**Comment by Mgazul** [comment]
Only appears in the paper branch

**Comment by KR33PYK1NG** [comment]
Paper branch is now archived. Use default 1.16.5 branch.
