### ISSUE TITLE
[1.16.5] Dynamic Trees Traverse crash

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1393]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5 Paper **#4**

**Operating System :** Unbuntu 20

**Concerned mod / plugin** : DynamicTreesTraverse-1.16.5-2.2.0.jar **`https://github.com/jamierocks/lithium-forge/tree/0.6.3-1`**

**Logs :** 
[crash-2021-05-30_10.48.25-fml.txt](https://github.com/MohistMC/Mohist/files/6565938/crash-2021-05-30_10.48.25-fml.txt)

**Steps to Reproduce :**
 1. Start server

**Description of issue :** Crash on launch

**Comment by Romaindu35** [comment]
Are you this error with 1.16.5#611 ?

**Comment by ghost** [comment]
> Are you this error with 1.16.5#611 ?

don't work

**Comment by Mgazul** [comment]
Mod dttraverse requires dynamictrees 0.10.0-Beta10 or above Currently, dynamictrees is not installed
