### ISSUE TITLE
[1.16.5] FTB janitor crash

### ISSUE THREAD

**Issue by liampearson96** [Teneted/Tenet#1394]
https://pastebin.com/wUdT18sY

**Minecraft Version :1.16.5
**Mohist Version :mohist-1.16.5-4-server.jar

**Operating System :linux

**Concerned mod / plugin** :FTB janitor

https://pastebin.com/wUdT18sY
https://pastebin.com/wUdT18sY
https://pastebin.com/wUdT18sY

**Steps to Reproduce :**
 1. load up server with mohist-1.16.5-4
 2. wait for server to crash with ftb janitor installed

**Description of issue :** Server Crashes upon loading due to mohist and ftb janitor

**Comment by Romaindu35** [comment]
Are you this error with 1.16.5#611 ?

**Comment by liampearson96** [comment]
> Are you this error with 1.16.5#611 ?

I have tried -614 and -611, also the latest on the website.

They all crash

**Comment by Mgazul** [comment]
Where can I download FTB janitor
