### ISSUE TITLE
615 doesn't load, says a bunch of mods require certain versions of mods or above, yet those mod versions are fine.

### ISSUE THREAD

**Issue by IITFA** [Teneted/Tenet#1395]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {615}

**Operating System :** {AntiX Linux Headless}

**Logs :** {https://pastebin.com/raw/gJqyzEdH}

**Mod list :** {https://pastebin.com/raw/61VCiHTR}

**Plugin list :** {none}

**Description of issue :** {Server fails to start. Claims mods need certain versions of other mods but all mod versions are fine, the whole mod setup was tested on plain Forge server prior to testing Mohist.}

**Comment by Romaindu35** [comment]
can you send the crash report : _crash-2021-05-30_21.43.08-fml.txt_ ?

**Comment by IITFA** [comment]
Here is that crash report.
https://pastebin.com/raw/hxWtBhWJ

**Comment by Mgazul** [comment]
This has nothing to do with mohist, please update all your mods to the latest version

**Comment by IITFA** [comment]
I am curious how this is not a Mohist issue? I updated all the mods and it fixed the issue, but that doesn't explain how a plain Forge server loaded the previous modpack with no issues but Mohist can't. This is mostly for curiosity and educational reasons that I want to know. Thank you.
