### ISSUE TITLE
Strange behavior after shutting down server, not sure if for sure a Mohist issue, read description.

### ISSUE THREAD

**Issue by IITFA** [Teneted/Tenet#1399]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {615}

**Operating System :** {AntiX Linux headless}

**Logs :** {n/a}

**Mod list :** {https://pastebin.com/raw/z4UmC32K}

**Plugin list :** {none}

**Description of issue :** {While playing around with Mohist after fixing the previous mod issue (thank you), I have noticed something strange that has not happened with any other server. If I load Mohist and once loaded do the stop command to shut down the server, once it finishes and returns to the prompt, I can no longer type anything in the prompt until I force close the ssh connection then reconnect. This happens every time. I don't know for sure if this is a Mohist issue or some other issue, but Mohist is the only server software this happens with. Catserver, Spigot, and plain Forge servers do not do this on shutting down. I have used Mohist before (1.12) and it didn't do this either on the same setup (AntiX headless), so I am presuming this might be an issue with the Mohist for 1.16. Thank you.}

**Comment by Mgazul** [comment]
pastebin Not Found (#404)

**Comment by TheOriginalCER06** [comment]
> pastebin Not Found (#404)

working link:
https://pastebin.com/raw/z4UmC32K

Think I found pastebin, the "}" counted in link, thus making it illegitimate, now shows a bunch of plugins in a list.
