### ISSUE TITLE
[1.12.2] FTB Ranks dont works

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#1401]
**Minecraft Version :** 1.12.2

**Mohist Version :** 225

**Operating System :** Windows 10/Lunix

**Concerned mod / plugin** : FTB Utilities

**Logs :** No.

**Steps to Reproduce :**
 1. Install FTB Utulities
 2. Type /ranks create
 3. Nothing. (This feature disabled on server!)<-- Text in chat.

**Description of issue :** no ranks are created

**Comment by Mgazul** [comment]
#1103

**Comment by Exzept1on** [comment]
@Mgazul When approximately you can expect a fix for this bug. It's just that I and my community are creating a server that is based on FTB mods. We used to use pure Forge, but now we need plugins, but the FTB Utils(ranks) does not work on Mohist.

**Comment by FullGreenGN** [comment]
Same
