### ISSUE TITLE
[1.16.5] Create - Moving Contraptions  with chest not gain items.

### ISSUE THREAD

**Issue by SeaLoong** [Teneted/Tenet#1403]
**Minecraft Version :** 1.16.5

**Mohist Version :** 604, 606, 611, 617, 618, 622 tested

**Operating System :** Windows 10

**Concerned mod / plugin** : [Create](https://github.com/Creators-of-Create/Create)0.3.1c

**Logs :** No logs

**Steps to Reproduce :**
 1. Build a Moving Contraptions with a chest and a Mechanical Harvester/Mechanical Saw.
 2. Let the Moving Contraptions be moving and the Mechanical Harvester/Mechanical Saw should work. Some items(such as carrots) should be gain, and it should be in a container(in this example, it's a chest).
 3. Stop moving the Moving Contraptions.
 4. Check the chest, it's empty.

Video of Reproducing: [Personal Netdrive share link](http://sealoong.top:40001/s/38rIY)

**Description of issue :** 
I have tested in different versions/builds. It is work with forge only, but not work with Mohist or Arclight. May the upstream break something?

**Comment by muriplz** [comment]
The solution for this right now is to use barrels instead of chests, the error is already reported #1180

**Comment by KubiRemPL** [comment]
can confirm
