### ISSUE TITLE
[1.16.5] when apply valhelsia structures

### ISSUE THREAD

**Issue by chan1253** [Teneted/Tenet#1404]
**Minecraft Version :** Minecraft version 
1.16.5
**Mohist Version :** Provide Mohist build number
618
**Operating System :** Provide the name of your OS
windows
**Concerned mod / plugin** : Provide mod / plugin name and download link if possible
valhelsia structure
**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Do this Just put the valhelsia structure mod in your mohist bucket
 2. Then do that 
 3. ...

**Description of issue :** Give all details about your issue
Bucket does not start when applying valhelsia structure mod
[2021-06-02-1.log.zip](https://github.com/MohistMC/Mohist/files/6582638/2021-06-02-1.log.zip)
, thank you for fixing this error

**Comment by kencinder** [comment]
https://github.com/MohistMC/Mohist/issues/1340
