### ISSUE TITLE
[1.16.5] WorldEdit //replace comand not working when adding mods

### ISSUE THREAD

**Issue by MCEventHorizon** [Teneted/Tenet#1415]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-625

**Operating System :** Windows 10

**Concerned mod / plugin** : WorldEdit

**Steps to Reproduce :**
 1. Add any mod to the mods folder(I think it's related to mods that add block IDs specifically)
 2. Try to use //replace command with 2 arguments(for example //replace 1 3)
 3. It will always say 0 blocks replaced

When I run Mohist alone with WorldEdit, //replace command works normally but after I added mods(tried adding just Biomes O'Plenty and then just MrCrayfish Furniture mod), the command always says "0 blocks replaced". That's why I think it's some issue with IDs. Also when I remove the mods I have to also replace the world for it to work again.

**Comment by KR33PYK1NG** [comment]
You have to also install WorldEdit mod alongside with the plugin.

**Comment by MCEventHorizon** [comment]
I tried that and it's still not working.

**Comment by Romaindu35** [comment]
You can use the plugin fix

**Comment by MCEventHorizon** [comment]
> 
> 
> You can use the plugin fix

Sorry, but I don't know what that is.

**Comment by Romaindu35** [comment]
https://discord.com/channels/311256119005937665/747808399634202706/851546808597086208

**Comment by Romaindu35** [comment]
or just start the game with lastest build
