### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by lujo777** [Teneted/Tenet#1419]
**Minecraft Version :** 1.16.5

**Mohist Version :** #629

**Operating System :** Debian 9

**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/6619495/latest.log)

**Mod list :** ![image](https://user-images.githubusercontent.com/34795882/121254513-03991f80-c8b3-11eb-9524-ee1c8a74c4b6.png), 
![image](https://user-images.githubusercontent.com/34795882/121254569-16135900-c8b3-11eb-8a7c-83a28d2abdf1.png), 
![image](https://user-images.githubusercontent.com/34795882/121254604-21668480-c8b3-11eb-9b13-51332833c342.png)

**Plugin list :** LockLogin, SkinsRestorer

**Description of issue :** Didn't find any error trace at all. Server stops at startup

**Comment by Romaindu35** [comment]
Are you a file in datapack directory ?

**Comment by lujo777** [comment]
I only uploaded mods into folder and started server up. No changes in other directories

**Comment by KR33PYK1NG** [comment]
Could be that one of the mods registers datapacks incorrectly. I would suggest trying removing mods one by one until you get to the source of this issue.
