### ISSUE TITLE
[1.16.5] ChunkManager deadlock

### ISSUE THREAD

**Issue by bigenergy** [Teneted/Tenet#1420]
**Minecraft Version :** 1.16.5

**Mohist Version :** 629

**Operating System :** ubuntu

**Logs :** https://pastebin.com/5LQAuQTT

**Comment by Romaindu35** [comment]
This work with lastest build ? (1.16.5#634)

**Comment by bigenergy** [comment]
> This work with lastest build ? (1.16.5#634)

No, https://paste.ubuntu.com/p/jKHfRQFCW8/

**Comment by Romaindu35** [comment]
Are you this error with build#626 ?

**Comment by bigenergy** [comment]
> Are you this error with build#626 ?

636 has the same error

**Comment by bigenergy** [comment]
https://pastebin.com/2rEGYW0H
maybe related this

**Comment by Romaindu35** [comment]
I can reproduce this bug with lastest build

**Comment by bigenergy** [comment]
> I can reproduce this bug with lastest build

https://paste.ubuntu.com/p/YhZJtwxksc/
build 661

**Comment by Romaindu35** [comment]
Same #1463
