### ISSUE TITLE
[1.16.5] Plugins do not save the last coordinates.

### ISSUE THREAD

**Issue by Scrulius** [Teneted/Tenet#1427]
All plugins that use /back, /dback or some way to save your last position are getting errors.

I have tried CMI and DeathCoordinates, in previous versions of mohist it worked and I have tried on a paper server without mods and it works.

I don't know if you have changed anything, but it is quite important since the /back is an important feature for the players.

Thank you very much.

Mohist version: 632
Minecraft version: 1.16.5
Mods: Tested without mods

**Comment by Romaindu35** [comment]
Can you send errors ?

**Comment by Kotori0629** [comment]
> Can you send errors ? 

#1409 Duplicate，I also had this problem, After testing, I found that the PlayerDeathEvent was not posted

**Comment by Kotori0629** [comment]
> Can you send errors ? 

This bug haven't logs/debug, You may have to check LivingEntity.java/ServerPlayerEntity.Java

**Comment by Scrulius** [comment]
> Can you send errors ?

Hello! sorry for taking so long to reply, it doesn't generate any error in console :(

**Comment by Kotori0629** [comment]
> > Can you send errors ?
> 
> 
> 
> Hello! sorry for taking so long to reply, it doesn't generate any error in console :(
> 
> 

No！This Problem not have error. EntityDeathEvent instead of PlayerDeathEvent, CMI's Listen is PlayerDeathEvent.

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/121760918-ba212c80-cb5f-11eb-8c98-8612c05f1b49.png)
Maybe you need this debug code

**Comment by Romaindu35** [comment]
The problem is that PlayerDeathEvent is never call ?

**Comment by Kotori0629** [comment]
> The problem is that PlayerDeathEvent is never call ?

Yep

**Comment by Scrulius** [comment]
Bump

This is very important, I could pay if necessary for you to fix it.

Thanks!

**Comment by Kotori0629** [comment]
> Bump
> 
> This is very important, I could pay if necessary for you to fix it.
> 
> Thanks!

I've fixed the problem. 
![image](https://user-images.githubusercontent.com/81866089/122267456-7cc8f000-cf0d-11eb-9060-1fcdcbfbadba.png)
@Romaindu35

**Comment by Kotori0629** [comment]
If you think this method is feasible, please write it manually

**Comment by Matthew-MBG** [comment]
le bump

**Comment by Kotori0629** [comment]
[Loli-Server/LoliServer1.16@ca141c2](https://github.com/Loli-Server/LoliServer1.16/commit/ca141c2fbf0479762459fc5b6978468d12a03b1a)

**Comment by Kotori0629** [comment]
Originally, I didn't want to help solve it, but later I found that there was a problem, so I repaired it @Mgazul @Shawiizz @Romaindu35

**Comment by Romaindu35** [comment]
Can we port this commit in Mohist ?

**Comment by Kotori0629** [comment]
Sure
