### ISSUE TITLE
[1.16.5] paper errors

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1428]
**Minecraft Version :** 1.16.5

**Mohist Version :**  632

**Operating System :** windows 10

**Concerned mod / plugin** : https://mclo.gs/T1k48Cp

**Logs :** https://mclo.gs/cqt9LNf

**Steps to Reproduce :**
 1.  start server and waiting
 
**Description of issue :** i am use plugins, no have mods.

**Comment by Romaindu35** [comment]
Same #1420

**Comment by joaoespanhol** [comment]
> Same #1420

Sorry :(

**Comment by Romaindu35** [comment]
No problem :)
