### ISSUE TITLE
Switch to bStats' "Sever Implementation" category

### ISSUE THREAD

**Issue by Bastian** [Teneted/Tenet#143]
I've noticed that you use a modified version of the Metrics class to submit your stats to bStats.
Please do switch to the special "Server Implementation" category and update the Metrics class accordingly.
I've created the plugin for you and added it to your bStats account: https://bstats.org/plugin/server-implementation/Mohist/6762

Please see https://github.com/PaperMC/Paper/issues/646#issuecomment-293876337 for more information. I would also recommend to take a look at Paper's implementation for the custom charts: https://github.com/PaperMC/Paper/blob/19de9af63c98137a8bbfe9b0550bb30c3d6da7df/Spigot-Server-Patches/0005-Paper-Metrics.patch#L569-L647

Thank you!
Feel free to ask, if you have any further questions.

**Comment by Mgazul** [comment]
Thanks for your proposal.

**Comment by Bastian** [comment]
Wow, that was quick!
Thanks for switching!
