### ISSUE TITLE
[1.16.5] Cannot load server

### ISSUE THREAD

**Issue by Sam-Chai** [Teneted/Tenet#1430]
**Minecraft Version :** 1.16.5

**Mohist Version :** #360

**Operating System :** Windows 10

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** just alex's mobs

**Plugin list :** nope

**Description of issue :** 
Cannot load Server data pack when start mohist.
```
Found validation problem in {alexsmobs:gameplay/seal_reward}.pools[0].entries[1].functions[0]: Parameters [<parameter minecraft:origin>] are not provided in this context
[15:11:08 WARN]: 无法加载数据包并启动服务器，尝试修复数据包或使用“--safeMode”参数重置数据包为原版
```
Only have alex's mobs mod. And I turn on "--safeMode" on start script also cannot start server.

**Comment by Sam-Chai** [comment]
latest build cannot load either.

**Comment by Dokman** [comment]
you have installed Citadel library mod?
PS: In my end is working well.

**Comment by Sam-Chai** [comment]
> you have installed Citadel library mod?
> 
> PS: In my end is working well.


Yeah. I installed Citadel

**Comment by Dokman** [comment]
I cannot reproduce it

**Comment by joaoespanhol** [comment]
has been fixed with last update
@Romaindu35
