### ISSUE TITLE
Mohist fails to build ; forge:compileJava fails while building

### ISSUE THREAD

**Issue by Arthurmeade12** [Teneted/Tenet#1432]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {Latest build 637}

**Operating System :** {MacOSX}

**Mod list :** {No mods}

**Plugin list :** {none}

**Description of issue :** {
When I attempted to build Mohist, it seems that the forge:compileJava Task failed while building. I have attached google drive link to a video of myself cloning the repo, making sure I'm running java 11, and then attempting to build. 
[link](https://drive.google.com/file/d/1_vm_NbY0ZpC05T-Bwsq5IMBSrHYgWtqA/view?usp=sharing)
}

**Comment by Shawiizz** [comment]
./gradlew setup
./gradlew mohistJar
