### ISSUE TITLE
Cannot run mohist using Java 16

### ISSUE THREAD

**Issue by H4kt** [Teneted/Tenet#1439]
**Minecraft Version :** 1.16.5

**Mohist Version :** 646

**Operating System :** Windows 10

**Logs :**
```
Mohist must be ran using Java 11 or higher.
If you want to download Java 11 automatically, print 'Yes'. If not, print 'No'.
The downloaded Java will be used only for this server installation.
No
Ok! Remember, you'll need to install Java 11+ to run Mohist.
```

**Mod list :** none

**Plugin list :** none

**Description of issue :**

**Java info:**
```
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by Shawiizz** [comment]
Java 16 can only be used with Minecraft 1.17. Minecraft 1.16 isn't designed to work with java 16, it's why you must use java 11 or a version under java 16.

**Comment by H4kt** [comment]
Why isn't is stated then?
