### ISSUE TITLE
[1.12.2 - 20a5bb5] NetherEX Issue

### ISSUE THREAD

**Issue by Diamondman121314** [Teneted/Tenet#144]
When using NetherEX, even just by itself, it seems like none of the content added by the mod generates. I've tested this first with Biomes O' Plenty and used the `/bop tpbiome` command to find that it said it couldn't find the four biomes. I then tested it alone to see if it was a BOP issue, but still nothing was generating.
Also, I'm not sure if this information is useful.
![image](https://user-images.githubusercontent.com/22570455/76709087-39605000-66d2-11ea-9cb4-c36b125b307d.png)

**Comment by CraftDream** [comment]
Does the problem exist in Forge for MinecraftServer?

**Comment by Diamondman121314** [comment]
I've tested it with only Forge and the issue does not exist on there.

**Comment by CraftDream** [comment]
This problem does not occur when the client and server of Forge mount NetherEX respectively, does it?

**Comment by Diamondman121314** [comment]
No, everything works fine at that point.

**Comment by CraftDream** [comment]
Is there any error message on Mohist?

**Comment by Diamondman121314** [comment]
Nope, I checked to make sure and there unfortunately was no error.

**Comment by CraftDream** [comment]
But it just doesn't work?

**Comment by Diamondman121314** [comment]
Yep, I loaded the mod with a Mohist server and it flew around the Nether for awhile and nothing loaded. I did this for like 5-7 minutes just to make sure. I then loaded the mod with a Forge server and noticed just about all of the biomes in less than 3 minutes.

**Comment by CraftDream** [comment]
Waiting for fix

**Comment by dawgun** [comment]
Hopefully you can fix it soon, thank you very much for your work.
