### ISSUE TITLE
[1.12.2] Crash avec 

### ISSUE THREAD

**Issue by XxNoobxXfr** [Teneted/Tenet#1445]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-200-server.jar

**Operating System :** J'en sais rien, c'est le serveur x)

**Concerned mod / plugin** : 
- https://www.curseforge.com/minecraft/mc-mods/malisisdoors
- https://www.curseforge.com/minecraft/mc-mods/malisiscore

**Logs :** https://hastebin.com/owudozavav.rb

**Steps to Reproduce :**
 1.  Installez malisisdoor ainsi que sont coremd
 2. Redémarrez son serveur
 3. voilà c'est planté ._.

**Description of issue :** Étrangement, sa à très bien fonctionné durant quelques temps et au redémarrage suivant sa ne fonctionne plus...

**Comment by XxNoobxXfr** [comment]
EDIT : même en retirant les mobs concerné, sa ne fonctionne toujours pas.

**Comment by Shawiizz** [comment]
Hi, please translate your issue in English.
