### ISSUE TITLE
[1.16.5] Epic Fight Mod Incompatibility

### ISSUE THREAD

**Issue by EdwardKnox3099** [Teneted/Tenet#1447]
Minecraft Version : 1.16.5

Mohist Version : 662

Operating System : Windows 10 Pro

Concerned mod / plugin: Epic Fight Mod ( https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files ) 

Logs : https://pastebin.com/LsEhtDeK

**Steps to Reproduce :**
 1. Summon zombie / skeleton / enderman
 2.  Wait that any entity hits you
 3. Server crashes
 
Description of issue : If any entity hits you the server shuts down. All mods of epic fight are imcopatible, the server no start. The unique version that allows me start server is "EpicFightMod-1.16.5-4.0.0-alpha" but shuts down when any entity hits any player.

**Comment by Romaindu35** [comment]
Are you this bug with forge server ?

**Comment by EdwardKnox3099** [comment]
I tested same world and sames mods in forge, there is no problem with forge, this crash only occurs in mohist
