### ISSUE TITLE
[1.16.5]Mohist Server can't play Multiplay...

### ISSUE THREAD

**Issue by Naegiiiii** [Teneted/Tenet#1451]
Hello! I have a problem with the Java version of Minecraft this time, so let me ask you a question. Please forgive me because I can't speak English well.
After updating Java 11, I created a server and tried to play multiplayer, but I get the error "Unable connect to server" and cannot play multiplayer.
The host can enter the server, but no other participants can enter. The cause is unknown, so please let us know if you know the reason.

**Comment by Romaindu35** [comment]
Does the host host his server locally? If so, does he think about opening the ports of his box?

**Comment by joaoespanhol** [comment]
that's not mohist's problem.

can close the ticket please
@Romaindu35
