### ISSUE TITLE
[1.16.5]Neptune’s bounty-Aquaculture

### ISSUE THREAD

**Issue by mem0rz** [Teneted/Tenet#1455]
Hey guys recently I got 10 bounty chest after fishing for about 1 h and 30 mins after putting them down I was so excited to see what I got but when I opened all 10 bounty’s I got nothing literally nothing which sucks please fix this issue cuz I really like aqua culture mod and I really wanna get every tool and piece of armor in aqua culture thank you
简单的就是说水产养殖里那个海王恩惠开不出东西。
https://github.com/TeamMetallurgy/Aquaculture/issues/236
https://github.com/TeamMetallurgy/Aquaculture/issues/204

**Minecraft Version :** {Minecraft version}
1.16.5
**Mohist Version :** {Provide Mohist build number}
latest
**Operating System :** {Provide the name of your OS}
debian 11 linux 5.10
**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by mem0rz** [comment]
Have anyone could solve this bug?
Thank you.

**Comment by XionioXMaster** [comment]
https://github.com/MohistMC/Mohist/issues/1629
Here is more information
