### ISSUE TITLE
[1.16.5] Some commands in BagOfGold v3.0.7 do not work, such as creating an NPC Banker

### ISSUE THREAD

**Issue by AnthonyPaulO** [Teneted/Tenet#1458]
**Minecraft Version :** 1.16.5

**Mohist Version :** mohist-1.16.5-661-server

**Operating System :** WIndows 10

**Concerned mod / plugin** : BagOfGold v3.0.7 (https://www.spigotmc.org/resources/bagofgold.49332/download?version=352446)

**Logs :** https://paste.ubuntu.com/p/F366pNp3mQ/
Spigot log: https://paste.ubuntu.com/p/qvFFPjMpMS/
NOTE: Nothing shows in the logs, but in Minecraft as you type in the commands, instead of executing the command like it does just fine on a Spigot 1.16.5 server, it comes up with Usage help text instead, as if you had typed the command incorrectly. In Spigot it works fine.

**Steps to Reproduce :**
1. copy mohist jar to clean folder, create run.bat file to run it (java -jar mohist-1.16.5-661-server.jar)
2. create plugins folder with BagOfGold v3.0.7 (https://www.spigotmc.org/resources/bagofgold.49332/download?version=352446), Vault v1.7.3-b131 (https://www.spigotmc.org/resources/vault.34315/download?version=344916), and Citizens v2.0.28 (https://www.spigotmc.org/resources/citizens.13811/download?version=403552)
3. copy eula file so that you don't get prompted
4. run the bat file
5. run Minecraft client and join server
6. type /bog banker create

**Description of issue :** 
BagOfGold commands don't seem to work on Mohist but run just fine on Spigot. For example, I type in the following:

/bog banker create

and this produces a Usage text description of how to correctly use the command, even though it is being typed in correctly. it's supposed to create an NPC at the cursor but instead just shows Usage text.

note:  BagOfGold interacts with the Citizens 2 mod in order to create an NPC. citizens mod seems to work fine, i can create an NPC via the following Citizens mod command:

/citizens:npc create SomeNPC

**Comment by Romaindu35** [comment]
Can you send logs ?

**Comment by AnthonyPaulO** [comment]
> Can you send logs ?

I've updated the log section in the post with both the mohist log and the spigot log. I'll copy here for your convenience:
Mohist: https://paste.ubuntu.com/p/F366pNp3mQ/
Spigot log: https://paste.ubuntu.com/p/qvFFPjMpMS/
