### ISSUE TITLE
Instant Crash on 1.16.5

### ISSUE THREAD

**Issue by drugpup** [Teneted/Tenet#1460]
**Minecraft Version :** 1.16.5

**Mohist Version :** 672

**Operating System :** Windows 10

**Log1 :** https://drive.google.com/file/d/1OmUyBmLoUyXU6t288vW3mF-wZ_vmgDXi/view?usp=sharing
**Log2 :** https://paste.ubuntu.com/p/TdKWNgZdbB/

**Mod list :** That are 92 mods, and because  i can't start the server, i won't write them here.

**Plugin list :** AutoRestart; Dynmap; EssentialsXProtect; EssentialsXSpawn; GriefPrevention; LuckPerms; Minepacks; Old Piglins (By FredTheDoggy); Vault;

**Description of issue :** The First time i tried to start the server i took some time and than it crashed. I tried it agein and it crashed in 5 seconds. At the End it says something about CraftBukkit, but the window closes to fast.

**Comment by Romaindu35** [comment]
In your mod, you have ReplayMod, which is client side mod. Normally if you delete this mod, server can start !
