### ISSUE TITLE
[1.16.5] ChunkManager deadlock 2

### ISSUE THREAD

**Issue by bigenergy** [Teneted/Tenet#1463]
**Minecraft Version :** 1.16.5

**Mohist Version :** 672

**Operating System :** ubuntu

**Logs :** https://paste.ubuntu.com/p/qwHS4My95Z/

related https://github.com/MohistMC/Mohist/issues/1420

**Comment by Romaindu35** [comment]
Why open 2 issues ?

**Comment by bigenergy** [comment]
> Why open 2 issues ?

I thought that you did not notice my logs, since I saw several commits with the deadlock fix, but this is still not working, so I decided to attach the latest logs to this issue

**Comment by Romaindu35** [comment]
> > Why open 2 issues ?
> 
> I thought that you did not notice my logs, since I saw several commits with the deadlock fix, but this is still not working, so I decided to attach the latest logs to this issue

Ok

**Comment by Romaindu35** [comment]
Are you always this bug with build#670 and later ?

**Comment by bigenergy** [comment]
> Are you always this bug with build#670 and later ?

noticed this error from build 629

**Comment by KR33PYK1NG** [comment]
This does not look like a deadlock: stacktraces from 10s/20s/30s/40s differ from each other, so the Server Thread is not stuck in one place.
I'm more inclined to believe this is some kind of overload (too many chunk loads, maybe?)

**Comment by bigenergy** [comment]
> This does not look like a deadlock: stacktraces from 10s/20s/30s/40s differ from each other, so the Server Thread is not stuck in one place.
> I'm more inclined to believe this is some kind of overload (too many chunk loads, maybe?)

https://paste.ubuntu.com/p/yvvHTZbTxf/

The server hangs up tightly, including not saving the map
You have to kill the server process manually

**Comment by KR33PYK1NG** [comment]
@bigenergy, please check out the latest build and let us know if the issue persists, @Romaindu35 implemented Async Chunk IO from Paper.

**Comment by bigenergy** [comment]
i currently testing

**Comment by bigenergy** [comment]
maybe related https://github.com/MohistMC/Mohist/issues/1496#issuecomment-872985521

**Comment by bigenergy** [comment]
> @bigenergy, please check out the latest build and let us know if the issue persists, @Romaindu35 implemented Async Chunk IO from Paper.

still works

**Comment by KR33PYK1NG** [comment]
Build number? Also, log would be useful.

**Comment by bigenergy** [comment]
> Build number? Also, log would be useful.

707
maybe https://github.com/MohistMC/Mohist/issues/1496

crash https://paste.ubuntu.com/p/m3PrK48CQW/
full log https://paste.ubuntu.com/p/KFsjssHKPy/
