### ISSUE TITLE
[1.12.2] can't have a block ID above 4095

### ISSUE THREAD

**Issue by myaako-wasure** [Teneted/Tenet#1466]
**Minecraft Version :** 1.12.2

**Mohist Version :** 209

**Operating System :** CentOS

**Mod List :** https://pastebin.com/cNeAU73P

**Plugin List :** https://pastebin.com/JhmMPLTX

**Logs :** https://pastebin.com/De6vPK7B

**Steps to Reproduce :**
 1. Select the Block ID above 4096 with Wand in WorldEdit.
 2. Override with //set 0.
 3. An error occurs and overwriting is not possible.

**Description of issue :** It is the Mod version of WorldEdit that is written in the Mod List.
I installed the Mohist version of WorldEdit later, but there was no change. (Log is the Mohist version of WorldEdit.)

**Comment by Romaindu35** [comment]
Can you send complete logs and are you sure that the id you are looking for matches a block ?

**Comment by myaako-wasure** [comment]
Server Log
[latest.log](https://github.com/MohistMC/Mohist/files/6720275/latest.log)

I tried to overwrite Pam's HarvestCraft's Windy Garden with //set 0.
Then I got the following error.
[Mohist]: [WorldEdit] An unexpected error while handling a WorldEdit command
IllegalArgumentException: Can't have a block ID above 4095 (4683 given)
The actual block ID for Windy Garden is 10633.

Future MC's Cornflower also throws an error.
IllegalArgumentException: Can't have a block ID above 4095 (4113 given)
The actual block ID for Cornflower is 9526.

I have verified WorldEdit for both plugins and mods and the errors are similar.
It seems that not all mod blocks cause the error.
In some cases, the error did not occur even when the block ID exceeded 4096.

This error also occurs in the client.
I had an idea, so I verified that it was the JustEnoughIDs-1.0.3-SNAPSHOT-m.jar modified by Mohist that caused the error.
When I tried to run Minecraft with the regular JustEnoughIDs-1.0.3-55.jar on the client, the error did not occur.

If I run a JEID in Mohist that is not modified by Mohist, the biome ID goes wrong.
Can you please fix this so that WorldEdit and JEID can coexist?
