### ISSUE TITLE
[1.12.2] Cant run Mohist

### ISSUE THREAD

**Issue by GothkittyGirl** [Teneted/Tenet#1468]
**Minecraft Version :** 1.12.2

**Mohist Version :** 239

**Operating System :** linux?

**Concerned mod / plugin** : Modpack im using is Mc Eternal Lite

**Logs :** Log File: https://pastebin.com/qDKJdYds No crash report

**Steps to Reproduce :**
 1. Add mohist
 2. start server
 3. 3 crashes

**Description of issue :** cant run the server with mohist

**Comment by KR33PYK1NG** [comment]
Remove your mods one by one until you find the problematic mod.
