### ISSUE TITLE
[1.16.5] The worldborder does not change again without restarting

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1469]
Version mohist: **Mohist version 1.16.5-673 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.32)**

1 bug-the command /worldborder set (number) does not work , you create the world border 1 time, 2 times without restarting it can no longer be increased or expanded, it stands still as if rooted to the spot.

**Comment by Romaindu35** [comment]
Can you send log ?

**Comment by GitJhopa** [comment]
there are no errors, just the border of the world does not change without a reboot
