### ISSUE TITLE
[1.16.5] Worldguard spam console PlayerInteractEvent

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1470]
**logs worldguard spam console:** [https://pastebin.com/hWjeU4Lm](https://pastebin.com/hWjeU4Lm)

i change new version worldguard/worldedit and this spam remained in the console..

my version worldguard: **worldguard-bukkit-7.0.4-dist**

**Comment by Romaindu35** [comment]
Can you send complete log ?

**Comment by GitJhopa** [comment]
yes, pls: https://drive.google.com/file/d/1YlmcGBy4zGJYDYBdT3MNatMWLFmt7elA/view?usp=sharing

**Comment by GitJhopa** [comment]
man you fixed or no this bug?!?

**Comment by Romaindu35** [comment]
Please wait, but are you other plugin ?

**Comment by GitJhopa** [comment]
so where's the fix? I'm tired of the console, I'm all in errors, fix it already!
![image](https://user-images.githubusercontent.com/86250668/124624702-c9a54400-de85-11eb-8f29-637ee282bae2.png)

**Comment by GitJhopa** [comment]
![image](https://user-images.githubusercontent.com/86250668/124624723-d033bb80-de85-11eb-8ba7-74d2f2e70c68.png)
SPAM SPAM SPAM SPAM!! lagged!

**Comment by Scrulius** [comment]
> ![image](https://user-images.githubusercontent.com/86250668/124624723-d033bb80-de85-11eb-8ba7-74d2f2e70c68.png)
> SPAM SPAM SPAM SPAM!! lagged!

Shut up man, do you pay them? Do you think they are your slaves or something?

They do this for the community, they have a life and they can't spend all day fixing things.

Be respectful and maybe they will fix this.

**Comment by joaoespanhol** [comment]
use last version, no have more spam
