### ISSUE TITLE
[1.16.5] Things disappear very quickly and the essentialsx bug

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1471]
When players die, they lose things very quickly, in spigot. yml there is a normal value for missing things in the form of 5 minutes. But the items disappear even after 1-2 minutes, this is random.

EssentialsX has a function for saving inventory, when I die it doesn't work, and things don't even fall out, they just disappear, maybe that's the problem, check it out.

my EssentialsX: **EssentialsX-2.19.0-dev99-fd961d5_1.jar**
my Mohist: **Mohist version 1.16.5-673 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.1.32)**

**Comment by Romaindu35** [comment]
Can you send log ?

**Comment by GitJhopa** [comment]
full log my server: **https://drive.google.com/file/d/1YlmcGBy4zGJYDYBdT3MNatMWLFmt7elA/view?usp=sharing**

**Comment by Shawiizz** [comment]
If you want to keep inventory when dying, please use keepInventory gamerule.

**Comment by GitJhopa** [comment]
bug no actuall. fixed. close.
