### ISSUE TITLE
[1.16.5] No working entitytrackfixer spigotmc or use tuinity optimization

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1473]
The EntityTrackFixer plugin does not work on the server, you have very bad timings on the core, the servers hang on TPS and monsters and animals lag, the Tuinity core is very well optimized, take it from them..

**my timings:** https://timings.aikar.co/?id=fac05eb8eadd4d4e97e6b51d42df3fe3
**crash-log plugin EntityTrackFixer**: https://pastebin.com/BU9aumwN
**tuinity last core full optimization 1.16.5**: https://github.com/Tuinity/Tuinity/actions/runs/926621205

**Comment by KR33PYK1NG** [comment]
I'm using EntityTrackerFixer just fine. Why are you using an unofficial build?

**Comment by GitJhopa** [comment]
okay, i download original, please use **Tuinity optimization**! it's very cool!

**Comment by GitJhopa** [comment]
**no working** entitytrackfixer official..

**Comment by KR33PYK1NG** [comment]
Can't reproduce.

**Comment by XionioXMaster** [comment]
> Can't reproduce.

It also works for me!
