### ISSUE TITLE
Mohist crashes when FTB Quests is installed

### ISSUE THREAD

**Issue by niekmos** [Teneted/Tenet#1474]
When I try to run FTB Quests on Mohist the server gets into a crash loop, when I run it on a vanilla forge server everything works fine. 
[crash-2021-06-26_10.23.53-server.txt](https://github.com/MohistMC/Mohist/files/6720213/crash-2021-06-26_10.23.53-server.txt)

**Comment by KR33PYK1NG** [comment]
Can't reproduce with Mohist 681/Architectury 1.17.22/FTB Quests 1605.2.1 build 39.
