### ISSUE TITLE
mohist multi

### ISSUE THREAD

**Issue by ookami1414** [Teneted/Tenet#1476]
Good afternoon. Good evening.
I'm Japanese and I'm not good at English, so I use a translation site.
Please forgive me if some parts are a little strange.

The question I want to ask is about multiplayer.
I used to use an old version of mohist to play multiplayer.
The version I was using was the "mohist 453 1.16.5" version.
I recently updated my mohist to the latest version, and now I can't play multiplayer anymore.
The server log says to install java11, so I did, but after installing it, when I build a server and try to play multiplayer, the other players say they can't connect.

I can open ports.
What could be the cause?
I asked the other players to install java11, but they could not connect.

Translated with www.DeepL.com/Translator (free version)

**Comment by Romaindu35** [comment]
What is the error ?

**Comment by Romaindu35** [comment]
I think it is because player don't have good forge version

**Comment by Shawiizz** [comment]
Please be sure that your players have latest forge version before connecting to the server.

**Comment by ookami1414** [comment]
@Romaindu35 I have the latest version of Forge.
Could not connect with "1.16.5 36.1.32".

**Comment by ookami1414** [comment]
@Shawiizz I have the latest version of Forge.

**Comment by Shawiizz** [comment]
What is the error please ?

**Comment by ookami1414** [comment]
@Shawiizz The error was "Could not connect" after the other player entered the IP address. after the other player enters their IP address.
I have opened the port properly.

**Comment by Shawiizz** [comment]
What does others players enter their own ip ?

**Comment by ookami1414** [comment]
@Shawiizz I asked other players to enter the global IP of the host.
This is how I played with MULTI in previous versions as well.

**Comment by Romaindu35** [comment]
You use your public IP ?

**Comment by ookami1414** [comment]
@Romaindu35 Does public IP mean ipv4?
I search for global IP on Google and tell my friends that IP.
I've heard that you can't tell anyone else about ipv4.

**Comment by ookami1414** [comment]
I'm sorry for asking so many questions.
Are you sure about this procedure?
1. Start the server
2. Open port
3. Ask other players to enter their global IP
Do I need to install java11 for other players as well?
