### ISSUE TITLE
Separate the debug information in log file to a new file

### ISSUE THREAD

**Issue by BillZhucn** [Teneted/Tenet#1478]
**What is your question ?**
Is there any way to separate the debug information from the log file?

**Comment by Romaindu35** [comment]
No, is not possible

**Comment by BillZhucn** [comment]
> No, is not possible

Could it become a new feature in the future?

**Comment by Romaindu35** [comment]
you would like to have a file where is written just what is in the console?

**Comment by BillZhucn** [comment]
> you would like to have a file where is written just what is in the console?

Yes! This is what I really need. The debug information is hard for a newbie to understand. It should be developed for the developers. The server operators should concentrate more on INFOs, WARNs and ERRORs. I think if the debug info is saved in another file it will be better for the server operator to manage and find useful information asap.
