### ISSUE TITLE
[bug and lagg 1.16.5] low TPS and lagg server

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1479]
**timings:** https://timings.aikar.co/?id=a57e20a7adcd46138641e0f84e4b8df9

at 20 online, the TPS starts to fall significantly, please optimize the core, take an example from Tuinity for optimizing chunks, monsters, entity, Your core is fine, but it lags a lot!

**Comment by GitJhopa** [comment]
and no working official **entitytrackfixer**

**Comment by Romaindu35** [comment]
the lag depends on the number of mod / plugin as well as the power of your machines

**Comment by GitJhopa** [comment]
ahah man don't make me laugh, I've been building builds since 2012 and I know what and how to put it, it's the mohist that lags very much and gets a small TPS even with 20 online, there are no optimizations!

**Comment by GitJhopa** [comment]
I use proven plugins that are configured and do not load TPS, I have only 10 mods, an IntelCore i9-9990K machine, 32 RAM, NVME 1TB

**Comment by Romaindu35** [comment]
Have you ever tried forge? And if not, isn't the async chunk there to optimize?

**Comment by GitJhopa** [comment]
tell us in more detail

**Comment by Romaindu35** [comment]
Forge just uses 2gb of ram empty, and then you need to add about 250mb of ram per mods

**Comment by Romaindu35** [comment]
Else, on Friday we added the async chunk of paper, which gives better performance, but this kind of patch requires a lot of work, because forge and bukkit do not have the same operation, it can break other things!

**Comment by GitJhopa** [comment]
ok i wait

**Comment by Romaindu35** [comment]
Same #1473

**Comment by KR33PYK1NG** [comment]
@GitJhopa, use Spark Profiler to debug your TPS lag, Aikar's Timings doesn't really work with mods.
