### ISSUE TITLE
crasher mohist

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1484]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {678}

**Operating System :** {Windows 10}

**Logs :** https://mclo.gs/zKQEU9V

**Mod list :** {no have}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {start server}

**Comment by Romaindu35** [comment]
What your mods or plugins ?

**Comment by Romaindu35** [comment]
And how you have this error ?
