### ISSUE TITLE
[1.16.5] Cant create NPC with Citizens

### ISSUE THREAD

**Issue by DaDiGui** [Teneted/Tenet#1485]
Minecraft Version : 1.16.5

Mohist Version : 1.16.5-678

Operating System : Windows 10 Pro

Concerned plugin: https://www.spigotmc.org/resources/citizens.13811/

Logs :
ERROR when I do /npc create test https://pastebin.com/49Y5i37J
full log: https://mclo.gs/ScQCSU5
plugin list: https://haste.mohistmc.com/xirofelome

Steps to Reproduce :
 1. Install the plugin
 2. Run the server
 3. Enter the server
 4. Check with /plugins if Citizens it was detected
 5. do /npc create test
 6. nothing happens and error pop up in the chat.

Description of issue : In the saves.yml files it DOES show the NPC as having been created.

**Comment by Romaindu35** [comment]
Are you journey map mods ?

**Comment by DaDiGui** [comment]
Yes, I have it installed. Is there any possibility to have another minimap without influencing Citizen?

**Comment by Romaindu35** [comment]
I don't know, I try to fix this bug

**Comment by Romaindu35** [comment]
I don't have this bug with build#2330 of Citizen and with journey map (lastest)
![image](https://user-images.githubusercontent.com/67557705/123678194-4e6cde00-d846-11eb-94ed-7f136ed1875e.png)

**Comment by DaDiGui** [comment]
Test with same build and same mod and it still doesn't work for me. When I enter the world I am falling into the void, the npc hits me but he is obviously invisible.
https://mclo.gs/EalbCbN
Mod List: https://i.imgur.com/1Bc5xPh.png (no journeymap)

**Comment by Romaindu35** [comment]
You don't use journey map ?

**Comment by DaDiGui** [comment]
Yes, but the listing above does not include JourneyMap because I took it out earlier to take the photo.

**Comment by Romaindu35** [comment]
Can you try just with journey map and citizen ?

**Comment by DaDiGui** [comment]
Well, for now that list of mods, works correctly together with JourneyMap, so the bug may now be because of a plugin.

**Comment by DaDiGui** [comment]
I don't understand why or how, but now everything works fine.

**Comment by Romaindu35** [comment]
this bug is really weird, but i had the same as you
