### ISSUE TITLE
[1.12.2] Fatal Error on open /enderchest with MZP-EnderChest

### ISSUE THREAD

**Issue by yodaylay22** [Teneted/Tenet#1486]
Minecraft Version : 1.12.2

Mohist Version : 1.12.2-239

Operating System : Idk is pterodactyl panel

Concerned mod / plugin: 
Mods:
![image](https://user-images.githubusercontent.com/12820569/123553473-b7bef500-d751-11eb-9003-8eb4aabeeae9.png)
Plugin:
https://www.spigotmc.org/resources/mzp-enderchest-custom-extendable-enderchest-with-vault-and-mysql-support-1-8-1-16.92124/

Logs :
![image](https://user-images.githubusercontent.com/12820569/123553456-a4ac2500-d751-11eb-9765-fbdd6d474a83.png)

Steps to Reproduce : Just run /enderchest

**Comment by joaoespanhol** [comment]
observation: He say that on spigot does not happen.
