### ISSUE TITLE
The server thread is dumped after a player issued the /back command

### ISSUE THREAD

**Issue by BillZhucn** [Teneted/Tenet#1488]
**Minecraft Version :** 1.16.5

**Mohist Version :** 677

**Operating System :** Windows Server 2016 Datacenter

**Logs :** https://paste.ubuntu.com/p/HdJkBBgYJx/
[latest.log](https://github.com/MohistMC/Mohist/files/6722970/latest.log)

**Mod list :** [sndctrl, torchslabmod, netherportalfix, ftblibrary, eidolon, jei, additionalbanners, doggytalents, create, controlling, citadel, yungsapi, botanypots, bookshelf, iceandfire, carpetstairsmod, chat_heads, ftbteams, ftbchunks, forge, betterendforge, dsurround, dungeons_arise, minecraft, torchmaster, environs, betterspawnercontrol, classicalart, biomesoplenty, ftbranks, editsign, rare-ice, jeiintegration, mobeffects, curios, patchouli, quark, ftbbackups, collective, autoreglib, ingameime, jecharacters, worldedit, architectury, cloth-config, classicbar, dtquark, dynamictrees, bettermineshafts, wwta]

**Plugin list :** https://haste.mohistmc.com/dohelamadu

**Description of issue :** When the Player uses the /back command (from the EssentialsX plugin), the server thread is dumped. https://paste.ubuntu.com/p/HdJkBBgYJx/ indicates that it might be the problem of the chunk handler. So I'm here to ask for help. The command /back sometimes do not teleport the player to the correct death point.

**Comment by KR33PYK1NG** [comment]
You can see `The server has not responded for 10 seconds` notification on top of your log.
Does thread dump get printed for 20, 30... etc seconds or does the server continue to work normally after 10 seconds one?

**Comment by BillZhucn** [comment]
> You can see `The server has not responded for 10 seconds` notification on top of your log.
> Does thread dump get printed for 20, 30... etc seconds or does the server continue to work normally after 10 seconds one?

Hmmm, Actually it seems fine. But it might be caused by essentials as some commands of the plugin like '/back' and '/tpa' sometimes do not work.

**Comment by KR33PYK1NG** [comment]
Then your server may be overloaded, or it's somehow tied with Essentials.

**Comment by Shawiizz** [comment]
I close this since thread dumps can be ignored if your server doesn't crash. If it crashes, please open a new issue.
