### ISSUE TITLE
[1.16.5] MythicMobs plugin projectiles are not working

### ISSUE THREAD

**Issue by t0xic1** [Teneted/Tenet#1490]
Minecraft Version : 1.16.5

Mohist Version : 1.16.5-680

Operating System : Windows 10 

MythicMobs Version: 4.12.0 FREE

Concerned plugin: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/updates

Files: 
Full Server Log File: https://mclo.gs/zubxvJL
No errors on console (note that i turned on MythicMobs Debug mode at the end of the log)

MythicMobs Mob File: https://pastebin.com/t1yiABzf (copy into ExampleMobs.yml)
MythicMobs Skill File:  https://pastebin.com/NvyPbRdV (copy into ExampleSkills.yml)

Steps to reproduce:

1. Copy these MythicMobs files into your MythicMobs folder
2. Start the server
3. Spawn the mob via /mm mobs spawn TestMob
4. Be on non-creative mode and he launches a projectile attack that should deal 6 hearts of damage but doesnt!

IF YOU HAVE ANY QUESTIONS AS MYTHICMOBS CAN BE A BIT COMPLEX, DISCORD: Magickz#2551

**Comment by Romaindu35** [comment]
You have optifine on your server ?

**Comment by t0xic1** [comment]
> You have optifine on your server ?

I tested the server without any mods aswell and the issue still persisted, just using the plugins listed in the log file

**Comment by Romaindu35** [comment]
Ok

**Comment by Romaindu35** [comment]
Can you send logs without optifine ?

**Comment by t0xic1** [comment]
> Can you send logs without optifine ?

https://mclo.gs/pztpeoY

Here, as i said there's no errors or anything but with Mohist the projectile skills don't deal any damage for somereason

**Comment by Romaindu35** [comment]
It's fix
