### ISSUE TITLE
Server Dont Starting after 665 build

### ISSUE THREAD

**Issue by SadManLie** [Teneted/Tenet#1492]
**Minecraft Version :*1.16.5{Minecraft version}

**Mohist Version :680 {Provide Mohist build number}

**Operating System :Debian 10{Provide the name of your OS}

**Logs : https://pastebin.com/mBWnZmTR  {Link(s) of logs and crash reports if you have}

**Mod list :**
![image](https://user-images.githubusercontent.com/73479208/123962812-85640080-d9ba-11eb-8b3c-9e9bd7f65d65.png)
 {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :
![image](https://user-images.githubusercontent.com/73479208/123962848-8e54d200-d9ba-11eb-894d-53eea7441042.png)
 {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by Romaindu35** [comment]
This issue is create with mod performant, I fix that when I have the time.

**Comment by KR33PYK1NG** [comment]
Fixed in 6e9fd95
