### ISSUE TITLE
[BUG] BIG BUG GENERATOR CHUNKS

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1499]
I use mods for landscape generation from the Abnormals Team. The essence of the bug is that when I generate a map for 1 time without restarting or shutting down the server , everything is fine, all chunks work, the map is beautiful. But when I turn off the server or restart it, the map generation is lost and broken chunks are formed. I give an example of these chunks, they occur randomly and often, the //regen command from WorldEdit helps to remove them, but this is very inconvenient, please fix it! I am using the latest version of Mohist.
![image](https://user-images.githubusercontent.com/86250668/124357263-53090c00-dc23-11eb-8276-3722eb3a5d24.png)
![image](https://user-images.githubusercontent.com/86250668/124357267-569c9300-dc23-11eb-820f-6b48cf864c11.png)
![image](https://user-images.githubusercontent.com/86250668/124357268-59978380-dc23-11eb-950d-5dd201618392.png)

my mods: 
![image](https://user-images.githubusercontent.com/86250668/124357277-6320eb80-dc23-11eb-9f7e-fbf08c4c54ea.png)

**Comment by GitJhopa** [comment]
i found bug, - essentials X - crashed chunks , fix pls

**Comment by Romaindu35** [comment]
Can you send logs ?
