### ISSUE TITLE
[1.12.2] Betweenlands bugs

### ISSUE THREAD

**Issue by nicolube** [Teneted/Tenet#1500]
**Minecraft Version :** 1.12.2

**Mohist Version :** 230

**Operating System :** Linux Debian 11

**Concerned mod / plugin** : The Betweenlands

**Logs :** Not avalible

**Steps to Reproduce :**
See in this issue:
https://github.com/Angry-Pixel/The-Betweenlands/issues/860

**Description of issue :** 
See here:
https://github.com/Angry-Pixel/The-Betweenlands/issues/860
Also happens with the current mothist version

**Comment by Romaindu35** [comment]
Can you send logs ?

**Comment by nicolube** [comment]
Well I created a test server with just that mod:

**Logs :** https://paste.enginehub.org/5uRPpsfoq

**Mohist Version :** 242
