### ISSUE TITLE
[1.16.5] Aurelium Skills

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1503]
**Minecraft Version :** 1.16.5
**Mohist Version :** 688

**Operating System :** windows 11

**Concerned mod / plugin** : Aurelium Skills

**Logs :** https://mclo.gs/9WRIcbS

**Steps to Reproduce :**
 1. start server, let's go survival
 2. dammager zombie

**Comment by MagnusHJensen** [comment]
I can not reproduce this. (Logs have expired so not sure what happened, I however see no errors in my console)

Mohist: 1.16.5 (889)
Aurelium Skills - Beta-1.2.7

Logs: https://pastebin.com/sruvyThi

**Comment by joaoespanhol** [comment]
> I can not reproduce this. (Logs have expired so not sure what happened, I however see no errors in my console)
> 
> Mohist: 1.16.5 (889) Aurelium Skills - Beta-1.2.7
> 
> Logs: https://pastebin.com/sruvyThi


it should have probably already been fixed.

So I will close the ticket.
