### ISSUE TITLE
[1.16.5] MCMT + ServerTickList opt crash

### ISSUE THREAD

**Issue by KubiRemPL** [Teneted/Tenet#1504]
**Minecraft Version :** 1.16.5

**Mohist Version :** 691

**Operating System :** Ubuntu 20.04

**Concerned mod / plugin** : ServerTickList optimization in mohist

**Logs :**  [latest.log](https://github.com/MohistMC/Mohist/files/6762000/latest.log) (too big to even upload it on paste sites) [crashlink](https://pastebin.com/ZDY086B3)

**Steps to Reproduce :**
 1. Download MCMT
 2. Start the server
 3. After a while you should get a crash

**Description of issue :** I suspect crash is coming from recent commit adding ServerTickList optimization. Earlier versions worked fine (685 for example)

**Comment by Romaindu35** [comment]
I think it's work with build#690.
Can you  confirm this ?

**Comment by KubiRemPL** [comment]
It's still crashing with build#690
