### ISSUE TITLE
[1.16.5] BUG bamboo grows downwards

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1509]
i use latest version Mohist, and i found bug, **bamboo happens to grow down itself and breaks the block**
![image](https://user-images.githubusercontent.com/86250668/124651301-688c6900-dea3-11eb-96c5-b97dfe712b61.png)

**Comment by Scrulius** [comment]
this has been happening since I installed mohist (3 months ago)

I never reported it because I don't see it as important, but it's true that it happens xDD

**Comment by Shawiizz** [comment]
After testing I'm not able to reproduce this issue. The bamboo grows correctly on my side.

**Comment by Scrulius** [comment]
> After testing I'm not able to reproduce this issue. The bamboo grows correctly on my side.

don't worry, there are much more important things to fix, if I have time I'll try mod by mod to see which one is the one that gives the problem ^^

maybe it's a quark bug, I know it doesn't happen in singleplayer, if you want I leave a list of my mods.

![aaaaaaa](https://user-images.githubusercontent.com/43689161/124843010-44a75100-df91-11eb-9932-41fadd6d1d27.png)

**Comment by GitJhopa** [comment]
fix bamboo pls 
![image](https://user-images.githubusercontent.com/86250668/124875984-3168a580-dfd2-11eb-9f42-01f7e8211887.png)

**Comment by MrJorman** [comment]
UP! current topic

**Comment by Romaindu35** [comment]
Please don't say 'Up' !

**Comment by GitJhopa** [comment]
okay, sorry, fix please gyus..

**Comment by Romaindu35** [comment]
When this happens ? I have grow 1000 bamboo, and I don't have this problem

**Comment by GitJhopa** [comment]
![image](https://user-images.githubusercontent.com/86250668/125149171-13b94e80-e140-11eb-832f-890bb83052f3.png)
new screenshoot, last version mohist build#701

**Comment by Romaindu35** [comment]
Yes, but when this happens ? In specific biome, at random time, always ?

**Comment by GitJhopa** [comment]
always

**Comment by Shawiizz** [comment]
Please give your mod list and plugin list

**Comment by GitJhopa** [comment]
MY **MODS**
![image](https://user-images.githubusercontent.com/86250668/125177244-e5d91600-e1e2-11eb-974e-8fd45e332d6c.png)

**Comment by GitJhopa** [comment]
MY **PLUGINS**
![image](https://user-images.githubusercontent.com/86250668/125177251-f093ab00-e1e2-11eb-8dc8-c642458891cb.png)

**Comment by Shawiizz** [comment]
Ok, please remove them 1 per 1 until you find which one cause the bamboo grow bug.

**Comment by Dontrell94** [comment]
To add to this issue, I am having the same issue and the only mod that is shared is JEI between my instance and @GitJhopa list of mods.

To add: The affected bamboo nearest to me is located in a plains biome and seems to possibly be tied to the random tick speed code in relation to the way it affects growth rate on the stems potentially.

**Comment by Yeobu** [comment]
Do we have any information on this please? i am having the same issue :(

**Comment by Mgazul** [comment]
fixed
