### ISSUE TITLE
[BUG] kicked from server packet processing error

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1516]
on the old version of the kernel did not crash
![image](https://user-images.githubusercontent.com/86250668/124876598-dc795f00-dfd2-11eb-9790-9540271acf8a.png)
![image](https://user-images.githubusercontent.com/86250668/124876689-f5821000-dfd2-11eb-9934-74e8afb7b74e.png)
![image](https://user-images.githubusercontent.com/86250668/124876700-f9159700-dfd2-11eb-8d7d-a1fe4efa5f4c.png)

**Comment by MrJorman** [comment]
i use latest version mohist, and use mod: MowzieMobs. 

on the old kernel, there was the same error in the console, but it did not kick from the server, and now the players kick after 10-15 minutes of the game

**Comment by MrJorman** [comment]
please fix my players kicking after some time with this error

**Comment by Romaindu35** [comment]
I think that you dont have this error with build#695

**Comment by MrJorman** [comment]
yes, but in the new build it is available and the players fly out endlessly

**Comment by GitJhopa** [comment]
oh no, 695build no working , too kick :D

**Comment by Romaindu35** [comment]
Are you sure ? If yes, can you send errors?

**Comment by Black-INV** [comment]
Any idea of a build that doesn't have this error?

**Comment by Romaindu35** [comment]
Normally, build#695 don't have errors because we have delete bad code, but else use build#690 or wait tomorow

**Comment by GitJhopa** [comment]
build#690 
![image](https://user-images.githubusercontent.com/86250668/124974194-301c9480-e035-11eb-9a7b-32243592bdd2.png)

**Comment by Romaindu35** [comment]
This cannot be possible. Are you sure that auto download new version of mohist is not active ?

**Comment by GitJhopa** [comment]
yes

**Comment by GitJhopa** [comment]
![image](https://user-images.githubusercontent.com/86250668/124974899-0879fc00-e036-11eb-9910-a9d86a0c61a8.png)

**Comment by GitJhopa** [comment]
check you https://drive.google.com/file/d/1YayliiuPPHuE9xPT-pggO5_qjKaGrPD5/view?usp=sharing my mods

**Comment by GitJhopa** [comment]
and upload mods from your client and check :D give talisman earth and click from blocks ... more..
![image](https://user-images.githubusercontent.com/86250668/124975093-4d059780-e036-11eb-9527-c4951ae41f58.png)

**Comment by GitJhopa** [comment]
right click from enderegg = server packet processing error

**Comment by GitJhopa** [comment]
and ender egg - rightclick - no Teleport fix pls...

**Comment by GitJhopa** [comment]
dragonegg *

**Comment by Black-INV** [comment]
> Normally, build#695 don't have errors because we have delete bad code, but else use build#690 or wait tomorow

I just tested the build#695 and the issue isn't present. Thank's a lot!

**Comment by Romaindu35** [comment]
is fix in latest version
