### ISSUE TITLE
Packet processing error after player death

### ISSUE THREAD

**Issue by Black-INV** [Teneted/Tenet#1518]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.0-1.16.5-697

**Operating System :** Windows 10 64 Bits

**Logs :** https://haste.mohistmc.com/cigubefegi.coffeescript

**Mod list :** NONE

**Plugin list :** NONE

**Description of issue :** {The issue is quite simple, every time a player dies and respawns they can not interact with anything, I decided to test it in a brand new fresh server and after getting killed by a zombie (line 1) I respawn and interacted with a bock of grass (line 6) and automatically got kicked of the server with the Packet Processing Error. After That just close the server manually. As I said before this is a fresh server with no mods or pluggins.}

**Comment by Romaindu35** [comment]
Same #1516
