### ISSUE TITLE
Error after dying in server

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1519]
**Minecraft Version :** 1.16.5

**Mohist Version :** 697

**Operating System :** Apex hosting multicraft

**Logs :** [2021-07-09-3.log.zip](https://github.com/MohistMC/Mohist/files/6788357/2021-07-09-3.log.zip)

**Mod list :** [nuclear_craft, kubejs, supermartijn642configlib, quarryplus, lazierae2, variant16x, infernalexp, simplemagnets, extratrades, nethers_exoticism, enchantable, mcwwindows, silents_mechanisms, stalwart_dungeons, strawgolem, thermal, neat, bettercaves, rftoolsbase, forgeendertech, mekanismextension, xnet, yungsapi, cabletiers, pyromancer, environmental, mdecore, wstweaks, xreliquary, guardvillagers, randompatches, forgivingvoid, pickupnotifier, waila, dynview, jeresources, paraglider, shetiphiancore, mysticalagradditions, supplementaries, betterendforge, refinedstorage, upgradednetherite, tomeofblood, structure_gel, alltheores, cleancut, industrialforegoing, torchmaster, repurposed_structures, morevillagers, thermal_innovation, fastfurnaceminusreplacement, biomesoplenty, botanytrees, ironfurnaces, toughnessbar, dungeons_plus, simplyimprovedterrain, silentgear, supermartijn642corelib, mysticaladaptations, curios, omnis_backpacks, yungsextras, tanknull, obfuscate, rftoolsdim, theabyss, thermal_locomotion, constructionwand, mcwroofs, sapience, cfm, observerlib, mcwfurnitures, cloth-config, adchimneys, fastbenchminusreplacement, exoticbirds, codechickenlib, bettermineshafts, geckolib3, wailaharvestability, iapif, quarkoddities, simplyjetpacks, cgm, transcendingtrident, tonsofenchants, jeiprofessions, schizocraft, jei, comfortable_nether, attributefix, terraincognita, goblintraders, mekanism, caelus, kobolds, kubejs_thermal, easyelytratakeoff, catjammies, compactmachines, stoneholm, botanypots, adhooks, cofh_core, starlight, iceandfire, ars_nouveau, mysticalworld, extradisks, rftoolspower, extendedbonemeal, forge, ae2ao, neapolitan, wooltweaks, ironchest, dungeons_arise, minecraft, lucky, spheric, psi, classicalart, allthemodium, personality, jeiintegration, rftoolsbuilder, mantle, savageandravage, mrplibrary, cyclepaintings, thermal_cultivation, autumnity, polymorph, autoreglib, globaldataandresourcepacks, structurize, the_legency_of_villige, creativecrafter, kubejs_create, allthetweaks, byg, xlfoodmod, cosmeticarmorreworked, endermail, xpbook, rsrequestify, cyclopscore, dungeonsmod, netherportalfix, wyrmroost, jecalculation, extendedcrafting, additionalbanners, kubejs_mekanism, doggytalents, connectivity, autooredictconv, industrialagriculture, slimier-slimes, jrftl, placebo, citadel, potionsmaster, cartographer, bookshelf, uteamcore, buildinggadgets, waddles, mcwdoors, mekanismgenerators, kubejs_blood_magic, shulkerbox, matc, xnetgases, kubejs_ui, absentbydesign, twilightforest, morewires, cuneiform, out_of_sight, oretweaker, chocolate, mcwbridges, farmersdelight, usefulbackpacks, commoncapabilities, crashutilities, compressium, mekanismadditions, lollipop, industrialmeat, valhelsia_structures, mcwfences, vehicle, simplylight, atmadditions, refinedcurios, bountiful, cnb, dpanvil, patchouli, overworld_two, leap, collective, rftoolsstorage, camera, betterbiomeblend, advancementplus, rftoolscontrol, thermal_expansion, drawerstooltip, xercapaint, mysticalcustomization, betterstrongholds, desolation, buildersaddition, banneradditions, mekanismtools, architectury, curiouselytra, aiimprovements, compactcrafting, undergarden, bwncr, cyclic, betteradvancements, rhino, cucumber, buzzier_bees, berry_good, spiderstpo, shrines, nourished_nether, platforms, dungeons_mobs, abnormals_core, curiosquarkobp, ae2extras, reap, extraboats, wawla, ensorcellation, create, fastsuite, clumps, journeymap, village_employment, comforts, appliedenergistics2, tumbleweed, artifacts, storagenetwork, framedcompactdrawers, cpm, outer_end, dungeoncrawl, demagnetize, lazydfu, mcjtylib, packagedexcrafting, inventorypets, traverse, bloodmagic, selene, mysticalagriculture, craftingtweaks, rftoolsutility, titanium, mcpaint, mana-and-artifice, silentlib, jade, quarkoplenty, packagedauto, archers_paradox, smoothboot, atmospheric, quark, abnormals_delight, storagedrawers, fluxnetworks, simplytea, inventoryhud, combustivefishing, ferritecore, extendedcreativeinventory, silentgems, craftablehorsearmour, refinedstorageaddons, thebeginning, expandability, valhelsia_core, overloadedarmorbar, chiselsandbits, nature_expansion, createaddition, balancedenchanting]

**Plugin list :**  Plugins (24): AuthMe, Chunky, CustomizablePlayerModels, DiscordSRV, EntityTrackerFixer, Graves, Hibernate, HolographicDisplays, Images, JourneyMapServer, LaggRemover, MobsManager, PermissionsEx, PexTabCompleter, PlaceholderAPI, PlugMan, ProtocolLib, ServerEssentials, ServerRestorer, SkinsRestorer, sleep-most, spark, SpigotPing, Vault

**Description of issue :** Whenever I start the server I get:

[main/INFO] [STDERR/]: [org.spongepowered.asm.util.Locals:generateLocalVariableTable:396]: org.objectweb.asm.tree.analysis.AnalyzerException: Error at instruction 821: null

and a stacktrace. But most importantly, whenever I die, the server seems unable to use commands like /gamemode on me and will kick me automatically with a package error when I try breaking any block after dying.

**Comment by ghost** [comment]
To recreate the package error:
1. Start the server
2. Join
3. Die
4. Try breaking any block

It creates errors simmilar to this:

[01:13:08] [Server thread/ERROR] [net.minecraft.network.PacketThreadUtil/]: Error whilst processing packet net.minecraft.network.play.client.CPlayerDiggingPacket@5271490f for FlameinfirenBr[/201.131.153.65:25393]
java.lang.NullPointerException: null
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:140) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:1429) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$1(PacketThreadUtil.java:28) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:152) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:899) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:179) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:125) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:882) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:876) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:113) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1011) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:778) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:283) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Romaindu35** [comment]
This is fix in latest build
