### ISSUE TITLE
Placeholders instread of localized text after today's changes

### ISSUE THREAD

**Issue by kaziu687** [Teneted/Tenet#152]
After commit 0fa9a84f0ccb774e4b8e6c3ba223181e3c95d771 texts from mods (The one probe, mekanism and others) are not localized.

![atomic](https://user-images.githubusercontent.com/1757563/77099902-00e3ad80-6a15-11ea-978b-a408c6c0972f.png)
![Discord_0MeLAwYfX3](https://user-images.githubusercontent.com/1757563/77099936-0e993300-6a15-11ea-9bc5-726df5007ef8.png)

**Comment by CelestialKitsune** [comment]
This is still occuring for AppliedEnergistics2 on Mohist 23b0325
