### ISSUE TITLE
[BUG 1.16.5] The dragon egg does not teleport if I right click on it

### ISSUE THREAD

**Issue by MrJorman** [Teneted/Tenet#1522]
**Minecraft Version:** 1.16.5

**Mohist Version:** build#698

**Operating System:** Windows 10 64 Bits

**Logs:** NONE

**Mod list:** NONE

**Plugin list:** NONE

**Description of issue:** The dragon egg does not teleport if I right click on it.

**Comment by Shawiizz** [comment]
Can reproduce. The egg disappear but don't reappear.

**Comment by GitJhopa** [comment]
When I right-click on the dragon egg, it teleports but does not appear. I can't get it in any way, it just doesn't exist, it disappears after right-clicking on it.
