### ISSUE TITLE
[BUG 1.16.5] Error whilst processing packet net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1526]
**Minecraft Version:** 1.16.5

**Mohist Version:** build#698

**Operating System:** Windows 10 64 Bits

**Logs:** https://pastebin.com/ZCRDcTzq

**Mod list:** NONE

**Plugin list:** NONE

**Description of issue:** i use item Seeker Compass from mod **Seeker Compass** or item **Talisman Earth** from mod **MowzieMobs**, it kicks me from the server and writes an error in the console. Check seeker compass from enchant summoning and talisman earth check right-click leaves, and other fence, stairs, plate to do..

![image](https://user-images.githubusercontent.com/86250668/125102335-d4f5ab00-e0e3-11eb-8dd4-2061a12a1ef9.png)
![image](https://user-images.githubusercontent.com/86250668/125102356-d921c880-e0e3-11eb-9837-61a0c91138d1.png)

**Comment by Romaindu35** [comment]
To use talisman earth, we just need to do right click ?
if yes, I don't have any errors

**Comment by GitJhopa** [comment]
no

**Comment by GitJhopa** [comment]
You need to right-click on the blocks from the mods or on the grass or on the steps and try different options. Also put the Abnormals mods.

**Comment by Romaindu35** [comment]
Fix in latest build
