### ISSUE TITLE
[BUG 1.16.5] you no fixed bug kicked..

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1527]
![image](https://user-images.githubusercontent.com/86250668/125111318-6ec25580-e0ee-11eb-998f-596b397cfe4f.png)

**Comment by Romaindu35** [comment]
How you have this bugs ??? Because for me, when I do /kill and click on button respawn, I have no errors

**Comment by GitJhopa** [comment]
players connect from server and open MENU, or right click from blocks.. i create new issue, check pls. and fix this.

**Comment by Romaindu35** [comment]
I have right click, open inventory, put block or break block, but the bug don't appears
(It appears on build#598). Are sure have latest build
