### ISSUE TITLE
[1.16.5] Kick when right click after die

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1529]
**Minecraft Version :** 1.16.5

**Mohist Version :** 701

**Operating System :** Apex Hosting Multicraft

**Logs :** link of the error message https://hastebin.com/edoboximol.scss

**Steps to Reproduce :**
 1.  Start the server
 2. Join the server
 3. Die
 4. respawn and try right click actions like placing blocks, using doors, etc.

**Description of issue :** whenever I make a right click interaction of any kind with an object after dying in my server, it automatically kicks me out with a package error message, and texts like the log given above appear in the server console. Happening to every user on my server regardless of perms or plugins.

**Current modlist:** https://hastebin.com/piyecinibo.json

**Current plugin list:** https://hastebin.com/ladedonono.apache

**Comment by Romaindu35** [comment]
I don't have any problem :

https://user-images.githubusercontent.com/67557705/125162130-8816e080-e186-11eb-9764-30a2c607b4e3.mp4

**Comment by ghost** [comment]
Try interacting with a door or using a custom mod object that uses right click, also in a normally generated world and not flat. Also is this version still 701 or is it a new build?

**Comment by Romaindu35** [comment]
I use normal pregen and I use build#701

**Comment by ghost** [comment]
Pls try dying in a normal way instead of using the /kill command, my server still has the error when using any right click actuon after dying or just right clicking on a normal block

this is my latest error log when I get kicked https://haste.mohistmc.com/ezimugapof.rb It appears to happen afer running a kubejs command and omnis backpacks appears to be related
