### ISSUE TITLE
[1.16.5 BUG] the horse doesn't move

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1530]
Version: 1.16.5
Mohist: #701
Logs: NONE
VIDEO AAHAHAHAHHA NICE BUG: https://youtu.be/1auTVMNPq34

the horse repeats the player's movement, as the player explained to me that he was sitting on a horse and teleported to another player
A horse does not move in private (WorldGuard) when it has a saddle on it, maybe not in private (WorldGuard) and you can't sit on it
![image](https://user-images.githubusercontent.com/86250668/125141510-e491e580-e11d-11eb-83e4-1a77d984365c.png)
![image](https://user-images.githubusercontent.com/86250668/125141535-fa9fa600-e11d-11eb-8fd2-3ba027b51a17.png)

**Comment by Romaindu35** [comment]
I don't have this bugs with normal mohist server.
Are you sure that you don't have any flag that block this ?

**Comment by Romaindu35** [comment]
https://user-images.githubusercontent.com/67557705/125162728-be099400-e189-11eb-82bf-6870ea8b243a.mp4
