### ISSUE TITLE
[1.16.5 BUG] portal to hell deals damage when teleporting to the world

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1531]
Version: 1.16.5
Mohist: #701
Logs: NONE
Mods: NetherPortalFix.

portal to hell deals damage when teleporting to the world.

when I teleport to hell, there is no damage, and when I get damage from hell to the ordinary world, maybe the bug is related to the NetherPortalFix mod, please check and fix it! Thanks!

**Comment by Romaindu35** [comment]
I don't have any problem


https://user-images.githubusercontent.com/67557705/125163004-56544880-e18b-11eb-8d22-4692690b4e58.mp4

**Comment by GitJhopa** [comment]
you install NetherPortalFix mod?

**Comment by Romaindu35** [comment]
Yes

**Comment by GitJhopa** [comment]
I check Nether Portal Fix, me damaged portal..

**Comment by GitJhopa** [comment]
i install 1 mod NetherPortalFix - damaged. fix pls.

**Comment by GitJhopa** [comment]
moved to quickly no worked.. me damaged teleport nether portal... fix pls

**Comment by GitJhopa** [comment]
nether portal damaged. bro fix pls. teleport nerther 2-3 times

**Comment by Shawiizz** [comment]
Bro stop spamming

**Comment by GitJhopa** [comment]
damaged worldguard. fix?

worldedit-bukkit-7.2.5-dist.jar
worldguard-bukkit-7.0.4-dist.jar

**Comment by GitJhopa** [comment]
sorry guys, WGextender damaged..

**Comment by Romaindu35** [comment]
> damaged worldguard. fix?
> 
> worldedit-bukkit-7.2.5-dist.jar
> worldguard-bukkit-7.0.4-dist.jar

I have also this plugin, so this is create with other mod
