### ISSUE TITLE
[1.16.5] WorldEditCUI Forge Edition 3, no working!

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1534]
Minecraft Version: 1.16.5
Mohist Version: build#701
Logs: none
Plugins: worldedit, worldguard, wgextender.
mods: worldeditCUI

a very strange problem, but WorldEdit CUI does not work, it just does not see a connection with a plugin or something else, with the WorldEdit mod - it works, without the mod - it does not work. Please help, without a world edit cui selections, life is pain.

url: https://www.curseforge.com/minecraft/mc-mods/worldeditcui-forge-edition-3

**Comment by MrJorman** [comment]
hello. please fix bro.

**Comment by Shawiizz** [comment]
Hello, know that we are working on our free time and that we have lives. So please be patient.

**Comment by Mgazul** [comment]
#997
