### ISSUE TITLE
[1.16.5] pls add optimization core (Tuinity 1.16.5)

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1535]
please, I ask you, take the optimization from the Tuinity core for chunks and entity, I have their core on vanilla minecraft took out 120 online at 19.0 TPS. Your core can withstand 30 online at 19.0 TPS.

this is a really good idea

**Comment by Shawiizz** [comment]
This isn't a good idea at all for now. Mohist 1.16.5 isn't stable enough to get these optimizations.
