### ISSUE TITLE
[1.16.5] Problem enter server MODS

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1546]
**Minecraft Version :**1.16.5

**Mohist Version :** 706

**Operating System :** windows 10

**Concerned mod / plugin** : MODPACK: https://www.curseforge.com/minecraft/modpacks/all-the-mods-6-to-the-sky-atm6s

**Logs :** https://mclo.gs/Q8O0BN1
https://haste.mohistmc.com/afejuzofoh.sql

**1problem - Steps to Reproduce :**
1. Start server
2. try enter server

**2 problem - Steps to Reproduce :**
1. Start server
2. try enter server
3. die and try to be respawn

**Description of issue :** Give all details about your issue

**Comment by Shawiizz** [comment]
Please give more details. What happens exactly ?

**Comment by joaoespanhol** [comment]
https://github.com/magmafoundation/Magma-1.16.x/issues/135

Same problem.

**Comment by joaoespanhol** [comment]
@Romaindu35 and @Shawiizz

**Comment by Shawiizz** [comment]
It's not needed to ping us.

**Comment by joaoespanhol** [comment]
no have more problem, last version
