### ISSUE TITLE
[MC VERSION 1.16.5] Entity Crash - Scaling Health mod

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1547]
**Minecraft Version :** 1.16.5

**Mohist Version :** 706

**Operating System :** 

**Concerned mod / plugin** : Mods in the crash report

**Logs :** 
https://mclo.gs/ulck3Kt
https://mclo.gs/9b12RLW

**Steps to Reproduce :**
When dying and trying to reappear, it crashes

**Description of issue :** 
When dying and trying to reappear, it crashes

**Comment by Mgazul** [comment]
fixed

**Comment by RubenRDC** [comment]
12/7

LOG https://mclo.gs/ikwgZjw

Crash Report https://mclo.gs/UK1WMcS
