### ISSUE TITLE
Cannot run on Java 16

### ISSUE THREAD

**Issue by mokurin000** [Teneted/Tenet#1549]
**Minecraft Version :** 1.16.5

**Mohist Version :** 707

**Operating System :** Archlinux

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** I tried run Mohist on Java 16, it tells me I must run it on Java 11+

Java version: openjdk-jre-16

**Comment by Romaindu35** [comment]
This is normal, dor the moment forge 1.16.5 don't support java 16 so mohist don't support too
