### ISSUE TITLE
Failed to load datapacks, cant proceed with server load

### ISSUE THREAD

**Issue by LeoChow0407** [Teneted/Tenet#1551]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {1.16.5-697}

**Operating System :** {Win10}

**Logs :** 
[latest.log](https://github.com/MohistMC/Mohist/files/6802035/latest.log)

**Description of issue :** {Can't load the server }

**Comment by Mgazul** [comment]
Check your mod version, and can you provide a mod package?
