### ISSUE TITLE
[MC VERSION 1.16.5] Entity Crash - Scaling Health mod

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1552]
**Minecraft Version :** 1.16.5

**Mohist Version :** 707

**Operating System :** 

**Concerned mod / plugin** : Mods in the crash report

**Logs :** 
LOG https://mclo.gs/ikwgZjw
Crash Report https://mclo.gs/UK1WMcS

**Steps to Reproduce :**
When dying and trying to reappear, it crashes

**Description of issue :** 
When dying and trying to reappear, it crashes

**Comment by Mgazul** [comment]
I tested it countless times and it worked normally without crashing

**Comment by Mgazul** [comment]
Please use ScalingHealth-1.16.5-4.1.5+11, the version you are using is too old

**Comment by Mgazul** [comment]
Please check the mod version and plug-in version before reporting the problem
