### ISSUE TITLE
[1.16.5 BUG] Lot error create when player died

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1554]
version: 1.16.5
mohist: build#701-705
crash log: https://pastebin.com/D1jt0ugS

when a player puts on a backpack from the Quark mod and tries to convert spruce logs into boards in the inventory, he kicks.

**Comment by Mgazul** [comment]
Please provide crash-reports

**Comment by MrJorman** [comment]
I provided it. There are no other errors. Packet processing error.

https://pastebin.com/D1jt0ugS

**Comment by Romaindu35** [comment]
Fix on latest build

**Comment by Shawiizz** [comment]
I reopen this since the fix has been reverted.
This error is same as all other packets bugs, this needs to be fixed quickly.

**Comment by Romaindu35** [comment]
@Mgazul To fix that, you can revert this commit (This commit create lot of bugs)
https://github.com/MohistMC/Mohist/commit/7d7afdf288978fc00de59f96c32eac166c401cb8
https://github.com/MohistMC/Mohist/commit/1a9c41f87cd2e4be1d7cd242fd1840ca865c19bd
https://github.com/MohistMC/Mohist/commit/375c03a87b94e0dc5993be02ef0143a0bd5f3f17
https://github.com/MohistMC/Mohist/commit/ca89dc4c757a6b585c77718fb48b8aaefcaa9a97

**Comment by GitJhopa** [comment]
https://youtu.be/dheGr-gIitw check this bug , tested in build#715

**Comment by Romaindu35** [comment]
I have rename title of the issue, because all problem after player died, is due that same problem. I can fix that when I stay at home (15 august). 
Please don't reopen new issue for all problem after player died !

**Comment by Romaindu35** [comment]
Normally, this bug is fix, but I can test my commit, so if you have error, please report here !

**Comment by Shurui54** [comment]
mods are fixed but essentials no longer is able to use commands after death and I believe it is to do with this update

**Comment by Romaindu35** [comment]
Yes we know (#1643)
