### ISSUE TITLE
kicked out after death

### ISSUE THREAD

**Issue by mem0rz** [Teneted/Tenet#1557]
https://paste.ubuntu.com/p/G7xMbQqtyz/

**Minecraft Version :** {Minecraft version}
1.16.5
**Mohist Version :** {Provide Mohist build number}
14.07 00:05:29 [Server] INFO Mohist: 1.16.5-706
14.07 00:05:29 [Server] INFO Forge: 36.1.32
14.07 00:05:29 [Server] INFO Bukkit: 7e29f765
14.07 00:05:29 [Server] INFO CraftBukkit: 296df566
14.07 00:05:29 [Server] INFO Spigot: 9fb885e8
**Operating System :** {Provide the name of your OS}
debian bullseye linux 5.10
**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}
100 [alexsmobs, upsizer, eidolon, bettercaves, terraforged, jrftl, cookingforblockheads, citadel, placebo, yungsapi, environmental, dense_ores_reborn, biomeidfixer, randompatches, relics, mcwdoors, carryon, paraglider, supplementaries, betterendforge, chocolate, farmersdelight, finallyfarmabledyes, biomesoplenty, projectvibrantjourneys, skinnedlanterns, vehicle, simplylight, pamhc2foodextended, curios, patchouli, collective, randomite, camera, roadstuff, oreexcavation, betterthirdperson, skiing, obfuscate, chunkpregen, betterstrongholds, expandedstorage, constructionwand, decocraftia, cfm, undergarden, tramplestopper, bettershields, classicbar, fastleafdecay, exoticbirds, disenchanting, dungeons_gear, repairchests, betteradvancements, mowziesmobs, sndctrl, trashslot, serene_shrubbery, pamhc2trees, abnormals_core, bayou_blues, upgrade_aquatic, ensorcellation, comforts, travelersbackpack, naturescompass, ender_bags, risingtides, skinnedcarts, good_nights_sleep, betteranimalsplus, cofh_core, mapperbase, mysticsbiomes, forge, spawnbalanceutility, dsurround, dungeons_arise, minecraft, environs, swingthroughgrass, realism_mats_furniture_pack, abundance, majobroom, pamhc2crops, towers_of_the_wild, smoothboot, naturaldecormod, mobeffects, quark, pamhc2foodcore, polymorph, autoreglib, storagedrawers, sit, mobcatcher, byg, aquaculture, cloudboots, cosmeticarmorreworked, healingcampfire]
**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}
https://haste.mohistmc.com/elilegunec
**Description of issue :** {Give all details about your issue}
kicked out by server (left the game) after death(killed by mob)

**Comment by Shawiizz** [comment]
Please use latest build and try again.
