### ISSUE TITLE
WORLD GENERATION CRASH

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1558]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {708}

**Operating System :** {.}

**Logs :** { https://mclo.gs/BkwmxQE }

**Mod list :** {List in crash report}

**Plugin list :** 

**Description of issue :** { I generate between a couple of people in the world for a while and crash the server }

**Comment by Mgazul** [comment]
Don't use 708 build
