### ISSUE TITLE
Problem with /give

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#156]
Items from mods are not issued. I also tried to issue things from other mods, but all the same.
Here is an example with a pixelmon mod

CONSOLE issued server command: /give cermonx 5314 1
 Error: Unknown item id: 5,314.
or
CONSOLE issued server command: /give cermonx pixelmon:great_ball 1
Error: Unknown item name: pixelmon:great_ball
or
CONSOLE issued server command: /give cermonx pixelmon_great_ball 1
Error: Unknown item name: pixelmon_great_ball
or
CONSOLE issued server command: /give cermonx great_ball 1
Error: Unknown item name: great_ball

**Comment by Flashback083** [comment]
Use Essentials EssentialsX-2.15.0.55.jar

**Comment by Rasgnarok** [comment]
Pixelmon dev here. Please do not use number IDs as those have been deprecated since 1.7.10. The correct command usage is `/give cermonx pixelmon:great_ball 1`.

**Comment by Tanguygab** [comment]
If you want to give you items with vanilla minecraft /give command, then do as Rasgnarok said.
Else, if you are using a Bukkit/Spigot plugin who adds a /give command like EssentialsX, you have to do /mohist item info with the item you want in hand, then you'll be able to use the material name it tells you in Bukkit/Spigot plugins

**Comment by Rasgnarok** [comment]
Agreed, you can also do `/minecraft:give` to use the vanilla iteration of the command specifically.

**Comment by Mgazul** [comment]
Someone has already answered
