### ISSUE TITLE
Mohist crashes when updated from 710 to 711 and newest versions

### ISSUE THREAD

**Issue by Mestima** [Teneted/Tenet#1561]
**Minecraft Version :** 1.16.5

**Mohist Version :** 711, 712

**Operating System :** ubuntu 18.04 lts

**Logs :** https://pastebin.com/m2UvNCfs

**Mod list :** listed at logs

**Plugin list :** ConsoleSpamFix, WorldEdit (mohist fixed version from official discord channel), BanItem, SinglePlayerSleep

**Description of issue :** I've updated Mohist from 710 to 711 and it's crashed. I've also tried to update it from 710 to 712 and it's crashed too. 710 works fine.

**Comment by Shawiizz** [comment]
Use 710 for now. This is a bug from a recent commit
