### ISSUE TITLE
[1.16.5] Inventorypets crash

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#1564]
**Minecraft Version :** 1.16.5

**Mohist Version :** 713

**Operating System :** Apex Hosting Muticraft

**Concerned mod / plugin** : Inventory pets https://www.curseforge.com/minecraft/mc-mods/inventory-pets

**Logs :** 
[crash-2021-07-15_01.33.10-fml.txt](https://github.com/MohistMC/Mohist/files/6819787/crash-2021-07-15_01.33.10-fml.txt)

**Steps to Reproduce :**
1. Install inventorypets
2. Start the server

**Description of issue :** Server crashes when loading inventorypets in its latest build

**Comment by Romaindu35** [comment]
This bugs is fix in latest build !
