### ISSUE TITLE
[1.16.5] Add Mod Inventory Support

### ISSUE THREAD

**Issue by AlwaysReadyWBY** [Teneted/Tenet#1566]
InventoryOpenEvent is not called for mod containers. Players may bypass container protection backed by plugins like Residence/Coreprotect and steal from these containers.

Is it possible to create a kind of inventory to support mod inventories, so that certain plugins can receive InventoryEvent for mod containers?

**Comment by Romaindu35** [comment]
It is a forge or bukkit event that never call ?
