### ISSUE TITLE
Does not start the server 710-715 1.16.5

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1572]
**Minecraft Version :** 1.16.5

**Mohist Version :** 710/715

**Operating System :** Linux

**Logs :**
https://haste.mohistmc.com/acafusazil

**Mod list :** not relevant

**Plugin list :** not relevant

**Description of issue :**
 It does not start the server and I have no idea what the last message means

**Comment by AviiNL** [comment]
@RubenRDC You closed this issue 2 hours after opening it. Did you manage to solve it? I'm having the exact same problem right now.

**Comment by Shawiizz** [comment]
@AviiNL try with latest build.

**Comment by AviiNL** [comment]
Just tried with build 727, still the same result.

[Latest log](https://haste.mohistmc.com/qodiyotuve.yaml)

**Comment by Romaindu35** [comment]
Can you paste logs on hastebin ?
https://haste.mohistmc.com/

**Comment by AviiNL** [comment]
https://haste.mohistmc.com/qodiyotuve.yaml

**Comment by AviiNL** [comment]
This can now be flagged as a duplicate of #1584 where https://github.com/MohistMC/Mohist/issues/1584#issuecomment-883751417 is the likely fix
