### ISSUE TITLE
[BUG 1.16.5] LuckPerms bugg

### ISSUE THREAD

**Issue by GitJhopa** [Teneted/Tenet#1573]
LuckPerms stopped working correctly , the plugin loads normally, but the rights of the players begin to disappear at times.

Mohist version: build#715
crashlog: none

**Comment by Shawiizz** [comment]
How to reproduce ?

**Comment by RubenRDC** [comment]
x2 Usually happens when the player dies and after that loses the permissions

**Comment by GitJhopa** [comment]
yes ++ fix please

**Comment by GitJhopa** [comment]
when my player dies on the server and respawns, all his rights fly off, I use LuckPerms.

**Comment by XionioXMaster** [comment]
They disappear after the death of the player, after restarting the game everything is already normal. Use build 708 so there is no such thing.

**Comment by XionioXMaster** [comment]
Perhaps the last build has the same bug.

**Comment by XionioXMaster** [comment]
Last build fix, don't work...

**Comment by Romaindu35** [comment]
It is normal, this bugs is not fix !

**Comment by XionioXMaster** [comment]
3.66m 

> It is normal, this bugs is not fix !

my players report that after death the teams do not work and they need to restart

**Comment by Switch-Back18** [comment]
With GroupManager when we die we lose permission too !

**Comment by joaoespanhol** [comment]
i no have is problem, last version.

**Comment by Romaindu35** [comment]
This is fix in latest update !
