### ISSUE TITLE
Illegal Reflective Access Operation crash

### ISSUE THREAD

**Issue by RedPxnda** [Teneted/Tenet#1574]
**Minecraft Version :** 1.16.5

**Mohist Version :** 715

**Operating System :** Using Server Host(Pebblehost) so idk the os

**Logs :** https://mcpaste.io/33791cf5004c9843

**Mod list :** Seaopolis modpack, but i can garantee mods aren't the problem(I can send modlist because server wont start)

**Plugin list :** None

**Description of issue :** Server keeps crashing when trying to start. https://mcpaste.io/33791cf5004c9843
 saying something about an illegal reflective access operation

**Comment by Romaindu35** [comment]
Can you try with clean mohist server ?

**Comment by RedPxnda** [comment]
I have. Mohist works okay without any mods, but the wierd part is that with this modpack it works perfectly fine on my personal computer. When I try and run it on the server host, it does this. I asked the hosting service, and they said my best bet was to ask here.

**Comment by Shawiizz** [comment]
Try enabling custom_java11 in mohist.yml, maybe the jre is corrupted, it's difficult to tell what's wrong here

**Comment by RedPxnda** [comment]
That did seem to work. Thankyou.
