### ISSUE TITLE
[MC VERSION 1.16.5] Freezes when starting mycommands plugin

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1576]
**Minecraft Version :** 1.16.5

**Mohist Version :** 715

**Operating System :** Linux

**Concerned mod / plugin** : mycommands Plugin

**Logs :** none

**Steps to Reproduce :**
when starting the server normally when loading the MyCMD the console freezes and does not start the server

**Description of issue :** 
when starting the server normally when loading the MyCMD the console freezes and does not start the server

**Comment by RubenRDC** [comment]
https://mclo.gs/bPl20gd

**Comment by Romaindu35** [comment]
This is not a bug, just restart the server (it is often because server don't have enough ram)

**Comment by Mgazul** [comment]
It is accessing and reading data https://api.curseforge.com/servermods/files?projectIds=37488
