### ISSUE TITLE
Server Console Gets Stuck at Preparing spawn area: 99%

### ISSUE THREAD

**Issue by Undeadtrile** [Teneted/Tenet#1579]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-717

**Operating System** Windows

**Logs :** https://mclo.gs/mOL72c7 

**Mod list :** 
Abnormals Core
TeamAbnormals
abnormals_core-1.16.5-3.2.0.jar
Abnormals Delight
TeamAbnormals
abnormals_delight-1.16.5-1.1.1.jar
Abundance
team_aurora_modding
Abundance-1.16.5-1.0.5.jar
Adorn (Forge)
Juicebus
Adorn-1.14.1+1.16.5-forge.jar
Alex's Mobs
alex1the1666
alexsmobs-1.11.1.jar
Allurement
TeamAbnormals
allurement-1.16.5-1.2.0.jar
Aquaculture 2
Shadowclaimer
Aquaculture-1.16.5-2.1.19.jar
Atmospheric
TeamAbnormals
atmospheric-1.16.5-3.1.0.jar
AutoRegLib
Vazkii
AutoRegLib-1.6-49.jar
Autumnity
TeamAbnormals
autumnity-1.16.5-2.1.1.jar
Bayou Blues (Forge)
team_aurora_modding
Bayou-Blues-1.16.5-1.0.5.jar
Berry Good
TeamAbnormals
berry_good-1.16.5-4.1.1.jar
Better Badlands
Gkoliver
Better-Badlands-1.16.5-2.0.3.jar
BetterEnd (Forge)
Beethoven92
betterendforge-1.16.4-1.6.0.jar
Buzzier Bees
TeamAbnormals
buzzier_bees-1.16.5-3.0.1.jar
Caves and Cliffs mod [1.17]
lukebattle04
CAC+MOD+[1.16.5]+[2021.2-pre4].jar
Citadel
alex1the1666
citadel-1.7.2-1.16.5.jar
Clumps
Jaredlll08
Clumps-6.0.0.25.jar
Collective
Serilum
collective-1.16.5-2.27.jar
Cosmetic Armor Reworked
LainMI
CosmeticArmorReworked-1.16.5-v3a.jar
Curios API (Forge)
TheIllusiveC4
curios-forge-1.16.5-4.0.5.2.jar
Curios Quark Oddities Backpack
6LeoMC
CuriosQuarkOBP-1.16.5-1.0.2.jar
Dash
ModdingLegacy
dash-1.16.4-1.0.1.jar
Deeper Nether Biomes
Moon_Slime
DeeperNetherBiomes-v2.0.2-1.16.5.jar
Earth Mobs
bagu_chan500
earthmobsmod-1.16.4-0.4.2.jar
Enchant With Mob(Forge)
bagu_chan500
enchantwithmob-1.16.5-1.4.6.jar
Environmental
TeamAbnormals
environmental-1.16.5-1.0.0.jar
Extra Boats
TeamAbnormals
extraboats-1.16.5-2.1.0.jar
Farmer's Delight
vectorwing
FarmersDelight-1.16.5-0.4.5.jar
ForgeEndertech
EnderLanky
ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar
Frozen Up
ninnih_
frozenup-1.0.1.jar
Goblin Traders
MrCrayfish
goblintraders-1.6.0-1.16.3.jar
Guard Villagers
almightytallestred
guardvillagers-1.16.5.1.2.4.jar
Hunter illager
bagu_chan500
HunterIllager-1.16.5-1.4.0.jar
Illagers Wear Armor
almightytallestred
illagersweararmor-1.0.4.jar
Iron Chests
ProgWML6
ironchest-1.16.4-11.2.10.jar
Jungle Villages
FreyPlayYT
Jungle Villages 1.16.5 v1.1.jar
Kotlin for Forge
thedarkcolour
kotlinforforge-1.14.0-obf.jar
Large Ore Deposits
EnderLanky
AdLods-1.16.4-4.1.6.1-build.0145.jar
More Villagers
SameDifferent
morevillagers-FORGE-1.16.5-1.5.3.jar
Nature's Compass
Chaosyr
NaturesCompass-1.16.5-1.9.1-forge.jar
Neapolitan
TeamAbnormals
neapolitan-1.16.5-2.1.0.jar
Nether's Delight
lumpazl
nethers_delight-1.1.jar
Nether's Exoticism
Furti_Two
nether-s-exoticism-1.16.5-1.0.8.jar
Netherite Horse Armor Mod
louie_cai
netheritehorsearmor-1.7.jar
NetherPortalFix
BlayTheNinth
NetherPortalFix_1.16.3-7.2.1.jar
Odd Water Mobs
Tegus_Talpan
OddWaterMobs[1.16.5]_1.3.0.jar
Pretty Beaches
BlayTheNinth
PrettyBeaches_1.16.3-5.2.0.jar
Quark
Vazkii
Quark-r2.4-314.jar
Quark Oddities
Vazkii
QuarkOddities-1.16.3.jar
Realistic Bees
Serilum
realisticbees_1.16.5-1.3.jar
Repurposed Structures (Forge)
telepathicgrunt
repurposed_structures-1.16.5-2.7.10-forge.jar
Sapience
the_infamous_1
sapience-1.16.5-1.1.2.jar
Savage & Ravage
TeamAbnormals
savageandravage-1.16.5-3.1.0.jar
Snow Pig [Forge]
uraneptus
Snow_Pig-1.16.5-2.3.0.jar
Structures' Compass
Samarium_150
structurescompass-1.16.5-1.1.0.jar
The Endergetic Expansion
TeamAbnormals
endergetic-1.16.4-3.0.0.jar
Trample Stopper
UnRealDinnerbone
TrampleStopper-2.4.9+mc-1.16.5.jar
Upgrade Aquatic
TeamAbnormals
upgrade_aquatic-1.16.5-3.1.0.jar
Upgraded Netherite
Rolfmao25
Upgraded Netherite 1.16.5 - 1.9.13.jar
Valhelsia Core
ValhelsiaTeam
valhelsia_core-16.0.9.jar
Valhelsia Structures
ValhelsiaTeam
valhelsia_structures-1.16.5-0.1.3.jar
YUNG's API (Forge)
YUNGNICKYOUNG
YungsApi-1.16.4-Forge-11.jar
YUNG's Better Caves (Forge)
YUNGNICKYOUNG
BetterCaves-Forge-1.16.4-1.1.2.jar
YUNG's Better Mineshafts (Forge)
YUNGNICKYOUNG
BetterMineshafts-Forge-1.16.4-2.0.4.jar
YUNG's Better Strongholds (Forge)
YUNGNICKYOUNG
BetterStrongholds-1.16.4-1.2.jar

**Plugin List**
AFK Plus
FastChunkPregenerator
Harbor

**Description** When I get to preparing world spawn 99% in the bat file, nothing happens after that, no new messages come and everything just stops. It gets stuck at 99%. How do I fix this? Technically it didn't crash so I can't give a crash log

**Comment by Romaindu35** [comment]
If you delete world and recreate it, the bugs is already here ?

**Comment by joaoespanhol** [comment]
no have this problem, last version mohist.
