### ISSUE TITLE
Server doesn't recognize plugins anymore

### ISSUE THREAD

**Issue by SwitzerLad** [Teneted/Tenet#1582]
**Minecraft Version :** 1.16.5

**Mohist Version :** Latest

**Operating System :** Windows 10

**Logs :** https://haste.mohistmc.com/bapazekuta.yaml

**Mod list :** 
- Added Origins

- AppleSkin
- Better Third Person
- Bits And Chisels
- Ears
- Genesis - An Origins Addon
- Libra - An Origins Addon
- Mob Origins
- UltrusBot
- Netherite Plus Mod
- OroArmor
- Origins
- Pehkui
- Roughly Enough Resources
- Simple Voice Chat
- WiiDude's Custom Origins Mod
- WiiDudeOfficial
- Xaero's Minimap
- [Fabric] Fat Experience Orbs
- Architectury API (Fabric)
- Audio Output
- BetterEnd (Forge)
- Cardinal Components
- Cloth Config API (Fabric)
- Daemonic
- Dynamic FPS
- Eldritch Mobs
- Expanded Origins
- Extra Origins
- Fabric API
- Fabric Language Kotlin
- Gravestones
- Haema
- Improved Stations (Fabric)
- Jumploader
- LambDynamicLights
- Lato Origins
- Latokire
- Light Overlay (Rift/Forge/Fabric)
- Lithium (Fabric)
- Mod Menu
- Mouse Wheelie (Fabric)
- Oh The Biomes You'll Go
- Ok Zoomer
- Origins - Environmental Armor
- Origins - MegaExtraUltimateMobOrigins
- Origins: Classes
- Origins: The Architect
- Phosphor (Fabric)
- Requiem
- Roughly Enough Items Fabric (REI)
- RPG-Hud [Forge]
- Slime Origin
- Tom's Simple Storage Mod (Fabric)
- TooManyOrigins
- MerchantPug
- U Team Core
- Useful Backpacks
- WTHIT

**Plugin list :** 

- AntiXRay

- EssentialsGroupManager
- EssentialsX
- GriefPrevention
- lpc-chat-formatter
- luckperms
- MarriageMaster
- nametagedit
- placeholderapi
- PvPManager
- UltimateTimber
- vault
- VeinMiner
- worldedit
- worldguard

**Description of issue :** 
I created the server and first installed the plugins and they have all worked. Now since I have added the mods to the server, ther server doesnt acknowlege them anymore. It seems has the server isn't even on a bukkit / spigot term since I cannot do stuff like /plugins and other commands that would be possible on a bukkit / spigot server.

**Comment by KR33PYK1NG** [comment]
This log doesn't even look like Mohist (fabric mods???).
I suggest reinstall everything from scratch.

**Comment by SwitzerLad** [comment]
> This log doesn't even look like Mohist (fabric mods???).
> I suggest reinstall everything from scratch.

yeah Origin Requires fabric is maybe that the issue?
The fabric mods do work and all and I did use the latest Mohist. 
Cause i see the logo and all
So i try reinstalling

**Comment by Shawiizz** [comment]
Mohist is forge + plugins, fabric isn't compatible.

**Comment by SwitzerLad** [comment]
> Mohist is forge + plugins, fabric isn't compatible.

Even with Fabric API and JumpLoader?
If so, is there any other possibility to make plugins and all these mods work together?

**Comment by Shawiizz** [comment]
Your logs doesn't looks like you're using Mohist. And there is no way to use any Fabric mod with Mohist.

**Comment by Romaindu35** [comment]
> > Mohist is forge + plugins, fabric isn't compatible.
> 
> Even with Fabric API and JumpLoader?
> If so, is there any other possibility to make plugins and all these mods work together?

JumpLoader remplace forge by fabric, so delete mohist code and remplace by fabric loader
