### ISSUE TITLE
crash with no apparently reason

### ISSUE THREAD

**Issue by Spider4Tech** [Teneted/Tenet#1584]
**Minecraft Version :** 1.16.5

**Mohist Version :** last (727)

**Operating System :** linux

**Logs :** https://pastebin.com/Pn4BuNwy

**Mod list :** security craft, biome o plenty, blood magic, byg, champion forge, citadel, create mc, dungeon mod, ice and fire, meet your fight, mowzie mob, performant, torohealth, villager and monster, wizard staff

**Plugin list :** authme, vault,banitem,chunky,clearlag, cmilib, csf, essentialx, group manager, infinite scoreboard, jobs, kingdoms+, limit creative, loot chest, placeholder, protocollib, randomtp, shopkeeper, skin restorer, skript, spark, tab,tradeplus, tuske, zauctionhouse v3

**Description of issue :** 

when i start the server, not same time or same load segment, the server crash, i gave the log but i don't see anything

**Comment by Romaindu35** [comment]
Can you try without mod or plugin and if canot reproduire, try mod per mod

**Comment by Spider4Tech** [comment]
> 
> 
> Can you try without mod or plugin and if canot reproduire, try mod per mod

ok i'll try, but the problem is that not appears all time and all the same time

**Comment by AviiNL** [comment]
Try running it on Java 14 instead of 11, Took me a while to debug this, but it seems to work on Java 14 for me.

**Comment by johansantana** [comment]
Does it worked? Cause i have that same issue and i want to know that

**Comment by joaoespanhol** [comment]
i have this mod, my server, no have this problem.
