### ISSUE TITLE
last CREATE mod version

### ISSUE THREAD

**Issue by Spider4Tech** [Teneted/Tenet#1585]
**Minecraft Version :** 1.16.5

**Mohist Version :** last

**Operating System :** linux

**Logs :** https://pastebin.com/85Tk7i7U

**Mod list :** listed in the pastebin

**Plugin list :** no plugin

**Description of issue :** try lo load last create version on mohist and this happen

**Comment by Dontrell94** [comment]
Install Flywheel as it's required by Create
[https://www.curseforge.com/minecraft/mc-mods/flywheel/files/3384004](url)
