### ISSUE TITLE
[1.16.5] The multiplayer interface will indicate that FML is not compatible

### ISSUE THREAD

**Issue by Rcrafte22** [Teneted/Tenet#1587]
**Minecraft Version :1.16.5** 

**Mohist Version :1.16.5.727**

**Operating System :Windows 11**

**Concerned mod / plugin** :Dynamic Lights and I18nUpdateMod

**Logs : no logs**

**Steps to Reproduce :**
 1.Add one of these mods to the client

**Description of issue :The multiplayer interface will indicate that FML is not compatible, but it can still enter the server normally**
![error](https://user-images.githubusercontent.com/39120466/126432638-01607c64-adf9-40f3-800d-33b3acc57d05.png)

**Comment by Romaindu35** [comment]
Are update server list ?

**Comment by Mgazul** [comment]
This is a feature of forge, not mohist
