### ISSUE TITLE
[1.16.5] Scaling Heal BUG

### ISSUE THREAD

**Issue by RubenRDC** [Teneted/Tenet#1588]
**Minecraft Version :** 1.16.5

**Mohist Version :** 727

**Operating System :** Linux
**Concerned mod / plugin**  
**Logs :**  https://mclo.gs/2rhZugc
**Mods :** https://ibb.co/Qk3Yzzt
**Plugins :** https://ibb.co/cJ4dwKs
**Steps to Reproduce :**
The server opens and everything but when a player tries to enter he sends the error above

**Description of issue :** 
The server opens and everything but when a player tries to enter he sends the error above

**Comment by Romaindu35** [comment]
When player tries to enter in World ?
And also, can you repost logs ?
