### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by shade233** [Teneted/Tenet#159]
When players are in the End world,the client crashes and failed to join the server again.

SERVER Core : Mohist-ed564e8-server.jar
the issue doesn't exist in older version.
when using plugin command to teleport to the End,there is nothing wrong.The bug happens only when using the Ender Portal.

> _The log on server when a player log in (player in the End).
> [13:39:14] [Server thread/DEBUG] [FML]: FMLHandshakeServerState: null->FMLHandshakeServerState$1:START
> [13:39:14] [Server thread/DEBUG] [FML]:   Next: HELLO
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $ClientHello->FMLHandshakeServerState$2:HELLO
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $ModList:8 mods->FMLHandshakeServerState$2:HELLO
> [13:39:14] [Netty Server IO #2/INFO] [FML]: 客户端尝试加载以下模组加入服务器: 8
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: Client attempting to join with 8 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.5.2847,inventorytweaks@1.63+release.109.220f184,vanillafix@1.0.10-SNAPSHOT,mcp@9.42,waila@1.8.26,jei@4.15.0.293
> [13:39:14] [Netty Server IO #2/INFO] [FML]: Forge Mod Loader 已成功加载 [mohist] ModCLIENT
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]:   Next: WAITINGCACK
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $HandshakeAck:{2}->FMLHandshakeServerState$3:WAITINGCACK
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]:   Next: COMPLETE
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $HandshakeAck:{3}->FMLHandshakeServerState$4:COMPLETE
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]:   Next: DONE
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $HandshakeAck:{4}->FMLHandshakeServerState$5:DONE
> [13:39:14] [Netty Server IO #2/DEBUG] [FML]: FMLHandshakeServerState: $HandshakeAck:{5}->FMLHandshakeServerState$5:DONE
> [13:39:14] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [13:39:14] [Server thread/WARN] [net.minecraft.entity.SharedMonsterAttributes]: Ignoring unknown attribute 'enderio.aoe.xz'
> [13:39:14] [Server thread/WARN] [net.minecraft.entity.SharedMonsterAttributes]: Ignoring unknown attribute 'enderio.aoe.y'
> [13:39:14] [Server thread/WARN] [net.minecraft.entity.SharedMonsterAttributes]: Ignoring unknown attribute 'enderio.aoe.xyz'
> [13:39:15] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: 553627045[/127.0.0.1:14175] logged in with entity id 284 at ([world]-1650.9232887138933, 32.12600165485529, -202.94837400090785)
> [13:39:15] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /127.0.0.1:14175
> net.minecraft.util.ReportedException: Colliding entity with block
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:563) ~[oq.class:?]
> 	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:253) ~[pa.class:?]
> 	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:ed564e8]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:296) ~[gw.class:?]
> 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:934) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:468) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:1223) ~[pl.class:?]
> 	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:1198) ~[pl.class:?]
> 	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:1162) ~[pl.class:?]
> 	at net.minecraft.server.management.PlayerList.changeDimension(PlayerList.java:1079) ~[pl.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:876) ~[oq.class:?]
> 	at net.minecraft.entity.Entity.func_184204_a(Entity.java:2854) ~[vg.class:?]
> 	at net.minecraft.block.BlockEndPortal.func_180634_a(BlockEndPortal.java:75) ~[aqh.class:?]
> 	at net.minecraft.entity.Entity.func_145775_I(Entity.java:1189) ~[vg.class:?]
> 	at net.minecraft.entity.Entity.func_70091_d(Entity.java:703) ~[vg.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:2250) ~[vp.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1986) ~[aed.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2691) ~[vp.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:534) ~[aed.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2473) ~[vp.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:254) ~[aed.class:?]
> 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:470) ~[oq.class:?]
> 	... 9 more
> [13:39:15] [Server thread/WARN] [net.minecraft.entity.EntityList]: Skipping Entity with id chickens:chickenschicken
> [13:39:15] [Server thread/WARN] [net.minecraft.entity.EntityList]: Skipping Entity with id chickens:chickenschicken
> [13:39:15] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: 553627045 lost connection: Internal server error
> [13:39:15] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: 553627045 left the game_
>

**Comment by Mgazul** [comment]
Test again

**Comment by shade233** [comment]
### **Fixed.**

I've tested 5 versions. all ran correctly when players were **not** at the Obsidian where players teleported to.And the Bug Version stop players joining in server when they go in the End_Portal.

here are my test.
Normal version:
> Mohist-2e1b046-server.jar
> Mohist-343c500-server.jar

Bug version:
> Mohist-20a5bb5-server.jar
> Mohist-b6534c0-server.jar
> Mohist-ed564e8-server.jar

**Comment by Mgazul** [comment]
You should test it with the latest build

**Comment by shade233** [comment]
Tested. the latest is Mohist-343c500-server.jar and the bug is   **fixed.**

**Comment by Mgazul** [comment]
> Tested. the latest is Mohist-343c500-server.jar and the bug is **fixed.**

I wish you a happy use!
