### ISSUE TITLE
it out flat crashes

### ISSUE THREAD

**Issue by DemonBigj781** [Teneted/Tenet#1590]
**Minecraft Version :** 1.16.5

**Mohist Version :** 729

**Operating System :** Linux

**Logs :** too big to paste

**Mod list :** cant get

**Plugin list :** cant get

**Description of issue :** it flat out crashes with a massive log
[latest.log](https://github.com/MohistMC/Mohist/files/6865221/latest.log)

**Comment by Romaindu35** [comment]
What do you mean ?

**Comment by DemonBigj781** [comment]
it was fixed.
