### ISSUE TITLE
minecraft commands can't use but player have permission

### ISSUE THREAD

**Issue by Louisover** [Teneted/Tenet#1592]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {682 ~ 727}

**Operating System :** {linux-debian}

**Logs :** {none}

**Mod list :** {none}

**Plugin list :** {none}

**Description of issue :** {I use "permissions.yml" to give players some permissions
###
server.basics:
       description: Basic permissions for My Cool Server.
       default: true
       children:
          minecraft.command.seed: true
          minecraft.command.teleport: true
###
But when player use "/seed" or "/tp ~ ~ ~",
game will print "Unknown or incomplete command,see below for error",
only minecraft command like this, plugins command can be used normally when player have permission.
I think "permissions.yml" is running, because if player don't have permission, game will print "I'm sorry, but you do not have permission to perform this command.Please contact the server administrators if you believe that this is in error."
Even I use permission plugins like "luckperms" or "groupmanager" to give player permission,game still print "Unknown or incomplete command,see below for error"}

**Comment by MagnusHJensen** [comment]
I'm not too into permissions.yml.
But this is taken from the bukkit wiki: "Warning: Permissions.yml is NOT a replacement Permission awarding/checking system and any permissions should continue to be handled by a plugin." https://bukkit.fandom.com/wiki/Permissions.yml

Which I would interpret as, the permissions.yml file does nothing in itself, and needs to be paired with any other permission plugin.

Therefore just using the permissions.yml does not change anything. 
I might be wrong however.
