### ISSUE TITLE
[MC VERSION 1.16.5] Could not view old deaths when i died alot

### ISSUE THREAD

**Issue by huyhhuy1410** [Teneted/Tenet#1595]
**Minecraft Version :** MC 1.16.5

**Mohist Version :** Mohist 727
Logs: (This is the first time it happened, the next time it doesn't show any more)
https://pastebin.com/6pjeZxrL
**Concerned mod / plugin** : Coprse
https://www.curseforge.com/minecraft/mc-mods/corpse

**Steps to Reproduce :**

 1. Start the server with corpse added newly.
 2. Me and my friends died a few times in game
 3. Could press key to view information about past deaths
 4. We dying a few more times
 5. Couldn't press key to view past deaths 

**Description of issue :** It happened 2 times. I must delete the 'death' folder in 'world' folder to make it work again. I tried to report the issue with the mod owner and he said this mod is not compatible with mohist.
This is all my mod use on the server
![image](https://user-images.githubusercontent.com/86774570/126810602-1b30d077-3886-45e1-9d66-5f71f5d5c306.png)
![image](https://user-images.githubusercontent.com/86774570/126810615-90f00d38-7916-4809-8570-5d34bb2e4341.png)
![image](https://user-images.githubusercontent.com/86774570/126810631-cc9ba981-aea7-433e-80ef-0376d9cd0a41.png)

Could you fix this? 
Thank a lot !

**Comment by Romaindu35** [comment]
Same #1554
