### ISSUE TITLE
[1.16.5] Mohist server messages have formatting placeholders instead of their value

### ISSUE THREAD

**Issue by Column01** [Teneted/Tenet#1604]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Debian

**Logs :** N/A

**Mod list :** Whatever mods are in ATM6 1.7.2 (command doesn't exist for me, see the [related projects section on the files page](https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/files/3395166))

**Plugin list :** https://haste.mohistmc.com/sahezoqalu

**Description of issue :** When the server prints a message that requires formatting, still has the placeholders and no formatted text.
![image](https://user-images.githubusercontent.com/26526649/127212404-a0a2e169-0828-4564-99d0-71c0c311ff53.png)

**Comment by Column01** [comment]
I found another instance of this when loading the server up.
![image](https://user-images.githubusercontent.com/26526649/127881680-a46e42c3-d443-4c40-b4ff-34444d9d1fc9.png)

**Comment by Column01** [comment]
I believe that is located [here](https://github.com/MohistMC/Mohist/blob/ebeabb2b11624d3a5308eb37c083a951662b5f3f/patches/minecraft/net/minecraft/tags/TagCollectionReader.java.patch) and all the other messages there probably also have this issue

**Comment by Column01** [comment]
The initial issue also appears to not be fixed either:
![image](https://user-images.githubusercontent.com/26526649/127883120-81495336-3bfa-496b-b3f1-7de3cdb61bfc.png)

**Comment by Mgazul** [comment]
I have deleted this information, why do you still show it?

**Comment by Column01** [comment]
Its good to gauge if a sever is lagging and how bad without needing to run
a command
