### ISSUE TITLE
1.16.5 [ERROR] .... Player TextComponent{text='ThatTopGamer', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} doesn't have an attached origin capability. This should be possible.

### ISSUE THREAD

**Issue by ThatTopGamer** [Teneted/Tenet#1606]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Windows

**Logs :** https://mclo.gs/rkhpRRl

**Mod list :** latest 1.16.5 optifine, archer's paradox, architectury api (forge), autoreglib, yung's better caves, yung's better mineshafts, yung's api, oh the biomes you'll go, caelus (forge), cloth config (forge), cofh core, when dungeons arise, emojiful, guardvillagers, improved mobs, just enough items, justenoughprofessions, more villagers (forge), origins (forge port), quark, subterranean wilderness, and tenshilib

**Plugin list :** getting error even without any plugins but i used essentials x, fixed luck perms, fixed world edit, worldguard, vault, elections plus, and advanced region market before even with the same mod list

**Description of issue :** When I die in my server with the origins mod (forge port) on at the same time, I lose access
![servererror2](https://user-images.githubusercontent.com/88057070/127224196-f48c5d61-c001-4889-86cd-e87119ae456f.jpg)
![severerror1](https://user-images.githubusercontent.com/88057070/127224197-db907e42-4f4a-4136-a38e-521ed74b8415.jpg)
 to my origins and it says I don't have access to an origin. I can only fix it by leaving the server and rejoining.

**Comment by Romaindu35** [comment]
Same #1554
