### ISSUE TITLE
[1.16.5] Spice of life foodlist packet causes client to disconnect

### ISSUE THREAD

**Issue by Column01** [Teneted/Tenet#1609]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Debian

**Concerned mod / plugin** : [Spice of Life: Carrot](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)

**Logs :** https://gist.github.com/Column01/6ed7981e45311cd7de8469048cb351a3

**Steps to Reproduce :**
 1. Install spice of life
 2. Die
 3. Try to respawn and get disconnected or you cannot respawn.
 4. If you reconnect and try to eat, you will also get disconnected again

**Description of issue :** When spice of life carrot is installed, the client will get disconnected when trying to respawn after death. They will also get disconnected with subsequent attempts to eat. Using the SOL command `/foodlist clear` seems to fix it, but the foodlist packet should just work as intended. Also it can sometimes not work in which case you need to edit their player data to delete their foodlist

See related SOL issue report: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/115

I believe it has something to do with [where the capability is attached to the player entity](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/f4af6e9abc81882c2ca65fc77b24c040c96255ed/src/main/java/com/cazsius/solcarrot/tracking/CapabilityHandler.java#L37) but I'm not sure.

**Comment by Column01** [comment]
I didn't test if it happens with just Mohist and SOL. I also have [Corail tombstones](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone) installed and no grave spawns when I die with something in my inv

EDIT: Still happens sometimes with nothing in my inv

**Comment by Column01** [comment]
Just noticed also: I can't open my backpack (Sophisticated backpacks) and I am unable to view my baubles

**Comment by Column01** [comment]
I believe this part of SOL's code might be related: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/1.14/src/main/java/com/cazsius/solcarrot/tracking/CapabilityHandler.java#L51-L61

I think mohist isn't handling making a new capability properly like it should. I wonder if disabling the Clear foodlist on death stuff would get around this bug?

**Comment by Column01** [comment]
> I wonder if disabling the Clear foodlist on death stuff would get around this bug?

It does not...

**Comment by Column01** [comment]
Tho I did notice, it will respawn fine the first time you die, but if you respawn again it will not be fine.

**Comment by Romaindu35** [comment]
Same #1554

**Comment by Jcorderop02** [comment]
Issue appears again on #1760
