### ISSUE TITLE
[1.16.5] Problems with Epicfight and Locks

### ISSUE THREAD

**Issue by chan1253** [Teneted/Tenet#1610]
https://pastebin.com/05gA8XYy

**Minecraft Version :** Minecraft version 1.16.5

**Mohist Version :** 735

**Operating System :** windows

**Concerned mod / plugin** : Epicfight :https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/download/3393757
                                                Locks: https://www.curseforge.com/minecraft/mc-mods/locks/download/3324065
**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Install locks and Epicfight on the server
 2. The problem with locks is that when it dies, the server shuts down with an internal error message.
 3. The problem with Epicfight is that after death and revive, Epicfight's combat mode is not used. Also, there is a problem that an error occurs in bukkit, and you have to leave and return to the server to solve this problem.

**Description of issue :** Give all details about your issue

**Comment by Romaindu35** [comment]
Same #1554

**Comment by Romaindu35** [comment]
Same #1554
