### ISSUE TITLE
[1.16.5] Origin lost when player died

### ISSUE THREAD

**Issue by Tealwen** [Teneted/Tenet#1611]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-733

**Operating System :** Ubuntu

**Concerned mod / plugin** : Origins Forge (https://www.curseforge.com/minecraft/mc-mods/origins-forge)

**Logs :** no log or error but , when player died , the origin they choose dispear and when the player reconnect to the server he have the origin again or when  change of  dimension . I have contacted the devlopper of the mod bug i tell me is mohist fault !

**Steps to Reproduce :**
 1. Connect and choose origins
 2. then died
 3. and now look at your origin and you don't have it anymore (reconect or change dimension and Magic origin back agains :))

**Description of issue :** 
no log or error but , when player died , the origin they choose dispear and when the player reconnect to the server he have the origin again or when  change of  dimension . I have contacted the devlopper of the mod bug i tell me is mohist fault !

**Comment by Romaindu35** [comment]
Same problem #1554

**Comment by ThatTopGamer** [comment]
I also got this issue and I couldn’t fix it unless I changed it to mihost build 715 but it doesn’t support luck perms editor fix for some reason
