### ISSUE TITLE
[1.16.5] WorldEdit&WorldEditCUI Mod/plugin doesn't completely work

### ISSUE THREAD

**Issue by creamIcec** [Teneted/Tenet#1614]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Windows 10 21H1

**Concerned mod / plugin** : 
mods : WorldEdit 7.2.5 , WorldEditCUI Forge Edition 3  https://www.curseforge.com/minecraft/mc-mods/worldedit/download/3283693
plugins: worldedit-bukkit-7.2.5-dist.jar  https://dev.bukkit.org/projects/worldedit/

**Logs :** None

**Steps to Reproduce :**
This problem can be reproduced in two ways:
I. Way of mods
 1. Just put the WorldEdit Mod and WorldEditCUI Forge Edition 3 jar file into "mods" folder of the server;
 2. A player joins in server with both WorldEdit 7.2.5 and WorldEditCUI Forge Edition 3 mod;
 3. A selection can be created and the area is visible but when the player uses the command "//set smooth_quartz" it just told "unknown command. type /help to see list of commands."
II. Way of plugins
 1.Delete the WorldEdit mod from the server;
 2.Put the WorldEdit plugin jar file into "plugins" folder of the server;
 3.A player joins in server with both WorldEdit 7.2.5 and WorldEditCUI Forge Edition 3 mod;
 4.Different from the mod way, this time the command can work correctly, but the area of selection becomes invisible.

**Description of issue :** I'm confused that why WorldEdit and WorldEditCUI can't work together. The problem which mod way can reproduce won't happen in pure forge server(version:forge-1.16.5-36.2.2)but it happens in Mohist. I need help. A great work won't be created successfully without the WorldEditCUI.

**Comment by Romaindu35** [comment]
WorldEditCui can't work with WE plugin, because to work, WorldEditCui need client mod.
And with WE mod, the mod is been loaded ?
 Else, it is better if you do ```//set modid:blockName```

**Comment by creamIcec** [comment]
> And with WE mod, the mod is been loaded ?

  Yes it is.Here is a sheet of conditions:
  ![表格](https://user-images.githubusercontent.com/42510470/127755317-025b807c-8d6b-4c97-ac96-d4157fc0a2b9.png)
  To the first condition it works well in pure forge server.

> Else, it is better if you do `//set modid:blockName`

Yes, I also tried this but it also doesn't work.
Not only the command "//set" is useless, but all of the commands are responsed "Unknown command" by console.

**Comment by Mgazul** [comment]
#997
