### ISSUE TITLE
[1.16.5] Why was debug log and main log combined?

### ISSUE THREAD

**Issue by Column01** [Teneted/Tenet#1616]
**What is your question ?**
I see in https://github.com/MohistMC/Mohist/commit/d1ab43a16f449b144050b13ede8b94cb88a9f90a that the log files were changed to all happen in the `latest.log` file instead of splitting into `debug.log` and `latest.log` as is the default configuration. This makes it **extremely** frustrating to find anything useful in the log as it's filled with **_THOUSANDS_** of debug lines from mods that 99% of the time are unimportant.

Can this please be reverted or at least provide a way to configure it?

**Comment by joaoespanhol** [comment]
good job

**Comment by Column01** [comment]
Seems to have been fixed with the above changes. Now just wish mods didn't spam check and spam debug messages... (looking at you compact machines!)
