### ISSUE TITLE
[1.16.5] Apotheosis anvil level cap not changed

### ISSUE THREAD

**Issue by Column01** [Teneted/Tenet#1620]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735

**Operating System :** Debian

**Concerned mod / plugin** : [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)

**Logs :** https://gist.github.com/Column01/b7b7e0b6cf8ece45252f5f895105d15d#file-atm6-apotheosis-issue-log-L189

**Steps to Reproduce :**
 1. Launch a server with Apotheosis installed
 2. Max anvil Level cap is not set properly

**Description of issue :** With the mod Apotheosis installed, the max anvil level cap is supposed to be changed, it fails to change as shown in the logs. This is also an issue with Magma (in the description of [this issue](https://github.com/magmafoundation/Magma-1.16.x/issues/135) it was mentioned, but is not the main focus of the issue)

**Comment by Mgazul** [comment]
Apotheosis's asm code conflicts with craftbukkit

**Comment by Column01** [comment]
Is there any way to add a patch to allow it to work?
