### ISSUE TITLE
[1.16.5] Plugin: ImageOnMap doesn't work

### ISSUE THREAD

**Issue by creamIcec** [Teneted/Tenet#1621]
**Minecraft Version :** 1.16.5

**Mohist Version :** 735 and 736

**Operating System :** Windows10 21H1

**Concerned mod / plugin** : ImageOnMap https://github.com/zDevelopers/ImageOnMap/releases/tag/v4.1.2

**Logs :** None

**Steps to Reproduce :**
 1. Load ImageOnMap Plugin
 2. submit command "/tomap https://images-na.ssl-images-amazon.com/images/I/41eehlrUIHL._SX384_BO1,204,203,200_.jpg"
 3. error happens. See the picture below.
 
![E{L@(7DZ8GK~BTEO)OTHL G](https://user-images.githubusercontent.com/42510470/127769306-4979bc53-f355-4e87-b1c9-563ddcbc664b.png)
 4.If it works, the result is as below:
![Z$___5BV@_OUX5F7BY($L~X](https://user-images.githubusercontent.com/42510470/127769579-14d30e2a-e564-4c20-8821-931bd644f03f.png)

**Description of issue :** Not only this url of image will cause the problem but also all of the urls of pictures. I also tried to save the image to my own image-server (as this plugin need to get image from internet not local files) and submit the command again(difference is that the url is replaced by the url of my own server),but this still happens. I need help. This plugin works correctly in pure bukkit(ver. 1.16.5) server.

**Comment by Mgazul** [comment]
Please provide server logs

**Comment by creamIcec** [comment]
[2021-08-01-1.log](https://github.com/MohistMC/Mohist/files/6920353/2021-08-01-1.log)
the log concerned this plugin begins at line 4485
