### ISSUE TITLE
[1.16.5] SPAM ERROR PLUGIN AND MODS

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1623]
**Minecraft Version :** 1.16.5

**Mohist Version :** 736

**Operating System :** windows 10

**Concerned mod / plugin** :

> **MOD:**

1º architectury
2º MysticalWorld
3º Solcarrot
4º arsnouveau

> **Link mod:**
https://www.curseforge.com/minecraft/mc-mods/architectury-forge
https://www.curseforge.com/minecraft/mc-mods/mystical-world
https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau

> **Plugin:**
1º PlayerKits 

> **Link plugin:**
https://www.spigotmc.org/resources/playerkits-fully-configurable-kits-1-8-1-17.75185/

> **Other error**

1º encoding packet: [15:29:20] [Netty Server IO #23/ERROR] [net.minecraft.network.NettyPacketEncoder/]: Error encoding packet ( no have more problem : Fix: https://github.com/MohistMC/Mohist/commit/147a0a78a584f0da73401dcf490cb3ccc3dde0df  ) 

**Logs :** 
**latest:** https://mclo.gs/mYnVfSB
**Debug::** https://mclo.gs/g15SzFI
**Debug:** https://mclo.gs/oIcocxZ  (lighter debug, only appears almost all errors.)

**Steps to Reproduce :**
 1. start server
 2. When players get to play these errors give log.

**Description of issue :** Give all details about your issue

**Comment by Romaindu35** [comment]
What mod create this bugs ? All ?

**Comment by joaoespanhol** [comment]
> What mod create this bugs ? All ?

these are all mods that give server spam problem.
1º architectury
2º MysticalWorld
3º Solcarrot
4º arsnouveau

**Comment by joaoespanhol** [comment]
Server turned on for 18 hours, total
10743 error
Log: https://mclo.gs/4YXp0Ey

I need fix for problem.

**Comment by Romaindu35** [comment]
Can you send logs for mod per mod, because there are lot different error

**Comment by joaoespanhol** [comment]
Log mod:  architectury

https://mclo.gs/NFp9drz

Log MOD:2º MysticalWorld


https://mclo.gs/EM7kvob


Log MOD 3: arsnouveau

plus 9000 error generated by ars

#1625 
https://github.com/MohistMC/Mohist/issues/1625

![image](https://user-images.githubusercontent.com/22871432/128247805-5d40aa6b-601d-4dca-a36f-03efead594d7.png)


This problem causes server performance problem, consuming all processor cores and causing lag and TPS problem, not to mention server lag and log full of error spam.

**Comment by Romaindu35** [comment]
Latest build fix error encoding packet  ?

**Comment by joaoespanhol** [comment]
> Latest build fix error encoding packet  ?


apparently yes, but a new bug appears.
![image](https://user-images.githubusercontent.com/22871432/128404874-7bc9c16a-3547-4033-be9c-f9c87270676d.png)

Your need fix arsnouveau  because it's causing big server performance problem

**Comment by joaoespanhol** [comment]
More info about arsnouveau. @Romaindu35 @

![image](https://user-images.githubusercontent.com/22871432/128408034-6a4929a7-55cc-4795-9919-da5479584f39.png)

**Comment by Romaindu35** [comment]
If you just have arsnouveau, are you this error ?

**Comment by joaoespanhol** [comment]
> If you just have arsnouveau, are you this error ?

we didn't understand what you said.

**Comment by Romaindu35** [comment]
If you just have arsnouveau mod on your server, this warn is always display ?

**Comment by joaoespanhol** [comment]
> If you just have arsnouveau mod on your server, this warn is always display ?

I don't know, I haven't tested it.

**Comment by joaoespanhol** [comment]
but I don't see anyone complaining about it.

**Comment by Romaindu35** [comment]
Can you test ? Because I think that it is conflict with other mod or plugin !

**Comment by joaoespanhol** [comment]
> Can you test ? Because I think that it is conflict with other mod or plugin !

there is no way to test 163 mods. :(

**Comment by Romaindu35** [comment]
I don't want you to test all mods but just if you run a mohist server with only arsnouveau know if the error appears or not ! So, I will know if it is a bug in mohist, or a conflict with other mod!

**Comment by joaoespanhol** [comment]
> I don't want you to test all mods but just if you run a mohist server with only arsnouveau know if the error appears or not ! So, I will know if it is a bug in mohist, or a conflict with other mod!

I tested the mod alone and without a multiverse plugin, but it didn't show up.

**Comment by joaoespanhol** [comment]
more info:

![image](https://user-images.githubusercontent.com/22871432/128415375-e9fd11b1-6136-4e8c-9cdf-8d22218001cd.png)

**Comment by joaoespanhol** [comment]
Plugin Multiverse-Core

this can also cause this, as this plugin loads the worlds.

Error plugin Multiverse-core Log: https://mclo.gs/hf3Hrs3

@Romaindu35

**Comment by joaoespanhol** [comment]
https://mclo.gs/ht9236a

Log Erro mod: [21:07:36] [Server thread/ERROR] [mysticmods.mysticalworld.MysticalWorld/]: Unable to look up chunk provider's generator

[21:07:48] [Server thread/ERROR] [net.mehvahdjukaar.supplementaries.Supplementaries/]: Was unable to check if minecraft:dimension is using Terraforged's ChunkGenerator.

[21:07:44] [Server thread/ERROR] [net.minecraft.world.gen.settings.DimensionGeneratorSettings/]: No key layers in MapLike[{}]; No key structures in MapLike[{}]; Not a registry ops


[21:07:48] [Server thread/ERROR] [net.mehvahdjukaar.supplementaries.Supplementaries/]: Was unable to check if minecraft:dimension is using Terraforged's ChunkGenerator.

this bug, may also be causing the mod problem: arsnouveau

**Comment by joaoespanhol** [comment]
https://mclo.gs/KVTVVqi

as you can see from the log, when someone goes to another world, spam starts.

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/128478066-000ecc40-7305-49f1-9389-66bbb82804aa.png)

**Comment by Romaindu35** [comment]
> Plugin Multiverse-Core
> 
> cela peut aussi causer cela, car ce plugin charge les mondes.
> 
> Erreur du plugin Multiverse-core Log : https://mclo.gs/hf3Hrs3
> 
> @Romaindu35

If you delete plugin multiverse, you don't have any errors ?

**Comment by Romaindu35** [comment]
Else, lot error is create with DiscordSRV, but I think it is not a mohist problem (Log say Discord Rate Limit)

**Comment by joaoespanhol** [comment]
> Else, lot error is create with DiscordSRV, but I think it is not a mohist problem (Log say Discord Rate Limit)

not talking about the discord error, I sent a log, where to show when someone goes to another world to spam.
Error:
[19:50:17 ERROR]: Error adding element: Unknown registry element com.hollingsworth.arsnouveau.common.world.WorldEvent$1@4f97fd3e

**Comment by joaoespanhol** [comment]
> > Plugin Multiverse-Core
> > cela peut aussi causer cela, car ce plugin charge les mondes.
> > Erreur du plugin Multiverse-core Log : https://mclo.gs/hf3Hrs3
> > @Romaindu35
> 
> If you delete plugin multiverse, you don't have any errors ?

the problem i don't just have the multiverses, i also have an island plugin.

Every time someone goes to a new world, they get spam from the console.

**Comment by joaoespanhol** [comment]
Managed to fix the spam problem of the mod using the plugin: hfix, but the plugin spam an error.

https://www.spigotmc.org/resources/hfix-tools-to-improve-your-server.93139/

Log error. https://mclo.gs/oCKTltX

**Comment by joaoespanhol** [comment]
any predictions to fix the plugin fix problem?
Because this plugin fixes the mod problem: arsnouveau

**Comment by Romaindu35** [comment]
I fix this bug when I have the time
To fix this bug, we need to add this patch : 
1) https://github.com/PaperMC/Paper/blob/master/patches/api/0009-Add-getTPS-method.patch
2) https://github.com/PaperMC/Paper/blob/master/patches/server/0023-Further-improve-server-tick-loop.patch

**Comment by joaoespanhol** [comment]
:o thanks.

good job
