### ISSUE TITLE
ERROR overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

### ISSUE THREAD

**Issue by INotSleep** [Teneted/Tenet#1627]
**Minecraft Version :** 1.16.5

**Mohist Version :** b#740

**Operating System :** Linux

**Logs :** https://cdn.discordapp.com/attachments/648302600864923654/871717136832282684/latest.log

**Mod list :** cyclopscore, jei, abnormals_core, reap, invtweaks, armorstatushud, mgui, journeymap, placebo, citadel, lordcraft, artifacts, evilcraft, evilcraftcompat, environmental, bookshelf, pneumaticcraft, uteamcore, apotheosis, morpheus, datafixerslayer, iceandfire, waila, jeresources, boblib, forge, tlskincape, minecraft, farmersdelight, usefulbackpacks, enchdesc, mousetweaks, silentlib, silentgear, flywheel, curios, tetra, patchouli, autoreglib, performant, diagonalfences, factory, tombstone, quark, structurize, minecolonies, architectury, ftblibrary, appleskin, ferritecore, puzzleslib, smallships, expandability, valhelsia_core, valhelsia_structures, cyclic

**Plugin list :** 0

**Description of issue :** ERROR overwrite PlayerEvent.LoadFromFile {inv:{Size:36,Items:[]},spectatorTicks:0,flyTicks:0,storage:0b,tasks:[]}

**Comment by Romaindu35** [comment]
Can you try mod per mod to know what mod create this bug ?

**Comment by TLCW** [comment]
Same issue here, happens when trying to load a singleplayer world in ATM6. 

I tried an instance with only the common mods but couldn't reproduce the error.

I was messing around with Java arguments at the time, so that might have something to do with it.
