### ISSUE TITLE
Player's cannot join

### ISSUE THREAD

**Issue by KubiRemPL** [Teneted/Tenet#163]
[latest.log](https://github.com/Mohist-Community/Mohist/files/4377010/latest.log)

**Comment by ProsperCraft** [comment]
There are a whole lot of mod errors there, have you tried with only forge and not Mohist?

Did you try without tickdynamic? it has a massive wall of stacktraces.

Also seeing errors from other mods in there when trying to join overloading the buffer.

Listing the modpack would be helpful.
