### ISSUE TITLE
[MC 1.16.5] Chunky and Enhanced Celestials's command not work

### ISSUE THREAD

**Issue by huyhhuy1410** [Teneted/Tenet#1637]
**Minecraft Version :** Minecraft version 1.16.5

**Mohist Version :** Mohist 744

**Concerned mod / plugin** :
https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials
https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge

**Logs :** Nothing

**Steps to Reproduce :**
 1. Start the server with one of the mods above installed
 2. Type the command of these mods in game or in console such as:
 /chunky radius 5000
 /chunky start
 /enhancedcelestials setlunarevent BLOOD_MOON
 3. The server said "Unknown command. Type "/help" for help."

**Description of issue :** I couldn't use the commands of mods above. But when i test those commands in single-player, they worked normally. I tried to contact to Enhanced Celestials's Author but they said that's weird thing, and they don't know. I couldn't use the commands of these mods. Please fix this !
Many thanks :(

**Comment by Romaindu35** [comment]
Are you operator on your server ?

**Comment by huyhhuy1410** [comment]
Yes, i am

**Comment by Romaindu35** [comment]
Can you execute command ```/give``` or ```/gamemode``` ?

**Comment by huyhhuy1410** [comment]
The other commands are okay, i think.

**Comment by neptune-gaming** [comment]
this is an issue i encounter on a LOT of mods, like WorldEdit for forge, dynmap, etc.
idk what's wrong, but i can't execute any command provided by those mods. i'd recommend using the plugin versions, but this issue is something i definitely think needs inspecting
