### ISSUE TITLE
Player cannot join the server with Jei-7.7.1-117

### ISSUE THREAD

**Issue by Sam-Chai** [Teneted/Tenet#1638]
**Minecraft Version :** 1.16.5

**Mohist Version :** 745

**Logs :** ![image](https://user-images.githubusercontent.com/29940426/128461469-08e63aa4-cd08-4340-b804-f00f29fcd91e.png)

Internal server error in client and without any errors in logs.

**Mod list :** jei with these extra mods.

**Plugin list :** vault

**Description of issue :** when player join the server with jei mods, then the Minecraft client said Internal server error. Without any logs.

**Comment by Sam-Chai** [comment]
Oh well, the problem happend with lastest version of JER. On normal forge server.
Here is the issue: [https://github.com/way2muchnoise/JustEnoughResources/issues/305
](https://github.com/way2muchnoise/JustEnoughResources/issues/305
)

**Comment by Romaindu35** [comment]
So, this is a mod problem !
