### ISSUE TITLE
[1.16.5] MMOcore+MMOitem+MythicLib cannot be used correctly

### ISSUE THREAD

**Issue by YKDZ** [Teneted/Tenet#1640]
**Minecraft Version** : 1.16.5

**Mohist Version** : build 744

**Operating System** : centos 7

**Concerned mod / plugin** :
https://www.spigotmc.org/resources/mmocore.70575/
https://www.spigotmc.org/resources/mmoitems-premium.39267/
https://www.spigotmc.org/resources/mythiclib.90306/

**Logs** : no any log

**Steps to Reproduce :**
1. Install the three plugins.
2. Entering the game and the plugins function can be use without any problem.
3. Die once in some way.
4. After respawn, the plugin function cannot be used normally. For example, use /mi browse opens the GUI, and the buttons can be moved. The same is true for other GUIs of the three plugins. Moreover, the attribute (power, speed, etc.) provided by mmoitem can not be used normally.
5. Exit the game, re-enter, and the function returns to normal. Die again and the problem reappears.

**Description of issue** :  **This problem does not appear in Mohist 742. But it appeared in 744 and 745.**

**Comment by Romaindu35** [comment]
Can you test with build 743 and 696 ?

**Comment by Romaindu35** [comment]
Same problem #1643
