### ISSUE TITLE
[1.16.5] Geyser 1.2.1 (for Minecraft 1.16.5) crashes

### ISSUE THREAD

**Issue by neptune-gaming** [Teneted/Tenet#1647]
**Minecraft Version :** 1.16.5

**Mohist Version :** build 744

**Operating System :** i have no idea, but the server is on falixnodes, and they might be using linux

**Concerned mod / plugin** : Geyser-Spigot (the last build for 1.16) at https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/706/

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Download GeyserMC from https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/706/
 2. Start the server
 3. Boom! It will start but it will say it failed to do so right after (Done (time of boot)! run /geyser help for help!)

**Description of issue :** I have no mods that add new blocks or anything, so i decided to run geysermc on my server. i have tested it with a copy of minecraft bedrock that i own and it won't connect. sorry that i don't have the logs, as i just cleaned up my server to make space for new world data

**Comment by Shawiizz** [comment]
I already tested and i was able to run geyser without any problem on my Mohist server. But know that there is no point to use geyser if you have mods which are needed on client side on your server.

**Comment by neptune-gaming** [comment]
i don't have any mods that are needed in the client, since most of them are just performance enhancing mods.

but, with my testing, it's broken and idk why. i don't have the logs tho, but i'll try recreating it and send the logs

**Comment by byquanton** [comment]
@neptune-gaming then use fabric or paper

**Comment by neptune-gaming** [comment]
@byquanton i use plenty of forge server-side mods that doesn't have any fabric counterparts, like terraforged, etc.

**Comment by neptune-gaming** [comment]
It was viaversion that was crashing when connecting to geyser. No need to fix this issue.
