### ISSUE TITLE
[1.12.2] Build 413/414 repeats commands in chat.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#165]
So when i type any command in chat it places a message in the chatbox of me doing that command.
What is this? How do i turn this off?
![Screenshot_459](https://user-images.githubusercontent.com/3002248/77510392-df772d00-6e2b-11ea-81a4-1291a427e25f.png)

**Comment by ghost** [comment]
@Mgazul Caused by this commit; https://github.com/Mohist-Community/Mohist/commit/c933b352b50927571a9178b7236372142f11a437
