### ISSUE TITLE
[1.16.5] Corpse Complex/Survive Mod Crash

### ISSUE THREAD

**Issue by PikeNote** [Teneted/Tenet#1660]
**Minecraft Version :** 1.16.5

**Mohist Version :** Mohist build 757

**Operating System :** Linux

**Logs :** https://pastebin.com/raw/0wpcfhgp

**Mod list :** Listed above in the logs at the bottom.

**Plugin list :** None

**Description of issue :** The Corpse Complex mod seems to crash the server on startup. It seems like it has failed an injection check test that was set up. This is from the modpack [Permafrost](https://www.curseforge.com/minecraft/modpacks/permafrost-eots).

**Comment by Mgazul** [comment]
The error did not appear when the mod was installed separately

**Comment by PikeNote** [comment]
After further testing, I have found the [Survive mod](https://www.curseforge.com/minecraft/mc-mods/survive) causing conflicts/issues with this one specifically. I have been able to reproduce this when installing the two mods standalone with Mohist. Both mods work standalone when the other one is not present.

**Comment by kaliflowerx3** [comment]
i ran into this crash with a variety of combinations of the versions. @PikeNote can you tell me which combo of only survive (no corpse complex) and mohist you got working?
