### ISSUE TITLE
close your core, it's not a core, it's a bicycle with crutches

### ISSUE THREAD

**Issue by MrJorman** [Teneted/Tenet#1661]
close your core, it's not a core, it's a bicycle with crutches 

it is impossible to use anything, mods are running, plugins are being decorated, the server is barely breathing. Why do you need to keep breaking minecraft? Wait for SPONGE

**Comment by MrJorman** [comment]
Developer, I feel sorry for you

**Comment by VOrlando520** [comment]
lol, the only person you need to feel sorry for is yourself. No one forces you to use this, so don't comment on it. Also, Sponge is way far off. One big dev leaves it (like giz, blood or luck) and sponge will be even more dead than it already is. Basically, just go on with your day. This project does not affect you in the slightest.

**Comment by Shawiizz** [comment]
If you don't want to use Mohist, you're free to not use it. We don't force anyone to use it.
If you need Sponge, use Sponge. 
Try to make your own hybrid, and after we will see who is the bike with crutches.
lol.
