### ISSUE TITLE
[1.12.2] Worlds not unloading on Build 413.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#167]
![Screenshot_461](https://user-images.githubusercontent.com/3002248/77578224-68767e80-6e95-11ea-8ec0-9e83a45ad5e5.png)

**Comment by ProsperCraft** [comment]
Try this - https://www.curseforge.com/minecraft/mc-mods/born-in-a-barn

**Comment by Mgazul** [comment]
73238ac
