### ISSUE TITLE
[1.16] Allow vanilla connections with forge mod

### ISSUE THREAD

**Issue by Faris90** [Teneted/Tenet#1688]
**Is your feature request related to a problem? Please describe.**
I have a forge mod but it says "this server has mods that require forge to be installed" but I want to use vanilla

**Describe the solution you'd like**
An option in the config to allow vanilla connections for any mod.

**Additional context**
This is for experimental use

**Comment by Shawiizz** [comment]
If you have a mod which is needed on client side on your server, then you'll not be able to login without forge. If you only have server side mods, you'll be able to join with a vanilla client.

**Comment by Faris90** [comment]
I know but I want it for experimental uses

**Comment by Faris90** [comment]
> If you have a mod which is needed on client side on your server, then you'll not be able to login without forge. If you only have server side mods, you'll be able to join with a vanilla client.

I know but I want it for experimental uses

**Comment by Romaindu35** [comment]
But for what ???
Why do you want to allow vanilla connection if the server need to have something on client ?
This can just create bug !

**Comment by Romaindu35** [comment]
But if you really want to disable this, setup mohist, modify this function ( https://github.com/MohistMC/Mohist/blob/11da7f05e43171ddc05d68ae8d47515e244dc7ce/src/main/java/net/minecraftforge/fml/network/FMLHandshakeHandler.java#L208 ) and build mohist yourself

**Comment by Faris90** [comment]
> But for what ???
> Why do you want to allow vanilla connection if the server need to have something on client ?
> This can just create bug !

I know but it can be a config

**Comment by Shawiizz** [comment]
I don't see the point to add this as a setting because this won't be used a lot of this is not really useful.
If you really want this, you should modify Mohist code as romaindu35 told you and build Mohist yourself.
Also know that all PRs are welcome, if you want to make one, you can :)

**Comment by Faris90** [comment]
I want to test mod resources as a resource pack...
