### ISSUE TITLE
Chuncks not unloaded 

### ISSUE THREAD

**Issue by GDVE** [Teneted/Tenet#169]
**This is my server status:**
![Screenshot_2](https://user-images.githubusercontent.com/19783608/77642864-64b72a80-6f6f-11ea-95c6-588faccde371.png)
![image](https://user-images.githubusercontent.com/19783608/77642688-1efa6200-6f6f-11ea-90c9-0532c63e84ac.png)

**This is my mods:** 
![Screenshot_1](https://user-images.githubusercontent.com/19783608/77642575-f07c8700-6f6e-11ea-90c3-7ec22dfc4ede.png)
**This is my configs:** 
[server_configuration.zip](https://github.com/Mohist-Community/Mohist/files/4386901/server_configuration.zip)

https://sparkprofiler.github.io/#Wve1YM6L72
https://www.spigotmc.org/go/timings?url=hamuxeduro

**Now the essence of the problem. When I enter the lagg unloadchunks command (its functionality will be lower) it simply does not execute, as if it were not even executed!**

Command code: 
![image](https://user-images.githubusercontent.com/19783608/77643135-e0b17280-6f6f-11ea-923d-a2f692e86e68.png)

**Comment by GDVE** [comment]
I forgot to mention this problem appears when the server is overloaded or many chunks are loaded at the same time, I’m definitely not sure.

**Comment by kaziu687** [comment]
I'm working at "load-chunk-on-request: false" feature, for now every mod asking for chunk will load it.

**Comment by GDVE** [comment]
EEEEEEEEEEE LAAAAAAAAAGS FROM MOJANG WITH LOVE! 
![image](https://user-images.githubusercontent.com/19783608/77651402-c8e0eb00-6f7d-11ea-867a-f234c8e0e3b7.png)
