### ISSUE TITLE
NetherPortalFix problem

### ISSUE THREAD

**Issue by QMan0** [Teneted/Tenet#177]
NetherPortalFix is not working. It just uses the default Minecraft radius search algorithm instead of saving player portal position. Working fine on Forge ModLoader server.

**Comment by Krosta8** [comment]
I can confirm, that this problem is still there also in build (539)

**Comment by idunnoooooo** [comment]
+1

**Comment by Shawiizz** [comment]
Hi, please try again with latest build and tell if your error happens with latest or no.

**Comment by joaoespanhol** [comment]
better close ticket.

Does not answer, already do some month

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug persist, please open new issue.
