### ISSUE TITLE
Anyone manage to get GriefPrevention to protect non-vanilla chests in Mohist 1.16.5?

### ISSUE THREAD

**Issue by anu3bis** [Teneted/Tenet#1780]
**What is your question ?**
Anyone manage to get GriefPrevention to protect non-vanilla chests in Mohist 1.16.5?

Problem: GriefPrevention (plugin) does not recognize quark non-vanilla chests as something to be protected.

Thread from the GriefPrevention github: TechFortress/GriefPrevention#1615 (comment)

I like the plugin, but don't have to use that one in particular, I just need something that will be reliable griefprevention (meaning protect chests of all kinds, property, etc) from griefing in claimed areas.

**Comment by GnomoMuitoLoco** [comment]
Em 1.12.2 a mesma coisa, alguém sabe resolver isso?
