### ISSUE TITLE
Disabling update and library checking does not work

### ISSUE THREAD

**Issue by mirroI** [Teneted/Tenet#180]
Mohist config
![image](https://user-images.githubusercontent.com/44697703/77939672-55bada00-72d9-11ea-87aa-0094e48738e8.png)

Server log
![image](https://user-images.githubusercontent.com/44697703/77939755-75ea9900-72d9-11ea-8fcd-a7732f9a95a2.png)

**Comment by Mgazul** [comment]
I modified the format and removed it to rewrite the build
