### ISSUE TITLE
Teleport issue 

### ISSUE THREAD

**Issue by sentest** [Teneted/Tenet#181]
when playing stoneblock 2 it does not teleport you to the dimension just throws you back at your spawn

**Comment by ProsperCraft** [comment]
what is "it"  , what teleports you?

Teleports you from where to where?

**Comment by sentest** [comment]
So in the modpack stoneblock2 there is a mod called stoneblockdimensions
when you goto 255 y level on overworld it's meant to teleport you to
dimension -7. As it currently stands it doesn't teleport you it puts you
back at your local spawn in overworld

**Comment by kaziu687** [comment]
changeDimension at EntityPlayer not work on latest version. Tested with self-made mod.

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug persist, please open new issue.
