### ISSUE TITLE
[1.12.2]不支持dynmap

### ISSUE THREAD

**Issue by nidbCN** [Teneted/Tenet#182]
RT
我是MCBBS内转载dynmap插件的楼主。好多反馈mohist不支持dynmap的（插件版和MOD版都不行）：D
有解决方案咩

**Comment by Mgazul** [comment]
A simple Dynmap fix branch, a PR has been submitted to the original author, you can use this version before agreeing. https://github.com/Mohist-Community/dynmap/releases/download/mohist/Dynmap-3.0-SNAPSHOT-mohist.jar
