### ISSUE TITLE
Change Mohist language by commands

### ISSUE THREAD

**Issue by FrannDzs** [Teneted/Tenet#1833]
**What is your question ?**
Hi!, Is it possible to change the Mohist language as the mohist.yml file does, but using commands?
The `/mohist lang` argument does not seem to work.

**Comment by Romaindu35** [comment]
This is add in recent commit

**Comment by FrannDzs** [comment]
> This is add in recent commit

Spanish lang not work. I get the following message:
`For an unsupported language, the default value has been restored..`

**Comment by Shawiizz** [comment]
> > This is add in recent commit
> 
> Spanish lang not work. I get the following message: `For an unsupported language, the default value has been restored..`

Mohist is not translated into Spanish
