### ISSUE TITLE
Mohist and vanilla language change via commands and configuration file

### ISSUE THREAD

**Issue by FrannDzs** [Teneted/Tenet#1836]
**Is your feature request related to a problem? Please describe.**
I saw that they added the server console language and although it is ok I was not really referring to this but to the same language file that is used when changing lang from mohist.yml, I think that to avoid confusion there should be an option to change the vanilla language and another to change the mohist server console language.

**Describe the solution you'd like**

add command to change vanilla language:
https://github.com/MohistMC/Mohist/tree/1.16.5/src/main/resources/assets/minecraft/lang
 like `/mohist lang vanilla xx_XX`

add command to change mohist server messages:
https://github.com/MohistMC/Mohist/tree/1.16.5/src/fmllauncher/resources/lang
 like `/mohist lang mohist xx_XX `
 
The mohist.yml file now works by changing only the vanilla language, so I also suggest adding an option to change the language of the server messages in the mohist.yml file as it was originally like `lang-mohist = xx_XX`
pointing to https://github.com/MohistMC/Mohist/tree/1.16.5/src/fmllauncher/resources/lang

**Comment by Mgazul** [comment]
Can't do
