### ISSUE TITLE
Mobs freeze when Cubic Chunks is installed.

### ISSUE THREAD

**Issue by Yr1t** [Teneted/Tenet#184]
I'm running Mohist 6e6a547 and CC 1055. I'm having an issue where mobs in CC worlds don't move at all. I also have terrarium running but the issue  occurs with CC since I have tested it on a local server as the only mod and the same issue persisted.

Log: https://mcpaste.io/563ab17d69b30363
Edit: I kept posting the wrong log because I got them mixed up, this one is the right one.

**Comment by Godolt** [comment]
oop wrong link hold on

**Comment by Mgazul** [comment]
Sorry to tell you, because craftbukkit modified most of the code, resulting in incompatibility with a few mods, CC is one of them
