### ISSUE TITLE
Update Forge to fix important vulnerabilities found in log4j

### ISSUE THREAD

**Issue by vico93** [Teneted/Tenet#1887]
I don't know if this is already been worked by Mohist team, but this morning i read from some modders social media there is a huge security hole in older log4j versions that required an update of several Forge versions.

Tweets for context: 
![image](https://user-images.githubusercontent.com/3485505/145641295-a13d6a78-bbbe-4b3d-9aee-20922e88c0a5.png)
[Link](https://twitter.com/gigaherz/status/1469331286473023494)

![image](https://user-images.githubusercontent.com/3485505/145641369-87235f37-3662-449e-b4f0-d07a9ce0604d.png)
[Link](https://twitter.com/gigaherz/status/1469331288368861195) (please not that, at least for 1.12.2, there is newer builds available on Forge website)

Can Mohist update the Forge version used internally as well?

**Comment by Shawiizz** [comment]
Hello, the security issue has been fixed earlier today. We will update Forge tomorrow.

**Comment by vico93** [comment]
Thanks a lot!
