### ISSUE TITLE
1.7.10 Branch and Builds of Mohist missing

### ISSUE THREAD

**Issue by Xanton19** [Teneted/Tenet#190]
Hello there,

first of all, this is an amazing project you are creating, but sadly I have not seen any 1.7.10 Version of this Server lately. Is the 1.7.10 Mohist project discontinued?

If it has been discontinued, what are the reasons for discontinuing it and are there any up to date 1.7.10 (Forge+Paper/Spigot) alternatives or builds for the 1.7.10 Mohist server?

Anyways, thank you very much for your time, maintaining the other versions of Mohist, have a nice day.

**Comment by Shawiizz** [comment]
Hi !

Unfortunately Mohist 1.7.10 has been discontinued. The reasons are that there were a lot of bugs and Mohist 1.7.10 wasn't stable. Also, there weren't many users for this version, and the 1.7.10 is really old today, so there are less features than on the other versions. Know that we are doing everything we can to maintain Mohist :).

I know 2 alternatives : Thermos or UraniumMC. Both are working nice ^^
Have a nice day.

**Comment by Xanton19** [comment]
Thank you very much for your quick answer and explanation. Anyways, I am anyway happy to use Mohist for my 1.12.2 Server and use UraniumMC for my 1.7.10 Server. Have a nice day.
