### ISSUE TITLE
[1.12.2] Inventory and spawnpoint resets when player disconnects

### ISSUE THREAD

**Issue by missdeadful** [Teneted/Tenet#1904]
**Minecraft version :** 1.12.2

**Mohist Version :** 1.12.2 (289)

**Operating System :** Windows 10

**Description of issue :** I have a problem with mohist software. I have a server on minecraft 1.12.2 and for the last couple of months it has been running with magma. Suddenly, for whatever reason, magma stopped being available for my server and i need something that can allow plugins and mods alltogether and I tried using Mohist. So my problem is that everytime anyone disconnects their inventory, spawnpoint and level resets and i'm not able to find the problem. Please any help is welcome.

**Comment by Lunni40** [comment]
Good afternoon Mohist team, I have come to report a problem with the version of Minecraft 1.12.2 version 289, and with other versions, every time I have objects in the inventory, I exit the server and return to enter all the inventory and the initial spawn point. It seems to me that it is from version 288

**Comment by NicoHeff** [comment]
Hi Mohist team, I have also come to report the same problem with Minecraft 1.12.2 version 289.

**Comment by ghost** [comment]
Hi Mohist team, I have also come to report the same problem with Minecraft 1.12.2

**Comment by Mgazul** [comment]
fixed
