### ISSUE TITLE
[1.12.2] DIM ID not persisting after restart

### ISSUE THREAD

**Issue by austin4195** [Teneted/Tenet#1907]
**Is your feature request related to a problem? Please describe.**
As of Build 289, Mohist when restarted using worlds imported with Multiverse Core will have their DIM IDs changed.

**Describe the solution you'd like**
The solution here would be to force Mohist's implementation of Forge's DimensionManager to use the existing level.dat if it is present. By doing this, it would maintain DIM IDs across restarts and would allow for better compatibility with mods that require specifying a DIM ID for actions to occur. As an example, Pixelmon utilizes DIM IDs to specify which worlds Pokemon can spawn in in addition to the main overworld, nether, and end.

**Additional context**
Repairing this should allow for Multiverse-Core compatibility. This would allow people to create worlds that dont need to be modded as well as open up the usage of Spigot generator plugins like VoidGen.

**Comment by austin4195** [comment]
Apparently what I was referencing is found here

https://github.com/MohistMC/Mohist/blob/1.12.2/src/main/java/net/minecraftforge/common/DimensionManager.java

This must have gotten broken as of late

**Comment by speccycy** [comment]
Have you tried deleting level.dat and level.old?

I've had a problem And this way it works for me.

**Comment by Lunni40** [comment]
In the event that the server is hosted in aternos, how can I solve it?

**Comment by austin4195** [comment]
After running more testing, I have narrowed it down to a single world that is incrementing its DIM ID with each reboot. All other DIMs are maintaining their IDs. I can provide the world save as a ZIP file here in case a dev wants to take a crack at an edge case.
