### ISSUE TITLE
Connection Issue Mod - 1.16.5(889)

### ISSUE THREAD

**Issue by djburg** [Teneted/Tenet#1908]
**Minecraft Version :** 1.16.5

**Mohist Version :** 889

**Operating System :** Windows 10 & Ubuntu 20

**Logs :** (https://gist.github.com/djburg/c53a936eb4e5f6884c6d2144c7e2510e)

**Mod list :** FTB Oceanblocks - 1.11.0

**Plugin list :** Nothing Installed Yet.

**Description of issue :** Connecting Client is given size limit on join too many bytes. I don't know if it's a mod compatibilities issue or error in the code for mixins loading "441 mods when there isn't that many", I've included the debug log to help understand the issue I'm having. - Thanks!

**Comment by MagnusHJensen** [comment]
The logs, doesn't contain any severe issues as far as I can tell.
