### ISSUE TITLE
[1.12.2] Failed to load BKCommonLib (and TrainCarts which depends of it)

### ISSUE THREAD

**Issue by vico93** [Teneted/Tenet#191]
Hello!
I did a quick test of Mohist 1.12.2 (Mohist-8a57f42-server.jar), no mods installed, just dropped TrainCarts and its dependency BKCommonLib in `plugins`, but when i started the server seems like for some reason BKCommonLib crashes when loading, and in turn TrainCarts doesnt work.

[Log in hastebin](https://paste.dimdev.org/ejubalegaw.md).

**Comment by Mgazul** [comment]
Not compatible with BKCommonLib, there are too many problems

**Comment by vico93** [comment]
Oh sad!

Anyway thanks for the information!

**Comment by vico93** [comment]
Well, bergerkiller replied in the issue i make in bk github with the following:

> To add to this: the main thing I need right now is access to the remapper. This is a component that server implementations use to remap net.minecraft.server classes, method names and field names from/to CraftBukkit <> Forge. Without this I can do nothing.
MCPC+ in the distant past had an excellent remapper, which I could hook into. Every single implementation, Mohist included, has such a one. But each implementation, for reasons beyond me, uses a different one. Adding support for just one takes a very long time.

Maybe providing him the remapper and he could or not try to improve compatibility on their side...

**Comment by vico93** [comment]
Closing because @bergerkiller actually added support for hybrid servers on his side:

> So it's taken some months, but there is now rudimentary support for Mohist (and Magma/CatServer) in BKCommonLib. Feel free to check it out, and report back any issues you may find. There are some warnings at startup which can be ignored.
