### ISSUE TITLE
[1.16.5] FartherViewDistance Incompatibility

### ISSUE THREAD

**Issue by Vauxian** [Teneted/Tenet#1913]
**Minecraft Version :** 1.16.5

**Mohist Version :** 891

**Operating System :** Windows 10

**Concerned mod / plugin** : [FartherViewDistance](https://www.spigotmc.org/resources/fartherviewdistance.84950/)

**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/7756831/latest.log)

**Steps to Reproduce :**
 1. Add the FartherViewDistance plugin to a Mohist server.
 2. Connect to the server.
 3. Cry at your log being spammed constantly.

**Description of issue :** The server doesn't crash, but the logs get spammed with an exception; the method name "getLightEngine()" is not reflected, and the plugin does not function as intended. Issue still present on older versions (I tested 669, not sure how far back it goes), and to the most recent version (893).

**Comment by XionioXMaster** [comment]
+
