### ISSUE TITLE
[1.12.2] Vault and PlaceholdersAPI does not work

### ISSUE THREAD

**Issue by DeusVitale** [Teneted/Tenet#1917]
**Minecraft Version :** 1.12.2

**Mohist Version :** git-Mohist-1.12.2-291

**Operating System :** Windows 11

**Concerned mod / plugin** : Vault and PlaceholdersAPI

**Logs :** https://pastebin.com/idXAx8rE

**Steps to Reproduce :**
 1. Start server
 2. Gives an error in the console
 3. Placeholders does not work

**Description of issue :** this works perfectly in other servers like spigot or paper but in mohist this error happens

**Comment by speccycy** [comment]
PlaceholdersAPI version?

**Comment by DeusVitale** [comment]
> PlaceholdersAPI version?

2.11.0 but I tried in other versions and in the same way it does not work

**Comment by thejbone** [comment]
The issue is due to the ecloud integration. I have a fix if you are interested. thejbone#7391

**Comment by Mgazul** [comment]
#1949
