### ISSUE TITLE
[1.16.5] Crash when respawn with First Aid

### ISSUE THREAD

**Issue by FrenchBoyi** [Teneted/Tenet#1920]
**Minecraft 1.16.5** Minecraft version

**mohist-1.16.5-891-server** Provide Mohist build number

**Windows 11** Provide the name of your OS

**First Aid** : Provide mod / plugin name and download link if possible
https://www.curseforge.com/minecraft/mc-mods/first-aid

**Logs :** Link(s) of logs and crash reports if you have
[crash-2021-12-22_15.19.04-server.txt](https://github.com/MohistMC/Mohist/files/7763237/crash-2021-12-22_15.19.04-server.txt)

**Steps to Reproduce :**
 1. Install First Aid on mohist-1.16.5-891-server
 2. Kill yourself in game and respawn
 3. Server crash

**Description of issue :** Give all details about your issue

**Comment by joaoespanhol** [comment]
#1760 and 1960
no have more problem. :)
