### ISSUE TITLE
swtiching drives makes pl ayerdata no work

### ISSUE THREAD

**Issue by drewciaramitaro** [Teneted/Tenet#1922]
i switch drive to different pc and sicne drive letter differnet the player data no load and say "Failed to save player data for user xxxx_swagmaster420deezznutsmynamejeff21fidgetspinnercompliationxxxx_"
movin bak fix lol

**Minecraft Version :** {Minecraft version}
1.12.2

**Mohist Version :** {Provide Mohist build number}
 1.12.2-290

**Operating System :** {Provide the name of your OS}
window

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}
this comman dcrashed my server lol

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}
essentials

**Description of issue :** {Give all details about your issue}
pls fix

**Comment by speccycy** [comment]
Check your `mohist.yml` file.

and then look at the `playersdirectory:`

**Comment by drewciaramitaro** [comment]
thanks but imgay

**Comment by Mgazul** [comment]
#291 fixed
