### ISSUE TITLE
[1.16.5] crasher server

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#1925]
**Minecraft Version :** 1.16.5

**Mohist Version :** 893

**Operating System :** windows 11

**Concerned mod / plugin** :  Plugin: luckperms, system and Mod Mekanism, mcmt

**Logs :** https://mclo.gs/H1JWWD6

**Steps to Reproduce :**
 1. start server
 2. enter server
 3. dies to a zombie or other aggressive mob

**Description of issue :** Give all details about your issue

**Comment by joaoespanhol** [comment]
https://mclo.gs/kVPraSJ

more log

**Comment by joaoespanhol** [comment]
https://mclo.gs/8ngbgC4
@MagnusHJensen

**Comment by joaoespanhol** [comment]
just dies, then respawn.

**Comment by MagnusHJensen** [comment]
I see, something odd. I will try and dig deeper :)

**Comment by joaoespanhol** [comment]
> I see, something odd. I will try and dig deeper :)

do you want the debug?

**Comment by MagnusHJensen** [comment]
This is a issue with a mod, on vanilla no errors.

**Comment by MagnusHJensen** [comment]
Same capability issue as #1920
