### ISSUE TITLE
[1.16.5] Server hangs in infinite loop, with a thread dump.

### ISSUE THREAD

**Issue by MagnusHJensen** [Teneted/Tenet#1926]
**Minecraft Version :** 1.16.5

**Mohist Version :** 891

**Operating System :** Redhat 8 Linux

**Logs :** See image
**Mod list :** AppleSkin 2.2, Callable Horses 1.2.1.4, Chat Heads 0.2, Equipment Compare 1.2.7, Fairy Lights 4.0.5, GeckoLib 3.0.35, HWYLA 1.10.11-B78_1.16.2, Iceberg 1.0.24, Inventory HUD+ 3.4.1, Item Borders 1.1.2, LootBeams 1.16.5, SWEM (our mod in beta), Storage Drawers 8.3, U Team Core 3.2.1.196, USeful Backpacks 1.12.1.90, Waila Harvestability 1.1.15.

**Plugin list :** EssentialsX 2.19.2, EssentialsXSpawn 2.19.2, WorldGuard 7.0.5, AutomaticInventory, CoreProtect 20.1,  LPC 3.2, LuckPerms 5.3.74, ForgivingVoid 1.1, HolographicDisplays 2.4.6, HorsesTpWithMe 7.4.0.2

**Description of issue :** Server just hangs randomly, with no errors, and repeats what is shown in the screenshot, and kicks everyone out. This did not happen at first, it suddenly just happened out of nowhere, no new mods etc were added.
![unknown](https://user-images.githubusercontent.com/32039051/147298632-5753813c-0fc0-4b88-88f4-6dc2bfc27b14.png)

**Comment by Mgazul** [comment]
#1463
