### ISSUE TITLE
[1.12.2] Forge unable to call bukkit

### ISSUE THREAD

**Issue by austin4195** [Teneted/Tenet#1927]
**Minecraft Version :** 1.12.2

**Mohist Version :** 292

**Operating System :** Linux (Hosted)

**Logs :** https://haste.mohistmc.com/ixegoqorut.apache , https://haste.mohistmc.com/iyabuxoweh.properties

**Mod list :** https://haste.mohistmc.com/ilulakumoc

**Plugin list :** https://haste.mohistmc.com/alunogoziw

**Description of issue :** The issue occurring is that ForgeMenus (https://github.com/Daniel-Forge-Development/ForgeMenus) which makes use of Forge Placeholder API and its extensions (https://github.com/Daniel-Forge-Development/ForgePlaceholderAPI-Extensions) are unable to talk with LuckPerms and CMI. When speaking with the dev, they seem to work in other hybrid environments meaning that something may be not working properly here. This was all tested with the forge-can-call-bukkit setting set to true.

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/147861805-83d441fa-1424-4e83-87a1-28f8be07747d.png)
try change false for true file mohist @austin4195

**Comment by austin4195** [comment]
Already did that

Portion of mohist.yml

```
mohist:
  use_custom_java8: false
  disable_config_update: false
  check_update: true
  downloadfile_command_enabled: false
  server-type: FML
  BukkitPermissionsHandler: true
  connectionTimeout: 15000
  lang: xx_XX
  libraries_downloadsource: MOHIST
  console_name: Server
  watchdog_spigot: true
  forge_can_call_bukkit: true
  fail-on-unresolved-gameprofile: true
  CloseChatInConsole: false
  showlogo: true
  check_libraries: false
  support_nocmd: false
  watchdog_mohist: false
  disable_mods_blacklist: false
  disable_plugins_blacklist: false
  networkmanager:
    debug: false
    intercept: []
  check_update_auto_download: false
  realtimeticking: false
```

**Comment by austin4195** [comment]
Issue still occurring despite the settings above. Still occurring on build 297

**Comment by austin4195** [comment]
https://github.com/Daniel-Forge-Development/ForgePlaceholderAPI-Extensions/issues/8
https://github.com/Daniel-Forge-Development/ForgePlaceholderAPI-Extensions/issues/7
