### ISSUE TITLE
Mohist error

### ISSUE THREAD

**Issue by y0tsy** [Teneted/Tenet#1938]
**Minecraft Version :** 1.16.5

**Mohist Version :** 895

**Operating System :** Linux (amd64) version 4.16.18-zen

**Logs :** https://haste.mohistmc.com/soxucemuxe.rb

**Mod list :** Quark-1.16.5-r2.4-321.jar, AutoRegLib-1.6-49.jar, Placebo-1.16.5-4.6.1.jar, ironchest-1.16.5-11.2.21.jar, clumps-6.0.0.27.jar , Daconic-Evolution-1.16.5-3.0.18.428-universal.jar, BrandonsCore-1.16.5-3.0.11.238-universal.jar, create-mc1.16.5_v0.3.2g.jar, CodeChickenLib-1.16.5-4.0.4.435-universal.jar, flywheel-1.16-0.2.5.jar, MoreFoods_by_Daleeny_v1.1_MCV1.16.5.jar, mohist-1.16.5-895-universal.jar, mekanism.jar, smoothboot-forge-1.16.4-1.2.2.jar, jei-1.16.5-7.7.1.138.jar, ferritecore-2.1.0-forge.jar, sulfuric-1.1.jar, Apotheosis-1.16.5-4.8.4.jar, create-stuff-additions1.16.5_v1.1.5.jar, configured-1.5.1-1.16.5.jar              

**Plugin list :** no

**Description of issue :** I don't know anything about this problem, I don't know what to do with it either, can you help?

**Comment by MagnusHJensen** [comment]
When did this happen? What were you doing? Is there a 100% way to reproduce the same error, if so what are the steps?

**Comment by y0tsy** [comment]
This error prevents the server from starting.

**Comment by MagnusHJensen** [comment]
So just on server start it crashes?

**Comment by y0tsy** [comment]
yes.

**Comment by y0tsy** [comment]
Even without mods, it fails.

**Comment by MagnusHJensen** [comment]
That is not true, if it fails with the same issue even without mods, try using the 897 version of mohist.

**Comment by y0tsy** [comment]
Okay, I'll try

**Comment by y0tsy** [comment]
The error will be repeated.

**Comment by MagnusHJensen** [comment]
I can't reproduce.
I don't get any errors or crashes.
https://haste.mohistmc.com/rusohabese.css

**Comment by y0tsy** [comment]
I deleted all the server files, leaving only mods, plugins, worlds. Then launched Moist. And it helped me!
