### ISSUE TITLE
tpLogin v1.5.1 卡加载无法启动服务器

### ISSUE THREAD

**Issue by CyiceK** [Teneted/Tenet#194]
服务器安装有插件tpLogin v1.5.1会卡加载，无法启动正常服务器
服务器版本 1.12
服务器端版本 Mohist-6408ec0-server

**Comment by CyiceK** [comment]
对了，还有个问题，不想新开issues了
涉及mod： [环境污染]AdPother-1.12.2-1.2.0.0-build.0454 
问题：无法使用真空袋和真空管吸收气体，吸收后气体会跑出来而不是留在玩家物品栏里

**Comment by Mgazul** [comment]
1.5.1？ 能告诉我链接吗

**Comment by Mgazul** [comment]
我使用该版本测试 没有发现任何问题 https://www.spigotmc.org/resources/tplogin.21692/

**Comment by CyiceK** [comment]
https://dev.bukkit.org/projects/tplogin/files

**Comment by Mgazul** [comment]
> https://dev.bukkit.org/projects/tplogin/files

我看了一下 你这个版本最高仅支持1.7.2 请使用我上面那个 如果你坚持使用，可以把配置文件里的更新检测关掉
