### ISSUE TITLE
[1.12.2] CrackShot插件伤害兼容问题 Crackshot plug-in injury compatibility problem

### ISSUE THREAD

**Issue by luoxiawuchen** [Teneted/Tenet#1942]
**Minecraft Version :1.12.2

**Mohist Version :292

**Operating System : linux（centos）

**Concerned mod / plugin** : CrackShot

**Logs :none 无报错日志，和任何与本插件相关的有效信息

**Steps to Reproduce :**
 1. 安装插件，启动服务器
 2. 输入/shot get Ak-47 获得枪支
 3. 右键射击动物，无伤害
 4. 我查阅资料是说雪球作为弹药本来就没伤害，但是经过测试spigot1.12.2是有伤害的，墨端的66号构建只对玩家有伤害，200版本左右开始对玩家和实体均无伤害。所以有些匪夷所思，也没有提示任何的报错
 
1. Install the plug-in and start the server
2. Enter / shot get AK-47 to get the gun
3. Right click to shoot animals without damage
4. I refer to the information to say that snowballs as ammunition do not hurt, but they have been tested spigot1 12.2 is harmful. Mo Duan's No. 66 construction only does harm to players. From about 200 version, it does no harm to players and entities. So it's ridiculous and doesn't prompt any error reporting

**Description of issue :
枪械插件雪球作为弹药时会无伤害，但是经过测试spigot1.12.2是有伤害的，墨端的66号构建只对玩家有伤害，200版本左右开始对玩家和实体均无伤害。所以有些匪夷所思，也没有提示任何的报错。

The firearm plug-in snowball will be harmless as ammunition, but it has been tested spigot1 12.2 is harmful. Mo Duan's No. 66 build only does harm to players. From about 200 build, it does no harm to players and entities. So it's ridiculous and doesn't prompt any error reporting.

**Comment by 290qthfsgghredv** [comment]
这个我知道，是监听器的bug，我写插件的时候遇到了
ProjectileHitEvent 的getHit 方法应该传回击中的目标
但实际上传回的是抛射物本身
也就是说结算的时候伤害结算到你那个雪球上了

**Comment by luoxiawuchen** [comment]
> 这个我知道，是监听器的bug，我写插件的时候遇到了 ProjectileHitEvent 的getHit 方法应该传回击中的目标 但实际上传回的是抛射物本身 也就是说结算的时候伤害结算到你那个雪球上了

啊这 谢谢大佬解释 就豁然开朗啊 几天测试了特久 请问是有办法得到解决和修复吗？
这个是服务端本身的bug？坐等大佬们修复这个监听器？（本来也不抱啥希望了 抱着反馈试一试的心态233）

**Comment by 290qthfsgghredv** [comment]
我只能说你等原作者修
