### ISSUE TITLE
官方forge换成Mohist后出现客户端登陆问题 After the official forge is changed to Mohist, there is a client login problem

### ISSUE THREAD

**Issue by lordlearnstocode** [Teneted/Tenet#1943]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-292-server.jar

**Operating System :** linux（tb找的面板服）

**Logs :** https://haste.mohistmc.com/agoyohupib.yaml

**Mod list :** https://haste.mohistmc.com/imajorarom

**Plugin list :** 无

**Description of issue :** 前言：这个整合包是RlcraftV2.9（原版），我自己加了几个mod进去。以上在forge-1.12.2-14.23.5.2860.jar是可以完全正常运行的，为了用一些插件所以选择了Mohist
问题：我换成Mohist后启动服务器，在确定服务器已经启动完全后（进度100%），我在客户端登陆，它提示登陆中，于此同时服务器提示以上的logs。过了一小会儿，客户端提示连接已丢失。

**Comment by Romaindu35** [comment]
Please create new issue with text translate in english !

**Comment by lordlearnstocode** [comment]
Minecraft Version : 
1.12.2

Mohist Version : 
mohist-1.12.2-292-server.jar

Operating System : linux (actually a web terminal which i brought online)

Logs : https://haste.mohistmc.com/agoyohupib.yaml

Mod list : https://haste.mohistmc.com/imajorarom

Plugin list : none

Description of issue : 
Foreword: This modpack is RlcraftV2.9 (original version i downloaded at curseforge),and I have added a few mods to it. The above can run normally in forge-1.12.2-14.23.5.2860.jar. In order to use some plugins, I chose to use Mohist to host the game.
Question: I switched to Mohist and started the server. After I made sure that the server was started completely (100% progress), I logged in on the client, and it prompted loginning in . At the same time, the server prompts the above logs. After a short while, the client prompts that the connection has been lost.

**Comment by lordlearnstocode** [comment]
sorry,i fotgot to tell you guys i disable a mod name grapplemod-1.12.2-v12.2.jar which caused err,and i have reported the problem,expect that nothing was removed compared to the orginal modpack

**Comment by lordlearnstocode** [comment]
the modpack can be downloaded here :https://www.curseforge.com/minecraft/modpacks/rlcraft/files version 2.9
The other mods I added myself:
 
![image](https://user-images.githubusercontent.com/65746397/147593053-5317faab-70a4-4a3c-8455-cbb2ea786d7b.png)

**Comment by lordlearnstocode** [comment]
if you don't mind i can upload a zip contains all the mods i added.😀

**Comment by lordlearnstocode** [comment]
already solved.
just pregenerate the server at my windows desktop
 and copy all the file to linux server and it just runs fine.
