### ISSUE TITLE
[1.16.5] All accessories will disappear after death.

### ISSUE THREAD

**Issue by jingjing96** [Teneted/Tenet#1947]
**Minecraft Version :** 1.16.5
**Mohist Version :** 900

**Operating System :** Server: Debian 9, Client: Windows 10

**Concerned mod / plugin** : Curios API

**Logs :** none

**Steps to Reproduce :**
 1. /gamerule keepInventory true
 2. put on an accessory, then die
 3. all accessories will disappear

**Description of issue :** I installed Curios API on my server, but after players died, the accessories will disappear.

**Comment by Ashley123477** [comment]
Related to #1940 ?

Seems the same as things not carrying over after death

**Comment by luckyyjdev** [comment]
我也遇到了mohist 904

**Comment by Romaindu35** [comment]
Please translate in English
