### ISSUE TITLE
[1.12.2] Vault and PlaceholdersAPI does not work

### ISSUE THREAD

**Issue by DeusVitale** [Teneted/Tenet#1949]
**Minecraft Version :** 1.12.2

**Mohist Version :** git-Mohist-1.12.2-291

**Operating System :** Windows 11

**Concerned mod / plugin** : Vault and PlaceholdersAPI 2.11.1

**Logs :** https://paste.helpch.at/gabomuzuni.sql

**Steps to Reproduce :**
1. Start server
2. Gives an error in the console
3. Placeholders does not work

**Description of issue :** this works perfectly in other servers like spigot or paper but in mohist this error happens

**Comment by Mgazul** [comment]
This is probably related to Expansion itself. Expansion uses the old version of PlaceholderAPI, and the new version of PlaceholderAPI modifies the interface, which makes Expansion lack the new interface inheritance.

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/147861782-26074f5e-6232-4034-9091-09b237e78c07.png)
