### ISSUE TITLE
[1.16.5]Drops can't be pick up.

### ISSUE THREAD

**Issue by CNXudiandian** [Teneted/Tenet#1953]
**Minecraft Version :** 1.16.5

**Mohist Version :** mohist-1.16.5-886

**Operating System :** Windows Server 2012 R2(Server),Windows 10(Clients)

**Logs :** no crash logs

**Mod list :** not installed any mods

**Plugin list :** not installed any plugins

**Description of issue :** 
I can't pick up drops,however can see they,and they can't naturally disappear.
I was tried restart my server,but not resolved.
I don't think so is client problem,because my friends can see they too,and can't pick up.
They Strangely can be Flint and Steel burned up.

(Sorry, I don't speak English very well,I hope you can understand...)

**Comment by MagnusHJensen** [comment]
The items are however interactable with the world (hoppers, flint and steel etc.) but nobody can pick them up.

It happens to me if the items are on the ground, and the server shuts down. Then when it get's back up, they can't be picked up.

**Comment by MysticalLatios** [comment]
I'm having this same issue, simular setup but on Linux. All items on the ground afters server restart enter this state of not being able to be picked up by players. 

Note that that items can be deleted with the /kill @e[type=item] command. Blocks from mods that pick up items from the world like hoppers can also interact(pick up, move, ect) with these dropped items that can not be picked up by players.

**Comment by CNXudiandian** [comment]
oh,thank you for your answers. @MagnusHJensen @MysticalLatios 
It useful for me.
but who are you is developer?I want know the issue is a bug or a feature?and it can be fixed?

**Comment by joaoespanhol** [comment]
i have same problem my server.

**Comment by Mike5357** [comment]
Correct, this problem seems to be relevant to drops persisting between server reboots. To reproduce, drop an item on the ground, then /stop the server. When the server comes back online, you cannot pick up the item that was dropped.

**Comment by MCUmbrella** [comment]
got the same problem here. It doesn't seem to be a problem with some plugins

**Comment by joaoespanhol** [comment]
I had this problem with the other versions.

But in the current one, this bug doesn't happen
