### ISSUE TITLE
[1.16.5-904] Player not able to respawn after death.

### ISSUE THREAD

**Issue by Gizmo0320** [Teneted/Tenet#1959]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {904}

**Operating System :** {Linux}

**Logs :** {[Crash Report](https://gist.github.com/Gizmo0320/6dccb91b72127b3b0f137af4a6a16035), [Lastest Log](https://gist.github.com/Gizmo0320/cd694ccfcb3cfdbdf2e32ef507c4862a)}

**Mod list :** {[Mod List](https://gist.github.com/Gizmo0320/1cc5247c706b838e5cff83632cc271bf)}

**Plugin list :** {No Plugins Installed}

**Description of issue :** {We are able to load the server just fine and join the world. But once someone dies they are not able to click the respawn button. We have tried removing some mod to see if it would help and we have no idea what it could be.}

**Comment by joaoespanhol** [comment]
Mod causing problem: tombstone

**Comment by Gizmo0320** [comment]
We will remove and test again. Thank you

**Comment by Gizmo0320** [comment]
New updated log after removing tomstone and a starting a brand new world. https://gist.github.com/Gizmo0320/a0f1e14e4d00bc7dcc678068415f6c2e

**Comment by Gizmo0320** [comment]
#1643 
I don't know if it is related to this. I see there is some respawn issues in the issue as well.

**Comment by Gizmo0320** [comment]
and #1772

**Comment by Gizmo0320** [comment]
After much testing we have found that it is Epic Flight Mod that causes the issue. 
https://gist.github.com/Gizmo0320/2dbbec607207aee2233545458d4cf72a

**Comment by Gizmo0320** [comment]
This was fixed with fef6900

how ever I have a new issue. I will open a new issue for it.
