### ISSUE TITLE
[1.16.5] Epic Fight mod crash server after entering fight mode from respawn. 

### ISSUE THREAD

**Issue by Gizmo0320** [Teneted/Tenet#1964]
**Minecraft Version :** 1.16.5

**Mohist Version :** 905

**Operating System :** Linux

**Concerned mod / plugin** : Epic Fight Mod

**Logs :** Link(s) of logs and crash reports if you have
[Crash Report](https://gist.github.com/Gizmo0320/e0edf4f54342edb9d3ae9aaa356681e7), [Log](https://gist.github.com/Gizmo0320/4aea87a5b4690c843c26b0c82c39f769)
**Steps to Reproduce :**
 1. Enter Fight Mode attack something, Die
 2. Respawn
 3. Enter Fight Mode again and if you die the server crashes

**Description of issue :** Give all details about your issue

**Comment by MagnusHJensen** [comment]
This is most likely the cause of the same commit fixing your other issue. fef6900
It's an underlying issue, that needs to be fixed, to help all issues with this kind of problem.

**Comment by Gizmo0320** [comment]
Is there anything on the mod side that could be changed to fix this or is this strictly a server side issue?

**Comment by Romaindu35** [comment]
Same #1966
