### ISSUE TITLE
[1.16.5] Epic Fight mod crashing server because "serverplayerdata" is null

### ISSUE THREAD

**Issue by lambor590** [Teneted/Tenet#1965]
**Minecraft Version :** 1.16.5

**Mohist Version :** 906

**Operating System :** Debian 11 (Linux)

**Concerned mod / plugin** : [Epic Fight Mod](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)

**Logs :** [Link of the logs](https://gist.github.com/lambor590/9c6830c364c2a7c76b9ecd9ee15a2b8c)

**Steps to Reproduce :**
 1. Taking fall damage triggers the error (you don't get damage). And if you move your camera, it also laggs the server a lot.
 2. Taking damage from a mob crashes the server.

**Description of issue :** The people that play in my server said that they didn't do anything. In build 904 I had an issue which caused a dead player don't be able to respawn. (I had to remove his account registry to be able to spawn). And that was fixed in build 905. But now I have the problem mentioned in this issue.

**Comment by lambor590** [comment]
Not always happens apparently, and battle mode doesn't seem to affect.
And if you are bugged, you can debug yourself if you jump.

**Comment by Romaindu35** [comment]
Same #1966
