### ISSUE TITLE
Console formatting broken

### ISSUE THREAD

**Issue by reiyooki** [Teneted/Tenet#1967]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-904

**Operating System :** Windows 10

**Logs :** N/A

**Mod list :** N/A

**Plugin list :** N/A

**Description of issue :** Console output does not properly parse color code formatting. This was fixed in Forge versions by removing the library `log4j-slf4j18-impl`, however removing the library manually just causes Mohist to re-download it on next launch.

**Comment by lxgnzlz05** [comment]
duplicated

**Comment by lxgnzlz05** [comment]
https://github.com/MohistMC/Mohist/issues/1877 see that... i have a unnoficial fix
