### ISSUE TITLE
Does Mohist force servers into Offline mode [1.12.2]

### ISSUE THREAD

**Issue by ImplicitSaber** [Teneted/Tenet#1969]
**What is your question ?**
I have noticed that my server says it is in offline mode though in server.properties online mode is on. Is Mohist changing it to offline mode? I am running Java 8, Mohist 1.12.2 on Linux x64.
Literally, here is the line from _server.properties_:
`online-mode=true`

**Comment by Shawiizz** [comment]
Mohist doesn't change that, but yesterday I heard Mojang servers were maybe down and that maybe explain your problem.
