### ISSUE TITLE
[1.12.2] Crash with CensoredASM(SneedASM)(LoliASM)

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#1973]
**Minecraft Version :** 1.12.2

**Mohist Version :** 296

**Operating System :** Windows

**Concerned mod / plugin** : loliasm-4.4.jar(https://www.curseforge.com/minecraft/mc-mods/lolasm)

**Logs :** 
Latest: 
[latest.log](https://github.com/MohistMC/Mohist/files/7832781/latest.log)

Crash: 
[crash-2022-01-08_12.24.10-server.txt](https://github.com/MohistMC/Mohist/files/7832776/crash-2022-01-08_12.24.10-server.txt)

**Steps to Reproduce :**
 1. Install Mohist
 2. Install in mods folder loliasm-4.4.jar
 3. Start server.
 4. See crash.

**Description of issue :** When running with this mod, the server crashes. I could just delete it, but it is needed for the TFC-Florae mod, and this is a huge addon for the TFC mod. Therefore, it is not possible to simply delete it. I hope to fix this bug.

**Comment by Mgazul** [comment]
remove phosphor mod

**Comment by Exzept1on** [comment]
[latest.log](https://github.com/MohistMC/Mohist/files/7834725/latest.log)
Same :(
Maybe then I attached the old crash log. You need to look at the latest.log, the server does not even have time to start and immediately closes.

**Comment by Exzept1on** [comment]
Thanks. All works fine!
