### ISSUE TITLE
[1.16.5] Any mob mod crashs the server. 

### ISSUE THREAD

**Issue by BuddySirJava** [Teneted/Tenet#1974]
**Minecraft Version :** 1.16.5

**Mohist Version :** 907

**Operating System :** Windows 10

**Logs :** https://www.toptal.com/developers/hastebin/ewisefavew.yaml https://haste.mohistmc.com/yehiqimepa.yaml

**Mod list :** AlexMobs, caveBiomeapi, cavesandcliffs, citadel, journeymap, mowziesmobs, MutantBeasts, pandoras_creatures, randompatches, TheAbyss2, twilightforest

**Plugin list :** No plugins

**Description of issue :** Any mod that contains mobs causes the server crash and I tested every mod one by one on the server. These mods work fine on client without any problem.

**Comment by Mgazul** [comment]
1.16.5 does not support the use of java17

**Comment by BuddySirJava** [comment]
> 1.16.5 does not support the use of java17

I tried with Java 8 and Java 11. Still it has the same problem
