### ISSUE TITLE
最新构建1.12.2-297-server被报毒

### ISSUE THREAD

**Issue by xzrui** [Teneted/Tenet#1980]
**Minecraft Version :** 1.12.2

**Mohist Version :**297

**Operating System :** Windows Server 2019

**Logs :** windows defender 报告Scipt/Wacarac.B!ml病毒直接删除

**Mod list :** windows defender 报告Scipt/Wacarac.B!ml病毒直接删除

**Plugin list :** windows defender 报告Scipt/Wacarac.B!ml病毒直接删除

**Description of issue :** 墨端本体被windows defender 报告Scipt/Wacarac.B!ml病毒直接删除，下载源是官网直接下载，已验证md5码正确，上一个构建并未出现此问题

**Comment by Mgazul** [comment]
与浏览器有关
