### ISSUE TITLE
[1.16.5] Mohist does not recognize Forge mod permissions

### ISSUE THREAD

**Issue by Rasgnarok** [Teneted/Tenet#1981]
**Minecraft Version :** 1.16.5

**Mohist Version :** mohist-1.16.5-904-server.jar

**Operating System :** CentOS

**Concerned mod / plugin** : Literally any Forge mod for 1.16.5, https://www.curseforge.com/minecraft/mc-mods?filter-game-version=2020709689%3A8203&filter-sort=4

**Description of issue :** Forge mod permissions are not recognized on Mohist 1.16.5. Using LuckPerms-Bukkit-5.3.98.jar.

**Comment by Rasgnarok** [comment]
Related to: https://github.com/MohistMC/Mohist/issues/1694

**Comment by Rasgnarok** [comment]
Related to: https://github.com/MohistMC/Mohist/issues/1823

**Comment by Rasgnarok** [comment]
Related to on-death permission loss atop of the Forge-native issue: https://github.com/MohistMC/Mohist/issues/1830, https://github.com/MohistMC/Mohist/issues/1839

**Comment by Rasgnarok** [comment]
Related to: https://github.com/MohistMC/Mohist/issues/1614

**Comment by Rasgnarok** [comment]
Related to: https://github.com/MohistMC/Mohist/issues/1592

**Comment by Rasgnarok** [comment]
Possibly related to: https://github.com/MohistMC/Mohist/issues/1477

**Comment by Rasgnarok** [comment]
Related to: https://github.com/MohistMC/Mohist/issues/1458

**Comment by Rasgnarok** [comment]
Possibly related: https://github.com/MohistMC/Mohist/issues/1436

**Comment by johnfriedrich** [comment]
Can confirm on mohist-1.16.5-910-server.jar with Dynmap Forge and Worldedit Forge. I can tab complete commands, but getting "Unknown command. Type "/help" for help"

**Comment by witchyface** [comment]
Would appreciate if this could be looked into asap.

**Comment by Mikirae** [comment]
Would appreciate it if someone would be able to take the time to look into this :)

**Comment by LeoB-26** [comment]
same, I want to use mohist so bad but this is the dealbreaker for me

**Comment by nicholasrobertm** [comment]
This is a big issue for using mohist with both forge mods and plugins
