### ISSUE TITLE
[1.16.5] Failed to handle packet with ProtocolLib/InteractiveChat installed

### ISSUE THREAD

**Issue by Mike5357** [Teneted/Tenet#1983]
**Minecraft Version :** 1.16.5

**Mohist Version :** 912

**Concerned mod / plugin** : InteractiveChat (https://www.spigotmc.org/resources/interactivechat-show-items-inventory-in-chat-custom-chat-keywords-bungee-velocity-support.75870/)

**Logs :** https://pastebin.com/dumvxeV9

**Steps to Reproduce :**
 1. Install ProtocolLib and InteractiveChat
 2. Boot the server
 3. Attempt to join and get kicked by an Internal Server Error with the above log error.

**Description of issue :** ProtocolLib on its own works fine and players are able to join the server, however with InteractiveChat installed players are immediately kicked on join with an Internal Server Error (Failed to handle packet net.minecraft.crash.ReportedException: Sending packet).

**Comment by MagnusHJensen** [comment]
This comes from NMS not being fully implemented if I read the error correctly.

**Comment by Mgazul** [comment]
#1540
