### ISSUE TITLE
[1.18.1]Chest dupe and item disappearing

### ISSUE THREAD

**Issue by ztfarcBG1** [Teneted/Tenet#1985]
**Minecraft Version :** {1.18.1}

**Mohist Version :** {105}

**Operating System :** {Linux Zorin OS}

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {None}

**Plugin list :** {None}

**Description of issue :** {if you right click drag items the amount of items back every item will be that and sometimes when you put items in chest they disappear}

**Comment by MagnusHJensen** [comment]
Please add [1.18.1] to the issue name.
