### ISSUE TITLE
[1.16.5] WorldEdit Not Functional

### ISSUE THREAD

**Issue by Reforged-Network** [Teneted/Tenet#1987]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-916

**Operating System :** Provide the name of your OS

**Concerned mod / plugin** : World Edit

**Logs :** Link(s) of logs and crash reports if you have
https://haste.mohistmc.com/uxuhuvilud.properties

**Steps to Reproduce :**
 1. Set 2 potions then use any of the WE commands to edit terrain (//set air)

**Description of issue :** WE isn't functional in its current state and with 1.16.5 being the new 1.12.2 you can expect it to be supported in the modding community for a decent amount of time. I think it would be beneficial for Mohist fix this issue.

**Comment by Mgazul** [comment]
#997
