### ISSUE TITLE
[1.12.2] Crash with CubicChunks

### ISSUE THREAD

**Issue by idkimanerd** [Teneted/Tenet#1988]
**Minecraft Version :** 1.12.2

**Mohist Version :** 299

**Operating System :** Windows 10

**Concerned mod / plugin** : CubicChunks https://www.curseforge.com/minecraft/mc-mods/opencubicchunks

**Logs :** Link(s) of logs and crash reports if you have
https://gist.github.com/idkimanerd/e4ac3f1d9e0f8146bcf73ea986626fe8
Latest
https://gist.github.com/idkimanerd/1029a75ca7cfde968d02ff758fa82c47
Crash

**Steps to Reproduce :**
 1. Install CubicChunks
 2. Start server

**Description of issue :** Trying to run a server with CubicChunks and it crashed.

**Comment by idkimanerd** [comment]
I also have luckperms installed

**Comment by lxgnzlz05** [comment]
normal....

https://prnt.sc/26eezbi

**Comment by idkimanerd** [comment]
Oh  I thought that meant there wasn't a dedicated spigot version
