### ISSUE TITLE
[1.12.2] ProtocolLib unable to get the NMS code. Hence kicking player for not being able to send packets.

### ISSUE THREAD

**Issue by Xeravax** [Teneted/Tenet#1989]
**Minecraft Version :** 1.12.2

**Mohist Version :** 1.12.2-299

**Operating System :** CentOS 8

**Concerned mod / plugin** : https://www.spigotmc.org/resources/protocollib.1997/ - Version 4.7.0

**Logs :** [Link(s) of logs and crash reports if you have](https://mclo.gs/ayvXlZs)

**Steps to Reproduce :**
 1. Get a mohist server with the latest ProtocolLib (as of now, 4.7.0) and the latest Mohist (as of now, `1.12.2-299`). 
 2. Try and join the server with \<insert modpack name here\>
 3. Player gets kicked from the server with **Internal Server Error**

**Description of issue :** See above ^

**Comment by Mike5357** [comment]
This is an issue in both the 1.12 and 1.16 builds. 
See: #1983
