### ISSUE TITLE
[1.12.2] 加载 Craftconomy3 插件时线程卡死, 服务端无响应

### ISSUE THREAD

**Issue by uthanw** [Teneted/Tenet#1990]
**Minecraft Version :** 1.12.2

**Mohist Version :** 299

**Operating System :** Windows Server 2019

**Concerned mod / plugin** : https://www.spigotmc.org/resources/craftconomy.2395/update?update=10532

**Logs :** https://gist.github.com/xiaoyangOvO/16a7717f4fce6bc917c1bd308bf1eb17

**Steps to Reproduce :**
 1. 加载这个插件

**Description of issue :** 服务端加载到这个插件之后再无任何响应, Yum 插件的线程监控也没有做出反应. 加载该插件前后均没有任何有关报错

**Comment by Mgazul** [comment]
你日志是使用298的
