### ISSUE TITLE
[1.18.1] Unable to use crafting table

### ISSUE THREAD

**Issue by foliet** [Teneted/Tenet#1991]
**Minecraft Version :** 1.18.1

**Mohist Version :** 1.18.1-106

**Operating System :** Windows11

**Logs :** None

**Mod list :** None

**Plugin list :** None

**Description of issue :** Items disappear when placed on a crafting table, such as when 4 woods are placed on it. When changing to forge's original server, this problem does not occur. There are no other mods and plugins when testing, and it is a newly opened map.

**Comment by foliet** [comment]
I would like to know why my issue was deleted

**Comment by lxgnzlz05** [comment]
> I would like to know why my issue was deleted

Because 1.18 doenst have support. It is on BETA. The supported mohist version is 1.12.2 and 1.16.5

**Comment by foliet** [comment]
If I find a bug, where should I go to report it?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MohistMC/Mohist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月17日(星期一) 凌晨3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MohistMC/Mohist] [1.18.1] Unable to use crafting table (Issue #1991)





  
I would like to know why my issue was deleted
  
Because 1.18 doenst have support. It is on BETA. The supported mohist version is 1.12.2 and 1.16.5
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
