### ISSUE TITLE
[1.12.2] Villagers and Illagers spawing without AI

### ISSUE THREAD

**Issue by vico93** [Teneted/Tenet#1999]
**Minecraft Version :** 1.12.2

**Mohist Version :** b300

**Operating System :** Windows 10 x64 (b 21H2)

**Logs :** [latest.log (but it doesn't show any error)](https://gist.github.com/vico93/e0dda937f238a740a1a661a6fa0f125e)

**Mod list :** [Here](https://haste.mohistmc.com/ruluduyaya)

**Plugin list :** [Here](https://haste.mohistmc.com/ofodohucuq)

**Description of issue :** I have some .nbt structures (with mobs embedded) that are spawned by the mod [Pillar](https://github.com/Vazkii/Pillar) on the world. Today, when i started a new world (to check if build 300 really have fixed the issue Gegy reported on PR #1997 - that i reported the bug to her in first place since it involved another of my Pillar structures), i noticed a structure that have a Johnny-like illager that spawned with the illager semi-floating, not reacting at all (even his axe haven't been drawn) and i couldnt hurt him with a wooden sword.
![2022-01-18_21 26 45](https://user-images.githubusercontent.com/3485505/150039263-76965296-6d75-4b20-b082-edf11f4aba16.png)

I didn't tested on a "vanilla" Forge server yet, but in singleplayer the spawned mob have AI:
![2022-01-18_21 30 06](https://user-images.githubusercontent.com/3485505/150039154-78394824-cbb8-4515-bcd6-ce6b384a28ff.png)

**Comment by vico93** [comment]
Testing further here seems like the issue didn't happen only with Pillar-based structures.
Villagers from vanilla villages also didn't have AI and cant be attacked more than once

**Comment by vico93** [comment]
~~lol fixed just now that i switched to Catserver due to the securities issues Mohist had...~~

Forget that. Fake news from EssentialsX spread to me via Fabric's Discord server (read below)...

**Comment by LeStegii** [comment]
What Security issues are you talking about?

**Comment by Shawiizz** [comment]
> lol fixed just now that i switched to Catserver due to the securities issues Mohist had...

Could you please tell me what securities issues exactly?

**Comment by vico93** [comment]
Well, basically i was chatting in Fabric's Discord server (honestly i'm on that server just because i still believe someone will make a native version of TrainCarts - that is also the reason i use Forge+Spigot hybrids for 1.12 - for Fabric and i will be able finally to update my modpack to 1.18+) about Cardboard and possible solutions similar to Forge+Spigot hybrids but for Fabric, and mentioned i used Mohist in the past and now i'm using CatServer because this issue right here wasnt fixed since Jan.

Then a person on there said "Don't use Mohist" and linked me [this article](https://essentialsx.net/do-not-use-mohist.html) claiming those things. That's all what i know.

**Comment by vico93** [comment]
![image](https://user-images.githubusercontent.com/3485505/166124038-0d4a749c-4e6b-4007-b88e-45748dd04e76.png)
![image](https://user-images.githubusercontent.com/3485505/166124057-a12dccad-2e19-4787-8b17-c209d7d9b480.png)

**Comment by LeStegii** [comment]
Well, it never tricked anyone into installing any plugins. It asked the user if they want to install a version of the plugin which is working with Mohist. All plugins were open source.

Btw, Catserver does the same, but without asking the user first. It just installs plugins by its own...

**Comment by vico93** [comment]
Well, i just read the reply for the EssentialsX's "PSA" written by Shawiizz, and now i just feel bad for bring this topic to here. I  really trusted what those guys on Fabric server told me.

To be honest, i should have left that server after realizing they just bully me on there - like i said before, i asked sometimes in their request channel about a TrainCarts "port" native to Fabric but they just laughed on me. And a couple of days ago i discovered there was a mod that added part of the mechanics of TC natively and no one here told me about when i did the request.

And now after this false PSA i think it's time to ditch that shitty modloader for good and stick with my "beloved" 1.12.2 and my fine-tuned modpack. Sadly, from what i read in Mohist's discord, 1.12.2 builds are going to be deprecated, but i will keep using it.

So, sorry for this rant, sorry for bringing fake news to the issue tracker and thank you so much for make this piece of software.
