### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GDVE** [Teneted/Tenet#20]
This is data from a dump made while the server consumed too much RAM. (The garbage collector began to reduce TPS to 5 - 6)
![image](https://user-images.githubusercontent.com/19783608/67874211-aae59a80-fb45-11e9-838f-3a740567dc5f.png)

**Comment by Mgazul** [comment]
Unable to determine the specific reason

**Comment by GDVE** [comment]
This is Embers mod.
