### ISSUE TITLE
[1.16.5] All mod properties on players lost after death

### ISSUE THREAD

**Issue by MCUmbrella** [Teneted/Tenet#2009]
**Minecraft Version :** 1.16.5

**Mohist Version :** 923

**Operating System :** Linux

**Logs :** Nothing. It's just like normal

**Mod list :** mcwbridges, minecraft, ftbessentials, ftblibrary, bluemap, aoa3, creeperheal, bettercaves, quark, autoreglib, sit, performant, yungsapi, backpacked, upstream, betterstrongholds, randompatches, cfm, architectury, ferritecore, byg, forge, chinjufumod, bettermineshafts, betterendforge

**Plugin list :** https://haste.mohistmc.com/lesunatapi

**Description of issue :** All mod properties on players(e.g. AoA3 skill level, the backpack from Travellers Backpack you are currently equipped) will be lost after death, even though the mod offers the option to keep them.
Issue #1940 #1947 and #1954 is also about this situation.

**Comment by Mike5357** [comment]
#2003 also notes properties being reset on death

**Comment by maxanier** [comment]
The respawn code looks a bit weird:
https://github.com/MohistMC/Mohist/blob/b2f20aa287c7b465a067581b91a4f5d9a57ed7c8/patches/minecraft/net/minecraft/server/management/PlayerList.java.patch#L694-L707
why are things like id copied from the "old" player object to the "new" one, when both objects are identical?

I'm not entirely sure, but it assume mainly this line could be the part of this issue:
https://github.com/MohistMC/Mohist/blob/b2f20aa287c7b465a067581b91a4f5d9a57ed7c8/patches/minecraft/net/minecraft/server/management/PlayerList.java.patch#L710
This probably simply overrides the existing capabilities with new ones.
Usually one could copy the capability data from the old player object afterwards, but that does not exist here, so the data is lost.
Can you just call #reviveCaps here instead?

**Comment by maxanier** [comment]
Probably fixed with https://github.com/MohistMC/Mohist/commit/37cdfa9238456e638491d20194ea01a6794cce42

**Comment by Exiels** [comment]
It also happens when a player change dimension.

**Comment by Mike5357** [comment]
> It also happens when a player change dimension.

On the latest release? (933)

**Comment by Exiels** [comment]
Yes, Mohist-1.16.5-933

**Comment by nyaalex** [comment]
It no longer happens when a player changes dimension, at least not as far as I tested it on 953

**Comment by Mgazul** [comment]
fixed
