### ISSUE TITLE
[1.16.5] Badly Compressed Packet - Issue still present!

### ISSUE THREAD

**Issue by TooCoolCello** [Teneted/Tenet#2010]
**Minecraft Version : 1.16.5

**Mohist Version :**  923

**Operating System :** Windows 10 Pro

**Log :** https://gist.github.com/TooCoolCello/547ac48cc2b0a1a01e3062b51e43d30b

**Mod list :** https://gist.github.com/TooCoolCello/2ec143b04634e3aa023883c867c9537e

**Plugin list :** None

**Description of issue :** I submitted this issue multiple times previously and saw the github updates that was supposed to fix it but none of the fixes work, my server starts fine but upon a player joining they are kicked with the error:
"Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 4058499 is larger than protocol maximum of 2097152"

I have tried using RandomPatches, Connectivity, and XLPackets  individually and together to try and raise or disable the packet limit with no success.

**Comment by Mike5357** [comment]
Your old issue #1998 is still open; no need for a duplicate
