### ISSUE TITLE
About Mohist 1.18.x

### ISSUE THREAD

**Issue by Daman-Yang** [Teneted/Tenet#2011]
I download Mohist 1.18.x through your website, and use "java -jar" to build and run it as I used to.
When I used 1.16.5, I can just run it easily by "java -jar", but when I run this, only a FORGE dialog appears.

Therefore, HOW TO USE MOHIST 1.18.X ?

**Comment by Shawiizz** [comment]
Due to the way forge changed how to run MinecraftForge servers, you have to install the server before. Mohist 1.18 jars on our website are Forge installer, just run it and follow the Forge documentation.
