### ISSUE TITLE
[1.16.5] Vampirism: Loosing faction after death

### ISSUE THREAD

**Issue by lunofe** [Teneted/Tenet#2012]
**Minecraft Version :** 1.16.5

**Mohist Version :** 923

**Operating System :** CentOS

**Concerned mod / plugin** : [Vampirism](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire)

**Logs :** N/A

**Steps to Reproduce :**
 1. Join the server
 2. `/vampirism level vampirism:vampire 14`
 3. Press R or P -> works as intended
 4. `/kill` or die any other way
 5. Press R or P -> nothing happens

**Description of issue :**
After dying, you can't use any of Vampirisms skills. You can't access the menu to unlock skills, manage quests and change your appearance either. As a vampire you don't get damage from standing in the sun, but keep your additional hearts.

**Comment by Mike5357** [comment]
Related to #2009
