### ISSUE TITLE
Vampirism/Werewolves mod progression being lost upon death.

### ISSUE THREAD

**Issue by grimreeaperr** [Teneted/Tenet#2014]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {MD5: e7baf0d7e7b2be97fbc4521887f86958}

**Operating System :** {Windows 10}

**Logs :** {This glitch unfortunately has no console information.}

**Mod list :** {mowziesmobs, ogres, wyrmroost, mining_helmet, bountifulbaubles, additionallanterns, treeharvester, jei, doggytalents, callablehorses, abnormals_core, goblintraders, mcwwindows, kobolds, guideapi-vp, neat, waystones, villagernames, fallingleaves, mcwpaintings, ring_of_repair, journeymap, citadel, alexsmobs, sereneseasons, configured, netheritehorsearmor, decorative_blocks, fantasy, champions, magistuarmory, mutantbeasts, sophisticatedbackpacks, guardvillagers, pedestals, mcwdoors, morpheus, mahoutsukai, iceandfire, carryon, chat_heads, forge, twilightforest, supplementaries, selene, corpse, minecraft, upgrade_aquatic, farmersdelight, voicechat, ambientsounds, toolbelt, silentlib, biomesoplenty, baubles, pamhc2crops, creativecore, mcwtrpdoors, mcwfences, trolls, supermartijn642corelib, cavesandcliffs, jeiintegration, curios, eidolon, atum, spartanshields, pamhc2foodcore, collective, advancednetherite, sit, goblins, twoplayersonehorse, structurize, theabyss, cavebiomeapi, minecolonies, spartanweaponry, mcwroofs, architectury, ftblibrary, ftbranks, vampirism, teamlapenlib, vampirism_integrations, vampiresneedumbrellas, godly-vampirism, werewolves, enhancedcelestials, aquaculture, craftablehorsearmour, smallships, voidtotem, mcwlights, drinkbeer, xpbook}

**Plugin list :** {No plugins added.}

**Description of issue :** {One of our main mods for progression called the vampirism mod and werewolves mod, everytime we die everyone loses their levels, their race and loses all of their progression. It works perfectly fine on a forge server and the server would be perfect if I could add plugins for anti-cheats and other eventful minigames as well. I will link some photos. I've uploaded some photos down below and for reference the purple number is the level I am in the vampirism mod, but once I die I lose my race and all of my progression.}
![Screenshot (384)_LI](https://user-images.githubusercontent.com/78335256/150711815-91a546cc-81dc-439d-9ffd-fd7c78fa7ea8.jpg)
![Screenshot (385)_LI](https://user-images.githubusercontent.com/78335256/150711829-2a425dab-9fb8-43b5-be57-5f9951af6c8d.jpg)

**Comment by grimreeaperr** [comment]
I know there are a lot of mods in this server so there's obviously going to be these types of problems, I completely understand.

**Comment by Mike5357** [comment]
Related to #2009

**Comment by grimreeaperr** [comment]
ahh right.
