### ISSUE TITLE
[1.16.5]/locate 命令 或 制图师村民交易将造成主线程卡顿  The /locate command or Cartographer villager transaction stuns the main thread

### ISSUE THREAD

**Issue by luoxiawuchen** [Teneted/Tenet#2015]
**Minecraft Version :1.16.5 {Minecraft version}

**Mohist Version :923 {Provide Mohist build number}

**Operating System: windows {Provide the name of your OS}

**Logs :** {Link(s) of logs and crash reports if you have}
[latest.log](https://github.com/MohistMC/Mohist/files/7922537/latest.log)
https://paste.ubuntu.com/p/GTz6RxtkZ8/

**Mod list :none 在没有任何模组和插件的环境下测试 {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :none 在没有任何模组和插件的环境下测试 {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}
1、当我去与制图师交易提升交易等级时候，解锁到一定程度就会主线区块相关的主线程卡顿，怀疑是与藏宝图搜索附近遗迹造成的主线程卡顿，如果和制图师村民交易速度过快，就会卡顿到服务器崩溃。
2、当我使用locate搜索遗迹的时候，也有概率出现主线程的卡顿。

1. When I go to trade with cartographers to upgrade the transaction level, if I unlock it to a certain extent, I will get stuck in the main route related to the main line block. It is suspected that it is caused by the search for nearby relics in the treasure map. If I trade with cartographers and villagers too fast, the server will crash.
2. When I use locate to search for relics, there is also a probability that the main thread will get stuck.

**Comment by Mgazul** [comment]
#1463
