### ISSUE TITLE
Strange error happends after player death.

### ISSUE THREAD

**Issue by JosephJoJoDa** [Teneted/Tenet#2017]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {923}

**Operating System :** {Linux}

**Logs :** {No report produced}

**Mod list :**{ mods from **Better Minecraft 1.16.5**:  betterdungeons, immersivefx, immersivecooking, alexsmobs, infernalexp, fd_cookbook, betternether, stalwart_dungeons, strawgolem, farmersdelightintegrations, yungsapi, pyromancer, environmental, bamboo_blocks, guardvillagers, randompatches, copperpot, pickupnotifier, waila, snowrealmagic, dynview, whatareyouvotingfor, jeresources, revampedwolf, supplementaries, betterendforge, upgradednetherite, corpse, structure_gel, tinyskeletons, cleancut, torchmaster, bcc, morevillagers, repurposed_structures, morepaths, fastfurnaceminusreplacement, dungeons_plus, toughnessbar, cavesandcliffs, decorative_blocks_abnormals, darkerdepths, spark, curios, extendedmushrooms, jepb, obfuscate, theabyss, adorn, cloth-config, bettershields, fallingtree, fastbenchminusreplacement, charm, customstartinggear, fastleafdecay, babel, bettermineshafts, geckolib3, bettermodsbutton, veinmining, darkpaintings, kiwi, clienttweaks, mowziesmobs, ftblibrary, configmenusforge, jeiprofessions, jei, visualworkbench, attributefix, catlib, bayou_blues, terraincognita, differentiate, goblintraders, caelus, paxi, upgrade_aquatic, better_badlands, naturescompass, sereneseasons, irregularchef, stoneholm, curioofundying, endergetic, sulfuric, outvoted, catalogue, jeitweaker, crafttweaker, forge, dsurround, neapolitan, dungeons_arise, minecraft, mousetweaks, ftbquests, totw_additions, farmersdelightintegration, cavesandcliffsbackportadditions, personality, paintings, savageandravage, xaerominimap, ftbbackups, autumnity, polymorph, justenoughprofessions, autoreglib, earthmobsmod, nethers_delight, puzzleslib, byg, aquaculture, xpbook, blue_skies, tips, architects_palette, incontrol, osv, kleeslabs, villagernames, xaeroworldmap, controlling, citadel, bookshelf, improvedbackpacks, jeed, carryon, omnis, ftbteams, dragonmounts, twilightforest, cuneiform, jeienchantmentinfo, equipmentcompare, chocolate, farmersdelight, simpleshops, talpm, skinnedlanterns, bountiful, cnb, cataclysm, patchouli, collective, villagertools, elevatorid, betterstrongholds, travelers_index, cavebiomeapi, architectury, curiouselytra, aiimprovements, enchantwithmob, voidtotem, tradingpost, betteradvancements, sndctrl, buzzier_bees, nourished_nether, itemfilters, easymagic, nourished_end, enhanced_mushrooms, abnormals_core, dungeons_mobs, conjurer_illager, extraboats, waystones, goldenhopper, clumps, village_employment, roadrunner, comforts, tumbleweed, campful, storagenetwork, outer_end, decorative_blocks, badmobs, dead_guys_untitled_deep_dark_, lazydfu, wandering_bag, akashictome, ftbchunks, frozenup, skinlayers3d, travelerstitles, selene, environs, enchdesc, amfd, jade, towers_of_the_wild, atmospheric, mobeffects, iceberg, quark, kryptonreforged, abnormals_delight, inventoryhud, illagersweararmor, combustivefishing, blocksplus, hunterillager, ferritecore, enhancedcelestials, overloadedarmorbar, [nature_expansion]}]

**Plugin list :** {}

**Description of issue :** {After a player death and clicking the respawn button, the console would keep producing "preparing crash report with uuid: xxxx-xxxx" and never terminate. So, no report was given. ;((  (the player could still move or build)
![image](https://user-images.githubusercontent.com/73632710/150840675-6e8729b1-e734-4cc2-bc90-c8e47c33ac97.png)
  }

**Comment by IridiumH** [comment]
I got the same issue as yours when using build 924 or build 904. When this happens, player data can not be saved. I revert the server to build 855 and this problem just disappear.

**Comment by TNTUP** [comment]
Can confirm this issue. As soon the player dies, it stops saving the playerdata (leading to dupe items or loss) and can lead to server crashes(due to ResourcefulBees on ATM6 modpack).

Downgrading to Mohist 1.16.5-929 fixes the issue
