### ISSUE TITLE
EasyBackup wont load on Mohist but loaded fine on Spigot

### ISSUE THREAD

**Issue by Shurelia** [Teneted/Tenet#202]
Hi,
recently i've been thinking about adding a nice backup system on my mohist server like my old spigot server has, but when i tried to load them on mohist, this error occurs:

Error log: https://gist.github.com/Ex-Infinityy/ffa465215412b459bea28cec947e8800

later i tried that plugin on my test-serv spigot 1.12.2 build and it was working perfectly.
any ideas? also sorry for my bad grammar, thankyouu^^

Mohist ver: b438 [6a04bfe](https://github.com/Mohist-Community/Mohist/commit/6a04bfeb6d2e23e3c66a34572511ced7bfc8b950) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847) (Latest atm) 
EasyBackup plugin ver: Latest 3.3.2
https://www.spigotmc.org/resources/%E2%AD%90-easybackup-%E2%AD%90-easy-and-powerful-backup-service-protecting-servers-since-2015.8017/

**Comment by Arcami** [comment]
Having the exact problem
