### ISSUE TITLE
[1.16.5] Plugin Wandering Trades doesn't work

### ISSUE THREAD

**Issue by galoti** [Teneted/Tenet#2026]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-924

**Operating System :** Windows 10

**Concerned mod / plugin** : Wandering Trades / https://www.spigotmc.org/resources/wandering-trades-easily-customize-wandering-traders-1-16-1-18.79068/

**Logs :** https://pastebin.com/YUFPCk0t

**Steps to Reproduce :**
 1. Copy plugin to 'plugins' folder
 2. Run server

**Description of issue :** Plugin doesn't work with mohist

**Comment by Mgazul** [comment]
The java version used by the plugin is too high, and forge cannot be compatible with java17
