### ISSUE TITLE
[1.12.2] ProtocolLib Error

### ISSUE THREAD

**Issue by MCrashCraft** [Teneted/Tenet#2030]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist 1.12.2 249

**Operating System :** Idk, Im using Bisect Hosting

**Concerned mod / plugin** : ProtocolLib

**Logs :** [Link(s) of logs and crash reports if you have](https://haste.mohistmc.com/lejesehena.sql)

**Steps to Reproduce :**
 1. Start server
 2. let it run

**Description of issue :** Keeps popping up with errors

**Comment by MCrashCraft** [comment]
Update: I updated to Mohist 1.12.2 304 and still having these errors.

**Comment by Mgazul** [comment]
1.12.2 must use ProtocolLib 4.5.0
