### ISSUE TITLE
1.16.5 Mana & Artifice data still getting erased 

### ISSUE THREAD

**Issue by SpoilersMC** [Teneted/Tenet#2032]
**Minecraft Version :** 1.16.5

**Mohist Version :** 935

**Operating System :** win10

**Concerned mod / plugin** : Mana & Artifice

**Steps to Reproduce :**
Dying

**Description of issue :** although the recent build fixed player deaths erasing attached capabilities, mana & artifice's 'rote data' tracker capability is still erased on death

**Comment by Mgazul** [comment]
#2009
