### ISSUE TITLE
[1.16.5] Wordguard not preventing punch from pvp

### ISSUE THREAD

**Issue by Reforged-Network** [Teneted/Tenet#2033]
**Minecraft Version :** 1.16.5

**Mohist Version :** 936

**Operating System :** Provide the name of your OS

**Concerned mod / plugin** : Worldguard https://dev.bukkit.org/projects/worldguard/files (build 7.0.5)

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Create a new worldguard region
 2. /rg flag REGION pvp deny
 3. punch another player
 4. player still gets hit and takes knockback

**Description of issue :** Players still taking knockback while pvp & invincible flags are disabled in a specific region which can lead to more issues by being able to punch players out of safezones and into pvpzones since knockback is still applied (region priority is also set). 

Edit:
Players are still able to be hit when using /god (essentials) so it doesn't seem to be a plugin issue

**Comment by TheMatiaz0** [comment]
I have the same issue with Oracle Linux Server 8.5 OS. I use Mohist version 961 and the same version of plugin. For me the region flag pvp is completely not working, causing players to get hurt on every hit. I tried the RedProtect plugin but it didn't work as well. Does anyone have any alternatives or potential causes beside Mohist's plugin compatibility?

**Comment by joaoespanhol** [comment]
same problem
https://github.com/MohistMC/Mohist/issues/2147
