### ISSUE TITLE
Mohist Offline-mod

### ISSUE THREAD

**Issue by Heriptik** [Teneted/Tenet#204]
Hello, i would like use a permission plugins (like LuckPerms) but it's don't work on mohist because my serveur is in offline-mod. (https://image.noelshack.com/fichiers/2020/15/3/1586301613-offline.png)

Can you add this at mohist (https://hub.spigotmc.org/jira/browse/SPIGOT-3541)

thank you (my server is in 1.12.2)

**Comment by Mgazul** [comment]
He already exists, no need to add it again
