### ISSUE TITLE
[1.16.5] ProdigyNightclub's Blaze Rod Without Effect

### ISSUE THREAD

**Issue by quickgk** [Teneted/Tenet#2040]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-936

**Operating System :** Windows 11(22000.469)

**Concerned mod / plugin** : ProdigyNightClub https://www.spigotmc.org/resources/prodigynightclub.58234/

**Logs :** No log report

**Steps to Reproduce :**
 1. Copy plugin to plugins folder (Requires ProtocolLib as a dependency)
 2. Run server
 3. Enter the game
 4. Enter /pnc setup create name
 5. Left or Right Click Block

**Description of issue :** Left or right click has without effect

**Comment by Mgazul** [comment]
Compatibility with ProtocolLib is not perfect
