### ISSUE TITLE
[1.12.2] Mohist cant passed material name from mod?

### ISSUE THREAD

**Issue by Krosta8** [Teneted/Tenet#205]
Hello,
I want to use plugin called `RedProtect`, which has official support for Mohist.
In this plugin is option to disable specific item/block usage in specific worlds.
The problem is with modded items. 
Example: I tried to disable usage of Chunk Loader from IndustrialCraft in specific world. The debug info from the RedProtect plugin say `IC2_TE`, but this is going to disable all blocks from IndustrialCraft which are `ic2:te:XX`.
Author of RedProtect wrote, that the problem is maybe on your side. 
`"Well, redprotect can know the item material name if its not passed from modded to Mohist... In this case, its not possible"`

Using Mohist build 439 9f12580

Issue on RedProtect: https://github.com/FabioZumbi12/RedProtect/issues/608

**Comment by FabioZumbi12** [comment]
Additionally, if you join the mohist Discord channel, theres a suggestion about this:

![image](https://user-images.githubusercontent.com/5833818/78730012-0183ab80-7912-11ea-8328-43e08dca697c.png)

And the votes are positive :)

**Comment by Krosta8** [comment]
Nice, thanks and I hope, this is going to be done quickly :D

**Comment by Mgazul** [comment]
Does it support digital ID, such as 4096: 82

**Comment by Shawiizz** [comment]
it would be nice if we could add a modded block in the LockettePro configuration for example to make the modded block lockable, or can make kits with modded items on Essentials, or be able to use modded things with Skript etc without editing plugin's source code... and a lot of things on others plugins.

**Comment by FabioZumbi12** [comment]
The problem is that we (devs) were discouraged from using ids anymore, so many plugins no longer support ids (and neither does mine)

**Comment by Mgazul** [comment]
Ignore the implementation of this function, just like wool, you must use 35:subid
