### ISSUE TITLE
玩家进入服务器后服务端崩溃：NoSuchMethodError

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#206]
#### Mohist 版本 - Mod version:

1.12.2-fb20a25

#### Forge版本 - Forge version:

14.23.5.2847

#### 完整的 MOD 列表 - Installed mods:
第一次崩溃时的 MOD 列表，崩溃报告中附带。
第二次崩溃时 MOD 除了删除了 FoamFix 以外和第一次相同，在第二次的报告中附带。

#### 完整的插件列表 - Installed plugins:
两次崩溃均没有任何插件。

## 崩溃报告的链接 - Link to full crash log
第一次崩溃的崩溃报告：https://paste.ubuntu.com/p/YS2585xhc3/
第二次崩溃的崩溃报告：https://paste.ubuntu.com/p/Vd8DgTZPK9/

#### 产生Bug的步骤 - How to reproduce:

1. 玩家登入服务器。
2. 出现“生成地形中”，然后出现“Internal Error”，同时服务端崩溃。

在此感谢您拨冗阅读我的反馈，
事先感谢您的帮助。

**Comment by Mgazul** [comment]
Related to deltahard, he used a method marked @SideOnly (Side.CLIENT) on the server
