### ISSUE TITLE
a couple of problems.

### ISSUE THREAD

**Issue by ariesclark** [Teneted/Tenet#210]
every single start when the server is joinable;
https://pastebin.com/AVUSkNBA

I assume these two are related?
https://pastebin.com/YwbLEMA2
https://pastebin.com/8NT1ECeQ

the last two are pretty big problems, once it occurs nothing on the server saves and players can't join.

**Comment by ariesclark** [comment]
might I add that none of these errors occur in a normal forge instance.

**Comment by Mgazul** [comment]
Uninstall randompatches mod, some functions and mohist duplicate

**Comment by Mgazul** [comment]
The second question comes from the immersivepetroleum mod

**Comment by ariesclark** [comment]
yeah, but the problem occurs in mohist only.
