### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by toya-xo** [Teneted/Tenet#2107]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {961}

**Operating System :** {Ubuntu}

**Logs :** {[Link(s) of logs and crash reports if you have](https://pastebin.com/Zv6jvwNF)}

**Mod list :** {https://pbs.twimg.com/media/FNWPJRrWYAYP5tf?format=png&name=900x900 }

**Plugin list :** {EssentialsX ; LuckPerms-Bukkit ; SimpleTpa ; SkinsRestorer}

**Description of issue :** {First, I was playing on the server and i see a chunk error (not loading) after the server crashed and the server continues to crashes after.}

**Comment by lunofe** [comment]
The crash log you've provided very obviously states:
>  Failed loading config file mowziesmobs-common.toml of type COMMON for modid mowziesmobs

Check if the server starts if you remove that file.
