### ISSUE TITLE
Mohist bugs in protection plugins and others

### ISSUE THREAD

**Issue by brasilcraft54** [Teneted/Tenet#2111]
I have used all the protection plugins people can attack mobs and use a shovel to make terra cotta on protected land.

Protection plugins: GriefDefender, Griefprevetion, RedProtect, Land.

mohist version: mohist-1.16.5-961-universal.jar

java: 17

**Comment by brasilcraft54** [comment]
I used a plugin to detect what was happening and it showed this: https://prnt.sc/GgFoSng9Q_lC

the player attacks the cow but it does not die is there any way to block it from attacking me it seems that mohist is not compatible with griefprevention

in the console shows this:  https://prnt.sc/PoCeAURd5Fmu

my all plugins: https://prnt.sc/AvQKLo21C2zh

**Comment by Shawiizz** [comment]
The issue do not match with any issue template. Please recreate an issue using a template.

**Comment by brasilcraft54** [comment]
The bug happens with all protection plugins. I have tested about 5 and all 5 have the same problem. 
 https://youtu.be/AYaVzU9NaTo

**Comment by Jorue23** [comment]
He meant that you should open a new issue and use the given template this time in order for the mohist team to get all the informations they need.

**Comment by GnomoMuitoLoco** [comment]
Não resolveu, estou com problemas similares, não consigo proteger itens de mods, por exemplo o AE2, estou usando GriefPrevention para salvar terrenos de jogadores e conseguem abrir e pegar as coisas mesmo com proteção.
