### ISSUE TITLE
Permissions are still broken, even without any mods.

### ISSUE THREAD

**Issue by MistressPlague** [Teneted/Tenet#216]
Upon server start on latest build on codemc, the server logs that the permission group in permissions.yml is already defined no matter what, furthermore this occurs with no additional files in the server other than forge itself. Vanilla permissions work without mohist, but with mohist I can't even run /help.

I'm still to find a fix for this.

I even removed plugins to test. 

I have tried permission management plugins such as UltraPermissions, all change nothing towards this issue. This issue is with Mohist itself.

Please fix this instead of blowing it off as user error, as a coder I can assure it is not on my end.

To Reproduce: Literally just run Mohist-82d9a17-server and have a user join and try running /help.

**Comment by Mgazul** [comment]
https://github.com/Mohist-Community/Mohist/blob/1.12.2/wiki/PERMISSION.md

**Comment by MistressPlague** [comment]
That doesn't really explain /help not even working.

**Comment by ariesclark** [comment]
You just need to give them permissions to use it. Mohist registers commands with a Bukkit permission node so that plugins like GroupManager or PermissionEX can control usage.

**Comment by Mgazul** [comment]
Now the default command of bukkit can be used by ordinary players. I judged the isop before, I have deleted it
