### ISSUE TITLE
I can't seem to download the 1.16.5 version of Mohist

### ISSUE THREAD

**Issue by 936338156** [Teneted/Tenet#2168]
I can't seem to download the 1.16.5 version of Mohist

https://user-images.githubusercontent.com/100773763/165474232-bcfe66ff-0fc0-4858-a59d-f37659ad55a1.mp4

**Comment by Shawiizz** [comment]
Your video seems to not working with me, but if you want to download Mohist, please go to https://mohistmc.com/download
