### ISSUE TITLE
Add an option to enable rail machine

### ISSUE THREAD

**Issue by heipiao233** [Teneted/Tenet#2198]
**Is your feature request related to a problem? Please describe.**
I want to use it.

**Describe the solution you'd like**
Add an option to disable Paper's "bug fix"

**Comment by Romaindu35** [comment]
I don't understand your request

**Comment by joaoespanhol** [comment]
basically it wants to disable all conditions presented as plugin I used paper.
Basically it just wants bukkit and spigot support
