### ISSUE TITLE
[Mohist1.16.5]Maybe update automatically downloaded jdk version to 11.0.15?

### ISSUE THREAD

**Issue by Cran-May** [Teneted/Tenet#2199]
**Mohist 1.16.5自动下载的AdoptOpenJDK版本有点旧了，也许可以换成更新的Adoptium/ojdkbuild 11.0.15？**
Adoptium:[For Windows x64](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.15_10.zip) [For Linux x64](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jre_x64_linux_hotspot_11.0.15_10.tar.gz)
ojdkbuild:[For Windows x64](https://github.com/ojdkbuild/ojdkbuild/releases/download/java-11-openjdk-11.0.15.9-1/java-11-openjdk-jre-11.0.15.9-1.windows.ojdkbuild.x86_64.zip) 
经过测试，他们都能很好的工作

The version of adoptopenjdk automatically downloaded by Mohist(1.16.5) itself is a bit old. Maybe replace it with the updated adoptium / ojdkbuild 11.0.15?
Adoptium:[For Windows x64](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jre_x64_windows_hotspot_11.0.15_10.zip) [For Linux x64](https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jre_x64_linux_hotspot_11.0.15_10.tar.gz)
ojdkbuild:[For Windows x64](https://github.com/ojdkbuild/ojdkbuild/releases/download/java-11-openjdk-11.0.15.9-1/java-11-openjdk-jre-11.0.15.9-1.windows.ojdkbuild.x86_64.zip) 
Tested, they all work well

**Comment by Shawiizz** [comment]
Thank you for having reporting this, I'll update it when I'm able to do it.

**Comment by joaoespanhol** [comment]
may also be support for java 17, with forge support.

**Comment by Shawiizz** [comment]
> may also be support for java 17, with forge support.
> 

Mohist 1.16.5 already works fine with java 17. It's still not recommended to use as Forge itself isn't designed to run with it.

**Comment by joaoespanhol** [comment]
artfully it was not possible to run java17, new forge updates that started to be supported.

**Comment by Shawiizz** [comment]
I have updated the JREs to their latest versions. Unfortunately i'm not able to do something that automatically downloads and update from the adoptium JDK site because of the format of compressed files (tar.gz) that would need an additional library to uncompress them. 
In the future i'll think about a better solution for this. So I updated them manually on the maven, the only thing you have to do is deleting the CustomJAVA folder and let Mohist re-download it again.
