### ISSUE TITLE
Error starting my plugin

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#221]
This is my plugin that connects discord and minecraft.
My github plugin: https://github.com/LoopRich161/DiscordBotLogger
I use the latest core version (Mohist-b5d8615-server.jar)
There are no mods on the server
Plugins only: Vault, EssentialsX, PermissionEX
My error: https://hastebin.com/hefikanufu.rb
P.S.
It works on all other cores, only it does not work on moss. I tried on: CatServer, Vanila, Magma, Thermos (1.7.10, yes, my plugin suppot this version)

**Comment by ariesclark** [comment]
That's totally a you problem, are you sure the plugin works in a non-Mohist environment?

**Comment by LoopRich161** [comment]
Yes, sure

> That's totally a you problem, are you sure the plugin works in a non-Mohist environment?

**Comment by LoopRich161** [comment]
Problem resolved
