### ISSUE TITLE
[1.18.2] Monsters don't spawn on the server

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#2293]
**Minecraft Version :** 1.18.2

**Mohist Version :** 88

**Operating System :** Windows 10 Pro x64

**Mod list :** SecurityCraft, MrCrayfish's Furniture Mod, MrCrayfish's Gun Mod, Additional Guns, Framework

**Plugin list :** SkinsRestorer, PlaceholdersAPI, PlugMan, Vault, MyCommand

**Description of issue :** I noticed that apart from phantoms on my server, no monsters spawn. I didn't change bukkit.yml and spigot.yml settings (optimizing these files did not help). The difficulty of the game is hard (monsters also do not spawn on other difficulties). Gamerule doMobSpawning is set to true. spawn-monsters, spawn-animals, spawn-npcs set to true. Creating a new world did not help.

**Comment by EpleBRO** [comment]
i am also have this problem, r u fix it?

**Comment by ProsperCraft** [comment]
From what I understand, the two versions being deved is 1.16.5 and 1.19, skipping 1.18.2.
