### ISSUE TITLE
Forge's ServerChatEvent not cancelling the Bukkit AsyncChatEvent or vice versa (results in collision)

### ISSUE THREAD

**Issue by Hi-Im-Ina** [Teneted/Tenet#233]
The server chat event is currently not able to be listened to (not showing up as canceled even just doesnt fire)

**Comment by CelestialKitsune** [comment]
I've been struggling to get the chat working with the latest (when I tried) build (Mohist-23b0325-server.jar), and the issue was caused by FTBUtilities. It can be fixed by modifying its config about ranks (from lines 98 to 107).

**Comment by Hi-Im-Ina** [comment]
> 
> 
> I've been struggling to get the chat working with the latest (when I tried) build (Mohist-23b0325-server.jar), and the issue was caused by FTBUtilities. It can be fixed by modifying its config about ranks (from lines 98 to 107).

Thanks for the reply but my issue doesn't come from any particular mod, any mod that uses the ServerChatEvent won't do anything.
To test simply create any and listen for canceled events and you will see theres no ServerChatEvent on there nor will you do anything by making even a simple sout to check.

**Comment by CelestialKitsune** [comment]
I did create a server without any mod, and chat worked well. Though this needs investigation as older versions also had such an issue

**Comment by Hi-Im-Ina** [comment]
> 
> 
> I did create a server without any mod, and chat worked well. Though this needs investigation as older versions also had such an issue

I think were referring to different things... Chat itself works fine to clarify for further bumps im reffering to an event from [Forge](https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.9.4-12.17.0.2051/net/minecraftforge/event/ServerChatEvent.html)

**Comment by Hi-Im-Ina** [comment]
**Bump for the latest version**
The event now works and can be listened to however you need to manually cancel the Bukkit/Spigot equivalent making mods require a plugin or a plugin require a mod, if it were possible to merge the cancel with both that would be great!
Updated title to match current situation.

**Comment by Shawiizz** [comment]
Hello @Licious17, is this fixed in the latest build (can you test) ?

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug persist, please open new issue.
