### ISSUE TITLE
Correct Respawning Support.

### ISSUE THREAD

**Issue by agapelogos4** [Teneted/Tenet#2334]
**Could you add support with the Lord of the rings mod.**
I'm having a problem with respawning I have a "Lord of the rings" mod I would like the players to respawn in the lord of the rings dimension but the player keeps respawning in the over-world, and when I boot up my server I get this error at the start https://pastebin.com/3xvAG8Mr somethings stopping the mod from respawning players in the dimension.

**Describe the solution you'd like**
Could you change the respawning bug and allow players the ability to respawn in the Lord of the rings dimension the mod has the future built into it its just being block by mohist. please fix it for minecraft version 1.16.5

**Additional context**
The modpack wiki on its respawning feature. https://lotrminecraftmod.fandom.com/wiki/Player_Respawning#:~:text=If%20your%20player%20dies%20within,bed%20or%20the%20Ring%20Portal.

mod: https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed

**Comment by agapelogos4** [comment]
why was this closed? ive been stuck on this bug for about a year and support for this would be nice.

**Comment by Mgazul** [comment]
because it has been fixed

**Comment by agapelogos4** [comment]
Really in a resent update! That's awesome thanks so much. What did they do to fix it.
