### ISSUE TITLE
1.19.2 World#getEnvironment() always returns null (Spigot)

### ISSUE THREAD

**Issue by Grayseon** [Teneted/Tenet#2380]
**Minecraft Version :** 1.19.2

**Mohist Version :** 72

**Operating System :** MacOS

**Concerned mod / plugin** : Homes, a plugin made by me

**Steps to Reproduce :**
 1. Make a 1.19.2 Spigot plugin
 2. Log the output of world.getEnvironment()
 3. Check the output, and it will be null.

**Description of issue :** When calling world.getEnvironment() it will always return null. Does work on a Spigot only server.

**Comment by Mgazul** [comment]
#997
