### ISSUE TITLE
[1.16.5] Brush problem with WorldEdit

### ISSUE THREAD

**Issue by themoney158** [Teneted/Tenet#2382]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-1087

**Operating System :** Windows 10

**Concerned mod / plugin** : WorldEdit https://www.curseforge.com/minecraft/bukkit-plugins/worldedit/files

**Logs :** 

**Steps to Reproduce :**
 1. Use command /brush sphere snow_block 5 with a tool in your hand (not the wooden axe of course)
 2. Click wherever you want this sphere to go.

**Description of issue :** When I want to use a sphere brush, instead of placing the sphere where I target, it appears where I stand, so I end up stuck in my sphere. This happends wherever I am and all the time.

**Comment by Mgazul** [comment]
#997
