### ISSUE TITLE
[1.16.5] JumpPad error in console

### ISSUE THREAD

**Issue by firmeon** [Teneted/Tenet#2383]
**Minecraft Version :** 1.16.5

**Mohist Version :**  1.16.5-1075

**Operating System :** Debian

**Concerned mod / plugin** : JumpPad (https://www.spigotmc.org/resources/custom-jumppads-1-8-1-19.44876/)

**Logs :** https://gist.github.com/firmeon/200164c8cd4fc98766a598571ad0095c

**Steps to Reproduce :**
 1. Install JumpPad
 2. Create a plate that make you jump with the plugin
 3. Walk on the plate, you will go launch in the air but in the console there is a warn

**Description of issue :** This issue is only visible on the console, the player don't see anything

**Comment by Mgazul** [comment]
you set the wrong sound
