### ISSUE TITLE
[1.19.2] Ticking entity crash minecraft:drowned

### ISSUE THREAD

**Issue by nikindreus** [Teneted/Tenet#2385]
**Minecraft Version :** 1.19.2

**Mohist Version :** 1.19.2-75

**Operating System :** Linux

**Logs :** [Link of logs](https://pastebin.com/HfQk6BKr)

**Steps to Reproduce :**
 1. Create world
 2. Spawn minecraft:drowned
 3. Go to survival difficulty
 4. Make a mob attack you

**Description of issue :** difficulty peaceful fix this problem

**Comment by Mgazul** [comment]
1.19.3 fixed this
