### ISSUE TITLE
[1.19.2] 无法下载库文件

### ISSUE THREAD

**Issue by duanygithub** [Teneted/Tenet#2386]
**Minecraft Version :** 1.19.2

**Mohist Version :** 1.19.2-74

**Operating System :** CentOS 7

**Logs :**

**Mod list :** 

**Plugin list :** 

**Description of issue :** 下载server-1.19.2-20220805.130853-mappings.txt时出错，显示"Downloading file server-1.19.2-20220805.130853-mappings.txt with size 5.3946934MB The download of http://s1.devicloud.cn:25119/libraries/net/minecraft/server/1.19.2-20220805.130853/server-1.19.2-20220805.130853-mappings.txt failed because the MD5 of this file is c240b761705866f116aede9731d0b613 while it should be 138867aa3c4f09eb341d6802b44213fe. The file got deleted for security reasons."

**Comment by Mgazul** [comment]
fixed
