### ISSUE TITLE
[1.19.2] server crashes every time a mob stops targeting or changes target

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#2393]
**Minecraft Version :** 1.19.2

**Mohist Version :** 78

**Operating System :** Don't know, I use Shockbyte

**Logs :** https://paste.shockbyte.com/nolawuqaxukadoremuvu

**Mod list :** Alarms, Immersive Engineering, Create, Flywheel, Lucky TNT Mob, Lucky TNT Lib

**Plugin list :** None

**Description of issue :** Whenever I die, go into creative, walk away from a mob, or it locks on to another player the server crashes.

**Comment by Mgazul** [comment]
1.19.3 fix this
