### ISSUE TITLE
[1.19.2] server crash with Exception in thread "main" java.lang.module.ResolutionException

### ISSUE THREAD

**Issue by pouyarisk** [Teneted/Tenet#2395]
Hi
i get this error when i want to start my server for no reason
the log is [here](https://mclo.gs/6Mu4qS7)

**Comment by Mgazul** [comment]
Mod ID: 'placebo', Requested by: 'fastfurnace', Expected range: '[7.0.0,)', Actual version: '[MISSING]'

**Comment by pouyarisk** [comment]
Sorry, I might got you wrong
that was a problem a had in the first start and the log i sent you is all of the startups 😅
but [this](https://haste.mohistmc.com/ujifebevid.coffeescript) is the actual bug i have @Mgazul

**Comment by pouyarisk** [comment]
and the mod that got mentioned at the last of the error Changes every time
