### ISSUE TITLE
question

### ISSUE THREAD

**Issue by WarriorGamingserv** [Teneted/Tenet#24]
Will this work with a bungee server

**Comment by Mgazul** [comment]
Yes

**Comment by WarriorGamingserv** [comment]
I set it up just like a regular spigot bungee connection and it did not work, am I missing something?

**Comment by Mgazul** [comment]
Give me your setting config

**Comment by WarriorGamingserv** [comment]
the server.properties and the spigot.yml?

**Comment by Mgazul** [comment]
yes

**Comment by WarriorGamingserv** [comment]
[TCModded.zip](https://github.com/Mohist-Community/Mohist/files/3805761/TCModded.zip)

**Comment by WarriorGamingserv** [comment]
it reads that i'm trying to connect to it, but doesn't fully send it through so it'll wait a bit then say i timed out

**Comment by Mgazul** [comment]
give me bungeecord/config.yml  thx

**Comment by Zilacon** [comment]
@WarriorGamingserv Make sure forge support is enabled in the bungeecord config. Bungeecord also has to be set to true in spigot.yml for the server.

**Comment by WarriorGamingserv** [comment]
i have both bungeecord and forge support set to true

**Comment by WarriorGamingserv** [comment]
the bungeecord config is ran by a verteran server maker, and i've also ran multiple servers in the past, everything is setup as it should, trying to connect from a none modded to modded isn't working, or it just isn't working at all

**Comment by Zilacon** [comment]
I just updated to the most recent version of mohist and i connected to the server from my bungee with no issues.

![Screenshot_31](https://user-images.githubusercontent.com/3002248/68243003-7307a880-ffc6-11e9-82d1-c9188c166df6.png)
![Screenshot_32](https://user-images.githubusercontent.com/3002248/68243040-861a7880-ffc6-11e9-9ad2-f3143d400086.png)
