### ISSUE TITLE
java.lang.nosuchmethoderror: okio.bytestring.startswith(lokio/bytestring;)z

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#240]
Core: Mohist-856104e-server.jar
My error: https://prnt.sc/s2decs
I create discord bot, line 107: jda = JDABuilder.createDefault(tokenBot).build().awaitReady();

Everything works well if there are plugins on the server: CoreProtect v2.14.4, LuckPerms v5.0.72, Vault v1.7.1-b91, PlaceholderAPI v2.10.4, AConomy v2.3, DiscordBotLogger v3.7, Enabling Vault v1.7.1-b91, Enabling AConomy v2.3
And not a single mod.

I have completely different plugins on my main server and it doesn’t work there: DiscordBotLogger v3.7, CoreProtect v2.14.4, WorldEdit v6.1.9, Playtime v1.4.5, PlaceholderAPI v2.10.4, ClearLag v3.1.6, AutoMessage v1.0, NBTKits v1.0, WorldBorder v1.8.7, ProtocolLib v4.4.0, WorldGuard v6.2.2-SNAPSHOT;, MultiWorld v5.2.8, MaxBans v2.7, AdvancedRandomTeleport v1.01, VoxelSniper v5.172.0-SNAPSHOT, PermissionsEx v1.23.4, BanItem v3.0, Restarter v1.1, AverageOnline v0.3, WGExtender v1.0, Vault v1.7.1-b91, LiteCore3 v3.1, MyCommand v5.6.0, FixFishingRodHitPlayer v1.0, MyWarp v3.1+Travis-b1815.git-77239c4f28, Essentials v2.17.1.0, Logger v0.4, XConomy v1.88, Logs v0.3, EssentialsChat v2.17.1.0, TAB v2.6.4, EssentialsSpawn v2.17.1.0
And mods: creativecoredummy, gameshark, moveskillcontroller, pixelextras, pixelmon, tcg, wondertrade, legendaryplus, coralreef, igcm, mtlib, creativecore, opframe, essentialfeatures, mantle, openfm, architecturecraft, bspkrscore, treecapitator, customnpcs, chisel, cfm, bonsaitrees, chameleon, storagedrawers, ironchest, elevatorid, enderbags, placebo, emoticons, mclib

**Comment by Shawiizz** [comment]
Hi, is this bug is here on the latest Mohist version ? I tested making a bot with JDA on a plugin and i don't have any problems. I didn't tested with all your plugins, i'm testing.
