### ISSUE TITLE
Crash with lycanites mobs

### ISSUE THREAD

**Issue by CronaG** [Teneted/Tenet#2406]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {1.16.5-1095}

**Operating System :** {Linux (amd64) version 4.9.0-15-amd64}

**Logs :** {https://haste.mohistmc.com/ecatuxewew.rb}

**Mod list :** {mowziesmobs, pmmobridge, ftbessentials, cucumber, aiotbotania, alexsmobs, ftblibrary, mca, mekanismdefense, spiderstpo, eidolon, itemfilters, jei, extendedcrafting, attributefix, the_abyssal_void, goblintraders, mekanism, invtweaks, waystones, dragon_egg, ring_of_repair, ctm, christmasfestivity, structurescompass, citadel, appliedenergistics2, naturescompass, configured, dungeoncrawl, mutantbeasts, lootbeams, randompatches, secretroomsmod, morpheus, iceandfire, mekanismgenerators, waila, jeitweaker, jeresources, crafttweaker, ars_nouveau, mysticalworld, uncrafter, paraglider, ftbteams, ftbchunks, forge, mysticalagradditions, dcintegration, twilightforest, betterendforge, mysticalagriculture, duneons, minecraft, sons_of_sins, ancient_debris_in_overworld, theoneprobe, mousetweaks, psi, mekanismadditions, jade, ironfurnaces, creativecore, mining_dimension, towers_of_the_wild, botania, jeiintegration, curios, patchouli, mantle, collective, bhc, storagedrawers, parcool, endreborn, elevatorid, gobber2, ftbultimine, enigmaticlegacy, customnpcs, worldedit, starterkit, mekanismtools, pmmo, architectury, byg, dicemcpmmonbt, cosmeticarmorreworked, geckolib3, cyclic, lycanites mobs}

**Plugin list :** {LuckPerms, FastChunkPregenerator, OpenInv, ServerLog, Votifier, LaggRemover, ProtocolLib, CMWTokens, SkinsRestorer, DisplayFormatter, PluginsFurnace, TrollBoss, Vault, WorldEdit, PlayerKits, DecentHolograms, Essentials, GCore, WorldGuard, GUIShop, TabList, TradeSystem, SuperbVote, PlayerVaults, JSONAPI-RELOADED-UNIVERSAL, EssentialsSpawn, CustomCommands, LootCrate, AuthMe, Winter, PlugManX (PlugMan)}

**Description of issue :** {lycanites mobs crash my server randomly}

**Comment by Mgazul** [comment]
fixed
