### ISSUE TITLE
Where can I download version 1.18.2?

### ISSUE THREAD

**Issue by WCarey99** [Teneted/Tenet#2415]
**What is your question ?**
{Answer here}

**Comment by Shawiizz** [comment]
Hello, Mohist 1.18.2 is discontinued and cannot be downloaded. It's recommended to use Magma or Arclight instead.

**Comment by Ayx03** [comment]
I just checked <https://mohistmc.com/download> there are newer releases
~~These are the releases that are working.
[#4](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-4-server.jar), [#5](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-5-server.jar), [#6](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-6-server.jar), [#8](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-8-server.jar)~~
