### ISSUE TITLE
请求添加1.18.2

### ISSUE THREAD

**Issue by poisongod** [Teneted/Tenet#2419]

**Comment by lonelysam3** [comment]
#2415

**Comment by Ayx03** [comment]
在 <https://mohistmc.com/download> 就能找到新的 release。
~~这些是能正常启动的 1.18.2 核心。
[#4](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-4-server.jar), [#5](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-5-server.jar), [#6](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-6-server.jar), [#8](https://mohistmc.com/builds/1.18.2/mohist-1.18.2-8-server.jar)~~
