### ISSUE TITLE
Damage bug

### ISSUE THREAD

**Issue by toniocraft** [Teneted/Tenet#2435]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1102

**Operating System :** WIN 10 X64

**Logs :** No crash

**Mod list :** Nothing to do with mods because even without them there is this bug

**Plugin list :** Nothing to do with plugins because even without them there is this bug

**Description of issue :**
Hi, I posted a video of my problem on youtube, this came as soon as I upgraded to build 1102
https://youtu.be/LR5gxewnubM

**Comment by Mgazul** [comment]
Fixed

**Comment by toniocraft** [comment]
thanks 👍
