### ISSUE TITLE
Mohist server error

### ISSUE THREAD

**Issue by radiatorextremz** [Teneted/Tenet#2462]
**Minecraft Version :** {1.18.2}

**Mohist Version :** {#10}

**Operating System :** {RevisionOS}

**Logs :** {[https://mclo.gs/kJM9tmu]}

**Mod list :** {dawncraft modpack, cant iniciate the server}

**Plugin list :** {none}

**Description of issue :** {I created a normal mohist 1.18.2 server, with the dawncraft modpack, and then when I started the server it just crashed like this}

![image](https://user-images.githubusercontent.com/88463358/230728359-939fbd39-6a68-42a3-9389-5639f2120bea.png)

**Comment by Ayx03** [comment]
Build #9 and #10 have a major issue (#2457), you won't be able to join the server even if it didn't crash. I recommend you try with #8 again.
