### ISSUE TITLE
[1.16.5 | bug] 在Linux终端(Screen)使用stop关服后输入系统命令时无回显

### ISSUE THREAD

**Issue by big-tooth** [Teneted/Tenet#2464]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1109

**Operating System :** armbian 20.04 (rk3399 4GB+32GB)

**Description of issue :** 当我使用stop命令以后，跑完结束代码以后，之后的所有命令都消失了，只能盲打或关闭session对话才可以

**Comment by big-tooth** [comment]
我是在新建了一个screen之后，会发生以上现象，目前在screen外浅试了一下还没遇到这样的情况

**Comment by big-tooth** [comment]
问题描述的再准确一些就是，stop命令跑完以后，之后的所有命令都会被吞掉，如图所示：
![image](https://user-images.githubusercontent.com/55900340/230825160-e5091a1f-6379-45de-b054-1b198d2d2c6f.png)

**Comment by Mgazul** [comment]
服务器都关闭了，哪来的命令给你执行？

**Comment by big-tooth** [comment]
> 服务器都关闭了，哪来的命令给你执行？

吞命令了呀 = = 
不应该会显示`ls`俩字母么

**Comment by MCUmbrella** [comment]
> 服务器都关闭了，哪来的命令给你执行？

@Mgazul 这个我懂，他的意思是如果你用Linux跑mohist，在输stop关服了以后你就会发现在终端输系统命令会没有回显，只剩下提示符（类似于sudo或者su的时候你输密码没有回显的现象）。在我这边摁Ctrl+C关服不会出现这种问题，貌似只有输stop正常关服才会

**Comment by MCUmbrella** [comment]
建议把标题改成像“在Linux终端使用stop关服后输入系统命令时无回显”这样的，要不然没哪个人能看懂，我也是看后边的这个截图才明白楼主想表达的是这个问题

**Comment by big-tooth** [comment]
> 建议把标题改成像“在Linux终端使用stop关服后输入系统命令时无回显”这样的，要不然没哪个人能看懂，我也是看后边的这个截图才明白楼主想表达的是这个问题

title 已改

**Comment by big-tooth** [comment]
> > 服务器都关闭了，哪来的命令给你执行？
> 
> @Mgazul 这个我懂，他的意思是如果你用Linux跑mohist，在输stop关服了以后你就会发现在终端输系统命令会没有回显，只剩下提示符（类似于sudo或者su的时候你输密码没有回显的现象）。在我这边摁Ctrl+C关服不会出现这种问题，貌似只有输stop正常关服才会

你这是在screen内部执行嘛，ctrl+c 也会存在无回显现象，感觉是bukkit插件的缘故吧，还得跟一下代码才行==

**Comment by MCUmbrella** [comment]
我在正常终端跟screen用stop关服都有这个问题，没装插件和mod的情况我还没测试

**Comment by big-tooth** [comment]
> 我在正常终端跟screen用stop关服都有这个问题，没装插件和mod的情况我还没测试

可能需要重写`StopCommand.execute()` 方法☹

**Comment by ProjectSky** [comment]
该问题在1.20.1版本中依然可以复现。
版本：1.20.1-502, Java(17.0.8.1)
