### ISSUE TITLE
[1.18.2] 使用Mod机械动力（Create）后加载报错

### ISSUE THREAD

**Issue by imJack6** [Teneted/Tenet#2467]
**Minecraft Version :** 1.18.2

**Mohist Version :** 10

**Operating System :** Linux

**Concerned mod / plugin** : 机械动力（Create）

**Steps to Reproduce :**
 1. 在mods文件夹放入机械动力mod或机械动力与飞轮前置
 2. 启动

**Description of issue :** 安装机械动力Mod后报错：
`[20:31:55] [WARN]: Error loading class: java/lang/Class (java.lang.IllegalArgumentException: Unsupported class file major version 63)`

`[20:31:55] [FATAL]: Mixin apply failed create.mixins.json:ContraptionDriverInteractMixin -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> create.mixins.json:ContraptionDriverInteractMixin -> Apply Methods -> (Ljava/lang/Class;)V:<init> -> Transform LVT -> var=baseClass -> desc=Ljava/lang/Class;]`

**Comment by Mgazul** [comment]
Create does not support jdk19
