### ISSUE TITLE
[1.19.4] Unable to create world using WorldLoader

### ISSUE THREAD

**Issue by ImagineEngine** [Teneted/Tenet#2469]
**Minecraft Version :** 1.19.4

**Mohist Version :** mohist-1.19.4-41-server.jar

**Operating System :** Windows 11

**Concerned mod / plugin** : Custom Coded Plugin

**Logs :** https://pastebin.com/LALyTHAZ

**Steps to Reproduce :**
 1. Use any plugin that creates or loads multiple worlds

**Description of issue :** As per the logs, it says that the Minecraft world loader is null

**Comment by Mgazul** [comment]
It has been fixed
