### ISSUE TITLE
【1.16.5 #1119】关于EPIC FIGHT末影龙无法正常召唤的问题

### ISSUE THREAD

**Issue by wdkoij** [Teneted/Tenet#2487]
**Describe the solution you'd like**
你好，请问能帮我弄一个server.jar是给epic fight模组能让末影龙正常召唤出来的吗？我对于代码方面一窍不通，所以不知道该怎么做

**Additional context**
[Add any other context or screenshots about the feature request here.](https://github.com/MohistMC/Mohist/commit/708f0d03645dd7fc3120373c348cf615954fd0c0) 《 这是你发的解决代码

**Comment by wdkoij** [comment]
> **Describe the solution you'd like** 你好，请问能帮我弄一个server.jar是给epic fight模组能让末影龙正常召唤出来的吗？我对于代码方面一窍不通，所以不知道该怎么做
> 
> **Additional context** [[Add any other context or screenshots about the feature request here.](https://github.com/MohistMC/Mohist/commit/708f0d03645dd7fc3120373c348cf615954fd0c0)] 《 这是你发的解决代码

**Comment by Mgazul** [comment]
如果1119仍然崩溃，请再次提供崩溃日志

**Comment by wdkoij** [comment]
full log < https://haste.mohistmc.com/zeximodunu.yaml
crash report < https://haste.mohistmc.com/exakejohes.rb
