### ISSUE TITLE
World generation issues with Mohist and JustEnoughIDs

### ISSUE THREAD

**Issue by cestofmir** [Teneted/Tenet#255]
**Describe the bug**
With Mohist installed on the server, I appear to get weird world generation issues. In the overworld, terrain generation appears to be normal though all of the biomes are marked as "Ocean." In modded dimensions, added by the Galacticraft mod, I appear to get weird glitched dimensions which add overworld features to them: 

I believe this may have something to do with JustEnoughIDs.

**To Reproduce**
1. Install JustEnoughIDs and Galacticraft, exceed the biome ID limit with mods
2. Go into space using /dimensiontp

**Expected behavior**
Normally, generation on other dimensions from galacticraft wouldn't generate overworld features such as flowers, dirt, lava, etc.

**Screenshots**
[https://cdn.discordapp.com/attachments/615256015704948808/702700822412394557/unknown.png]

**Info (please complete the following information):**
The primary worldgeneration altering mods I'm using are Geographicraft, Biomes o Plenty, and JustEnoughIDs. I can obtain a full modlist if necessary

**Additional context**

**Comment by Mgazul** [comment]
When you do n’t use JustEnoughID, does it work properly?

**Comment by cestofmir** [comment]
> When you do n’t use JustEnoughID, does it work properly?

Yeah, it works properly without JustEnoughIDs

**Comment by LoganTheOverlord** [comment]
I have same problem, can confirm!

**Comment by TansuoTro** [comment]
Sorry, this problem cannot be solved perfectly due to the MOD mechanism, please uninstall JustEnoughIDs. Maybe it will be on the agenda to fix in the future.
