### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by blacksythe** [Teneted/Tenet#258]
**Describe the bug**
Libraries Fail to aquire when running forge installer
Manually pulling the forge libraries results in failed to find minecraft
 
**To Reproduce**

**Expected behavior**

**Screenshots**
[2020-04-25-1.log.gz](https://github.com/Mohist-Community/Mohist/files/4533644/2020-04-25-1.log.gz)
[2020-04-25-2.log.gz](https://github.com/Mohist-Community/Mohist/files/4533645/2020-04-25-2.log.gz)
[debug.log](https://github.com/Mohist-Community/Mohist/files/4533646/debug.log)
[debug-1.log.gz](https://github.com/Mohist-Community/Mohist/files/4533647/debug-1.log.gz)
[debug-2.log.gz](https://github.com/Mohist-Community/Mohist/files/4533648/debug-2.log.gz)
[latest.log](https://github.com/Mohist-Community/Mohist/files/4533649/latest.log)

**Info (please co
![explorer_Q5yPJdQC1d](https://user-images.githubusercontent.com/11398873/80286903-18096f80-8726-11ea-8ac8-40adda6cc656.png)
mplete the following information):**
Vanilla Mohist

**Additional context**

**Comment by Shawiizz** [comment]
Hello, Mohist 1.15.2 is not usable yet. You need to wait the first official release to use it.

**Comment by blacksythe** [comment]
Looking forward to it Will be keeping an eye on jenkins and this git. regardless hope my log and debug files are of some use to you.
