### ISSUE TITLE
[1.19.2] IridiumSkyblock 空岛插件问题

### ISSUE THREAD

**Issue by FENYU-STUDIO** [Teneted/Tenet#2593]
**Minecraft Version :** {1.19.2}

**Mohist Version :** 35

**Operating System :** {Linux (amd64) version 5.15.0-76-generic}

**Concerned mod / plugin** : {Plugins (2): IridiumSkyblock v.3.2.12,Vault 1.7.3-b131}

**Logs :** ![IMG_20230804_164122.jpg](https://github.com/MohistMC/Mohist/assets/136221034/4284b607-aca0-4471-a5ee-3db9940c74ab)
![IMG_20230804_164151.jpg](https://github.com/MohistMC/Mohist/assets/136221034/22021ed8-1526-4fe5-83ad-e108d4a35862)
![IMG_20230804_164224.jpg](https://github.com/MohistMC/Mohist/assets/136221034/a49bf4c5-81c2-4d0a-bcb5-bce3edd15f88)
**Steps to Reproduce :**
 1. 核心重命名为 server-release.jar
 2. 将IridiumSkyblock 3.2.12 和 vault 放进plugins
 3. 使用java -jar server-release.jar启动

**Description of issue :** 
- 创建空岛时无法选择架构，其内容为空。如图![7842ee09ec840167.jpg](https://github.com/MohistMC/Mohist/assets/136221034/fb036ea1-467e-4cec-86ff-929d4d7a0683)
- 启动时并没有生成空岛地图文件，如图中的IridiumSkyblock,IridiumSkyblock_nether,IridiumSkyblock_the_end。
（这是在paperMC 1.20.1所测试的）
![IMG_20230804_182320.jpg](https://github.com/MohistMC/Mohist/assets/136221034/da6d5358-b391-4797-b3d8-8db4ade740e2)
- 经过测试，这个问题不与mods有关，在卸除所有mods后依然存在。在plugins中仅保留IridiumSkyblock及其前置插件vault问题依然存在。

**Comment by Mgazul** [comment]
1.19.2还没有制作完毕
