### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by SaGye9816** [Teneted/Tenet#2595]
**Minecraft Version :** {Minecraft version}
1.19.4
**Mohist Version :** {Provide Mohist build number}
160
**Operating System :** {Provide the name of your OS}

**Logs :** {Link(s) of logs and crash reports if you have}
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-08-06 19:58:51
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:948) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:298) ~[server-1.19.4-20230314.122934-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2671702016 bytes (2547 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34727.43
	Virtual memory used (MB): 19917.09
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 7 total; -Xms3G -Xmx3G -XX:UseSSE=4 -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:G1NewSizePercent=40 -XX:+UseCodeCacheFlushing
	CraftBukkit Information: CraftServer is not running yet
	Server Running: true
	Data Packs: vanilla, mod:forge
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.16.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.4-45.1.16-universal.jar                |Forge                         |forge                         |45.1.16             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6b0c8d27-cfb1-45c9-9bd5-d0dc7bb07006
	FML: 0.0
	Forge: net.minecraftforge:45.1.16

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by Mgazul** [comment]
Provide full log files

**Comment by SaGye9816** [comment]
> Provide full log files

That is a full log ..

**Comment by SaGye9816** [comment]
> > Provide full log files
> 
> That is a full log ..

I added an issues lastest version of mohist and full logs
