### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by SaGye9816** [Teneted/Tenet#2596]
**Minecraft Version :** {Minecraft version}
1.20.1
**Mohist Version :** {Provide Mohist build number}
287
**Operating System :** {Provide the name of your OS}
window
**Logs :** {Link(s) of logs and crash reports if you have}
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-08-06 20:07:19
Description: Exception in server tick loop

java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:853) ~[server-1.20.1-20230612.114412-srg.jar%23185!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:280) ~[server-1.20.1-20230612.114412-srg.jar%23185!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:littletiles.mixins.json:server.level.MinecraftServerAccessor,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Mohist Version: 1.20.1-287
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 170209384 bytes (162 MiB) / 717225984 bytes (684 MiB) up to 8568963072 bytes (8172 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34727.43
	Virtual memory used (MB): 20882.08
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	CraftBukkit Information: CraftServer is not running yet
	Server Running: true
	Data Packs: vanilla, mod:morecosmetics, mod:armourers_workshop (incompatible), mod:pamhc2trees (incompatible), mod:pamhc2crops (incompatible), mod:cfm, mod:zetter (incompatible), mod:creativecore, mod:simplylight (incompatible), mod:pamhc2foodextended (incompatible), mod:forge, mod:zettergallery (incompatible), mod:pamhc2foodcore (incompatible), mod:littletiles
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'mohist'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.1.62.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.62.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.1.62.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.1.62.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.1.62.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		MoreCosmetics-Forge-1.20.jar                      |MoreCosmetics                 |morecosmetics                 |1.2                 |DONE      |Manifest: NOSIGNATURE
		armourersworkshop-forge-1.20.1-2.0.2.jar          |Armourer's Workshop           |armourers_workshop            |2.0.2               |DONE      |Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a
		pamhc2trees-1.20-1.0.2.jar                        |Pam's HarvestCraft 2 - Trees  |pamhc2trees                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.20-1.0.2.jar                        |Pam's HarvestCraft 2 - Crops  |pamhc2crops                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		zetter-1.20-0.21.4.jar                            |Zetter                        |zetter                        |0.21.4              |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.32_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.32             |DONE      |Manifest: NOSIGNATURE
		simplylight-1.20.1-1.4.5-build.49.jar             |Simply Light                  |simplylight                   |1.20.1-1.4.5-build.4|DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.20-1.0.0.jar                 |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.62-universal.jar                |Forge                         |forge                         |47.1.62             |DONE      |Manifest: NOSIGNATURE
		zettergallery-1.20-0.5.3.jar                      |Zetter Gallery                |zettergallery                 |0.5.3               |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.20-1.0.0.jar                     |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		LittleTiles-Mod-Forge-1.20.1.jar                  |LittleTiles                   |littletiles                   |1.6.0-pre056        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b2457894-f077-4830-94f9-6ae7096f782f
	FML: 0.0
	Forge: net.minecraftforge:47.1.62
**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by Mgazul** [comment]
Provide full log files
