### ISSUE TITLE
[1.20.1] Content of storage on create contraption disappear when contraption is desassembled

### ISSUE THREAD

**Issue by benjamindeneu** [Teneted/Tenet#2599]
**Minecraft Version :** 1.20.1

**Mohist Version :** 289

**Operating System :** ubuntu server 22.04

**Concerned mod / plugin** : Create mod

**Logs :** No crash

**Steps to Reproduce :**
 1. Make a create contraption with a mechanical bearing or a minecart
 2. add inventory to the contraption (chests)
 3. put items in the contraction while assembled
 4. stop/disassemble the contraption
 5. items in storage desappear

**Description of issue :** On a minecraft server with mohist: Storage content of all storage on a create mod contraption disappear when contraptions returns to normal blocks (disassembled). Tried at least for mechanical bearing when right clicking to stop, and minecart contraption when putting on an activator rail that is not powered. It's working with the same modpack on a regular forge server with version 47.1.43

**Comment by Mgazul** [comment]
Fixed
