### ISSUE TITLE
Stack Owerflow when the mod JustAFewFish is used

### ISSUE THREAD

**Issue by DMNerd** [Teneted/Tenet#26]
[crash-2019-11-24_13.35.28-server.txt](https://github.com/Mohist-Community/Mohist/files/3883550/crash-2019-11-24_13.35.28-server.txt)

I dont have any further information. I Only know this doesn't happen without the mod enabled.

Tested on newest Jenkins build.

EDIT: I should also clarify that this doesn't happen on pure forge server
EDIT 2: Also removed betterFPS as it was clientside only, still the same crash

**Comment by Mgazul** [comment]
Need to provide latest.log

**Comment by Mgazul** [comment]
Related to JustAFewFish mod
