### ISSUE TITLE
[1.20.1] CoreProtect wrong block-break log

### ISSUE THREAD

**Issue by KLONOA9X6** [Teneted/Tenet#2605]
**Minecraft Version :** 1.20.1

**Mohist Version :** 287

**Operating System :** Windows 11

**Concerned mod / plugin** : [CoreProtect](https://github.com/PlayPro/CoreProtect)

**Logs :** 
_No Response_

**Steps to Reproduce :**
_No Response_

**Description of issue :** [CoreProtect #422](https://github.com/PlayPro/CoreProtect/issues/422)

**Comment by P3ridot** [comment]
I tested latest CoreProtect with latest Mohist and I can't really reproduce this problem... Everything is logging fine
