### ISSUE TITLE
Add Paper API plz

### ISSUE THREAD

**Issue by TransparentWhit** [Teneted/Tenet#2615]
Mohist doesn't include Paper API so Paper plugins don't work. I know paper has tons of patches and it would take a lot of work, but at least include the Adventure API plz. That would fix at least 60% of my paper plugins

**Comment by Mgazul** [comment]
1.20.2

**Comment by TransparentWhit** [comment]
I'm on 1.18.2 by the way

**Comment by Mgazul** [comment]
1.18.2 will not add paper api
