### ISSUE TITLE
[1.12.2] Tile-Entities not unloading.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#262]
As you can see, TE's build up and never get unloaded for some reason.
Like the chunks where the TE's are, arent even loaded. Ive sent everyone to spawn and let all the chunks unload completely, and theres still over 14k TE's.

```
[20:09:38 INFO]: 
                  |    E |    TE |    C |        
      overworld/0 |   13 |   424 |    1 |        
    the_nether/-1 |  131 |   321 |  367 |        
        the_end/1 |    8 |    82 |    1 |        
   Storage Cell/2 |    0 |     0 |    0 |        
      overworld/6 |  250 |   902 |    3 |        
      overworld/4 |  445 | 12561 | 1104 |        
  Space Station/9 |    0 |     3 |    0 |        
 Space Station/10 |    0 |    24 |    2 |        
  Space Station/8 |    0 |     3 |    0 |        
twilight_forest/7 |  393 |   160 |  332 |        
        8 Players | 1240 | 14480 | 1810 | 135.57%
 14.75 TPS [ ##############################~~~~~~~~~~ ] 
```

**Comment by kaziu687** [comment]
At 1.7 (Thermos, KCauldron) there were "load chunk on request" feature, when disabled TE's asking for chunk didn't load them. When enabled everything work like chunkloader (as now). I remember that even water can keep chunks loaded at that config. It's huge problem.

**Comment by Zilacon** [comment]
Can this please be fixed? This is kind of a major problem...
