### ISSUE TITLE
Citizens bug with Path

### ISSUE THREAD

**Issue by CKATEPTb** [Teneted/Tenet#263]
![image](https://user-images.githubusercontent.com/33106029/80343771-28793180-886f-11ea-904e-7f637e657466.png)
 Citizens broke the build #471 (and other nms plugins). Why was it necessary to change the already good remaper that the previous is wrong?

**Comment by Mgazul** [comment]
It ’s not an error, I ’m just trying to fix the compatibility of some plugins, so I made a new one, but found it not ideal, I have returned to the previous.
