### ISSUE TITLE
[1.19.2] Fix port from 1.19.4/1.20.1

### ISSUE THREAD

**Issue by nekorissu** [Teneted/Tenet#2654]
**Is your feature request related to a problem? Please describe.**
F*cking pehkui. I saw there was already a fix for 1.19.4/1.20.1, and I would like to ask for this fix for 1.19.2 (update is not possible because most of the mods special mods stopped updating). Thanks <3

**Describe the solution you'd like**
Port fix from 1.19.4: https://github.com/MohistMC/Mohist/commit/62c4b5f58712d50cc806bd77374603df5a05743f
& from 1.20.1: https://github.com/MohistMC/Mohist/commit/ee39bd0d4fc7c145f108a5f0062b20e1db14aba8

**Additional context**
Nothing

**Comment by Mgazul** [comment]
https://github.com/MohistMC/Mohist/commit/01a9156da9661dee0b3e62beaa0f0b661bc09ae9
fixed on the same day

**Comment by nekorissu** [comment]
Thanks, sorry didn't see it, but this fix doesn't work.
https://paste.ee/p/RfVVP (server: last 1.19.2 mohist build)
