### ISSUE TITLE
[Bug] Even with save world on stop, doesnt seems work

### ISSUE THREAD

**Issue by Flashback083** [Teneted/Tenet#266]
**Describe the bug**
I enable 'save world when server stop' but its doesnt seems work

**To Reproduce**
1. Start the server
2. Place a block
3. /stop immediatly
4. Restart the server & see the block isnt placed

**Expected behavior**
Should keep the block on the world cause its saved xd

**Version :**
Mohist 4c322ef

**Comment by Shawiizz** [comment]
Hi, after testing this bug isn't here on the latest Mohist version.
