### ISSUE TITLE
Mohist 1.20.1 and MSM

### ISSUE THREAD

**Issue by avescarelo** [Teneted/Tenet#2682]
**What is your question ?**
{Hello, I want to use the MSM manager for my server, but it can't run it... Is it solvable? I will be glad if you suggest alternatives to MSM}
MSM: [https://msmhq.com/](https://msmhq.com/)

**Comment by Mgazul** [comment]
You should ask the person in charge of MSM or provide specific indications of unavailability

**Comment by avescarelo** [comment]
> You should ask the person in charge of MSM or provide specific indications of unavailability

Thnx, do you know the alternatives?

**Comment by Mgazul** [comment]
Generally speaking, we do not recommend using any manager. It is recommended to directly use bat to run the server.

**Comment by avescarelo** [comment]
> Generally speaking, we do not recommend using any manager. It is recommended to directly use bat to run the server.

I go to the server folder and run it with a command, but if I disconnect from the remote server, the process closes and the server shuts down...
