### ISSUE TITLE
Mohist didn't support ipv6 in linux?

### ISSUE THREAD

**Issue by KLONOA9X6** [Teneted/Tenet#2696]
**What is your question ?**
When I set up a new 1.20.1 server to use the old address, I found that the server could not use the ipv6 address. Only jump to the paid ipv4 forwarding channels can be used. It's a bit of a financial burden for me.

The strange thing is that after testing, the exact same server file under Windows system without any network problems. And no related configuration files were found. Is this a BUG?
![image](https://github.com/MohistMC/Mohist/assets/95112579/dc2db936-be1a-4c06-baeb-258edcbe1b6e)
![image](https://github.com/MohistMC/Mohist/assets/95112579/1aed0b22-466a-4083-ad11-2f8e00118033)

**Comment by KLONOA9X6** [comment]
Mohist version: 1.20.1-426
System: Ubuntu 22.04.1 LTS x86_64

**Comment by glowingstone124** [comment]
maybe you should check your system configuration? Mohist never changes Minecraft's network part.

**Comment by KLONOA9X6** [comment]
> maybe you should check your system configuration? Mohist never changes Minecraft's network part.

I'm sure it's not system problem, because I tried fabric server and it's work well

**Comment by glowingstone124** [comment]
> > maybe you should check your system configuration? Mohist never changes Minecraft's network part.
> 
> I'm sure it's not system problem, because I tried fabric server and it's work well

can you privide some logs or just nothing but just cannot connect?

**Comment by KLONOA9X6** [comment]
> > > maybe you should check your system configuration? Mohist never changes Minecraft's network part.
> > 
> > 
> > I'm sure it's not system problem, because I tried fabric server and it's work well
> 
> can you privide some logs or just nothing but just cannot connect?

Just can not connect

**Comment by GRCXII** [comment]
启动参数里加上
`-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true`
试试，像这样
`java -Xms4G -Xmx16G -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -jar mohist-1.20.1-449-server.jar
`

**Comment by KLONOA9X6** [comment]
> 启动参数里加上 `-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true` 试试，像这样 `java -Xms4G -Xmx16G -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -jar mohist-1.20.1-449-server.jar `

没问题了，感谢
