### ISSUE TITLE
[Question] Add a method api from spigot 1.14.4

### ISSUE THREAD

**Issue by Flashback083** [Teneted/Tenet#270]
**Describe the bug**
Hello ! I would like to know if its possible to implement this idea to Mohist 1.12.2 :
https://hub.spigotmc.org/jira/browse/SPIGOT-5311
(screen to explain https://cdn.discordapp.com/attachments/645677989383766026/705452185143738398/unknown.png)
Thanks for your work !

**Comment by Mgazul** [comment]
Won't add
