### ISSUE TITLE
[1.12.2] Nether Portal Entity Tracking Crash with Pixelmon

### ISSUE THREAD

**Issue by Enderminer** [Teneted/Tenet#272]
Description:
When a player in the nether throws a Pokeball in a Nether Portal it crashes the server.

1. On a Mohist 1.8-1.12.2-042c616 Server, Install Pixelmon 7.2.0 and join.
2. When on the server enter the Nether.
3. Once in the Nether, send out your Pokemon a few times inside the Nether Portal.
4. Server should crash in a few seconds.
 
Expectation:
Player sends out Pokemon inside portal and nothing happens.

Info:
- Mod/Plugins Name: Pixelmon, Mohist
 - Mod/Plugins  Version: 7.2.0, 1.8-1.12.2-042c616

Additional info:
I believe it's an issue with entity tracking when the Pokeball travels through the portal.

Crash Report: https://gist.github.com/Enderminer/d797fc40399989015f213d0254067403

**Comment by abelbaek** [comment]
I am having the same problem.

Why was it closed?
