### ISSUE TITLE
Mohist 1.12.2 - Don't work plugins, many warns..

### ISSUE THREAD

**Issue by CrackBack11** [Teneted/Tenet#273]
**Describe the bug**
He kicks me off the server.

**To Reproduce**
1. On Mohist-1.12.2-52139cb-server.jar
2. Click on Entry on server
3. Many warns
4. You enter the server, you try to write something and it kicks you out

**Expected behavior**
The server works without any problems without plugins, after I added them and I enter the server it doesn't let me, I delete the plugins and I let it enter the same way it doesn't let me, it leaves me after I reset everything and it remains only with modes .... I managed to enter with modes and plugins leaves me in the end but if I write on chat it kicks me out ...

**Screenshots**
https://imgur.com/un4Iqgz

**Info (please complete the following information):**
- Plugins Name: BoostedJoin, ChatControlPro, ChestLockGui, Deluxe Mentinons, DeluxeCombat, ECore, EssentialsX, EssentialsXChat, EssentialsXSpawn, FastCraft, FPSHelper, GroupManager, IPWhitelist, KiteBoard, LaggRemover, LiteBans, NeoMoreTPPlus, NetherFix, PlaceholderAPI, PlayerInformation, ProtocolLib, PublicCrafters, SAML, TAB Premium, TradeMe, UltraCustomizer, UltraCustomizerPlus, Vault, WorldEdit, WorldGuard
 - Plugins Version: Latests

**Additional context**
I use an Aegis bungee fork, more precisely it must have been something from it, in fact I tested it on the waterfall and it is the same result ...

**Comment by Shawiizz** [comment]
Can you please remove your plugins 1 per 1 and test to know which plugin causes that ?

**Comment by ghost** [comment]
It's happens, because some plugin require the packet container from NettyIO. I belive its a ProtocolLib, because the same use the protocols of the Netty.

**Comment by Mgazul** [comment]
If you use ProtocolLib, please use version 4.4.0 instead of 4.5.0
