### ISSUE TITLE
[1.12.2] Items not dropping in correct quantities.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#275]
**Describe the bug**
Items not dropping from player.

**To Reproduce**
Place stack of items in hand, then press Q to drop. You will pick up a lesser amount from what you dropped from inventory..

**Expected behavior**
If i tossed out 32 blocks of stone, i should pick up 32 blocks of stone, not 5.

**Comment by Shawiizz** [comment]
Hi, after testing I don't have this problem. Is this problem appears for you today ?

**Comment by Mgazul** [comment]
Multiple tests have not appeared in this issue, if you reappear please reopen this issue
