### ISSUE TITLE
1.15.2 branch can't be imported to a workspace

### ISSUE THREAD

**Issue by HarroldSaxon** [Teneted/Tenet#276]
The main project name was changed to Forge, with registered dependent forge. this prevents the project being loaded into a workspace as Forge and forge are seen as importing the same project twice. perhaps this still works under some non windows environments?

**Comment by Mgazul** [comment]
Everything works fine here

**Comment by Shawiizz** [comment]
Hi @HarroldSaxon, is your problem solved ?
