### ISSUE TITLE
Mohist not terminating while loading libraries

### ISSUE THREAD

**Issue by argseby** [Teneted/Tenet#278]
```
                        -- Mohist Development Group
Mohist Starting...
Loading libraries, please wait...

C:\Users\sebyk\Desktop\FinalTest>pause
Press any key to continue . . .
```

Already tried different versions of java and gamefiles. 
This problem only persists if i want to load a big  modspack (The 1.12.2 modpack in my case).
No problems on blank server installation or low amount of mods.

Tried it with different sizes of ram.

**Comment by Mgazul** [comment]
Provide latest.log

**Comment by argseby** [comment]
[latest.log](https://github.com/Mohist-Community/Mohist/files/4595043/latest.log)

**Comment by Mgazul** [comment]
remove vanillafix
