### ISSUE TITLE
[1.12.2] wordedit //set error

### ISSUE THREAD

**Issue by douglasppn** [Teneted/Tenet#279]
**Describe the bug**
The world edit plugin is not recognizing the mods installed on the server, when you try to give for example: "//set divinerpg:arlemite_ore" there is an error saying that the block does not exist. I tested it with the mod world edit forge there it worked. the world guard plugin depends on the world edit plugin..

**To Reproduce**
4. Unknown data value 'arlemite_ore'

**Screenshots**
https://imgur.com/a/GQqwykB

**Info (please complete the following information):**
- Mod/Plugins Name: 
 - Mod/Plugins  Version:

**Comment by Mgazul** [comment]
Cannot be modified from within mohist, because worldedit customizes a BlockType class to enumerate all the vanilla blocks

**Comment by Mgazul** [comment]
https://github.com/Mohist-Community/WorldEdit/releases/download/6.1.9/WorldEdit-6.1.9-SNAPSHOT-all.jar
