### ISSUE TITLE
Incompatibility with NetherEx and End Reborn

### ISSUE THREAD

**Issue by dawgun** [Teneted/Tenet#28]
I was assembling a pack of mods and I managed to isolate these mods that gave me problems. None of the mods get them to work even if they are alone.

In the case of the End Reborn, with the latest version 0.3.1, the server does not start, although using 0.3.0, it does work.

Crash Log: [Crash_Endreborn_.txt](https://github.com/Mohist-Community/Mohist/files/3891977/Crash_Endreborn_.txt)

In the case of NetherEx, I have not been able to start in any of the latest versions.

Crash Log: [Crash_NetherEx.txt](https://github.com/Mohist-Community/Mohist/files/3891976/Crash_NetherEx.txt)

Thank you very much

**Comment by Mgazul** [comment]
already fixed! Thanks for feedback!

**Comment by dawgun** [comment]
Thank you very much for the speed in which you have solved everything.

The End reborn works perfectly in version 0.3.1

The NetherEx now starts the server but when I try to enter the Nether, the server crashes, of course I am testing it with the latest version (f83968c) that you uploaded a while ago.

I tried to start the server with just Forge and it works fine. Upon entering the Nether, he tells me this phrase in case it helps you.

"defineId called for: class net.minecraft.entity.monster.EntityBlaze from class logictechcorp.netherex.entity.monster.EntityFrost"

And then I leave you the log of the crash in Mohist. [Crash NetherEx Mohist-f83968c-server .txt](https://github.com/Mohist-Community/Mohist/files/3893179/Crash.NetherEx.Mohist-f83968c-server.txt)

Thanks for all! <3

**Comment by Mgazul** [comment]
Should be fixed! Need to test
