### ISSUE TITLE
[1.20.1] Entity does not have attribute null

### ISSUE THREAD

**Issue by killer2gudpl** [Teneted/Tenet#2800]
**Minecraft Version :** 1.20.1 Forge 47.2.5

**Mohist Version :** 1.20.1-512

**Operating System :** Windows 10

**Logs :** https://pastebin.com/Df7ryEQK (client log as it is relevant to client)

**Mod list :** None.

**Plugin list :** None.

**Description of issue :** The client is being spammed with warnings, which then escalate to Errors as  #2759 when Apotheosis is installed. The issue occurs even without mods and plugins and it does **not** occur when on single player server, leading to suggestion that Mohist is causing it. The frequency of the spam is very big, as any entity renderred gets it, which hinders storage space.

**Comment by killer2gudpl** [comment]
@Mgazul how come this is a duplicate? I just mentioned the problem I have could be the cause of the error specified too. I assume potential GBs of logs is not an issue then?

**Comment by Mgazul** [comment]
#2759

**Comment by killer2gudpl** [comment]
> #2759

Not the same issue, as the guy has Apotheosis installed. I did not and received a warning that gets spammed.

I have only mentioned the issue because I think the issue I am having, could be a **potential cause** of other issue.
