### ISSUE TITLE
[1.20.1] ModelEngine v4.0.3 NoSuchMethodError - PlayerDeathEvent.getPlayer() 

### ISSUE THREAD

**Issue by PeterMa9621** [Teneted/Tenet#2801]
**Minecraft Version :** 1.20.1

**Mohist Version :** #512

**Operating System :** Windows 11

**Concerned mod / plugin** : ModelEngine v4.0.3

**Logs :** Link(s) of logs and crash reports if you have
https://pastebin.com/sNB8nbg0

**Steps to Reproduce :**
 1. Install ModelEngine 4 and MythicMobs together
 2. Spawn a ModelEngine 4 mob and Let the mob kill you
 3. Check the console, error message will appear

**Description of issue :** Give all details about your issue

**Comment by SimonMage** [comment]
Yes the problem appears in 1.20.1 but if you can update to 1.20.2, it's fixed in this version

**Comment by SimonMage** [comment]
Mgazul always the best
