### ISSUE TITLE
[1.20.1] Adventure API font and translatable components are not displayed correctly.

### ISSUE THREAD

**Issue by Tobies** [Teneted/Tenet#2806]
**Minecraft Version :** 1.20.1

**Mohist Version :** 518

**Operating System :** Windows 10

**Concerned mod / plugin** : It's a custom made plugin, I would link a code snippet to reproduce the issue.

**Logs :** No errors, this bug is visual

**Steps to Reproduce :**
   
  - I created a custom resource pack to help you test and provided a code snippet that reproduces the issue.
  - I run this snippet in the PlayerDropItemEvent for faster iterations, feel free to use it in whatever way you see fit.

 1. Use this resource pack: https://download.mc-packs.net/pack/36d7a5b27ab5f11daaecf62b09f93171bad2b480.zip
 2. Run this code snippet: 
    ```java
    TextComponent.Builder builder = Component.text();
    builder.append(Component.translatable("space.50").font(Key.key("space:default")));
    builder.append(Component.text("1").font(Key.key("test:default")));
    event.getPlayer().openInventory(Bukkit.createInventory(null, 54, builder.build()));
    ```

**Description of issue :** Personally I think components are not being processed correctly but I haven't read into the code, so I can't provide any feedback confidently.

**Results with mohist ❌ :**
![image](https://github.com/MohistMC/Mohist/assets/37544558/e1f11f06-50c0-4632-a515-1e78cae86a89)

**Results with paper ✔ :**
![image](https://github.com/MohistMC/Mohist/assets/37544558/a82b25a7-298e-4059-b00a-c0a52f488e26)

**Comment by glowingstone124** [comment]
Hello, Mohist doesn't support the Component feature because it doesn't include the Paper API. Including the Paper API would cause many problems, so Mohist's developers are not planning to include it. Sorry for the inconvenience.
