### ISSUE TITLE
[1.20.1] Gui closes

### ISSUE THREAD

**Issue by steam9w** [Teneted/Tenet#2831]
Minecraft Version : 1.20.1

Mohist Version : mohist-1.20.1-497-server.jar

Operating System : windows / linux

Concerned mod / plugin : DivineRPG-1.10.6.1.jar

Logs : https://haste.mohistmc.com/ubivowutev.less

Steps to Reproduce :
 1. Put arcanium extractor.
 2. Open gui the block.
 3. Post any recipe. For example - collector + raw arcanium.
 4. After we put the necessary ingredients, the block's gui automatically closes and the items disappear.

Description of issue : This problem occurs ONLY on Mohist

**Comment by Mgazul** [comment]
Please provide the complete server log, not a fragment

**Comment by steam9w** [comment]
[latest.log](https://github.com/MohistMC/Mohist/files/13509939/latest.log)
The error was reproduced on the server with only 1 mod ( DivineRPG-1.10.6.1 ) ( no plugins )
The error has been reproduced.

But this error did not appear in the logs.

**Comment by HowardZHY** [comment]
Does it still happen with latest build & DRPG?

**Comment by steam9w** [comment]
yes

**Comment by Mgazul** [comment]
Fixed
