### ISSUE TITLE
Towny error

### ISSUE THREAD

**Issue by crassmister** [Teneted/Tenet#2832]
**Minecraft Version :** 1.18.2

**Mohist Version :** 113

**Operating System :** Using a server provider, Shockbyte, some kind of Linux

**Logs :** https://haste.mohistmc.com/ozuvociyop.yaml

**Mod list :** kiwi, otyacraftengine, createbigcannons, alloyed, alexsmobs, culturaldelights, oldguns, armor_speed, createdeco, jei, siegemachines, immersive_aircraft, immersive_weathering, create, falchionmoveset, epicfight, ritchiesprojectilelib, comforts, citadel, fruittrees, sereneseasons, nocubes_farmer_compats, magistuarmory, cofh_core, starlight, cloth_config, forge, dummmmmmy, createpickywheels, riding_partners, supplementaries, selene, corpse, minecraft, farmersdelight, horsecombatcontrols, environs, voicechat, iammusicplayer, cozy_home, growthcontrols, shouldersurfing, efdg, fishingoverhaul, archers_paradox, weaponmaster, spacecatasb, astikorcarts, shoppy, brewinandchewin, curios, flywheel, farmersrespite, patchouli, farmers_bundle, camera, some_assembly_required, polymorph, immersive_paintings, framedblocks, backpacked, canary, armourers_workshop, hangman, one_twenty_backport, architectury, alexsdelight, aquaculture, bn_blood_particles_mod, smallships, crabbersdelight, playertrade, cosmeticarmorreworked, overloadedarmorbar, geckolib3, dangerousstonecutter

**Plugin list :** Towny, Brewery, WorldBorder

**Description of issue :** Towny spits out a "[Towny] Not Registered." message in chat when walking/moving, and says "This world is exempt of all towny interactions" when trying to use any other command in towny

**Comment by Mgazul** [comment]
Your server-icon.png is not 64*64

**Comment by crassmister** [comment]
Oh thank you so very much!

**Comment by crassmister** [comment]
> Your server-icon.png is not 64*64

I tried setting the server-icon.png to 64x64 but it doesn't seem to have worked, it definitely loaded but towny is still broken and spitting out the same messages
