### ISSUE TITLE
[1.16.5] FAWE error at every commands in game

### ISSUE THREAD

**Issue by BaronDuScotch** [Teneted/Tenet#2833]
**Minecraft Version :** {1.16.5}

**Mohist Version :** {1.16.5-749}

**Operating System :** {Linux (amd64) version 5.10.0-26-amd64}

**Logs :** { https://pastebin.com/W7uYKgJM }

**Mod list :** {
AdvancementPlaques-1.16.5-1.4.1,
appleskin-forge-mc1.16.x-2.5.1,
Architects-Palette-1.16.4-1.1.5,
armourersworkshop-forge-1.16.5-2.0.7,
ars_nouveau-1.16.5-1.21.5,
AutoRegLib-1.6-49,
BackTools-1.16.5-10.2.0,
BetterF3-1.5.0-Forge-1.16.5,
betternether_reforged-1.2,
byg-1.2.9,
chalk-1.16.5-1.2.1,
Chisel-MC1.16.5-2.0.1-alpha.4,
citadel-1.7.3-1.16.5,
cloth-config-4.17.101-forge,
connectivity-2.4-1.16.5,
CosmicNPCs-1.16.4-1.3.0,
create-mc1.16.5_v0.3.2g,
CTM-MC1.16.1-1.1.2.6,
curios-forge-1.16.5-4.0.5.3,
CustomNPCs-1.16.5.20220226,
decorative_blocks-1.16.4-1.7.2,
decorative_winter-0.1.2,
DungeonBlocks-mc1.16.5-f36.1.0-v1.0.3,
dungeons_1.10.3_mc1.16.5,
dungeons_gear-1.16.5-3.0.17,
dungeons_mobs-1.16.5-1.0.10,
einsteins_library-2.0-1.16.5,
engineersdecor-1.16.4-1.1.14,
EpicFightMod-16.5.13,
EquipmentCompare-1.16.5-1.2.7,
fancymenu_forge_2.12.2_MC_1.16.2-1.16.5,
FarmersDelight-1.16.5-0.6.0,
ferritecore-2.1.1-forge,
flywheel-1.16-0.2.4,
geckolib-forge-1.16.5-3.0.45,
GottschCore-mc1.16.5-f36.2.34-v1.8.0,
HealthOverlay-1.16.5-3.0.1,
iceandfire-2.1.8-1.16.5,
Iceberg-1.16.5-1.0.41,
iChunUtil-1.16.5-10.7.0,
ImmersiveEngineering-1.16.5-5.1.0-148,
ImmersiveFX 1.0.2 1.16.5,
jmc-3.0-1.16.5,
konkrete_forge_1.5.0_MC_1.16.2-1.16.5,
L_Enders Cataclysm-0.48 Changed Theme -1.16.5,
LegendaryTooltips-1.16.5-1.1.7,
loadmyresources_1.0.1_MC_1.16.2-1.16.5,
MagmafurnaceDoubleTrouble,
magnesium_extras-mc1.16.5_v1.4.0,
mahoutsukai-1.16.5-v1.31.14,
mcw-furniture-2.0.1-mc1.16.5,
meetyourfight-1.16.5-1.2.0,
moreminecarts-1.3.16,
MoreOresInONE-1.2_1.16.5,
mowziesmobs-1.5.19,
NefsMedievalPub+v1.6(1.16.5),
nekoration-1.16.5-1.5.9,
Patchouli-1.16.4-53.1,
Placebo-1.16.5-4.7.1,
Quark-r2.4-312,
rubidium-0.2.11,
selene-1.16.5-1.8.1,
spiderstpo-1.16.4-2.0.0,
supplementaries-1.16.5-0.18.4,
Timber Framing-1.16.4-1.1.0,
ToastControl-1.16.5-4.4.0,
valhelsia_core-16.0.15,
valhelsia_structures-1.16.5-0.1.6,
windowlogging-mc1.16.3_v0.0.4,
xkdeco_0.2.4
}

**Plugin list :** {FastAsyncWorldEdit-Bukkit-2.2.1-SNAPSHOT-193}

**Description of issue :** {the server is working properly, but every FAWE commands return an error except //pos1 and //pos2, you can see them in the log}

**Comment by Mgazul** [comment]
Fixed

**Comment by BaronDuScotch** [comment]
Doesn't seem fixed to me... Every command return an error like before ^^'

I used the latest mohist version for 1.16.5
https://pastebin.com/A7Ew2CY1

**Comment by EdoEquin0x** [comment]
Try FAWE 2.2.1 instead of the latest version of it (you can find it on their website), I tried it with mohist 131 and work like a charm
