### ISSUE TITLE
粘液科技（slimefun)，物流相关的物品无法摆放

### ISSUE THREAD

**Issue by FlyingPig278** [Teneted/Tenet#2837]
**Minecraft Version :** {1.16.5、1.20.1}

**Mohist Version :** {1.16.5:131、1.20.1:512}

**Operating System :** {windows 10}

**Logs :** {none}

**Mod list :** {none}

**Plugin list :** {EssentialsX/EssentialsXAntiBuild/EssentialsXChat/EssentialsXProtect/EssentialsXSpawn/HungerKeeperPlus/IronElevator/LuckPerms-Bukkit-5.4.71/Slimefun4-35/TogglePvp/Vault1.7.3}

**Description of issue :** {粘液科技的大多数物品都是正常的，现在发现有问题是物流系统，物流系统的cargo node (input)/cargo node (output)/cargo node (output_advanced)无法使用。这三种设备的摆放方式是附着在箱子或机器的侧面的，在摆放到箱子或机器侧面时，本来应该可以摆放，但SF4却一直提示，该物品必须摆放在箱子或机器上，测试了纯插件服PaperSpigot，是正常的，找了下log文件，没有提示错误，删除世界、配置文件重启服务器都不行}

**Comment by Mgazul** [comment]
Fixed
