### ISSUE TITLE
CorruptedFrameException when placing Mohist under a Velocity proxy

### ISSUE THREAD

**Issue by SanderWxD** [Teneted/Tenet#2838]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-521

**Operating System :** Ubuntu

**Logs :** https://haste.mohistmc.com/mubinapiyu.yaml

**Mod list :** /dump web mods isnt a valid command. But the server is running the FTB Direwolf20 1.20.1 modpack (version 1.8.0)

**Plugin list :** /dump web plugins isnt a valid command. But server is running: LuckPerms, FastChunkPregenerator, PlaceholderAPI, ClearLag, Votifier, ProtocolLib, AutoRestart, LuckyWheel, KixsChatAnnouncer, Vault, WorldEdit, DecentHolograms, Essentials, CustomJoinMessages, WorldGuard, Discord_Link, BetterRTP, EssentialsSpawn, CoreProtect, LootCrate, Autorank, SignShop and three custom plugins.

**Description of issue :** Clients (with a matching modslist) cannot connect once the Mohist server is connected to a proxy (Velocity version 3.2.0-Snapshot). Clients receive an "Internal Exception: io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit" error when they attempt to join the proxy that is pointing to the Mohist server. Server generates the same error when all plugins are disabled. Server is perfectly accessible when ran standalone. Server is also accessible through the proxy once Mohist is disabled (and the server runs on bare forge). Error returns once Mohist is enabled again.

When Mohist is connected to the proxy, the Mohist server is set to offline-mode, has "settings.bungeecord" enabled in spigot.yml and is using legacy forwarding. Setting "velocity" to either true or false in mohist.yml makes no difference in the error produced.

**Comment by Mgazul** [comment]
mohist-1.20.1 does not actively support velocity
