### ISSUE TITLE
[1.20.1] Hoppers do not work with Applied Energistics 2 devices

### ISSUE THREAD

**Issue by dominic-03** [Teneted/Tenet#2839]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-533

**Operating System :** Ubuntu Server 22.04.3

**Concerned mod / plugin** : [Applied Energistics 2](https://modrinth.com/mod/ae2/version/U3MExcIx)

**Logs :** Link(s) of logs and crash reports if you have
Neither the server nor client log anything when this occurs.

**Steps to Reproduce :**
 1. Place a Charger, with a hopper below the Charger.
 2. Place Certus Quartz into the Charger.
 3. Wait for the Certus Quartz to charge
 4. Right click the hopper.

**Description of issue :** Give all details about your issue
With Applied Energistics 2 devices, if you try to hopper their output the hopper does not function. When the hopper begins attempting to pull an item in to its storage, it becomes completely inaccessible by right click (the interface closes immediately) and does not pull the item in. This issue does not occur on the official Forge server, which means Mohist most likely is the cause of this.

**Comment by Mgazul** [comment]
Fixed
