### ISSUE TITLE
[1.20.1] The build number of the download page does not match with actual build number

### ISSUE THREAD

**Issue by HowardZHY** [Teneted/Tenet#2843]
![image](https://github.com/MohistMC/Mohist/assets/96782166/f8d59058-290f-46c5-84e0-b34760150c30)
It's actually build 536
![image](https://github.com/MohistMC/Mohist/assets/96782166/c0a61046-a545-4f43-adcf-9fbcb54b822d)

**Comment by Shawiizz** [comment]
Hello, the new website has dynamic building naming so builds numbers are different than old website, it's completely normal. Don't worry, builds are the same and are the latests available, just numbers not updated inside Mohist yet.

**Comment by HowardZHY** [comment]
Still exists, the console output is 30 more than web page
