### ISSUE TITLE
Implement Paper Patches to Bukkit UnsafeValues

### ISSUE THREAD

**Issue by HowardZHY** [Teneted/Tenet#2844]
**Is your feature request related to a problem? Please describe.**
Improves more plugin compatibility

**Comment by HowardZHY** [comment]
This shouldn't be closed as completed now

**Comment by Mgazul** [comment]
we won't do this

**Comment by Mgazul** [comment]
Paper is ruining mc and mods

**Comment by HowardZHY** [comment]
> Paper is ruining mc and mods

This impl. is more API, won't ruin mods
