### ISSUE TITLE
[1.12.2] NetherEx doesn't works properly. Realted with issues #93 (Closed) and #144 (Open)

### ISSUE THREAD

**Issue by BCNGAMER** [Teneted/Tenet#285]
**Describe the bug:**
As explained in issues #93 and #144 NetherEx don't generate ores, biomes, mobs and other structures only generate NetherEx small villages.

**NetherEx Issues Sumnary:**
_1.- [1.12.2] NetherEx doesn't works properly #93:_
Dawgun opened this issue on 20 Feb 2020
Status: Closed on 21 Feb 2020

Dawgun commented later on 21 Feb: "I tested with lastest version and doesn't work yet. It doesn't generate ore, blocks or biomes."
https://github.com/Mohist-Community/Mohist/issues/93

_2.- Mohist Discord #support channel:_
Dawgun post on 28 Feb 2020 a request for double check about Issue #93. Closed as fixed but it still doesn't work.
Mgazul answered on 28 Feb 2020 "I'll check again later."
https://discordapp.com/channels/311256119005937665/615256015704948808/682954280675835941

_3.-  [1.12.2 - 20a5bb5] NetherEX Issue #144_
Diamondman121314 opened this issue on 15 Mar 2020
Status as of 10/05/2020: Open
CraftDream commented on 16 Mar 2020: "Waiting for fix" 

**From our own tests:**
_Tested with Dawgun._
1.- NetherEx-1.12.2-2.0.15 works properly on Mohist-7464a42  [Build [#204]](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/204/)
Generate ores, biomes, mobs, villages and villagers.

2.- NetherEx-1.12.2-2.0.15 doesn't work properly on Mohist-d3c98c9
Doesn't generate ores, biomes neither mobs but generate NetherEX villages and  NetherEX villagers.

_Latest tests_
3.- NetherEx-1.12.2-2.1.6.jar works on Forge 1.12.2 -14.23.5.2847  
(Tested today 10/05/2020)

4.- NetherEx-1.12.2-2.1.6.jar doesn't works on Mohist-1.12.2-d64fc79-server.jar [Build [#507]](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/507/)

- No ores, biomes, mobs and other structures generated. Generates NetherEX villages and  NetherEX villagers.
- Mobs and ores can be spawned in creative mode.
(Tested today 10/05/2020)

**Mod Info :**
Mod NetherEX https://www.curseforge.com/minecraft/mc-mods/netherex
Total Downloads as of 10/05/2020: 8.561.093

NetherEx-1.12.2-2.1.6.jar (Last released version issued on 07/05/2020)
Relations: LibraryEx-1.12.2-1.1.3.jar (Last released version issued on 07/05/2020)
https://www.curseforge.com/minecraft/mc-mods/libraryex/files/2950203

Thank you in advance for fixing this issue as soon as posible.

Kind regards.

**Comment by BCNGAMER** [comment]
I don't know if following info could be useful for your dev team.

 **Mohist-7464a42 Build [[#204]](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/204/)**

As I said before this build works fine.
NetherEX config folder and required .json files are stored into:

![imagen](https://user-images.githubusercontent.com/65110799/81506466-cbfa2580-92f6-11ea-8757-a9b9a63f4134.png)
-
![imagen](https://user-images.githubusercontent.com/65110799/81506545-60fd1e80-92f7-11ea-9488-da1432d8aca4.png)
-
![imagen](https://user-images.githubusercontent.com/65110799/81506565-8853eb80-92f7-11ea-8970-057b1f09c598.png)
- 
![imagen](https://user-images.githubusercontent.com/65110799/81506577-9f92d900-92f7-11ea-9675-10ef5ecc348d.png)
-
**Forge 1.12.2 -14.23.5.2847 and Mohist-1.12.2-d64fc79-server.jar [Build [#507]](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/507/)**

In both cases the tree files structure is the same
NetherEX config folder contains the same file alone:
![imagen](https://user-images.githubusercontent.com/65110799/81506771-01077780-92f9-11ea-9f27-ef804004468e.png)

All other .json files are now stored in both cases into world folder:

![imagen](https://user-images.githubusercontent.com/65110799/81506883-b89c8980-92f9-11ea-8fae-b373eca38cb0.png)

I don't know if this difference between paths could be related with Mohist early builds manage properly this mod and later builds can't. Seems that later builds don't get biomes json files despite they exist into the above mentiones folders.

Please don't flame me, I've no Java idea.

Kind regards.

**Comment by Forbidden-A** [comment]
Catserver fixed it, maybe ask the dev how they did that? They have a little discord server

**Comment by EverNife** [comment]
Mohist have a config called `autounloadWorld_whitelist`
By default has the 3 vanilla DIMs, try to remove the nether one (-1)
```
forge:
  ...
  autounloadWorld_whitelist:
  - 0
  - 1
```
