### ISSUE TITLE
【1.20.1】皮革盔甲染色bug

### ISSUE THREAD

**Issue by XiongGaPuo** [Teneted/Tenet#2850]
使用版本: mohist-1.20.1-512-server
测试环境: 无MOD 无插件 纯净mohist端
漏洞描述:
         染色的皮革盔甲 进行交互 
         如:点击 右键穿戴 被攻击后 
         染色皮革盔甲 会回无染色盔甲

这个BUG会导致 使用MC原版染色皮革甲 
更换盔甲纹理的插件无法正常使用
如: itemsadder oraxen 

以下图片操作: 将物品栏的染色盔甲 拖动到背包格 

![IQ27W4%R~R~EM(PMPL)_{PR](https://github.com/MohistMC/Mohist/assets/53654069/54f01f51-82a0-4f71-93ff-9a6a157d1ec3)
![$EMTQ2G)U$PJ @(29Q(H2 U](https://github.com/MohistMC/Mohist/assets/53654069/54d9b0f5-acc8-4fb0-bd30-42576ac553f6)
![GCHL6VH26 7Y E2387II%JM](https://github.com/MohistMC/Mohist/assets/53654069/21fd0c83-dcf6-4f52-bc12-3cd84a0bc20d)

**Comment by wdkoij** [comment]
請問這個情況已經修復好了嗎？
