### ISSUE TITLE
[1.20.1] Typewriter插件不能加载

### ISSUE THREAD

**Issue by 5ur3z** [Teneted/Tenet#2853]
**Minecraft Version :**1.20.1

**Mohist Version :** 513

**Operating System :** Windows11

**Concerned mod / plugin** : Typewritter
https://modrinth.com/plugin/typewriter
https://gabber235.github.io/TypeWriter/docs/first-interaction

**Logs :** https://haste.mohistmc.com/ufefijiyoq.sql

**Steps to Reproduce :**
进入游戏，输入/typewritter connect客户端无效
后台报错

**Description of issue :** Give all details about your issue
注意：这是一个纯paper插件，希望提供支持

**Comment by Unitei-Dev** [comment]
он не будет работать, в плагине онли Paper
