### ISSUE TITLE
[1.20.1] IridiumSkyblock放置模组方块报错

### ISSUE THREAD

**Issue by 3186418613** [Teneted/Tenet#2857]
Minecraft Version :1.20.1
Mohist Version :mohist-1.20.1-514-server
Operating System :Windows 11 22H2
Concerned plugin : IridiumSkyblock-4.0.8 https://www.spigotmc.org/resources/iridium-skyblock-1-13-1-20.62480/
Logs :https://mclo.gs/jHFVTAb
Steps to Reproduce :在空岛上放置任意模组方块
Description of issue :使用IridiumSkyblock插件创建岛屿后放置模组方块报错

**Comment by Mgazul** [comment]
IridiumSkyblock does not support mod blocks
