### ISSUE TITLE
Attempted to send a Plugin Message to a channel that was too large

### ISSUE THREAD

**Issue by shenniko** [Teneted/Tenet#2864]
**Minecraft Version :** 1.20.1

**Mohist Version :** 503

**Operating System :** windows server 2019

**Logs :** https://gist.github.com/shenniko/4cda0bea11b6b3265ea2a726bc7c84cc
                https://gist.github.com/shenniko/76fb3a584e5397e9f34fc84bbabc98a1

**Startup Script:** https://haste.mohistmc.com/usariyigel.sql

**Mod list :** https://www.modpackindex.com/modpack/64056/all-the-mods-9-atm9
ATM9 Modpack (there are about 400 mods in the list)

**Plugin list :** None

**Description of issue :** When player connects gets below error:
[14:44:12] [Server thread/ERROR] [net.minecraft.server.network.ServerGamePacketListenerImpl]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 67 - 'gravitationalmodulatingunittweaks:gravitationalmodulatingunittweaks.

**Comment by shenniko** [comment]
I've even changed the startup script to a more simpler version:

set JAVA_MCSS="C:\Program Files\Java\jdk-21\bin\java.exe"
@echo off
%JAVA_MCSS% -Xms4G -Xmx20G -Dpaper.maxCustomChannelName=80 -jar mohist-1.20.1-503-server.jar -nogui

Still getting the below error:

[15:23:57 ERROR]: Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 64 chars (attempted 67 - 'gravitationalmodulatingunittweaks:gravitationalmodulatingunittweaks.

**Comment by Mgazul** [comment]
The version of mohist you are using is too low. This issue has been fixed in newer versions
