### ISSUE TITLE
[1.20.2] Item display NBT clears upon moving in inventory

### ISSUE THREAD

**Issue by Shmeeb** [Teneted/Tenet#2867]
**Minecraft Version :** 1.20.2

**Mohist Version :** mohist-1.20.2-126-server.jar

**Operating System :** Windows 10

**Mod list :** None

**Plugin list :** None

**Description of issue :** When I move a piece of colored leather armor in my inventory, the color immediately disappears (https://gyazo.com/756a0c556abf9eb923228b6a111bc34e). This doesn't happen on pure forge.

**Comment by Shmeeb** [comment]
Could you link the other issue please? I can't seem to find it

**Comment by Mgazul** [comment]
Fixed
