### ISSUE TITLE
[1.20.1] Critical injection failure

### ISSUE THREAD

**Issue by raimu-music** [Teneted/Tenet#2872]
**Minecraft Version :** 1.20.1

**Mohist Version :** Hyrbrid Mohist 1.20.1 #343

**Operating System :** OS Big Sur

**Concerned mod / plugin** : Apotheosis & dependencies (Patchouli, Placebo, Aphotic Attributes)

**Logs :** https://gist.github.com/raimu-music/c2a729e7c5d4ccab03ef94bb18ff2d4d

**Steps to Reproduce :**
 1. Install Apotheosis
 2. Start Server
 3. Enjoy the loophole of crash-restart

**Description of issue :** As written above, I can't even log in the server anymore, it doesn't fully complete the start process because of that "Slime" critical injection failure.
It seemed similar to #2627 but probably not the same exact problem since it's still around!

Thank you in advance!

**Comment by Mgazul** [comment]
The mohist version is too low and is not supported
