### ISSUE TITLE
Feature request: Call every events with try-catch block

### ISSUE THREAD

**Issue by Dymeth** [Teneted/Tenet#2876]
**Is your feature request related to a problem? Please describe.**
A lot of plugins and mods can throw any exceptions in events.
For example:
![image](https://github.com/MohistMC/Mohist/assets/21080646/4ee68c3e-27ed-412a-9525-bf19ae7da853)
Full crash-report: https://pastebin.com/raw/dJqeuhw6

**Describe the solution you'd like**
It is vital for Mohist to prevent server crashes when exceptions throws in events. 

**Additional context**
I am not a user of Mohist. However, I observed the problem in the screenshot above, so I thought it was important to report this information so that the project can significantly improve its stability.

**Comment by Mgazul** [comment]
This requires modifying the eventbus, which is not our job
