### ISSUE TITLE
[崩溃]加载Connector相关模组时崩溃

### ISSUE THREAD

**Issue by Tollainmear** [Teneted/Tenet#2881]
**Minecraft Version :** 1.20.1

**Mohist Version :** B515

**Operating System :** Win10

**Logs :** [{崩溃日志}](https://gist.github.com/Tollainmear/83be43b61d8a8d77fadd386bcdc0e201)

**Mod list :** 
- ConnectorExtras-1.9.0+1.20.1
- Connector-1.0.0-beta.32+1.20.1
- fabric-api-0.91.0+1.10.4+1.20.1

**Plugin list :** none

**Description of issue :** 
ummmm，简而言之，我尝试在Mohist上通过Sinytra Connector加载Fabric模组，这听起来似乎有些离谱，但它确实能在客户端环境中完美运行。。。

我成功的在客户端环境中加载了FootSteps、BetterEnd和BetterNether这些Fabric模组，其中BetterEnd模组很大很复杂，却能完美运行，但当我将相同的模组拷贝到Mohist服务端之后，它便在启动的时候崩溃了，经过排查，我发现当Mohist加载这三个模组的时候就会崩溃(它理应正常工作)，我知道这种情况很特殊，但如果Mohist能支持这种骚操作，那简直是太棒了！

附上几张让人惊艳的BetterEnd/Nether的自然结构：
![0d58e16df17610e20187fdc3d2b61a5d](https://github.com/MohistMC/Mohist/assets/25898067/7d330929-c354-4e31-96d3-fac396642091)
![74b32a76b5acd73ec6030a73e0258c93](https://github.com/MohistMC/Mohist/assets/25898067/3799b127-4fa9-4828-a2a0-daebef22626c)
它确实很棒对吧~

**Comment by Tollainmear** [comment]
@Mgazul hi 墨佬，我尝试在QQ上给你留言，但我不确定你是否看到了它，所以我觉定在这里问一下：上面所描述的这个兼容性问题是否在未来的开发计划中，以及你认为这个问题是否容易处理呢？

**Comment by HowardZHY** [comment]
不兼容由ConnectorExtras导致
Incompatible with ConnectorExtras

**Comment by Mgazul** [comment]
使用最新構建再次測試，謝謝

**Comment by HowardZHY** [comment]
> 使用最新構建再次測試，謝謝

@Mgazul https://mclo.gs/NT2j0fO

**Comment by Tollainmear** [comment]
> 使用最新構建再次測試，謝謝

测试了B521(551)还是会崩溃。

基本信息：
[23:06:23 INFO]: Mohist: 1.20.1-551
[23:06:23 INFO]: Forge: 47.2.20
[23:06:23 INFO]: NeoForge: 47.2.20
[23:06:23 INFO]: Bukkit: 997de31d
[23:06:23 INFO]: CraftBukkit: ddc9a2dad
[23:06:23 INFO]: Spigot: d2eba2c8

Connect版本：
ConnectorExtras-1.9.2+1.20.1.jar
fabric-api-0.91.0+1.10.5+1.20.1.jar
Connector-1.0.0-beta.32+1.20.1.jar

下面是日志：
https://mclo.gs/n1ttQzE

**Comment by Mgazul** [comment]
该问题无法修复，可以期待未来的内置Fabric(直接在mohist安装fabric mod，无需安装Connector)

**Comment by Tollainmear** [comment]
> 该问题无法修复，可以期待未来的内置Fabric(直接在mohist安装fabric mod，无需安装Connector)

好耶，乐观的话，大概啥时候能用上

**Comment by HowardZHY** [comment]
Really completed?

**Comment by Mgazul** [comment]
> Really completed?

Yes
