### ISSUE TITLE
Cannot pickup anything in latest build 1.19.2 No.94

### ISSUE THREAD

**Issue by zhaodice** [Teneted/Tenet#2884]
**Minecraft Version :** 1.19.2

**Mohist Version :** https://ci.codemc.io/job/MohistMC/job/Mohist-1.19.2/lastBuild/ at No.94 (Sat Jan 06 12:15:31 UTC 2024) 

**Operating System :** Linux

**Logs :** no

**Mod list :** empty

**Plugin list :** empty

**Description of issue :** 

When I download the latest build https://ci.codemc.io/job/MohistMC/job/Mohist-1.19.2/lastBuild/ at No.94 (Sat Jan 06 12:15:31 UTC 2024)  , I found I cannot pickup anything even no mods, no plugins loaded.

**Comment by ArtuKILL** [comment]
Anyone knows about an "stable" minecraft 1.19.2 mohist release?

All versions that I tested seems buggy or at some point crashes the server.

**Comment by killer2gudpl** [comment]
> Anyone knows about an "stable" minecraft 1.19.2 mohist release?
> 
> All versions that I tested seems buggy or at some point crashes the server.

I know it does not help, but if you were inclined to move onto 1.20.1, then please do.

Much more stable and able to run a server with 250 mods quite happily.

**Comment by NoRestForWicked** [comment]
I have the same issue, but there seems to be no fix? Another issue that follows along side with this is that upon taking damage I will regenerate instantaneously after a second or 2. Straight back to full. Also my hearts always get set back to 10, even if I manually remove them.

**Comment by highesttt** [comment]
I know this was marked as completed but I am having the same issue with version 142 and 144...
