### ISSUE TITLE
[1.20.1] Mohist block-break event handling potentially ignores results of Forge events that have canceled the block break

### ISSUE THREAD

**Issue by raimu-music** [Teneted/Tenet#2885]
**Minecraft Version :** 1.20.1
 
**Mohist Version :** #517

**Operating System :** OS

**Concerned mod / plugin** : Lootr (https://www.curseforge.com/minecraft/mc-mods/lootr)

**Logs :** There's no logs about the error

**Steps to Reproduce :**
 1. Edit the config file of lootr so that "lootr chests are unbreakable unless crouching in creative" 
 2. Try to break a lootr chest
 3. The chest breaks without even crouching nor being in creative :(

**Description of issue :** As explained above; I tried asking in Lootr Discord and noobandius suggested me the title & the string that may be causing this ( https://github.com/MohistMC/Mohist/blob/6e1ef8bc331b0c162a24d16efd20ff246e5ccf01/src/main/java/com/mohistmc/eventhandler/dispatcher/BlockEventDispatcher.java#L81 )

**Comment by raimu-music** [comment]
Edit: it turns out it all comes back to the file rejecting the new config file of Lootr and reverting it to its original state.

09.01 16:09:47 [Server] WARN Configuration file /config/lootr-common.toml is not correct. Correcting

D:

**Comment by raimu-music** [comment]
Further warn message from console:
https://gist.github.com/raimu-music/11a8fa8aad09c547b755b346d681c846

**Comment by raimu-music** [comment]
Last Update: 
Was going to do another test today so I back-uped the current config file and with surprise I realized that it HAS indeed saved the 'true' on disablebreakunlesscreative, even if when the server was crashing I thought I re-uploaded the backup version with the breakunlesscreative event still set to 'false'. 

I get no more errors in the console even if I re-start the server with this config file but, despite that, being not in creative, non op, non crouching, I am still able to break lootr chests. 

The problem is that now it seems like even the normal 'warn' is not active and so anyone would be able to break chests without even getting the warn about loosing the loot for them/everyone else 😅 ..
I get the 'lootr and container carts cannot be broken' warn instead of 'you should crouch to break --> you'll loose all content'

Current config file: 
https://gist.github.com/raimu-music/075b496fd04179fb25ade7322a01383b

If I delete the config file and have the server create a new one (disable-unless-creative: false). I still can break any chests without crouching, while getting the correct warn message even if the chests are already broken.
This behavior is new as in #343 with the value set to 'false' I wasn't able to break unless crouching, as the mod is intended to behave!

**Comment by Mgazul** [comment]
Fixed
