### ISSUE TITLE
[1.20.1] Supplementaries 问题

### ISSUE THREAD

**Issue by wlm1455925277** [Teneted/Tenet#2886]
**Minecraft Version : 1.20.1

**Mohist Version : mohist-1.20.1-517-server

**Operating System : winserver 2019 x64

**Concerned mod / plugin :  supplementaries-1.20-2.7.22 | moonlight-1.20-2.8.81-forge

**Logs : https://mclo.gs/yQDgyYV

**Steps to Reproduce : 
 1. 当我使用 Velocity 代理 Mohist 并给予玩家 op 权限时
 2. 会直接踢出！
 3. 并显示 wlm123 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Registry moonlight:map_markers not found

**Description of issue : 
When I use Velocity to proxy Mohist and give the player op permission, he will be kicked out of the game!

wlm123 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: Registry moonlight:map_markers not found

**Comment by darksoon** [comment]
hey,

had the same error, for me this velocity plugin works perfekt:
https://github.com/adde0109/Ambassador

greetings

**Comment by wlm1455925277** [comment]
> 嘿，
> 
> 有同样的错误，对我来说这个速度插件工作得很好： https: [//github.com/adde0109/Ambassador](https://github.com/adde0109/Ambassador)
> 
> 问候

Thank you
