### ISSUE TITLE
[1.20.2] Seems whitelist mods section doesn't work with Velocity

### ISSUE THREAD

**Issue by SimonMage** [Teneted/Tenet#2887]
**Minecraft Version :** {1.20.2}

**Mohist Version :** {131}

**Operating System :** {Linux}

**Logs :** {
![Screenshot_1](https://github.com/MohistMC/Mohist/assets/75200996/072af097-82c0-4bd4-9dab-f73faa663d2a)
![Screenshot_1](https://github.com/MohistMC/Mohist/assets/75200996/50b8a813-3182-43d1-821d-16c6e0fb4e4e)
![Screenshot_2](https://github.com/MohistMC/Mohist/assets/75200996/c163d443-4108-4581-ad7e-617d9f6a69c2)
}

**Mod list :** {Pixelmon 9.2.5}

**Plugin list :** {Tested on blank server}

**Description of issue :** {seems the whitelist mods section doesn't work with your Velocity version, I added all the mods that I have in my client and the server kicks me telling me that I have some mods not whitelisted but it's impossible because I literally added the same mods that /mohist playermods told me}

**Comment by Not-Config** [comment]
How did you manage this task?
