### ISSUE TITLE
[1.20.1] LWC / Bolt plugin not working

### ISSUE THREAD

**Issue by killer2gudpl** [Teneted/Tenet#2897]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-551

**Operating System :** Windows 10 22H2

**Concerned mod / plugin** : Both LWC (https://www.spigotmc.org/resources/lwc-extended.69551/) and Bolt (https://www.spigotmc.org/resources/bolt.109679/) affected.

**Logs :**  https://pastebin.com/cGkHLyJ5

**Steps to Reproduce :**
 1. Add Bolt or LWC plugin to your mohist server
 2. Launch the server
 3. Issue occures preventing the plugin from loading.

**Description of issue :** The plugin is a chest locking plugin (as well as LWC), which does not work when under Mohist. Tested with Paper and the issue does not occur there. The issue with Mohist occures even when there are no mods or plugins installed apart from the affected plugin. I would appreciate any help! Thank you.

**Comment by LiteCat0905** [comment]
1.18.2遇到了相同的问题！

**Comment by killer2gudpl** [comment]
Fixed by  https://github.com/MohistMC/Mohist/commit/717c521959b456cbd652270f7248f5aabdba2138 in 1.20.1
@LiteCat0905 you may want to create another issue, referencing this one but for 1.18.2.

Thanks @Mgazul !
