### ISSUE TITLE
[1.20.1] 0.3.0+ versions of Canary don't work.

### ISSUE THREAD

**Issue by killer2gudpl** [Teneted/Tenet#2898]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-551

**Operating System :** Windows 10 22H2

**Concerned mod / plugin** : Canary 0.3.0+ https://www.curseforge.com/minecraft/mc-mods/canary

**Logs :** https://pastebin.com/fpR8JtXV

**Steps to Reproduce :**
 1. Download 0.3.0 or 0.3.0+ version of Canary
 2. Wait until world loading
 3. Server crash occurs upon first tick.

**Description of issue :** The issue occurs with 0.3.0+ versions of Canary, but does not on older ones. 0.3.0 introduced some chunk ticking optimizations, perhaps being an issue there, albeit the error points to a different problem. The problem occurs even when Canary is the only mod present with no plugins.

**Comment by killer2gudpl** [comment]
A major clue would be:

java.lang.NoClassDefFoundError: net/minecraft/server/level/DistanceManager

Can confirm it does not work still with 1.20.1-567

**Comment by Mgazul** [comment]
Fixed
