### ISSUE TITLE
BlockFormEvent may only be triggered synchronously

### ISSUE THREAD

**Issue by Alekuso** [Teneted/Tenet#2899]
**Minecraft Version :** 1.16.5

**Mohist Version :** 134

**Operating System :** Ubuntu 22.04.3 LTS

**Logs :** https://pastebin.com/0na0H0LQ

**Mod list :** AI-Improvements-1.16.5-0.5.0 , AmbientSounds_v3.1.11_mc1.16.5, appleskin-forge-mc1.16.x-2.5.1, Aquaculture-1.16.5-2.1.23, bendy-lib-forge-1.2.1, BetterThirdPerson-Forge-1.16.4-1.9.0, cfm-7.0.0pre22-1.16.3, cloth-config-4.17.101-forge, collective-1.16.5-5.49, connectivity-2.4-1.16.5, 
corpse-1.16.5-1.0.6, CreativeCore_v2.2.1_mc1.16.5, DiagonalFences-v1.1.1-1.16.5, Disenchanting-forge-1.16.5-1.7.2, doubledoors_1.16.5-3.3, embeddium-0.2.17+mc1.16.5, emotecraft-for-MC1.16.5-2.2.5-forge, Fallingleaves-1.16.3-1.2.4, FarmersDelight-1.16.5-0.6.0, FastFurnace-1.16.5-4.5.0, FastSuite-1.16.4-1.1.1, FastWorkbench-1.16.5-4.6.2, ferritecore-2.1.1-forge, FramedBlocks-2.16.3, Iceberg-1.16.5-1.0.45, inventorysorter-1.16.1-18.1.0, Jade-1.16.4-2.8.3, jei-1.16.5-7.8.0.1009, journeymap-1.16.5-5.8.5p6, konkrete_forge_1.6.1_MC_1.16.2-1.16.5, kotlinforforge-1.17.0-obf, Ksyxis-1.2.2, lazydfu-0.1.3, libraryferret-forge-1.16.5-4.0.0, loadmyresources_forge_1.0.4_MC_1.16.2-1.16.5, lootr-1.16.5-0.2.18.49, mcw-bridges-2.1.0-mc1.16.5forge, mcw-doors-1.1.0forge-mc1.16.5, mcw-fences-1.0.7-mc1.16.5forge, mcw-lights-1.0.6b-mc1.16.5forge, mcw-roofs-2.2.4-mc1.16.5forge, modernfix-forge-5.11.1+mc1.16.5, morevanillaarmor-1.16.4-1.2.6, MouseTweaks-2.14-mc1.16.2, MyServerIsCompatible-1.16.5-1.0, Paxi-Forge-1.16.4-1.0, Pixelmon-1.16.5-9.1.10-universal, Placebo-1.16.5-4.7.1, plasmovoice-forge-1.16-1.2.19, player-animation-lib-forge-0.4.0+1.16.5, PlayerRevive_v2.0.0-pre04_mc1.16.5, Prism-1.16.5-1.0.1, PuzzlesLib-v1.0.15-1.16.5-Forge, saturn-mc1.16.5-0.0.3, SkyVillage_1.0.0_1.16.5, sophisticatedbackpacks-1.16.5-3.15.20.755, StorageDrawers-1.16.3-8.5.2, YungsApi-1.16.4-Forge-13

**Datapack list :** william-wythers-overhauled-overworld-for-1-16-5

**Plugin list :** tabtps-spigot-1.3.21

**Description of issue :** I'm getting a crash because of `BlockFormEvent may only be triggered synchronously` that has been triggered by some players going at some certain coordinates. From what I've seen, I've kinda fixed this issue temporary when I changed someone's location from ~10K blocks away from spawn back to 0, 0. But now it has been happening again with a player only about 4K blocks away from spawn. I've searched about this error before and couldn't find anything about it

**Comment by Mgazul** [comment]
Fixed
