### ISSUE TITLE
Краш при запуске сервера с 1 модом

### ISSUE THREAD

**Issue by Maks-Haswell** [Teneted/Tenet#29]
При запуске чистого сервера Mohist-1.7.10 #36 с модом MalisisDoors и MalisisCore крашит сервер при запуске поэтому прилагаю лог ниже (только проверил что не только с этим модом такая же проблема на Mohist-1.7.10 #36)
https://hastebin.com/nuriwiyusi.rb

**Comment by Mgazul** [comment]
1.7.10 находится в стадии разработки и не рекомендуется для официального использования! Спасибо за отзыв!

**Comment by Maks-Haswell** [comment]
а фикс данной ошибки будет?
