### ISSUE TITLE
[1.19.2] Unable to pick any items up #97

### ISSUE THREAD

**Issue by djoveryde** [Teneted/Tenet#2902]
**Minecraft Version :** 1.19.2

**Mohist Version :** 97

**Operating System :** Windows 11

**Concerned mod / plugin** : No mods/plugins

**Logs :** No errors show up on console

**Steps to Reproduce :**
 1. Break a tree.
 2. Log just sits floating in front of you.

**Description of issue :** For some reason I am unable to pick anything up, I can break trees/blocks, but they just sit floating in front of me.

**Comment by YisuiDenghua** [comment]
The bug is also reproducible on my server.

**Comment by Zapzatron** [comment]
Same problem on version 99, have you found a working version?

**Comment by Mgazul** [comment]
#2884
