### ISSUE TITLE
java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by Alekuso** [Teneted/Tenet#2903]
**Minecraft Version :** 1.16.5

**Mohist Version :** 140

**Operating System :** Ubuntu 22.04.3 LTS

**Logs :** https://pastebin.com/k5YTcPGz

**Mod list :** Same as in #2899 

**Plugin list :** Chunky-1.3.92, CoreProtect-22.2, images-2.3.2, tabtps-spigot-1.3.21

**Description of issue :** Looks like an issue after #2899 got fixed, same instructions to do the error

**Comment by Mgazul** [comment]
Fixed
