### ISSUE TITLE
[1.20.2] Plugin configuration chat issue

### ISSUE THREAD

**Issue by DoZysGuy** [Teneted/Tenet#2913]
**Minecraft Version :** 1.20.2

**Mohist Version :** 1.20.2-134

**Operating System :** Debian

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** DeluxeCombat v1.60.2

**Description of issue :** 
There is an issue when the plugin wait an answer from the chat to change the config. For example, on the deluxecombat menu I can select at which percentage the head of player can drop, then I have to hit the number on the chat but nothing is happening when I enter. And I'm stuck on chat because the plugin wait a response. 
I can't configure the plugin, all the configuration is with the GUI.

I don't have any error on console.

I tried on a 1.20.2 paper server and it's working

Also I had the same issue with the plugin Quest 5.0.0-rc.3 and QuestGUI 1.5

**Comment by Meidde** [comment]
I have the same problem, where is the support or Dev?? this is much important , for create Quests with plugin
