### ISSUE TITLE
[1.20.1] QuickShop-Hikari不兼容

### ISSUE THREAD

**Issue by windy664** [Teneted/Tenet#2914]
**Minecraft Version :** 1.20.1

**Mohist Version :** 552

**Operating System :**win10

**Concerned mod / plugin** : QuickShop-Hikari

**Logs :** Link(s) of logs and crash reports if you have

https://pastebin.com/hrb5GXGV

**Steps to Reproduce :**
 1. Do this
 2. Then do that
 3. ...

**Description of issue :** Give all details about your issue

**Comment by Teena-ger** [comment]
Fixed
