### ISSUE TITLE
[崩溃]一些和worlds模块相关的问题

### ISSUE THREAD

**Issue by Tollainmear** [Teneted/Tenet#2917]
**Minecraft Version :** 1.20.1
**Mohist Version :** B525
**Operating System :** Win10
**Logs :** 
崩溃日志：https://gist.github.com/Tollainmear/3ef662e1c020dea0224c4b463988bd52
崩溃时控制台输出：https://gist.github.com/Tollainmear/c62511350ece760eb9a883747c01496d

**Mod list :** 
* TFC 3.1.6
* Patchouli 84

**Plugin list :** 
可以没有

**Description of issue :** 
在搭载了TFC的Mohist服务器上使用/worlds指令创建原版世界会在重启后，因加载/生成区块而导致崩溃，复现方法如下：

1. 搭载TFC并启动Mohist
2. 使用/worlds create指令创建原版世界
3. 重启服务端
4. 进入游戏后，传送至重启前创建的原版世界
5. 服务端崩溃

**一些关于Worlds模块的其他问题：**

1. 创建世界时不支持mod提供的生成器(但是可以通过单机创建世界并使用/worlds import指令导入，导入后，会按照mod的世界类型生成新区块)
2. /worlds delete指令无效，使用后，只会卸载对应世界，就算在关闭服务器后手动删除对应的文件，在重启后，对应世界仍然会被重新生成并加载
3. 下届、末地的世界边界会在重启后，被主世界覆写，即mohist文件夹下的world文本内描述下届、末地边界大小的数据，会在重启后被主世界的边界值所覆盖

**问题追踪**
https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2624#issuecomment-1916853515

![210b2158c341b6b302de63618055e7f9](https://github.com/MohistMC/Mohist/assets/25898067/3612a69d-7c39-44b8-be9e-4b5779e419be)

**Comment by Mgazul** [comment]
第二個已修復
