### ISSUE TITLE
[1.16.5] Cannot light Nether portal in vanilla Mohist.

### ISSUE THREAD

**Issue by DesolateIntention** [Teneted/Tenet#2920]
**Minecraft Version :** 1.16.5

**Mohist Version :** 1.16.5-1215

**Operating System :** Linux (amd64) version 5.15.0-91-generic | Java Version: 16.0.2

**Logs :** https://gist.github.com/DesolateIntention/ede9485745b9408a2d57c152a27cee94

**Mod list :** None.

**Plugin list :** None.

**Description of issue :** I previously used [BetterPortals](https://www.curseforge.com/minecraft/mc-mods/betterportals), a mod which disables the Nether portals and only allows players to enter the Nether via a new, randomly generated, portal in the bottom of the world. After removing all of my mods and plugins, I still cannot use the Nether portals. I deleted the world folder, and made sure `allow-nether` was set to `true`, but I still cannot light a portal. I haven't even modified any server config files, so I'm not sure why this is happening.

**Comment by c0derMo** [comment]
I can confirm, this is happening for me on 1.16.5-1220 aswell, both with mods and without mods. However, it works correctly on 1.16.5-1205, so it seems to have broken since then

**Comment by DesolateIntention** [comment]
> I can confirm, this is happening for me on 1.16.5-1220 aswell, both with mods and without mods. However, it works correctly on 1.16.5-1205, so it seems to have broken since then

Had you used BetterPortals, or was this a fresh installation?

**Comment by c0derMo** [comment]
> Had you used BetterPortals, or was this a fresh installation?

I've had this happen on a fresh installation aswell

**Comment by JimmyKungzcs** [comment]
![2024-03-25_01 55 04](https://github.com/MohistMC/Mohist/assets/38184044/4cf9027c-1d52-4109-98bb-5654bdc3dc8f)
I am too.

**Comment by FedorSV** [comment]
I have a same problem on my moded server.
![2024-04-02_18 42 30](https://github.com/MohistMC/Mohist/assets/63013203/d9f84234-8381-4b3f-ba7f-f16502486fca)

**Comment by FedorSV** [comment]
Sorry, just tried on 1223 version, everything is good

**Comment by Mgazul** [comment]
Fixed
