### ISSUE TITLE
[1.20.1] FAWE Error

### ISSUE THREAD

**Issue by SaGye9816** [Teneted/Tenet#2932]
**Minecraft Version :** 1.20.1

**Mohist Version :** 570

**Operating System :** Window

**Concerned mod / plugin** : FastAsyncWorldEdit-Bukkit-2.8.5-SNAPSHOT-651

**Logs :** Link(s) of logs and crash reports if you have
[https://pastebin.com/kT07KY40](url)

**Steps to Reproduce :**
 1. Do this
 2. Then do that
 3. ...

**Description of issue :** Give all details about your issue

**Comment by Mgazul** [comment]
This is not mohist's problem, fawe didn't consider the mods block
