### ISSUE TITLE
[1.19.2]版本客户端无法拾取任何物品

### ISSUE THREAD

**Issue by Alirea10** [Teneted/Tenet#2942]
使用版本：
mohist-1.19.2-100-server.jar
mohist-1.19.2-99-server.jar
问题：
无法在游戏内拾取任何掉落物
复现环境：
使用上述版本开启服务器。不使用任何plugin和mods，并用安装了forge并且没有mods的客户端本地0登录
出生后挖一个泥土或者其他任何东西都挖不起来，离远一点也不行

**Comment by ghost** [comment]
原版服务端自带出生点保护，需要op权限才能编辑出生点范围的所有事物

**Comment by Mgazul** [comment]
> 离远一点也不行

注意审题：离远一点也不行

**Comment by ghost** [comment]
我是傻逼（

**Comment by ghost** [comment]
我承认我最近精神状态太好了

**Comment by Alirea10** [comment]
> 原版服务端自带出生点保护，需要op权限才能编辑出生点范围的所有事物

虽然但是，出生点保护也没听说过不能捡东西好像只是不能挖

**Comment by Alirea10** [comment]
> 原版服务端自带出生点保护，需要op权限才能编辑出生点范围的所有事物

顺便补充一下，我已在op状态下也不能捡起来

**Comment by ghost** [comment]
> > 原版服务端自带出生点保护，需要op权限才能编辑出生点范围的所有事物
> 
> 顺便补充一下，我已在op状态下也不能捡起来

我的问题，我没看题（）

**Comment by LiteCat0905** [comment]
遇到了，请问有解决办法了吗！？

**Comment by SYSTEM-PEACE** [comment]
没，这版本bug可多了

**Comment by SYSTEM-PEACE** [comment]
> 遇到了，请问有解决办法了吗！？

没，这版本bug可多了

**Comment by YeiJ** [comment]
我在101版本也遇到了这个问题 不知道什么时候能修复

**Comment by Mgazul** [comment]
Fixed
