### ISSUE TITLE
CraftToExile2 start issue

### ISSUE THREAD

**Issue by Qblolz** [Teneted/Tenet#2947]
**Minecraft Version :1.20.1

**Mohist Version :mohist-1.20.1-546

**Operating System :win11

**Logs: https://mclo.gs/sxbilWN

**Mod list : listed in log

**Plugin list : -

**Description of issue : trying run latest version https://www.curseforge.com/minecraft/modpacks/craft-to-exile-2 (0.5.0 - server pack)
temp link (from CTE2 discrod)
https://drive.usercontent.google.com/download?id=15mvFaYtH7sq49EwwUFJ3hfruniRXx0A4&export=download&authuser=0
also bug with 0.4.1 version

**Comment by Mgazul** [comment]
remove neruina mod https://github.com/Bawnorton/Neruina/issues/37
