### ISSUE TITLE
[1.20.1] Citadel breaks ModelEngine's Behaviors.

### ISSUE THREAD

**Issue by rafucuk** [Teneted/Tenet#2956]
If meg (model engine) used with citadel bone behaviors breaks I think;

- Breaking model nametag and mount system
- Lags server

![image](https://github.com/MohistMC/Mohist/assets/33981808/05639abb-564c-4108-bbe0-12ee55ad0a69)
nametag and mount point bones are not syncing with mob model;

![image](https://github.com/MohistMC/Mohist/assets/33981808/ecd2cdd8-edda-4410-91c2-e626e52d3002)
![image](https://github.com/MohistMC/Mohist/assets/33981808/4898669a-24b2-4e82-987f-dac1b9115083)

Without citadel it works fine as expected, no logs nothing to provide.

**Comment by Skeletron72** [comment]
can confirm this error

**Comment by Unitei-Dev** [comment]
Это не как не пофиксить, ибо как сказал разработчик CItadel, переделайте мои моды и уберите мои Entity и делайте свои как вам будет удобнее, хотя в Citadel не вижу ничего и крутого как и моды которые поддерживают его, ибо в Meg 4 сейчас можно сделать точно так же )
