### ISSUE TITLE
[1.18.2] 世界维度异常

### ISSUE THREAD

**Issue by LiteCat0905** [Teneted/Tenet#2958]
**What is your question ?**
我将所有的MOD全部去掉了
世界维度异常，
EssentialsX插件我无法使用 /warp /home /back 之类的命令， 他会给你传送到同一坐标的末地去(正确应在主世界) 
CMI 使用/home 直接提示世界不存在
我通过 /cmi world 命令直接进入了末地，打完了龙出传送门，进去还是在末地                                              
非常需要/back 这个功能 请问有没有合适的方法修复啊！

**Comment by HalfSnowCN** [comment]
我的image citizens liteteleport(和essentials功能一样)插件也出现了这问题，第一次是变成了末地，重新安装之后又到了下界
