### ISSUE TITLE
[1.20.1] Mythic Dungeon failed to create level.dat

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#2978]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-554

**Operating System :** Windows 10

**Concerned mod / plugin** : https://www.spigotmc.org/resources/mythicdungeons.102699/

**Logs :** https://gist.github.com/Talan67/73ac98942e9a6db5c334a294680ea4dc

**Steps to Reproduce :**
 1. Install Mythic Dungeons and ProtocolLib
 2. Create a dungeon with /md create (dungeon name)
 3. Edit the dungeon with /md edit (dungeon name)
 4. Try build something, leave with /md leave
 5. Try edit it again and nothing saves

**Description of issue :** With this plugin it stores dungeon worlds seperatly and loads them when prompted either by editing, creation or playing them. The problem is on Mohist the level.dat is either ignored or cannot be made due to incompatibility.

**Comment by Talan67** [comment]
Just wondering, can this be fixed?

**Comment by Talan67** [comment]
https://gist.github.com/Talan67/9655e8d56dac6ab27db4f63854e3b1f1
https://gist.github.com/Talan67/0de72e5a223ffee0c6d651f559f432e7

Heres more logs incase these help, was on my server with a pretty big mod list so there might be a lot of useless text and errors.

**Comment by Talan67** [comment]
[latest.log](https://github.com/MohistMC/Mohist/files/15242377/latest.log)
[debug.log](https://github.com/MohistMC/Mohist/files/15242378/debug.log)

This has changed in the most recent snapshot of Mythic Dungeons, the files generated are not being saved to the plugins directory. Trying to play a dungeon still does not work as there is a loading error upon initiating the /md play [dungeon name] command.

Still holding out hope this gets fixed sooner than later, no rush, thanks.

**Comment by Mgazul** [comment]
Fixed

**Comment by Talan67** [comment]
Theres one last issue, which is probaly the easiest to solve. The instances that get opened close after they have either been completed or left, cause if not you would have hundreds of world folders.

[latest.log](https://github.com/MohistMC/Mohist/files/15277408/latest.log)
[debug.log](https://github.com/MohistMC/Mohist/files/15277409/debug.log)

Besides this everythings works, thank you.

**Comment by nikka10992-alt** [comment]
jo how do i install this mohist version ec77773 ??
i mean theres no java data
