### ISSUE TITLE
What are the parameters for "ignore_empty_time"?

### ISSUE THREAD

**Issue by DesolateIntention** [Teneted/Tenet#2982]
**What is your question?**
What are the parameters for `ignore_empty_time`? I set it to `minecraft:overworld`, but the server crashed when it got to world loading. I then set it to `world`, but it crashed as well. I'm trying to stop the server from loading all the dimensions because it results in huge resource utilization for no reason.

**Comment by Mgazul** [comment]
Provide your crash log

**Comment by DesolateIntention** [comment]
Certainly.
https://gist.github.com/DesolateIntention/0a35ae3dffb2d62cf7e1807151472704

**Comment by DesolateIntention** [comment]
Hey! Thanks for the fix. I am, however, still experiencing the loading of all dimensions. I updated Mohist and set it to `ignore_empty_time: minecraft:overworld`. Why is it loading all dimensions? ![Screenshot_20240412_135005_Termux.jpg](https://github.com/MohistMC/Mohist/assets/63953363/b9ee1f88-d7db-46c7-8e2f-4c858b9d93fb)

**Comment by Mgazul** [comment]
Loading all worlds is the logic of bukkit. Some plugins must ensure that the world has been loaded, otherwise the plugin will fail.
