### ISSUE TITLE
When equiping dyed leather armor it loses color!

### ISSUE THREAD

**Issue by PrograMysT** [Teneted/Tenet#2988]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {596}

**Operating System :** {Windows 11}

**Logs :** {https://mcpaste.io/8c62cd101456433b}

**Mod list :** {Create Mod, Biomes O Plenty, TerraBlender, CreateAddition}

**Plugin list :** {WorldGuard, WorldEdit, Vault. Tab, SkinsRestorer, SimpleScore, SetSpawn, ServerListPlus, ProtocolLib, PlayerKits2, PlaceHolderAPI, NexEngine, LuckPerms, LPC, LightEconomy, Joinleave, ImageFrame, ExcellentCrates, EconomyShopGui, DiscordSRV, DecentHolograms, Citizens 2, ChunkyBorder, Chunky, BlueMap, BetterRTP, Authy, ArmorStandTools}

**Description of issue :** {So when i dye a lether armor peice and i try to equip it it looses color, also happens when i try to duplace it in creative. Please watch the video.}

Video: https://github.com/MohistMC/Mohist/assets/114109438/3b39f6f1-bd68-439f-8a48-e3d8814bdeed

**Comment by Mgazul** [comment]
Duplicate #2850

**Comment by Mgazul** [comment]
Fixed
