### ISSUE TITLE
检测到病毒

### ISSUE THREAD

**Issue by woyaodangrapper** [Teneted/Tenet#2990]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-567-server.jar

**Operating System :** 版本	Windows 11 专业版
版本号	24H2
安装日期	‎2024/‎2/‎29
操作系统版本	26058.1300
体验	Windows Feature Experience Pack 1000.26058.1300.0

**Description of issue :** 不知道
下载地址 ：https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1
下载地址 ： https://adfoc.us/serve/?id=765928102395615

![57ae6892-ab26-4cf8-a858-13384eea09a4](https://github.com/MohistMC/Mohist/assets/38523332/d70f33e4-7fbb-441e-82ce-b647e460198f)

![1CAG`{S9PFC@PP`PN1~A})2](https://github.com/MohistMC/Mohist/assets/38523332/0c21ea3d-1885-40e0-bfb0-23623396f42b)

![H@Z3 Z1ZR46RG8~L{XPTG$V](https://github.com/MohistMC/Mohist/assets/38523332/5fa7e82a-4c21-447a-a0ff-9afd9011dbd6)

**Comment by Dreeam-qwq** [comment]
https://www.virustotal.com/gui/file/0306ad9a6c4d591e6131ac2ae918514c5f2cf6c9181c02071eddf78a3f93d4d4
Windows defender误报

**Comment by woyaodangrapper** [comment]
> https://www.virustotal.com/gui/file/0306ad9a6c4d591e6131ac2ae918514c5f2cf6c9181c02071eddf78a3f93d4d4 Windows defender误报

收到，我将会降级使用至无误报版本，但我希望在下一个版本得到解决。
开发者请主动关闭，该问题后续我不会持续跟踪
