### ISSUE TITLE
[1.20.1] CrazyCrates 1.19+ (plugin) versions do not work properly

### ISSUE THREAD

**Issue by killer2gudpl** [Teneted/Tenet#2991]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-602

**Operating System :** Windows 10

**Concerned mod / plugin** : CrazyCrates 1.19+ versions (https://www.spigotmc.org/resources/crazy-crates.17599/)

**Logs :** https://pastebin.com/zySDMCpV

**Steps to Reproduce :**
 1. Launch server
 2. Join
 3. Get hit by the mob/try to pick up an item from the floor/type /cc as an OP and select something by left clicking
 4. Observe the console and notice errors being spammed.

**Description of issue :** Happens even without any other mods/plugins apart from the one concerned. InventoryCloseEvent, InventoryClickEvent InventoryCreativeEvent do not work and cause the plugin to not work properly. Upon close investigation of source code of the plugin, the plugin calls org.bukkit.inventory.InventoryHolder org.bukkit.inventory.Inventory.getHolder(boolean) with a false value to check something. 

Mohist might have not implemented/pulled changes from paper/spigot that contain such modification? Also, similar issue happens when hit by the mob (org.bukkit.damage.DamageSource org.bukkit.event.entity.EntityDamageEvent.getDamageSource() not being found). However, I have not looked into it. 

PlayerAttemptPickupItemEvent also affected, with'boolean org.bukkit.persistence.PersistentDataContainer.has(org.bukkit.NamespacedKey) event missing.

Would appreciate any help.

Thanks!

**Comment by Mgazul** [comment]
This is a paper plug-in and cannot be used in spigot.

**Comment by killer2gudpl** [comment]
> This is a paper plug-in and cannot be used in spigot.

Fair enough. Thanks!
