### ISSUE TITLE
[1.20.1] Rolled back Inventory

### ISSUE THREAD

**Issue by BazZziliuS** [Teneted/Tenet#2997]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-604

**Operating System :** Linux

**Concerned mod / plugin** : EssentialsX and MyWarp

**Logs :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
Enter another world like hell
Teleport to the warp or at home
Your inventory will roll back

**Description of issue :** The problem is rolling back inventory when teleporting
The usual Minecraft teleport works fine, and inventory is rolled back through plugins

**Comment by sanik** [comment]
Small clarification! To repeat, enter the portal, update your inventory (move a stack or pick up a block) then return to the overworld using the bukkit command and open a crate or stove and your inventory will roll back to its pre-change state. Everything is fine with the vanilla (/minecraft:tp) team!

**Comment by sanik** [comment]
Video on repeating the bug: https://youtu.be/UT1Jc8esXIY
