### ISSUE TITLE
Not compatible with Luohuayu FastWorkbench

### ISSUE THREAD

**Issue by HeberonYT** [Teneted/Tenet#300]
Remove FastWorkbench, or use https://github.com/Luohuayu/FastWorkbench

_Originally posted by @Mgazul in https://github.com/Mohist-Community/Mohist/issues/55#issuecomment-568202343_

**Comment by HeberonYT** [comment]
Hi, I downloaded the FastWorkbench mod as explained in the comment above, but when I start the server the mod disappears and is not in the mods folder.
No matter how many times you put it, it will disappear again and will not load.

**Comment by Mgazul** [comment]
Fixed, https://github.com/Shawiizz/shawiizz.github.io/commit/fd76b7fdc4955de39cc9d1fd9ad4a79296636480
I modified the class recognition

**Comment by HeberonYT** [comment]
Excuse me, where do I get that correction?

**Comment by Mgazul** [comment]
Install Luohuayu FastWorkbench again
