### ISSUE TITLE
1.20.1 The first start works. An error occurs after restarting.

### ISSUE THREAD

**Issue by chillgerne89** [Teneted/Tenet#3008]
**Minecraft Version :**1.20.1

**Mohist Version :** 589 and some before. 

**Operating System :** Nitrado-Gameserver,

**Logs :** https://gist.github.com/chillgerne89/fbd36da90082d2f67de9c55314ef629d

**Mod list :** Error also occurs if no mods are installed.

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** The first start of the server works without any problems. After a restart, an error occurs after "Searching incompatible mods...". Mohist 503 works without this bug.

**Comment by Mgazul** [comment]
Unable to reproduce
