### ISSUE TITLE
[1.20.1] Strange crash caused by bowItem

### ISSUE THREAD

**Issue by Thspooks** [Teneted/Tenet#3018]
**Minecraft Version :** 1.20.1
**Mohist Version :** 597
**Operating System :** pebblehost

**Logs :**  https://mclo.gs/MtmSomX

**Mod list :** included with logs 

**Plugin list :** none atm

**Description of issue :** I updated mohist to 597 from 596, but it seems something else is crashing now. Im not sure what and why

**Comment by Thspooks** [comment]
But if i remove connector extras - https://mclo.gs/AKKlHaw

**Comment by Mgazul** [comment]
Add parameters to your startup script to get more detailed mixin errors```-Dmixin.debug=true```

**Comment by Thspooks** [comment]
> Add parameters to your startup script to get more detailed mixin errors`-Dmixin.debug=true`

https://mclo.gs/CzaU1pc Added, hope it worked

**Comment by Mgazul** [comment]
The parameters have no effect. Try restarting until all information about the mixin appears on the console.

**Comment by Thspooks** [comment]
Then i dont think theres more i can do, i added it to custom startup flags, since pebblehost doesnt allows parameters i think and i dont really have a script since its a hosting site

**Comment by Thspooks** [comment]
Unless its this ? https://mclo.gs/E49L7Lt

**Comment by Mgazul** [comment]
The error comes from a mixin compatibility issue with MC Dungeons Weapons
