### ISSUE TITLE
 How to fix the issue of "Can't run the installation because the minecraft server file doesn't exist!".

### ISSUE THREAD

**Issue by mitac-31709** [Teneted/Tenet#3023]
**Minecraft Version :** 1.20.1
**Mohist Version :** 593

**Operating System :** Windows11

**Logs :**
```
 Checking libraries, please wait...
DownloadSource: GITHUB
Download percentage:
 100% [==========================================] 116/116 (0:00:00 / 0:00:00)
All libraries are nice :)!
Checking the installation, please wait.
[Mohist] Can't run the installation because the minecraft server file doesn't exist!
[Mohist] Can't run the installation because the mcp config file doesn't exist!
```

**Mod list :** None

**Plugin list :** None

**Description of issue :** This is an error I got during installation. I found a fix and will share it.

This error can be corrected by changing the DownloadSource.

1. Open mohist.yml in the mohist-config folder in the folder where you are trying to install the server. relative link :`./mohist-config/mohist.yml`
2. In the file,`downloadsource: AUTO` to `downloadsource: CHINA`. (It could work elsewhere, but I have not been able to find out.)
3. Resume the installation procedure.

**Comment by Yuukyboi** [comment]
It Still does not work for me
