### ISSUE TITLE
[1.19.2] Slow entities and objects in the world are static

### ISSUE THREAD

**Issue by MaxNEO12748** [Teneted/Tenet#3026]
**Minecraft Version :** 1.19.2

**Mohist Version :** mohist-1.19.2-100-server.jar

**Operating System :** Windows

**Logs :** https://pastebin.com/nr7rFHt9

**Mod list :** None
**Plugin list :** None

**Description of issue :** Entities move slowly or endlessly stand in one place, objects are not picked up, and the trajectory of a flying arrow from a bow is repeated several times before it reaches the target. Changing the Mohist version does not solve the problem. A complete change to Forge fixes this, but the functionality of the plugins is really needed.

**Comment by Mgazul** [comment]
1.19.2 We have not completed the development and do not recommend its use.

**Comment by MaxNEO12748** [comment]
Okay, I won't use it for now then.
