### ISSUE TITLE
[1.20.1] Magicspells plugin function & events missing

### ISSUE THREAD

**Issue by Sorax5** [Teneted/Tenet#3029]
**Minecraft Version :** 1.20.1

**Mohist Version :** 603

**Operating System :** Ubuntu

**Concerned mod / plugin** : [MagicSpells](https://github.com/TheComputerGeek2/MagicSpells/releases/tag/1507fdf)

**Logs :** [logs](https://haste.mohistmc.com/olucuqequg.sql)

**Steps to Reproduce :**
 1. Install magicspells
 2. Launch server
 3. Wait for magicspells error after world loaded

**Description of issue :**
Magicspells is a plugin that is compatible with paper base, I can see that some vents are missing or that some functions are not present in mohist.
The ones I've identified are :

- boolean org.bukkit.inventory.ItemStack.editMeta(java.util.function.Consumer)
- io/papermc/paper/event/entity/EntityMoveEvent
- io/papermc/paper/event/player/PrePlayerAttackEntityEvent

I don't know what's planned for Mohist 1.20.1, if the quoted events/functions are planned?

**Comment by Mgazul** [comment]
Paper plugin is not supported

**Comment by Mgazul** [comment]
You must ensure that the plugin can be used in spigot

**Comment by Sorax5** [comment]
I see, so I guess it's not planned to be fixed?
