### ISSUE TITLE
无法打开原版下届传送门！

### ISSUE THREAD

**Issue by Lonmo0208** [Teneted/Tenet#3030]
**What is your question ?**
{无法打开原版下届传送门！
 版本mohist-1.16.5-150~mohist-1.16.5-161-server.jar
 都存在这个问题 更早的版本我没有测试，我看到之前有人提交过，但这个问题到现在还没有修复！请麻烦你们检查并且修复!}

**Comment by Mgazul** [comment]
目前无法复现该问题

**Comment by Lonmo0208** [comment]
> 目前无法复现该问题

无法复现？也就是说你们测试的时候是可以正常打开地狱门的吗？
那就奇怪了...
