### ISSUE TITLE
[1.20.1] Mythic Dungeon Level.dat missing and server crash

### ISSUE THREAD

**Issue by Godschalke** [Teneted/Tenet#3034]
**Minecraft Version:** 1.20.1

**Mohist Version :** mohist-1.20.1-603

**Operating System :** Windows 11

**Concerned mod / plugin** : https://mythiccraft.io/index.php?resources/mythic-dungeons.869/

**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/14799408/latest.log) 
                 [debug.log](https://github.com/MohistMC/Mohist/files/14799410/debug.log) 

**Steps to Reproduce :**
1. Install Mythic Dungeons and ProtocolLib
2. Create a dungeon with /md create (dungeon name)
3. Attempt to edit dungeon (dungeon name), nothing happens for 15-20 seconds
4. Server times out and disconnects player

**Description of issue :** On dungeon creation, it fails to create a Level.dat and the this means the dungeon can't be saved. Additionally, when attempting to edit the dungeon nothing happens, it doesn't load me into the dungeon instance. After a delay, I'm disconnected and the server times out.

**Comment by Mgazul** [comment]
#2978
