### ISSUE TITLE
[1.12.2] Protocol lib errors and disables upon server startup

### ISSUE THREAD

**Issue by BloxMaster3** [Teneted/Tenet#3039]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-343-server

**Operating System :** Windows 11

**Concerned mod / plugin** : [ProtocolLib 5.1.0](https://www.spigotmc.org/resources/protocollib.1997/)

**Logs :** https://gist.github.com/BloxMaster3/88785a6ac97e20aa6b229908f66d8a2d

**Steps to Reproduce :**
 1. download and run Mohist and start batch and then stop the server
 2. download and install ProtocolLib plugin
 3. run the server again and it should error and also error when attempting to reload the plugin or any other command pertaining to it

**Description of issue :** I saw this was a duplicate with newer versions but wanted to let you guys know it affects older versions as well, but whenever I try to run ProtocolLib on a Mohist server, the plugin errors and disables and errors when any command is executed that pertains to it
Some screenshots of the server terminal:
![Screenshot 2024-03-31 081547](https://github.com/MohistMC/Mohist/assets/136217084/6a3e1ef7-e509-454e-8ce9-7ec6dda8281a)
![Screenshot 2024-03-31 224422](https://github.com/MohistMC/Mohist/assets/136217084/18eadad8-cf27-44b5-b178-2efed8f51b35)
![Screenshot 2024-03-31 224514](https://github.com/MohistMC/Mohist/assets/136217084/e4231e52-412f-4492-8145-7ef644dfa2aa)

**Comment by Mgazul** [comment]
use ProtocolLib-4.5.1

**Comment by BloxMaster3** [comment]
> use ProtocolLib-4.5.1

that worked. thank you
