### ISSUE TITLE
[1.20.1] Client always report incompatible FML modded server

### ISSUE THREAD

**Issue by wang-silas** [Teneted/Tenet#3042]
**Minecraft Version :** 1.20.1

**Mohist Version :** 645
**Operating System :** Windows11 Professional

**Logs :** 

<details>
<summary>Client Screenshot</summary>

![Snipaste_2024-04-02_22-51-42](https://github.com/MohistMC/Mohist/assets/33516065/4ca518b1-5605-4223-99e3-0269a9bd1ac3)

</details>

<details>
<summary>Client Log</summary>

![Snipaste_2024-04-02_22-48-54](https://github.com/MohistMC/Mohist/assets/33516065/058766a3-ebde-4664-b761-b2231f41badb)

</details>

**Mod list :** omitted

**Plugin list :** omitted

**Description of issue :** Client always report incompatible FML modded server. I'm not sure if it is a bug. However, actually, the function is good.

**Comment by Mgazul** [comment]
First of all this is not a bug, you can use mod -> https://modrinth.com/mod/my-server-is-compatible
