### ISSUE TITLE
[1.20.1] 加questsadditions mod后启动崩溃

### ISSUE THREAD

**Issue by Star-Jirachi** [Teneted/Tenet#3043]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-609-server.jar

**Operating System :** win10

**Concerned mod / plugin** : 
MOD：
architectury-9.1.12-forge
ftb-library-forge-2001.1.4
ftb-quests-forge-2001.3.5
ftb-teams-forge-2001.1.4
ftb-xmod-compat-forge-2.0.3
item-filters-forge-2001.1.0-build.59
questsadditions-1.4.3a

**Logs :** 
[latest.log](https://github.com/MohistMC/Mohist/files/14846849/latest.log)

**Steps to Reproduce :**
 1. 加入相应mod
 2. 服务器启动崩溃

**Description of issue :** 加入questsadditions这个mod会导致服务器启动崩溃，删除该mod后可以正常启动服务器。单人该mod可以正常使用。

**Comment by Mgazul** [comment]
The download address of questsadditions-1.4.3a mod cannot be found

**Comment by Star-Jirachi** [comment]
> The download address of questsadditions-1.4.3a mod cannot be found

Here:
https://www.curseforge.com/minecraft/mc-mods/quests-additions/files/4799757
