### ISSUE TITLE
[1.20.1]  generating end portal and ender dragon  issues

### ISSUE THREAD

**Issue by Ryuya1779** [Teneted/Tenet#3044]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-646

**Operating System :** ubuntu

**Logs :** nologs

**Mod list :** none

**Plugin list :** none

**Description of issue :** I have created a end world with /worlds create command but the end portal is not generated along with the ender dragon in the world.

**Comment by Mgazul** [comment]
According to Mojang's principle, it will only generate the corresponding terrain, and doors and dragons will only be generated in the DIM dimension.

**Comment by Ryuya1779** [comment]
Thank you for your response.
