### ISSUE TITLE
[1.19.2]客户端无法拾取任何物品

### ISSUE THREAD

**Issue by Alirea10** [Teneted/Tenet#3045]
#2942 
![image](https://github.com/MohistMC/Mohist/assets/111880868/a52d5894-e8bd-4cfa-ba9f-5fca8a1d6228)
![image](https://github.com/MohistMC/Mohist/assets/111880868/6685bfe6-3838-4810-95f9-9c44e6915183)

图一为带mods版本。图二为纯mohist原版。

mohist-1.19.2-106
maybe.....not fixed?
此次更新(也许）增加了一个吸收物品的动画（bushi）然而他仍不生效.....

**Comment by Ashikaga-JFM** [comment]
解决了吗

**Comment by Mgazul** [comment]
已修复，可能需要清理一次libraries文件夹！
