### ISSUE TITLE
[1.20.1]CMI死亡保留物品权限添加到LuckPerms时,在生存模式使用suicide或kill命令自杀将清空背包

### ISSUE THREAD

**Issue by KaiTeJun** [Teneted/Tenet#3046]
**Minecraft Version :** 1.20.1-Forge_47.2.21

**Mohist Version :** Mohist-1.20.1-build646

**Operating System :** win11

**Concerned mod / plugin** : CMI和LuckPerms均为最新版.(以及CMI的前置)

**Logs :** Link(s) of logs and crash reports if you have.没有,甚至都没报错

**Steps to Reproduce :**
 1. 用Mohist-1.20.1-build646开服,并安装上CMI、CMILib、LuckPerms三个插件,并在LuckPerms插件添加cmi.keepinventory和cmi.keepexp两个权限.(分别是死亡保留背包和死亡保留经验)
 (用Mohist-1.20.1-build636也测试过,基本和mohist版本和插件版本没太大关系,能运行前提下)
 2. 用hmcl安装1.20.1-Forge_47.2.21并启动,然后连接上本地服务器
 3. 开启创造在物品栏放几个东西,切换到生存模式
 4. 使用suicide或者kill在生存模式下自杀
 5. 重生后打开背包点击物品或者使用物品,物品神奇的消失了
 6. 不确定是不是我这边有问题,不过我已经测试很多次了
 7. 如果我太久没回复就关掉我的提交(issue)

**Description of issue :** Give all details about your issue

**Comment by KaiTeJun** [comment]
解决方法是不在LuckPerms添加cmi.keepinventory和cmi.keepexp权限

**Comment by Mgazul** [comment]
最新构建内置了相关权限 
"mohist.keepinventory.inventory"
"mohist.keepinventory.exp"
