### ISSUE TITLE
[1.19.2] Bug: Unable to edit the ‘sign’（看板，board）

### ISSUE THREAD

**Issue by yamadafz** [Teneted/Tenet#3048]
Minecraft Version : 1.19.2

Mohist Version : mohist-1.19.2-109-server.jar

Operating System : windows11

Concerned mod / plugin : nothing
Logs : no logs

Steps to Reproduce :

make a sign board
set sign board
Nothing happened
Right-click on the sign board
Nothing happened
Description of issue : Give all details about your issue

**Comment by Alirea10** [comment]
![7467139ec042f7fc014e07e575a9d7d5](https://github.com/MohistMC/Mohist/assets/111880868/a8d0b6f1-eeef-4ad0-a854-f4fdea2ad9a8)
你是否清醒
