### ISSUE TITLE
[1.20.1] Cataclysm ability bug

### ISSUE THREAD

**Issue by VideoGamerRUS** [Teneted/Tenet#3049]
**Minecraft Version :** 1.20.1

**Mohist Version :** 643 and 653

**Operating System :** Win Server 22

**Concerned mod / plugin** : https://www.curseforge.com/minecraft/mc-mods/lendercataclysm

**Logs :** No logs. Video: https://drive.google.com/file/d/1Xau--NR-pPuCLYO-EuY8UOzhMZZAQPZx/view?usp=sharing

**Steps to Reproduce :**
 1. Take the Forge
 2. Use Right click ability
 3. Try to open the Crafting table

**Description of issue :** In the video we can sse, that ib 653 build we can`t open the crafting table after some ability usage, and in 643 it works as it should

**Comment by Mgazul** [comment]
After testing, this problem does not occur. Please try deleting the libraries folder and restarting the server.
