### ISSUE TITLE
[1.20.1] BlueMap and Multiverse problem

### ISSUE THREAD

**Issue by PrograMysT** [Teneted/Tenet#3053]
**Minecraft Version :** 1.20.1

**Mohist Version :** 646

**Operating System :** Ubuntu 22.04 (Pterodactyl Panel)

**Concerned mod / plugin** : BlueMap (https://www.spigotmc.org/resources/bluemap.83557/) (Version: 3.20)

**Logs :** https://mcpaste.io/d2da1e8095c0a978

**Steps to Reproduce :**
 1. Create a new multiverse world (in the root server directory)
 2. Add the world to bluemap
 3. Do bluemap reload
 4. This is what i get when i reload it: 
![image](https://github.com/MohistMC/Mohist/assets/114109438/1e7de710-f708-48c4-a587-442c3391d92f)

**Description of issue :** So i can see the world in the bluemap menu, I can also view it but i cant see the worldborder i created with chunky border also i cant see players on the map and it doesnt update at all. Bluemap support told me to contact you directly that it is a Mohist issue.

**Comment by Mgazul** [comment]
The bluemap plugin doesn't recognize forge world path rules

**Comment by PrograMysT** [comment]
How to fix it?

**Comment by Mgazul** [comment]
Currently unfixable，this is not a bug, but a problem with the plug-in's compatibility with the forge mechanism.

**Comment by PrograMysT** [comment]
Oh okay, thanks for the reply :)
