### ISSUE TITLE
Hello plugins not work

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3054]
Minecraft Version : 1.20.1

Mohist Version :

**Operating System :** Linux

**Concerned mod: off / plugin: [21:43:59 INFO]: [PlugMan] Plugins (84): Actions, AdvancedChests, ajLeaderboards, AquaticCrates, BentoBox, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-Visit, BentoBox-Warps, BetonQuest, BetonQuestGUI, Boosters, ChatControlRed, Citizens, ClothesPlus, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DisableHUD, eco, EcoArmor, EcoItems, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, GeekMail-Pro, GlobalMarketPlus, libreforge, LuckPerms, MCPets, ModelEngine, Mohist, Multiverse-Core, MythicAchievements, MythicChanger, MythicDungeons, MythicEnchants, MythicLibreforge, MythicMobs, MythicPrefixes, NBTAPI, PlaceholderAPI, PlayerPoints, PlugManX, Polymart, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, SCore, SkinsRestorer, Slabbo, TAB, Talismans, TopBossSlayer, TopCollections, TopMinion, Triton, UltimateClans, UnrealCore, UnrealGUI, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, WorldEdit, WorldGuard, MMOCore, MMOItems, MythicLib, Oraxen, RPGInventory

Logs : https://mclo.gs/271QI1Z

not work: MMOCore, MMOItems, MythicLib, Oraxen, RPGInventory

**Comment by funnycubeguy** [comment]
Same issue

**Comment by Mgazul** [comment]
You installed multiple versions of MythicLib, causing dependency transfer errors

**Comment by Unitei-Dev** [comment]
![image](https://github.com/MohistMC/Mohist/assets/136928305/a8627102-4eb9-425e-9151-1edce859908f)

**Comment by Unitei-Dev** [comment]
MythicLIbReforge This is an addition

**Comment by Unitei-Dev** [comment]
to work with Eco plugins

**Comment by Unitei-Dev** [comment]
> You installed multiple versions of MythicLib, causing dependency transfer errors

This error manifests itself even if it is installed on a clean Mohist kernel
