### ISSUE TITLE
Boot crashes caused by DBlockbusterDisplays 2.0.2-1.20.1

### ISSUE THREAD

**Issue by ASHISK404** [Teneted/Tenet#3059]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {1.20.1*625}

**Operating System :** {centos}

**Logs :** {https://gist.github.com/ASHISK404/7734dfdd5a74ded3b36c0d0166330909}

**Mod list :** {
Mod List: 
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		mcef-forge-2.1.5-1.20.1.jar                       |MCEF (Minecraft Chromium Embed|mcef                          |2.1.5-1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.2.23-universal.jar                |Forge                         |forge                         |47.2.23             |COMMON_SET|Manifest: NOSIGNATURE
		DBlockbusterDisplays-2.0.2-1.20.1.jar             |DBlockbusterDisplays          |webdisplays                   |2.0.1-1.20.1        |ERROR     |Manifest: NOSIGNATURE
}

**Plugin list :** {no one}

**Description of issue :** {Dblockbustershows-2.0.2-1.20.1 was a fork of webdisplayer that crashed the server just by adding it}

**Comment by Mgazul** [comment]
Dblockbustershows is a client-side mod

**Comment by Mgazul** [comment]
![image](https://github.com/MohistMC/Mohist/assets/23317456/a27fb56e-8ffd-41b2-8c19-f9d2963918c9)

**Comment by ASHISK404** [comment]
However, it adds items and squares, and it should not only exist in the client....
