### ISSUE TITLE
TileEntity duplication

### ISSUE THREAD

**Issue by HeberonYT** [Teneted/Tenet#306]
**Describe the bug**
The latest versions of Mohist are loading too many TileEntities placed in the overworld.
Every minute, the number increases infinitely until it causes the server to crash.
In the image I show a count of entities and TileEntity before turning it off.

For example, the image shows the count of "TileEntityRetinalScanner = 3796" and in reality my world only has 50 blocks maximum of that type placed, so you can imagine how they are duplicated somewhere to the point of being excessive to maintain the server online.
Visually they do not exist, or I have not found them. But too many appear in the reports, by the way, the data is obtained by tickprofiler.

This occurs when players go to another world and the overworld is empty of players, it begins to drastically increase the amount of "tileEntity" to the point of shutting down the server.
I found a way to temporarily fix it, and it is returning a player to overworld for a few seconds, and immediately the TileEntity count disappears improving server performance.

**To Reproduce**
In my case, just start the server and after a few hours it will crash, even with no players inside.

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/13698597/83182190-96717c80-a0eb-11ea-928e-b75d8c9bbc98.png)

**Additional context**
I did a test using CatServer and this does not happen.

Mohist: Build #538

**Comment by idunnoooooo** [comment]
+1
