### ISSUE TITLE
Mohist 1.20.1 broken again on startup

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3062]
Latest build...

Searching incompatible mods...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe87c51808d, pid=1, tid=33
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.10+7 (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xa9808d]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x20d
#
# Core dump will be written. Default location: /home/container/core
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

**Comment by Mgazul** [comment]
Are you using an Intel 13th generation CPU?

**Comment by funnycubeguy** [comment]
> Are you using an Intel 13th generation CPU?

AMD ryzen 7900X. Downgraded to build 319 fixed

**Comment by funnycubeguy** [comment]
> Are you using an Intel 13th generation CPU?

Updated to the latest:

Thanks for using Mohist - 1.20.1-664, Java(21) 65.0 PID: 34
Update in check...
If you don't want to enable update check, set check_update in mohist-config/mohist.yml to false
No update found, latest version: (664) current version: (664)
Checking libraries, please wait...
All libraries are nice :)!
Searching incompatible mods...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f90988ec6e6, pid=34, tid=35
#
# JRE version: OpenJDK Runtime Environment GraalVM CE 21+35.1 (21.0+35) (build 21+35-jvmci-23.1-b15)
# Java VM: OpenJDK 64-Bit Server VM GraalVM CE 21+35.1 (21+35-jvmci-23.1-b15, mixed mode, sharing, tiered, jvmci, jvmci compiler, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xb576e6]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x1b6
#
# Core dump will be written. Default location: /home/container/core
#
# An error report file with more information is saved as:
# /home/container/hs_err_pid34.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/oracle/graal/issues
#
/entrypoint.sh: line 49:    34 Aborted                 (core dumped) java -Xmx28G -Xms28G -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -jar server.jar

**Comment by funnycubeguy** [comment]
> Are you using an Intel 13th generation CPU?

I tried the latest now build 630 and the error doesn't show. All it says is "cannot access server.jar"

**Comment by funnycubeguy** [comment]
Deleting the libraries folder fixed it. Latest is working
