### ISSUE TITLE
mohist-1.20.1-628-无法在cmd中输入任何字符

### ISSUE THREAD

**Issue by MY2180** [Teneted/Tenet#3063]
**What is your question ?**
{
环境：win11x64 jdk17  
在664版本中cmd无法输入任何字符   
[debug.log](https://github.com/MohistMC/Mohist/files/14962572/debug.log)
[latest.log](https://github.com/MohistMC/Mohist/files/14962575/latest.log)
如果我的lssue报告有任何问题 请指出 感谢墨佬
}

**Comment by Mgazul** [comment]
已修复
