### ISSUE TITLE
MythicLib plugin not load 

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3064]
Minecraft Version : 1.20.1

Mohist Version : mohist-1.20.1-630-server.jar | e

Operating System : Linux

**Concerned mod: off / plugins: [PlugMan] Plugins (88): Actions, AdvancedChests, ajLeaderboards, AquaticCrates, BentoBox, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-Visit, BentoBox-Warps, BetonQuest, BetonQuestGUI, Boosters, ChatControlRed, Citizens, ClothesPlus, CMILib, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DisableHUD, eco, EcoArmor, EcoItems, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, GeekMail-Pro, GlobalMarketPlus, Jobs, libreforge, LuckPerms, MCPets, ModelEngine, Mohist, Multiverse-Core, MythicAchievements, MythicChanger, MythicCrucible, MythicDungeons, MythicEnchants, MythicLibreforge, MythicMobs, MythicPrefixes, NBTAPI, Origami, OutpostCommander, PlaceholderAPI, PlayerPoints, PlugManX, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, SCore, SkinsRestorer, Slabbo, TAB, Talismans, TopBossSlayer, TopCollections, TopMinion, Triton, UltimateClans, UnrealCore, UnrealGUI, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, WorldEdit, WorldGuard, MMOCore, MMOItems, MythicLib, Oraxen, RPGInventory

Logs : https://mclo.gs/0DVb6xq

not work: MMOCore, MMOItems, MythicLib, Oraxen, RPGInventory

Because of the mods, this does not happen, I have already checked

![Снимок экрана 2024-04-13 222452](https://github.com/MohistMC/Mohist/assets/136928305/0279acc0-9301-41e2-abdc-41c750a1808f)

![image](https://github.com/MohistMC/Mohist/assets/136928305/bda48259-275e-445a-8f6e-81eb6dbc077f)

**Comment by Unitei-Dev** [comment]
I think this is a bug, not a multi-version

**Comment by Mgazul** [comment]
https://www.spigotmc.org/resources/mmolib-mythiclib.90306/ use this
