### ISSUE TITLE
MythicLib plugin not load #3

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3069]
Minecraft Version : 1.20.1

Mohist Version : mohist-1.20.1-633-server.jar | e

Operating System : Linux

**Concerned mod: off / plugins: [PlugMan] Plugins (85): Actions, AdvancedChests, ajLeaderboards, AquaticCrates, BentoBox, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-Visit, BentoBox-Warps, BetonQuest, BetonQuestGUI, Boosters, ChatControlRed, Citizens, ClothesPlus, CMILib, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DisableHUD, eco, EcoArmor, EcoItems, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, GeekMail-Pro, GlobalMarketPlus, Jobs, libreforge, LuckPerms, MCPets, ModelEngine, Mohist, Multiverse-Core, MythicAchievements, MythicChanger, MythicCrucible, MythicDungeons, MythicEnchants, MythicLibreforge, MythicMobs, MythicPrefixes, NBTAPI, Oraxen, OutpostCommander, PlaceholderAPI, PlayerPoints, PlugManX, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, SCore, SkinsRestorer, Slabbo, TAB, Talismans, TopBossSlayer, TopCollections, Triton, UltimateClans, UnrealCore, UnrealGUI, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, WorldEdit, WorldGuard, MythicLib, Origami, TopMinion

Logs : https://mclo.gs/T5xsaQs

not work: MythicLib

Because of the mods, this does not happen, I have already checked

**Comment by Unitei-Dev** [comment]
![image](https://github.com/MohistMC/Mohist/assets/136928305/fb8e65a7-9f38-4a57-bc64-e01869a019b1)

**Comment by Unitei-Dev** [comment]
the problem was solved, the reason was in the Triton plugin for translation into different languages https://polymart.org/resource/triton-translate-your-server.38 Is there any way to fix this ?

**Comment by Mgazul** [comment]
Don't open the same question repeatedly
