### ISSUE TITLE
plugin not load fix please

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3070]
plugins are downloaded from: https://www.spigotmc.org/threads/gps-pathfinder-minecraft-pathfinding-tool.571729/ and https://madustrialtd.asuscomm.com/unrealforum/index.php?resources/chemdahucexpand.36/

Minecraft Version : 1.20.1

Mohist Version : mohist-1.20.1-633-server.jar | e

Operating System : Linux

**Concerned mod: off / plugins: [PlugMan] Plugins (85): Actions, AdvancedChests, ajLeaderboards, AquaticCrates, BentoBox, BentoBox-BSkyBlock, BentoBox-Challenges, BentoBox-Level, BentoBox-Likes, BentoBox-Limits, BentoBox-Visit, BentoBox-Warps, BetonQuest, BetonQuestGUI, Boosters, ChatControlRed, Citizens, ClothesPlus, CMILib, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DisableHUD, eco, EcoArmor, EcoItems, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, FancyCore, FancyDrop, FancyMobs, FancyTeam, GeekMail-Pro, GlobalMarketPlus, Jobs, LeaderMobs, libreforge, LuckPerms, MCPets, MMOCore, MMOItems, ModelEngine, Mohist, MythicAchievements, MythicChanger, MythicCrucible, MythicDungeons, MythicEnchants, MythicLib, MythicLibreforge, MythicMobs, MythicPrefixes, NBTAPI, Oraxen, OutpostCommander, PlaceholderAPI, PlayerPoints, PlugManX, Polymart, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, RPGInventory, SCore, SkinsRestorer, Slabbo, TAB, Talismans, TopBossSlayer, TopCollections, TopMinion, UltimateClans, UnrealCore, UnrealGUI, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, WorldEdit, WorldGuard, ChemdahUCExpand, PathFinder

Logs : https://mclo.gs/jUnOcgo

not work: ChemdahUCExpand, PathFinder

**Comment by Mgazul** [comment]
ChemdahUCExpand requires taboolib as a prerequisite

**Comment by Unitei-Dev** [comment]
> ChemdahUCExpand требует наличия taboolib в качестве предварительного условия.

so okay, where do I get this plugin?

**Comment by Mgazul** [comment]
> > ChemdahUCExpand требует наличия taboolib в качестве предварительного условия.
> 
> so okay, where do I get this plugin?

You should ask the plugin author
