### ISSUE TITLE
mohist-1.20.1-635-server 版本671 mc1.20.1

### ISSUE THREAD

**Issue by MY2180** [Teneted/Tenet#3074]
**What is your question ?**
{系统 win11x64 java 17甲骨文 版本671 mc1.20.1
[此版本存在死两次以上（包括2次）就会丢失用床设置的出生点返回世界出生点的bug
[2024-04-16-1.log.zip](https://github.com/MohistMC/Mohist/files/14995082/2024-04-16-1.log.zip)

[debug-1.log.zip](https://github.com/MohistMC/Mohist/files/14995083/debug-1.log.zip)
}

**Comment by Mgazul** [comment]
Fixed
