### ISSUE TITLE
[1.20.1] Spigot library loader does funny things again

### ISSUE THREAD

**Issue by wtlgo** [Teneted/Tenet#3076]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-674

**Operating System :** Windows 10

**Logs :** https://haste.mohistmc.com/qicoqotavi.yaml

**Mod list :** None

**Plugin list :** Just this one [example_plugin-0.0.1.zip](https://github.com/MohistMC/Mohist/files/15019234/example_plugin-0.0.1.zip)

**Description of issue :**
Version 1.20.1-674 breaks the Spigot library loader. The plugin already mentioned in #3060 stopped loading again.
As usual, the plugin loads correctly on Mohist 1.20.1-673 and the latest versions of Paper and Spigot.

**Comment by Mgazul** [comment]
Don't open the same issues over and over again, you should reply to the old one

**Comment by wtlgo** [comment]
I open a new issue because each of them is related to a new build, and because the previous issues are already marked as closed. I have no ability to re-open closed issues.

**Comment by Mgazul** [comment]
You don't need to reopen, just reply
