### ISSUE TITLE
[1.20.1] Fantasy Furniture bed problem

### ISSUE THREAD

**Issue by VideoGamerRUS** [Teneted/Tenet#3077]
**Minecraft Version :** 1.20.1

**Mohist Version :** 676

**Operating System :** WinServer 22

**Concerned mod / plugin** : https://www.modrinth.com/mod/fantasy-furniture

**Logs :** No logs

**Steps to Reproduce :**
 1. Take any bed from the mod
 2. Try to sleep on it

**Description of issue :** When you try to sleep on any Fantasy Furniture`s bed, it kick you with error: internal exception io.netty.handler.codec.decoderexception: received unexpected null component
Video: https://drive.google.com/file/d/1nq1Qz9LLRVgw2UkivlPO67GNpUTQbnAm/view?usp=sharing

**Comment by Mgazul** [comment]
The problem cannot be reproduced
![image](https://github.com/MohistMC/Mohist/assets/23317456/cbdb05de-d0d2-44ad-86c5-d9d8ae9a8609)

**Comment by VideoGamerRUS** [comment]
Fixed by found a mod incompatibility. thx <3

**Comment by elislavkat** [comment]
> Fixed by found a mod incompatibility. thx <3

hello. which one mod u found? i have same problem after updated whole modpack
and again adding fantasy furniture- now it make us crash on dedicated server
