### ISSUE TITLE
Plugins do not work - Banitem, CratesPlus, Great Kits

### ISSUE THREAD

**Issue by texbobcatv2** [Teneted/Tenet#308]
**Describe the bug**
Plugins fail to load or fails to load config

**To Reproduce**
Ban an item and restart 
1. BANITEM PLUGIN - https://www.spigotmc.org/resources/banitem-1-7-1-15.67701/?__cf_chl_jschl_tk__=75e654e8cbd9a231874b89a2f14fb890c0e4a6e9-1590698870-0-AbVcxCWVHNnbNoOA4ttcsDFuviWtR7jXQWE3_67CsoN0os0dVu_f9r25YLjdSF1l0nQU0TCrvkB0KdQylEpu4DiOOat9b2PdD41r3tgimALot_s3X6LXRH2zXmwHh1tzAaec64SEhxfN6Pd2FuOLlK-5Ds_9uf7zEwe6kTJlgVZDLHOf6Eu4OMecShKMlyU-jTZJN4U_z6-oUc1I8XG_hxbBwNGNn6Jawn4j6ACuEBG3wLeSf1DlEH8yy8p66IJbuAeljDBO-y4SvD1KjzK2nPL7BxQlxnNjoQZecZCXln4YNzzVDClHjnYt5qAJ7aaltw

1. Crates Plus - https://www.spigotmc.org/resources/cratesplus-free-crates-plugin-1-7-1-14-2.5018/?__cf_chl_jschl_tk__=847790ba0c340dab87fabf8e92e149f5ff1663d7-1590442549-0-AeRUUfAB9-ZJJnJSOTlWPlsU7Pu7sHk_8lrnjDelUZDT6LVDW_EdRWS-i9kNjMFwHDNZQ0YC4FYq6E7GQrhmCZ52PiNZH82-wIF-utL7V3VzWFC1M1eyolqTJ9CFhDPflrCrP0usT4qibQ8YoQrDMjZeafySd0JD70sMXhhKvGV_QKAuiJYh_4JiKZZRshquy3O9vHr0ICjXLowHhp45mZlbIBfdiEZyxDWy06m7c4YqVWGb4lVUarVAWLxppCnUmSDry5Owo4RAcHE_C78vtdnlOGBdqe2Kf6GXgH1fviBbE3KPFDQa2q7FZB6W6qcesLnjhTJojaKw4jHvYqcWbabretSZlNXfppJoqfC1WChf

1. https://www.spigotmc.org/resources/greatkits-1-7-1-13-full-config-kits-plugin-save-and-load-inventory-with-commands.44535/

2. https://pastebin.com/NHGmUfAN

**Expected behavior**
Banitem should load in the current banned items.  And then CratesPlus should show crates but instead the crates become chest and gui/commands do not work.  When you do /kit it says internal server error instead of pulling up the GUI
**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: Crates Plus, Banitem, Great Kits
 - Mod/Plugins  Version:  Crates plus 4.5.2, Banitem 2.1.2, GK 2.9.0

**Additional context**
Worked on build build #521
[latest.log](https://github.com/Mohist-Community/Mohist/files/4698289/latest.log)

**Comment by baominix** [comment]
BANITEM PLUGIN You can try.
------
config.yml
blacklist:
  world:
    saddleTest:
      armorstandplace: {}
      brew: {}
      entityinteract: {}
      entitydrop: {}
      place: {}
      hangingplace: {}
      interact: {}
      consume: {}
      delete: {}
      transfer: {}
      pickup: {}
      drop: {}
      attack: {}
      dispense: {}
      glide: {}
      craft: {}
      smelt: {}
      swap: {}
      click: {}
      armorstandtake: {}
      wear: {}
      break: {}
      drops: {}
------
------
item.yml
saddleTest:
  ==: org.bukkit.inventory.ItemStack
  type: SADDLE
------
item saddle will be  ban and work when restart

**Comment by Shawiizz** [comment]
I tested banitem and I have the issue. I think it's because the plugin don't support modded items and blocks.

**Comment by ColinVaughn** [comment]
No it does it broke when I switched versions of mohist

**Comment by Shawiizz** [comment]
Can you tell in which version the bug was created ? It can help us to fix the bug

**Comment by baominix** [comment]
> I tested banitem and I have the issue. I think it's because the plugin don't support modded items and blocks.

Me too.

**Comment by ColinVaughn** [comment]
build #521 all the plugins work fine and works with modded items because it uses block names
