### ISSUE TITLE
[MC VERSION] VintageFix causes Extreme server tick lag

### ISSUE THREAD

**Issue by BloxMaster3** [Teneted/Tenet#3080]
**Minecraft Version :** 1.12.2

**Mohist Version :** mohist-1.12.2-343-server.jar

**Operating System :** Windows 11

**Concerned mod / plugin** : VintageFix and MixinBooter (VintageFix dependency)

**Logs :** https://gist.github.com/BloxMaster3/0b0dc211c8cf0330a5617e3407f29e8e

**Steps to Reproduce :**
 1. Download VintageFix and MixinBooter (VintageFix dependency) and put in mods folder
 2. start mohist server and should see this every so often: ![Screenshot 2024-04-20 040338](https://github.com/MohistMC/Mohist/assets/136217084/1b10dbff-87fe-4ff3-b0d1-2d77066695d9)
 3. run /tps and you should see something like this where the bottom measurement says the TPS has been 0 even though the top measurements in all the dimensions has been 20:
![Screenshot 2024-04-21 050547](https://github.com/MohistMC/Mohist/assets/136217084/9bdddc1f-448a-485c-b1e7-606ce6475548)

**Description of issue :**
the effects of this is severe server ticklag where you can't break blocks unless you insta-mine it and can't pick up items, rendering the game unplayable. This doesn't happen on the normal forge server but I need plugins

**Comment by Mgazul** [comment]
VintageFix breaks tps calculation logic

**Comment by Mgazul** [comment]
https://github.com/embeddedt/VintageFix/blob/main/src/main/java/org/embeddedt/vintagefix/mixin/bugfix/slow_tps_catchup/MinecraftServerMixin.java#L87

https://github.com/MohistMC/Mohist/blob/1.20.1/patches/minecraft/net/minecraft/server/MinecraftServer.java.patch#L506

**Comment by BloxMaster3** [comment]
@embeddedt

**Comment by embeddedt** [comment]
Hybrid servers are not supported by VintageFix as they make too many changes to Forge internals to keep up with.

**Comment by BloxMaster3** [comment]
for everyone that has this problem use version 0.3.3

**Comment by FranklinMCA** [comment]
https://github.com/embeddedt/VintageFix/issues/89#issuecomment-2137989128
