### ISSUE TITLE
[1.20.1] MoreMobVariants Sheep and other animals cannot breed

### ISSUE THREAD

**Issue by PrograMysT** [Teneted/Tenet#3081]
**Minecraft Version :** 1.20.1

**Mohist Version :** 646

**Operating System :** Ubuntu 22.04

**Concerned mod / plugin** : https://www.curseforge.com/minecraft/mc-mods/more-mob-variants

**Logs :** https://mcpaste.io/b67eb7ec9207f6bb

**Steps to Reproduce :**
 1. Install mod on client and server
 2. Start the server and wait for the mod to load
 3. Try to breed sheep
 4. The sheeps disapear and i get this error in console.

![image](https://github.com/MohistMC/Mohist/assets/114109438/5cfa844b-4494-470e-8435-3071a8bf94d9)

**Description of issue :** When i try to breed 2 sheeps one seems to disapear and it doesnt spawn a baby sheep. Also i get an error in console, i tested the mod out of Mohist and it seems to work okay.

**Comment by Mgazul** [comment]
The problem comes from the mod itself and has been fixed by the mod author
