### ISSUE TITLE
[1.20.1]Multiverse-Core 多世界插件无法取消出生点内存常加载

### ISSUE THREAD

**Issue by kingniu4** [Teneted/Tenet#3086]
mohist版本：mohist-1.20.1-647-server
mc版本：1.20.1

问题描述：
如题，多世界插件无法取消出生点常加载，准确说：本来已经使用多世界插件取消了出生点，并且/reload后用CMI的/status指令查看已经正常取消了，但每次服务器重启后又会恢复出生点常加载，还得再次手动/reload才能关闭常加载。
另外，mohist自带的常加载调为false也没有用。

复现步骤：
1.不需要mod，安装核心，安装mv插件、CMI/CMILib插件，并启动一遍服务端退出
2.将mv插件配置三个维度的keepSpawnInMemory: 'true'改为false
3.启动服务器，输入/cmi status发现出生点仍然常加载，输入/mv reload后，出生点常加载又成功关闭。

不知道是无法正确读取配置还是咋的，一个月前的mohist版本还是正常的
[2024-04-23-12.log](https://github.com/MohistMC/Mohist/files/15075975/2024-04-23-12.log)

**Comment by kingniu4** [comment]
![image](https://github.com/MohistMC/Mohist/assets/98977392/484abc86-5274-481a-8b70-f210ea7b5e54)
好像没修好啊，656版本

**Comment by Mgazul** [comment]
目前无法操作原版的3个世界，仅对插件创建的世界有效

**Comment by kingniu4** [comment]
好吧，一个月前的核心还行的 qwq

**Comment by kingniu4** [comment]
等待后续修复了
