### ISSUE TITLE
[1.20.1] SkinRestorer isnt working

### ISSUE THREAD

**Issue by PrograMysT** [Teneted/Tenet#3087]
**Minecraft Version :** 1.20.1

**Mohist Version :** 646

**Operating System :** Ubuntu 22.04

**Concerned mod / plugin** : https://www.spigotmc.org/resources/skinsrestorer.2124/

**Logs :** https://mcpaste.io/872f2cf6d04c87b3

**Steps to Reproduce :**
 1. Install SkinRestorer
 2. Start the server

**Description of issue :** Hello, so SkinRestorer doesnt seem to be working on my server for some reason. I get an error in console.
![image](https://github.com/MohistMC/Mohist/assets/114109438/418110e7-acbc-4e21-95fa-5c45b21ad7ba)

**Comment by Mgazul** [comment]
This is because you cannot get the skin file from the mojang api. It may be that the mojang api is broken or there is a problem with your network.
