### ISSUE TITLE
[1.20.1] lets-do-meadow和architectury模组导致后台大量报错

### ISSUE THREAD

**Issue by Star-Jirachi** [Teneted/Tenet#3088]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-647-server

**Operating System :** win10

**Concerned mod / plugin** : 
[Let's Do] Meadow
链接：https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow
architectury
链接：https://www.curseforge.com/minecraft/mc-mods/architectury-api

**Logs :** 
[latest.log](https://github.com/MohistMC/Mohist/files/15077875/latest.log)

**Steps to Reproduce :**
 1. 启动服务器
 2. 服务器后台有时大量报错

**Description of issue :** 服务器后台大量报错，应该是lets-do-meadow和architectury引起的，目前似乎没有性能方面的影响，但是在后台刷大量报错影响观察日志

**Comment by Mgazul** [comment]
问题来自mod本身
