### ISSUE TITLE
[1.20.1] swem模组导致服务器启动失败

### ISSUE THREAD

**Issue by Star-Jirachi** [Teneted/Tenet#3092]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-653-server

**Operating System :** win10

**Concerned mod / plugin** : 
swem：https://www.mcmod.cn/class/7803.html

**Logs :** 
崩溃日志：
[crash-2024-04-25_17.07.53-server.txt](https://github.com/MohistMC/Mohist/files/15107142/crash-2024-04-25_17.07.53-server.txt)
日志：
[latest.log](https://github.com/MohistMC/Mohist/files/15107147/latest.log)

**Steps to Reproduce :**

**Description of issue :** swem模组导致服务器启动失败，删除swem模组后可以正常启动

**Comment by Mgazul** [comment]
问题来自mod本身
