### ISSUE TITLE
[1.18.2] WorldEdit mod doesn't work

### ISSUE THREAD

**Issue by Buer-Nahida** [Teneted/Tenet#3093]
**Minecraft Version :** 1.18.2

**Mohist Version :** 164

**Operating System :** ArchLinux

**Concerned mod / plugin** : https://www.curseforge.com/minecraft/mc-mods/worldedit/files/3697298

**Logs :** [debug.log](https://github.com/MohistMC/Mohist/files/15111097/debug.log)

<details>
<summary><b>Mods List (touch to extend) :</b></summary>

- AnvilRepairing-Forge-1.18.2-1.0.1.jar
- Apotheosis-1.18.2-5.8.1.jar
- apotheosis_modern_ragnarok-1.18.2-1.3.13.jar
- appleskin-forge-mc1.18.2-2.5.1.jar
- ArcaneAdditions-1.6.0.jar
- arcanearrays-alpha0.1.jar
- architectury-4.12.94-forge.jar
- ars_nouveau-1.18.2-2.9.0.jar
- asynclocator-1.18.2-1.1.0.jar
- AutoRegLib-1.7-53.jar
- autorun-1.18.2-1.0.0.0.jar
- balm-3.2.6.jar
- BeeFix-1.18-1.0.7.jar
- BetterF3-3.0.0-Forge-1.18.2.jar
- betterfpsdist-1.18.2-1.5.jar
- betterstats-2.2.2+1.18.2.jar
- bettervillage-forge-1.18.2-3.2.0.jar
- BiomesOPlenty-1.18.2-16.0.0.109-universal.jar
- blue_skies-1.18.2-1.3.12.jar
- Bookshelf-Forge-1.18.2-13.3.56.jar
- BrandonsCore-1.18.2-3.1.10.283-universal.jar
- caelus-forge-1.18.1-3.0.0.2.jar
- carryon-1.18.2-1.17.2.15.jar
- chat_heads-0.6.1-forge-1.18.2.jar
- chestedcompanions-1.2.2-1.18.2-FORGE.jar
- chunksending-1.18.2-2.5.jar
- cloth-config-6.5.116-forge.jar
- CodeChickenLib-1.18.2-4.1.4.488-universal.jar
- cofh_core-1.18.2-9.2.3.47.jar
- collective-1.18.2-7.7.jar
- ColossalChests-1.18.2-1.9.0.jar
- coroutil-forge-1.18.2-1.3.6.jar
- create-1.18.2-0.5.1.f.jar
- CTM-1.18.2-1.1.5+5.jar
- cupboard-1.18.2-1.5.jar
- curios-forge-1.18.2-5.0.9.2.jar
- curiousshulkerboxes-forge-1.18.1-4.2.0.0.jar
- curtain-mc1.18.2-1.3.2.jar
- CustomSkinLoader_ForgeActive-14.19.1.jar
- CyclopsCore-1.18.2-1.17.9.jar
- Draconic-Additions-1.18.2-2.2.7.10-universal.jar
- Draconic-Evolution-1.18.2-3.0.31.531-universal.jar
- dragonmagicandrelics-1.18.2-2.1.38.jar
- embeddium-0.3.10+mc1.18.2.jar
- embeddiumplus-1.18.2-v1.2.5.jar
- EnderStorage-1.18.2-2.9.0.182-universal.jar
- entityculling-forge-1.6.1-mc1.18.2.jar
- FarmersDelight-1.18.2-1.2.3.jar
- FastFurnace-1.18.2-6.0.3.jar
- FastSuite-1.18.2-3.0.2.jar
- FastWorkbench-1.18.2-6.1.1.jar
- feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
- FluxNetworks-1.18.2-7.0.9.15.jar
- forgivingvoid-forge-1.18.1-6.0.1.jar
- framework-forge-1.18.2-0.4.3.jar
- francium-1.18.2-1.0.1.jar
- ftb-chunks-forge-1802.3.17-build.265.jar
- ftb-essentials-1802.2.2-build.83.jar
- ftb-library-forge-1802.3.11-build.177.jar
- ftb-ranks-forge-1802.1.11-build.71.jar
- ftb-teams-forge-1802.2.11-build.107.jar
- geckolib-forge-1.18-3.0.57.jar
- goprone-1.18.2-2.2.1.jar
- gpumemleakfix-1.18.2-1.6.jar
- hourglass-1.18.2-1.2.1.0.jar
- integrated_api_forge-1.2.8+1.18.2.jar
- integrated_stronghold_forge-1.0.2+1.18.2.jar
- invhud.forge.1.18.2-3.4.18.jar
- ironchest-1.18.2-13.2.11.jar
- ironfurnaces-1.18.2-3.3.3.jar
- Jade-1.18.2-forge-5.3.2.jar
- JER-Integration-3.4.0.jar
- JustEnoughResources-1.18.2-0.14.2.206.jar
- lazydfu-1.0-1.18+.jar
- libraryferret-forge-1.18.2-4.0.0.jar
- longerlogintimes-1.0.0-mc1.18.jar
- lootr-1.18.2-0.3.27.69.jar
- MaxHealthFix-Forge-1.18.2-5.0.5.jar
- Mekanism-1.18.2-10.2.5.465.jar
- melody_forge_1.0.1_MC_1.18.2.jar
- metalbarrels-1.18.2-4.3.jar
- mna-2.0.0.33.jar
- modernfix-forge-5.15.0+mc1.18.2.jar
- MouseTweaks-forge-mc1.18-2.21.jar
- Neat 1.8-30.jar
- nerb-1.18.2-0.3-FORGE.jar
- NoChatLagForge-1.1.0.jar
- Nullscape_1.18.2_v1.1.4.jar
- oculus-flywheel-compat-1.18.2-0.2.1.jar
- PassiveSearchBar+Forge+1.18.2-1.19.2-1.0.0.jar
- passiveshield-1.18.2-3.3.jar
- Patchouli-1.18.2-71.1.jar
- Placebo-1.18.2-6.6.7.jar
- player-animation-lib-forge-1.0.2+1.18.jar
- playerex-3.4.2.jar
- polymorph-forge-1.18.2-0.50.jar
- Quark-3.2-358.jar
- REIPluginCompatibilities-forge-8.0.89.jar
- responsiveshields-2.3-mc1.18-19-20.x.jar
- RoughlyEnoughItems-8.3.681-forge.jar
- RoughlyEnoughProfessions-forge-1.18.2-1.0.3.jar
- [SBAdd]SJAP_ex_blades-[1.16.5-1.20.x]1.7_edited_1.0.2.jar
- seasonhud-forge-1.18.2-1.7.16.jar
- selene-1.18.2-1.17.14.jar
- sereneseasonfix-1.18.2-1.0.6.jar
- SereneSeasons-1.18.2-7.0.0.15.jar
- SlashBlade-1.18.2-0.0.9.jar
- smoothchunk-1.18.2-1.9.jar
- staaaaaaaaaaaack-forge-1.18.2-1.4-62.jar
- starlight-1.0.2+forge.546ae87.jar
- structure_gel-1.18.2-2.4.8.jar
- supermartijn642configlib-1.1.8-forge-mc1.18.jar
- supplementaries-1.18.2-1.5.18.jar
- tac-0.3.10.1-1.18.2.jar
- TerraBlender-forge-1.18.2-1.2.0.126.jar
- textrues_embeddium_options-0.1.1+mc1.18.2.jar
- thermal_cultivation-1.18.2-9.2.1.20.jar
- thermal_dynamics-1.18.2-9.2.2.19.jar
- thermal_expansion-1.18.2-9.2.2.24.jar
- thermal_foundation-1.18.2-9.2.2.58.jar
- thermal_innovation-1.18.2-9.2.1.19.jar
- thermal_integration-1.18.2-9.2.1.18.jar
- thermal_locomotion-1.18.2-9.2.1.15.jar
- timerecorder-1.0-PreRelease-1.jar
- touhoulittlemaid-1.18.2-release-1.1.7.jar
- travelersbackpack-forge-1.18.2-7.1.47.jar
- twilightforest-1.18.2-4.1.1494-universal.jar
- watut-forge-1.18.2-1.0.14.jar
- waveycapes-forge-1.4.4-mc1.18.2.jar
- worldedit-mod-7.2.10.jar
- Xaeros_Minimap_24.0.3_Forge_1.18.2.jar
- XaerosWorldMap_1.38.1_Forge_1.18.2.jar
- xibao-1.0.0.jar
- yesstevemodel-1.18.2-release-1.1.5-hotfix-2.jar
- YungsApi-1.18.2-Forge-2.2.9.jar
- YungsBetterEndIsland-1.18.2-Forge-1.0.jar
</details>

I installed worldedit forge mod, but in server, I select 2 pos (use wand) and I execute `//set minecraft:oak_wood`, after that, It tell me it.

![2024-04-25-22-02-54](https://github.com/MohistMC/Mohist/assets/139795416/d6c3dc88-1bf8-4452-9024-d802379a2221)

I also tried `//wand` `//pos1` `//pos2` and other WE commands, They all doesn't work too.

**Comment by Pignoniii** [comment]
Hi,
I have the same problem...
