### ISSUE TITLE
1.20.1 The plugin to view inventory does not work

### ISSUE THREAD

**Issue by QuQuShKa1205** [Teneted/Tenet#3095]
**1.20.1 :** Minecraft version

**639 :** Provide Mohist build number

**ubuntu 22 04 :** Provide the name of your OS

**SeePlayerInventory-2.7.2.jar** : Provide mod / plugin name and download link if possible

**[Logs](https://gist.github.com/QuQuShKa1205/3771d8dec6a95699d32387b8805f0efe) :** Link(s) of logs and crash reports if you have

**Steps to Reproduce :**
 1. Join server
 2. enter the command to view inventory

**Description of issue :** Give all details about your issue
I get an error when entering a command: "An internal error occured while attempting to perform this command

**Comment by Mgazul** [comment]
SeePlayerInventory only supports 1.16.5

**Comment by QuQuShKa1205** [comment]
Similar problem with InvSee++ plugin
https://gist.github.com/QuQuShKa1205/0f4021013acf05e2a9886b07591a85be
https://gist.github.com/QuQuShKa1205/502f3f5dfe1b2cd061baa59820826a6f

**Comment by Mgazul** [comment]
This is not our problem and needs to be fixed by the plugin author
