### ISSUE TITLE
[1.20.1] Crash When Right-Clicking Anything in Server

### ISSUE THREAD

**Issue by CiciHoneyBee** [Teneted/Tenet#3099]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {mohist-1.20.1-661}

**Operating System :** {Windows 11 Pro}

**Logs :** https://gist.github.com/CiciHoneyBee/94c14e34c12f2f31798efdedaad52859

**Mod list :** 

![Screenshot (208)](https://github.com/MohistMC/Mohist/assets/166247139/1c802d8c-ce21-4ce9-bab2-c86e65bfbf5c)

![Screenshot (209)](https://github.com/MohistMC/Mohist/assets/166247139/1bf88477-5f9c-47b7-8018-2a4eacfea6a2)

![Screenshot (210)](https://github.com/MohistMC/Mohist/assets/166247139/39cbb775-e46d-4373-9b5f-c57b7b95d975)

![Screenshot (211)](https://github.com/MohistMC/Mohist/assets/166247139/97e04942-d273-409f-96dc-d6de8a63c5ad)

![Screenshot (212)](https://github.com/MohistMC/Mohist/assets/166247139/02c6e032-18fb-4c26-be87-afba9ffdb9a9)

![Screenshot (213)](https://github.com/MohistMC/Mohist/assets/166247139/eee43e17-21b6-4efe-9442-d3c2ccb66bf9)

**Plugin list :**

![Screenshot (214)](https://github.com/MohistMC/Mohist/assets/166247139/c9b746d9-b6df-4e38-a475-18effba49a57)

**Description of issue :** {When I right-click or attempt to place anything in the server, I crash immediately. Also I have never reported a crash before so I apologize if I did something incorrectly.}

**Comment by Mgazul** [comment]
The error comes from "me.shedaniel.rareice.forge.RareIce", which uses the wrong block id: rare-ice:rare_ice

**Comment by CiciHoneyBee** [comment]
Oooh I see, thank you very much!
