### ISSUE TITLE
java.lang.ClassCastException: com.someguyssoftware.treasure2.tileentity.GravestoneProximitySpawnerTileEntity cannot be cast to com.someguyssoftware.treasure2.tileentity.AbstractTreasureChestTileEntity

### ISSUE THREAD

**Issue by modcraftmc** [Teneted/Tenet#310]
**Describe the bug**
my server crash with this errror
i don't know why. see crash report
[crash-2020-05-30_17.20.45-server.txt](https://github.com/Mohist-Community/Mohist/files/4706154/crash-2020-05-30_17.20.45-server.txt)

**To Reproduce**
idk

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by modcraftmc** [comment]
https://www.curseforge.com/minecraft/mc-mods/treasure2
this mod cause crash

**Comment by TansuoTro** [comment]
Ok
