### ISSUE TITLE
Respawn point lost after respawn, next time when a player dies he respawns to world's respawn point

### ISSUE THREAD

**Issue by QyInvoLing** [Teneted/Tenet#3104]
**Minecraft Version :** 1.20.1

**Mohist Version :** 663

**Operating System :** Win11

**Logs :** Nothing got logged

**Mod list :** 
```
[openpartiesandclaims, geckolib, cccbridge, playeranimator, palladiumcore, immersive_aircraft, ritchiesprojectilelib, citadel, mixinextras, carryon, cloth_config, twilightforest, mcwbridges, farmersdelight, casualness_delight, ends_delight, vintagedelight, spark, cataclysm, curios, patchouli, mr_dungeons_andtaverns, worldedit, twilightdelight, cfm, architectury, computercraft, l2library, t_and_t, fastleafdecay, cuisinedelight, elytraslot, createbigcannons, xtraarrows, unusual_delight, amendments, jei, callablehorses, yes_steve_model, caelus, mr_blossom_blade, integrated_api, travelersbackpack, terralith, memoryleakfix, forge, mohist, idas, tectonic, minecraft, alexscaves, voicechat, terrablender, moonlight, mixinsquared, jade, vc_gliders, nethersdelight, kotlinforforge, flywheel, create, zeta, quark, supplementaries, valkyrienskies, vs_eureka, vs_clockwork, cc_vs, crabbersdelight, fruitsdelight, cristellib]
```

**Plugin list :** 
```
 LuckPerms, SpigotPing, OpeNLogin, ConsoleFilter, PlaceholderAPI, CustomWelcome, DisableCommands, Prism, LPC, ProtocolLib, LiteAnnouncer, nLogin, SuperVanish, PlugManX (PlugMan), Mohist
```

**Description of issue :** 
According to vanilla's feature, players can use beds to set their respawn point. However, when using mohist, after a player's respawn, his respawn point would be cleared by the server, which means he got respawn at his bed, and if he doesn't click on the bed before he dies again, he'll find that he respawned at the overworld's respawn point. The 'keepInventory' gamerule doesn't affect this behaviour.
按照原版特性，玩家可以用床设置重生点，但在使用mohist开服时，玩家死了复活之后会丢失他们设置的重生点信息，导致他们死完复活在自己的床边之后，如果不再点一下床设置重生点，那下一次死就会让他们回到主世界的重生点。keepInventory不会影响这个现象。

**Comment by anazhaba** [comment]
The same problem, even without mods or plugins installed.

**Comment by linkarvane** [comment]
Same problem

**Comment by VideoGamerRUS** [comment]
I have too
