### ISSUE TITLE
[1.20.1] Crash with the Critters and Companians mod

### ISSUE THREAD

**Issue by CiciHoneyBee** [Teneted/Tenet#3105]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-665

**Operating System :** Windows 11 Pro

**Concerned mod / plugin** : Critters and Companions - https://www.curseforge.com/minecraft/mc-mods/critters-and-companions/files/5296137

**Logs :** https://gist.github.com/CiciHoneyBee/cd780c2a4d3a55be3afc73e58480779f

**Steps to Reproduce :**
 
1. I included these mods and plugins:

mods:

![Screenshot (221)](https://github.com/MohistMC/Mohist/assets/166247139/854d64e0-ac81-4e43-9841-38b24a8b466a)

![Screenshot (222)](https://github.com/MohistMC/Mohist/assets/166247139/15368950-a407-4584-8e71-b495f89eda26)

![Screenshot (223)](https://github.com/MohistMC/Mohist/assets/166247139/3742d84a-381a-47c9-af5e-8f04845d997e)

![Screenshot (224)](https://github.com/MohistMC/Mohist/assets/166247139/41c726fc-e4f1-4e39-be57-bdb6b772ff14)

![Screenshot (225)](https://github.com/MohistMC/Mohist/assets/166247139/a16f8720-a65e-4903-881e-5011aba3377c)

![Screenshot (226)](https://github.com/MohistMC/Mohist/assets/166247139/8398ae62-c795-4274-8fc8-bfcd0f47869d)

plugins:
 
![Screenshot (227)](https://github.com/MohistMC/Mohist/assets/166247139/d30845da-0ec8-4faa-b4b5-7615ad5dfe40)

2. I then started the server with the start.bat.

**Description of issue :** MohistMC crash on startup when using the Critters and Companions mod.

**Comment by Mgazul** [comment]
crittersandcompanions uses the client class in the server

**Comment by CiciHoneyBee** [comment]
When I attempt to join the server with crittersandcompanions as a client side, it fails and tells me that the server is missing the mod or to remove the mod altogether
