### ISSUE TITLE
[1.20.1]Can't use the plugin "Zmusic" correctly 不能正常使用Zmusic插件[resolved-解决]

### ISSUE THREAD

**Issue by HighToward** [Teneted/Tenet#3108]
**Minecraft Version :
1.20.1

**Mohist Version :
mohist-1.20.1-665-server

**Operating System :
Windows 11

**Concerned mod / plugin** : 
zmuisc (plugin)

**Logs :
do not have any wrong with the Logs

**Steps to Reproduce :**
1.进入服务器
2.使用/zmuisc play 163 star后播放音乐没有声音
3.bossbar正常显示音频歌词等内容

**Description of issue :
无法正常使用该插件
插件链接为：[https://www.spigotmc.org/resources/zmusic-1-20-ready-powerful-music-system.83027/](url)

**Comment by 5ur3z** [comment]
有没有可能这个还需要客户端装mod

**Comment by HighToward** [comment]
> 有没有可能这个还需要客户端装mod

装了，也是没用的，一点声音都无

**Comment by HighToward** [comment]
So whoelse can fix this bug
Server plugin and client mods doesn’t make it work that play the music

**Comment by ProjectSky** [comment]
我也装了这个插件，一切正常。所以你需要自行排除是否为音量/设备之类的问题

**Comment by HighToward** [comment]
> 我也装了这个插件，一切正常。所以你需要自行排除是否为音量/设备之类的问题

怎么可能是设备的问题，你这个说了跟没说一样，我还以为你会说没有声音可能跟mods有关。。。

**Comment by HighToward** [comment]
解决办法如下：

删除 Forgified Fabric API mod

【此操作可能会导致Fabric模组无法在Mohist Forge服务端上使用，谨慎删除】
