### ISSUE TITLE
[1.19.2] Multiverse core and griefprevention can't see overworld

### ISSUE THREAD

**Issue by bmd070** [Teneted/Tenet#3109]
**Minecraft Version :** 1.19.2

**Mohist Version :** 27.04.2024

**Operating System :** Windows 10

**Concerned mod / plugin** : [plgsnow.zip](https://github.com/MohistMC/Mohist/files/15200024/plg.zip)
**Logs :** [latest.log](https://github.com/MohistMC/Mohist/files/15200226/latest.log)
**Config file of griefprevention** :  [config.txt](https://github.com/MohistMC/Mohist/files/15200240/config.txt)

**Steps to Reproduce :**
 1. I downloaded Forge
 2. I played with 70 mods
 3. I downloaded Mohist
 4. I install plugins
 5. I ran server
 6. Spawn in the nether or in the end (if multiverse core)
 7. Griefprevention plugin write "Land claims are disabled in this world"
 10. I tried to find solution for this problem
 11. I didn't find the solution
 12. I changed config file but it still don't work
 13. I tried to set spawn in overworld but after death it teleport me to thee nether
 14. I deleted DIM1 and DIM-1
 15. I am spawned in the end
 16. I uninstall multiverse core
 17. I am spawned in overworld but griefprevention still write "Land claims are disabled in this world"
 18. I go to the nether
 19. Griefprevention write "Claim created"
 20. I deleted this claim
 21. I'm writing this

**Description of issue :** I don't how it happen but I think that world don't want to divide on overworld, nether and the end and don't see overworld (This is one folder "World")
![Снимок экрана 2024-05-03 160130](https://github.com/MohistMC/Mohist/assets/132436585/56e21ca5-5cac-4afb-ba49-df03d7e24bcf)
![Снимок экрана 2024-05-03 154300](https://github.com/MohistMC/Mohist/assets/132436585/22c69722-a6b8-40ec-8a70-d8ce408cc970)

**Comment by Mgazul** [comment]
1.19.2 is not expected to be updated again
