### ISSUE TITLE
[1.20.1]velocity下连接客户端显示Packet 0/61 (ClientboundRecipePacket) was larger than I expcted

### ISSUE THREAD

**Issue by YukiRiiNa** [Teneted/Tenet#3110]
Minecraft Version : 1.20.1

Mohist Version :** 699 (the latest)
![image](https://github.com/MohistMC/Mohist/assets/39652411/b42c8c9f-43d4-4d55-a205-31e6308c6248)

Operating System : Windows Server 2019

Logs : 日志无报错
![image](https://github.com/MohistMC/Mohist/assets/39652411/4db18c47-07a9-460a-8a49-d00f76d5507d)
![image](https://github.com/MohistMC/Mohist/assets/39652411/bd8a1965-f4a3-4dc5-b5d4-10ec60d3563d)

Mod list :
![image](https://github.com/MohistMC/Mohist/assets/39652411/be6dc681-db59-4f71-b87a-1f823bc892bb)
![image](https://github.com/MohistMC/Mohist/assets/39652411/94863457-310b-42a5-bf34-ab81fef7b9fb)
![image](https://github.com/MohistMC/Mohist/assets/39652411/ab803533-5bfd-438d-bef9-b665a994d7a9)

Plugin list :
![image](https://github.com/MohistMC/Mohist/assets/39652411/1e698bfc-6fff-43f1-9cb4-320413460517)
![image](https://github.com/MohistMC/Mohist/assets/39652411/a49e8907-97b2-479d-ab52-1b121723ddcb)

Description of issue :
![image](https://github.com/MohistMC/Mohist/assets/39652411/15d34b20-1eaf-45cd-afa9-321bdb2889d6)
客户端无法连接，显示如上

**Comment by Mgazul** [comment]
你需要安装一个vc插件 https://modrinth.com/plugin/ambassador
