### ISSUE TITLE
Fix please new version plugin MythicCraft

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3111]
Minecraft Version : 1.20.1

Mohist Version : 1.20.1-702

Operating System :* Linux

Mod: not mods 

Plugin:  Actions, AdvancedChests, AdvancedPets, Adyeshach, ajLeaderboards, AquaticCrates, BetonQuest, BetonQuestGUI, BetterHud, Boosters, BugReport, Chemdah, ChemdahUCExpand, CMILib, Codex, ConditionalEvents, Craftorithm, CustomFishing, CustomNameplates, CustomPiglinsTrades, DarkAuctionsX, DecentHolograms, DeluxeMenus, DisableHUD, eco, EcoArmor, EcoEnchants, EcoItems, Economobs, EcoPets, EcoSkills, Essentials, EssentialsSpawn, ExecutableBlocks, ExecutableEvents, ExecutableItems, ExtraStorage, FeatheredBags, FeatheredElection, GeekMail-Pro, GlobalMarketPlus, HeadBlocks, HyronicFriends, Jobs, libreforge, LicenseManager, LuckPerms, MCCoroutine-Sample, MCoreAddon, MineRegion, MiningContest, MIReplacer, MMOCore, MMOItems, MMOXPAddon, ModelEngine, Mohist, MythicAchievements, MythicChanger, MythicCrucible, MythicDungeons, MythicEnchants, MythicLib, MythicLibreforge, MythicMobs, MythicPrefixes, MythicTotem, NBTAPI, Oraxen, OutpostCommander, packetevents, PAPISign, PlaceholderAPI, PlayerPoints, PlugManX, Polymart, ProtocolLib, Reforges, RegionInteraction, RegionPlaceholders, Resources, RoyaleEconomy, RPGInventory, RPGRegions, SalakauCore, SCore, SkinsRestorer, Slabbo, TAB, Talismans, TigerReports, TigerReportsSupports, TopBossSlayer, TopCollections, TopMinion, TradeAudit, TradeSystem, UltimateAdvancementAPI, UltimateClans, UnrealCore, UnrealGUI, UnrealHeartBeat, UnrealHUD, UnrealKeyBoard, UnrealResource, Vault, WorldEdit, WorldGuard, XLTournaments, XPBoosterPlusPlus, ChatControlRed

Logs : https://mclo.gs/9wf3qKN

not work plugins: PathFinder MythicMobs (new version 5.7.0 build 5060) MythicDungeons [1.3.1-SNAPSHOT (Build 203)], MythicEnchants 0.1.0-SNAPSHOT Build 253] and MythicCrucible build [2.1.0 SNAPSHOT 3870]

Fix plz

**Comment by Mgazul** [comment]
MythicMobs uses paper api, And it is also not supported for use in spigot-1.20.1
