### ISSUE TITLE
[1.20.1] Let's Do mod can't read config file

### ISSUE THREAD

**Issue by KaranMaia** [Teneted/Tenet#3114]
**Minecraft Version :** 1.20.1

**Mohist Version :** 668

**Operating System :** Windows 11

**Concerned mod / plugin** : [Let's Do]

**Logs :** (https://pastebin.com/umNuuT8R)

**Steps to Reproduce :**
 1. I started the server with only these mods (that I sucessfully started with Forge Loader)
 2. And it doesn't start

**Description of issue :** I started the server without mods and plugins and it goes just fine. When I added the mods, it crashed like this, haven't tested plugins yet

There are all the mods I'm using
![image](https://github.com/MohistMC/Mohist/assets/73917457/a3f952e7-d1dd-4201-9431-d897d19b8377)
![image](https://github.com/MohistMC/Mohist/assets/73917457/147e0d8d-047e-404d-a998-876c70fb8d52)
![image](https://github.com/MohistMC/Mohist/assets/73917457/0b332693-a294-4704-a169-403c8be6c6f5)

**Comment by Mgazul** [comment]
Unable to reproduce, please delete the config and restart the server

**Comment by Mgazul** [comment]
![image](https://github.com/MohistMC/Mohist/assets/23317456/6d159ee9-fe5d-434f-9b2a-87d45b713a3e)
