### ISSUE TITLE
[1.20.1] TextureSheetParticle and event handler problem

### ISSUE THREAD

**Issue by FunGluck** [Teneted/Tenet#3116]
**Minecraft Version :** 1.20.1

**Mohist Version :** 679

**Operating System :** Windows 10

**Logs :** https://pastebin.com/eSPZTy6Q

**Mod list :** 
![image](https://github.com/MohistMC/Mohist/assets/65889218/335f8073-e412-45a1-83ae-0adb021610a1)
![image](https://github.com/MohistMC/Mohist/assets/65889218/9d65b871-30fe-4cb0-91c5-e1436f00f49d)
![image](https://github.com/MohistMC/Mohist/assets/65889218/bec18e80-c885-4b22-a3cf-6dda7e2547ff)
![image](https://github.com/MohistMC/Mohist/assets/65889218/a721934f-f904-4fd7-a701-4f8d4c4c0cd9)

**Plugin list :** EssentialsX-2.20.1, Vanish

**Description of issue :** When I start the console, this error appears and I do not know how to solve it because I could not find it on the internet

**Comment by Mgazul** [comment]
TextureSheetParticle is a client-side thing. Your server has installed a mod that is only used by the client.

**Comment by FunGluck** [comment]
Do you have any idea what kind of mod it could be?

**Comment by Mgazul** [comment]
I can't tell. There are no errors in the log you posted. Is it an upload error?

**Comment by Mgazul** [comment]
It just throws a warning and does not affect server functionality, you can ignore it
