### ISSUE TITLE
Extreme lag on world save with 1.20.1 680 builds and up

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3121]
Any mohist 1.20.1 build 679 and above has extreme server lag. Versions 679 and below do not have this lag issue (related to world save?) I am using the all the mods 9 pack no plugins.

Build 678
![image](https://github.com/MohistMC/Mohist/assets/9994438/016cff56-d8de-469d-bef9-c7a7f698c40f)
https://spark.lucko.me/l6Y8ALLr7C

Build 679+ 
![image](https://github.com/MohistMC/Mohist/assets/9994438/813eb548-ee32-42ca-8757-cdab57a837f2)
https://spark.lucko.me/tbwKxxE5LU

This is what it looks like with build 688 on an actual server.
![image](https://github.com/MohistMC/Mohist/assets/9994438/402d6f9e-87f0-4406-a849-511cb69319a5)

**EDIT: Corrected it starts are build 679. Build 678 and below works perfect**

**Comment by Unitei-Dev** [comment]
You would still download everything from Modrinth and CurseForge on 1.20.1 (in 4k mods)   ))))

**Comment by funnycubeguy** [comment]
> You would still download everything from Modrinth and CurseForge on 1.20.1 (in 4k mods) ))))

What?

**Comment by Mgazul** [comment]
Fixed
