### ISSUE TITLE
1.20.1 Big lag on game save with recent update

### ISSUE THREAD

**Issue by funnycubeguy** [Teneted/Tenet#3122]
Build 678 the save game is fast takes 3 seconds no tps drop. Build 691 the save game takes 10 - 20 seconds and causes a big lag spike and tps drop.

This happens on all builds above 678 still. You can test with /save-all while flying. I tested this with the all the mods 9 pack.

**Comment by Mgazul** [comment]
Because we need to generate a level.dat for each world and save it, this is what the bukkit plug-in requires.

**Comment by funnycubeguy** [comment]
> Because we need to generate a level.dat for each world and save it, this is what the bukkit plug-in requires.

Is there a way to disable it really ruins the game for people since the server lags hard every 5 minutes. I didn't noticed a difference with any of my bukkit plugins they all seem to work with the worlds
