### ISSUE TITLE
[1.12.2] Downloading libraries failed

### ISSUE THREAD

**Issue by SuperSCNova** [Teneted/Tenet#3128]
**Minecraft Version :** {1.12.2}

**Mohist Version :** {mohist-1.12.2-265-server}

**Operating System :** {Win Server 2019}

**Logs :** {}

**Mod list :** {no mods}

**Plugin list :** {no plugins}

**Description of issue :** {
On serverstart getting infinit loop of Downloading file: log4j-... You can download it manually: https://maven.mohistmc.com/libraries/org/apache/logging/log4j/log4j-core/2.15.0/...

Version 2.15.0 does not exist anymore
}

**Comment by SuperSCNova** [comment]
Fixed my issue for now with disableing the "check_libraries: false" & "check_updates: false" setting

**Comment by Mgazul** [comment]
mohist-1.12.2-265-server is obsolete and no longer supported
