### ISSUE TITLE
Skript

### ISSUE THREAD

**Issue by idunnoooooo** [Teneted/Tenet#314]
is there a way to use skript with mohist?

**Comment by Shawiizz** [comment]
Hi ! Skript is working on Mohist, but we recommend the use of Skript 2.2 dev37c not to have a lot of bugs. If you want to install another version of Skript just type no when the server asking you if you want to download the right version of Skript or just disable the plugin checker in mohist.yml (it's explained in the message when server ask).

**Comment by idunnoooooo** [comment]
@Shawiizz thanks!
