### ISSUE TITLE
[1.20.1] Campfires Do Not Cook

### ISSUE THREAD

**Issue by Vexadros** [Teneted/Tenet#3140]
**Minecraft Version :** 1.20.1

**Mohist Version :** 734

**Operating System :** Arch Linux/Windows 10 Pro 22H2

**Logs :** No logs

**Mod list :** No Mods

**Plugin list :** No plugins

**Description of issue :** Campfires never complete cooking, raw food can be placed and retrieved from breaking the campfire, but they will never become cooked. Tested from a completely new server with no mods/plugins or config changes. Can't recreate the issue on forge, spigot, or bukkit servers.

**Comment by glowingstone124** [comment]
终于还是在修😭😭😭
