### ISSUE TITLE
启动的时候报错

### ISSUE THREAD

**Issue by RedCarl** [Teneted/Tenet#3150]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {Mohist - 1.20.1-735}

**Operating System :** {Ubuntu24.04}

**Logs :** {https://privatebin.net/?5e039ae253be625d#9XvQDmrubZnPs2JtAXTxbLEJsVBA8dqGKkamwFQUWj8X}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Give all details about your issue}

**Comment by glowingstone124** [comment]
where is your -jar argument?

**Comment by RedCarl** [comment]
抱歉，您看一下这个log
https://paste.fastmirror.net/?a8093bcdf0a8f9ae#8byoCuYrtfyTNHJQzE5rcKu5ERYP8LVygTE2rXBAUavo
