### ISSUE TITLE
[1.20.1] Mohist 启动报错

### ISSUE THREAD

**Issue by RedCarl** [Teneted/Tenet#3154]
Minecraft Version : 1.20.1

Mohist Version : Mohist - 1.20.1-736

Operating System : Ubuntu24.04

Logs : https://paste.fastmirror.net/?a8093bcdf0a8f9ae#8byoCuYrtfyTNHJQzE5rcKu5ERYP8LVygTE2rXBAUavo

Mod list : 
> forge mods 
[10:00:11 INFO]: Mod List: 
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• mods_folder FarmersDelight-1.20.1-1.2.4.jar : farmersdelight (1.20.1-1.2.4) - 1
• mods_folder proxy-compatible-forge-1.20-1.1.4.jar : pcf (1.20-1.1.4) - 1
• JarInJar kffmod-4.10.0.jar : kotlinforforge (4.10.0) - 1
• minecraft forge-1.20.1-47.2.32-universal.jar : forge (47.2.32) - 2
• mods_folder Cobblemon-forge-1.5.2+1.20.1.jar : cobblemon (1.5.2+1.20.1) - 1

Plugin list : 
> pl
[10:00:51 INFO]: Plugins (12): LuckPerms, spark, NBTAPI, Vault, ProtocolLib, TAB, FastAsyncWorldEdit (WorldEdit), DecentHolograms, WorldGuard, Citizens, OociCore, Mohist

Description of issue : 启动服务器后报错，暂不影响正常运行。

**Comment by Mgazul** [comment]
这不是核心的问题，是某个mod引起的
