### ISSUE TITLE
[1.12.2] Worlds not unloading.

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#317]
Worlds not unloading, adding extra tick time to the server.
Seems to be mainly Galacticraft.

![Screenshot_72](https://user-images.githubusercontent.com/3002248/83569674-b339f580-a4d9-11ea-953d-dcf275806a0a.png)

**Comment by TheDeafCreeper** [comment]
You could try this mod: https://www.curseforge.com/minecraft/mc-mods/unloader until its fixed in Mohist

**Comment by Zilacon** [comment]
It doesnt work.

**Comment by Zilacon** [comment]
Can this please be fixed? This is kind of a major problem...

**Comment by Shawiizz** [comment]
Hey, how can i reproduce that on my server please ?

**Comment by Zilacon** [comment]
Use galacticraft.

**Comment by Shawiizz** [comment]
Ok, i will test later
