### ISSUE TITLE
Mohist load times too long

### ISSUE THREAD

**Issue by PSYCHOFOX81** [Teneted/Tenet#3172]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {705}

**Operating System :** {Linux i believe ubuntu}

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue :** {Okay so its a very simple issue. Even on a freash install (No plugins or mods) i sit on the MOHIST logo splash text screen for 60-120 seconds even with update checker disabled. On other hybrids like magma/arclight it doesnt do this. Why use Mohist over the other two that clearly works? Well Magma like to crap out all 12 of my dims from ad astral into the main directory and arclight doesnt like one of my plugins. So i beg of you developers please fix these oddly long load times. Thank you so much for all your hard work and dedication. Mohist is truely one of the best hybrids a man could ask for. (My discord is gamingfoxy81 if you want more info because theres no guarantee i'll look back here) }

**Comment by AnVir** [comment]
The same issue. Each restart - like +3 minutes to wait, maybe more.

![изображение](https://github.com/MohistMC/Mohist/assets/4398167/1d449676-99af-4d2b-91f0-04df3a85822f)
