### ISSUE TITLE
[1.20.1] Multiverse & Difficulty reset

### ISSUE THREAD

**Issue by Akumas76** [Teneted/Tenet#3173]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {mohist-1.20.1-705-server.jar}

**Operating System :** {Window10}

**Plugin list :** {Multiverse-core 4.3.12 OrMyWorlds-1.20.6-v1-294}

**Description of issue :** {I created a fresh Mohist server with no mods, but I wanted multi-world functionality, so I used Multiverse Core (and later tested MyWorld).

Multiverse: The world is created in Easy mode. I use /mv modify set difficulty hard to set the difficulty to Hard for the newly created world. When I check the config, it shows as HARD, but after restarting the server, the world reverts to Easy mode. The main world (world) stays in Hard mode when set through server.properties.

MyWorld: Similar situation. I create a world, set it to HARD, and it remains in Hard mode. However, when I use /difficulty, it shows as Easy, and pressing F3 indicates the world is in Easy mode with no local difficulty.

I've tried modifying config files, using plugins, and mods that lock difficulty, but nothing works. Something keeps changing the difficulty. On Mohist build 502, everything worked fine without this issue. Does anyone have any ideas?

Thx for helping}

**Comment by tokie1298** [comment]
我再次遇到了这个问题，在mohist-1.20.1-917-server上
