### ISSUE TITLE
[1.18.2] 生物在正常击杀后自动触发不死图腾

### ISSUE THREAD

**Issue by 8MiYile** [Teneted/Tenet#3180]
**What is your question ?**
版本 1.18.2-174
想知道如何上传视频，我这有录制(视频文件大于github标准，不被允许上传成功)

**Comment by Pisces-Moze** [comment]
确实

**Comment by Pisces-Moze** [comment]
你可以使用更早的版本

**Comment by 8MiYile** [comment]
@bzmid 前一个版本有暮色的实体崩溃问题 才更新的
