### ISSUE TITLE
[1.20.1] Mythic Dungeons incompatibility with Alex Caves

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#3190]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-724

**Operating System :** Windows 10

**Concerned mod / plugin** :  https://www.spigotmc.org/resources/mythicdungeons.102699/

**Logs :** 
Latest log: https://gist.github.com/Talan67/d06b8b48669644a8000b19ccaa870f88
Debug log: https://gist.github.com/Talan67/ca2a49e03e9fb09e5c54f2f0f6ce6e5e

**Steps to Reproduce :**
1. Install Mythic Dungeons, ProtocolLib, Alex Caves and Citadel
2. Create a dungeon with /md create (dungeon name), I used "test" in the logs
3, Edit the dungeon with /md edit (dungeon name)
4. Error and failure to load into dungeon
5. Also tried playing the dungeon with /md play (dungeon name) to no avail

**Description of issue :**  Install plugins and mods mentioned above, create a dungeon, try to play/edit said dungeon and Error.
Alex caves is adding in a new mob spawn condition which conflicts with Mythic Dungeons.

**Comment by Unitei-Dev** [comment]
Wouldn't it be easier for you to use Mythic Dungeons 1.4.0 from MythicCraft rather than this buggy plugin?

**Comment by Talan67** [comment]
wdym its the same plugin??

**Comment by NeverPixel** [comment]
https://mclo.gs/veCBKHf

**Comment by Unitei-Dev** [comment]
Нет, это от MythicCraft, но да они почти одинаковые
