### ISSUE TITLE
尝试使用信雅互联加载迷上城建报错

### ISSUE THREAD

**Issue by Qha821** [Teneted/Tenet#3191]
**Minecraft Version :1.20.1

**Mohist Version :1.20.1-758(在服务器后台终端显示)

**Operating System :MCSManager On Ubuntu

**Logs :https://gist.github.com/Jeyzhen/bce5f53213e8e0b1d51938ba624a138a

**Mod list : Loading 107 mods:
	- adorn 5.0.1+1.20.1
	- aft_fabroads 1.0.2
	- architectury 9.2.14
	- automobility 0.4.2+1.20.1-forge
	- bclib 3.0.14
	- betterend 4.0.11
	- blockus 2.7.151.20.1
	- blue_endless_jankson 1.2.2
	- brrp_v1 1.0.1
	- chatimage 1.2.4+1.20.1+forge
		\-- actionlib 0.9.3
	- com_github_llamalad7_mixinextras 0.2.0
	- computercraft 1.111.0
	- connectorextras 1.11.1+1.20.1
		|-- amecsapi 1.5.3+mc1.20-pre1
		|-- connectorextras_architectury_bridge 1.11.1+1.20.1
		|-- connectorextras_continuity_compat 1.11.1+1.20.1
		|-- connectorextras_emi_bridge 1.11.1+1.20.1
		|-- connectorextras_energy_bridge 1.11.1+1.20.1
		|-- connectorextras_geckolib_fabric_compat 1.11.1+1.20.1
		|-- connectorextras_jei_bridge 1.11.1+1.20.1
		|-- connectorextras_kubejs_bridge 1.11.1+1.20.1
		|-- connectorextras_modmenu_bridge 1.11.1+1.20.1
			\-- modmenu 7.2.2
		|-- connectorextras_pehkui_bridge 1.11.1+1.20.1
		|-- connectorextras_rei_bridge 1.11.1+1.20.1
		|-- connectorextras_terrablender_bridge 1.11.1+1.20.1
		|-- forgeconfigapiport 8.0.0
		\-- reach_entity_attributes 2.4.0
	- connectormod 1.0.0-beta.44+1.20.1
	- create 0.5.1.f
		\-- flywheel 0.6.10-7
	- curtain 1.3.2
	- diagonalfences 8.1.4
		\-- diagonalblocks 8.0.5
	- entityculling 1.6.6
	- fabric_api 0.92.2+1.11.8+1.20.1
		|-- fabric_api_base 0.4.31+ef105b4977
		|-- fabric_api_lookup_api_v1 1.6.36+67f9824077
		|-- fabric_biome_api_v1 13.0.13+dc36698e77
		|-- fabric_block_api_v1 1.0.11+0e6cb7f777
		|-- fabric_block_view_api_v2 1.0.1+0767707077
		|-- fabric_blockrenderlayer_v1 1.1.41+1d0da21e77
		|-- fabric_client_tags_api_v1 1.1.2+5d6761b877
		|-- fabric_command_api_v1 1.2.34+f71b366f77
		|-- fabric_command_api_v2 2.2.13+561530ec77
		|-- fabric_content_registries_v0 4.0.11+a670df1e77
		|-- fabric_convention_tags_v1 1.5.5+fa3d1c0177
		|-- fabric_data_attachment_api_v1 1.0.0+30ef839e77
		|-- fabric_data_generation_api_v1 12.3.4+369cb3a477
		|-- fabric_dimensions_v1 2.1.54+8005d10d77
		|-- fabric_entity_events_v1 1.6.0+6274ab9d77
		|-- fabric_events_interaction_v0 0.6.2+0d0bd5a777
		|-- fabric_game_rule_api_v1 1.0.40+683d4da877
		|-- fabric_item_api_v1 2.1.28+4d0bbcfa77
		|-- fabric_item_group_api_v1 4.0.12+c9161c2d77
		|-- fabric_key_binding_api_v1 1.0.37+561530ec77
		|-- fabric_lifecycle_events_v1 2.2.22+afab492177
		|-- fabric_loot_api_v2 1.2.1+eb28f93e77
		|-- fabric_message_api_v1 5.1.9+52cc178c77
		|-- fabric_mining_level_api_v1 2.1.50+561530ec77
		|-- fabric_model_loading_api_v1 1.0.3+6274ab9d77
		|-- fabric_models_v0 0.4.2+7c3892a477
		|-- fabric_networking_api_v1 1.3.11+503a202477
		|-- fabric_object_builder_api_v1 11.1.3+2174fc8477
		|-- fabric_particles_v1 1.1.2+78e1ecb877
		|-- fabric_recipe_api_v1 1.0.21+514a076577
		|-- fabric_registry_sync_v0 2.3.3+1c0ea72177
		|-- fabric_renderer_api_v1 3.2.1+1d29b44577
		|-- fabric_renderer_indigo 1.5.2+b5b2da4177
		|-- fabric_rendering_data_attachment_v1 0.3.37+a6081afc77
		|-- fabric_rendering_fluids_v1 3.0.28+4ac5e37a77
		|-- fabric_rendering_v1 3.0.8+66e9a48f77
		|-- fabric_resource_conditions_api_v1 2.3.8+9ad825cd77
		|-- fabric_resource_loader_v0 0.11.10+bcd08ed377
		|-- fabric_screen_api_v1 2.0.8+45a670a577
		|-- fabric_screen_handler_api_v1 1.3.30+561530ec77
		|-- fabric_sound_api_v1 1.0.13+4f23bd8477
		|-- fabric_transfer_api_v1 3.3.5+631c9cd677
		\-- fabric_transitive_access_wideners_v1 4.3.1+1880499877
	- forge 47.3.1
		\-- mohist 1.20.1
	- immediatelyfast 1.2.18+1.20.4
		\-- mixinextras 0.3.6
	- immersive_paintings 0.6.7+1.20.1
	- jankson 5.0.1j1.2.2
	- jsblock 2.0.0-beta-2+1.20.1
	- kotlinforforge 4.11.0
	- libgui 8.0.01.20
	- libninepatch 1.2.0
	- londonunderground 2.2.0
	- minecraft 1.20.1
	- mishanguc 1.3.0
	- modernfix 5.18.1+mc1.20.1
	- msd 1.3.5
	- mtr 4.0.0-beta-8
	- neruina 2.0.0-beta.10
	- nochatreports 1.20.1-v2.2.2
	- patchouli 1.20.1-84-FORGE
	- puzzleslib 8.1.20
		\-- puzzlesaccessapi 8.0.7
	- railways 1.6.4+forge-mc1.20.1
	- russianmetro 4.0.0-2.0.0-beta-2
	- slide_show 0.8.4
	- terraform_wood_api_v1 7.0.2
	- worldedit 7.2.15+6463-5ca4dff
	- wunderlib 1.1.5
	- yuushya 2.1.1
	- yuushya_modelling 2.0.0

**Plugin list :没加

**Description of issue :如果移除迷上城建模组，服务器可以正常启动以及添加插件，但是一旦加入了，就会导致报错（日志最后），使用了信雅互联Beta44，信雅互联附加最新版，FFAPI最新版，BRRP最新版，迷上城建最新版

**Comment by Qha821** [comment]
@Mgazul 这个问题可以在将来被修复嘛？

**Comment by glowingstone124** [comment]
你的mod有一部分是需要客户端的，删掉

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Qha821** [comment]
@glowingstone124 我已经删除了，但还是报了同样的错误，现在更新到最新版了

**Comment by Qha821** [comment]
已通过其它方法解决该问题，所以我会关闭此议题
