### ISSUE TITLE
[1.20.1] 使用Connector出现java.lang.NoClassDefFoundError (不通过Connector的部分mod也有相同的问题)

### ISSUE THREAD

**Issue by BiliRumble** [Teneted/Tenet#3207]
**Minecraft Version :** 1.20.1
**Mohist Version :** mohist-1.20.1-727-server
**Operating System :** Windows 11 专业版 23H2

**Concerned mod / plugin** : 
1. [Universal Sawmill](https://www.curseforge.com/minecraft/mc-mods/sawmill)
2. [L2 Library](https://modrinth.com/mod/l2library/)
3. [Create Big Cannons](https://modrinth.com/mod/create-big-cannons)
4. [Blue Skies](https://modrinth.com/mod/blue-skies)
5. [Immersive Aircraft](https://modrinth.com/mod/immersive-aircraft)
6. [Carry On](https://www.curseforge.com/minecraft/mc-mods/carry-on)
7. [Hearth & Home](https://www.curseforge.com/minecraft/mc-mods/hearth-and-home)
8. [Create](https://www.curseforge.com/minecraft/mc-mods/create)
9. [Create: Central Kitchen](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
10. [Extended Cogwheels](https://www.curseforge.com/minecraft/mc-mods/create-extended-cogs)
11. [What Are They Up To](https://modrinth.com/mod/what-are-they-up-to/version/1.20.1-1.1.1)
12. [Friends&Foes](https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge)
13. [Moonlight Library](https://modrinth.com/mod/moonlight)
14. [Another Furniture](https://modrinth.com/mod/another-furniture)
15. [Supplementaries](https://modrinth.com/mod/supplementaries)

**Logs :** 
1. [Log](https://mclo.gs/AASUAAG)
2. [crash-report](https://mclo.gs/6Fx4bGB)

**Steps to Reproduce :**
 1. 将客户端(魔改版的BetterMC)mod复制到Mohist服务端并删除客户端独有mod
 2. 启动Mohist
 3. 服务端崩溃*

**Description of issue :**
1. 相同操作在原生forge可以正常启动
2. 出现类似于
```
[18:22:16 WARN]: Injection warning: LVT in net/minecraft/server/players/PlayerList::m_11236_(Lnet/minecraft/server/level/ServerPlayer;Z)Lnet/minecraft/server/level/ServerPlayer; has incompatible changes at opcode 674 in callback dehydration.mixins.json:PlayerManagerMixin from mod dehydration->@Inject::respawnPlayerMixin(Lnet/minecraft/server/level/ServerPlayer;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/core/BlockPos;FZLnet/minecraft/server/level/ServerLevel;Ljava/util/Optional;Lnet/minecraft/server/level/ServerLevel;Lnet/minecraft/server/level/ServerPlayer;)V.
 Expected: [Lnet/minecraft/core/BlockPos;, F, Z, Lnet/minecraft/server/level/ServerLevel;, Ljava/util/Optional;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;]
    Found: [Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;, Z, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerLevel;]
Available: [Lnet/minecraft/core/BlockPos;, F, Z, Lorg/bukkit/World;, Z, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerLevel;, Lnet/minecraft/server/level/ServerPlayer;, B, Lnet/minecraft/world/level/storage/LevelData;, Lnet/minecraft/world/phys/Vec3;, F, Lnet/minecraft/world/phys/Vec3;]
```
的Warn
3. 此操作可以在和Mohist类似的服务端复现
4. 这是[服务端](http://server.whcraft.top:9502/s/W7IP) - 30日后过期

**Comment by BiliRumble** [comment]
已经搞了两天了QWQ

**Comment by Unitei-Dev** [comment]
![image](https://github.com/MohistMC/Mohist/assets/136928305/293744bf-f8e9-4769-b326-500973cfbb61)

> 已经搞了两天了QWQ

**Comment by Mgazul** [comment]
remove dehydration mod

**Comment by BiliRumble** [comment]
ok修好了
