### ISSUE TITLE
关于模组传送机制与（任何）背包隔离插件的BUG

### ISSUE THREAD

**Issue by zoe-may** [Teneted/Tenet#3221]
**Minecraft Version :** 1.20.1

**Mohist Version :** 761,

**Operating System :** Windows

**Logs :** 似乎没有

**Mod list :** <script src="https://gist.github.com/zoe-may/dbd6893dbd9c10f2c033e5abdfb96b80.js"></script>

**Plugin list :** 不知道为何无法导出
![image](https://github.com/MohistMC/Mohist/assets/71170887/b79e69b2-e744-45c5-97b0-7dcc7b4df241)

**Description of issue :** 
文字描述有点乱，请看视频，群里还有高清版
https://github.com/MohistMC/Mohist/assets/71170887/7b1f0ca3-ff13-4c4f-ad63-b00d0b2c442a

**Comment by Mgazul** [comment]
请提供mod和插件的下载，你这样反馈是无法进行复现测试的

**Comment by zoe-may** [comment]
> 请提供mod和插件的下载，你这样反馈是无法进行复现测试的

好的
插件：三个任选其一（其实市面上的任何背包隔离插件都可以）
https://modrinth.com/plugin/separeworldsitems    （在config.yml设置世分组）
https://www.spigotmc.org/resources/myworlds.39594/    （需要在config.yml中打开"useWorldInventories: true"）
https://modrinth.com/plugin/multiverse-inventories    （需要前置https://modrinth.com/plugin/multiverse-core 
 ）

模组：任何有传送功能的模组
比如传送石碑：https://modrinth.com/mod/waystones
甚至莱特兰-扩充当中的幻梦图腾：https://modrinth.com/mod/l2-complements
（幻梦图腾：https://www.mcmod.cn/item/672763.html    返回的出生点无视[ess插件](https://essentialsx.net/downloads.html)与[lp](https://luckperms.net/download)权限组设置的出生点）

**Comment by Mgazul** [comment]
Fixed
