### ISSUE TITLE
[1.20.1] Crashing not able to find class file.

### ISSUE THREAD

**Issue by MrBloom2037** [Teneted/Tenet#3222]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-775

**Operating System :**  Windows 11 (amd64) version 10.0

**JVM Version:** 21.0.2

**Concerned mod / plugin** : JEG 0.5.3 | JustEnoughGuns | https://www.curseforge.com/minecraft/mc-mods/just-enough-guns

**Logs :** https://pastebin.com/wquP8YY7

**Steps to Reproduce :**
 1. Add mod to mods folder
 2. Start server, server gets to mod initialization.
 3. Server crashes due to the server unable to find the class even though the class file is present.

**Description of issue :** java.lang.NoClassDefFoundError: ttv/migami/jeg/item/AnimatedGunItem is specific to the class but isn't specific as to why it cannot load the mods class file though its present in the jar file.

**Comment by Mgazul** [comment]
Use java17 for testing, don't use java21

**Comment by MrBloom2037** [comment]
> Use java17 for testing, don't use java21

I'll build a version of Mohist standalone to run using JDK 17, I'm unsure its the JVM build thats causing it though.

**Comment by MrBloom2037** [comment]
> Use java17 for testing, don't use java21

https://pastebin.com/dJi8Crj5
Recent crash report with JVM 17.0.11
This is with the mod by itself in the mods directory.

**Comment by Mgazul** [comment]
After testing, you need to install geckolib mod to run

**Comment by MrBloom2037** [comment]
> After testing, you need to install geckolib mod to run

really wow, thank you for letting me know I'll run a test on my experimental server to see if this fixes it.

**Comment by MrBloom2037** [comment]
Your fix was absolutely on point even the mod developer pointed out that, glad for your help it didn't show that the mod was missing in the stacktrace I had so I am shocked you were able to find it.
