### ISSUE TITLE
"Colliding entity with block" internal server error. Crashing everytime anyone goes into end portal

### ISSUE THREAD

**Issue by Jxhne** [Teneted/Tenet#3224]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {748}

**Operating System :** {Windows}

**Logs :** { https://pastebin.com/3WEtgD6m }

**Mod list :** {cant use /getmodlist but modlist is in crash report}

**Plugin list :** {Mohist}

**Description of issue :** {everytime i enter the end portal or another player enters it crashes server, "internal server error"}

**Comment by Mgazul** [comment]
Fixed
