### ISSUE TITLE
[1.20.1] FastMenu插件导致玩家聊天信息无法发送或接收 | FastMenu Plugin causing In-Game Chat messages to disappear

### ISSUE THREAD

**Issue by p0rt39** [Teneted/Tenet#3238]
**Minecraft Version :** 1.20.1

**Mohist Version :** 755

**Operating System :** Windows Server 2022(21H2)

**Concerned mod / plugin** : FastMenu(fmenu-xxx.jar) 
[fmenu-2.7.0.zip](https://github.com/user-attachments/files/16235161/fmenu-2.7.0.zip)

**Logs :**
[latest.log](https://github.com/user-attachments/files/16235166/latest.log)
[debug.log](https://github.com/user-attachments/files/16235167/debug.log)

**Steps to Reproduce :**
 1. Load the plugin above 加载上述插件
 2. Send a message through In-Game Chat 在游戏内聊天发送信息

**Description of issue :** 
根据严格的减法测试，确定了是此插件导致的问题。玩家所发送的聊天信息在控制台和游戏内聊天均不会出现。
According to a strict one-by-one-delete teste,it's ensured that this plugin is causing the problem.All the chat messages will appear in neither server console nor in game.

**Comment by 1766141426** [comment]
dantiao3  和 DreamCleaner  这两个插件使用墨端也有同样的问题，加入去发消息 发不出去 后台也不显示！

**Comment by Mgazul** [comment]
Fixed
