### ISSUE TITLE
[1.19.2] Crash when using "Quark" Mod

### ISSUE THREAD

**Issue by abcdshiwo** [Teneted/Tenet#3241]
**Minecraft Version :** 1.19.2

**Mohist Version :** 130

**Operating System :** Windows 11 (amd64) version

**Concerned mod / plugin** : 
 "Quark" https://modrinth.com/mod/quark
 "Quark" requires "AutoRegLib" https://modrinth.com/mod/autoreglib

**Logs :** 
 https://gist.github.com/abcdshiwo/b818875db5f5c0cff6da0a327e41bd6a
**Steps to Reproduce :**
 1.Add those 2 mods
 2.Then run mohist-1.19.2-130-server.jar
 3.Say "true" to the EULA
 4.Wait for about 1 minute or 2
 5.Crash

**Description of issue :** 
tested with only Quark and AutoRegLib
logs link include "log","crash report","debuglog" . Already make a test only with the "AutoRegLib" and "Quark" mod on both "azul zulu 21 and 17" & "dragonwell 21 and 17" JDK, and all of them got the same crash report.
"AutoRegLib" seems did not cause the problem, I have tested only with "AutoRegLib",and nothing went wrong.

**Comment by CNliaoM** [comment]
同情况，求解。
same proble.

**Comment by Teena-ger** [comment]
Fixed
