### ISSUE TITLE
[1.19.2] Crash with "ImmersivePetroleum" mod

### ISSUE THREAD

**Issue by abcdshiwo** [Teneted/Tenet#3248]
**Minecraft Version :** 1.19.2

**Mohist Version :** 130

**Operating System :** Windows 11 (amd64) version

**Concerned mod / plugin** : 
"_ImmersivePetroleum_"  https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum
"_ImmersivePetroleum_" requires "_ImmersiveEngineering_" https://modrinth.com/mod/immersiveengineering

**Logs :** 
https://gist.github.com/abcdshiwo/97d9b2fe97a0d165dafba828de8dc229

**Steps to Reproduce :**
1.Add those 2 mods
2.Then run mohist-1.19.2-130-server.jar
3.Say "true" to the EULA
4.Wait for about 1 minute or 2
5.Crash

**Description of issue :** 
tested with only _ImmersivePetroleum_ and _ImmersiveEngineering_
logs link include "log","crash report","debuglog" . Already make a test only with the "_ImmersiveEngineering_" and "_ImmersivePetroleum_" mod on both "azul zulu 21 and 17" & "dragonwell 21 and 17" JDK, and all of them got the same crash report.
"_ImmersiveEngineering_" seems did not cause the problem, I have tested only with "_ImmersiveEngineering_",and nothing went wrong.

**Comment by Teena-ger** [comment]
The latest build has been fixed!
