### ISSUE TITLE
[1.20.1] java.lang.NoClassDefFoundError: net/minecraft/server/level/ChunkMap$TrackedEntity

### ISSUE THREAD

**Issue by ASHISK404** [Teneted/Tenet#3258]
**Minecraft Version :** 1.20.1

**Mohist Version :**mohist-1.20.1-771-server

**Operating System :** centos7

**Concerned mod / plugin** : HulisZCrystals-1.0    https://modrinth.com/mod/hulis-z-crystals/version/1.0

**Logs :** [Link(s) of logs and crash reports if you have](https://gist.github.com/ASHISK404/73cfe9c024d35b381a97b606ef727096)

**Steps to Reproduce :**
 1. Install the Sinytra Connector and the module, along with its dependencies
 2. Start the server
 3. In spawning world collapse, and error report java.lang.NoClassDefFoundError: net/minecraft/server/level/ChunkMap$TrackedEntity

**Description of issue :** After installing this mod through the Sinytra Connector, the server crashes while spawning world.It performed well in single player, but on server it would crash on startup

**Comment by Mgazul** [comment]
Fixed
