### ISSUE TITLE
[1.20.1] java.lang.NoClassDefFoundError: net/minecraft/server/level/ChunkMap

### ISSUE THREAD

**Issue by xg787** [Teneted/Tenet#3265]
**Minecraft Version :** 1.20.1

**Mohist Version :** 774

**Operating System :** Windows 10

**Logs :** [crash-2024-07-28_13.19.35-server.txt](https://github.com/user-attachments/files/16404636/crash-2024-07-28_13.19.35-server.txt) [latest.log](https://github.com/user-attachments/files/16404637/latest.log)

**Mod list :** in latest.log

**Plugin list :** no plugins

**Description of issue :** crash on world load

**Comment by Mgazul** [comment]
Fixed by build#811
