### ISSUE TITLE
quark 1.19.2 crash

### ISSUE THREAD

**Issue by Kit1112** [Teneted/Tenet#3281]
**Minecraft Version :** 1.19.2

**Mohist Version :** 138

**Operating System :** Win10

**Logs :**  [latest.log](https://github.com/user-attachments/files/16488660/latest.log)

**Mod list :** Quark-3.4-418, AutoRegLib-1.8.2-55

**Plugin list :** none

**Description of issue :** crash

**Comment by Teena-ger** [comment]
Fixed
