### ISSUE TITLE
[1.20.1] When using EssentialsX Protect, it's "anti-explode" feature is not functionally as expected/当使用EssentialsX Protect时，其防止爆炸类交互摧毁方块的功能出现问题

### ISSUE THREAD

**Issue by 5tanL** [Teneted/Tenet#3289]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-784-server

**Operating System :** Windows11

**Concerned mod / plugin** : 
EssentialsX(https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.21.0-dev+107-7b02d22.jar)
EssentialsX Protect(https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsXProtect-2.21.0-dev+107-7b02d22.jar)

**Logs :** 
https://gist.github.com/5tanL/c6c8f89eca8d657bcbcebc657c4370b4

**Steps to Reproduce :**
 1. Enable the "anti explode" feature in EssentialsXProtect/启动EssentialsX中的防爆功能
![image](https://github.com/user-attachments/assets/40dbf9c7-7373-47d9-8ac3-ae0a1acbd171)

 2.  When something that was disabled are triggered in game/在游戏中，使被禁用“爆炸破坏方块”性质的交互触发(演示视频https://youtu.be/I5j-XUezA0I)

**Description of issue :** Give all details about your issue
Demonstrate video/演示视频:https://youtu.be/I5j-XUezA0I
The problem was only on client, when player reconnects to the server, the "hole" will disappear as nothing happend/问题仅出现在客户端侧，在玩家退出重进后坑洞会恢复
The player is hard to move when they entered the "hole"/当玩家试图进入这种“假坑洞”的情况下，玩家的角色行动会受限
When the player is trying to fill the "hole" with their blocks, the blocks they used will be replaced with the block which it was/当玩家试图用手中的其他方块重建坑洞时，放置的方块会被替换为被破坏前应有的方块
Sorry about my poor English!

**Comment by Unitei-Dev** [comment]
CMI works much better on a hybrid than EssenticalX (because there is Mohist support there)

**Comment by 5tanL** [comment]
> SMI works much better on a hybrid than EssenticalX (because there is Mohist support there)

Sorry to bother, but can I get a link about it? I found some plugins named CMI/SunLight but not SMI

Thanks!

**Comment by Unitei-Dev** [comment]
> CMI

Sorry CMI
