### ISSUE TITLE
[1.20.1] Failed to create mod instance. ModID: asteorbar, class com.afoxxvi.asteorbar.AsteorBarForge java.lang.NoClassDefFoundError: net/minecraft/client/player/LocalPlayer

### ISSUE THREAD

**Issue by TeQTabanca** [Teneted/Tenet#3293]
**Minecraft Version :** 1.20.1

**Mohist Version :** Mohist - 1.20.1-822, Java(22.0.1) 66.0

**Operating System :** Windows

**Concerned mod / plugin** : [asteorbar-forge-1.20.1-1.4.6](https://www.curseforge.com/minecraft/mc-mods/asteorbar/download/5186550)

**Logs :** [Log](https://gist.github.com/TeQTabanca/25cb489bceb799266b69c8674a731be9)

**Steps to Reproduce :**
 1. Add the mod and just run the server.

**Description of issue :** Because of this error, the server becomes unusable.

**Comment by Mgazul** [comment]
asteorbar is a client mod
