### ISSUE TITLE
[1.20.2]不知道什么错误崩溃报告 宝可梦模组

### ISSUE THREAD

**Issue by yuankun1** [Teneted/Tenet#3299]
核心mohist-1.20.2-166-server
模组Pixelmon-1.20.2-9.2.8-server
以下是错误报告
https://paste.ubuntu.com/p/ndMTJ6g5cD/
https://paste.ubuntu.com/p/CsVkrvhpH5/

**Comment by Unitei-Dev** [comment]
Use 1.20.1
In all other versions 1.19.x, as well as in versions 1.20.2 and higher, there is no normal support for mods and plugins

**Comment by yuankun1** [comment]
> 使用 1.20.1 在所有其他版本 1.19.x 以及版本 1.20.2 及更高版本中，没有对 mod 和插件的正常支持



> Use 1.20.1 In all other versions 1.19.x, as well as in versions 1.20.2 and higher, there is no normal support for mods and plugins

But can the Pokémon mod version 1.20.2 run on 1.20.1 Mohist?

**Comment by Unitei-Dev** [comment]
Cobblemon + cobblemon model pokemon

**Comment by Akita041** [comment]
This is not a Mohist issue, it is a design flaw in the Pixelmon Mod 9.2.8，the problem with the defect is that the return value of the senderParty. getOpenStorage() method added in 9.2.8 is null in normal state。Please refer to the picture：
![image](https://github.com/user-attachments/assets/5f782ce7-9bcc-4a97-b860-48d94f57ad48)

[Tip]The repair method is as follows:

PlayerPartyStorage senderParty = StorageProxy.getPartyNow(sender) →     PokemonStorage senderParty = StorageProxy.getStorageNow(sender, this.position1);
PokemonStorage targetStorage = senderParty.getOpenStorage() →  PokemonStorage storage2 = StorageProxy.getStorageNow(sender, this.position2);

Method screenshot：
![image](https://github.com/user-attachments/assets/67f1e48a-70fb-4f29-8cbd-5308ffafe9f8)
