### ISSUE TITLE
JSON API Page 502??

### ISSUE THREAD

**Issue by xiaoyin2011** [Teneted/Tenet#3300]
**[This page](https://new.mohistmc.com/mohistmc-api) can't show its content**
**[This also](https://new.mohistmc.com/mohistmc-api)**
I'm a developer who wants to make a tool to build Mohist Server up automatically

蹩脚的英文QWQ
这两个页面：https://new.mohistmc.com/mohistmc-api的内容一直不会显示，查看网络发现https://new.mohistmc.com/mohistmc-api访问不到。发送请求发现https://new.mohistmc.com/mohistmc-api返回502，一直两天没有解决。
我是一个开发者，希望能够制作一个自动构造Mohist端的服务器的工具，需要能够根据MC版本确定最新稳定构造号并根据构造号获取Forge版本。

遗憾的是，我以前在mohist网页的下载界面制作的爬虫爬取最新构造和Forge版本在更改之后失效了。所以我寻求json数据作为帮助，但可惜这个API页面并不让我访问（悲

{Answer here}

**Comment by Shawiizz** [comment]
Hello, unfortunately, the API is not usable for now as there's an issue on it. I'm currently working on a solution to make it work properly. I'll give more info when it will be fixed.
I'm very sorry for inconvenience.

**Comment by xiaoyin2011** [comment]
谢谢您，到今天中午（UTC+8）它已经可以访问了。

**Comment by xiaoyin2011** [comment]
Thank you, it is accessible by noon today (UTC+8).
