### ISSUE TITLE
1.20.1 Constant mohist entity crash

### ISSUE THREAD

**Issue by spammer559** [Teneted/Tenet#3301]
I do not know what causes this entity crash but it happens very often across many mohist server.

https://mclo.gs/ecK1Ed4

**Comment by oskarbukovsky** [comment]
We have problems with probably entities too, sometimes something bricks server and only solution is to find location (region file) where is something wrong, and delete it in entities folder in world and everything works after restart

https://mclo.gs/Q6o835M
