### ISSUE TITLE
502 Bad Gateway Again

### ISSUE THREAD

**Issue by xiaoyin2011** [Teneted/Tenet#3306]
502 Bad Gateway Again
2024-08-17 02:28:15 UTC

[**这一页**](https://mohistmc.com/api/v2/projects/Mohist/1.18.2/builds)
[**和这一页**](https://mohistmc.com/api/v2/docs/json)
我今天尝试运行我的程序获取1.18.2版本的最新构造号时，发现这两个网页都不能访问（502 Bad Gateway）
我该怎么办？

{Answer here}

**Comment by xiaoyin2011** [comment]
现在是有时可以访问，但大部分时间都是502。此外https://mohistmc.com/api/v2/projects/Mohist/1.18.2/builds一直502

**Comment by xiaoyin2011** [comment]
[502 Bad Gateway Page](http://mohistmc.com/api/v2/projects/Mohist/1.18.2/builds/)

**Comment by xiaoyin2011** [comment]
[Page](https://mohistmc.com/api/v2/projects/Mohist/1.18.2/builds%E4%B8%80%E7%9B%B4502) 502.

**Comment by xiaoyin2011** [comment]
Is the page moved to a new place? Or only my network is bad.

**Comment by Shawiizz** [comment]
The API had some problems a few days ago, it's fixed since. I'm sorry for any problem you had using it.
