### ISSUE TITLE
[1.20.1 Mohist-832] Server crash during modloading.

### ISSUE THREAD

**Issue by MrBloom2037** [Teneted/Tenet#3308]
**Minecraft Version :** 1.20.1

**Mohist Version :** 832

**Operating System :** Windows 11 Professional amd64

**Concerned mod / plugin** : Botania & Aether seem to have critical errors that cause the server to halt.

**Logs :** https://pastebin.com/17t9V4c4

**Steps to Reproduce :**
 1. Updated to the latest version of Mohist from Build 823 / 832
 2. Start Server with mods that cause the crash.
 3. Server crashes and doesn't even output a crash report.

**Description of issue :** The server crashed only after I updated to the latest build of Mohist.

**Comment by oskarbukovsky** [comment]
https://github.com/VazkiiMods/Botania/issues/4738
Similar issue, find working version mohist-1.20.1-775-server.jar, i have problems with discordSRV plugin (Timed out), but server is running

**Comment by spammer559** [comment]
same issue

**Comment by TheRealWormbo** [comment]
> Botania & Aether seem to have critical errors that cause the server to halt.

These "issues" notably have never been a problem on Forge or Fabric servers.
