### ISSUE TITLE
[1.20.1]推测826版本的修改导致 NoClassDefFoundError 错误，825版本正常启动

### ISSUE THREAD

**Issue by amibas** [Teneted/Tenet#3310]
**Minecraft Version :** 1.20.1

**Mohist Version :** 826

**Operating System :** Window11

**Logs :** https://pastebin.com/898Kw1GL

**Mod list :** Log包含   in log

**Plugin list :** none

**Description of issue :** 从832一路降到825才能启动成功，推测是826版本出了问题。NoClassDefFoundError 错误，具体是找不到 net.minecraftforge.registries.ForgeRegistry

**Comment by Mgazul** [comment]
使用832测试，无法复现

**Comment by amibas** [comment]
虽然你只是删除了i18n，但是确实启动成功了，有点难以理解
