### ISSUE TITLE
[1.20.1] Monsters are unable to produce drops

### ISSUE THREAD

**Issue by TimRained** [Teneted/Tenet#3315]
**Minecraft Version :** 1.20.1

**Mohist Version :** mohist-1.20.1-837

**Operating System :** Windows server 2019

**Concerned mod / plugin** : 
mod：null 

plugin：Advanceportals，Coreprotect，cristreecapitator，essentialsX，essentialsXspawn，essentialsXchat，Gsit，Luckperms，placeholderapi，playertitle，skinrestorer，TAB，vault，Viaversion.

**Logs :** https://gist.github.com/TimRained/dafe3348da69cc060ef075399c7fe992

**Steps to Reproduce :**
 1. Upload the mohist server from 1.20.1-833 to 1.20.1-837
 2. Then I found the world monsters were unable to produce drops.

**Description of issue :** Today, I uploaded the mohist server from 1.20.1-833 to 1.20.1-837, in my world, I have a Monsters tower, and a hour later, I found when monsters dead, they did not produce drops. Then, I rollback the server version to 1.20.1-833, everything has become normal in 1.20.1-833.

**Comment by Mgazul** [comment]
fix
