### ISSUE TITLE
[1.20.1] Crash with CNPC Epicfight Addon

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#3322]
**Minecraft Version :** 1.20.1

**Mohist Version :** 839

**Operating System :** Windows 10

**Concerned mod / plugin** : https://www.curseforge.com/minecraft/mc-mods/cnpc-epicfight-integration
                                              https://www.curseforge.com/minecraft/mc-mods/customnpcs-unofficial
                                              https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod (Any Version 20.8.X)

**Logs :** https://gist.github.com/Talan67/9f88d3ce20c12656c3091ce9c07324b1
                https://gist.github.com/Talan67/ce24f3becd38a02c608fe887de8610f7

**Steps to Reproduce :**
 1. Install Mods listed above
 2. Install Example Datapack (Heres a link to the example Datapack:
                      https://github.com/user-attachments/files/16711779/CNPC_EpicFight_Datapack-1.20.1-20.8.x.zip
 3. Launch the server with Mods and datapack
 4. Crash on start

**Description of issue :** CNPC Epicfight integration is a mod that adds compatibility between CustomNPCS and Epicfight. Epicfight is constantly being updated so that's why the mods version is all over the place, CNPC EF integration just updated to work with any Epicfight version around 20.8.X

Now onto the issue, CNPC EF integration utilizes datapacks to load Epicfight movesets for NPCs, The server only crashes when a datapack is loaded, the logs seem to point to a render issue with the gui but I'm not sure.

**Comment by Mgazul** [comment]
CNPC Epicfight uses the client class on the server side

**Comment by Goodbird-git** [comment]
There is now a version of CNPC EpicFight Addon that is compatible with servers
https://www.curseforge.com/minecraft/mc-mods/cnpc-epicfight-integration/files/5667558
