### ISSUE TITLE
VanillaFix Compatibility

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#334]
Mohist crashes when using VanillaFix. And VanillaFix on the client throws hundreds of crash reports and errors if its not on the server.

I know mohist removes or has this mod on its blacklist, but something needs to be done to mimic it completely or to support it running to stop the clientside version from spamming your screen with "An error has occurred! Type CTRL + I for more info!" dozens of times a minutes on the right side of your screen.

VanillaFix seems to throw these errors every time someone logs in, teleports near you, appears near you, a mob spawns near you, basically any entity that appears near you this error is thrown.

It also does entire screen "crashes" where it says a critical error has occurred and it gives you a link of some pastebin that makes no sense, and an option to continue playing.

**Comment by RomualdYT** [comment]
Want it too ! Hope you can do something with it

**Comment by Zilacon** [comment]
This issue is still present in latest version.
