### ISSUE TITLE
[1.20.1] 龙之研究 混沌守卫爆炸事件报错

### ISSUE THREAD

**Issue by starxjys** [Teneted/Tenet#3342]
**Minecraft Version :** 1.20.1

**Mohist Version :** 859

**Operating System :** Windows10

**Concerned mod / plugin** : [龙之研究](https://www.curseforge.com/minecraft/mc-mods/draconic-evolution)

**Logs :** [Link(s) of logs and crash reports if you have](https://haste.mohistmc.com/redexifire.pl)

**Steps to Reproduce :**
 1. tp到[混沌之岛](https://www.mcmod.cn/item/30865.html)
 2. 被混沌守卫揍（逃）
 3. 后台报错

**Description of issue :**

猜测与龙研用到自己的爆炸处理有关，不会java，看不太懂

**Comment by Mgazul** [comment]
CMI不支持mod的爆炸
