### ISSUE TITLE
New MCP Decoder slowing down start up!

### ISSUE THREAD

**Issue by Zilacon** [Teneted/Tenet#335]
The new download/decoder for MCP in the beginning literally adds about 4 minutes to my server load time. What is this? Can this be fixed? Why is this here when it was never needed before? Where is my sad trombone?

**Comment by Mgazul** [comment]
The first start will be longer

**Comment by Zilacon** [comment]
Nah i shut it down right after the first time, second time was the same duration as the first.

**Comment by Zilacon** [comment]
It should be cached somewhere or something if anything.

**Comment by Mgazul** [comment]
If it is not completed for the first time, it will still be executed for the second time, just like the first phase of the paper starts: generate the necessary data. We no longer provide any cache for mcp data

**Comment by Zilacon** [comment]
Right i let it complete the first time, then stopped the server, and it spent another 4 mins again on the 2nd start doing the same thing...

**Comment by DonatiFilippo** [comment]
Maybe I know where the problem lies: I think that MD5 hash take in account also the place and the date of creation of the file, breaking the check algorithm, but I'm not sure

Edit: ok, yes it is one problem, but also the lenght check seems wrong
