### ISSUE TITLE
Problem with server shutdown

### ISSUE THREAD

**Issue by ququshkaaeng** [Teneted/Tenet#3356]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {865}

**Operating System :** {24.04}

**Logs :** {[Link(s) of logs and crash reports if you have](https://gist.github.com/ququshkaaeng/b82dd1c77db9ce76e642b82b2c6f0f6d)}

**Mod list :** {Same as in #3355}

**Plugin list :** {Same as in #3355}

**Description of issue :** {When shutting down the server, you may get this error

**Comment by ququshkaaeng** [comment]
The problem still remains

**Comment by SNWCreations** [comment]
It seems that ModernFix still exists on your server installation and you've said that ModernFix caused the linked issue. This is confusing.
