### ISSUE TITLE
[1.20.1] Minecraft Transit Railway

### ISSUE THREAD

**Issue by Leonmmcoset** [Teneted/Tenet#3357]
**Minecraft Version :** 1.20.1

**Mohist Version :** 850

**Operating System :** Windows Server 2022

**Concerned mod / plugin** : Minecraft Transit Railway

**Logs :** No Errors :(

**Steps to Reproduce :**
1. Start server
2. Place rails
3. Stop the server
4. Start the server

**Description of issue :** The server will not save files on `/world/mtr` folder,Forge is not have this bug.

**Comment by Mgazul** [comment]
The latest build of mohist cannot reproduce this issue

**Comment by Leonmmcoset** [comment]
This bug is happens on latest version of Mohist(867)
Video: [https://leonmtr.netlify.app/page/issue/mohist3357](https://leonmtr.netlify.app/page/issue/mohist3357)
The mod(MTR)'s version:`3.2.2 hotfix 2 Forge`
