### ISSUE TITLE
[1.20.2-168]很抱歉，在最新的168版本中，还是无法部署服务端，也出现了167版本中反馈的问题

### ISSUE THREAD

**Issue by DemonKing707** [Teneted/Tenet#3358]
**你的问题是什么？**
{
我不知道该如何解决！我也非常希望能够用上Mohist核心！
![image](https://github.com/user-attachments/assets/2734bc27-f00d-4b52-a1a0-11506e615564)
![image](https://github.com/user-attachments/assets/2982d9f5-6d61-41d7-8593-541a74b56bc7)
![image](https://github.com/user-attachments/assets/ec9e2561-a1c7-4d7e-8eae-49e300fa2fc0)
}

**Comment by Mgazul** [comment]
这不是mohist的问题
