### ISSUE TITLE
This bug is happens on latest version of Mohist(867)

### ISSUE THREAD

**Issue by Leonmmcoset** [Teneted/Tenet#3361]
This bug is happens on latest version of Mohist(867)
Video: [https://leonmtr.netlify.app/page/issue/mohist3357](https://leonmtr.netlify.app/page/issue/mohist3357)
The mod(MTR)'s version:`3.2.2 hotfix 2 Forge`

_Originally posted by @Leonmmcoset in https://github.com/MohistMC/Mohist/issues/3357#issuecomment-2387706027_

**Comment by Mgazul** [comment]
Still can't reproduce, tested everything is normal, world/mtr has been generated, and there are saved rails in world\mtr\minecraft\overworld\rails\CB

**Comment by Mgazul** [comment]
use ```MTR-forge-4.0.0-beta-9+1.20.1```

**Comment by Lonmo0208** [comment]
> ```
>           This bug is happens on latest version of Mohist(867)
> ```
> 
> 视频：https://leonmtr.netlify.app/page/issue/mohist3357 The mod（MTR） 的版本：`3.2.2 hotfix 2 Forge`
> 
> _最初由 [#3357 （评论）](https://github.com/MohistMC/Mohist/issues/3357#issuecomment-2387706027) 发布_

哥们直接下最新版就好了~ 问题解决了不用去下MTR4.0

**Comment by Leonmmcoset** [comment]
> > ```
> 
> >           This bug is happens on latest version of Mohist(867)
> 
> > ```
> 
> > 
> 
> > 视频：https://leonmtr.netlify.app/page/issue/mohist3357 The mod（MTR） 的版本：`3.2.2 hotfix 2 Forge`
> 
> > 
> 
> > _最初由 [#3357 （评论）](https://github.com/MohistMC/Mohist/issues/3357#issuecomment-2387706027) 发布_
> 
> 
> 
> 哥们直接下最新版就好了~ 问题解决了不用去下MTR4.0

更新mohist了？我去试试

**Comment by Leonmmcoset** [comment]
此bug已在871中修复（已测试）
