### ISSUE TITLE
1.20.1mohist和唢呐生存指南Sona Survival 101不兼容

### ISSUE THREAD

**Issue by ElainAwa** [Teneted/Tenet#3362]
**Minecraft Version :**1.20,.1

**Mohist Version :** mohist-1.20.1-867-server

**Operating System :** windows11

**Logs :** {Link(s) of logs and crash reports if you have}

**Mod list :** 唢呐生存指南Sona Survival 101

**Plugin list :** 没有

**Description of issue :** 1.20.1mohist加上这个模组就会崩溃

**Comment by Mgazul** [comment]
经查证，该问题来源于mod本身，mod的mixin类中使用了forge-1.18.2早期的代码，并不存在于1.20.1中
