### ISSUE TITLE
[1.20.1] SkRedis 插件加载失败，因为方法缺失：`java.lang.NoSuchMethodError: 'void org.bukkit.command.ConsoleCommandSender.sendMessage(net.kyori.adventure.text.Component)'`

### ISSUE THREAD

**Issue by BredyAK** [Teneted/Tenet#3366]
**Minecraft Version :** 1.20.1

**Mohist Version :** 1.20.1-871

**Operating System :** Debian GNU/Linux 9 (stretch) x86_64(Py3.7.8)

**Concerned mod / plugin** : SkRedis（[https://github.com/byPixelTV/skRedis](https://github.com/byPixelTV/skRedis)）

**Logs :** [https://mclo.gs/BkIR2Ov](https://mclo.gs/BkIR2Ov)（第 909 至 924 行）

**Steps to Reproduce :**
 1. 安装上述环境
 2. 启动服务器
 3. 错误在启动过程中出现

**Description of issue :** 希望可以修复方法缺失的问题

**Comment by Mgazul** [comment]
SkRedis 是一个paper插件，mohist不支持大部分paper插件
