### ISSUE TITLE
[1.20.2][C][疯狂抽奖]CrazyCrates-1.18.5 获取坐标的问题

### ISSUE THREAD

**Issue by yuankun1** [Teneted/Tenet#3367]
很奇怪的是我给我的抽奖箱设置了固定坐标 每次重启服务器我都需要输入一次cc reload 来加载设置好的坐标
在1.20.1版本也有类似的问题 我开发的插件也是在重启服务器过后识别不到坐标了
https://www.minebbs.com/resources/akfrewards-1-13-1-20.9425/
在我插件重启服务器之前加载提示是没有指定世界
cc配置文件:
Locations:
  '1':
    Crate: 每日抽奖宝箱
    World: lobby
    X: 906
    Y: 58
    Z: 1247

**Comment by Mgazul** [comment]
因为你的世界加载循序在抽奖箱后面(加载抽奖箱插件的时候 世界没有被加载，无法识别到world)

**Comment by yuankun1** [comment]
> 因为你的世界加载循序在抽奖箱后面(加载抽奖箱插件的时候 世界没有被加载，无法识别到world)

确实是这样的我插件提示也显示了没有指定世界     那意思就是cc抽奖插件用不了

**Comment by Mgazul** [comment]
修改插件的plugin.yml 添加世界管理插件到依赖选项中
