### ISSUE TITLE
[1.20.1] 与模组 Dimensional Threading Reforked 不兼容，服务器启动后在创建世界过程奔溃

### ISSUE THREAD

**Issue by Lonmo0208** [Teneted/Tenet#3368]
> **Minecraft Version :** 1.20.1
> 
> **Mohist Version :** 876
> 
> **Operating System :** Windows 11
> 
> **Concerned mod / plugin** : Dimthread（https://www.curseforge.com/minecraft/mc-mods/dimensional-threads/files/all?page=1&pageSize=20&version=1.20.1, 使用版本: Dimthread/1.20.1/v1.0.5 ）
> 
> **Logs :** https://mclo.gs/d885YEV
> **debug :**  https://mclo.gs/ZxSiRqD
> 
> **Steps to Reproduce :**
> 
> 1.  向 mods 文件夹安装 Dimthread
> 2.  启动服务器
> 3.  服务器生存世界过程中启动失败

**Comment by Mgazul** [comment]
无法复现

**Comment by Lonmo0208** [comment]
> 无法复现

问题更正
启动服务器后 有几率启动成功，但是玩家加入服务器，加载新区块，就会崩溃
