### ISSUE TITLE
[1.20.1] Mythic Dungeons cave creature not supported

### ISSUE THREAD

**Issue by Talan67** [Teneted/Tenet#3369]
**Minecraft Version :** 1.20.1

**Mohist Version :** 873

**Operating System :** Windows 10

**Concerned mod / plugin** : https://mythiccraft.io/index.php?resources/mythic-dungeons.869/

**Logs :**  Debug: https://gist.github.com/Talan67/d59415e854c178712e028c3424c65ca8
                 Latest: https://gist.github.com/Talan67/6138b169d854a84e5cc9c170551965c7

**Steps to Reproduce :**
 1. Install "Friends and Foes" and/or "Alex's Caves" and "Citadel" (I used both in this case because its the same issue)
 2. Join Server
 3. Create dungeon with "/md create test classic"
 4. Edit dungeon with "/md edit test "
 5. Error... (In logs it spouts a message about cave creature not supported)

**Description of issue :** Dungeons cannot be loaded as the Mob "Glare" from "Friends and Foes" and all the Mobs from "Alex's Caves" have a special spawn category that is not present in Vanilla or Bukkit, which causes Mythic Dungeons to throw an error.

**Comment by Talan67** [comment]
Crash on Server Start with build-875

Latest: https://gist.github.com/Talan67/dbbe90632d438aab9a25a42583926831
Debug: https://gist.github.com/Talan67/9994ac33b35155c94c9a5169163af706

**Comment by Mgazul** [comment]
use 876

**Comment by Talan67** [comment]
just checked same with build-876

**Comment by Talan67** [comment]
i am so sorry this must be horrible to debug

**Comment by Talan67** [comment]
build-876

debug: https://gist.github.com/Talan67/12cfc7e9f3439822397b6abc62eb1084
latest: https://gist.github.com/Talan67/39aeea08c1d904c5bc7fa75df6db618f

**Comment by Talan67** [comment]
Fixed, thanks Mgazul.
