### ISSUE TITLE
[1.20.1] 与模组 Aether（天境）不兼容，服务器启动时报错，不能正常启动

### ISSUE THREAD

**Issue by BredyAK** [Teneted/Tenet#3374]
**Minecraft Version :** 1.20.1

**Mohist Version :** 874

**Operating System :** Debian GNU/Linux 9 (stretch) x86_64(Py3.7.8)

**Concerned mod / plugin** : Aether（[https://modrinth.com/mod/aether](https://modrinth.com/mod/aether)，测试版本：1.5.0）

**Logs :** [https://mclo.gs/4K14Wzn](https://mclo.gs/4K14Wzn)（第 582 至 632 行）

**Steps to Reproduce :**
 1. install Aether to your mods folder / 向 mods 文件夹安装 Aether
 2. start the server / 启动服务器
 3. server failed to start up / 服务器启动失败

**Description of issue :** see above / 见上

**Comment by Lonmo0208** [comment]
> **Minecraft Version :** 1.20.1
> 
> **Mohist Version :** 874
> 
> **Operating System :** Debian GNU/Linux 9 (stretch) x86_64(Py3.7.8)
> 
> **Concerned mod / plugin** : Aether（https://modrinth.com/mod/aether，测试版本：1.5.0）
> 
> **Logs :** https://mclo.gs/4K14Wzn（第 582 至 632 行）
> 
> **Steps to Reproduce :**
> 
> 1. install Aether to your mods folder / 向 mods 文件夹安装 Aether
> 2. start the server / 启动服务器
> 3. server failed to start up / 服务器启动失败
> 
> **Description of issue :** see above / 见上

在873上可以正常开服... 
可能是874修啥的时候 冲突了.. 到876一样天境无法开服

**Comment by Lonmo0208** [comment]
在878上 仅仅安装天境最新的1.5.0版本开服失败
日志： https://mclo.gs/VHrwhy5

**Comment by Mgazul** [comment]
这不是mohist的问题，mod在服务器中调用了客户端的类 ```net.minecraft.client.resources.sounds.SoundInstance```

**Comment by Mgazul** [comment]
同时，你给的日志中显示安装了其他多个mod，并非仅仅天镜一个mod

**Comment by Lonmo0208** [comment]
> 同时，你给的日志中显示安装了其他多个mod，并非仅仅天镜一个mod

提出这个Issues的笔者是多个mod的


> 在878上 仅仅安装天境最新的1.5.0版本开服失败 日志： https://mclo.gs/VHrwhy5

但是我这个是单模组的报告 


> 这不是mohist的问题，mod在服务器中调用了客户端的类 `net.minecraft.client.resources.sounds.SoundInstance`

会反应问题给天境团队，感谢

**Comment by Mgazul** [comment]
经过反复测试，无法复现该问题

**Comment by BredyAK** [comment]
这个 issue 先别着急 close，目前先等待 aether 解决这个调用问题，然后等他们修复以后再看看 mohist 这边是否有问题，而后我再决定自行 close 或者继续追踪此问题

**Comment by Mgazul** [comment]
![image](https://github.com/user-attachments/assets/3a8a023e-43f3-4fa9-aeda-72d5d209b609)

**Comment by BredyAK** [comment]
我这边确保了在 mods 文件夹仅包含 Aether 的情况下又测了一下，确实服务器是可以启动的。
Mohist 版本：878
日志：[https://mclo.gs/POEwEaF](https://mclo.gs/POEwEaF)

目前 Aether 最新 1.5.0 版本引起的服务器崩溃问题大部分情况都是因为 Aether: Redux 这个模组导致的。情报链接：[https://github.com/The-Aether-Team/The-Aether/issues/2297#issuecomment-2395268456](https://github.com/The-Aether-Team/The-Aether/issues/2297#issuecomment-2395268456)。

@Lonmo0208 可以等一下 Aether: Redux 团队那边修复。情报链接：[https://github.com/Zepalesque/The-Aether-Redux/issues/142#issuecomment-2395223874](https://github.com/Zepalesque/The-Aether-Redux/issues/142#issuecomment-2395223874)。

那么这个 issue 我就先关掉了，如有问题再给墨老反应。感谢！
