### ISSUE TITLE
[1.20.1] 与模组 Dimensional Threading Reforked 不兼容，服务器启动后在创建世界过程奔溃

### ISSUE THREAD

**Issue by Lonmo0208** [Teneted/Tenet#3376]
**Minecraft Version :** 1.20.1
 **Mohist Version :** 876
 **Operating System :** Windows 11
 **Concerned mod / plugin** : Dimthread（https://www.curseforge.com/minecraft/mc-mods/dimensional-threads/files/all?page=1&pageSize=20&version=1.20.1, 使用版本: Dimthread/1.20.1/v1.0.5 ）
**Logs :** https://mclo.gs/d885YEV

**debug :**  https://mclo.gs/ZxSiRqD

 **Steps to Reproduce :**
 1. 向 mods 文件夹安装 Dimthread
 2. 启动服务器
 3. 服务器生成世界过程中启动失败

**Comment by Mgazul** [comment]
修了一半，全是bukkit的异步拦截报错

**Comment by Lonmo0208** [comment]
> 修了一半，全是bukkit的异步拦截报错

那是无法修复了吗qwq 无解了qwq

**Comment by Mgazul** [comment]
bukkit的方块事件不支持多线程

**Comment by Lonmo0208** [comment]
> bukkit的方块事件不支持多线程

好的 知道了qwq 那就关闭这个issues吧？

**Comment by Mgazul** [comment]
关闭原因：尽管可以完全修复，但是所有bukkit事件将失效(插件失效)，不如不修！

**Comment by Lonmo0208** [comment]
> 关闭原因：尽管可以完全修复，但是所有bukkit事件将失效(插件失效)，不如不修！

收到了~ （虽然可以在879上成功开服，但是无法对世界做任何更改，所以寄~ 居然会影响到插件的话，那就算了吧~）
