### ISSUE TITLE
Voicechat mod bug

### ISSUE THREAD

**Issue by link1107** [Teneted/Tenet#338]
I use Gliby's voicechat Reloaded mod for 1.12.2.
It works perfectly on pure Forge server.
But here is a bug which i've found while running this mod on Mohist:
If i connect first time to the server - everything is fine.
If i disconnect and connect again - mod says thet Voicechat on this server is disabled, however other players, who had not reconnected, can use voicechat and have no problems with it.
This problem can be solved in 2 ways 
1) by connecting without Voicechat mod, getting error while connecting (Voicechat mod is missing), and then connecting with mod. Then it works until next disconnect.
2) by restarting server. Then you can connect and everything will work until you disconnect and connect again. After that mod is not working again, saying that mod is disabled on server, however it is not.
Here is the mod sources - https://github.com/IvasikDev/GlibysVoiceChat

**Comment by Shawiizz** [comment]
I had this issue too. So i used ImmersiveVoice which work nice :)
Hope this can be fixed because Gliby's voicechat Reloaded is maybe better than ImmersiveVoice

**Comment by link1107** [comment]
Yep, i know. Hope so too

**Comment by TansuoTro** [comment]
ummm.
the server does not need to install voice MOD, 
if this is wrong, please reopen this issue
