### ISSUE TITLE
[1.20.1] NickName等在聊天框的头衔都不显示

### ISSUE THREAD

**Issue by Lonmo0208** [Teneted/Tenet#3380]
**Minecraft Version :** 1.20.1

**Mohist Version :** 881

**Operating System :** Windows11

**Concerned mod / plugin** : 不应该是模组的问题，因为在873的时候是正常的，可能是在往后的更新中修改到了

**Logs :** 无报错

**Steps to Reproduce :**
在服务器内，给自己NickName，或者用Team指令给自己的团队一个头衔（如红队什么什么的）
正常来说，聊天框发送消息会有显示出Nick好的名字和所在队伍
但是在881中 只有原版样式

**Comment by Lonmo0208** [comment]
![image](https://github.com/user-attachments/assets/0b07b352-9d4e-4ef2-bc4b-d26d3a61c376)

**Comment by Lonmo0208** [comment]
> ![image](https://private-user-images.githubusercontent.com/95102577/374281484-0b07b352-9d4e-4ef2-bc4b-d26d3a61c376.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjI3MjQsIm5iZiI6MTcyODM2MjQyNCwicGF0aCI6Ii85NTEwMjU3Ny8zNzQyODE0ODQtMGIwN2IzNTItOWQ0ZS00ZWYyLWJjNGItZDI2ZDNhNjFjMzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDA0NDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTEyYTdkNDdjMmNlZWFiMjQ5N2RjYjg3NzU5NGEwMTU4MmEyMDY3OGUyMzQ4ODI3MjVlOGE1Y2ZhYmZhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tddEaQggN0dxmEK2Uwz5y5v8Fl-TKvTPzppaDP2545o)

在873的时候 正常玩家在聊天框输入信息应该是这样的
![image](https://github.com/user-attachments/assets/cf549904-0173-45d4-b4a5-f860adf4feee)

**Comment by Mgazul** [comment]
使用最新版测试，该问题和paper api补丁有关
