### ISSUE TITLE
[1.20.1] 与模组 PlayerSync 不兼容，服务器启动时报错：`Exception in thread "main" java.lang.module.ResolutionException: Modules mysql.connector.j and mysql_jdbc export package com.mysql.cj to module betterstrongholds`

### ISSUE THREAD

**Issue by BredyAK** [Teneted/Tenet#3384]
**Minecraft Version :** 1.20.1

**Mohist Version :** 888

**Operating System :** Debian GNU/Linux 9 (stretch) x86_64(Py3.7.8)

**Concerned mod / plugin** : PlayerSync（[https://www.curseforge.com/minecraft/mc-mods/playersync](https://www.curseforge.com/minecraft/mc-mods/playersync)，测试版本：1.3.3）

**Logs :** [https://mclo.gs/JGyGMJW](https://mclo.gs/JGyGMJW)（第 26 行）

**Steps to Reproduce :**
 1. install PlayerSync to your mods folder / 向 mods 文件夹安装 PlayerSync
 2. start the server / 启动服务器
 3. server failed to start up / 服务器启动失败

**Description of issue :** see above / 见上

**Comment by BredyAK** [comment]
已收到作者答复。跟进记录：

![Snipaste_2024-10-09_20-38-43](https://github.com/user-attachments/assets/9a4b81b4-03db-45b6-b8f3-0811e09613b3)

此 issue 关闭。

**Comment by l89669** [comment]
@Mgazul 请问是否有解决方案
