### ISSUE TITLE
The Betweenlands Mod's rings are double when player dies

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#339]
**Describe the bug**
When a player who is equipped with rings from the Betweenlands Mod dies,
all of his rings will drop, but he is still equipped with the same rings.
By being killed again and again, he can multiply his rings easily.
装备有交错次元 MOD 戒指的玩家，死亡时装备的戒指不会消失，
但地上会掉落一份同样的戒指。
通过反复自杀等方式可以复制戒指。

**To Reproduce**
1. Install [the Betweenlands mod](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod).
安装交错次元 MOD。
2. Get any of its rings. Simply search "ring" in Creative Mode backpack and you will find it.
任找几个戒指。
3. Hold them in the main hand, and right-click to equip them.
手持右键点击即可装备，任意装备几个。
3. Get killed by any way. `/kill` command for example.
使用`/kill`等方法杀死自己。
4. You will still have your rings equipped; but the copy of your rings drops to the ground.
就会出现上面提到的那种情况。

**Expected behavior**
Rings which you have equipped drop normally.
装备在身上的戒指本来应该消失，并掉在地上。

**Screenshots**
I have a screen record.
这是屏幕录像。
https://imgur.com/gallery/wub54uB

**Info (please complete the following information):**
- Mod/Plugins Name: the Betweenlands
 - Mod/Plugins  Version: 3.6.1

**Additional context**
This bug cannot be reproduced in single player game.
Neither other mods nor any plugins are installed.
这个 Bug 在单机游戏无法复现。
没有安装任何其他 MOD 或插件。

**Comment by TansuoTro** [comment]
很抱歉这么晚才回复你
应该是Mod和Bukkit有冲突，我将会进行修复，在修复完成之前，你可以选择关闭死亡掉落或定制插件实现，更建议你使用前者的方案。

It should be that there is a conflict between Mod and Bukkit. I will repair it. Before the repair is completed, you can choose to turn off the death drop or customize the plugin fix it. It is recommended that you use the former solution .
