### ISSUE TITLE
Why is the obsidian platform in the end dimension loaded every time the server starts ?

### ISSUE THREAD

**Issue by EltyDev** [Teneted/Tenet#3391]
**What is your question ?**
I have a tile entity in the end that causes the server to crash when loaded. This is normal and makes sense. But it should only crash when the chunk is loaded, right? So why does the server crash while starting, even though the chunk shouldn't be loaded?

**Comment by Mgazul** [comment]
So, where is your crash log?

**Comment by EltyDev** [comment]
I've already said that the crash wasn't really a big deal. I just don't understand why the obisdian platform is loading at the start of the server
