### ISSUE TITLE
Add plz Event

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3393]
https://mclo.gs -->  https://mclo.gs/r3hVWqt

Minecraft Version : 1.20.1

Mohist Version : 891

Operating System : linux

Fix plz

**Steps to Reproduce :**
 1. Do this
 2. Then do that
 3. ...

<html>
<body>

[18:10:42] [Server thread/INFO] [com.sarry20.topminion.TopMinion]: [TopMinion] Enabling TopMinion v2.4.3
--
16318 | [18:10:43] [Server thread/INFO] [Console]: [TopMinion]We're checking your license.
16319 | [18:10:43] [Server thread/INFO] [Console]: [TopMinion]The license is: valid
16320 | [18:10:43] [Server thread/INFO] [Console]: [TopMinion]The plugin is starting... Version: 2.4.3
16321 | [18:10:44] [Server thread/ERROR] [Minecraft]: Error occurred while enabling TopMinion v2.4.3 (Is it up to date?)
16322 | java.lang.NoClassDefFoundError: com/mohistmc/paper/profile/PlayerProfile
16323 | at com.sarry20.topminion.models.spawnItem.SpawnItemManager.<clinit>(SpawnItemManager.java:25) ~[?:?]
16324 | at java.lang.Class.forName0(Native Method) ~[?:?]
16325 | at java.lang.Class.forName(Class.java:529) ~[?:?]
16326 | at java.lang.Class.forName(Class.java:508) ~[?:?]
16327 | at com.mohistmc.bukkit.remapping.ReflectionHandler_73.redirectClassForName(ReflectionHandler.java:227) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16328 | at com.mohistmc.bukkit.remapping.ReflectionHandler_73.redirectClassForName(ReflectionHandler.java:220) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16329 | at com.sarry20.topminion.TopMinion.nb(TopMinion.java:33) ~[?:?]
16330 | at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:109) ~[?:?]
16331 | at java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]
16332 | at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:275) ~[?:?]
16333 | at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:265) ~[?:?]
16334 | at com.sarry20.topminion.TopMinion.registerClass(TopMinion.java:122) ~[?:?]
16335 | at com.sarry20.topminion.TopMinion.onEnable(TopMinion.java:88) ~[?:?]
16336 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:348) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16337 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16338 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:484) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16339 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
16340 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
16341 | at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:446) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16342 | at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16343 | at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16344 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16345 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16346 | at java.lang.Thread.run(Thread.java:1570) [?:?]
16347 | Caused by: java.lang.ClassNotFoundException: com.mohistmc.paper.profile.PlayerProfile
16348 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:186) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16349 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:138) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16350 | at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
16351 | ... 24 more
16352 | [18:10:44] [Server thread/INFO] [com.sarry20.topminion.TopMinion]: [TopMinion] Disabling TopMinion v2.4.3
16353 | [18:10:44] [Server thread/ERROR] [Minecraft]: Error occurred while disabling TopMinion v2.4.3 (Is it up to date?)
16354 | java.lang.NullPointerException: null
16355 | at com.sarry20.topminion.TopMinion.onDisable(TopMinion.java:110) ~[?:?]
16356 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:350) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16357 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:366) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16358 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:509) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16359 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16360 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:484) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:?]
16361 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:547) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
16362 | at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.3.11-universal.jar%23387!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
16363 | at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:446) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16364 | at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:346) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16365 | at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:233) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16366 | at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:856) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16367 | at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23382!/:?]
16368 | at java.lang.Thread.run(Thread.java:1570) [?:?]

</body>
</html>

**Comment by Mgazul** [comment]
This is the core API of Paper, which cannot be combined with Forge and will break most mods.
