### ISSUE TITLE
[1.20.1] private MixinContainer(Mod valkyrien skies)

### ISSUE THREAD

**Issue by HeDmitry** [Teneted/Tenet#3394]
**Minecraft Version :** 1.20.1

**Mohist Version :** 891

**Operating System :** Windows 11

**Concerned mod / plugin** :Valkyrien Skies(mod)

**Logs :**https://pastes.dev/weQvAMDOVa

**Steps to Reproduce :**
 1. start the server with the valkyrien skies mod and all its dependencies (including the Create mod with ClockWord)

**Description of issue :** the server throws the error that I provided in the logs and stops working

**Comment by Mgazul** [comment]
This should be a problem with the mod itself. The client has the same problem

**Comment by HeDmitry** [comment]
I didn't have any problems with the client

**Comment by Mgazul** [comment]
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/872

**Comment by HeDmitry** [comment]
Okay, I admit I have tested it on a client right now, it doesn't work

**Comment by HeDmitry** [comment]
But the only difference I noticed is that I also get this error when I have other mods

**Comment by HeDmitry** [comment]
but I didn't understand what Kotlin has to do with it
