### ISSUE TITLE
升级到最新构建出现的问题

### ISSUE THREAD

**Issue by CenX233** [Teneted/Tenet#340]
以前一直使用802b14f版本，现在升级到b704e64出现了这些问题：
1.工业炸线，后台刷屏，工业版本是2.8.188-ex112
2.KillerMoney 4.2.0插件不正常，击杀敌对生物前后台无提示，配置文件正常，击杀友好生物正常
附件是从换上新核心到发现问题的log
[latest.log](https://github.com/Mohist-Community/Mohist/files/4774962/latest.log)

**Comment by TansuoTro** [comment]
Ok, I will fix it

**Comment by TansuoTro** [comment]
可以尝试使用最新的版本
