### ISSUE TITLE
Server PlayerInteractEvent Error

### ISSUE THREAD

**Issue by ssavnayt** [Teneted/Tenet#3400]
**Minecraft Version :** {1.20.1}

**Mohist Version :** {893}

**Operating System :** {Windows 11 24H2}

**Logs :** {Debug Log: https://mclo.gs/upM5Wwp, Base log: https://mclo.gs/L7Y5WIB}

**Mod list :** {Unknown Command, but i can send screenshots: https://mega.nz/folder/57MynBqL#MX7Apr46ctubxjmwgnn4Bw}

**Plugin list :** {ActionInfo-1.6, BaritoneRemover-1.4.0-all, BetterPerformance-v1.0.0, EndPortalTimer-2.1, FigureFix, FunTools, GreenChunk-1.4x, HeadDrops-1.0.0, Home-Sethome-Plugin-1.20.6, InvSee++, killcommand-1.0, Maintenance-4.2.1, morertp-1.0-SNAPSHOT, OpenSit-1.0.4, PerWorldCommands-1.2.0, QuickEChest-1.0.0, Sethome-Yottaka-1.20.1, SimpleVirtualWorkBench, Spawn-2.4.1, UberEnchant, UPnP-1.8-SNAPSHOT, Vault, ViaBackwards-5.0.4-SNAPSHOT, ViaVersion-5.0.4-SNAPSHOT, ViaVersionStatus-3.13, visual-crafting-modrinth, VoidPickaxe, WebStats-1.10.0+mc1.18+}

**Description of issue :** {The problem is that when I touch the block, the error PlayerInteractEvent is displayed in the log and it still hasn't been fixed, even in the core 859-862 version.}

**Comment by Unitei-Dev** [comment]
пWhy do you need ViaVersion, and you have a bunch of errors, you need to delete them individually to remove all the errors and look for reasons why, no one will fix you because there can be any error and from anywhere

**Comment by ssavnayt** [comment]
I removed ViaVersion, and even with it, this error is still there. mclogs writes that this is a minecraft bug (possibly a core error). If it was a plugin or a mod, I would send a request to the plugins section

**Comment by ssavnayt** [comment]
I am just removed FunTools, and it works!
