### ISSUE TITLE
Supplementaries 3.0.0 not work

### ISSUE THREAD

**Issue by Unitei-Dev** [Teneted/Tenet#3412]
Mohist:  895
Minecraft: 1.20.1
Linux

Log: https://mclo.gs/Pc8h1to

**Comment by ssavnayt** [comment]
Version?

**Comment by ssavnayt** [comment]
Try to download newer version, if it doesn't work, downgrade mod or switch Mohist version

**Comment by Unitei-Dev** [comment]
> Try to download newer version, if it doesn't work, downgrade mod or switch Mohist version

I think your brain can also be lowered, since you don’t understand what I’m talking about.
