### ISSUE TITLE
Description: Exception ticking world

### ISSUE THREAD

**Issue by wuweidmw** [Teneted/Tenet#3430]
[crash-2024-11-19_01.03.39-server.txt](https://github.com/user-attachments/files/17803917/crash-2024-11-19_01.03.39-server.txt)

**Comment by wuweidmw** [comment]
about Touhou Little Maid EntityJoinWorldEvent.onAnimalJoinWorld

**Comment by SNWCreations** [comment]
No Bukkit code involved here. Could you replicate it with pure-Forge server?

**Comment by wuweidmw** [comment]
> No Bukkit code involved here. Could you replicate it with pure-Forge server?这里不涉及 Bukkit 代码。你能用 pure-Forge 服务器复制它吗？

The test has shown that the Forge server also has this issue. I have already reported it to the mod author, and I greatly appreciate your response.

**Comment by wuweidmw** [comment]
> No Bukkit code involved here. Could you replicate it with pure-Forge server?

The test has shown that the Forge server also has this issue. I have already reported it to the mod author, and I greatly appreciate your response.
