### ISSUE TITLE
What happened to 1.21.1

### ISSUE THREAD

**Issue by hckgg** [Teneted/Tenet#3441]
New modpacks are using 1.21.1 not 1.21.3. What happened to the build?

**Comment by Unitei-Dev** [comment]
> New modpacks are using 1.21.1 not 1.21.3. What happened to the build?

All ready-made assemblies for production are available on https://mohistmc.com
Everything you take to [Codemc](https://ci.codemc.io/job/MohistMC/) or other sites is not ready to work, and you will have to wait for at least another year when the kernel from 1.21.x to 1.22 is released

![image](https://github.com/user-attachments/assets/644f9891-25e8-45d9-99df-c61512334269)
