### ISSUE TITLE
[1.20.1] 使用 littletiles小方块mod 创建的门 无法正常工作

### ISSUE THREAD

**Issue by AiharaYuriko** [Teneted/Tenet#3451]
**Minecraft Version :** 1.20.1

**Mohist Version :** 909
**Operating System :** win10 ltsc
**Concerned mod / plugin** : LittleTiles_BETA_v1.6.0-pre136_mc1.20.1  CreativeCore_FORGE_v2.12.24_mc1.20.1

**Logs :** 
[log.txt](https://github.com/user-attachments/files/18018367/log.txt)

**Steps to Reproduce :**
 1. 右键littletiles中创建的任何门(axis door/sliding door/advanced door)

**Description of issue :** 右键littletiles中创建的任何门均无法正常工作（开启），此时控制台报错 java.lang.NullPointerException: Cannot assign field "currentPrimedTnt" because "this.spigotConfig" is null 但服务器不会崩溃，使用同样的客户端在单人存档中测试正常

**Comment by SNWCreations** [comment]
这可以在纯 Forge 服务端上再现吗？LittleTiles 这么继承 Level 是不合理的写法（如果是只访问 Level ，为什么要继承？？）。
已经找到修复方法，但是仍然应该建议其开发团队更改使用 Level 的方法。

**Comment by SNWCreations** [comment]
应该可以通过 #3461 修复

**Comment by AiharaYuriko** [comment]
> 这可以在纯 Forge 服务端上再现吗？LittleTiles 这么继承 Level 是不合理的写法（如果是只访问 Level ，为什么要继承？？）。 已经找到修复方法，但是仍然应该建议其开发团队更改使用 Level 的方法。

感谢大佬修复，暂时还没有在纯forge服务端上测试过，但已经把这个问题反映给了LittleTiles开发者
https://github.com/CreativeMD/LittleTiles/issues/966
