### ISSUE TITLE
[1.12.2] GreatKits has stopped working

### ISSUE THREAD

**Issue by ResponsibleBear** [Teneted/Tenet#346]
**Describe the bug**
GreatKits throws error in console. New ones are not created, old ones are not obtained.
On previous mohist builds (#523), everything worked stably.

**To Reproduce**
1. Place GreatKits plugin in plugins folder
2. Start server
3. Try create new kit or get an old kit.

**Info (please complete the following information):**
Plugin: [GreatKits](https://www.spigotmc.org/resources/greatkits-1-7-1-13-full-config-kits-plugin-save-and-load-inventory-with-commands.44535/)
Using latest Mohist build 557

Error: https://hastebin.com/huheqitafu.rb

**Comment by Shawiizz** [comment]
Hey, the error link is dead. Could you recreate one please ?

**Comment by Shawiizz** [comment]
After testing i don't see any error. I'm using latest Mohist d0b9a3e version and GreatKits 2.9.0. It's working nice with the latest Mohist build @ResponsibleBear

**Comment by ResponsibleBear** [comment]
The link is dead bcoz two months has spent. Ok, ill try it, tnx.
