### ISSUE TITLE
1.20.1mohist921版本补充库文件无限循环

### ISSUE THREAD

**Issue by chessMCman** [Teneted/Tenet#3463]
游戏版本：1.20.1
核心版本：mohist-921
系统版本：Ubuntu-24.04.1 lts
启动时补充库文件，无限循环输出这个日志，服务器无法正常运行。
[Mohist] The file libraries/net/minecraftforge/coremods/5.2.4/coremods-5.2.4.jar doesn't exists in the Mohist jar !
 100% [======================================================================================] 1/1 (0:00:00 / 0:00:00)

**Comment by chessMCman** [comment]
![image](https://github.com/user-attachments/assets/46feee44-4798-4620-83a0-b1b252a9c125)
启动服务器状态如图

**Comment by WeiguangTWK** [comment]
遇到了一样的情况
