### ISSUE TITLE
[1.7.10] Mutual support for client and server languages

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#35]
_Hello o/
I apologize in advance for my English._

My question is about the possibility of localizing the server that interests me very much. I already checked the operation of this function, but without proper documentation I could misunderstand. In general, as I understand it, the language that will be shown to the player on the server depends on the 'language' parameter in the _uranium.yml_ file.

And this fixes one and at the same time causes another problem with systems that work on reading a request to chat.

**Let me give you an example:** in Botania mod there is the so-called Corporea system, which can issue items to the player upon his request to the chat. For example, a request to chat “1 stone” will give the player a “stone” item in the amount of 1. But the problem is that the language in which this system receives the request depends on the language of the server.

Thus, if a player uses the Russian language on the client, and the server is configured in English, then the Corporea system will not accept requests like "1 камень" (in Russian).

Of course, in the opposite case (if the client plays in English, and the server is configured in Russian), the problem persists.

_The problem above interests me personally most of all, since my servers are fully translated into Russian, but many players prefer to play in English. And in this case, I need to be able to provide both groups of players with comfortable localization conditions._

**What specifically I want to know:** is it possible to make the server "pick up" the language from the client and send messages to it in its language?

**How it could work:** when a player connects to the server, the second one asks for the client language. And further sends all messages in the client language. If the player changes the language during the game, he will have to reconnect to the server, since the language is checked once upon connection.

**An example of a situation in which this will be useful:** a foreign player (for example, Russian) plays on a Chinese server. Naturally, it will be more convenient for the Russian player if all messages from several dozen mods are displayed on the client in his native language, and not in the server language (Chinese).

_P.S. I hope that something can be done about it. But in any case, thanks for your time._

**Comment by CraftDream** [comment]
This can be done with plug-ins, can't it? (similar to the language selection in the hypixel server)

**Comment by GedeonGrays** [comment]
> This can be done with plug-ins, can't it? (similar to the language selection in the hypixel server)

Unfortunately, I have not seen a similar implementation on mod servers, and on mini-game servers I do not play. Therefore, I am not aware of this kind of plugins, but I will be very grateful if you tell me.

**Comment by CraftDream** [comment]
Unfortunately, I haven't found such a plug-in (or you can write one yourself), but I've seen similar implementations.

**Comment by GedeonGrays** [comment]
> Unfortunately, I haven't found such a plug-in (or you can write one yourself), but I've seen similar implementations.

Well, thanks for the info and advice. I hope that someday Mohist developers will try to do something on this topic, but if nothing of the kind is planned in the near future, I will not mind if you want to close the issue.

**Comment by CraftDream** [comment]
> > Unfortunately, I haven't found such a plug-in (or you can write one yourself), but I've seen similar implementations.
> 
> Well, thanks for the info and advice. I hope that someday Mohist developers will try to do something on this topic, but if nothing of the kind is planned in the near future, I will not mind if you want to close the issue.

Is it a huge project to implement in Mohist? Because it has to adapt to all kinds of plug-ins in your server, I think it is unlikely to be implemented.

**Comment by CraftDream** [comment]
What else, if there are no other questions, I will close the issue?

**Comment by GedeonGrays** [comment]
> What else, if there are no other questions, I will close the issue?

No more questions. I'll try to implement it on my own. Thanks for the answer.
