### ISSUE TITLE
[1.12.2] Dupe with ender portal

### ISSUE THREAD

**Issue by ilsilk** [Teneted/Tenet#36]
If you drop a dragon egg / sand / gravel / anvil / something else in an ender portal in the end you will get 2 items in the overworld. It was tested on an empty server only with the last build Mohist core.

**Comment by Mgazul** [comment]
I can't confirm the problem after testing, can you provide a video demonstration?

**Comment by ilsilk** [comment]
I have sent it in your Discord.

**Comment by GedeonGrays** [comment]
Oh, and we specially recorded a video for you. It is a pity that it is no longer necessary, but still it will not be superfluous.
Link: https://youtu.be/K09Lk72CT0Y

Also, please note that in the video, starting from [0:48](https://youtu.be/K09Lk72CT0Y?t=48) it is shown that the obsidian platform is restored every time when teleporting to End. This allows you to unlimitedly duplicate obsidian, and remove any blocks in the 5x5x3 area (length, width, height). I would suggest doing something about it.

_P.S. Meanwhile, this duplication works on almost any version of Minecraft, and not just on 1.12.2._

**Comment by ilsilk** [comment]
@Mgazul Why don't you fix this issue? Dupe is a serious problem. In your latest updates, you fix much less important things.

**Comment by Mgazul** [comment]
Use # 396 to see if the problem persists, thanks

**Comment by ilsilk** [comment]
@Mgazul Unfortunately, the problem still persists. Tested on build # 400.

**Comment by ilsilk** [comment]
@Mgazul Maybe you can basically disable the ability to transfer any items through the ender portal? I think this function isn't necessary, only for dupe.

**Comment by ProsperCraft** [comment]
This is a vanilla/forge bug and has nothing to do with Mohist, we made it happen in 1.15.2 forge from a player who has been doing it for years.

**Comment by ilia-shelkovyi** [comment]
Even so, I suggest at least disabling the ability to transfer any entities through the portal.

**Comment by ilsilk** [comment]
Even so, I suggest at least disabling the ability to transfer any entities through the portal.

**Comment by Mgazul** [comment]
You can disable EntityPortalEvent events through plugins
