### ISSUE TITLE
[1.7.10] Incompatibility with MobiusCore

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#37]
_Hello o/_

**Mohist Version:** Build 47
**MobiusCore Version:** 1.2.5
**Crash report:** https://pastebin.com/KWNYMxZ5

Crash during server startup.

Special MobiusCore versions for KCauldron or Thermos also do not work on Mohist.

**Comment by RupticMC** [comment]
Hmm, it works perfectly fine on Thermos for me.

**Comment by GedeonGrays** [comment]
> Hmm, it works perfectly fine on Thermos for me.

Perhaps our versions of Thermos vary. For mine, a patched version of MobiusCore is required. In the case of Mohist, apparently, too.
It is unlikely that anyone would make patched MobiusCore for fun ;3

**Comment by RupticMC** [comment]
Whoops😅 I forgot I had the patched version.

**Comment by GedeonGrays** [comment]
> Whoops I forgot I had the patched version.

These patches are so secretive, we all forget about them all the time :D

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
