### ISSUE TITLE
PlaceholderAPI JavaScript expansion doesn't work

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#372]
**Describe the bug**
PlaceholderAPI JavaScript expansion can't find JS scripts in folder

**To Reproduce**
1. You need PlaceholderAPI (plugin) installed.
2. Download the JavaScript expansion:
    /papi ecloud download JavaScript
    /papi reload
3. https://github.com/PlaceholderAPI/Javascript-Expansion/wiki/Your-First-Script

**Info (please complete the following information):**
PlaceholderAPI-2.10.6
Expansion-Javascript-1.5.3 (/papi ecloud download JavaScript)
Mohist-1.12.2-310ebdb-server

`[20:07:00 WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: hello_world`

**Comment by GMatrixGames** [comment]
What Java version are you using `java -version` in console

Edit: This issue stems from the ScriptEngine from javax being null. Did you set the script engine in your js placeholder?

**Comment by SSKirillSS** [comment]
> Edit: This issue stems from the ScriptEngine from javax being null. Did you set the script engine in your js placeholder?

![image](https://user-images.githubusercontent.com/38190325/85947812-961c0980-b955-11ea-8a21-f800ecbf5d4f.png)

> What Java version are you using `java -version` in console

`java version "1.8.0_241"`
`Java(TM) SE Runtime Environment (build 1.8.0_241-b07)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`

**Comment by SSKirillSS** [comment]
I think that it's related to this lib: https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions

**Comment by bagomot** [comment]
This problem can be solved in one of two ways:

1. Add `-Djava.class.path` with the path to the Nashorn library to the server startup line.
2. If you want to build Mohist with support for this library, do this: find the file `Mohist/forge/1.12.2-mohist-dev.json` and/or `Mohist/forge/1.12.2-mohist-rel.json`, and add the Nashorn library in the file at the end of the "libraries" section:
```json
{
      "name": "org.bodil.openjdk:nashorn:0.1.0.2013070801",
      "url" : "https://clojars.org/repo",
      "clientreq":false,
      "serverreq":true
}
```
Remember to add a comma after the last library to comply with json rules.

With the second method, Monist downloads the library himself.

**Comment by Alink-Marty** [comment]
@perezzloy i have tested your second solution and it not works :/

**Comment by bagomot** [comment]
> 
> 
> @perezzloy i have tested your second solution and it not works :/

Both solutions work for me.

![410173960b](https://user-images.githubusercontent.com/8365261/86250736-a3393280-bbb9-11ea-9b9e-e9915d5b3bcc.jpg)

**Comment by SSKirillSS** [comment]
So.. Any info about official fix?

**Comment by Rabbit0w0** [comment]
upload your logs and we can get problem details

**Comment by SSKirillSS** [comment]
Err.. What? Logs of one line? You just need to implement nashorn library. After I did it - everything starts work.
https://wiki.openjdk.java.net/display/Nashorn/Nashorn+extensions
