### ISSUE TITLE
[1.12.2] Possible bug with Mohist and CMI plugin

### ISSUE THREAD

**Issue by Krosta8** [Teneted/Tenet#374]
**Describe the bug**
All items from mods are not showing information to CMI /cmi iteminfo (with screen below)

I added this issue also on CMI github, but it looks like, that the problem is in Mohist
https://github.com/Zrips/CMI/issues/3604

**To Reproduce**
1. Start Mohist 1.12.2 with CMI plugin and any mod with new items/blocks
2. Place modded item/block in hand
3. Type /cmi iteminfo
4. It will show only minecraft:air, not the item/block information

**Expected behavior**
To show the info about item/block from mod

**Screenshots**
![image](https://user-images.githubusercontent.com/30801575/86013797-d647be80-ba1f-11ea-8dac-b8f0aaf01ebb.png)

**Info (please complete the following information):**
- Plugin: CMI 8.7.0.2
- Mohist: 1.12.2-310ebdb (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)

**Additional context**
User from CMI github suggested this:
"have you tried compiling newest Spigotversion?
in the first SpigotVersions there was an issues with heads, also in the first Papers
They should be fixed now in both."

I can't try it by myself. Never did this before.

**Comment by Rabbit0w0** [comment]
This probably caused by CMI, ask CMI's author first.

**Comment by Krosta8** [comment]
Like I wrote in this issue, I asked CMI's author first
"CMI is not made to support modded servers, if something works, cool, but in general its made to support spigot/paperspigot/tuinity and similar builds/forks. Modded servers are to different for me to make compatibility with all of them."

**Comment by Rabbit0w0** [comment]
Sorry I didn't read your issue carefully.This is not a bug of Mohist, but we will try to fix it. Thanks for supporting! :)

**Comment by Krosta8** [comment]
No problem :D Thank you for your hard work! :)

**Comment by Mgazul** [comment]
You can use /mohist item info
