### ISSUE TITLE
Mohist uses offline UUID in ops.json with waterfall

### ISSUE THREAD

**Issue by Chintam** [Teneted/Tenet#385]
**Describe the bug**
Mohist uses the offline UUID of the player for ops.json. Even when all relevant configuration settings are enabled for bungee/waterfall.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable online mode and ip-forwarding in bungee.
2. set ``bungeecord=true`` in spigot.yml
3. /op <name>

**Expected behaviour**
ops.json will register the user with his offline UUID. 

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: None
 - Mod/Plugins  Version:  None

**Additional context**

**Comment by Rabbit0w0** [comment]
Please tell us your current Mohist version

**Comment by Chintam** [comment]
Mohist build: f2d4264
