### ISSUE TITLE
Server Crash, PistonPush Error

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#386]
Random Error that causes Server Crash

https://hasteb.in/unakawoj

**Comment by Erafle** [comment]
I had this error yesterday too. It's a bug with a recent build. You need to downgrade Mohist again and again to find which build is starting to do that.

EDIT: It seems this error start happening on Build #586 (Mohist-1.12.2-81a1939-server.jar). Downgrade to Build #585 (Mohist-1.12.2-310ebdb-server.jar) and disable update-check and auto-update in mohist-config.

**Comment by NovaPixell** [comment]
okay thanks, but fix this bug in the newer version!

**Comment by TansuoTro** [comment]
Can you paste the report on this website? Sorry, I can't open the above website(hasteb.in)
please go to https://paste.ubuntu.com/

**Comment by NovaPixell** [comment]
Here: https://paste.ubuntu.com/p/kSVKNqWG8X/

**Comment by NovaPixell** [comment]
Still the same problem. Do you solve it? https://paste.ubuntu.com/p/mYjVyvhM9W/

**Comment by NovaPixell** [comment]
The problem concerns precisely these cursed pistons. In fact, in a gym generated by pixelmon, if you clicked a button to activate them, the server crashes ...

**Comment by Heriptik** [comment]
Same issue can you patch this problem ? I use Build 1.12.2-0fb4b27

Error crash : https://paste.ubuntu.com/p/VZQwnMmbB7/

thanks

**Comment by NovaPixell** [comment]
Can you solve because the problem is serious?

**Comment by NovaPixell** [comment]
I used the latest version of Mohist, and I have the same issue. I can attach a video.

Crash Report: https://paste.ubuntu.com/p/Tv8Fm2FzKg/

Video: https://streamable.com/yzvs1u

**Comment by NovaPixell** [comment]
I can point out that with the Build "Mohist-1.12.2-310ebdb-server", this problem does not occur. Unfortunately, I am now forced to use this build temporarily.

**Comment by Rabbit0w0** [comment]
> I can point out that with the Build "Mohist-1.12.2-310ebdb-server", this problem does not occur. Unfortunately, I am now forced to use this build temporarily.

Fixing it, wait please :D

**Comment by NovaPixell** [comment]
When a new release?

**Comment by Shawiizz** [comment]
Now :)

**Comment by Shawiizz** [comment]
https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/619/

**Comment by PierreBouffartigue** [comment]
Problem solved
