### ISSUE TITLE
[1.12.2] Error with Nether wart block, concrete and other

### ISSUE THREAD

**Issue by Heriptik** [Teneted/Tenet#388]
**Describe the bug**
Hi, place or break concrete block with a WorldGuard, Essentials or FactionsUUID plugins installed in Mohist spam error in your console.

**To Reproduce**
1. Install Worldguard and WorldEdit (latest 1.12.2)
2. Place / break concrete or nether wart block
3. Check console

**Info (please complete the following information):**
- Mohist version 1.12.2-fc80d13

**Additional context**
Error console : [https://hastebin.com/ozotejotis.sql](https://hastebin.com/ozotejotis.sql)

**Comment by wdog5** [comment]
![image](https://user-images.githubusercontent.com/40519136/87118773-cac18680-c2ae-11ea-986f-c586be327b5e.png)

**Comment by wdog5** [comment]
Sorry I cannot read....

**Comment by wdog5** [comment]
Please give it by  https://paste.ubuntu.com

**Comment by Heriptik** [comment]
https://pastebin.com/raw/0Wc5uc1s

**Comment by Heriptik** [comment]
Hi, same error with the shulker box, log error : https://pastebin.ubuntu.com/p/J3gHRGM2ZX/

**Comment by Shawiizz** [comment]
Hi, can you try to find in which build this appears ? Or maybe it's caused by a plugin or a mod...
