### ISSUE TITLE
[1.7.10] Duplication with chunk overflow and rollback

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#39]
_Hello o/_

**Mohist Version:** Build 47

_A fairly old universal duplication that works on almost any server core. As far as I know, this is quite simply fixed, but for some reason no one has officially implemented this fix._

**How duplication works:**

Everything is based on the preservation of the chunk, and more precisely on its impossibility during overflow. It does not matter what exactly we are going to duplicate, the main thing is to find the most acceptable way for you to overflow the chunk.

**How to reproduce duplication:**

You can check the timecodes (TC) from the video.
**Link:** https://youtu.be/7MAjL7mcOzE

1. First of all, we need something with which we will overflow the chunk. It can be any item capable of storing NBT. For ease of understanding, I selected signed books. Each of the 50 pages of the book is full of different characters (there are no identical pages) ([TC](https://youtu.be/7MAjL7mcOzE?t=19)).
2. Next, we select a chunk that is not yet overflowing and place duplicate items in it ([TC](https://youtu.be/7MAjL7mcOzE?t=45)). Also a good solution would be to add to this list those items that we use FOR duplication (like my books), since in the process some of them will be destroyed.
3. Now we need to save the chunk with the items selected for duplication. To do this, just disconnect from the server for a few seconds and reconnect ([TC](https://youtu.be/7MAjL7mcOzE?t=56)).
4. Now the most important thing, we have to overflow the chunk. To do this, I copy the previously prepared layer of chests with books inside, and then paste the new layers above. After 2-3 layers, the chunk overflows ([TC](https://youtu.be/7MAjL7mcOzE?t=98)). Note that I did not copy the chest with duplicate items, but it is within the chunk.
5. Now we just pick up our duplicate items from the chest (I just broke the chest) and reconnect to the server again so that the overflowing chunk tries to save ([TC](https://youtu.be/7MAjL7mcOzE?t=116)).
6. As we can see, the chunk rolled back to its initial state (until the moment after our first reconnection), because it could not be saved due to overflow, and a broken chest appeared with all our duplicate items ([TC](https://youtu.be/7MAjL7mcOzE?t=142)).

**Comment by terrainwax** [comment]
Is it possible to have your map i have made a fix for it but i need to try it before updating

**Comment by GedeonGrays** [comment]
> Is it possible to have your map i have made a fix for it but i need to try it before updating

Of course. Coordinates of the ender portal: 888, 26, 290

Map download link: https://www.dropbox.com/s/6g5ne3bihxsurgc/world.zip?dl=0

**Comment by terrainwax** [comment]
what's worldedit are you using ?

**Comment by GedeonGrays** [comment]
> what's worldedit are you using ?

Plugin: worldedit-bukkit-6.1.9
and
Mod: worldedit-forge-mc1.7.10-6.1.1-dist

**Comment by terrainwax** [comment]
ok my fix work perfectly i will update soon

**Comment by GedeonGrays** [comment]
> ok my fix work perfectly i will update soon

You are a great fellow. Thank you for your work :3

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work. I close the issue.
