### ISSUE TITLE
Issue with Simply Jetpacks

### ISSUE THREAD

**Issue by Osprey4444** [Teneted/Tenet#40]
Server crashes when trying to initialize simpy jetpacks.

What it says on console - https://paste.ee/p/QFMUs
Crash Report - https://paste.ee/p/1i24C

Works fine when removing simply jetpacks, but SJ is needed for the packs progression system.

**Comment by Mgazul** [comment]
I used the latest build, installed RedstoneFlux-1.12-2.1.0.6-universal and SimplyJetpacks2-1.12.2-2.2.14.67, everything works fine

**Comment by tiagoadp** [comment]
I got the same problem like an year ago, using mohist build 69... Using Omnifactory 1.2.2 CE.

https://paste.ee/p/DUp5H

Tnx for your time.
