### ISSUE TITLE
[1.7.10] Is TickProfiler allowed?

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#41]
_Hello o/_

Does it make sense to refrain from using TickProfiler with Mohist? Given the infamous KCauldron and Thermos experience, could a similar problem migrate to Mohist?

**Link to the source of the question:** https://github.com/CyberdyneCC/Thermos/issues/52

_P.S. Of course, the question may seem silly, but I can not find the answer to it myself. In any case, thanks for your time._

**Comment by Mgazul** [comment]
Yes, you can ask any questions about 1.7.10 here

**Comment by GedeonGrays** [comment]
> Yes, you can ask any questions about 1.7.10 here

So, are there any problems using TickProfiler? Or does Mohist have nothing like problems with KCauldron and Thermos? :3

**Comment by Mgazul** [comment]
Need to test! No one has responded to this question yet

**Comment by GedeonGrays** [comment]
> Need to test! No one has responded to this question yet

Thanks for the answer. I will monitor the status of this issue.
