### ISSUE TITLE
Pixelmon Generation Crash

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#414]
This bug happens randomly, I don't know how to reproduce it. I spoke to the Pixelmon developers and they confirmed to me that this error is caused by Mohist.

https://paste.ubuntu.com/p/vgBXdHrKyb/

**Comment by TansuoTro** [comment]
Roger that

**Comment by Rabbit0w0** [comment]
This problem seems like another problem we fixed, try the latest build and tell us the problem details?

**Comment by NovaPixell** [comment]
Ok!

**Comment by NovaPixell** [comment]
A new Crash from Pixelmon Generation:

https://paste.ubuntu.com/p/rzh43cvgHF/

By the way, did you solve the Piston Push problem with build 610? or not yet?

**Comment by PierreBouffartigue** [comment]
Problem solved
