### ISSUE TITLE
Exception in thread error. not even a crash log generates. build 608

### ISSUE THREAD

**Issue by realflow100** [Teneted/Tenet#417]
![4b81163f-e1d3-40f2-91c6-f339c21907c6](https://user-images.githubusercontent.com/16261960/87251519-5d426100-c43a-11ea-8ac2-8c32d040fdc7.png)
**Describe the bug**
Exception in thread error. not even a crash log
Happens even in a fresh folder with only the server jar file and nothing else.

screenshot was really hard to take because it flashed so fast.

**To Reproduce**
1. Try to start the jar with .bat it flashes for a brief moment saying thread error
if you start without a .bat. it appears in task manager processes list for a split second. thats it.

**Expected behavior**
it starts successfully and generates a new world.

**Info (please complete the following information):**
- Mod/Plugins Name: None
 - Mod/Plugins  Version: None

**Comment by TansuoTro** [comment]
OK, I saw it

**Comment by TansuoTro** [comment]
You are missing some library files. You can try to delete the libraries folder so that the server will download it again

**Comment by Rabbit0w0** [comment]
Download the libraries again.

**Comment by realflow100** [comment]
It literally doesnt generate a libraries folder or log files!!!!!

**Comment by realflow100** [comment]
Only a config folder generates with mohist.yml

**Comment by realflow100** [comment]
![image](https://user-images.githubusercontent.com/16261960/87270797-408c4480-c49f-11ea-9e1c-03fbb610ce74.png)
Thats all it generates when i run it! nothing else at all

Its not downloading a libraries folder for me to be able to delete one
Same issue with build 609

**Comment by realflow100** [comment]
Why was this issue closed?? its not solved or fixed! its still a problem :( I cant start a server it wont work.

**Comment by Rabbit0w0** [comment]
Check your Internet and make sure you are using the latest build.

**Comment by realflow100** [comment]
My internet is very good stable and fine I'm able to watch 4k 60FPS youtube without any buffering issues. no issues on speedtest website either. google works nothings wrong there.

And I am trying the latest build! I even disabled antivirus and redownloaded to a new folder to see if that would help and it made no difference.

**Comment by Shawiizz** [comment]
I know what's wrong, the devs need to remove new MohistConfig().init(); in copyMohistConfig() method, or place MohistConfigUtil.copyMohistConfig(); after libraries download and it will fix this problem.

**Comment by Rabbit0w0** [comment]
Sorry, i dont check the code completely because im using Mohist with offline version. I will fix it in 10 minutes

**Comment by Rabbit0w0** [comment]
> I know what's wrong, the devs need to remove new MohistConfig().init(); in copyMohistConfig() method, or place MohistConfigUtil.copyMohistConfig(); after libraries download and it will fix this problem.

`            System.setProperty("log4j.configurationFile", "log4j2_mohist.xml");
        if (bMohist("check_libraries")) DownloadLibraries.run();
        MohistConfigUtil.copyMohistConfig();
        MappingFix.init();
        if (!hasAcceptedEULA()) {`
But it is alright

**Comment by realflow100** [comment]
Whats even going on?

**Comment by Rabbit0w0** [comment]
> Whats even going on?

Actually, i dont know, im fixing it

**Comment by Rabbit0w0** [comment]
Fixed, download the latest build.
