### ISSUE TITLE
When sending commands via RCON cpu is hard work.

### ISSUE THREAD

**Issue by baominix** [Teneted/Tenet#424]
**Describe the bug**
When sending commands via RCON cpu is hard work.

RCON php [https://github.com/Rauks/Minecraft-RCON](https://github.com/Rauks/Minecraft-RCON)

This is an image while is not command.
[https://www.picz.in.th/image/rcon1.5ufAZk](https://www.picz.in.th/image/rcon1.5ufAZk)

1 command
[https://www.picz.in.th/image/rcon2.5ufC9N](https://www.picz.in.th/image/rcon2.5ufC9N)

more command
[https://www.picz.in.th/image/rcon3.5uf6pQ](https://www.picz.in.th/image/rcon3.5uf6pQ)

Build #612 Mohist-1.12.2-0fb4b27-server.jar
no mod
no plugin

**Comment by Rabbit0w0** [comment]
Not a bug, problem also happened in other servers.

**Comment by baominix** [comment]
OK, plugin websender is probably the right choice.
