### ISSUE TITLE
[Permission] Error with forge

### ISSUE THREAD

**Issue by Flashback083** [Teneted/Tenet#426]
**Describe the bug**
When creating permission in forge sidemod by using `player.canUseCommand(0,"test");` it will create under `minecraft.command.test` instead of just `test`
**To Reproduce**
1. Create forge sidemod
2. Create permission by using `player.canUseCommand(0,"yourpermission");`  with a command
3. Install luckperm on bukkit
4. Check the perm checked by Luckperm by doing `/lp verbose record yourname` then `/lp verbose paste`

**Comment by Flashback083** [comment]
For helping, a friend @ licious help me to find a fix for custom forge mod, but still need to fix it for at least mod which we can't modify
There is the part of the code which make the permission working (By licious)
: https://gist.github.com/Flashback083/167d3dc8260e2c83477be1e5fa5c771b

**Comment by Mgazul** [comment]
modid.command.commandName

**Comment by Mgazul** [comment]
There is no player.canUseCommand(0,"yourpermission");
Only  canUseCommand(int permLevel, String commandName) and canUseCommand(int permLevel, String commandName, String permissionNode);

**Comment by Flashback083** [comment]
yeah the first one
 canUseCommand(int permLevel, String commandName) 
use this in any sidemod to create custom permission will not create the normal one

**Comment by Mgazul** [comment]
This is not an error, you cannot use canUseCommand(int permLevel, String commandName)
The commandName in is set to permission, when mojang is designing the code, it is only specified as a command here
