### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#432]
"These libraries failed to download. Try again.

net.md-5:bungeecord-chat:1.15-20200526.094816-73"

1. Open forge-1.15.2-31.2.0-installer.jar
2. Click on install server
3. Choose the directory you want to install it
4. Click on Ok
5. See error.

**Comment by Shawiizz** [comment]
This will be fixed soon.

**Comment by wdog5** [comment]
Please download it by yourself,because of your Internet that you cannot download

**Comment by Shawiizz** [comment]
The right link is https://hub.spigotmc.org/nexus/content/groups/public/net/md-5/bungeecord-chat/1.15-SNAPSHOT/bungeecord-chat-1.15-20200526.094816-73.jar
