### ISSUE TITLE
Problems with latest EssentialsX

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#443]
**Describe the bug**
Quote from discord:
After HUGE update of EssentialsX it doesn't working on Mohist.
Error, if I execute command from EssX: https://pastebin.com/jp3cKLYY

**To Reproduce**
1. Install EssentialsX-2.18.0.0;
2. Install some mods (doesn't matter which ones. I tried only with BetterQuesting mod and modpack without it);
3. Try to execute any essentials command;
4. See error.

**Info:**
EssentialsX-2.18.0.3 (Also tried with EssentialsX-2.18.0.0)
LuckPerms-Bukkit-5.1.79
Vault-1.7.2-b107
Mohist-1.12.2-7bb5453-server. Also tried with Mohist-1.12.2-310ebdb-server - same problem.

**Additional context**
"lolwut" error from console:
![image](https://user-images.githubusercontent.com/38190325/87758757-bb45be80-c815-11ea-89a1-bfcb957f411d.png)

Previous major EssX version worked perfectly, but it weirds and very-very bad in most features. 2.18 contains a lot of fixes and API-changes, so, would be cool if it would work on Mohist

**Comment by VanillaChan6571** [comment]
I can confirm this. 

Temp Solution: EssentialsX-2.17.2

**Comment by kaliflowerx3** [comment]
https://github.com/EssentialsX/Essentials/issues/3494

EssentialsX doesn't plan on fixing this, but the issue comes up here: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/commands/Commandhat.java#L44

I was able to fork and get it working because I wasn't interested in the hats functionality.

Please let me know if I shouldn't post this here 👍

**Comment by SSKirillSS** [comment]
Still an issue.

Mohist-1.12.2-5d032f7-server
EssentialsX-2.18.0.9

![image](https://user-images.githubusercontent.com/38190325/88984357-0d86e500-d2d6-11ea-96a6-0656db5f1947.png)

**Comment by lucas11222** [comment]
> kaliflowerx3

No. Is Mohist The Poblem. https://essentialsx.net/do-not-use-mohist.html

**Comment by Shawiizz** [comment]
> > kaliflowerx3
> 
> No. Is Mohist The Poblem. https://essentialsx.net/do-not-use-mohist.html

Please do not spread false information. You should read this instead of blindly trusting EssentialsX: https://github.com/Shawiizz/MohistEssentialsX/blob/main/README.md

**Comment by Grass-block** [comment]
![image](https://github.com/user-attachments/assets/5a76130f-77b7-453b-a554-1c820b7797c9)
why dont adding this types of logic in backend
