### ISSUE TITLE
[1.7.10] Console spam "Failed to load"

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#45]
_Hello o/_

**Mohist Version:** Build 58
**Log:** https://pastebin.com/aLjdc3QU

_I understand that this is not an error at all, but a warning about the absence of some files on the first start of the server. It just seems to me that this kind of message does not make sense, given that at the next start of the server they will be gone._ 

Therefore, I propose to replace the output of this spam with something like:
"_File sample.txt not found. Generating..._"

_P.S. In any case, thanks for your time._

**Comment by TheXaver** [comment]
I propose to close issues. There is no point in correcting

**Comment by GedeonGrays** [comment]
> I propose to close issues. There is no point in correcting

Thanks for the suggestion. I agree that there is no practical sense in my proposal, but I am a supporter of aesthetics and cleanliness in the console. Therefore, I would like to receive a final answer from the developers.
