### ISSUE TITLE
Failed to handle packet and crash

### ISSUE THREAD

**Issue by LoopRich161** [Teneted/Tenet#454]
Very often an error appears that the package cannot be listened, it needs to be fixed.
More importantly, at some point in time, the server can simply drive all the players out of the server, then it will lag for 5 minutes, then the players will be able to log in, and after some time the server crashes for an unknown reason to me.
Can you tell me how to fix this or fix it in your code

It's my full log file: https://drive.google.com/file/d/1X9qpYHGBX4ebWjjyaqDDWklYz-Xbv8o4/view

**Comment by LoopRich161** [comment]
version mohist: 
Mohist-1.12.2-dde44c8-server.jar

**Comment by LoopRich161** [comment]
https://prnt.sc/tlbmad

**Comment by Mgazul** [comment]
Need a complete log, not a picture
