### ISSUE TITLE
Join Issue

### ISSUE THREAD

**Issue by noy98** [Teneted/Tenet#462]
**Describe the bug**

**To Reproduce**

**Expected behavior**

4Seasons_ lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 9

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name:
 - Mod/Plugins  Version: 

**Additional context**

**Comment by salomj** [comment]
I am also getting this issue

**Comment by Shawiizz** [comment]
This problem needs to be resolved urgently, a lot of persons having this issue on the latest build and a lot of others builds
