### ISSUE TITLE
[1.7.10] hurtResistantTime not reducing

### ISSUE THREAD

**Issue by AlexSocol** [Teneted/Tenet#47]
Hello
So I'm trying to slightly speedup player attack rate in `LivingHurtEvent` - `event.entityLiving.hurtResistantTime = 16`
But it is not working. Tried in single and Forge server - everything is fine

Mohist build 60

**Comment by terrainwax** [comment]
You need to increase maxhurtresistanttime

**Comment by AlexSocol** [comment]
Do you mean DEcrease? That's not the case, because I'm speeding up not all players, just several, if they has some custom property

**Comment by terrainwax** [comment]
you have to do something like this 
![image](https://user-images.githubusercontent.com/14014510/70499231-02016680-1b19-11ea-855a-c32ca21950c2.png)

**Comment by GedeonGrays** [comment]
I am very sorry, but I did not mention the issues above (37 and 39), at least it was not on purpose. This is the functionality of the github that I can’t disable.

**Comment by AlexSocol** [comment]
Whatever...
