### ISSUE TITLE
[1.7.10] Different hash function result

### ISSUE THREAD

**Issue by AlexSocol** [Teneted/Tenet#48]
Hello again

So I'm using hash function equal to [this](https://github.com/Vazkii/Botania/blob/1.7.10-final/src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java#L132) and getting different results on server and client (client is correct). Moreover, server returns different hash each try, while client returns the same (like it is supposed to). Tested on single and Forge server, everything was fine
Screenshot - https://imgur.com/a/u4c97TY

Mohist build 60

**Comment by terrainwax** [comment]
can i have the full code that you are using

**Comment by AlexSocol** [comment]
[Here](https://bitbucket.org/AlexSocol/alfheim/src/master/src/main/java/alfheim/common/item/equipment/tool/ItemRealitySword.kt#lines-75). It's Kotlin though... Hope you understand

**Comment by AlexSocol** [comment]
Just tested it on Windows 7 Oracle jvm and on Debian 8 OpenJDK (both just Forge)... It works on Windows and not on Debian. So I think it depends on Java implementation. Sorry for falsereporting.
But I would be grateful if you tell me a possible way out
