### ISSUE TITLE
[求助] Bad packet id 9

### ISSUE THREAD

**Issue by jerrita** [Teneted/Tenet#483]
查询过了以前的issues，使用最新的#628，尝试删除server.properties，但都没有用
还有其他解决方案吗

**Comment by moemoli** [comment]
请耐心等待，原因还在查找中。
请尝试#609~#610，我们会尽快解决这个问题

**Comment by jerrita** [comment]
> 请耐心等待，原因还在查找中。
> 请尝试#609~#610，我们会尽快解决这个问题

嗯嗯，okk，辛苦啦

**Comment by lushangkan** [comment]
> 查询过了以前的issues，使用最新的#628，尝试删除server.properties，但都没有用
> 还有其他解决方案吗

请你可以告诉我们这个问题是怎么产生的吗?
Could you please tell us how this problem arises?

**Comment by moemoli** [comment]
请问可以提供下如何触发的这个问题吗，包括服务端的版本，mod列表，插件列表等等。
如果可以的话请您提供下您目前服务端的整合（不包括玩家数据），来帮助我们修复这个问题

**Comment by jerrita** [comment]
> 请问可以提供下如何触发的这个问题吗，包括服务端的版本，mod列表，插件列表等等。
> 如果可以的话请您提供下您目前服务端的整合（不包括玩家数据），来帮助我们修复这个问题

610能用以后就把之前的删掉了.....
不过我当时配置的时候是先运行一遍主程序生成配置，然后把[EnigTech2-1.4.1-server](https://github.com/ET-Team/EnigTech2)包里的配置和mod丢了进去，客户端加入的时候就出现了这个问题

**Comment by lushangkan** [comment]
类似问题[https://github.com/Mohist-Community/Mohist/issues/416](url)

**Comment by xingxingchuan** [comment]
同样问题，即使是不加入模组后也会显示什么Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 9
客户端显示连接中止

**Comment by lushangkan** [comment]
> 同样问题，即使是不加入模组后也会显示什么Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 9
> 客户端显示连接中止

您可以提供你的服务端配置吗?您是什么时候出现此问题的?

**Comment by xingxingchuan** [comment]
我是昨天搭建Mohist服务器时就出现了，现在切换到610是没问题的；
我是直接用脚本启动核心来搭建服务器。
你具体需要哪些文件？

**Comment by lushangkan** [comment]
[该](https://github.com/Mohist-Community/Mohist/commit/1669f1f34836513919567793d1ea4c685d2c08df)提交导致Bad Packet id 9问题。
[This](https://github.com/Mohist-Community/Mohist/commit/1669f1f34836513919567793d1ea4c685d2c08df) commit caused the Bad Packet id 9 issue.
