### ISSUE TITLE
[1.7.10] Crash with Bookshelf

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#49]
_Hello o/_

**Mohist Version:** Build 61
**Bookshelf Version:** 1.0.4.187
**Crash report:** https://pastebin.com/4eS9a3h7

Crash during server startup.

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
