### ISSUE TITLE
Error log when starting Mohist server with TrHologram installed

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#499]
**Describe the bug**
When starting my Mohist server with TrHologram plugin installed, there will be error logs posted.
I copied it and paste it here:
https://paste.ubuntu.com/p/zFNcD5VTqW/

**To Reproduce**
1. Install TrHologram plugin.
2. Start server.
3. See error.

**Info (please complete the following information):**
- Mod/Plugins Name: TrHologram
 - Mod/Plugins  Version: 1.11

**Additional context**
My Mohist version is Mohist-1.12.2-b704e64-server.

**Comment by Mgazul** [comment]
Taboolib is not compatible
