### ISSUE TITLE
[1.7.10] Crash with MalisisCore

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#50]
_Hello o/_

**Mohist Version:** Build 61
**MalisisCore Version:** 0.14.3
**Log:** https://pastebin.com/xDYyWAUe

Crash during server startup.

_P.S. I know this issue is a duplicate of issue #29. I created a copy asking not to close until the problem is resolved._

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
