### ISSUE TITLE
Can i do custom login?

### ISSUE THREAD

**Issue by Zlatex** [Teneted/Tenet#504]
can i change the link to check user login if online mode is enabled on the server? If so, what files do I need to change?

**Comment by Shawiizz** [comment]
I don't really understand what do you want to do... can you explain please ?

**Comment by trucsetastuces** [comment]
server.properties : 

online-mode=true (premium) (online-mode enabled)
online-mode=false (crack) (online-mode disabled)

Cordialement Dwenrell - Dev Trucsetastuces

**Comment by Zlatex** [comment]
I need people to be able to login in only through my launcher and not through the official launcher.

**Comment by Alink-Marty** [comment]
What does this have to do with Mohist? xd

**Comment by Zlatex** [comment]
Well, I need the server to check if the user is logged in, and for that I need to change the official check link in the server files, but I don't know where it is.

**Comment by Shawiizz** [comment]
You mean replace Mojang auth link by your link ?

**Comment by Zlatex** [comment]
yes

**Comment by trucsetastuces** [comment]
You have to go to the file that I indicated to you above and put onlinemode = false as its its no longer goes through the mogang server and you can as its inci go through your launcher

**Comment by Shawiizz** [comment]
Unfortunately you can't... The auth is managed by an external library (yggdrasil auth)

**Comment by Zlatex** [comment]
Ok, thanks, I get it.

**Comment by Shawiizz** [comment]
You can maybe make a plugin to change the auth.

**Comment by ishland** [comment]
This issue is not related to Mohist. Use authlib-injector to use your own yggdrasil server
