### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by Hexeption** [Teneted/Tenet#505]

**Comment by Hexeption** [comment]
Found more files you took

https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/dispenser/IDispenseItemBehavior.java.patch#L544
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/entity/passive/SheepEntity.java.patch#L30
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch#L494-L520
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/fluid/LavaFluid.java.patch#L41
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/network/play/ServerPlayNetHandler.java.patch#L170
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/world/chunk/storage/RegionFileCache.java.patch#L7-L14
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/patches/minecraft/net/minecraft/world/gen/feature/structure/ScatteredStructure.java.patch#L24-L27
https://github.com/Mohist-Community/Mohist/blob/8ebf54e8ded39bc58d7199fa50dd2c0e4d342f50/src/main/java/org/bukkit/craftbukkit/v1_15_R1/util/CraftMagicNumbers.java#L79-L82

**Comment by Hexeption** [comment]
https://github.com/Mohist-Community/Mohist/blob/1.15.2/src/main/resources/mappings/nms.srg

**Comment by Hexeption** [comment]
This one has my name on it 😆 
https://github.com/Mohist-Community/Mohist/blob/1.15.2/src/main/java/org/spigotmc/FINDME.java

**Comment by fakeTrotsky** [comment]
omg

**Comment by fakeTrotsky** [comment]
all right。。。

**Comment by Hexeption** [comment]
Is that all you have to say?

**Comment by fakeTrotsky** [comment]
NO, our developers made a huge mistake.

**Comment by Hexeption** [comment]
Yes they have.

**Comment by fakeTrotsky** [comment]
I think maybe I should add Magma to the list of Credis? This error is really big, I can only do this for now...

**Comment by Hexeption** [comment]
There's a lot more than that most of the craftbukkit and patch folder are exactly the same as magma remove the branch or else

**Comment by GeorgeWL** [comment]
Since when was Magma closed-source?

**Comment by Shawiizz** [comment]
Magma 1.16 is closed source since 1 week. Also they are selling Magma 1.16 builds while it's closed source and they don't have the right to distribute builds since it's closed source. So they are breaking the forge license.

**Comment by GeorgeWL** [comment]
https://github.com/magmafoundation/Magma/blob/master/LICENSE
