### ISSUE TITLE
Fabric-1.16 branch violates Bukkit4Fabric's license

### ISSUE THREAD

**Issue by Martmists-GH** [Teneted/Tenet#509]
The majority, if not the entirety of the Fabric implementation is a copy-pasted from [Bukkit4Fabric](https://github.com/fungus-soft/bukkit4fabric), licensed under LGPL, and as such, violates the license.

**Comment by wrdg** [comment]
I think you should re-read the license for Bukkit4Fabric, and then check the license for Mohist. @martmists

**Comment by Shawiizz** [comment]
Read the two licenses again, and you will see that Mohist does not violate the license of Bukkit4Fabric. Also i can't find any thing which is copy pasted from Bukkit4Fabric.

**Comment by F4JBS** [comment]
Mohist is licensed under GPLv3 and Bukkit4Fabric is licensed under LGPLv3, therefore Mohist may include code from Bukkit4Fabric. You may check the FSF/GNU websites for more information.

In particular, check https://www.gnu.org/licenses/license-compatibility.en.html : "If a program permits use under GNU LGPL version 3 or later, you can relicense it to GPL version 3 or later"

However, it would be an issue if code was copied and uncredited. It that's the case, please provide examples/proof.

**Comment by Martmists-GH** [comment]
You don't have the right to "relicense" anything that you didn't write without the author's explicit permission. However, if you take something and make changes (of which renaming the package does NOT count), you're creating a derivative work. You can choose how to license that derived work, but only under the conditions of the code you included.

**Comment by F4JBS** [comment]
Again, if you believe that this branch is plagiarism or merely a renamed Bukkit4Forge or has pieces of code from Bukkit4Forge without proper crediting, please provide proof.

Also, what you said about not being able to "relicense" contradicts what's written on the GNU website. If what you say is true, please prove it by quoting excepts from the license file, or the GNU or FSF websites.

**Comment by Hexeption** [comment]
Util Class the same and even got the projects name.
https://github.com/Mohist-Community/Mohist/blob/a4ecad1651c67d69271da7edb0179825b734ab39/src/main/java/red/mohist/utils/UtilsFabric.java#L11
https://github.com/fungus-soft/bukkit4fabric/blob/6b1ad28d38f606730852560489b9439e3598b4f9/src/main/java/com/fungus_soft/bukkitfabric/Utils.java#L11

Most of the Mixins are the same 

https://github.com/Mohist-Community/Mohist/blob/a4ecad1651c67d69271da7edb0179825b734ab39/src/main/java/red/mohist/mixin/player/MixinServerPlayeEntity.java#L40

https://github.com/fungus-soft/bukkit4fabric/blob/master/src/main/java/com/fungus_soft/bukkitfabric/mixin/MixinBlockEntity.java
https://github.com/Mohist-Community/Mohist/blob/Fabric-1.16/src/main/java/red/mohist/mixin/entity/MixinBlockEntity.java

**Comment by F4JBS** [comment]
oof, that's pretty bad plagiarism indeed, apologies for being rude earlier

**Comment by kingdevnl** [comment]
First they stole code from magma.....

Do they never learn here...

**Comment by Shawiizz** [comment]
@kingdevnl the only thing you are is a kid.
