### ISSUE TITLE
[1.7.10] Crash with Thaumcraft and CarefulCastCorrector

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#51]
_Hello o/_

**Mohist Version:** Build 61
**Thaumcraft Version:** 4.2.3.5
**CarefulCastCorrector Version:** [1.0](https://www.curseforge.com/minecraft/mc-mods/careful-cast-corrector-ccc/files/2726649)
**Crash report:** https://pastebin.com/RQ1ZyczS

Crash during server startup.

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
