### ISSUE TITLE
crash while ticking world

### ISSUE THREAD

**Issue by roughanddai** [Teneted/Tenet#512]
*(My English is extremely terrible,so following use Simplified Chinese）*  
错误起因：当玩家进入游戏，并且使用authme登入后，不久就会服务器崩溃  
（已在catserver和forge官方端测试，工作均正常，仅在mohist崩溃）  
crashreport和log:  https://gist.github.com/roughanddai/8bf45c989ba01043a8ba5d1fc60faaf9  
https://gist.github.com/roughanddai/26c397314ba8f77f2f4e16b199705762  
以下是forge的config:  
https://gist.github.com/roughanddai/a511d8de2e084e6ad54d58f6a928405e

**Comment by Mgazul** [comment]
崩溃日志中显示你并不是最新构建

**Comment by roughanddai** [comment]
> 崩溃日志中显示你并不是最新构建

最新架构出了类似的问题#515

**Comment by Mgazul** [comment]
最新構建的問題 我知道 我自己寫出來的
