### ISSUE TITLE
EssentialsX problem

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#516]
P.S. - This issue was already reported, but seems like it doesn't fixed: https://github.com/Mohist-Community/Mohist/issues/443

Describe the bug
Quote from discord:
After HUGE update of EssentialsX it doesn't working on Mohist.
Error, if I execute command from EssX: https://pastebin.com/jp3cKLYY

To Reproduce

Install EssentialsX-2.18.0.0;
Install some mods (doesn't matter which ones. I tried only with BetterQuesting mod and modpack without it);
Try to execute any essentials command;
See error.
Info:
EssentialsX-2.18.0.3 (Also tried with EssentialsX-2.18.0.0)
LuckPerms-Bukkit-5.1.79
Vault-1.7.2-b107
Mohist-1.12.2-7bb5453-server. Also tried with Mohist-1.12.2-310ebdb-server - same problem.

Additional context
"lolwut" error from console:
![image](https://user-images.githubusercontent.com/38190325/89423759-94591900-d73f-11ea-9b8c-3fc7dc6877c9.png)

Previous major EssX version worked perfectly, but it weirds and very-very bad in most features. 2.18 contains a lot of fixes and API-changes, so, would be cool if it would work on Mohist

**Comment by Mgazul** [comment]
You are using an outdated mohist version
