### ISSUE TITLE
[1.7.10] Crash with PrivateMod

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#52]
_Hello o/_

**Mohist Version:** Build 61
**Log:** https://pastebin.com/iJZ0Gd12

Crash during server startup.

PrivateMod works correctly on both Forge and Thermos.

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
### Fix confirmed. Thanks for the work.
