### ISSUE TITLE
Reflection of Vec3D (net.minecraft.util.math.Vec3d) is broken

### ISSUE THREAD

**Issue by bergerkiller** [Teneted/Tenet#527]
**Describe the bug**
Calling methods such as _getDeclaredMethods()_ on the Class of _net.minecraft.util.math.Vec3d_ causes a class loading error at runtime for Vec2f.

**To Reproduce**
Execute the following code (done from a plugin, but this should not matter.)
```
try {
    Class<?> vec3dclass = Class.forName("net.minecraft.util.math.Vec3d");
    vec3dclass.getDeclaredMethods();
} catch (Throwable t) {
    t.printStackTrace();
}
```

**Expected behavior**
Methods such as getMethods()/getDeclaredMethods() should not throw.

**Error**
```
java.lang.NoClassDefFoundError: net/minecraft/util/math/Vec2f
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethods(Unknown Source)
    at com.bergerkiller.bukkit.test.Main.<clinit>(Main.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.Vec2f
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
```

**Info (please complete the following information):**
- Mod/Plugins Name: BKCommonLib ( https://ci.mg-dev.eu/job/BKCommonLib )
 - Mod/Plugins  Version: 1.16.2-v1 (in-dev)
- Server version: git-Mohist-1.12.2-72ba39a (MC: 1.12.2)(Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Additional context**
As part of initializing my library it matches all sorts of things by checking using reflection what fields/methods are available, and selecting the right one depending on server type. This error popped up deep in the code when initializing Vec3D mixins.

**Comment by Mgazul** [comment]
net/minecraft/util/math/Vec2f is client class

**Comment by bergerkiller** [comment]
Tested the new build with your changes https://github.com/Mohist-Community/Mohist/commit/626829f6cb62d71f414a7295c149cd726f001c63 and that fixed the error on my end.
