### ISSUE TITLE
Error with Factions plugin (SaberFactions)

### ISSUE THREAD

**Issue by RomualdYT** [Teneted/Tenet#531]
**Describe the bug**

When I do /f disband, I get this error :
https://prnt.sc/u0lgwi

Looks like it happens each time I put a modded block : https://prnt.sc/u0lhcp
I hope you will find a way to fix it :slight_smile:

**To Reproduce**
Install SaberFactions and try to disband or put a modded block

**Info (please complete the following information):**
- Mod/Plugins Name: SaberFactions Plugin
 - Mod/Plugins  Version: 

**Additional context**

**Comment by RomualdYT** [comment]
Error with /f perms
https://prnt.sc/u0li4f

**Comment by Mgazul** [comment]
Use SaberFactions-2.4.4-RC to test again, or delete the plug-in configuration to make again

**Comment by RomualdYT** [comment]
I use now the last version with stock configuration, and I still have the problem when I put a modded block :(
Same as that : "Looks like it happens each time I put a modded block : https://prnt.sc/u0lhcp"

**Comment by Mgazul** [comment]
https://cdn.discordapp.com/attachments/436907032352653312/698176876656590918/Factions.jar

**Comment by RomualdYT** [comment]
This version is outdated and not complete. Lot of problems, of things that aren't working for the game mode. You should make a version for SaberFactions which is the best plugin for the game mode Factions
