### ISSUE TITLE
URGENT: Crash Report

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#532]
Crash Report:  https://paste.ubuntu.com/p/Q6NxZHHCbb/

**Comment by Shawiizz** [comment]
Same as #449. Please don't duplicate your issue.

**Comment by NovaPixell** [comment]
Ah sorry I hadn't really noticed. But now that problem gives me a repeat like every five minutes and I don't understand what triggers it...

**Comment by Shawiizz** [comment]
We can't know why this crash happens since we don't know how to reproduce it

**Comment by NovaPixell** [comment]
From the crash report can't figure out what triggers it?

**Comment by Mgazul** [comment]
Could not query the reason, what were you doing before the crash

**Comment by Mgazul** [comment]
Same as #449, so close
