### ISSUE TITLE
Nature's Aura TileEntity "Imperceptible Placer" <naturesaura:placer> not actually placing (but works w/ Forge server) - 1.12.2

### ISSUE THREAD

**Issue by ubergarm** [Teneted/Tenet#534]
**Describe the bug**
Building a Nature's Aura "Imperceptible Placer" block does not actually ever place blocks even when configured properly. Works as expected when running forge server with exact same `server.properties` config, mods, and world.

**To Reproduce**
1. Install Mohist-1.12.2
2. Install [Nature's Aura](https://www.curseforge.com/minecraft/mc-mods/natures-aura)
3. Start the server, and connect w/ client and go into creative mode with cheats on
4. Run these commands to get the needed items and place them in correct configuration (tutorial video linked below)
```
/give @p naturesaura:placer
/give @p minecraft:chest
/give @p minecraft:item_frame
/give @p minecraft:stone 64
/give @p minecraft:planks 64
```

**Expected behavior**
For example, build the `Imperceptible Placer` in a flat open area and place the chest on top of it. Fill the chest with some wood planks. Put the item frame on side of the placer. Put a wood plank in the item frame. Now build some stone around within 5 block radius of the `Placer` and it *should* build wood planks on top of any stone you built.

**Screenshots**
[Build a setup like this and add a stone into the item frame, and it *should* begin to build wood planks.](https://ibb.co/Z8sg4Pc)

**Info**
 - [Mohist-1.12.2-e28b82d-server.jar](https://github.com/Mohist-Community/Mohist/commit/e28b82d30b7ba340dd8fea914934fb3a0b0d7b95) (maybe something w/ fakePlayer compatibility??)
 - [forge-1.12.2-14.23.5.2854.jar](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html)
 - [NaturesAura-18.1.jar](https://www.curseforge.com/minecraft/mc-mods/natures-aura)
 - [naturestopography-1.0.2.jar](https://www.curseforge.com/minecraft/mc-mods/natures-topography)
 - [Topography-1.12.2-1.14.2.jar](https://www.curseforge.com/minecraft/mc-mods/topography)
There are also other mods in this custom pack, and Mohist has been running like a champ until I hit this odd bug.

**Additional context**
#### Topography
This modpack is also using natures topography to sort out compatibility mod between topography and nature's aura. Versions and links listed above.

#### Building Tutorial
This great video shows how to configure the blocks: [Nature's Aura: Getting Started! Bit-by-Bit by Mischief of Mice!](https://youtu.be/APE0UWPGBDM?t=1381) (links right to the information)

**Comment by ubergarm** [comment]
Everything you need to test is available in my new modpack [Sky Magic Islands](https://www.curseforge.com/minecraft/modpacks/sky-magic-islands) thanks!

**Comment by Shawiizz** [comment]
Hello @ubergarm, can you try with latest build to see if this is fixed please ?

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug persist, please open new issue.
