### ISSUE TITLE
Casting EnderSkills Abilities on a newest Mohist version

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#535]
**Describe the bug**
When I cast ES (EnderSkills) ability server prints huge stacktrace to the console, but skills still work. Log: https://pastebin.com/wstpviLa

I see in log HolographicExtension, but idk is it relates to the problem.

**To Reproduce**
1. Just cast any ability. You can find guide how to learn and cast it in this issue: https://github.com/Mohist-Community/Mohist/issues/524

**Info (please complete the following information):**
Checked with: Mohist-1.12.2-56a8ba9-server, Mohist-1.12.2-62b4f3d-server, Mohist-1.12.2-4562b17-server, Mohist-1.12.2-626829f-server, Mohist-1.12.2-e28b82d-server. Before using these versions I'm stayed at Mohist-1.12.2-310ebdb-server, and with Mohist-1.12.2-310ebdb everything works fine.
EnderSkills-1.12.2-1.7.0.1
BetterHurtTimer-1.12.2-1.3.0.3

Cuz I see in logs HolographicExtension:
HolographicExtension-1.10.9

**Comment by SSKirillSS** [comment]
Looks like problem related to the HolographicExtension (https://www.spigotmc.org/resources/holographicextension.18461/)

When I remove it - everything works fine, but this is not a solution.

**Comment by SSKirillSS** [comment]
Tested with latest for now version of Mohist (mohist-1.12.2-31-server).

Still an issue.

**Comment by Shawiizz** [comment]
Hi, please try again with latest build and tell if your error happens with latest or no.

**Comment by Shawiizz** [comment]
Closing due to not responding.
If this still an issue, please open a new one.
