### ISSUE TITLE
EasyBackup 3.2.7 cannot be loaded

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#537]
**Describe the bug**
Start a Mohist server with EasyBackup 3.2.7 installed, but the EasyBackup plugin will not be loaded, throwing erroring logs instead.

**To Reproduce**
1. Install EasyBackup 3.2.7 on a Mohist server.
2. Start it.
3. Find erroring logs attached below in log file.

**Expected behavior**
EasyBackup is tested on Minecraft 1.12, it should work properly.

**Info (please complete the following information):**
- Mod/Plugins Name: EasyBackup
 - Mod/Plugins  Version: 3.2.7

**Additional context**
Mohist version: Mohist-1.12.2-72ba39a-server
Error log: https://paste.ubuntu.com/p/pSM8vnYCg9/

**Comment by Shawiizz** [comment]
Same as https://github.com/Mohist-Community/Mohist/issues/345. Please close this issue
