### ISSUE TITLE
Bewitchment's TileEntity "Witches' Cauldron" <bewitchment:witches_cauldron> fails to make Brews, but works with Forge - 1.12.2 

### ISSUE THREAD

**Issue by ubergarm** [Teneted/Tenet#544]
**To Reproduce**
1. Install Mohist-1.12.2
2. Install [Bewitchment](https://www.curseforge.com/minecraft/mc-mods/bewitchment)
3. Start the server, and connect w/ client and go into creative mode with cheats on
4. Run these commands to get the needed items and place them in correct configuration
```
/give @p bewitchment:witches_cauldron
/give @p bewitchment:stone_witches_altar 6
/give @p bewitchment:blessed_stone
/give @p minecraft:carpet
/give @p minecraft:lava_bucket
/give @p minecraft:water_bucket
/give @p bewitchment:mandrake_root 64
```

**Expected behavior**
1. Place the 6x stone witches altar blocks in a 2x3 rectangle on a flat area.
2. Hold the piece of carpet in your hand and right click the top of the altar and it will "cover it"
3. Hold the blessed stone and right click it anywhere on top of the altar to place it upon the altar
4. Right click any empty part or side of the altar with an empty hand and confirm it shows `32767/32767 (x32767)` altar power
5. Dig a one block hole and dump in the lava bucket within 16 blocks away from the altar
6. Place the witches cauldron above this lava block (might have to put something near it to build it in the place you want)
7. Fill the cauldron by dumping the water bucket into it and wait about 5 seconds for it to show the boiling effects
8. Hold the mandrake in your hand toss it into the cauldron with `q` and make sure it lands in the liquid
9. The liquid should turn Light Blue indicating everything is working and you can continue to create brews by throwing their specific ingredients etc. For example if you toss in an apple next, it would turn bright red. Then you can scoop out three bottles of your completed brew by right clicking the cauldron with vanilla empty glass bottles in your hand.

**What Actually Happens**

When using Mohist, the liquid immediately turns [Reddish Brown](https://www.color-hex.com/color/604040) indicating that there is a problem and the brewing attempt has failed. You have to clear the cauldron by tossing in some wood ash or break/place it to try again. Throwing an apple into this reddish brown liquid will not change colors, and you cannot scoop it out with vanilla empty glass bottles.

**Screenshots**
[Build a setup like this and and toss in mandrake, and it *should* turn light blue as shown in photo made running Forge server](https://ibb.co/948H2y3)

**Info**
 - [Mohist-1.12.2-b71b544-server.jar](https://github.com/Mohist-Community/Mohist/commit/b71b544380ad0f5eb336af8ff183e07bc40c8b6e)
 - [forge-1.12.2-14.23.5.2854.jar](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html)
 - [bewitchment-1.12.2-0.0.22.37.jar](https://www.curseforge.com/minecraft/mc-mods/bewitchment)

**Additional context**
#### TileEntity Source Code 
https://github.com/Um-Mitternacht/Bewitchment/blob/1.12.2/src/main/java/com/bewitchment/common/block/tile/entity/TileEntityWitchesCauldron.java

Another mod called [Performant](https://www.curseforge.com/minecraft/mc-mods/performant) likely has compatibility issues that cause a similar bug, however I do *not* have that installed in my modpack.

I didn't change any mods or config or world/saves, just switch out mohist jar to forge jar then it works fine.

Here is the link to my discussion on the [Bewitchment Github Issues Page](https://github.com/Um-Mitternacht/Bewitchment/issues/565#issuecomment-683480650) for cross reference

**Comment by ubergarm** [comment]
FWIW I did not have a `GrimoireMagia` or any personal Altar Power storage object when doing this test.

**Comment by SSKirillSS** [comment]
Can confirm.

**Comment by ubergarm** [comment]
Everything needed to test is available in my new modpack [Sky Magic Islands](https://www.curseforge.com/minecraft/modpacks/sky-magic-islands) thanks!

**Comment by gracieArmour** [comment]
Having the same issue. Have been searching far and wide for a solution with no success. Mohist tileentity config changes don't affect the issue either.

**Comment by jshalbrook** [comment]
Having the same issue. Is there a fix?
