### ISSUE TITLE
[1.12.2] crashes/errors/incompatibility with quark oddities matrix enchanting

### ISSUE THREAD

**Issue by xemnes** [Teneted/Tenet#546]
**Describe the bug**
When matrix enchanting is enabled in quark oddities, the server may sometimes crash with this error https://pastebin.com/eKcN0hip
looks like it might be an issue with timings being on?

if there is no crash, and the enchanting table modified by quark oddities is used, the console is spammed with: 
`Block at -609,88,-533 is ENCHANTMENT_TABLE but has vazkii.quark.oddities.tile.TileMatrixEnchanter@407746d8. Bukkit will attempt to fix this, but there may be additional damage that we cannot recover.`

also putting any item in any slot in the enchanting table when matric enchanting is enabled causes the item to be immediately deleted.

**To Reproduce**
have quark and quark oddities mods installed,
place an enchanting table
use it
check console
try put items in the enchanting table slots such as swords or tools

**Expected behavior**
matrix enchanting shouldnt cause errors or item deletion, should just work.

**Info (please complete the following information):**
- Mod/Plugins Name: quark, quark oddities
 - Mod/Plugins  Version: -r1.6-179 (the latest)

**Comment by SSKirillSS** [comment]
Can confirm.

**Comment by Mgazul** [comment]
Use the /dump material command and send the file to me! Thanks

**Comment by Mgazul** [comment]
Use, use the latest to test the problem again

**Comment by xemnes** [comment]
it seems to have fixed it. but the issue with using newer versions is i still cant use most spigot plugins like essentials as they always cause an error when using commands

**Comment by xemnes** [comment]
after looking into it, i downgraded to essentials 2.17 and essentials is now working properly again

**Comment by xemnes** [comment]
never mind, just encountered another crash with related to timings whilst using the enchanting table https://pastebin.com/Q7riDLHY

**Comment by Mgazul** [comment]
Use the /dump material command and send the file to me! Thanks

**Comment by xemnes** [comment]
sorry for the late reply, here you go.

https://pastebin.com/d9DzWM6S

**Comment by xemnes** [comment]
bringing this back up, seems the crashes only happen when timings is turned on 
crash report: https://pastebin.com/efqRHFfZ

this seems to happen if the enchanting table is in a loaded chunk, doesnt have to be used. and only happens with timings so i have to keep it turned off 

id like to be able to use timings to measure what might be causing the servers tps to drop but cant due to this crash.

**Comment by xemnes** [comment]
does this being closed mean the crashes with timings enabled is fixed?

**Comment by YoSoyDona** [comment]
> bringing this back up, seems the crashes only happen when timings is turned on
> crash report: https://pastebin.com/efqRHFfZ
> 
> this seems to happen if the enchanting table is in a loaded chunk, doesnt have to be used. and only happens with timings so i have to keep it turned off
> 
> id like to be able to use timings to measure what might be causing the servers tps to drop but cant due to this crash.

How can I turn off timings?

**Comment by xemnes** [comment]
> 
> 
> > bringing this back up, seems the crashes only happen when timings is turned on
> > crash report: https://pastebin.com/efqRHFfZ
> > this seems to happen if the enchanting table is in a loaded chunk, doesnt have to be used. and only happens with timings so i have to keep it turned off
> > id like to be able to use timings to measure what might be causing the servers tps to drop but cant due to this crash.
> 
> How can I turn off timings?

in paper.yml find timings
