### ISSUE TITLE
reload命令导致FastAsyncWorldEdit无法使用 WorldEdit can't running after run reload command 

### ISSUE THREAD

**Issue by rsp4jack** [Teneted/Tenet#548]
**Describe the bug**
当执行`/reload`后，FastAsyncWorldEdit对所有指令没有任何响应。
After run `/reload`, Can't exec all FastAsyncWorldEdit command.

**To Reproduce**
1. Run command `/reload`
2. Error reproduced.
---
1. 运行`/reload`
2. 错误重现。

**Expected behavior**
FastAsyncWorldEdit可以正常运行。
FastAsyncWorldEdit can running expected.

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: FastAsyncWorldEdit, WorldEdit
 - Mod/Plugins  Version: FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5, worldedit-forge-mc1.12-6.1.8-dist

**Additional context**
Mohist Version: `This server is running Mohist version 1.12.2-3a8f576 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)`

**Comment by Mgazul** [comment]
Usually we do not recommend using /reload
