### ISSUE TITLE
Vote Party Don't Load

### ISSUE THREAD

**Issue by hoctz** [Teneted/Tenet#549]
**Plugin Vote Party Don't load properly (Mohist 1.12.2)**

**Steps to Reproduce**
Get the plugin vote party
Drop it in your plugins folder
Start the server
- Looks that Vote Party don't load
Error message: https://hastebin.com/ruyiwufero.rb

I should run fine, but don't even load 
I've tested in spigot 1.12.2 and it works perfectly

**Error**
https://hastebin.com/ruyiwufero.rb

**Info (please complete the following information):**
- Mod/Plugins Name: VoteParty
 - Mod/Plugins  Version:  2.19

**Additional context**
Spigot Link: https://www.spigotmc.org/resources/voteparty-new-leaderboards-1-8-8-1-16-x-20-summer-sale.987/

**Comment by Mgazul** [comment]
I can't test the premium plugin, please send me the complete error log

**Comment by Mgazul** [comment]
After testing, I think this should be fixed by the plugin author
