### ISSUE TITLE
[1.12.2]Chat no longer works & console cannot do any commands(FastWorkbench)

### ISSUE THREAD

**Issue by Osprey4444** [Teneted/Tenet#55]
LOG: https://logs.minelure.com/pluginissues.txt

No idea what is causing this issue.

Modpack: Project OZone 3

Plugins:
Essentials
RankGrantPlus
GroupManager
Trading

**Comment by Osprey4444** [comment]
https://logs.minelure.com/o2uRxd5kng

**Comment by Mgazul** [comment]
Remove FastWorkbench, or use https://github.com/Luohuayu/FastWorkbench
