### ISSUE TITLE
Please add support for WorldEdit and mods

### ISSUE THREAD

**Issue by GizzaGander** [Teneted/Tenet#551]
WorldEdit does not work with items from mods, the kernel does not support this

**Comment by Shawiizz** [comment]
Hello, please follow the template for the issues and you can download Mohist's fix for WorldEdit [here](https://github.com/Mohist-Community/WorldEdit/releases/download/0.2.1/WorldEdit-6.1.9-0.2.1-SNAPSHOT-all.jar)

**Comment by Shawiizz** [comment]
You also have the choice to use WorldEdit forge.
