### ISSUE TITLE
CC:Tweaked text on the screen not updating

### ISSUE THREAD

**Issue by xemnes** [Teneted/Tenet#552]
**Describe the bug**
when opening a cc:tweaked computer, the screen is blank, if i close and reopen it, the text updates. the text only updates when i exit and reopen the screen. works fine single player. this only happens after long server uptime, restarting the server seems to fix it for a while but then it breaks again.

**To Reproduce**
place a computer down
right click on it, screen will be blank
exit then right click on it, text will be shown
try to type anything, nothing happens
exit then right click on it again, the text typed will be shown.

**Expected behavior**
text should update as text is rendered.

**Screenshots**
https://gfycat.com/agitatedgreatcrab

**Info (please complete the following information):**
- Mod/Plugins Name: cc:tweaked
 - Mod/Plugins  Version: 1.89.2

**Comment by Rabbit0w0** [comment]
try it on another server, and tell us does it work

**Comment by xemnes** [comment]
forgot to close this, the issue is very intermitent and hard to reproduce, happens only sometimes and a restart of the server fixes it.
