### ISSUE TITLE
crash when opening a strongbox from thermal expansion

### ISSUE THREAD

**Issue by xemnes** [Teneted/Tenet#553]
**Describe the bug**
i opened a strongbox and the server crashed. 
crash report: https://pastebin.com/L6U8P0DV
extra info from console: https://pastebin.com/Q69VBvki

**To Reproduce**
place a strongbox
open it

**Expected behavior**
the strongbox shouldnt crash the server when you open it

**Info (please complete the following information):**
- Mod/Plugins Name: Thermal Expansion
 - Mod/Plugins  Version: 1.12.2-5.5.7.1

**Comment by Rabbit0w0** [comment]
tell the mod's author first

**Comment by xemnes** [comment]
ok will do that
