### ISSUE TITLE
BLOCK TYPE

### ISSUE THREAD

**Issue by 4Seasons11** [Teneted/Tenet#555]
**Describe the bug**

I try to see block type 

it says X368(id of item)

[13:19:38 INFO]: CraftBlock{chunk=CraftChunk{x=2z=41},x=34,y=51,z=668,type=X368,data=7}

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name:
 - Mod/Plugins  Version: 

**Additional context**

**Comment by Mgazul** [comment]
what?

**Comment by 4Seasons11** [comment]
> what?
I try to load the mod item's block type
The bukkit missed their specific block type name.

Like This,
[13:19:38 INFO]: CraftBlock{chunk=CraftChunk{x=2z=41},x=34,y=51,z=668,type=X368,data=7}

but normally it has to be load like this
[Server thread/INFO]: CraftBlock{chunk=CraftChunk{x=-6z=15},x=-88,y=64,z=251,type=SAKURA_CABBAGECROP,data=0}

**Comment by EverNife** [comment]
Fixed at https://github.com/Mohist-Community/Mohist/issues/560 https://github.com/Mohist-Community/Mohist/commit/8f643889594a368b0443963793a277c5ee06923e

**Comment by Shawiizz** [comment]
Hi @4Seasons11, is this issue fixed for you ?

**Comment by 4Seasons11** [comment]
> Hi @4Seasons11, is this issue fixed for you ?

Yes I think so
