### ISSUE TITLE
Missing space in translation file

### ISSUE THREAD

**Issue by VerxoLP** [Teneted/Tenet#556]
**Describe the bug**
On server console appears message with missing space between usermane and "issued server command:" after executing command. It's caused by missing spaces in server.command.issued_command from translation file message_en_US.properties. In the other translation files it also occurs.

**To Reproduce**
1. Run server and connect
2. Execute any command
3. Go to console
4. Message in console should contain two more spaces before and after: server.command.issued_command

**Screenshots**
![console](https://user-images.githubusercontent.com/28629594/93593395-5264f900-f9b4-11ea-8c4c-0196746ebe82.PNG)

**Comment by VerxoLP** [comment]
Still an issue. 

Before  this commit (<a data-hovercard-type="commit" data-hovercard-url="/Mohist-Community/Mohist/commit/de72b861972b7643b47e624f320647060efa1238/hovercard" href="/Mohist-Community/Mohist/commit/de72b861972b7643b47e624f320647060efa1238">de72b86</a>): 

![](https://cdn.discordapp.com/attachments/746021385775612014/756858291321307146/console.PNG)

After this commit:

![](https://cdn.discordapp.com/attachments/746021385775612014/756858323315326976/console1.PNG)

In this commit was added only space between this message and typed command but not between username and this translation.

It should look like this: `iKEVAREZ issued server command: /help`

**Comment by Shawiizz** [comment]
It just need to add a space before issued. Not a difficult thing xD

**Comment by VerxoLP** [comment]
> It just need to add a space before issued. Not a difficult thing xD

I know but if I edit this in jar file this will be messed up after next update XD
