### ISSUE TITLE
A couple of Spigot plugins that don't work with Mohist.

### ISSUE THREAD

**Issue by IITFA** [Teneted/Tenet#558]
I have noticed two plugins that do not seem to work with Mohist.

Infernal Mobs: https://www.spigotmc.org/resources/infernal-mobs.2156/
Enchantment Solution: https://www.spigotmc.org/resources/enchantment-solution.59556/

Infernal mobs supposedly supports 1.12 but Enchantment Solution I'm not sure. I'm going to guess Enchantment Solution doesn't support 1.12.

https://pastebin.com/raw/msZMtcAC
I couldn't find the logs for infernal mobs but I remember it loaded and at the time of testing I didn't notice anything odd, but no infernal mobs would spawn and there was no sign inside the game that the plugin even loaded. I was using version 5.4.

**Comment by Shawiizz** [comment]
Enchantements Solution is not for 1.12.2, so it will not work correctly. And for internal mobs, what isn't working exactly ?

**Comment by IITFA** [comment]
If I remember right, the logs showed that it loaded and I saw no errors, but in-game, there were no infernal mobs and no sign that it loaded. I searched around a good half hour flying around and into caves and not a single infernal mob.

**Comment by Irgendwer01** [comment]
@IITFA try to ask on Fabiozumbi12's Discord: https://discord.gg/VHTwk53 since he is supporting Mohist for his plugins
