### ISSUE TITLE
[1.12.2] AdvancedBan

### ISSUE THREAD

**Issue by UrsusDeningeri** [Teneted/Tenet#559]
After updating Mohist to the latest version, the AdvancedBan plugin does not work and you cannot then connect to the server. Now I'm forced to stay on the older version where AdvancedBan works

AdvancedBan 2.1.9

[latest.log](https://github.com/Mohist-Community/Mohist/files/5250474/latest.log)
[AdvancedBan.log.log](https://github.com/Mohist-Community/Mohist/files/5250475/AdvancedBan.log.log)

**Comment by Rabbit0w0** [comment]
just change the time zone ;D
