### ISSUE TITLE
Why have you changed the BukkitMaterial name from modded items?

### ISSUE THREAD

**Issue by EverNife** [Teneted/Tenet#560]
**Question**

Since allways the Bukkit Material's names from FORGE items are their MODID_ITEMNAME.

Why have you changed that?

Why MOD_MATERIAL names are their ID not their usually identifier?

![image](https://user-images.githubusercontent.com/11357801/93691034-013d2e00-fab6-11ea-91f7-6f561950860e.png)

Was this meanted to fix a issue?

(Seems to be here the change https://github.com/Mohist-Community/Mohist/commit/f33298820e4b778b33438c814d16e1e7a9c46ffd#diff-e64bded7b970d0ae77382436b844e218L56 )

This change make it impossivel to create configs for multiple servers.

**Comment by Mgazul** [comment]
8f643889

**Comment by EverNife** [comment]
If i may suggest, i would say to keep ITEMS as the original one (MODID_ITEMNAME) and change only the Block ones with the prefix.

**Comment by Mgazul** [comment]
This will cause an error, the item and block registered by modds will use the same name

**Comment by EverNife** [comment]
Item: CUSTOMNPCS_NPCMAILBOX
Block: BLOCK_CUSTOMNPCS_NPCMAILBOX

This way will cause ?

**Comment by Mgazul** [comment]
ITEM：IC2_SPARING   (4023)
BLOCK: IC2_SPARING  (236)

**Comment by EverNife** [comment]
ITEM：IC2_SPARING (4023)
BLOCK: BLOCK_IC2_SPARING (236)

Keep the prefix BLOCK on blocks only.
And no prefix at ITEMS.

**Comment by Mgazul** [comment]
ok

**Comment by EverNife** [comment]
Thankyou :D
