### ISSUE TITLE
Having a different MATERIAL for Blocks and Items causes problems as well.

### ISSUE THREAD

**Issue by EverNife** [Teneted/Tenet#561]
**The problem**
I was doing some tests here, having a different material for Blocks and Items may cause some problems as well.

For example, plugins that ban items will not be able to ban a block from an item.

>    Example:
>    -  A player uses '/banitem add Hand' holding a Forge ItemBlock like 'IC2_SPARING'
>      When using this command the player will ban its HandItem! ('IC2_SPARING')
> 
>       But the Block from 'IC2_SPARING', the 'BLOCK_IC2_SPARING'  will remaing unbanned.

Another example,

A plugin that mines around the player, like some McMMO magic that take a hole tree down, the plugin will not know what is the ItemStack from the Tree's Block.

To be more clear, if you create a listener like this:

```
    @EventHandler()
    public void onBlockBreak(BlockBreakEvent event) {
        if (event.getPlayer().isSneaking()){
            event.setCancelled(true);
            Material block_material = event.getBlock().getType();

            event.getPlayer().sendRawMessage("YOu broke: " + event.getBlock().getType());

            ItemStack block_item = new ItemStack(block_material, 1);
            //block_item.setDurability(event.getBlock().getData());
            event.getPlayer().getInventory().addItem(block_item);
        }
    }
```

This will work with VanillaBlocks but not with Forge Blocks.

(Video https://www.youtube.com/watch?v=j_6kuHKgyps)

**Possible Solution**

The solution i tested and seems to be working:
	- Use a single MATERIAL for both Blocks and BlockItems, but store both ids on the Material.
	- In the creation of the CraftItemStack uses material.getItemID();
	- In the creation of the CraftBlock uses material.getBlockID();

**My commit with the possible fix is here** https://github.com/evernife/Mohist/commit/36415face1264ab2f744cc217fe767b06b20cf50

I will open a pullrequest after some tests on my server (30+players, probably will found out fast if something breaks up)

**Comment by Mgazul** [comment]
This will also cause problems：the same value exists in Enum

**Comment by Mgazul** [comment]
Well,  can you send pr?
