### ISSUE TITLE
This worked on my local machine then when uploading to hosted server it throws this error any ideas?

### ISSUE THREAD

**Issue by Lunatic-Gamer** [Teneted/Tenet#566]
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
:/home/container$ java -Xms128M -Xmx8000M -jar server.jar
__ __ ______ __ __ __ ______ ______
/\ "-./ \ /\ __ \ /\ \_\ \ /\ \ /\ ___\ /\__ _\
\ \ \-./\ \\ \ \/\ \\ \ __ \\ \ \\ \___ \\/_/\ \/
\ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\ \ \_\
\/_/ \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/ \/_/
-- Mohist Development Group
Start running libraries checker
Exception in thread "main" java.lang.NullPointerException
at com.mohistmc.network.download.DownloadLibraries.run(DownloadLibraries.java:34)
at com.mohistmc.MohistMC.main(MohistMC.java:44)

**Comment by Mgazul** [comment]
use old Mohist

**Comment by Lunatic-Gamer** [comment]
Thanks for the speedy reply have you got a link to the latest stable version that you think will work then? 👍

**Comment by Lunatic-Gamer** [comment]
This is version 1.12.2 @Mgazul

**Comment by Shawiizz** [comment]
Hey, please use build 41. I tested and bug is fixed. Have a nice day ! 👍

**Comment by Breadabix** [comment]
Thanks for the quick responses, ive let Lunatic know that build 41 is the build to use whenever he can get on pc.

**Comment by xemnes** [comment]
build 41 causes my game to error during initialization https://pastebin.com/rLHM9jzh

**Comment by Shawiizz** [comment]
What @xemnes ?

**Comment by xemnes** [comment]
dont worry, my issue was resolved somehow by deleting the libraries folder
