### ISSUE TITLE
Void island control not detecting that world Type is void island 

### ISSUE THREAD

**Issue by Irgendwer01** [Teneted/Tenet#567]
**Describe the bug**
Void island control is not detecting that world type ist void island
**To Reproduce**
1. Import a void island world into mohist
2. do /island create
3. it says that world type isnt void island
**Expected behavior**
running without bugs
**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: void island control 
 - Mod/Plugins  Version: 1.5.3

**Additional context**
Modpack is awakening Sky of diamonds 1.18.0

**Comment by Eden-Mor** [comment]
Im not a dev or something but do check that your 
server.properties has 
level-type=voidworld

**Comment by Irgendwer01** [comment]
@Xenooooon yes its already
