### ISSUE TITLE
Skinsrestorer and Biomes O' Plenty

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#568]
**Describe the bug**
When using SkinsRestorer together with Biomes O' Plenty, the skin does not appear to the player.

**To Reproduce**
1. Install SkinsRestorer
2. Install Biomes O' Plenty
3. Set Biomes O' Plenty as the default generator.
4. See error.

**Expected behavior**
Show player skin.

**Screenshots**
https://www.dropbox.com/s/jehay507k84i9u8/2020-09-23%2023-39-16_Trim.mp4?dl=0
Obs: Skip 03:40 to 06:40 and 08:20 to 11:13.

https://imgur.com/iPBV3Kx

**Info (please complete the following information):**
- Mod/Plugins Name: SkinsRestorer - Biomes O' Plenty
- Mod/Plugins Version: 13.8.4 - 7.0.1.2444.

**Additional context**
Other players can see the skin, but he cannot see it.

**Comment by Rabbit0w0** [comment]
do u have a Bungee or else proxy? pls install skinrestorer on the proxy

**Comment by jpedrocguimaraes** [comment]
> do u have a Bungee or else proxy? pls install skinrestorer on the proxy
no i don't have

**Comment by ghost** [comment]
> do u have a Bungee or else proxy? pls install skinrestorer on the proxy

no i don't have

**Comment by Plasman888** [comment]
> do u have a Bungee or else proxy? pls install skinrestorer on the proxy

what do you mean on proxy?

**Comment by Irgendwer01** [comment]
@jpedrocguimaraes do u have it tried with an world generated with the vanilla generator?
