### ISSUE TITLE
Bukkit plugins  not getting output of forge commands

### ISSUE THREAD

**Issue by Irgendwer01** [Teneted/Tenet#573]
**Describe the bug**
Bukkit plugins not getting output of Forge commands back when executing them

**To Reproduce**
1. execute an forge command with bukkit plugin
2. see problem

**Expected behavior**
Output of command is viewable by plugin

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: Polychatbukkit 
 - Mod/Plugins  Version: 1.2.1

**Additional context**
Same issue is on Thermos with all plugins

**Comment by Irgendwer01** [comment]
link to plugin: https://github.com/ModdedMinecraftClub/polychat-client-bukkit

**Comment by Rabbit0w0** [comment]
actually forge's priority is higher than bukkit so it does
leave ur mohist version and describe the steps more clearly
