### ISSUE TITLE
Server stop responding, related to nearly all terrain generation mod

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#575]
**Describe the bug**
When players randomly exploring the server map, the server stop responding suddenly.
No crash, neither hrr_pid_xxxx.log.
Before I found that __*almost every terrain generation mod*__ in my modpack is mentioned in the Watchdog report,
I have not consider this issue is related to the Mohist server platform itself.
However, I think this may be a server platform's issue.

**Expected behavior**
Server should not stop responding when players exploring.

**Info (please complete the following information):**
Mod Name: 
- [Traverse-1.12.2-1.6.0-69](https://www.curseforge.com/minecraft/mc-mods/traverse-legacy-continued/files/2613657) 
- [CoralReef-2.5-1.12.2](https://www.curseforge.com/minecraft/mc-mods/coralreef/files/2560552)
- [MysticalWorld-1.12.2-1.9.2](https://www.curseforge.com/minecraft/mc-mods/mystical-world/files/3054945)
- [Phosphor-forge-mc1.12.2-0.2.7-universal](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge/files/2919497)

Because of my fault, there are many other mod's corresponding watchdog logs are missing.
I will collect them and post them here later.

**Additional context**
Part of server console log:

No mod related, just Mohist itself: 
1. https://paste.ubuntu.com/p/fKnhbR4Qm7/
2. https://paste.ubuntu.com/p/5s97Gwv6j4/

Traverse: https://paste.ubuntu.com/p/jN9ZdRx4WY/
CoralReef: https://paste.ubuntu.com/p/29SqVTJFXP/
MysticalWorld: https://paste.ubuntu.com/p/VDgZyybhNb/
Phosphor: https://paste.ubuntu.com/p/89P3QzY8fY/

If more log info is needed, I will provide you as soon as possible.

Thanks in advance!

**Comment by Rabbit0w0** [comment]
this seems werid, ill check this soon, do not explore the badlands while we are fixing it

**Comment by TansuoTro** [comment]
这就雷普

**Comment by TansuoTro** [comment]
建议dump发出来

**Comment by RisingInIris2017** [comment]
> 建议dump发出来

我使用 MohistWatchdog 获取的 dump 信息如下。

Watchdog 提到了一个模组：
https://paste.ubuntu.com/p/fsmZQJWSvS/ 

Watchdog 没有提到模组：
https://paste.ubuntu.com/p/swJN2zgSsx/

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug persist, please open new issue.
