### ISSUE TITLE
Server stop when I use World Edit with chunk loader

### ISSUE THREAD

**Issue by 4Seasons11** [Teneted/Tenet#580]
**Describe the bug**

I use chunk loader mods,

Try to use World Edit  with FAWE

Server stop

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- Mod/Plugins Name: ChickenChunks, CodeChinkenLib, WeirdingGadget
 - Mod/Plugins  Version: 1.12.2

**Additional context**

**Comment by Rabbit0w0** [comment]
u can download a special WE for Mohist on the official site of mohist

**Comment by 4Seasons11** [comment]
> u can download a special WE for Mohist on the official site of mohist

Yes I'm using that.

Mohist 60~64 bukkit occurs these probelms

**Comment by Rabbit0w0** [comment]
give me the dump and the last stack trace report

**Comment by Rabbit0w0** [comment]
use MohistWatchdog but not SpigotWatchdog, switch it in mohist.yml, then reproduce the problem and generate the details

**Comment by 4Seasons11** [comment]
> use MohistWatchdog but not SpigotWatchdog, switch it in mohist.yml, then reproduce the problem and generate the details

same problem, and I'm not using anyWatchdog.

**Comment by Mgazul** [comment]
#651
