### ISSUE TITLE
Rip off of magma

### ISSUE THREAD

**Issue by SizzlinSeal01** [Teneted/Tenet#581]
Why are u stealing code from magma

**Comment by SSKirillSS** [comment]
What do you mean under "stealing"? Can you provide a part, that Mohist-Devs "stealed" from Magma?

Just based on my experience with Magma and Mohist:
Mohist better in mod compatibility than Magma. Magma more complicated in work with plugins (also a bit more optimized), but Magma works very bad with mods sometimes. So, I can't say that Mohist just copy magma code, cuz this server-cores works different.

**Comment by ghost** [comment]
Nothing is created, everything is copied kekw

**Comment by Shawiizz** [comment]
Mohist is not stealing any Magma code, or please provide proofs. Please don't open an issue for nothing. If you don't give any proof, i will lock this issue.

**Comment by Irgendwer01** [comment]
@jpredrocguimaraes @SizzlinSeal dont open an issue without an proper reason and u guys dont even have any proofs for it

**Comment by ghost** [comment]
> @jpredrocguimaraes @SizzlinSeal dont open an issue without an proper reason and u guys dont even have any proofs for it

but I didn't open anything, I just answered the op ironically, lol

**Comment by Mgazul** [comment]
Look at the recent Magma submission? Happy taking it from Mohist? I deliberately modified a few places (he works normally), haven't you found out
