### ISSUE TITLE
Credits out of date/ incomplete

### ISSUE THREAD

**Issue by TheUserCreated** [Teneted/Tenet#586]
**Describe the bug**
README.MD lists projects code is taken from as a form of credits, some projects are not listed which mohist borrows quite a bit of code from.
**To Reproduce**
1. Go to https://github.com/Mohist-Community/Mohist
2. Scroll down to 'special thanks'
4. Magma Foundation is not credited for the rather large portion of the code that has been taken from them, see issue here for a list of taken code https://github.com/Mohist-Community/Mohist/issues/505

**Expected behavior**
All projects which Mohist is a fork of are credited

Lack of credit in this fashion is not only immoral, but is also a violation of GPL and could cause serious legal issues if its not taken care of.

**Comment by DaFray31** [comment]
+1

**Comment by TheDevMinerTV** [comment]
+1
