### ISSUE TITLE
Credits out of date/ incomplete

### ISSUE THREAD

**Issue by TheDevMinerTV** [Teneted/Tenet#587]
**Describe the bug**
README.MD lists projects code is taken from as a form of credits, some projects are not listed which mohist borrows quite a bit of code from.
To Reproduce

Go to https://github.com/Mohist-Community/Mohist
Scroll down to 'special thanks'
Magma Foundation is not credited for the rather large portion of the code that has been taken from them, see issue here for a list of taken code #505

**Expected behavior**
All projects which Mohist is a fork of are credited

Lack of credit in this fashion is not only immoral, but is also a violation of GPL and could cause serious legal issues if its not taken care of.

**Comment by TheDevMinerTV** [comment]
you know that you're stealing code, so admit it.

**Comment by Mgazul** [comment]
I've sent DMCA to magma-1.12.2 and magma-1.15.2, and they've stolen more code from Mohist, saying it's licensed through catserver

**Comment by TheDevMinerTV** [comment]
then both of you should add the credits of each others projects...

**Comment by Mgazul** [comment]
The #505 you said above comes from the 1.15.2 branch that has been removed

**Comment by TheDevMinerTV** [comment]
I can diff the current code against Magma's and find obvious copy pasta. If you really want that, then tell me
