### ISSUE TITLE
Simply Jetpacks 2 startup problem.

### ISSUE THREAD

**Issue by tiagoadp** [Teneted/Tenet#592]
I got the same problem like an year ago, using mohist build 69... Using Omnifactory 1.2.2 CE.

https://paste.ee/p/DUp5H

Same as the issue #40 like one year ago, tryed the versions but not worked... Tryed to update those mods and same problem...

Any help appreciated. Tnx

**Comment by Irgendwer01** [comment]
@tiagoadp i have the same problem, its an issue in LibrarianLib's ASM and can only be changed by modifying its source code and the developer wont fix it see https://github.com/TeamWizardry/LibrarianLib/issues/157 for details.

**Comment by ghost** [comment]
Is it ASM or Mixin Crashing?

**Comment by ghost** [comment]
This Paste.ee really sucks. Like wtf

**Comment by tiagoadp** [comment]
Dunno, using mohist he modpack never starts... its giving those erros on the crash log...

**Comment by Irgendwer01** [comment]
@tiagoadp @0Hrl3qu1n0 temporarily fix: add behind -jar -noverify argument in ur startup script

**Comment by tiagoadp** [comment]
@Irgendwer01 yep, it worked... tnx nice! <3

But i dunnot if it will be bad at some point...

**Comment by EnterFor** [comment]
@tiagoadp Will this cause problems with other mods?

**Comment by tiagoadp** [comment]
> @tiagoadp Will this cause problems with other mods?

Not at all... Nearly completed it...
