### ISSUE TITLE
Server crashes in SERVER_STOPPING

### ISSUE THREAD

**Issue by argseby** [Teneted/Tenet#598]
**Describe the bug**
The server crashes every time at a random event. 
Server tries so save-all, I don't know if this is fault.

**To Reproduce**
Just play the game and the server crashes at a random time. 
- Mod/Plugins Name: Used with Roguelike Adventures
I added BspkrsCore and TreeCapitatorMod by myself.

This is the latest log:

[latest.log](https://github.com/Mohist-Community/Mohist/files/5425247/latest.log)

**Comment by ghost** [comment]
You used a lot more mods that that. And it seems to be RandomPatches that's causing the Crash: "om.therandomlabs.randompatches.patch.packetsize.NettyCompressionDecoderPatch.apply(NettyCompressionDecoderPatch.java:41) ~[NettyCompressionDecoderPatch.class:?]" Also this is something quite easy to find if you know what's what.

**Comment by argseby** [comment]
> You used a lot more mods that that. And it seems to be RandomPatches that's causing the Crash: "om.therandomlabs.randompatches.patch.packetsize.NettyCompressionDecoderPatch.apply(NettyCompressionDecoderPatch.java:41) ~[NettyCompressionDecoderPatch.class:?]" Also this is something quite easy to find if you know what's what.

Ye, Roguelike Adventures are like 100+ mods. BspkrsCore and TreeCapitatorMod are just added by myself. Unfortunately i have no idea what random patches are.

**Comment by ghost** [comment]
Random Patches is a mod that patches the game in multiple ways. It doesn't really affect performance and shouldn't affect anything if removed on server. And also i thought it said Rougelike Dungeons and not Adventures. Terribly Sorry

**Comment by argseby** [comment]
Is this something easy to remove ? Or do i have to recode the mods. (which im not capable of lol)

**Comment by ghost** [comment]
You should be able to find it in your server's mods folder. Just delete it. And i'm sure the server will boot up without any crashes. If anything else happens. Let me know here.

**Comment by argseby** [comment]
How can I identify the plugin that is causing the trouble ?

**Comment by ghost** [comment]
It should either tell you in the log or just in the console itself. But there is no pluin causing this crash however.

**Comment by ghost** [comment]
plugin*

**Comment by argseby** [comment]
Would it look like this: 
```
[21:25:24] [Server thread/INFO] [THAUMCRAFT]: Creating aura cache for world 687
[21:25:24] [Server thread/INFO] [twilightforest]: Loaded a world with the tfEnforcedProgression game rule not defined. Defining it.
[21:25:24] [Server thread/INFO] [dsurround]: Creating NULL weather generator for dimension [dungeon_pockets]
[21:25:25] [Server thread/INFO] [OTG]: Saving structure data
[21:25:25] [Server thread/INFO] [OTG]: Saving structures and pre-generator data
[21:25:25] [Server thread/INFO] [OTG]: Saving done
[21:25:25] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception 
```

?

**Comment by argseby** [comment]
Twilight forest ?

**Comment by ghost** [comment]
That shows no information. Although i recommend removing Dynamic Surroundings from the mods folder as it spams the console useless information.

**Comment by argseby** [comment]
I have no idea what i'm looking for. There are some nullpointer exceptions, but they don't seem to impact.

**Comment by argseby** [comment]
```
[21:25:25] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
[21:25:25] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: D:\Minecraft-Server\.\crash-reports\crash-2020-10-22_21.25.25-server.txt

```
This is literally the exception thrown.

**Comment by ghost** [comment]
Send the Crashlog (D:\Minecraft-Server\.\crash-reports\crash-2020-10-22_21.25.25.txt)

**Comment by argseby** [comment]
I already did. called latest.log

**Comment by ghost** [comment]
No send the log from the path i just sent

**Comment by ghost** [comment]
it's called crash-2020-10-22_21.25.25.txt

**Comment by ghost** [comment]
D:\Minecraft-Server.\crash-reports\
it's in this path

**Comment by argseby** [comment]
[crash-2020-10-22_21.25.25-server.txt](https://github.com/Mohist-Community/Mohist/files/5425411/crash-2020-10-22_21.25.25-server.txt)

**Comment by ghost** [comment]
Did you remove Random Patches?

**Comment by ghost** [comment]
from the server?

**Comment by argseby** [comment]
Wait... so there is a mod called randompatches. okay

**Comment by ghost** [comment]
You didn't remove it even though i told you to remove it...

**Comment by argseby** [comment]
Well I overread it. My bad

**Comment by argseby** [comment]
Thaaanks. That worked.
