### ISSUE TITLE
Skript incompatibility

### ISSUE THREAD

**Issue by wanou067** [Teneted/Tenet#599]
**Describe the bug**
https://pastebin.com/54rDUYrB

**To Reproduce**
1. Install Skript 2.5 on mohist (in plugins folder)

**Info (please complete the following information):**
- Skript: https://github.com/SkriptLang/Skript/releases/download/2.5/Skript.jar
 - Mohist: https://ci.codemc.io/job/Mohist-Community/job/debug/ (Build 47)

**Additional context**
I am using a clean install of mohist, no others plugins/mods are installed on the server

**Comment by Mgazul** [comment]
https://github.com/Mohist-Community/Mohist/issues/331

**Comment by evanlegamer** [comment]
This is not a duplicate since the version of mohist is 1.16.3 here and not 1.12.2 as #331

**Comment by Shawiizz** [comment]
Skript 2.5 is working fine on Mohist 1.12.2, but not on Mohist 1.16.3.
