### ISSUE TITLE
Bungeecord option -- 1.16.3

### ISSUE THREAD

**Issue by imagreez** [Teneted/Tenet#603]
**Describe the bug**
You get that error on console when you try to connect via bungeecord:
```sh
/127.0.0.1:53531 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
```
**To Reproduce**
1. Start a server with bungeecord option enabled and a bungeecord with IPForwarding
2. Try to connect

**Info (please complete the following information):**
- Mod/Plugins Name: No
 - Mod/Plugins  Version: No
 - Last commit of magma

**Comment by Mgazul** [comment]
Fixed
