### ISSUE TITLE
Can't connect via Bungeecord to server -- 1.16.3

### ISSUE THREAD

**Issue by imagreez** [Teneted/Tenet#604]
**Describe the bug**
Connect via bungeecord to mohist, without IPForwarding

**To Reproduce**
1. Start a server and try to connect via bungeecord

**Info (please complete the following information):**
- Mod/Plugins Name: No
 - Mod/Plugins  Version:  No
- Last commit of mohist

**Comment by imagreez** [comment]
It works now??

**Comment by Mgazul** [comment]
Need Bungeecord to be compatible with FML2 protocol

**Comment by imagreez** [comment]
@Mgazul You know if waterfall is compatible with FML2 protocol? or a bungeecord 1.8 to 1.16 with that compatible (and the FML1 too) if it is possible

**Comment by Mgazul** [comment]
This requires Bungeecord to actively fix it or a branch to fix it. Mohist is based on forge and spigot, and has its own problems.

**Comment by Mgazul** [comment]
Fixed
