### ISSUE TITLE
[Plugin] Pixelmon Eco Bridge

### ISSUE THREAD

**Issue by brycepsd** [Teneted/Tenet#606]
Pretty much just need this plugin
https://pixelmonmod.com/wiki/Economy_Bridge
made from sponge to mohist.
Thank you and let me know!

**Comment by PierreBouffartigue** [comment]
Use this mod : https://www.curseforge.com/minecraft/mc-mods/grand-economy
It work with Pixelmon

**Comment by Mgazul** [comment]
This is unrelated to mohist
