### ISSUE TITLE
[1.16.3] CraftTweaker (crafttweaker) has failed to load correctly Bad type on operand stack

### ISSUE THREAD

**Issue by VaNnOrus** [Teneted/Tenet#610]
Hello.
Forge mod CraftTweaker-1.16.3-7.0.0.48 has failed to load on forge client, installing from mohist installer (mohist-1.16.3-34.1.34-installer). 
At the same time that mod loads correctly on client installing from forge 34.1.34 installer.
Logs: https://pastebin.com/sUTxs6kF

**Comment by ghost** [comment]
Mohist has no client only server. The client from the installer will never work. As mohist is server software. Not client software.
