### ISSUE TITLE
1.16.3 Not compatible generators

### ISSUE THREAD

**Issue by Edel-Lilies** [Teneted/Tenet#613]
Version : 1.16.3-34.1.25
Mods: Oh The Biomes You'll Go 1.1.1 ,YUNG's Better Mineshafts 1.0.1 and Better Cave 1.0.4 
Time: Create World

Other: Crash,I don't know the cause
[crash-2020-11-04_07.06.13-server.txt](https://github.com/Mohist-Community/Mohist/files/5484346/crash-2020-11-04_07.06.13-server.txt)

**Comment by Mgazul** [comment]
Sorry for the late reply: please first determine if it is caused by a mod

**Comment by Mgazul** [comment]
Forge has abandoned 1.16.3, and mohist will follow it
