### ISSUE TITLE
code d'erreur console lors de la création de mes fichiers

### ISSUE THREAD

**Issue by azenlp** [Teneted/Tenet#614]
lorsque j'éssaye d'installer Mohist via mon herbergeur en FTP les fichier se crée et à chaque fois cette ligne d'erreur apparait : > [23:43:35 WARN]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with com.mohistmc.forge.BukkitPermissionsHandler

si quelqu'un pouvait m'aider ça serait simpa.

**Comment by Mgazul** [comment]
mohist.yml -> "mohist.BukkitPermissionsHandler“ setting to false
