### ISSUE TITLE
problème d'enregistrement d'un fichier

### ISSUE THREAD

**Issue by azenlp** [Teneted/Tenet#615]
lors que je vais dans le mohist.yml -> "mohist.BukkitPermissionsHandler" et que je le défini sur false à chaque lancement de mon server il se remet en "true"

**Comment by Mgazul** [comment]
Si vous utilisez la dernière version de Mohist

**Comment by Shawiizz** [comment]
Salut, déjà évite d'ouvrir plusieurs issues et utilises la dernière version de Mohist si ce n'est pas le cas. Tu peux la télécharger ici https://mohistmc.com/download 
Pourrais tu expliquer ton problème car c'est pas très compréhensible.
