### ISSUE TITLE
Ignoring damage custom ender teleport damage

### ISSUE THREAD

**Issue by Serega007RU** [Teneted/Tenet#619]
In the Reskillable mod, there is a Safe Port skill, it should remove damage from teleportation with Ender Pearl. This doesn't work on mohist, and the damage will be applied as usual. I think this problem can be solved like this: #618 
![image](https://user-images.githubusercontent.com/64780091/98460891-38c47e80-21b9-11eb-9f8d-464d7b5ab0c5.png)

**Comment by Mgazul** [comment]
executed
