### ISSUE TITLE
Mohist having issues with CMI, tried on fresh paperspigot install, didn't have this error.

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#62]
So, I reported the error to CMI but actually comes from Mohist having issues with CMI.

First, /version on CMI puts this error:
https://pastebin.com/raw/QvkuScQD

Secondly, when there is players, Mohist randomly has issues with CMI with player interaction.
https://pastebin.com/raw/rCk2AQye

Please look into this, thanks.

**Comment by MCUmbrella** [comment]
Are you using a modified version(for example, cracked no-verification edition) of CMI? If yes, use the newest offical version of CMI and try it again.
