### ISSUE TITLE
Populators of Plugins do not work

### ISSUE THREAD

**Issue by YellowPhoenix18** [Teneted/Tenet#625]
Hello,
a customer reported us, that there no trees when using RWG(RealisticWorldGenerator) on Mohist.
We verified the issue on our test-bench ourself.

Our trees are populated via Populators, so it seems, like they do not get populated properly.

**Comment by Mgazul** [comment]
Where can I download RealisticWorldGenerator

**Comment by Rabbit0w0** [comment]
> Hello,
> a customer reported us, that there no trees when using RWG(RealisticWorldGenerator) on Mohist.
> We verified the issue on our test-bench ourself.
> 
> Our trees are populated via Populators, so it seems, like they do not get populated properly.

hi there, i got a copy of rwg's source code, can i distribute it for only development?
this may fix this problem

**Comment by Mgazul** [comment]
It has been fixed!
