### ISSUE TITLE
[1.16.4] Mekanism not work

### ISSUE THREAD

**Issue by bigenergy** [Teneted/Tenet#626]
1. install mekanism
2 . join mohist server

![image](https://user-images.githubusercontent.com/17977139/99145653-a5d88800-2681-11eb-97a2-cb8e5bace1fe.png)
client error
[latest.log](https://github.com/Mohist-Community/Mohist/files/5540545/latest.log)

`[14 nov 2020 13:59:38.683] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Incomplete server tags, disconnecting. Missing: {mekanism:infuse_type=[mekanism:fungi, mekanism:diamond, mekanism:redstone, mekanism:gold, mekanism:tin, mekanism:refined_obsidian, mekanism:carbon, mekanism:bio], mekanism:gas=[mekanism:water_vapor, mekanism:fusion_fuel, mekanism:deuterium, mekanism:tritium]}`

mohist-1.16.4-35.0.17 latest

**Comment by bigenergy** [comment]
https://gist.github.com/bigenergy/351155e4de403aa1e62530abcf9c3488

**Comment by Mgazul** [comment]
Fixed
