### ISSUE TITLE
[1.12.2] Terrarium Server Crash

### ISSUE THREAD

**Issue by Ytoblo** [Teneted/Tenet#629]
[crash-2020-11-17_22.49.11-server.txt](https://github.com/Mohist-Community/Mohist/files/5555247/crash-2020-11-17_22.49.11-server.txt)
How to reproduce
1. Download terraium and cubic chunks
2. go to server.properties 
edit next:
level-type=terrarium.earth
and add to generator-settings (from client side. when u configuring world. u can copy arguments) arguments. for example mine -{"ravine_generation"\:true,"compatibility_mode"\:true,"add_strongholds"\:true,"spawn_latitude"\:27.98835,"spawn_longitude"\:86.923641,"ore_generation"\:true,"add_mineshafts"\:true,"add_flowers"\:true,"add_temples"\:true,"height_offset"\:63.0,"bop_integration"\:true,"add_woodland_mansions"\:true,"add_ocean_monuments"\:true,"terrestrial_height_scale"\:3.5000000000000004,"add_trees"\:true,"world_scale"\:125.00000000000006,"add_cacti"\:true,"add_grass"\:true,"add_gourds"\:true,"add_sugar_cane"\:true,"add_villages"\:true,"oceanic_height_scale"\:1.0000000000000004,"cave_generation"\:true}

3. Start ur server

**Comment by Mgazul** [comment]
Related to the village

**Comment by Mgazul** [comment]
This is not the final solution, But it works.

**Comment by Gegy** [comment]
This is an interesting issue- it seems for it to be accessing a null villageCollection, it must be trying to tick Terrarium's fake compatibility world implementation, which should really never be considered a true world. Is Mohist tracking all ServerWorld instances as they are constructed? This is something that Forge does, and Terrarium has some very hacky code to make sure it doesn't actually update the dimension array, but I imagine that may be what is breaking here?
