### ISSUE TITLE
[1.12.2] Mystcraft dimensions dont point to correct spawn

### ISSUE THREAD

**Issue by lazr58** [Teneted/Tenet#632]
Ive noticed that mystcraft doesnt spawn you on top of cobblestone(a "safe" platform) like it normally should in mohist. A pre-existing world shows that the platform does spawn, but the spawn location in the mystcraft dimension has changed.

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug is always here, please open new issue.
