### ISSUE TITLE
[1.12.2] Change paper to akarin

### ISSUE THREAD

**Issue by Ytoblo** [Teneted/Tenet#633]
for more STABLE optimization, I suggest using akarin upstream instead paper - https: //github.com/Akarin-project/Akarin/tree/ver/1.12.2

**Comment by Dum4G** [comment]
>Akarin is currently **under heavy development** 
>Akarin is a powerful (not yet) 
>Autobuild failed

Nice suggestion bro

**Comment by Mgazul** [comment]
Akarin's optimization processing is not suitable for forge
