### ISSUE TITLE
i cant launch  my server

### ISSUE THREAD

**Issue by epicyeeto** [Teneted/Tenet#635]
i try to open and it closes immediately 
it says it's in an incorrect state in my logs

log:
https://hasteb.in/ikibuwil.md

EDIT:
crash report says something about bukkit
https://hasteb.in/egikerol.rb

**Comment by Mgazul** [comment]
You installed multiple identical mods

**Comment by epicyeeto** [comment]
i now have a different problem

**Comment by sh1kxrv** [comment]
already have a problem?

**Comment by epicyeeto** [comment]
i am going to close this issue and make a new one
