### ISSUE TITLE
1.16.4 Clients with Forge 35.0.17 installed (From Mohist installer jar) failed to login (Build 110)

### ISSUE THREAD

**Issue by No3371** [Teneted/Tenet#636]
![圖片](https://user-images.githubusercontent.com/1814971/99865446-a8d4fa80-2be4-11eb-8f7b-4f152ad2a02b.png)

Official Forge 35.0.17 tested and login without issue.

**Comment by Shawiizz** [comment]
Don't use Mohist installer to install the client ! It will not work. 
Use the official [forge installer](http://files.minecraftforge.net/) to install the client side.

**Comment by ghost** [comment]
maybe delete client downloader from mohist installer?

**Comment by Shawiizz** [comment]
It will not be useful to do that, because in my next update the installer will not be needed to run Mohist
