### ISSUE TITLE
Authlib

### ISSUE THREAD

**Issue by GoldenLs** [Teneted/Tenet#638]
how to edit this file Authlib, so that it is not pumped out of the box. after each change of certain classes, the file is downloaded back

**Comment by ghost** [comment]
pls specify target minecraft version

**Comment by GoldenLs** [comment]
> пожалуйста, укажите целевую версию Minecraft

1.12.2

**Comment by Shawiizz** [comment]
Why do you want to do exactly ?

**Comment by GoldenLs** [comment]
I edit the yagdrasil class, put it in authlib, start the server. It takes and uploads a new file minecraft_server

**Comment by Shawiizz** [comment]
The auth lib thing is in the minecraft_server.1.12.2.jar file

**Comment by GoldenLs** [comment]
> Почему именно вы хотите?


I need to sync with the client

**Comment by GoldenLs** [comment]
> Функция auth lib находится в файле minecraft_server.1.12.2.jar



> Функция auth lib находится в файле minecraft_server.1.12.2.jar


Quite right

**Comment by protectedsnow** [comment]
go to libraries/net/minecraft/server/<gameversion>/
and edit server-<gameversion>-extra.jar

**Comment by Shawiizz** [comment]
The file is in .\libraries\net\minecraft\1.12.2\minecraft_server.1.12.2.jar and the authlib is in the package com.mojang.authlib. Then if you edited some classes in this file, remove the part of this file in mohist_libraries.json to make Mohist not download it

**Comment by GoldenLs** [comment]
> Файл находится в. \ Libraries \ net \ minecraft \ 1.12.2 \ minecraft_server.1.12.2.jar, а authlib находится в пакете com.mojang.authlib. Затем, если вы редактировали некоторые классы в этом файле, удалите часть этого файла в mohist_libraries.json, чтобы Mohist не загружал его

Here's what you need thanks

**Comment by GoldenLs** [comment]
> Файл находится в. \ Libraries \ net \ minecraft \ 1.12.2 \ minecraft_server.1.12.2.jar, а authlib находится в пакете com.mojang.authlib. Затем, если вы редактировали некоторые классы в этом файле, удалите часть этого файла в mohist_libraries.json, чтобы Mohist не загружал его

and more specifically, as in mohiste_libraries.json, disable part of the minecraft_server. I will remove the line with the desired file when running. pumps both minecraft_server and mohist_libraries.json
