### ISSUE TITLE
[1.16.3] Client-side incompatibility with Mekanism Generators

### ISSUE THREAD

**Issue by DakakiWolf** [Teneted/Tenet#641]
Loads fine using forge 34.1.42, gives provided error message when loading with mohist 1.16.3-34.1.42
![image](https://user-images.githubusercontent.com/74933908/100015226-3f4c1c00-2d9d-11eb-8ad8-bc0517940cb3.png)
Server has loaded mod successfully, appears to only be a client-side issue
Client Crash Log:
https://pastebin.com/hdeXuvpg

**Comment by Mgazul** [comment]
Forge has abandoned 1.16.3, and mohist will follow it
