### ISSUE TITLE
[1.16.4] CoreProtect doesn't track block events

### ISSUE THREAD

**Issue by Dum4G** [Teneted/Tenet#642]
Minecraft Version 1.16.4
Mohist 110
Win 10
No other mods and plugins installed

![2020-11-24_01 22 26](https://user-images.githubusercontent.com/5430116/100022085-a0064380-2df3-11eb-857e-bcf73bf489be.png)
![2020-11-24_01 22 39](https://user-images.githubusercontent.com/5430116/100022118-ac8a9c00-2df3-11eb-8da4-012be3f54f7f.png)

Description
No matter if I break/place/change shape of any block, it it's not logged by /co inspect command and rollback features are probably broken as well. Any other events like mobs behavior, door usage and picking up items are handled properly.

How to reproduce
Install CoreProtect
Chunk some wood
Place it somewhere
type /co inspect
click on those blocks

Expected behavior
Make use of [CoreProtect API](https://www.minerealm.com/community/viewtopic.php?f=32&t=16687) if any event interference was intended

**Comment by Mgazul** [comment]
Some things are not done yet, please be patient

**Comment by Dum4G** [comment]
UPD: I've got a proof that build #73 (latest 1.16.3) is handling events properly. Seems like we have a regression here

**Comment by ricosw** [comment]
Should now work since #723
Can you test it with the latest build please.

**Comment by Dum4G** [comment]
I will in my spare time. However, since this is a temporary solution I'd rather wait for a permanent one
