### ISSUE TITLE
Server crashes with new FTB University install

### ISSUE THREAD

**Issue by crossfirearena** [Teneted/Tenet#644]
**Describe the bug**
The server tries to start, goes through the process and crashes exactly 30 seconds after finish. This is from a fresh install. During those 30 seconds, the server is responsive and responds to commands, then it shuts down with the following error: https://pastebin.com/vMbH1jim Removing OTG allows for the server to boot and not crash, but the server cannot be connected to then.

**To Reproduce**
Start with a fresh FTB uni install, and run it with mohist, crashes every time. Also crashes with magma

**Info (please complete the following information):**
 - Minecraft Version: 1.12.2
 - Mohist Version:  102
 - OS: Linux - Ubuntu 18.04.3 LTS

**Comment by Mgazul** [comment]
Related to unloader mod

**Comment by crossfirearena** [comment]
Unloader was not the cause. The server stayed longer than 30 seconds, but crashed in the same way after this. Same error as well.

**Comment by crossfirearena** [comment]
Also this error is showing up now when I try to log in for the short time that the server is online: https://pastebin.com/6ebVa7sk

**Comment by Mgazul** [comment]
No longer compatible with LagGoggles

**Comment by crossfirearena** [comment]
I have laggoggles running on another mohist server with no issues at all from it.

**Comment by Mgazul** [comment]
https://github.com/Mohist-Community/Mohist/commit/fff56db9edd0017f4fb3cc240ab4f8020b6222d4

**Comment by crossfirearena** [comment]
Not well versed in this code, not sure what you are pointing to. I literally copied the jar (102) from the server working with laggoggles 5.8-132 to this server. So the one server working with laggoggles and not the other makes me think its another issue.

**Comment by crossfirearena** [comment]
Took laggoggles out, no difference at all. Has to be another mod still.

**Comment by crossfirearena** [comment]
https://drive.google.com/file/d/13cAM5En5huqvxD3Sim1cv91HyL9fkbsd/view?usp=sharing
This is the entire latest.log. Perhaps this will help with additional information.

**Comment by crossfirearena** [comment]
Instead of 30 seconds and crash, its exactly 5 mins now, every time

**Comment by crossfirearena** [comment]
Removing OTG, Biome Bundle, Bundle_BOP, and vanilla vistas stops the crashes, but doesnt allow players to join the server. Some headway regardless
