### ISSUE TITLE
JEI behaviour mismatch with Forge

### ISSUE THREAD

**Issue by No3371** [Teneted/Tenet#646]
It seems that Bukkit takes over /give command, which seems parse commands in different way, this leads to JEI incompatibility.

EX: When giving any equipments through JEI, the command will fail because the item id is followed with {Damage: 0}, and bukkit only expects [count].

This also means we can not add NBT to given items.

I've tried `minecraft:give` and it's no help.

**Comment by Mgazul** [comment]
Provide a list of plugins

**Comment by No3371** [comment]
None, It's a fresh Mohist install with only mods added.

**Comment by Mgazul** [comment]
I haven't modified /give, and the same is true for bukkit

**Comment by Irgendwer01** [comment]
@No3371 can u post here a list of mods u have installed?

**Comment by No3371** [comment]
This can be reproduced on Build 150 with only `jei-1.16.4-7.6.0.58` installed.
You only have to click any equipment item on JEI panel.
![圖片](https://user-images.githubusercontent.com/1814971/101656299-81ec4480-3a7d-11eb-97d8-84b949ec59f0.png)

On Forge server, the nbt will be accepted.

**Comment by No3371** [comment]
#### Test with typing `/give XXX minecraft:iron_sword {Damage:0} 1`

| Condition | Result |
| -- | -- |
| Vanilla Single Player | failed |
| Forge Single Player (+JEI) | failed |
| Vanilla Server + Vanilla Client | failed |
| Forge Server (+JEI)+ Forge Client | failed |
| Forge Server (+JEI) + Forge Client (+JEI) | failed |
| Forge Server + Forge Client (+JEI) | failed |

#### Test clicking JEI equipment item icon
| Condition | Result |
| -- | -- |
| Forge Server (+JEI) + Forge Client (+JEI) | **success** |
| Forge Server + Forge Client (+JEI) | failed |

So it seems like JEI has some protocol to handle spawning items from its GUI, but Mohist does not work with that.

**Comment by Sl0ter** [comment]
try it with "/give XXX minecraft:iron_sword{Damage:0} 1" there should no Space between iron_sword and {Damage:0} this should work?

**Comment by Sl0ter** [comment]
try it with this command "/give @p minecraft:iron_sword{Damage:0} 1"

**Comment by Mgazul** [comment]
1.16.4? I thought you were talking about 1.12.2 error

**Comment by No3371** [comment]
Yes, sorry I forgot to tag version in title of this issue.

**Comment by No3371** [comment]
It seems like JEI does use custom packet to give items. ([link](https://github.com/mezz/JustEnoughItems/blob/1.16/src/main/java/mezz/jei/network/PacketHandler.java))

It checks if JEI is present on server to decide which way to execute the give, if it's not, it fallback to /give commands (which appears not parse-able to Minecraft now). ([link](https://github.com/mezz/JustEnoughItems/blob/cbe18a83dbafc220ad90d3e80a2031311565cd09/src/main/java/mezz/jei/util/CommandUtil.java#L47))

How it decide if JEI is present on server is ... ([link](https://github.com/mezz/JustEnoughItems/blob/cbe18a83dbafc220ad90d3e80a2031311565cd09/src/main/java/mezz/jei/startup/NetworkHandler.java#L18))

So I guess the difference between VanillaForge and Mohist, is that clientside JEI can't find JEI in "NetworkRegistry" when connected to Mohist.
