### ISSUE TITLE
[1.7.10] OutOfMemoryError with FAWE and more plugins

### ISSUE THREAD

**Issue by bagomot** [Teneted/Tenet#65]
Hello! For a long time I tried to understand the causes of the error myself, but this is not in my power.

I use the latest version of Monist 1.7.10 (af2f6ad) and your version of the FAWE plugin, the plugin gives an error (I attached a latest.log file), the plugin partially to work, but I am concerned about the error.

I often saw this error with other plugins, for example, with the HolographicDisplays addons plugin.

I tried different versions of JRE and different launch options, adding and decreasing the amount of memory ...

Now I just dumped it, parsed it using MemoryAnalyzer and threw it to you (java_pid520.threads file).

Perhaps you can fix this error in the server core, or at least in your version of the FAWE plugin.

And yet, it is very unfortunate that the WE is not fully supported in 1.7.10 (does not return entity, etc.).

Sorry for my English.

latest.log: https://www.dropbox.com/s/umf9zifgba43z98/latest.log?dl=0
java_pid520.threads: https://www.dropbox.com/s/hho1h0yin4995xv/java_pid520.threads?dl=0

**Comment by Mgazul** [comment]
c07ab6f
