### ISSUE TITLE
[1.16.4] SmoothTimber 1.11.4 doesn't chop trees

### ISSUE THREAD

**Issue by Dum4G** [Teneted/Tenet#652]
Minecraft Version 1.16.4
Mohist 115
Win 10
No other mods and plugins installed

Description
Plugin doesn't do anything and doesn't suggest any commands, but surprisingly it doesn't show any warns and actually reacts to commands it has

How to reproduce
Install SmoothTimber
Type /sm toggle
See `woodchopper enabled` message
Chunk some wood

Expected behavior
https://ypict.de/img/upload/ZkE0mqqmYBmXDANN.gif

There's no logs to provide (no pun intended)

**Comment by Dum4G** [comment]
There's no logs to provide (no pun intended)

**Comment by Mgazul** [comment]
Same problem as #642
