### ISSUE TITLE
[1.16.4] Valhelsia 3 pre-7-3.1.0 - Minecolonies compatibility issues

### ISSUE THREAD

**Issue by maddiethegm** [Teneted/Tenet#654]
Debug log and modpack info attached.

I don't know what other information I can provide to help troubleshoot, and I don't expect a resolution quickly, but wanted the team aware of whatever issue caused this, and I'm hoping I can figure out the source of the issue because the Mohist server launches fine with the mods folder empty.

[Modpack Installed](https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files/3123980)
[Debug Log](https://pastebin.com/i4my5Zg4)

**Comment by Mgazul** [comment]
I am testing Modpack and have found multiple mods that are not available（Apotheosis, Waystones，minecolonies，....）

**Comment by Mgazul** [comment]
It has been determined that the minecolonies mod cannot be used

**Comment by Mgazul** [comment]
fixed
