### ISSUE TITLE
[Bug]&[Issue]for[1.12.2]Advancement Issues

### ISSUE THREAD

**Issue by Plasman888** [Teneted/Tenet#657]
**Describe the issue**
Advancements repeat as shown in the gif
also occurs on magma(probably a mod which i have yet to identify)
the advancements json file prevent the server from bein started again unless deleted

**To Reproduce**
1. Use (the mod)
2.Run the server and log in a player
3. Stop the server
4. Try to start again

**Expected behavior**
Just starts normally the subsequent times

 - Mohist version:mohist-1.12.2-121
 -OS: windows
![Minecraft-1122-2020-11-30-08-58](https://user-images.githubusercontent.com/71266194/100690432-75068b80-33c1-11eb-911b-b9e903d8bf31.gif)

**Comment by Plasman888** [comment]
#390

**Comment by Mgazul** [comment]
Check your mod list, it may be related to tombstone

**Comment by Plasman888** [comment]
Yes yes it was

**Comment by Plasman888** [comment]
nvm it wasnt

**Comment by Plasman888** [comment]
it was Mowzie's Mobs - 1.5.8
https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs/files

**Comment by Plasman888** [comment]
and tombstone

**Comment by Plasman888** [comment]
i tried toubleshooting a lot and i couldnt find a specific mod

**Comment by Plasman888** [comment]
i really need help

**Comment by Mgazul** [comment]
Tell me your mod list

**Comment by Mgazul** [comment]
mowziesmobs-1.5.8，gravestone-1.10.2  I only installed these two and your problem did not occur

**Comment by Plasman888** [comment]
yeah its fine illl try and trouble shoot to find out which mod it is first

**Comment by Plasman888** [comment]
i have like 200 mods so yeah

**Comment by Plasman888** [comment]
the latest mohist version fixed the issue, was never able to find the mod tho
