### ISSUE TITLE
Player cannot join the Server (LibrarianLib)

### ISSUE THREAD

**Issue by Jacky10X** [Teneted/Tenet#659]
Server Software version: Mohist 1.12.2
Server Error: https://pastebin.com/YKc87Xdi
(Sorry for the Chinese language because I am not using the English language and I don't know how to change the output to English)
Client Error: https://ibb.co/zxB6dsz

When the player joins the game, they cannot connect to the server and show the error but the server keeps running.
It is confirmed that LibrarianLib cause the issue
I also report the bug to them before: https://github.com/TeamWizardry/LibrarianLib/issues/129
Someone pointed out that it might cause by this (unsure):
https://github.com/TeamWizardry/LibrarianLib/blob/eb72a3d402054bb134bc47c0b59615e4ad76ef5d/src/main/java/com/teamwizardry/librarianlib/asm/LibLibTransformer.java#L276

**Comment by Mgazul** [comment]
Repeated question

**Comment by Mgazul** [comment]
#592 temporarily fix: add behind -jar -noverify argument in ur startup script
