### ISSUE TITLE
can not join sever

### ISSUE THREAD

**Issue by epicyeeto** [Teneted/Tenet#660]
i keep on joining my server and it keeps on saying
![image](https://user-images.githubusercontent.com/73504007/100812311-b3746880-340a-11eb-85f3-c35ae99842e2.png)

I have looked at command prompt and logs 

and said
https://hasteb.in/osazanij.css

I cant show you latest.log because it crashes hastebin and mclo .gs 

mohist: 1.12.2-106

forge: 1.12.2

**Comment by Mgazul** [comment]
Useless information

**Comment by epicyeeto** [comment]
https://hasteb.in/mebijocu.css latest log but wont share anything

**Comment by SekiAlpha** [comment]
@epicyeeto You most likely have something incorrectly configured. Have you tried running the server on your local computer?

**Comment by epicyeeto** [comment]
![Uploading image.png…]()
That is my server properties

**Comment by SekiAlpha** [comment]
> Uploading image.png…
> That is my server properties
@epicyeeto that link is just an image

**Comment by Shawiizz** [comment]
Can you give more informations please ?
Like list of mods and plugins and logs
