### ISSUE TITLE
[1.16.4] io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by Dum4G** [Teneted/Tenet#662]
### Minecraft Version 1.16.4
Mohist 128
Affected mod: MrCrayfishFurnitureMod 7.0.0 pre19
No other mods installed
Doesn't happen on Forge vanilla server

### Description
Crates from CFM are playing it's animation but instead of seeing inventory we're seeing console spam. Server doesn't crash

### How to reproduce
Install CFM
Place a crate
Try to open

[debug.log](https://github.com/Mohist-Community/Mohist/files/5636788/debug.log)
[latest.log](https://github.com/Mohist-Community/Mohist/files/5636789/latest.log)

**Comment by Dum4G** [comment]
Affected mod: Builders Crafts & Additions 1.16.2/3/4-20201130b
No other mods installed

### Description
Some furniture with advanced features doesn't do anything on interaction but an error seem to be connected to previous case. Server doesn't crash

### How to reproduce
Install Builders Crafts & Additions
Place an Arcade or MIDI Speaker or bookshelf
Try to click with RMB

[debug.log](https://github.com/Mohist-Community/Mohist/files/5638393/debug.log)
[latest.log](https://github.com/Mohist-Community/Mohist/files/5638394/latest.log)

**Comment by Sl0ter** [comment]
work's with the mohist build version 142

**Comment by Sl0ter** [comment]
ok sry I made a mistake, my Mohist was not correct installed. i can't load plugins. its the nomal Forge not the mohist -.-

**Comment by Mgazul** [comment]
work's with the mohist build version 143
