### ISSUE TITLE
[1.12.2] JustEnoughIds sets every biome in the game to plains

### ISSUE THREAD

**Issue by Jorbon** [Teneted/Tenet#663]
The mod JustEnoughIds removes the hard cap on items, blocks, and a few other things including biomes. It is effectively a backport of the 1.13 chunk format. In Mohist, all biomes in all dimensions are Plains as seen in the F3 menu and according to grass colors and mob spawns. This happens with nothing except for this mod loaded, and it does not happen in singleplayer or in a standard forge server.

Here is a link to the mod page:
https://www.curseforge.com/minecraft/mc-mods/jeid

**Comment by Mgazul** [comment]
It only removes the restrictions in forge, bukkit is still implementing restrictions

**Comment by Piston35** [comment]
> It only removes the restrictions in forge, bukkit is still implementing restrictions

Is there a way to remove the bukkit restriction? I don't see any option in the bukkit.yml file

**Comment by Jorbon** [comment]
@Mgazul is there a way to remove these restriction is bukkit? I don't see any options for that in the yaml file.

**Comment by Mgazul** [comment]
It is not recommended that you install jeids on the server, because mohist has already done the same thing, you only need to install it on the client

**Comment by Mgazul** [comment]
Same problem as #616, close here
