### ISSUE TITLE
[1.16.4] Heroes 1.97 init error

### ISSUE THREAD

**Issue by dreemlees** [Teneted/Tenet#666]
**Minecraft Version 1.16.4**
**Mohist 129**

### **Description**
An error occurs while loading Heroes 1.97[1.16.4] using Mohist 129. Works with Paper 1.16.4.

### **How to reproduce**
Install vault 1.7.3.
Install effectLib 6.4
Install Heroes premium 1.97 https://www.spigotmc.org/resources/⚔-heroes-premium-⚔.24734/

### **Logs**
https://pastebin.com/pY9PvGdL

**Comment by Shawiizz** [comment]
![image](https://user-images.githubusercontent.com/55449195/106359457-36cf0f00-6313-11eb-8a2c-b04ca5f1a427.png)
