### ISSUE TITLE
[1.16.4] Server crash with an Dimension API mod

### ISSUE THREAD

**Issue by Sl0ter** [Teneted/Tenet#676]
[debug.log](https://github.com/Mohist-Community/Mohist/files/5662329/debug.log)
[latest.log](https://github.com/Mohist-Community/Mohist/files/5662330/latest.log)
[crash-2020-12-08_23.26.54-server.txt](https://github.com/Mohist-Community/Mohist/files/5662331/crash-2020-12-08_23.26.54-server.txt)

**Describe the bug**
Server crash on startup with structure-gel-api mod. It's the only installed mod.

**To Reproduce**
1. Install structure-gel-api
2. Start the Server 

**Info (please complete the following information):**
- Mod/Plugins Name: structure-gel-api
 - Mod/Plugins  Version: 1.16.4-1.7.2

 - Mohist 1.16.4 build 147

**Comment by SilverDavidMC** [comment]
Hey, I'm the dev for Structure Gel. I looked into if I could fix it on my end, and it looks like you're setting the MinecraftServer's IServerConfiguration to null. That could break other mods besides mine, so having it not being null would be nice. Idk if this will fix everything or not though.

Here's my [MinecraftServer mixin](https://gitlab.com/modding-legacy/structure-gel-api/-/blob/1.16.4/src/main/java/com/legacy/structure_gel/core/mixin/MinecraftServerMixin.java) that we use to register dimensions, and a [build of Structure Gel](https://gitlab.com/modding-legacy/structure-gel-api/-/tree/1.16.4/FOR%20MOHIST) with logging to say what values are null when trying to run the mixin.

If you have any questions, let me know!

**Comment by Mgazul** [comment]
fixed
