### ISSUE TITLE
[1.16.4] Server crash with mod mob spawn

### ISSUE THREAD

**Issue by Nunmina** [Teneted/Tenet#678]
**Server env**
- Minecraft Version 1.16.4
- Mohist 165

Mods
- citadel-1.5.3
- iceandfire-2.1.4-1.16.4

Plugins
No

**Description**
Crash when joining a server and walking around the world.

**Logs**
[crash report](https://pastebin.com/jL1E8rUF)
[latestlog](https://pastebin.com/HScS8Zuy)

**Comment by Nunmina** [comment]
Thank you for the correction work.
However, it still seems to crash.
Thank you so much for your help in advance.

**Server env**
- Minecraft Version 1.16.4
- Mohist 166

**Mods**
- citadel-1.5.3
- iceandfire-2.1.4-1.16.4

**Plugins**
No

**Description**
Crash when joining a server and walking around the world.

**Logs**
[crash report](https://pastebin.com/NjrB7tBJ)
[latestlog](https://pastebin.com/dCi52RGv)
[debuglog](https://pastebin.com/rrc1GtFt)

**Comment by No3371** [comment]
If you are sure that it does not happens within Forge, you should reopen the issue.

**Comment by Nunmina** [comment]
Yes, I want you to open it again.
I don't have permission so I can't open it again.
It seems to work fine in single play.

By the way, the version of FORGE is `35.1.11`
