### ISSUE TITLE
[1.16.4] Vampirism crash on startup

### ISSUE THREAD

**Issue by bigenergy** [Teneted/Tenet#679]
mohist-1.16.4-165
[latest.log](https://github.com/Mohist-Community/Mohist/files/5684175/latest.log)
[crash-2020-12-13_07.08.03-fml.txt](https://github.com/Mohist-Community/Mohist/files/5684176/crash-2020-12-13_07.08.03-fml.txt)

**Comment by Mgazul** [comment]
mohist version #167 The error no longer appears after build
