### ISSUE TITLE
[1.12.2] Nether portals & Modded portals always creates new portals.

### ISSUE THREAD

**Issue by VanillaChan6571** [Teneted/Tenet#687]
Mohist Version : 136-146 (there could be older versions that have the issue but I know100% that 146 has this issue)

Nether portals & Modded portals making new portals in overworld causing infinite portals to be made and never used the portal that the user made.

When a user makes a portal in the overworld it "makes it" but when going back from the nether it seems to make a new portal floating or underground making infinite portals there is no 1 linked portal.

1. Make a nether portal or modded portal.
2. Enter
3. Go back 

Issue occurs.

I even test with only world edit so 1 mod and issue occurs.

Bypass: Magma does not have this issue. So right now waiting for a bug fix for Mohist. If you have this issue and want a fix? Magma Dev Build is working with portals just fine.

**Comment by Mgazul** [comment]
I did not have this problem after testing

**Comment by VanillaChan6571** [comment]
> 
> 
> I did not have this problem after testing

I tested with 2 modpacks and 1 with no pack.

All have the portal bug.

**Comment by DarkEvoli** [comment]
I also have the problem with the nether portals with the modpack enigmatica 2 expert skyblock

https://prnt.sc/w6kss6

https://prnt.sc/w6ktl0

**Comment by VanillaChan6571** [comment]
> 
> 
> I also have the problem with the nether portals with the modpack enigmatica 2 expert skyblock
> 
> https://prnt.sc/w6kss6
> 
> https://prnt.sc/w6ktl0

Only thing you can do is to wait for Mohist to update this fix or switch to magma. :/

**Comment by randomei** [comment]
I also have this bug. Mohist-1.12.2-166

**Comment by Mgazul** [comment]
fixed
