### ISSUE TITLE
Commands from mods do not work.

### ISSUE THREAD

**Issue by mirroI** [Teneted/Tenet#69]
I have my mod that adds a team. The team is available to everyone. If I run on a clean forgg server everything works. As soon as I run on your server it says "no permissons"

**Comment by ProsperCraft** [comment]
We wrote a plugin for this ;)
https://www.curseforge.com/minecraft/mc-mods/forge-to-bukkit-permissions/

**Comment by Mgazul** [comment]
Use the command /dump modscmds and print it in the dump/modscommads.mo file to view the permissions of the command and add it to your default group
