### ISSUE TITLE
[1.16.4] Ice&Fire's dragons doesn't work

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#693]
**Steps to reproduce:**
1. Try to summon Dragon from Ice&Fire mod via spawn eggs
2. Watch how nothing appears

**Log:** https://pastebin.com/gj2KyEvL

**Versions:**
citadel-1.5.3
iceandfire-2.1.4-1.16.4
mohist-1.16.4-188-server

**UPD:**
After traveling through the world server tries to summon a broken entity, that cause server crash: https://pastebin.com/eDEewvyg

**Comment by SSKirillSS** [comment]
Same with some mobs from Alex'sMobs 1.1.1. Log: https://pastebin.com/Hd97cs8S
To reproduce just try to summon Grizzly bear, Crocodile, Orca, or other mobs.

**Comment by SSKirillSS** [comment]
Just to clarify if you didn't saw my message in Discord:
Still an issue. New log: https://pastebin.com/mcsdVq8r

**Comment by Mgazul** [comment]
After my test, there is no such error

**Comment by SSKirillSS** [comment]
But after my test problem is still here. I also tried to redownload .jar file of mohist (build 191).
List of mods:
![image](https://user-images.githubusercontent.com/38190325/103014555-0051e780-4550-11eb-99d5-6778ce8e328d.png)
Log: https://pastebin.com/uExbvNBc

**Comment by SSKirillSS** [comment]
So, yea, it works. Make sure that you have enabled libraries checking in mohist config. Thanks to Mgazul for help in Discord ! ;)
