### ISSUE TITLE
【BUG】Player can take item from plugin GUI with bugs

### ISSUE THREAD

**Issue by martin1194** [Teneted/Tenet#694]
MC: 1.12.2

If there is non-mod server, player can't take out item from the GUI inventory (like GUI shop, GUI menu). After we install force mod, player can using bug to take item out from GUI. When they using ALT+ left/right click  or  CTRL + left/right click, they can let item to drop out from GUI inventory. 

GUI inventory is from spigot plugin. Such as BossShopPro, dtlTraders.

玩家可以直接從插件的GUI取出物品。
方式: SHIFT+左擊/右擊   或   CTRL+左擊/右擊

**Comment by Shawiizz** [comment]
Hi @martin1194, please try again with latest build to know if this issue still existing.

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug is always here, please open new issue.
