### ISSUE TITLE
Plugin (Advance GUI) can't work in Mohist

### ISSUE THREAD

**Issue by martin1194** [Teneted/Tenet#695]
https://www.spigotmc.org/resources/advancedgui-interactive-itemframe-guis.83636/
it can't work when it install at Mohist.
I reported to the plugin developer this issue. They said they can't do anything on it cuz it is not normal spigot/paper

https://cdn.discordapp.com/attachments/615256015704948808/790643155879329822/javaw_2020-12-21_03-39-24-211.mp4

**Comment by martin1194** [comment]
This video shows it is not working well
https://www.youtube.com/watch?v=W2tbvieYsTc&feature=youtu.be

If it works, it must be like this picture.
![image](https://user-images.githubusercontent.com/18354205/103008316-47ec6980-4578-11eb-87b9-9c56739310f3.png)

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug is always here, please open new issue.
