### ISSUE TITLE
[1.16.4] Forge Capabilities on players are not being applied. 

### ISSUE THREAD

**Issue by TelepathicGrunt** [Teneted/Tenet#696]
Hello, I am the developer for The Bumblezone which utilizes Forge's capabilities to store player's previous dimension and position info for my inter-dimension teleportation code. However, I have received a report of my mod crashing on Mohist server. No matter what I do, I could not recreate the crash using a server running only Forge and the person's modlist. It seems the crash only happens on Mohist and the crash is caused by this line of code, no matter where it is.
`PlayerPositionAndDimension cap = (PlayerPositionAndDimension) playerEntity.getCapability(PAST_POS_AND_DIM).orElseThrow(RuntimeException::new);`

It seems like the capability is just gone from the player which means my mod's teleportation code cannot function at all without that info. Since my mod works with latest Forge server and I cannot reproduce the crash at all, my suspicion is that the missing capabilities is probably caused by the Spigot end or Mohist. Hopefully this won't be too hard to track down and fix!
            
The issue report I had gotten:
https://github.com/TelepathicGrunt/Bumblezone/issues/39

**Comment by Mgazul** [comment]
This may be related to craftbukkit, they are not using Capability

**Comment by Mgazul** [comment]
566ce181 fixed this
