### ISSUE TITLE
[1.12.2] Creeper is a type of animal

### ISSUE THREAD

**Issue by martin1194** [Teneted/Tenet#698]
I am not sure that is GriefDefender bug or Mohist bug.
I report it to both Github.

GriefDefender debug log: https://griefdefender.github.io/debug/?U0D5ANsewZ

![image](https://user-images.githubusercontent.com/18354205/103007477-de1f9000-4576-11eb-8be8-9a627c7c1762.png)

**Comment by ghost** [comment]
Use redprotect and coreprotect. Better compatibility and works.

**Comment by martin1194** [comment]
Issue have been solved by GD
