### ISSUE TITLE
[1.12.2] Issue with lostcities under skyfactory 4.2.2

### ISSUE THREAD

**Issue by johncsuti** [Teneted/Tenet#701]
Crash report: https://pastebin.com/74EGFayy
Startup log: https://www.64stacks.com/startup.txt (too big for pastebin...)
Seems to be an issue with spawn location on the mod lostcities the mod version is: 2.0.22
I would like to play skyfactory with lostcites as it comes with it by default. Plus its nice to get resources.

Let me know if you need any other information!

**Comment by Shawiizz** [comment]
Hi @johncsuti, please try again with latest build to know if this issue still exists.

**Comment by Romaindu35** [comment]
This issue was open long time ago, this bug can be fixed now, if the bug is always here, please open new issue.
