### ISSUE TITLE
[1.16.4] [191] EssentialsX Error

### ISSUE THREAD

**Issue by Maar10tech** [Teneted/Tenet#702]
EssentialsX doesn't start correctly

No further plugins, no mods. New installed server.

Error Log:
https://haste.mohistmc.com/aruqocinuf.yaml

I used this download link, because other links and versions produces other errors and not even start the server without plugins...
https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.16.4/

**Comment by Mgazul** [comment]
The new version of EssentialsX is no longer compatible with forge+bukkit
