### ISSUE TITLE
[1.16.4] Class not found: Nashorn Engine stuff

### ISSUE THREAD

**Issue by WilliamQiufeng** [Teneted/Tenet#705]
[latest.log](https://github.com/Mohist-Community/Mohist/files/5738432/latest.log)
Java version 15.0.1
Mohist build #191

**Comment by WilliamQiufeng** [comment]
Just realized java15 doesn't have nashorn
Sry

**Comment by Dum4G** [comment]
You can try this fork with Nashorn backported and other stuff but Mohist and mods compatibility are not guaranteed
https://github.com/ameisen/jdk-mc/releases
