### ISSUE TITLE
BetterPortals incompatibility

### ISSUE THREAD

**Issue by BinaryEnigma01** [Teneted/Tenet#706]
Can't get BetterPortals working with Mohist, but it works on a normal forge server (This is for Mohist 1.12.2, latest version)
Here's the crash report: https://pastebin.com/WaeefTgh

**Comment by ghost** [comment]
Mods like these are quite unstable. And usually have compatibility issues with everything. It would be nice for it to have compatibility with something for once :) Great Issue 👍

**Comment by BinaryEnigma01** [comment]
I can see how it's unstable, but it works with 114 other mods on a forge server just fine
