### ISSUE TITLE
[1.7.10] Mod Items Not Working

### ISSUE THREAD

**Issue by iwentafk** [Teneted/Tenet#707]
I think Thermos is the culprit, however, for some reason I cannot use any of my modded items, unless I OP myself.

I get this message in chat: "You cannot use that item here" whenever I try to use an item.

Mohist Ver: 1.7.10

**Comment by ghost** [comment]
Wait this makes no sense. You're saying thermos is the culprit while Mohist is it's own product. Does that mean that you're running both?

**Comment by ghost** [comment]
Also a log, mod list and a plugin list would be greatly appreciated.

**Comment by iwentafk** [comment]
Mohist uses thermos code in it.

ie: https://github.com/CyberdyneCC/Thermos/blob/master/patches/net/minecraftforge/event/ForgeEventFactory.java.patch

that is the event being called when I use mod items in game as a non-op. Also I’m not using any plugins and I’ve gotta find my mod list I’ll send that in a bit.

**Comment by iwentafk** [comment]
Biomes O Plenty, BuildCraft, Chisel, iChunUtil, Lucky Block, Millenaire, Minecraft Comes Alive, Morph, Mo Villagers, Orespawn, Pams Harvestcraft and RadixCore

These are the mods I use

**Comment by aceman1209** [comment]
Commit bebadca. Build 22.
```
KImagine is no longer used, we are refactoring the entire project
Will break the compatibility of most mods, you need to wait for the reconstruction to complete
```
Maybe this is the problem?

**Comment by iwentafk** [comment]
So I should use an older build?

**Comment by aceman1209** [comment]
Try older build or use latest Thermos while developers refactoring the entire project.
