### ISSUE TITLE
Server crashes on startup (Mc Eternal)

### ISSUE THREAD

**Issue by rdmchr** [Teneted/Tenet#708]
I'm trying to run the modpack [Mc Eternal](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal), but at the beginning of the server startup, it crashes.
This is all the output that is being generated: https://hastebin.com/suyigipoqi.http

**Comment by ghost** [comment]
A lot of typos but no it is not related to forgeessentials client. The patch i gave you usually fixes mixin conflicts. So i assumed you had one.

**Comment by rdmchr** [comment]
> A lot of typos but no it is not related to forgeessentials client. The patch i gave you usually fixes mixin conflicts. So i assumed you had one.

Oh sorry. I hope I fixed it.

**Comment by ghost** [comment]
Much better. Expect answers from Mgazul as soon as possible.

**Comment by Mgazul** [comment]
No longer compatible with LagGoggles

**Comment by rdmchr** [comment]
Even after I removed the mod LagGoogles, the server crashed immediately.
