### ISSUE TITLE
[1.12.2] Unable to get a block through the getMaterial method

### ISSUE THREAD

**Issue by Redned235** [Teneted/Tenet#71]
Hi, I'm a plugin developer and recently got a report about Materials not being found from blocks using the format `<mod name>_<material name>`. This is the format used for getting items and has worked for the user just fine, however when it comes to blocks, it does not work at all. If I had to guess, this issue likely lies in `Material#getMaterial`. 

I first noticed this when saving blocks to a config file using the built-in serialization method in `ItemStack`, since it extends ConfigurationSerializable. Seems to save properly, but reading from the block name doesn't appear to work. Items however, work perfectly fine. The block is also saved in the format I mentioned above, which leads me to believe there is an issue when resolving the block itself.

I've not looked far too deeply into the source of Mohist, so I can't exactly say I'm 100% sure this is where the issue lies; but from what I have seen, it seems to me this is most likely where it is.

**Comment by Mgazul** [comment]
Use Material # getMaterial (material name) instead of Material # getMaterial (<mod name> _ <material name>)

**Comment by Mgazul** [comment]
But considering that multiple mods will use the same name, I might add as <mod name> _ <material name>

**Comment by Mgazul** [comment]
if(Material.getMaterial("PIXELMON_RED_APRICORN_TREE") != null)
{ 
       Bukkit.getLogger().info("Find item： PIXELMON_RED_APRICORN_TREE");
}

I tested this code without any problems
