### ISSUE TITLE
1.16.4 195 Mohist Server does not Shutdown. Windows Batch

### ISSUE THREAD

**Issue by Trackhe** [Teneted/Tenet#711]
After running the mohist jar with 

```
java -Xmx10G -Xms10G  -jar mohist-server.jar
pause
```

and if i stop it. 

```
[22:46:46 INFO]: Done (5.695s)! For help, type "help"
> stop
[22:47:03 INFO]: Stopping the server
[22:47:03 INFO]: Stopping server
[22:47:03 INFO]: Saving players
[22:47:03 INFO]: Saving worlds
[22:47:03 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[22:47:04 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:47:04 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[22:47:04 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:47:04 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[22:47:04 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[22:47:04 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[22:47:04 INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[22:47:04 INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
```

but the java prozess wont close. On Windows Batch

**Comment by denireilly** [comment]
i have the same issue on ubuntu, the server dosnt shutdown properly when rebooting or stopping

28.12 18:07:54 [Server] INFO Saving players
28.12 18:07:54 [Server] INFO Saving worlds
28.12 18:07:54 [Server] INFO Saving chunks for level 'ServerLevel[seaport]'/minecraft:overworld
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (seaport): All chunks are saved
28.12 18:07:54 [Server] INFO Saving chunks for level 'ServerLevel[seaport]'/minecraft:the_nether
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
28.12 18:07:54 [Server] INFO Saving chunks for level 'ServerLevel[seaport]'/minecraft:the_end
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (seaport): All chunks are saved
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
28.12 18:07:54 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
28.12 18:08:55 [Multicraft] Terminating server via signal
28.12 18:08:55 [Multicraft] Server shut down (terminating)
28.12 18:08:55 [Multicraft] Looks like a crash, check the server console. Return value: 143
28.12 18:08:55 [Multicraft] Server stopped

**Comment by denireilly** [comment]
hey,

using the latest mohist but still getting the shutdown issue

30.12 19:43:20 [Server] INFO Saving players
30.12 19:43:20 [Server] INFO Saving worlds
30.12 19:43:20 [Server] INFO Saving chunks for level {0}/minecraft:overworld
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (seaport): All chunks are saved
30.12 19:43:21 [Server] INFO Saving chunks for level {0}/minecraft:the_nether
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
30.12 19:43:21 [Server] INFO Saving chunks for level {0}/minecraft:the_end
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (seaport): All chunks are saved
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
30.12 19:43:21 [Server] INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
30.12 19:44:22 [Multicraft] Terminating server via signal
30.12 19:44:23 [Multicraft] Server shut down (terminating)
30.12 19:44:23 [Multicraft] Looks like a crash, check the server console. Return value: 143
30.12 19:44:23 [Multicraft] Server stopped

it is of an older map, if this has anything to do with it?

**Comment by Shawiizz** [comment]
On my side the server process stops after 5 seconds

**Comment by Shawiizz** [comment]
and with build 213 you had that issue ?

**Comment by denireilly** [comment]
yeh, using 
30.12 19:48:24 [Server] INFO This server is running Mohist version 1.16.4-214 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT, Forge version 35.1.28)

**Comment by denireilly** [comment]
can confrim the server map stops and saves fine using Craftbukkit 1.16.4, so i think the possible issue of it being a older map is rolled out

if you need any more info let me know

**Comment by Shawiizz** [comment]
In my opinion something is making the server slow when the server stops

**Comment by denireilly** [comment]
ah, i think you are right, i got it to stop properly after moving the plugins folder out

i believe it was a plugin causing this issue, we are still building up the servers on mohist so we are testing a lot of plugins although mohist isnt ready yet

apologies

**Comment by Trackhe** [comment]
For me it is working. Thank you.

If anyone need a Updater for windows.

start.bat
```
@echo off
:anfang
curl https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.16.4/lastSuccessfulBuild/artifact/*zip*/archive.zip --output "archive.zip"
if exist %CD%\archive.zip (
	Call :UnZipFile "%CD%" "%CD%\archive.zip"
	del /Q %CD%\archive.zip
	if exist %CD%\archive\projects\mohist\build\libs\mohist* (
		xcopy /F /Y /Q %CD%\archive\projects\mohist\build\libs\. %CD%\mohist-server.jar
		rd /Q /S archive
		"C:\Program Files\Java\jdk-13.0.2\bin\java.exe" -Xmx10G -Xms10G -Dfml.readTimeout=5000 -Dfml.queryResult=confirm -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -jar mohist-server.jar
		pause
		exit
	) else (
		echo No Downloaded Mohist Jar found. New Download?
		pause
		GOTO anfang
	)
) else (
	echo No ZIP found.New Download?
	pause
	GOTO anfang
)
exit
:UnZipFile <ExtractTo> <newzipfile>
set vbs="%temp%\_.vbs"
if exist %vbs% del /f /q %vbs%
>%vbs%  echo Set fso = CreateObject("Scripting.FileSystemObject")
>>%vbs% echo If NOT fso.FolderExists(%1) Then
>>%vbs% echo fso.CreateFolder(%1)
>>%vbs% echo End If
>>%vbs% echo set objShell = CreateObject("Shell.Application")
>>%vbs% echo set FilesInZip=objShell.NameSpace(%2).items
>>%vbs% echo objShell.NameSpace(%1).CopyHere(FilesInZip)
>>%vbs% echo Set fso = Nothing
>>%vbs% echo Set objShell = Nothing
cscript //nologo %vbs%
if exist %vbs% del /f /q %vbs%
```

**Comment by Shawiizz** [comment]
or juste set check_update_auto_download to true in mohist-config/mohist.yml file

**Comment by Trackhe** [comment]
O.o oh thank you xDD i shot with a gun at sparrows again damit.
