### ISSUE TITLE
1.12.2 Harvestcraft Item Type has an errors

### ISSUE THREAD

**Issue by 4Seasons11** [Teneted/Tenet#719]
Try to print out item type of harvestcraftitem:onionseed

but it said "command_block_minecart"

![2020-12-30_00 41 10](https://user-images.githubusercontent.com/69511188/103300360-0e1cd680-4a42-11eb-9c4c-65a45ad98d5e.png)

**Comment by Mgazul** [comment]
How did you print

**Comment by 4Seasons11** [comment]
> How did you print

with skript 

send "%type of event-item%"

**Comment by Mgazul** [comment]
Tell me the version of skript and the complete skript content

**Comment by 4Seasons11** [comment]
> Tell me the version of skript and the complete skript content

Skript 2.2 dev 37c
