### ISSUE TITLE
[1.12] Server hard lock when generating chunks in Futurepack dim

### ISSUE THREAD

**Issue by Reveter** [Teneted/Tenet#720]
Server hard locks frequently when trying to generate chunks in the Menelaus dimension from the Futurepack mod. Only happens with Mohist. Tested to be working with forge-1.12.2-14.23.5.285.

latest.log - https://gist.github.com/Reveter/b5648803ca212c37f103d368464219b9
thread dump - https://gist.github.com/Reveter/86efcf71f1c7c45cbf3def1d1e0b2328
Futurepack-1.12.2-26.4.88.jar - https://www.curseforge.com/minecraft/mc-mods/futurepack
mohist-1.12.2-151-server.jar

**Comment by Reveter** [comment]
I took a Visual VM snapshot of the server locking up:

![visualvm](https://user-images.githubusercontent.com/8112174/103389452-d9aa2880-4adc-11eb-889d-dff34783a0e8.png)


https://www.mediafire.com/file/b7te1si2mopr5rj/mohist-fp-serverlock.nps/file

**Comment by Reveter** [comment]
Further testing has indicated that this only seems to affect Mohist builds 121+ and that something changed in that build may be resulting in infinitely cascading world gen in Futurepack.

**Comment by ProsperCraft** [comment]
Is this closed because it is fixed in builds past 121?  Or are we stuck forever not updating?
