### ISSUE TITLE
launchwrapper

### ISSUE THREAD

**Issue by dayd21git** [Teneted/Tenet#725]
Where did you put the library launchwrapper.jar? 1.7.10!
I need to change authlib.

**Comment by Shawiizz** [comment]
Hi, you need to add the library name in libraries backlist in mohist.yml. Then you need to add your custom lib in customize_libraries folder in libraries folder

**Comment by Shawiizz** [comment]
Also I think the jar file you search is located at libraries/net/minecraft/server/minecraft_1.7.10.server.jar. Iirc the authlib is in that jar file

**Comment by dayd21git** [comment]
Return the library to its default location. Please.

**Comment by Shawiizz** [comment]
The library has always been in the same place
