### ISSUE TITLE
1.16.4 Plugin Error redprotect

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#732]
Log error: https://mclo.gs/m2DpuKH
Version: mohist-1.16.4-226-server.jar
OS: Linux

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/103436751-44b84400-4c30-11eb-8d36-cc49e8ba02bc.png)

**Comment by joaoespanhol** [comment]
plugin is work 1.16.5-306
