### ISSUE TITLE
1.16.4 MOD iceandfire freezer server.

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#735]
version: last
os: linux
Log: https://mclo.gs/8SWe0ig
log-crasher: https://mclo.gs/ZK1iiUn
structure start: iceandfire:graveyard

**Comment by SSKirillSS** [comment]
Also looks like it prevents server loading on startup when you have "heavy" world generator, like TerraForged (+ Biomes o plenty), which, I think, cause cascading worldgen and load chunks with problematic structures

**Comment by Mgazul** [comment]
Test the problem again, it should be fixed

**Comment by joaoespanhol** [comment]
> Test the problem again, it should be fixed

ok go testing

**Comment by SSKirillSS** [comment]
Looks like it still an issue.

mohist-1.16.4-247-server

**Comment by Kowantify** [comment]
I am currently experiencing this issue as well, I believe a paper.yml config allows you to adjust the tick time allowed by generation features, but since there isn't a paper.yml we have no way to change it currently, what do we do to fix this for rn?
