### ISSUE TITLE
1.16 Plugin incompatible - Essentials

### ISSUE THREAD

**Issue by denireilly** [Teneted/Tenet#737]
hey,

thought i would make a issue on the essentials compatibility for 1.16 servers

01.01 16:20:55 [Server] ERROR Error occurred while enabling Essentials v2.18.2.0 (Is it up to date?)
01.01 16:20:55 [Server] INFO java.lang.NullPointerException: null
01.01 16:20:55 [Server] INFO at com.earth2me.essentials.Essentials.onDisable(Essentials.java:431) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[forge:?] {re:classloading}
01.01 16:20:55 [Server] INFO at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:830) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
01.01 16:20:55 [Server] INFO at com.earth2me.essentials.Essentials.onEnable(Essentials.java:370) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] {re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[forge:?] {re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[forge:?] {re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:401) ~[forge:1.16.4-230] {re:classloading}
01.01 16:20:55 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:315) ~[forge:1.16.4-230] {re:classloading}
01.01 16:20:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:444) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
01.01 16:20:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:363) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
01.01 16:20:55 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:217) ~[?:?] {re:classloading,pl:accesstransformer:B}
01.01 16:20:55 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
01.01 16:20:55 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
01.01 16:20:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}

**Comment by Mgazul** [comment]
#624
