### ISSUE TITLE
[1.12.2]使用群峦传说mod，生成世界时无法生成群峦的树木变种。

### ISSUE THREAD

**Issue by MasterIMLG** [Teneted/Tenet#741]
使用的群峦传说版本：TerraFirmaCraft-MC1.12.2-1.7.10.168.jar
使用的Minecraft版本：1.12.2
使用的Forge版本：14.23.5.2855
使用的操作系统：Windows 10
未使用任何其他模组与插件

Bug描述：在使用level-type=tfc_classic生成一个新的世界时，世界中只有原版橡树，包括使用“动态的树：群峦传说附属”mod时，世界中也只生成动态橡树。
此bug无错误报告，无日志。
此bug无法在Forge端复现

**Comment by Mgazul** [comment]
已知是由Bungeecord导致的错误
