### ISSUE TITLE
1.16.4 MOD FpsReducer-mc1.16.4-1.18 

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#743]
I can't join server

https://cdn.discordapp.com/attachments/615256015704948808/795026539876057168/unknown.png

Last version
OS: Linux

**Comment by SSKirillSS** [comment]
So... I have this mod on client (cuz it clientside), and I can join to server, it works fine.

**Comment by Mgazul** [comment]
The error usually comes from the plugin: ProtocolLib
