### ISSUE TITLE
[1.12.2] NetherEX 模组的地形和怪物生成在 Mohist 上不工作

### ISSUE THREAD

**Issue by RisingInIris2017** [Teneted/Tenet#745]
#### Mod version:
LibraryEx-1.12.2-1.1.3
NetherEx-1.12.2-2.2.2

#### Mohist version:

mohist-1.12.2-165-server

#### Installed mods:
Only LibraryEx-1.12.2-1.1.3 and NetherEx-1.12.2-2.2.2 

## Link to full crash log
No crashLog

#### How to reproduce:
1. remove  ./world 文件夹
2. Go Nether
3. No entities and structions in NetherEX。
It works in forge server

我已将相同的 issue 反馈给 NetherEX 模组：https://github.com/LogicTechCorp/NetherEx/issues/267
在此先感谢你的耐心帮助！

**Comment by Rabbit0w0** [comment]
Adding new terrains will expected to be fixed in the further versions
