### ISSUE TITLE
[1.16.4] Itemgroup fill crash

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#750]
IDK is this issue related to mohist, but to clarify I'll report it :D

So, to reproduce you should install these mods and try to create a new world on the server:
abnormals_core-1.16.4-3.0.6
minecolonies-0.13.557-ALPHA-universal

Version of mohist: mohist-1.16.4-247-server

Log: https://pastebin.com/MFRZfuQr

**Comment by SSKirillSS** [comment]
Also looks like this issue doesn't happen every time. It rarely happens when I try to create a new world on the server

**Comment by Mgazul** [comment]
Use forge server to test whether the problem can be reproduced
