### ISSUE TITLE
[1.16.4] Entities low spawnrate

### ISSUE THREAD

**Issue by SSKirillSS** [Teneted/Tenet#751]
So, as said in the title of this issue - most mobs (modded and vanilla) have a rly low spawnrate. With hard difficult and double-increased spawnrates in config I saw only 1-3 skeletons and zombies per whole terrain with a radius of 10 chunks.
Also noticed, that most of animal-typed mobs spawns fine, and issue with low spawnrate related only to monsters or some neutral mobs. Just for example, in the Nether I can't found any piglin or other hostile entity outside the dungeon, on condition I have 4 mods, that add entities to the Nether and other worlds.

**Version:** mohist-1.16.4-247-server

**Comment by SSKirillSS** [comment]
After staying AFK at one place ~2 hours I got some mobs:
![image](https://user-images.githubusercontent.com/38190325/103541662-d03e0900-4eac-11eb-94f6-14f307118d4f.png)
Other places of nether still pretty void and contains only striders.

**Comment by rex706** [comment]
@SSKirillSS I was frustrated about this too until I found this old thread and it surprisingly worked well for me. Got monsters to spawn way more than it used to:

https://www.spigotmc.org/threads/low-mobspawns-in-spigot-craftbukkit-is-fine.337884/#post-3179007

**Comment by VeritasSapere51** [comment]
This issue can most likely be closed, as I do not have major issues with spawrate after adjusting the settings in bukkit config, though it might be good if the standert setting does not produce such low spawnrates.
