### ISSUE TITLE
The server failed to start. There's a crash report

### ISSUE THREAD

**Issue by gzx7301** [Teneted/Tenet#753]
[crash-2021-01-02_04.29.45-server.txt](https://github.com/Mohist-Community/Mohist/files/5764831/crash-2021-01-02_04.29.45-server.txt)
↑This is a crash report without deleting the error mod↑

[crash-2021-01-04_06.57.32-server.txt](https://github.com/Mohist-Community/Mohist/files/5764830/crash-2021-01-04_06.57.32-server.txt)
↑This is my error report after deleting the error mod（appliedenergistics2）↑
I need to keep these two MODS and use the server normally. Can you help me（Using translation）

**Comment by Mgazul** [comment]
Your mod is using forge-1.7.10 class

**Comment by gzx7301** [comment]
thank you sir
