### ISSUE TITLE
[1.16.4] Entities despawning when out of render distance

### ISSUE THREAD

**Issue by germaniuss** [Teneted/Tenet#755]
Version: mohist-1.16.4-250-server

I was porting a forge server world to mohist and noticed a bug with all entities that were either not renamed or tamed. The issue is that when you walk out of render distance the entities just disappear (this includes cows and villagers in my case). I tried to make the server from zero (no mods) as well (same issue). 

Video: https://drive.google.com/file/d/1l4HTERacCZTjF4cxArL1H042PaFJ1L7F/view?usp=sharing

Reproduce:  
1. Create a mohist server
2. Place some entities in creative mode
3. Get out of render distance
4. Go back

**Comment by KR33PY** [comment]
Can confirm, happens to me also. Pretty annoying.
