### ISSUE TITLE
[1.16.4] Plugin [Protocolib] makes players unable to join the server

### ISSUE THREAD

**Issue by Lkids-innocence** [Teneted/Tenet#757]
Mohist version : mohist-1.16.4-251-server.jar
After adding the plugin "Protocolib", players can't join the server.
Minecraft client mentioned :
"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 107 bytes extra whilst reading packet 0"

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/103646316-89aee400-4f6a-11eb-94ab-675377e03987.png)

**Comment by Dum4G** [comment]
What version of ProtocolLib? Latest release is from early 2020 and developed for 1.15.2, latest two builds from Jenkins seem to be incompatible with Forge because of some new lib they use. Try 4.6.0 snapshots from #483 to #490

**Comment by Lkids-innocence** [comment]
I have already tried 4.6.0 snapshots #490 and #492. There is still the problem.
#490:
"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/0 (CConfirmTeleportPacket) was larger than I expected, found 8 bytes extra whilst reading packet 0"
and the error in my first issue is #492

**Comment by Mgazul** [comment]
Will not solve any plugin compatibility issues in the short term, so close it

**Comment by Maichmolker103** [comment]
I Am Having The Exact Same Problem Did Any One Ever Get A Fix???? Pls???

**Comment by Maichmolker103** [comment]
My Version is 1.16.5 Tho
