### ISSUE TITLE
Change the Javascript interpreter engine to Rhino

### ISSUE THREAD

**Issue by stevefan1999-personal** [Teneted/Tenet#758]
As of Java 11, Nashorn, the infamous JSR223 implementation of Javascript engine from Oracle, has been deprecated and was removed in the most recent version at Java 15. This means we cannot run Mohist, even without any mods nor plugins installed, on Java 15 as of now.

However, [mozilla/rhino](https://github.com/mozilla/rhino), a Mozilla-made alternative, still-maintaining implementation of Javascript engine, should be compatible to not only run Nashorn's code, but also features some more modern ES6 features (sadly, no classes support yet), and so I think this can be used as a substitute. 

I took the inspiration from KubeJS which demands the Rhino mod, and I had an eureka moment to remember this long-forgotten gem.

Previous issue: #705

**Comment by Mgazul** [comment]
Nashorn is used by forge
