### ISSUE TITLE
unloader incompatible

### ISSUE THREAD

**Issue by Tiagox42** [Teneted/Tenet#761]
Mohist 1.12.2 separates the mod unloader-1.2.0.jar in "delete" saying that the mod is not compatible, is this correct or is it a bug?
sorry the English

mod: https://www.curseforge.com/minecraft/mc-mods/unloader
mohist version: mohist-1.12.2-166-server

**Comment by Shawiizz** [comment]
Yeah the mod is in the incompatibility list, so that's not a bug.
