### ISSUE TITLE
[1.16.4] Immersive Portals (for Forge) Causes world generation to halt

### ISSUE THREAD

**Issue by CodexHere** [Teneted/Tenet#762]
No visible errors indicating any issue with Immersive Portals, but I manually copied over every mod one by one to verify this one was stopping world preparation at "84%." (seemingly fluctuates from 84-99% on each start, but either way it stops preparing)

Mod page on Curseforge: https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge

Startup Log: https://mclo.gs/EcsVdKK

Once removed, the server starts and everything works as expected.

Such a cool mod, would love to see this get some love!

**Comment by CodexHere** [comment]
We've completely removed this from our modpack since there hasn't been any feedback from Mohist.

**Comment by SSKirillSS** [comment]
Still an issue. Versions:
mohist-1.16.5-331-server
immersive-portals-0.14-mc1.16.4-forge
![image](https://user-images.githubusercontent.com/38190325/106119691-87edd000-6166-11eb-98b0-fc9a3f436b14.png)

Same problem with Ice&Fire.

**Comment by EnterFor** [comment]
same

**Comment by RayanGhahari** [comment]
same good luck to the developers

**Comment by wdog5** [comment]
Hmmm,the mod use mixin to redirec the methods that bukkit use....

**Comment by wdog5** [comment]
@Redirect(
        method = "Lnet/minecraft/world/TrackedEntity;sendPacket(Lnet/minecraft/network/IPacket;)V",
        at = @At(
            value = "INVOKE",
            target = "Lnet/minecraft/network/play/ServerPlayNetHandler;sendPacket(Lnet/minecraft/network/IPacket;)V"
        )
    )

**Comment by KR33PYK1NG** [comment]
Fixed in bceab8a
