### ISSUE TITLE
[1.12.2] RCON drops server

### ISSUE THREAD

**Issue by Hexagon-Dev** [Teneted/Tenet#767]
OS: Linux 18.04
Java: 1.8.0(275) build 01
Mohist: 1.12.2 with plugins and mods.
Using Pterodactyl panel to control server.
Another server using another core and works fine with RCON.
During issue testing there was only me on server.
After any RCON command sent from my site CPU usage rises up to 100%, after some any other RCON commands server just stops responding, CPU usage drops to ~0.05% and that's all. I have nothing in server logs or in Pterodactyl logs.
Tried to: change mohist version, remove mods&plugins, another OS, another site connection. Nothing helps.

**Comment by Shawiizz** [comment]
Hello, please try with latest build.

**Comment by Hexagon-Dev** [comment]
Tried with latest build. The same behavior. On first pic you can clearly see that there are no players and cpu usage is minimal and on second one after sending two rcon requests containing command "list", cpu usage risen up to 100% and commands weren't executed. Nowaday this problem isn't important for me because I use Pterodactyl API to send commands, however maybe other users without panel would encounter same problem.
![test](https://user-images.githubusercontent.com/69513821/125146713-04caa000-e130-11eb-8846-facd97ef0f9c.png)
![test2](https://user-images.githubusercontent.com/69513821/125146714-05fbcd00-e130-11eb-9a2c-92c360cd7e4e.png)
