### ISSUE TITLE
[1.12.2]WorldBorder issue not fixed yet with "UHCcore" plugin

### ISSUE THREAD

**Issue by MakcSan** [Teneted/Tenet#77]
im sorry about opening issue like this for twice
but i updated to latest version of this  i heared my issue i posted has been fixed
so i updated and i tried using UHCcore
but it didnt work again... :(
still same issue is happening
[latest.log](https://github.com/Mohist-Community/Mohist/files/4085184/latest.log)
details.
Server Running on 1.12.2 mohist latest version
the issue is (its almost same as before)
worldborder is invisible (its not on client side its only on serverside. in normal spigot server i can run UHCcore without any problems)
and once it starts moving it will disappear to farlands... again 😢 
of course i asked to UHCcore Dev for many times
but seems like this issue is caused by Servercore because in spigot it works without any Problems
im sorry about posting this for twice :(

**Comment by Mgazul** [comment]
https://github.com/Mezy/UhcCore/issues/20

**Comment by Mgazul** [comment]
https://github.com/Mezy/UhcCore/issues/20
