### ISSUE TITLE
[1.16.4] Ice and fire 造成服务器假死？？

### ISSUE THREAD

**Issue by liuseniubi** [Teneted/Tenet#770]
mohist-1.16.4-256-server

> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/world/gen/WorldGenFireDragonCave$SphereInfo.class got resource com/github/alexthe666/iceandfire/world/gen/WorldGenFireDragonCave$SphereInfo.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/NodeProcessorDragon.class got resource com/github/alexthe666/iceandfire/pathfinding/NodeProcessorDragon.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/IStuckHandler.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/IStuckHandler.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/AbstractPathJob.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/AbstractPathJob.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobMoveAwayFromLocation.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobMoveAwayFromLocation.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobRandomPos.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobRandomPos.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobMoveToLocation.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/pathjobs/PathJobMoveToLocation.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/PathingOptions.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/PathingOptions.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/pathfinding/raycoms/PathingStuckHandler.class got resource com/github/alexthe666/iceandfire/pathfinding/raycoms/PathingStuckHandler.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/EntityDragonBase$1.class got resource com/github/alexthe666/iceandfire/entity/EntityDragonBase$1.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/EntityDragonBase$2.class got resource com/github/alexthe666/iceandfire/entity/EntityDragonBase$2.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/ai/DragonAITargetItems$1.class got resource com/github/alexthe666/iceandfire/entity/ai/DragonAITargetItems$1.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/client/model/util/LegSolverQuadruped.class got resource com/github/alexthe666/iceandfire/client/model/util/LegSolverQuadruped.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/client/model/util/LegSolver.class got resource com/github/alexthe666/iceandfire/client/model/util/LegSolver.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/client/model/util/LegSolver$Leg.class got resource com/github/alexthe666/iceandfire/client/model/util/LegSolver$Leg.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/IafDragonFlightManager.class got resource com/github/alexthe666/iceandfire/entity/IafDragonFlightManager.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/IafDragonLogic.class got resource com/github/alexthe666/iceandfire/entity/IafDragonLogic.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/IafDragonAttacks$Air.class got resource com/github/alexthe666/iceandfire/entity/IafDragonAttacks$Air.class true
> [22:04:26] [Worker-Main-168/TRACE] [net.minecraftforge.fml.loading.ModJarURLHandler/CORE]: Loading modjar URL modjar://iceandfire/com/github/alexthe666/iceandfire/entity/IafDragonAttacks$Ground.class got resource com/github/alexthe666/iceandfire/entity/IafDragonAttacks$Ground.class true

在显示以上信息后，服务器假死，只能聊天。

**Comment by Mgazul** [comment]
Provide complete log

**Comment by Mgazul** [comment]
#735
