### ISSUE TITLE
[1.12.2] Bug with PlayerDropItemEvent (Bukkit)

### ISSUE THREAD

**Issue by Flashback083** [Teneted/Tenet#780]
When PlayerDropItemEvent bukkit event is cancelled, the /give player item will give it twice 
Its also happen when setting the flag worldguard "item-drop" to deny (which do same thing, but easier tp test)
Version of Mohist : 159
If you need more info tell me !
Idk if its mohist side or another thing sorry :(
Edit 1 : Build 169 doesnt work too (latest when i right this line)

**Comment by Mgazul** [comment]
What is the specific content of the two prompts after the cancelled event

**Comment by Flashback083** [comment]
What do you mean by that?
I'll try to make a video today
