### ISSUE TITLE
[1.12.2] Modded explosion not registered to bukkit

### ISSUE THREAD

**Issue by NicolasWent** [Teneted/Tenet#781]
Hello,

In my server, I am using Flan's mod and Faction.

I am trying to safe a zone with faction by disabling explosions. And even if they are disabled the explosion still happens.

I think that during a modded explosion, the event [EntityExplodeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityExplodeEvent.html) is not fired. Thats why I can't make any explosion-safe plugin work.

Is there any solution to do that? I had this issue on my server since 10 month already :(

**Comment by NicolasWent** [comment]
The event is correctly fired in forge:

I have tried to create a mod that cancel any ExplosionEvent.Start event, and it worked with my Flan's Mod explosion.

So the event is correctly registered in forge but not into bukkit.

**Comment by Mgazul** [comment]
ExplosionEvent.Start corresponds to ExplosionPrimeEvent in bukkit

**Comment by NicolasWent** [comment]
Thank you for your answer.

After looking into Faction code: [Their handling of explosions](https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/engine/EngineFlagExplosion.java)

There are many events that they call:
- [HangingBreakEvent](https://helpch.at/docs/1.12.2/index.html?org/bukkit/event/hanging/HangingBreakEvent.RemoveCause.html)
- [EntityDamageEvent](https://helpch.at/docs/1.12.2/index.html?org/bukkit/event/entity/EntityDamageEvent.html)
- [EntityExplodeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityExplodeEvent.html)
- [EntityChangeBlockEvent](https://helpch.at/docs/1.12.2/org/bukkit/event/entity/EntityChangeBlockEvent.html)

I don't know if all of these events registered to bukkit from mohist.

But I think that the most important event is [EntityExplodeEvent](https://papermc.io/javadocs/paper/1.12/org/bukkit/event/entity/EntityExplodeEvent.html), because in this event, you can get the list of blocks that are affected by the explosion which offers more control. And usually, I think that plugins that are made to safe a zone are using EntityExplodeEvent because it offers more control.

I think it would be nice to register the event EntityExplodeEvent to fire when ExplosionEvent.Detonate fire so we can set the list of blocks affected and it will solve the issue.

**Comment by SekiAlpha** [comment]
Oh this is something that I really need.

**Comment by SekiAlpha** [comment]
So a little update on the issue. I talked to some other developers making something similar to mohist and this was their response:
![image](https://user-images.githubusercontent.com/12445848/106323594-a971b900-6245-11eb-95b4-3920e7205f63.png)

Anyone have thoughts on this?

**Comment by NicolasWent** [comment]
I think that forge explosions can be cancelled, at least there can be a workaround I think

And if it is not fixed for some time I might create a server-side mod that register this explosion event to bukkit

**Comment by SekiAlpha** [comment]
@NicolasWent That would be amazing! Are you going to make the mod public on github?

**Comment by SekiAlpha** [comment]
To add to this issue, plugins that have "safe zones" can not protect players from damage from explosions too. So hopefully that can be passed through and canceled in the future.

**Comment by SekiAlpha** [comment]
@NicolasWent have you made that mod yet btw? It doesn't seem like this issue will be fixed any time soon.

**Comment by NicolasWent** [comment]
Hello @SekiAlpha 

I have fixed the issue directly into mohist on: #1075

**Comment by SekiAlpha** [comment]
Hmm, I'm still able to damage blocks in safe zone claimed territory with industrial TNT. I am however using factions UUID but I don't think that should be a problem.

**Comment by NicolasWent** [comment]
I don't know then :(

Maybe industrial craft does not fire the event in forge or Factions UUID does not listen to the event.

I have Industrial Craft too in my server will try with normal 1.12.2 Factions, will check that

**Comment by SekiAlpha** [comment]
What are you using to make a safezone?

**Comment by NicolasWent** [comment]
I am using the fixed faction plugin for mohist that you can find on their website or discord
