### ISSUE TITLE
[1.16.4] Multiverse Plugin Issue

### ISSUE THREAD

**Issue by yangberdo** [Teneted/Tenet#788]
I tried adding more worlds into my server using the multiverse command . On the imported worlds , I cant send out messages in the chat , blocks disappear when I right click on them , I jitter alot . Please help fix this guys , thanks!

**Comment by SSKirillSS** [comment]
![image](https://user-images.githubusercontent.com/38190325/104117624-b4ff4d80-5333-11eb-891f-77faaab58a21.png)

**Comment by yangberdo** [comment]
my bad
