### ISSUE TITLE
[1.12.2] BlockPlaceEvent: getBlockReplacedState() returns new one instead of replaced state

### ISSUE THREAD

**Issue by Misat11** [Teneted/Tenet#79]
When I try to get data from getBlockReplacedState(), it'll return just current BlockState. This makes some spigot minigames such as BedWars unplayable (you can't build any block, because you can't get the previous material).

I did some debugging (I replaced air with grass block):
![image](https://user-images.githubusercontent.com/20199703/73008931-d3f98c80-3e0f-11ea-8000-ca13cf018cee.png)
Both methods returns the same blockstate but the first should return the previous state (or clone of previous state) with material AIR.

Maybe this bug is also in 1.15.x branch but I didn't test it yet.

**Comment by Iltotore** [comment]
Hi, I'll try to resolve this bug before go skiing (they're winter holidays in France =p)
Secondly, did you try to place a block in a replaceable block like tall grass or water ?

**Comment by Misat11** [comment]
No, I tried just to place new block. I'll try it later.
