### ISSUE TITLE
[1.16.4] Botania accessory menu not showing

### ISSUE THREAD

**Issue by germaniuss** [Teneted/Tenet#794]
Version: mohist-1.16.4-270-server

In the botania mod when the button "G" is pressed or the yellow button on the top-left of your helmet is pressed a menu should show up that enables rings and other accessories, however it doesn't.

![image](https://user-images.githubusercontent.com/41348282/104247633-75864d80-5468-11eb-89c4-13debcc6a446.png)

Reproduce:

Create a mohist server with botania
Press "G" or the button on top of helmet

**Comment by EnterFor** [comment]
This is a serious problem..

**Comment by EnterFor** [comment]
When I play, I don't reproduce this problem
