### ISSUE TITLE
[1.16.4] Server stuck on Preparing spawn area around 95-100%

### ISSUE THREAD

**Issue by TheDeafCreeper** [Teneted/Tenet#797]
World types I have tried:
Server Generated Vanilla
Server Generated Modded
Singleplayer Generated Modded
(I dont believe it's a world generation issue).

After some testing it appears [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge/files/all) is causing the issue as until I re-added it the world loaded just fine.

[Log File](https://github.com/Mohist-Community/Mohist/files/5804390/latest.log)

Full Modlist:
- AutoRegLib
- BetterMineshafts
- BetterWeather
- CC-Tweaked
- ChiselandBits
- Clumps
- CodeChickenLib
- CraftTweaker
- Create
- ConnectedTexturesMod
- Ender Storage
- Fast Furnace
- Fast Workbench
- Immersive Portals
- Iron Chest
- JEI
- JEI Tweaker
- Mekanism
- Mekanism Generators
- Mekanism Tools
- Mouse Tweaks
- PhysEx
- Placebo
- Polymorph
- Quark
- QuarkOddities
- Random Patches
- SwingThroughGrass

**Comment by Mgazul** [comment]
#762
