### ISSUE TITLE
mohist crash-report（1.16.4）

### ISSUE THREAD

**Issue by Hsber** [Teneted/Tenet#799]
Oh my goodness, I hope to get help. When I create a new server, the server prompts me: Exception in server tick loop, it looks like the Mohist build is exploded, and finally I attach the error file
[crash-2021-01-13_09.43.28-server.txt](https://github.com/Mohist-Community/Mohist/files/5805883/crash-2021-01-13_09.43.28-server.txt)

**Comment by Mgazul** [comment]
The plugins is too old and does not support 1.16.4
