### ISSUE TITLE
Error Latest Red Protect

### ISSUE THREAD

**Issue by dhannyjsb** [Teneted/Tenet#8]
Plugin Redprotect cannot start with  Mohist.
I don't know it is because Mohist or Redprotect. 

https://pastebin.com/8GaPT0jt

**Comment by Mgazul** [comment]
I am not sure if this is an error from Mohist, maybe you can give feedback to the plugin author!

**Comment by NickImpact** [comment]
The error is likely actually from Mohist here, and it'd simply be that it's using a different version of Configurate than what Spigot/Paper is sourcing. At least I believe that is.

**Comment by FabioZumbi12** [comment]
Yeah, i can confirm this! Sponge uses the version 1.3.1 and for Spigot the version 1.3.1 its shaded on Redprotect jar. If Mohist updates to 1.3.1 will fix, but for now, if you go to libraries folder and remove the folder `1.2.1` inside `com\typesafe\config` Redprotect will load!
