### ISSUE TITLE
[1.16.4] Worlds is not loading if this mod is on the server (Performant).

### ISSUE THREAD

**Issue by Kamiszewskyy** [Teneted/Tenet#801]
When I have this mod on a server with Mohist, the world won't load and it stalls like "Preparing world spawn 7%" something like this.

File: performant-1.16.2-4-3.30m.jar

![mohist crash performant](https://user-images.githubusercontent.com/62818516/104596365-2f9dd500-5674-11eb-86a0-233d771ec4df.PNG)

**Comment by SSKirillSS** [comment]
This mod also incompatible with 1.12.2 Mohist and already known.

**Comment by Kamiszewskyy** [comment]
is there an incompatible modification list somewhere?
