### ISSUE TITLE
[1.16.4] Grindstone crashes server with Charm mod.

### ISSUE THREAD

**Issue by germaniuss** [Teneted/Tenet#806]
Mohist version: 1.16.4-305
Modlist: charm-forge-1.16.4
Reproduce: 
1. install the charm mod
2. load a world
3. use a grindstone

Latest Log: [latest.log](https://github.com/Mohist-Community/Mohist/files/5824810/latest.log)
Crash Report: [crash-2021-01-16_18.14.57-server.txt](https://github.com/Mohist-Community/Mohist/files/5824811/crash-2021-01-16_18.14.57-server.txt)
Video: https://user-images.githubusercontent.com/41348282/104818418-cbbc0d80-5827-11eb-9b46-c99157ec9c75.mp4

**Comment by Mgazul** [comment]
Where is the crash log

**Comment by germaniuss** [comment]
> Where is the crash log

Did some testing and narrowed it down to the charm mod. Also provided the log and crash report.
