### ISSUE TITLE
Mohist dont like world pregenerators

### ISSUE THREAD

**Issue by NXTler** [Teneted/Tenet#807]
Well i tried a few world pregenerators both as plugin and mod. for the first few seconds it seems fine but then it puts out errors in insane rates (as fast as you can generate the chunks). I had a few mods in but the dont mess with saving chunks or even the worldgen self but here is the list:
AI-Improvements-1.16.2-0.3.0
FastFurnace-1.16.3-4.3.0
FastWorkbench-1.16.3-4.4.1
jmt_mcmt-1.16.3-0.18.60 (great multi threading mod 10/10)
Placebo-1.16.3-4.3.3 (lib mod for Fast-Workbench/-Furnace)
here is the error:
![Unbenannt](https://user-images.githubusercontent.com/73062438/104782670-e4bfb280-5784-11eb-86d4-1315f4087913.PNG)
![Unbenaannt](https://user-images.githubusercontent.com/73062438/104782681-e9846680-5784-11eb-838f-32ae0e2f1e59.PNG)

**Comment by NXTler** [comment]
I just did a short test without any mods and it worked fine I will make some more testing.

**Comment by Mgazul** [comment]
jmt_mcmt (any multi-threaded mod) is not suitable for bukkit api

**Comment by Irgendwer01** [comment]
@NXTler please use Chunk Pregenerator instead https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator

**Comment by NXTler** [comment]
@Irgendwer01 I did test this to but the same error came up.

**Comment by Irgendwer01** [comment]
@NXTler then i would say remove Mohist temporarily, start normal Forge server up pregen the world then put Mohist back in
