### ISSUE TITLE
[1.16.4] Brewing stand does not work with Charm mod.

### ISSUE THREAD

**Issue by germaniuss** [Teneted/Tenet#811]
Mohist version: 1.16.4-305
Modlist: charm-forge-1.16.4
Reproduce:
1. install the charm mod
2. load a world
3. use a brewing stand

Video: https://user-images.githubusercontent.com/41348282/104818779-08890400-582a-11eb-8b1b-ada39878f919.mp4

**Comment by Mgazul** [comment]
After testing, the problem was not found. Have you installed other mods?

**Comment by germaniuss** [comment]
> After testing, the problem was not found. Have you installed other mods?

No, I did a fresh server with only charm, the stacked water bottles (a charm feature) do not enter the brewing stand.
