### ISSUE TITLE
[1.12.2] CoreProtect Issues

### ISSUE THREAD

**Issue by Paneedah** [Teneted/Tenet#812]
Mohist Version: 1.12.2-172
CoreProtect Version: Latest Legacy Version

Details about the issue:
CoreProtect mostly works, rolling back modded blocks, items into chests, etc. which is fantastic, however my only complaint is that when an explosion is caused by a mod (e.g. the "EFLN" item from Tinker's Construct), CoreProtect reports and tells me that the blocks existed in that location, however I am unable to rollback anything in the area of explosion.

I have tried in multiple ways, even if I replace the chest which needs to be rolled back by hand then try to roll it back, it says the rollback is complete without making any changes to the chest.

In addition, some modded containers (such as chests from IronChests) get rolled back, however not the items inside. This is strange as it only occurs occationally and not each time I rollback. From what I have noticed, this only occurs when the chest is no longer present, however rolls back fine if the chest already exists // wasn't broken.

Reproduce:
  1. Blow up an area with an "EFLN" from Tinker's Construct.
  2. Try to rollback the area.

Video: N/A, can provide if needed.

**Comment by SekiAlpha** [comment]
This would probably be resolved when this issue gets resolved: https://github.com/MohistMC/Mohist/issues/781#issue-782611792

**Comment by SekiAlpha** [comment]
To add to this issue, plugins that have "safe zones" can not protect players from damage from explosions too. So that's one thing to keep in mind.

**Comment by Shawiizz** [comment]
Hello, can you try with latest build please ?

**Comment by SekiAlpha** [comment]
Sure thing

**Comment by SekiAlpha** [comment]
It works for the EFLN however it doesn't work with industrial craft Industrial TNT.
