### ISSUE TITLE
[1.16.4]Plug-in permissions are lost after player death

### ISSUE THREAD

**Issue by Schwi-xgh** [Teneted/Tenet#814]
Mohist version: 1.16.5-306
Install plugin:
EssentialsX-2.18.2.0
GroupManager+ [v3.2] / LuckPerms-Bukkit-5.2.76

Both permission plugins have been tried. After giving the player permission, the player can use the command, and respawn after death. Use all commands to prompt no permission.
Re-join the server to resume the use of commands, and after one death, they have no permission to use all commands.

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/104845978-1db86e00-58d0-11eb-9fad-f1e93729a220.png)

**Comment by Schwi-xgh** [comment]
I tried the latest version and the problem still exists

**Comment by Mgazul** [comment]
Will not solve any plugin compatibility issues in the short term, so close it
