### ISSUE TITLE
Crash (1.12.2)

### ISSUE THREAD

**Issue by DragonOfStendarr** [Teneted/Tenet#815]
Im unsure if its mohist related but i think it could be, so im asking for help on the matter here is the link 

https://pastebin.com/BP8qXq8D

**Comment by Plasman888** [comment]
I have the same issue, a mod that we are using is causing the world file to be corrupt when a player enters the world, does your server work the first time but crash the subsequent times? This problem does not occur on a forge server so its probably got to do smth with mohist.

**Comment by DragonOfStendarr** [comment]
Hi forgot to close it, the issue is with nether portal spread 1.12.2 and mohist. since the crash didn't happen in forge but only on mohist.
