### ISSUE TITLE
1.16.5 mod ice and fire

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#816]
Server crasher.

LOG: https://mclo.gs/SoKYcoO

Version 1.16.5-306

**Comment by FrierenZk** [comment]
相同的问题，在ice and fire生成龙洞穴之类的结构时，服务器未响应，一分钟后自动关闭。
猜测可能跟线程死锁有关？

**Comment by SSKirillSS** [comment]
Idk what info you need, but to reproduce you can:
1. Install just Ice&Fire and fly around world, your server will be "freezed", then crashed.
2. Install Ice&Fire with Terraforder. Your server will be "freezed" on startup worldgen stage.

**Comment by KowalskiXCIX** [comment]
I am having this EXACT same issue, to fix the terraforged issue, terraforged has a config file that has a Max Tick Time for loading chunks/structures. Increasing that by a large amount fixes the generating new world issue. Ice & Fire still crashes when flying around thanks to it reaching minecrafts server.properties built in tick time, which i'm not starting to think is affected by paper.yml/mohist in some way, as in its overwriting there max tick time threshold.

**Comment by joaoespanhol** [comment]
The ice and fire structures are freezing the server.

**Comment by joaoespanhol** [comment]
you need more infor @Mgazul ?

**Comment by joaoespanhol** [comment]
https://mclo.gs/RiebMLf

**Comment by joaoespanhol** [comment]
I disabled the constructions and solve the crasher, but it is not a solution, because if not, there is no dragon in the world

**Comment by KR33PYK1NG** [comment]
Fixed in a51e8c4
