### ISSUE TITLE
[1.12.2] Issue with PIXELMONS not evolving under certain conditions only with Mohist.

### ISSUE THREAD

**Issue by LouisRs** [Teneted/Tenet#82]
Hey,
I've already done a ticket on the pixelmon tracker but I figured out I might as well put it here too considering it doesn't happen when the server doesn't run with Mohist.

The main issue is that some pokemon evolutions fail (and they end up evolving into themselves).
A safe way to reproduce it is by:
- Running a Mohist server.
- Disabling the "starterOnJoin" config in the "pixelmon.hocon" file.
- Giving the new player a Mudkip lvl 15 for example (through the "/pokegive [player] mudkip lvl:15" command).
- Making the Mudkip level up to 16 by fighting other pokemons.

The pokemon will then end up evolving into himself and then be kind of stuck in this state except if a staff uses the "/pokeevolve" command on it.

Here is the link to the issue with more details written on the Pixelmon bug tracker:
[https://www.pixelmonmod.com/tracker.php?p=2&t=14324](https://www.pixelmonmod.com/tracker.php?p=2&t=14324)

Feel free to ask anything that would be unclear ! (Even through Discord if needed: Douz#1212)
Thanks a lot !

**Comment by LouisRs** [comment]
Oh and I'm using the "reforged" version of Pixelmon !

You can find the download links here:
https://reforged.gg/

Thanks again !

**Comment by Iltotore** [comment]
Hi, I don't have this problem? Can you send a video of your mudkip while evolving ?
Also, which Mohist version do you use ?

**Comment by LouisRs** [comment]
Hey,
The Mohist version used is the "Mohist-2a408a8" one.

Here's a link to a video of the said bug:
[https://youtu.be/O3D8rC6yQPw](https://youtu.be/O3D8rC6yQPw)

As you can see in my pokemon, the ones that leveled up past 16 evolved successfully while the ones that only got to lvl 16 bugged (except for the lvl 17 one since I cancelled it myself).

Using a rare candy right on the evolution level also seems to work and not create the bug.

I hope this helps !

**Comment by LatePacket** [comment]
Yeah, getting the same issue here with Pixelmon not evolving although I'm running pixelmon with its default settings, and was also running the same build of Mohist as you were, just updated to the latest build "4f439ee" to see if there is any difference, will find out once the players give it a go

**Comment by PierreBouffartigue** [comment]
I also have the same problem which is random and does not seem to come from permissions

**Comment by LatePacket** [comment]
ok the players have reported it still happening on the latest Mohist build

**Comment by GDVE** [comment]
I have this problem too ..

**Comment by Renkiin** [comment]
Hello I'm also having this problem

**Comment by EpickaMC** [comment]
Hello the problem is always present and concerns especially new players.

**Comment by thomaaaas** [comment]
Any news ?

**Comment by Flashback083** [comment]
From what i heard by pixelmon dev team, its a know bug and not only on Mohist, so i think it more a pixelmon issue than a Mohist one

**Comment by Iltotore** [comment]
What are softwares affected by this pixelmon bug ?

**Comment by LouisRs** [comment]
Well, considering the topic is close to never touched on the Pixelmon Discord servers except for cases including Mohist (and Magma which I believe are copying some stuff from Mohist anyway), I feel like the problem might at least be somewhat related to Mohist.

I'm not sure as to what you're talking about Iltotore ? 
What do you mean by "What are softwares affected by this pixelmon bug ?" ?

**Comment by Rasgnarok** [comment]
It might be related to Mohist in Mohist-specific servers, but I can confirm this bug happens regardless of running Mohist or not. It's not as reliable to replicate, but it does happen on classic Spongeforge settings.

**Comment by ChampTheLegend** [comment]
Any fix?...
