### ISSUE TITLE
[1.16.5]ProgressiveBosses模组导致凋灵行为异常

### ISSUE THREAD

**Issue by hu7x** [Teneted/Tenet#823]
服务端版本：mohist-1.16.5-315
问题模组：[ProgressiveBosses](https://www.curseforge.com/minecraft/mc-mods/progressive-bosses/files)
问题描述：使用该模组生成凋灵后会直接触发一次破坏方块行为 导致灵魂沙和凋灵头掉落(单机无此问题)
视频链接：链接：https://pan.baidu.com/s/1EgTn6xrAIg3SAHOIRlxYQg 提取码：pepl

**Comment by Acyco** [comment]
凋灵头凋灵  ?
