### ISSUE TITLE
Saplings can't grow on server

### ISSUE THREAD

**Issue by GERFERIES** [Teneted/Tenet#824]
I started a server using Mohist core on minecraft version 1.16.5. It's working nice but has some annoying bugs. One of them - our saplings can't grow, they are just standing as a solid block and that's it. Bonemeal can grow a tree, however the tree can't grow by itself. I tried to grow tree naturally in singleplayer, it is working perfectly, then I tried it again on server but with no plugins and mods installed, still doesn't work. Any ideas how to fix this?

**Comment by 1528344561** [comment]
I have also encountered this problem. How did you solve it?
