### ISSUE TITLE
[1.12.2]TerraFirmaCraft trees don't spawn in the world

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#826]
Forge: 1.12.2 - 14.23.5.2854
TFC: TerraFirmaCraft-MC1.12.2-1.7.10.168
Mohist: mohist-1.12.2-179-server

Install mods, run, log in, there will be no trees in the world.

Also not in the topic, but I wanted to say that, when you set the rarity of trees to 0 in the Forestry mod config, so that they do not spawn, they still appear.

**Comment by Mgazul** [comment]
The problem does not exist, I am running a TFC server. He works well
