### ISSUE TITLE
Mod Crash 1.16.5-318

### ISSUE THREAD

**Issue by ptempleton** [Teneted/Tenet#828]
Structurize will not load on 1.16.5 from All The Mods 6 modpack.  structurize-0.13.104-ALPHA-universal.jar  To get the server to load, you must remove structurize and minecolonies(structurize is its dependency).
[crash-2021-01-21_08.10.19-fml.txt](https://github.com/Mohist-Community/Mohist/files/5850608/crash-2021-01-21_08.10.19-fml.txt)

**Comment by Mgazul** [comment]
```  [08:13:49 INFO]: Mod List:
• minecraft forge-1.16.5-36.0.1-server.jar : minecraft (1.16.5) - 1
• mods_folder structurize-0.13.113-ALPHA-universal.jar : structurize (0.13.113-ALPHA) - 1
• maven_libs forge-1.16.5-36.0.1-universal.jar : forge (36.0.1) - 1
• mods_folder minecolonies-0.13.574-ALPHA-universal.jar : minecolonies (0.13.574-ALPHA) - 1
• mods_folder create-mc1.16.3_v0.3e.jar : create (mc1.16.3_v0.3e) - 1

He works well

**Comment by joaoespanhol** [comment]
try new mod update, please
