### ISSUE TITLE
[1.16.5] Armor items do not lose durability on hit

### ISSUE THREAD

**Issue by Nyveon** [Teneted/Tenet#830]
Armor items when equipped, do not lose durability points upon taking damage. Tools do not have this issue, only armor.
Tested with a blank install of the latest mohist build (319)

Step to replicate:
1. equip armor (e.g iron armor)
2. take damage in survival mode (e.g on a cactus or a mob)
3. check durability

**Comment by SSKirillSS** [comment]
Can partially confirm. Most damage sources doesn't cause any damage to armor.
