### ISSUE TITLE
[1.16.5] 'Can't keep up' messages have placeholder text instead of actual values

### ISSUE THREAD

**Issue by arthomnix** [Teneted/Tenet#832]
Minecraft version: 1.16.5
Mohist version: 320

Java: OpenJDK 15.0.1
Operating system: Debian 10

Description:
The 'can't keep up' messages have `{0}` and `{1}` in place of the actual values for the amount of ms/ticks the server is behind. Here is an example message:
`[08:17:47 WARN]: Cant keep up! Is the server overloaded? Running {0}ms or {1} ticks behind`

**Comment by sayyidyofa** [comment]
Minecraft version: 1.16.5
Mohist version: 549

Java: OpenJDK 11.0.11
Operating system: Ubuntu Server 20.04

This issue still persists on build 549
