### ISSUE TITLE
[1.16.5] Dynmap commands are unknown but appear in autocomplete

### ISSUE THREAD

**Issue by arthomnix** [Teneted/Tenet#833]
Minecraft: 1.16.5
Mohist: 320
Java: OpenJDK 15.0.1
OS: Debian 10

Description: Commands from Dynmap (the forge mod version, not plugin) are unknown, although they do appear in the autocomplete.
![image](https://user-images.githubusercontent.com/35371030/105465944-7ea6c400-5c8b-11eb-9c81-03e5bbc86659.png)

Commands from other Forge mods work fine and it works on the standard Forge server.

**Comment by arthomnix** [comment]
sorry I accidentally saved it, I will edit the information in soon

**Comment by kotaniki** [comment]
I get same issue.

Mohist: 320
Java: OpenJDK 11.0.9
OS: CentOS8

**Comment by LiskoSlayer63** [comment]
Any info or schedule for fixing this?

**Comment by flololan** [comment]
Funny thing is that dynmap seems to work just fine (at least I can access the website) it's just not possible to execute commands.

**Comment by Gawdzend** [comment]
This issue persists with Mohist 1.16.5 / 572, the map loads fine in a browser, and what settings can be affected by its configuration text files appear to work as intended, however all server level commands (dynmap, dynmapext, dmarker) return an 'unknown command', despite being visible in autofill as previously mentioned.


![Capture](https://user-images.githubusercontent.com/84136225/118312169-d0c35d80-b4a5-11eb-82b8-3ae68ea533d2.PNG)

**Comment by gibland4** [comment]
Still having the same issue with Mohist 1.16.5 / 584.

**Comment by Mgazul** [comment]
#865
