### ISSUE TITLE
Mod Crash 1.16.5-318 #828

### ISSUE THREAD

**Issue by ptempleton** [Teneted/Tenet#834]
I just tested this on 1.16.5-321 and structurize still crashes the server.. Issue #828 is not resolved. #

**Comment by Nihilhalla** [comment]
828 has a workaround, update to the latest structurize, and it works.

**Comment by Shawiizz** [comment]
So is this issue resolved ?

**Comment by laboriens** [comment]
t's not possible to take the last version of the structurize because minecolonies ask for a precise version and refuse the above versions

**Comment by joaoespanhol** [comment]
try new mod update, please
