### ISSUE TITLE
Console Auto-completion Not Working

### ISSUE THREAD

**Issue by Subilan** [Teneted/Tenet#84]
Hi, there.

It's my first time to use **Mohist** as my server startup core. Before I heard of **Mohist** from my friend, I've always been using **SpongeForge**. _Mohist is great_, but there is one thing I cannot (under)stand.

My server is running on **Ubuntu 18.04**. During the time I run **SpongeForge**, I could easily get command completion from the console just by a press of <kbd>tab</kbd>. But today I found that **Mohist** does not support that awesome feature.

I asked my friends but they said they can get the completion easily. The only difference between my friends and I is that they are using **Windows Server** as server system while I am using **Ubuntu**.

Luckily, when I got into the server, the auto-completion worked. However, that is not in the range of **Mohist** itself, right?

Is it true that:
- Mohist **actually** supports command auto-completion in console?
- I can only get command completion from Mohist on **Windows**?
- Mohist does not supports command completion on **Ubuntu** or **OTHER LINUX SYSTEM**s?

The completion is important because
- It can help us quickily & easily get all the permissions that a specific plugin has. For example, `/lp group default permission set essentials.` + <kbd>tab</kbd>. If we have this, there is no need to search for information on the plugin wiki or Google.
- It can help us quickily & easily get all the items or blocks that a specific mod has. For example, `/give Steve botania:p` + <kbd>tab</kbd>.

All in all, auto-completion is very important. Actually, it is more important than **ANYTHING**.

OK, if the issue I reported only appears on my server, then I'll delete it :P

**Comment by Iltotore** [comment]
This doesn't seem to be a Mohist problem. Some terminal interfaces don't support tab completion. Did you try using another terminal ? Are you using ssh ?

Edit: Check also your spigot.yml. You can toogle auto completion tought it.

**Comment by Subilan** [comment]
~~Yes, I am using ssh through the ubuntu built-in terminal application.~~

Thank you! I finally find the completion configuration in `spigot.yml`.
