### ISSUE TITLE
[1.16.5] Permissions are gone after players die.

### ISSUE THREAD

**Issue by Remering** [Teneted/Tenet#841]
I use [LuckPems](https://github.com/lucko/LuckPerms) to manage the permissions, but this [issue](https://github.com/lucko/LuckPerms/issues/2846) said that the issue is caused by mohist.

**Comment by Shawiizz** [comment]
Please don't send issue about plugins. For the moment only mods are fixed, please wait ^-^

**Comment by Mgazul** [comment]
Will not solve any plugin compatibility issues in the short term, so close it
