### ISSUE TITLE
1.16.5 crasher Grindstone vanilla minecraft

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#844]
Server crasher.

LOG:https://mclo.gs/POGedMK
Version: last

**Comment by Mgazul** [comment]
#806

**Comment by joaoespanhol** [comment]
Server crasher again.

https://mclo.gs/8nVY1r3

Same problem.

**Comment by Mgazul** [comment]
Unable to reproduce

**Comment by Mgazul** [comment]
Use the latest version of charm-forge-1.16.4-2.3.1.jar （You are using 2.1.9）
Test again

**Comment by Mgazul** [comment]
Since the Minecraft-1.16.5 version is relatively new, the mod is developed and updated quickly, so make sure that the mod you use is the latest version when reporting errors
