### ISSUE TITLE
All TFC tree and grass generation breaks down

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#846]
All the grass and so on from TFC turns into vanilla grass, and the trees are spawned only from oak
What you need to reproduce the problem:
Mohist: 1.12.2 - 179
Forge: 2855
TFC: 1.7.11.169
Dynamic Trees: 0.9.21 - Or you can do it without it in any case the problem will appear
Dynamic Trees TFC: 0.9.16 - Or you can do it without it in any case the problem will appear
JustEnoughIDs: 1.0.3-55 - As I found out, when you include this mod in the build, this error appears, in a single game this does not happen.

**Comment by Exzept1on** [comment]
@Mgazul Did you fix the problem or just close it?

**Comment by Mgazul** [comment]
Remove JustEnoughIDs

**Comment by Mgazul** [comment]
I am running a TFC server for 2 months + he is working well

**Comment by Exzept1on** [comment]
@Mgazul I can't remove it because my modpack with TFC and GregTech doesn't work without it, because this mod expands the number of ids in minecraft, people ask me to make a cool server, I chose your core as the most advanced, but the build doesn't work on it because of one mod, you can just fix it and that's it. The problem is not solved by simple deletion, it seems that you do not want to do this. Your core is the most advanced, but you simply do not want to fix the bug of one mod, and everything works fine on the client, but not on the server. Install it and see for yourself.

And you just take and close the problem, without even bothering to check it, it's not professional -_-

**Comment by Exzept1on** [comment]
You again write that you have a TFC server and everything is fine with it, I'm not saying that this is a TFC error, this is a JustEnoughIds error, it feels like I'm sometimes not heard, if you are not going to fix it, then as a person who understands server cores, recommend a core that looks like Mohist, but it does not have a bug with JustEnoughIds

**Comment by Mgazul** [comment]
JustEnoughIds modified the biome, causing bukkit to fail to recognize the biome

**Comment by SpeeeDCraft** [comment]
Can you add support for this mod, it would be godlike, you dob support for other mods, let's not make this one an exception :)
