### ISSUE TITLE
the bug with death

### ISSUE THREAD

**Issue by Destroyer4ik** [Teneted/Tenet#848]
Faced with such a problem.
Server on version 1.16.5, Mohist core 1.16.5-326.
Installing the LuckPerms plugin. After death-all the rights of the player disappear, it is impossible to write to the chat or use any command. After re-entering the server , all rights appear again. I contacted the developers of the plugin - they said that the problem is in the core.

**Comment by Mgazul** [comment]
![](https://cdn.discordapp.com/attachments/615256015704948808/803193608642494465/unknown.png)

**Comment by kmecpp** [comment]
Even if plugin compatibility is low priority wouldn't it at least be a good idea to start working on getting the most essential plugins like LuckPerms and Essentials working?
