### ISSUE TITLE
Damage problem

### ISSUE THREAD

**Issue by itsmrval** [Teneted/Tenet#85]
When I hit a player who has diamond armor with a diamond sword, he takes half a heart / no damage.  it does the same thing with the armor and swords of all the minerals (and with modded minerals)

**Comment by Iltotore** [comment]
Hi, does this problem happen while wearing iron/leather/gold/chainmail armor ?

**Comment by itsmrval** [comment]
Yes, I noticed that the damage when a player wears armor is completely broken

**Comment by Iltotore** [comment]
Which version do you use?

**Comment by itsmrval** [comment]
Mohist-b01a467 1.12.2
