### ISSUE TITLE
1.16.5 Crasher mod farmersdelight

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#851]
Log:https://mclo.gs/QD7vxJY
Last version

**Comment by Mgazul** [comment]
Please use FarmersDelight-1.16.3-0.3.1 to test again  （You are using farmerdelight-1-16-3-0-2-4b.jar）

**Comment by SSKirillSS** [comment]
Starts just fine. Versions:
FarmersDelight-1.16.3-0.3.1
mohist-1.16.5-331-server

Have some startup issues with other mods (but I think it doesn't related to mohist), so check your modpack firstly.

UPD: Just found that this mod doesn't work with terraforged.

**Comment by SSKirillSS** [comment]
Finally, got it. To reproduce the issue you should install both Farmer's Delight and Terraforged **with a custom preset**. Versions:
FarmersDelight-1.16.3-0.3.1
TerraForged-1.16.4-0.2.0
mohist-1.16.5-331-server

In console I just see this, no more errors:
![image](https://user-images.githubusercontent.com/38190325/106125559-5d534580-616d-11eb-9c3b-21ac1df50ea0.png)

So, to fix this issue you should properly configure your terraforged world preset or just switch to default, then it should work fine.

Seems like issue can be closed.
