### ISSUE TITLE
[1.16.5]The plugin crashes immediately after installing the mod

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#852]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 21-1-25 下午10:12
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:324) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[forge:?] {re:classloading}
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:290) ~[forge:1.16.5-326] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:723) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}
Caused by: java.lang.IllegalStateException: No state for axis
	at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:354) ~[forge:?] {re:classloading}
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1127.el7.x86_64
	Java Version: 1.8.0_275, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 1242171096 bytes (1184 MB) / 2062286848 bytes (1966 MB) up to 6256590848 bytes (5966 MB)
	CPUs: 3
	JVM Flags: 15 total; -Xincgc -Xmx6000M -Xms2000M -Xss512K -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseCMSCompactAtFullCollection -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:CMSFullGCsBeforeCompaction=2 -XX:CMSInitiatingOccupancyFraction=70 -XX:-DisableExplicitGC -XX:-DisableExplicitGC -XX:TargetSurvivorRatio=90
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.1
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.1-server.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.8.4-f4f1a4d.jar   |Industrial Foregoing          |industrialforegoing           |3.2.8.4             |DONE      |NOSIGNATURE
		torchmaster-2.3.6.jar                             |Torchmaster                   |torchmaster                   |2.3.6               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |DONE      |45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		titanium-1.16.4-3.2.5.jar                         |Titanium                      |titanium                      |3.2.5               |DONE      |NOSIGNATURE
		Cucumber-1.16.4-4.1.5.jar                         |Cucumber Library              |cucumber                      |4.1.5               |DONE      |NOSIGNATURE
		ironfurnaces-1.16.5-2.6.1.jar                     |Iron Furnaces                 |ironfurnaces                  |2.6.1               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		Mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |DONE      |NOSIGNATURE
		SolarFluxReborn-1.16.3-16.2.3.jar                 |Solar Flux Reborn             |solarflux                     |16.2.3              |DONE      |NOSIGNATURE
		modnametooltip_1.16.2-1.15.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.15.0              |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		appliedenergistics2-8.2.0-beta.3.jar              |Applied Energistics 2         |appliedenergistics2           |8.2.0-beta.3        |DONE      |95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		torcherino-13.0.3+1.16.3.jar                      |Torcherino                    |torcherino                    |13.0.3              |DONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |DONE      |NOSIGNATURE
		NaturesCompass-1.16.4-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.4-1.8.6        |DONE      |NOSIGNATURE
		JustEnoughCharacters-1.16.5-4.1.4.jar             |Just Enough Characters        |jecharacters                  |4.1.4               |DONE      |NOSIGNATURE
		randompatches-2.2.0-forge.jar                     |RandomPatches                 |randompatches                 |2.2.0-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		buildinggadgets-1.16.4-3.7.3.jar                  |Building Gadgets              |buildinggadgets               |3.7.3               |DONE      |NOSIGNATURE
		DataFixerSlayer+1.0-3.jar                         |DataFixerSlayer               |datafixerslayer               |1.0-3               |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |DONE      |NOSIGNATURE
		MekanismGenerators-1.16.4-10.0.18.445.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.18             |DONE      |NOSIGNATURE
		byg-1.1.7-BETA-v3.jar                             |Oh The Biomes You'll Go       |byg                           |1.1.7-BETA-v3       |DONE      |NOSIGNATURE
		extradisks-1.16.4-1.5.0.jar                       |Extra Disks                   |extradisks                    |1.5.0               |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.1-universal.jar                 |Forge                         |forge                         |36.0.1              |DONE      |NOSIGNATURE
		Quark-r2.4-297.jar                                |Quark                         |quark                         |r2.4-297            |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		refinedstorage-1.9.11.jar                         |Refined Storage               |refinedstorage                |1.9.11              |DONE      |NOSIGNATURE
		MysticalAgriculture-1.16.4-4.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |4.1.4               |DONE      |NOSIGNATURE
		MysticalAgradditions-1.16.4-4.1.3.jar             |Mystical Agradditions         |mysticalagradditions          |4.1.3               |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |DONE      |NOSIGNATURE
		BetterPingDisplay-1.16.4-1.0.jar                  |Better Ping Display           |betterpingdisplay             |1.0                 |DONE      |NOSIGNATURE
	Crash Report UUID: c34fd1e5-425a-439b-9e09-237ed5740fc2
	CraftBukkit Information: 
   Running: Mohist version 1.16.5-326 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { TIMED_WAITING Timer hack thread: [java.lang.Thread.sleep(Native Method), net.minecraft.util.Util$6.run(Util.java:505)], RUNNABLE Thread-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338), com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:190)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], RUNNABLE Signal Dispatcher: [], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:73), net.minecraft.crash.CrashReport.<init>(CrashReport.java:38), net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:789), net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276), net.minecraft.server.MinecraftServer$$Lambda$10891/2074876416.run(Unknown Source), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Thread-3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], RUNNABLE Server console handler: [java.io.FileInputStream.read0(Native Method), java.io.FileInputStream.read(FileInputStream.java:207), org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:60), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:96)], RUNNABLE NanoHttpd Main Listener: [java.net.PlainSocketImpl.socketAccept(Native Method), java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409), java.net.ServerSocket.implAccept(ServerSocket.java:560), java.net.ServerSocket.accept(ServerSocket.java:528), moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:186), java.lang.Thread.run(Thread.java:748)], RUNNABLE Thread-6: [sun.nio.fs.LinuxWatchService.poll(Native Method), sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47), sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.lang.Thread.run(Thread.java:748)], RUNNABLE Thread-7: [sun.nio.fs.LinuxWatchService.poll(Native Method), sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47), sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.lang.Thread.run(Thread.java:748)], RUNNABLE Thread-2: [sun.nio.fs.LinuxWatchService.poll(Native Method), sun.nio.fs.LinuxWatchService.access$600(LinuxWatchService.java:47), sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:104)], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)], RUNNABLE Netty Epoll Server IO #0: [io.netty.channel.epoll.Native.epollWait0(Native Method), io.netty.channel.epoll.Native.epollWait(Native.java:114), io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:239), io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:256), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING ObjectCleanerThread: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.lang.Thread.run(Thread.java:748)], RUNNABLE DestroyJavaVM: [],}
   Recent tasks from -31--1{}
   Force Loaded Chunks: {}
	Player Count: 0 / 2021; []
	Data Packs: vanilla, mod:forge, file/bukkit, mod:torchmaster (incompatible), mod:theoneprobe, mod:astralsorcery, mod:titanium (incompatible), mod:cucumber, mod:ironfurnaces, mod:jei, mod:mekanism, mod:solarflux, mod:modnametooltip, mod:curios, mod:create (incompatible), mod:ftbbackups (incompatible), mod:placebo (incompatible), mod:autoreglib (incompatible), mod:appliedenergistics2 (incompatible), mod:torcherino, mod:storagedrawers (incompatible), mod:naturescompass (incompatible), mod:jecharacters (incompatible), mod:randompatches, mod:buildinggadgets, mod:datafixerslayer (incompatible), mod:aiimprovements, mod:observerlib, mod:mekanismgenerators, mod:byg, mod:extradisks, mod:quark (incompatible), mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_innovation (incompatible), mod:thermal_cultivation (incompatible), mod:thermal_expansion (incompatible), mod:fastleafdecay (incompatible), mod:refinedstorage, mod:mysticalagriculture, mod:mysticalagradditions (incompatible), mod:ironchest (incompatible), mod:chocolate, mod:betterpingdisplay (incompatible), mod:industrialforegoing (incompatible)
	Is Modded: Definitely; Server brand changed to 'Mohist'
	Type: Dedicated Server (map_server.txt)

**Comment by ghost** [comment]
https://mclo.gs/urcaIfm
The more

**Comment by Mgazul** [comment]
Provide a list of plugins, one of which does not support 1.13+

**Comment by ghost** [comment]
[Uploading latest.log…]()
the more.....

**Comment by ghost** [comment]
EssentialsX-2.18.0.21.jar
EssentialsXChat-2.18.0.21.jar
EssentialsXSpawn-2.18.0.21.jar
[权限组]GroupManagerPlus-2.0.5.jar

**Comment by ghost** [comment]
I‘m check All plugins support 1.16,but isn't work

**Comment by ghost** [comment]
If only use ess,it's say
[13:09:47 WARN]: 执行控制台指令 "ess" 出现异常
org.bukkit.command.CommandException: Cannot execute command 'ess' in plugin Essentials v2.18.2.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?] {re:classloading}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:669) ~[forge:1.16.5-329] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:655) ~[forge:1.16.5-329] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:925) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}

**Comment by ghost** [comment]
@Mgazul Thanks

**Comment by ghost** [comment]
disable byg
[13:14:24 WARN]: 执行控制台指令 "ess" 出现异常
org.bukkit.command.CommandException: Cannot execute command 'ess' in plugin Essentials v2.18.2.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[forge:?] {re:classloading}
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:160) ~[forge:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:669) ~[forge:1.16.5-329] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:655) ~[forge:1.16.5-329] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:362) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:761) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:276) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275] {}

**Comment by Mgazul** [comment]
Essentials v2.18+ no longer supports forge+bukkit
