### ISSUE TITLE
[1.16.5][320] The stop command doesn't terminate the mohist program.

### ISSUE THREAD

**Issue by kotaniki** [Teneted/Tenet#859]
Mohist: 320
Jave: OpenJDK 11.0.9
OS: CentOS8

The stop command saves the world, but does not terminate the program.
I have to force quit all the time.

![image](https://user-images.githubusercontent.com/10322951/106109945-72d86780-618d-11eb-98fa-5fd6ab934f2c.png)

**Comment by manugame** [comment]
Same problem on normal forge
