### ISSUE TITLE
[1.12.2] JustEnoughIds is not compatible with Mohist.

### ISSUE THREAD

**Issue by Exzept1on** [Teneted/Tenet#860]
JustEnoughIds: 1.0.3-55
Mohist: 185
LOG: [latest.log](https://github.com/Mohist-Community/Mohist/files/5886776/latest.log)
When installing JustEnoughIds on the Mohist server, no biome appears in the world except for plains and oak trees.

**Comment by Exzept1on** [comment]
@Mgazul Is it really impossible to fix it? I tried the CatServer core and there was no such bug. It has open source code and could take some of the code from there.

**Comment by SekiAlpha** [comment]
Have you tried a different seed?

**Comment by Exzept1on** [comment]
Yes, I have tried generating about 15 seeds and every time a biome is all over the world, even in the ocean plain.
