### ISSUE TITLE
how to use ipv6

### ISSUE THREAD

**Issue by zeruns** [Teneted/Tenet#862]
## **Mohist no support IPv6?**

![](https://img.zeruns.tech/2021/01/29/QQ20210129162651.jpg)
![](https://img.zeruns.tech/2021/01/29/QQ20210129162904.jpg)
![](https://img.zeruns.tech/2021/01/29/QQ20210129162921.jpg)

**Comment by Shawiizz** [comment]
Hey, first you shouldn't use an IPv6 since a lot of people don't have it if you make a public server. And then, if it's not working it's maybe because you don't have an IPv6 ? Try to put the IPv6 in the server.properties at line ip=

**Comment by zeruns** [comment]
> Hey, first you shouldn't use an IPv6 since a lot of people don't have it if you make a public server. And then, if it's not working it's maybe because you don't have an IPv6 ? Try to put the IPv6 in the server.properties at line ip=

Because our home network here does not have a public IP address, but they all have ipv6, so I need Mohist to support ipv6

I tried [Minecraft server 1.12.2](https://www.minecraft.net/en-us/article/minecraft-1122-released) can use ipv6.

**Comment by Shawiizz** [comment]
Try with normal forge

**Comment by zeruns** [comment]
> Try with normal forge

I have tried forge and it also does not support ipv6.

I see that the server is not listen ipv6, only listen ipv4

![](https://user-images.githubusercontent.com/17943073/106273642-f8cbdf80-626d-11eb-9a81-7352cca37b96.png)

**Comment by Shawiizz** [comment]
So contact forge team for that bug ^^

**Comment by zeruns** [comment]
> So contact forge team for that bug ^^

I just tried the latest version of forge(forge-1.12.2-14.23.5.2855) that supports ipv6

**Comment by zeruns** [comment]
I tried to support ipv6 under Windows, but not under Linux

**Comment by Longtianmu** [comment]
I thought you should use bracket like [240e::]

**Comment by AzAz71** [comment]
启动参数中尝试加入-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true
