### ISSUE TITLE
All commands are unknown

### ISSUE THREAD

**Issue by KubiRemPL** [Teneted/Tenet#865]
All comands that I use are unknown for the server, but autocompletion works.
I tried //pos1 and some of my other mods commands. Gamemode works tho.

**Comment by Shawiizz** [comment]
Which Mohist version ? 1.7.10, 1.12.2, 1.16.5 ?

**Comment by KubiRemPL** [comment]
Ohh sorry i forgot about that. I am on latest 1.16.5

**Comment by KR33PYK1NG** [comment]
@KubiRemPL, at the moment Bukkit doesn't know about mod (Forge) commands, see #748

**Comment by KubiRemPL** [comment]
I am using only mods @KR33PY

**Comment by LiskoSlayer63** [comment]
Any ETA for this? It's almost impossible to host a server without any access to commands

**Comment by Firch** [comment]
I really wish this will be resolved asap, all of my mods that require commands aren't working

**Comment by Dokman** [comment]
use fixed WorldEdit in the discord server and it's fixed, and update Mohist to latest version to fix essentials too.
