### ISSUE TITLE
[1.16.5] Excessive monster spawns

### ISSUE THREAD

**Issue by KR33PYK1NG** [Teneted/Tenet#867]
Monsters (and potentially other types of mobs) do not stop spawning.
To reproduce this fast, set 'ticks-per.monster-spawns' to 1 in bukkit.yml, set nighttime (/time set night) and stay in one chunk for several minutes.
From what I've seen, 'spawn-limits.monsters' matters only if set to 0 (fully prevents monster spawning)

![BONGP1A96k4](https://user-images.githubusercontent.com/75280223/106366287-df996080-634b-11eb-90db-d7f3a24cf52f.jpg)

**Comment by EnterFor** [comment]
It's scary, I think it should be a priority...

**Comment by Shawiizz** [comment]
Hi, can you try again with [this](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.16.5/341/artifact/projects/mohist/build/libs/mohist-1.16.5-341-server.jar) build to be sure before closing this ?

**Comment by KR33PYK1NG** [comment]
@Shawiizz, this can be closed.
