### ISSUE TITLE
[1.16.5]Can't connect to Mohist through proxy

### ISSUE THREAD

**Issue by xslingcn** [Teneted/Tenet#868]
Mohist:mohist-1.16.5-336-server.jar
客户端Forge:36.0.13
测试过的代理：
waterfall-1.16-394.jar
velocity-1.1.3.jar
配置文件：
Mohist:spigot.yml中` bungeecord: true`;
Waterfall:config.yml中`forge_support: true`,`ip_forward: true`;
Velocity:velocity.toml中`player-info-forwarding-mode = "modern"`,`announce-forge = true`,`ping-passthrough = "description"`;
确定客户端已安装所有所需Mod，并且不通过代理直接连接服务器时可以正常加入游戏。
使用Waterfall/Velocity代理均无法加入游戏并在console返回:
`[04:04:34 ERROR]: Channels [teamlapenlib:main,kiwi:main,quark:main,supplementaries:splmchannel,guideapi-vp:main,strawgolem:main,abnormals_core:net,vampirism:main,autoreglib:main,sereneseasons:main_channel,endergetic:net] rejected vanilla connections
[04:04:34 INFO]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.`
同时客户端会报错:![](https://i.bmp.ovh/imgs/2021/01/644163ca8aa152b8.png)
服务端Mod列表:![image](https://ftp.bmp.ovh/imgs/2021/01/067e038841250b4c.png)
服务端插件列表:![image](https://user-images.githubusercontent.com/43036991/106366645-3452d080-6378-11eb-9ede-c5739b4bdd2f.png)
客户端Mod列表:![](https://i.bmp.ovh/imgs/2021/01/9221ac7fc80ff030.png).

**Comment by Rabbit0w0** [comment]
This might be a proxy problem, please contact the authors of the proxies before contact Mohist.

**Comment by Rabbit0w0** [comment]
Try to remove the mod "BiomesOPlenty"

**Comment by xslingcn** [comment]
> Try to remove the mod "BiomesOPlenty"

Removed it and both the client&server tell me "This server has mods that require Forge to be installed on the client. Contact your server admin for more details."

**Comment by chrishdx** [comment]
Hi i have also the same Problem

**Comment by KingPhygieBoo** [comment]
I too have the same issue. It happens as soon as I install any mod that has a packet channel registered. This didn't use to be the case a few months back.

**Comment by KingPhygieBoo** [comment]
Okay, so I did some investigating. This issue seems to have popped up as soon as the initial 1.16.4 update happened, maybe that can help point the developers in the right direction
