### ISSUE TITLE
Too many mobs - 1.7.10

### ISSUE THREAD

**Issue by felipeleite5w** [Teneted/Tenet#870]
Im using Mohist 1.7.10 (latest version)

I used to use Thermos but I changed to Mohist this week, but there are TOO MANY animals spawning (Tps drop almost to 0) , in thermos less animals spawned, how to I fix that using Mohist?

**Comment by KR33PYK1NG** [comment]
Probably related to #867 ?

**Comment by Shawiizz** [comment]
@KR33PY I don't think since this issue is for Mohist 1.7.10 and your issue is for 1.16.5

**Comment by KR33PYK1NG** [comment]
@Shawiizz, nah, I'm just pointing out the problem and its solution could be the same, despite the version difference.

**Comment by Shawiizz** [comment]
Ah ok
