### ISSUE TITLE
[1.7.10] Please add jopt-simple 4.7 support

### ISSUE THREAD

**Issue by TENIOS** [Teneted/Tenet#871]
When I replaced jopt-simple from 5.0.1 to 4.7, the server stopped starting, without this version the functions of some mods do not work.

```
Mohist Starting...
Loading libraries, please wait...
Exception in thread "main"
```

Build 26.

**Comment by Shawiizz** [comment]
Hi, in your libraries folder you have another folder called customize_libraries. Just drag and drop jopt-simple 4.7 in this folder and start your server :)

**Comment by TENIOS** [comment]
I tried it. Mods use exactly the version that runs on Core.
