### ISSUE TITLE
Gravestones not spawning when players die

### ISSUE THREAD

**Issue by cheese404** [Teneted/Tenet#878]
Gravestones mod does not spawn a gravestone when players die.
Minecraft Version: 1.16.5
Mohist version: 336
Mod Version: gravestone-1.16.5-1.0.1.jar

Logs: https://mclo.gs/rjYisCq

**Comment by Jaboolian** [comment]
I also have this problem on my server. No gravestone, no obituary. Same versions of everything, though my server has 67 Forge mods. It worked fine before the transition from a Forge server to a Mohist server. Ctrl+F "slime" in the server log to find a death.

Log: https://mclo.gs/h5vo9eA
Mod list: https://gyazo.com/00ce6cee293fa489284db773a2ce9688

**Comment by joaoespanhol** [comment]
error mod: CarryOn 
i see your log, error mod CarryOn

**Comment by McNougatt** [comment]
this is the same issue as corpse and lootable bodies

**Comment by mango16384** [comment]
Same issue here without any other mod.
Completely empty (no plugin either) Mohist server with only corpse mod loaded still not spawning the corpse.
