### ISSUE TITLE
Enderman farm not working

### ISSUE THREAD

**Issue by InferusAnima** [Teneted/Tenet#890]
The Minecraft Version is 1.16.5
The mohist versio is 336

Mohist breaking endermans xp farm, in forge server working fine.

**Comment by gXLg** [comment]
the same. Trying to turn up the spawnrate just a bit results in thousands of mobs in the Nether. Turning it back again is making spawnrate in the End equal to zero

**Comment by tSinSky** [comment]
I changed in bukket.yml monster-spawns: 400 to monster-spawns: 1 and it fixed. Mb it will help you
