### ISSUE TITLE
[1.16.4] 护甲不掉耐久，1.6.3也是，被攻击不掉耐久

### ISSUE THREAD

**Issue by alcmoe** [Teneted/Tenet#899]
mohist-1.16.4-299

**Comment by Shawiizz** [comment]
Hi, first please use [latest build](https://mohistmc.com/builds/1.16.5/mohist-1.16.5-341-server.jar). Mohist 1.16.4 isn't supported anymore. And please write in english for that everyone can understand :)

**Comment by alcmoe** [comment]
ok thx, I close
