### ISSUE TITLE
mohist 1.16.5 345 crash mods minecolonies

### ISSUE THREAD

**Issue by laboriens** [Teneted/Tenet#901]
hello i open this ticket because i have minecolonies which crashes the server when a citizen tries to take a minecart i opened a ticket on minecolonies then after i tried just with the server forge-1.16.5-36.0.13.jar and the most no problem so the problem comes from mohist here is the link to the ticket minecolonies where you would find the version and the log + crash

https://github.com/ldtteam/minecolonies/issues/6506

**Comment by laboriens** [comment]
little info: same problem with 0 plugins

**Comment by Shawiizz** [comment]
Salut, peux tu tester a nouveau ?

**Comment by laboriens** [comment]
oui tous de suite

**Comment by laboriens** [comment]
v 347

https://textup.fr/527266ZL

**Comment by wdog5** [comment]
Please try again

**Comment by laboriens** [comment]
> Please try again

with which version ??

**Comment by wdog5** [comment]
https://github.com/Mohist-Community/Mohist/pull/911

**Comment by wdog5** [comment]
I try to fix it in this PR

**Comment by laboriens** [comment]
if you want you can give me the jar in private on discord for me to test

**Comment by wdog5** [comment]
Ok

**Comment by laboriens** [comment]
the problem comes from the library because if I disable the check_libraries in mohist.yml and put the forge library, it has more crashes

log library forge: https://textup.fr/527498xo

**Comment by laboriens** [comment]
mohist v358

debug.log https://textup.fr/527881Ld

for

[09Feb2021 06:48:24.205] [Netty Epoll Server IO #0/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@7b13e345 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!

crash-server.txt: https://textup.fr/527882q8

latest.log https://textup.fr/527883sk

**Comment by laboriens** [comment]
in 
libraries\net\minecraftforge\forge\1.16.5-36.0.22

I have replaced
forge-1.16.5-36.0.22-universal.jar
forge-1.16.5-36.0.22.jar
forge-1.16.5-36.0.22-server.jar

by that of the forge and I had more problem so the concern with mohist and minecolonies comes from one of these jar

**Comment by Shawiizz** [comment]
These files are the modified Forge jars, they can't be replaced as it contains a lot of Mohist code

**Comment by laboriens** [comment]
little info latest version minecolonies and mohist still same problem.

**Comment by laboriens** [comment]
here is the crash log with the latest version of minecolonies , structuze and mohist 368
https://textup.fr/529925vi

**Comment by laboriens** [comment]
crash mohist 369 https://textup.fr/530338I4

**Comment by laboriens** [comment]
v370 https://textup.fr/530841vU

**Comment by Shawiizz** [comment]
It's not useful to provide logs at every build since we don't fix this issue for the moment.

**Comment by laboriens** [comment]
problem solved with version 375, I close the subject thanks to Shawiiz_z and KR33PY
