### ISSUE TITLE
[1.12.2]启动后无限崩服，

### ISSUE THREAD

**Issue by 2651084156** [Teneted/Tenet#904]
服务器会在出现以下日志之后崩溃 （Server will crash when have log like this）

https://pastebin.com/ELJQHgt3

**Comment by Shawiizz** [comment]
Hello, do you have a crash report to give ?

**Comment by 2651084156** [comment]
well just log i can not find the crash report

**Comment by 2651084156** [comment]
> 
> 
> Hello, do you have a crash report to give ?

well just log i can not find the crash report

**Comment by Rabbit0w0** [comment]
> Hello, do you have a crash report to give ?

The server just stopped responding simply, this may caused by BetterNether

**Comment by 2651084156** [comment]
> > Hello, do you have a crash report to give ?
> 
> The server just stopped responding simply, this may caused by BetterNether

well if it have the crash report I well send it rather than log，bug it do not give it even there no crash report folder。and I think it maybe cause by the plugin 。if it cause by mod it well have the crash report，and I find some plugin cause it just like normal close the Server（如果我可以找到崩溃日子的话我肯定发的是崩溃日志，但事实上它并没有生成。这个问题应该是插件导致的，mod导致的画会有崩溃日志，但是有些插件导致的崩溃是没有的就像正常的关服一样，除了日志里面一堆error没有其他信息）

**Comment by 2651084156** [comment]
> Hello, do you have a crash report to give ?

它并没有生成崩溃日志只有log，类似的log我还有好几个，需要插件和mod列表吗？

**Comment by Rabbit0w0** [comment]
try to remove BetterNether and remember that English is the only language we supported in international community

**Comment by Rabbit0w0** [comment]
Maybe you can try to remove BetterNether first, we thought that this plugin caused this crash

**Comment by 2651084156** [comment]
> try to remove BetterNether and remember that English is the only language we supported in international community
maybe it cause this problem，i well try but only player connect the Server the crash will occur。

**Comment by 2651084156** [comment]
> 
> 
> try to remove BetterNether and remember that English is the only language we supported in international community

i delete the plugin name ‘WorldBorder’ and it fix this problem success

**Comment by 2651084156** [comment]
> 
> 
> > try to remove BetterNether and remember that English is the only language we supported in international community
> 
> i delete the plugin name ‘WorldBorder’ and it fix this problem success

and delete BetterNether can fix too

**Comment by Rabbit0w0** [comment]
did you forced the server to preload the chunks with worldborder?------------------&nbsp;Original&nbsp;------------------

**Comment by 2651084156** [comment]
> did you forced the server to preload the chunks with worldborder?------------------&nbsp;Original&nbsp;------------------ From:&nbsp;&quot;2651084156&quot;<notifications@github.com&gt; Date:&nbsp;Wed, Feb 10, 2021 12:11 PM To:&nbsp;&quot;Mohist-Community/Mohist&quot;<Mohist@noreply.github.com&gt;; Cc:&nbsp;&quot;ErrorEncounterd&quot;<401395069@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;; Subject:&nbsp;Re: [Mohist-Community/Mohist] [1.12.2]启动后无限崩服， (#904)

no i do not set aworldborder for the nether slove this problem success but i meet a new problem like #920 how can i to slove it？
