### ISSUE TITLE
Mohist construction in 1.7.10

### ISSUE THREAD

**Issue by Hsber** [Teneted/Tenet#907]
Oh, I'm sorry, 1.7.10 Mohist prompted me that the download failed during the startup process. I need to download it manually, but when I tried to download it manually, I found that it couldn't be downloaded. I don't know what to do

**Comment by feiyuyu2019** [comment]
What information does it prompt
I'm not sure if it's this
https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
Put it here
\libraries\org\apache\commons\commons-lang3\3.3.2

**Comment by Hsber** [comment]
No, just tell me that the download failed, and then attach a link for me to download manually

**Comment by Hsber** [comment]
> What information does it prompt
> I'm not sure if it's this
> https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> Put it here
> \libraries\org\apache\commons\commons-lang3\3.3.2

I don't even have a libraries folder

**Comment by Hsber** [comment]
> What information does it prompt
> I'm not sure if it's this
> https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> Put it here
> \libraries\org\apache\commons\commons-lang3\3.3.2

Oh, I'm sorry. It's my fault. I opened the link you gave me, downloaded a jar, and then dropped it to the designated location. I was asked to take over the EULA agreement. However, it's incredible that I didn't see the EULA at all, and I didn't know how to go down

**Comment by feiyuyu2019** [comment]
> > What information does it prompt
> > I'm not sure if it's this
> > https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> > Put it here
> > \libraries\org\apache\commons\commons-lang3\3.3.2
> 
> Oh, I'm sorry. It's my fault. I opened the link you gave me, downloaded a jar, and then dropped it to the designated location. I was asked to take over the EULA agreement. However, it's incredible that I didn't see the EULA at all, and I didn't know how to go down

Is this file in the server directory
eula.txt

**Comment by Hsber** [comment]
> Is this file in the server directory
> eula.txt

No

**Comment by Hsber** [comment]
> > > What information does it prompt
> > > I'm not sure if it's this
> > > https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
> > > Put it here
> > > \libraries\org\apache\commons\commons-lang3\3.3.2
> > 
> > 
> > Oh, I'm sorry. It's my fault. I opened the link you gave me, downloaded a jar, and then dropped it to the designated location. I was asked to take over the EULA agreement. However, it's incredible that I didn't see the EULA at all, and I didn't know how to go down
> 
> Is this file in the server directory
> eula.txt

I tried to copy the EULA loaded from the Mohist core of 1.12 to the Mohist core of 1.7.10. I didn't expect it to succeed. It's incredible. I've solved the problem. Thank you for helping me with it

**Comment by Shawiizz** [comment]
Hi, can you give the console output please ?

**Comment by Shawiizz** [comment]
![image](https://user-images.githubusercontent.com/55449195/107240659-7213c100-6a2a-11eb-8cbb-c0c97e6ad18e.png)
Yo, to accept the EULA you just need to type true here, it's very simple. I close this.
