### ISSUE TITLE
1.16.5 347

### ISSUE THREAD

**Issue by laboriens** [Teneted/Tenet#910]
probleme librairie a chaque redemarage

https://textup.fr/527265bv

**Comment by wdog5** [comment]
cpw.mods.modlauncher.api.IncompatibleEnvironmentException: No coremod library found
It is not a problem of mohist...
Please check your network connection

**Comment by laboriens** [comment]
these host at verygame and every time I delete the library I no longer have the problem until I restart

**Comment by laboriens** [comment]
little info with v345 I have no problem I only have it with v 346 and 347

**Comment by jkholick** [comment]
i have the same issue i just delete the library, it re-downloads and it works again until restart

**Comment by SSKirillSS** [comment]
Have similar issue. Libs redownloading doesn't help in my case.

**Comment by Shawiizz** [comment]
Fixed in latest build.
