### ISSUE TITLE
[1.12.2] Problem with Ducts and etc.

### ISSUE THREAD

**Issue by Asek3** [Teneted/Tenet#912]
https://youtu.be/VfL2HPPkmRI
Problem started with Mohist 183 version.
Also with restart Thermal Mods Gui's sometimes can't be open.

**Comment by SekiAlpha** [comment]
Best solution I found was to disable skip-tileentity-ticks in tileentity.yml in the mohist-config folder
There is also the option for skip-entity-ticks that I set to false in entity.yml also in the mohist-config folder.

Although this issue does still happen sometimes where tile entities are not updated, it happens to a much lesser degree. It even happens to vanilla furnaces sometimes.

**Comment by SparkGNRK** [comment]
Tested and working using latest mohist version
