### ISSUE TITLE
[1.16.5]A downloading problem for the new version 1.16.5-354

### ISSUE THREAD

**Issue by rainyorange** [Teneted/Tenet#916]
![image](https://user-images.githubusercontent.com/36807368/107396601-e046a980-6b38-11eb-8962-bed440b328ce.png)

This coremod.jar cannot be downloaded.
This download URL shows 404.

**Comment by Shawiizz** [comment]
it doesn't exists in gitee.io. Try to change the locale to en_US in mohist.yml

**Comment by rainyorange** [comment]
> it doesn't exists in gitee.io. Try to change the locale to en_US in mohist.yml

I will try it

**Comment by rainyorange** [comment]
> it doesn't exists in gitee.io. Try to change the locale to en_US in mohist.yml

It does't work
![image](https://user-images.githubusercontent.com/36807368/107397655-d4a7b280-6b39-11eb-93c2-c36e6b881a1b.png)
![image](https://user-images.githubusercontent.com/36807368/107397732-e12c0b00-6b39-11eb-9747-84612003911a.png)

**Comment by rainyorange** [comment]
Is there anything trouble in this site?

**Comment by Rabbit0w0** [comment]
fix soon
