### ISSUE TITLE
【1.12.2】服务器不生成树，server do not generate tree。JEID BUG

### ISSUE THREAD

**Issue by 2651084156** [Teneted/Tenet#919]
同样的种子我客户端试过了是有的，服务器只有mod的树。server do not have but the client have the tree just tree for mod

this  is the log 
https://mega.nz/file/2N50hD6B#JUmWUBVPPNDIdntbjengQAFL_D6D4fPevxd-drFqJQc  
this is the server
![2021-02-10_11 18 20](https://user-images.githubusercontent.com/69307837/107461379-d0f54980-6b94-11eb-88cc-e7ccf3b0af26.png)

this is the client
![2021-02-10_11 21 14](https://user-images.githubusercontent.com/69307837/107461459-fe41f780-6b94-11eb-80df-adc68b5ccc09.png)

i  generate this tow world with a seam seed.
i don't know why and use rtg to  generate the world is have the tree

**Comment by 1798643961** [comment]
log file，please

**Comment by Serega007RU** [comment]
This problem is due to the JustEnoughIDs mod. See https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/166

**Comment by Trackhe** [comment]
Why Wont Fix ?

**Comment by 0XPYEX0** [comment]
> Why Wont Fix ?

这是JEID的问题，不是Mohist的问题
JEID把群系全部变成了PLAINS(平原)
卸载JEID即可解决

**Comment by Trackhe** [comment]
@0XPYEX0 但是如果我卸载了这个mod，那么我就必须卸载其他mod，因为生物群落被限制在265个。不幸的是，这个问题将在1.13中得到解决。

**Comment by 0XPYEX0** [comment]
> @0XPYEX0 但是如果我卸载了这个mod，那么我就必须卸载其他mod，因为生物群落被限制在265个。不幸的是，这个问题将在1.13中得到解决。

Mohist has no idea to deal with this issue
Please check this:  https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/166
It must be fixed by its creator

**Comment by Serega007RU** [comment]
look at this fork, it seems like they added compatibility with MohistMC by cutting out some of the unnecessary functionality from this mod
https://github.com/Mgazul/JustEnoughIDs

**Comment by 0XPYEX0** [comment]
> look at this fork, it seems like they added compatibility with MohistMC by cutting out some of the unnecessary functionality from this mod
> https://github.com/Mgazul/JustEnoughIDs

This fork has some problems... It may cause your server crashed when you try to start it
According to Mgazul(Author of Mohist), Mohist itself has supported the existence of 256 + biomes

**Comment by Trackhe** [comment]
I will try that. And experiment a bit, thank you for your supporting.
"Mohist itself has supported the existence of 256 + formations" this is nice but if you add Galacticcraft, Biomsoplanty, Forestry and Twilightforest, you can get easely over the 256Bioms and i guess non of theese plan to be able to run only with mohist.

**Comment by 0XPYEX0** [comment]
> I will try that. And experiment a bit, thank you for your supporting.
> "Mohist itself has supported the existence of 256 + formations" this is nice but if you add Galacticcraft, Biomsoplanty, Forestry and Twilightforest, you can get easely over the 256Bioms and i guess non of theese plan to be able to run only with mohist.

I don't think it's a good idea that you now remove JEIDs. This behavior may destory your worlds and cannot recover
You can try to remove JEIDs when you are starting a new game

**Comment by Trackhe** [comment]
i tried to use(the fork https://github.com/Mgazul/JustEnoughIDs) it with a new world but this fork isnt working. In first place it crashes if the id limit is reached.
