### ISSUE TITLE
【1.12.2】服务器里机器会在跨世界传送后坏掉，machine in server  will broken when Teleport across the world

### ISSUE THREAD

**Issue by 2651084156** [Teneted/Tenet#920]
服务器里的机器会在跨世界传送后坏的就像这样，machine in server  will broken when Teleport across the world like this：
![WISXRT44I~{FDWNZ{3_})TG](https://user-images.githubusercontent.com/69307837/107462261-ad330300-6b96-11eb-8346-4ea39d434bb6.png)

this is the log
https://mega.nz/file/2N50hD6B#JUmWUBVPPNDIdntbjengQAFL_D6D4fPevxd-drFqJQc

**Comment by Rabbit0w0** [comment]
Sorry, i dont understand your words, can you describe it more clearly?

**Comment by Rabbit0w0** [comment]
You can use Chinese, it's ok, I will tell your words to others

**Comment by chengts95** [comment]
I can confirm that IC2 block machines stop working after teleportation to another dimension.

**Comment by Krosta8** [comment]
Just found this issue and I can confirm that too for Applied Energistics 2 too, tested with latest version of Mohist

**Comment by SparkGNRK** [comment]
Tested using latest  Applied Energistics 2 and mohist and working when teleporting far away from the machine and going on another dimensions.
