### ISSUE TITLE
(1.12.2)when client connection to the sever client will generate the crash-reports。客户端连接到服务器时客户端会生成崩溃日志

### ISSUE THREAD

**Issue by 2651084156** [Teneted/Tenet#921]
only client connection to the sever will happen this problem 。

this is the log
https://mega.nz/file/2N50hD6B#JUmWUBVPPNDIdntbjengQAFL_D6D4fPevxd-drFqJQc

**Comment by Shawiizz** [comment]
Cannot reproduce. If you still have this issue, open a new issue following an issue template.
