### ISSUE TITLE
经过我的测试我之前发的问题都是这一个服务器核心独有的，其他核心不存在此问题

### ISSUE THREAD

**Issue by 2651084156** [Teneted/Tenet#926]

**Comment by Shawiizz** [comment]
Hello, please write in english and give more details, thanks.

**Comment by 2651084156** [comment]
> Hello, please write in english and give more details, thanks.

#925 
#923 
#922 
#921 
#920 
#919 
i mean that

**Comment by Shawiizz** [comment]
And what do you mean ? What did you opened this issue ?
