### ISSUE TITLE
[1.12.2] No data value error

### ISSUE THREAD

**Issue by imagreez** [Teneted/Tenet#927]
I have this error, when I set a modded block on the island. I use Iridium skyblock,[ I made a issue in the plugin,](https://github.com/IridiumLLC/IridiumSkyblock/issues/555) but I post here too

https://pastebin.com/zj0nWNk0

**Comment by daspositioned** [comment]
This is an "issue" (missing feature) with our plugin, no need to report it here ^^

**Comment by imagreez** [comment]
yeah, but I report here, if mohist can do anything to repair that for all plugins, whithout that feature

**Comment by daspositioned** [comment]
That's not something he can do, as we are using [XSeries](https://github.com/CryptoMorin/XSeries) for multi-version support and that's causing issues
