### ISSUE TITLE
Multi Worlds problem

### ISSUE THREAD

**Issue by Ludoclt** [Teneted/Tenet#928]
Hi, I wanted to tell you about my problem, I am using mohist 1.16.5 and when I use a multi world plugin like multiverse-core or multiworlds everything is fine, the creation of the worlds works, but when I import a world downloaded from internet, I have a big problem, the world is loading but all the structures disappear, there is no trace of what was built, I then tried importing a solo save and I had the same problem, I tried all the plugins of multi worlds and I still have this VERY disturbing problem, I then download version 1.16.5 of spigot and the world import works fine and the structures are there but it bothers me because I do not have the support of mods which are essential for my games, thank you for your help!

**Comment by Rabbit0w0** [comment]
Sorry, please use our issue template, and tell us the steps to reproduce the issue.

**Comment by Ludoclt** [comment]
You have to download the multiverse-core plugin on mohist 1.16.5 and import a world downloaded from internet (for example a redstone house or something like its) with the command /mv import name_of_world and then you tp to this world and you will see by yourself that the house will not be there.

**Comment by wdog5** [comment]
Could you please provide the log file？
Use the pastebin

**Comment by digitaltrucker** [comment]
I also have this issue.  What is happening is that the world is being recreated instead of imported.  A workaround is to do the 'import', then overwrite the newly generated files with the ones you wanted to import.  MV works fine then.

**Comment by Ludoclt** [comment]
No, it's a very particular situation, the world is imported, it's the same seed but everything the player has built is missing as if the world has been reset but as soon as I put this world as default world in server.properties, the structures that the player built reappear, it's hard to explain and it must be hard to figure out, the best is you have to try, as far as the logs go, there is none, no error is displayed, I don't think the error comes from the multiverse-core plugin because I am trying with several multi-world plugins and I still have the same problem on mohist yet it works on spigot, I think then that it is mohist 1.16.5 which does not support multi worlds and cannot generate several with complex structures.

**Comment by Romaindu35** [comment]
Same #1116
