### ISSUE TITLE
HarvestDropsEvent called twice in Mohist 1.12.2?

### ISSUE THREAD

**Issue by ghost** [Teneted/Tenet#931]
Is it normal for a forge event like ``HarvestDropsEvent`` to called twice?

This caused a bug in Pixelmon, which makes [berries](https://pixelmonmod.com/wiki/Berries) dupeable. **I tested with no plugins only the Pixelmon mod** and this bug is confirmed only happens in Mohist.

It's a very critical bug since Pixelmon takes a heavy part in modding the server. 

Thank you

**Comment by VOrlando520** [comment]
Can also confirm this issue as well. Happens with a lot of harvestable things

**Comment by KR33PYK1NG** [comment]
Fixed in 6d7e31d

**Comment by KR33PYK1NG** [comment]
(Mistook this issue for #936)

**Comment by ghost** [comment]
> 
> 
> (Mistook this issue for #936)

Hi. Have this issue is fix yet?
