### ISSUE TITLE
1.16.5 mod immersive-portals

### ISSUE THREAD

**Issue by laboriens** [Teneted/Tenet#932]
I contact you because the immersive-portals-0.14-mc1.16.4-forge.jar mod with mohist-1.16.5-360-server.jar plants.

I explain when it reaches 78% of loading the server does not answer any more, it has no crash file but if I launch the server only with forge-1.16.5-36.0.22.jar all works.

log in mohist server: https://textup.fr/528540tx
log in forge server: https://textup.fr/528541TK

**Comment by Shawiizz** [comment]
Same as #762
