### ISSUE TITLE
1.16.5冠军/强敌MOD精英怪追踪火球/冰弹导致服务器崩溃

### ISSUE THREAD

**Issue by hu7x** [Teneted/Tenet#933]
服务端版本：1.16.5-360
崩溃报告：https://paste.ubuntu.com/p/mYSTZh6pX9/
问题MOD：[Champions-forge-1.16.5-2.0.1.3](https://www.curseforge.com/minecraft/mc-mods/champions/files)
触发方法：该模组的精英怪的追踪火球/冰弹技能（手动生成也会触发）攻击玩家导致服务器崩溃
在单机测试无此问题
Forge官服测试无此问题

**Comment by Shawiizz** [comment]
Hello, please write in english.
