### ISSUE TITLE
#182 1.12.2 dupe head

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#934]
when the head is broken, drop two.
version 182
https://www.youtube.com/watch?v=MLfIVcA5SCA&feature=youtu.be

**Comment by SekiAlpha** [comment]
I'm also having this issue on my server.

**Comment by Shawiizz** [comment]
Try again with https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/191/artifact/projects/mohist/build/libs/mohist-1.12.2-191-server.jar
