### ISSUE TITLE
Gitee下载失败，手动访问404

### ISSUE THREAD

**Issue by cyans-nya** [Teneted/Tenet#935]
我直接Powershell使用Java启动Mohist
’PS D:\1.16.5 plugin+mod server> java -jar .\mohist-1.16.5-360-server.jar

 __    __   ______   __  __   __   ______   ______
/\ "-./  \ /\  __ \ /\ \_\ \ /\ \ /\  ___\ /\__  _\
\ \ \-./\ \\ \ \/\ \\ \  __ \\ \ \\ \___  \\/_/\ \/
 \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\  \ \_\
  \/_/  \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/   \/_/

                                      欢迎来到 1.16.5 ! - Mohist开发组
检查库文件中，请稍等...
总进度 >17%
下载文件 coremods-4.0.6.jar ，大小 175 B
下载文件 https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar 失 败
尝试第 1 下载之前下载失败的库文件
检查库文件中，请稍等...
总进度 >17%
下载文件 coremods-4.0.6.jar ，大小 175 B
下载文件 https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar 失 败
尝试第 2 下载之前下载失败的库文件
检查库文件中，请稍等...
总进度 >17%
下载文件 coremods-4.0.6.jar ，大小 175 B
下载文件 https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar 失 败
尝试第 3 下载之前下载失败的库文件
检查库文件中，请稍等...
总进度 >17%
下载文件 coremods-4.0.6.jar ，大小 175 B
下载文件 https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar 失 败
库文件检查完成，未发现问题
一些库文件下载失败了，请手动下载它们并放置到指定位置:
Link : https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
Path : D:\1.16.5 plugin mod server\libraries\net\minecraftforge\coremods\4.0.6\coremods-4.0.6.jar

PS D:\1.16.5 plugin+mod server>‘
让我手动下载，
我访问了 **https://mohist-community.gitee.io/mohistdown/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar**
![image](https://user-images.githubusercontent.com/68551684/107866798-5fefb380-6e6c-11eb-9a14-3dc61d6a50ca.png)
### 404 Not Found
请问Gitee那边镜像是不是炸了，
还是我这网络问题？

**Comment by mcdoeswhat** [comment]
一样的问题，同问

**Comment by BlueFunny19** [comment]
我刚才去Mohist的官方GitHub库里面拷了一份出来，现在分享出来
https://19770214.lanzous.com/b0165tq3g 密码:1234

附言:https://github.com/Mohist-Community/maven/
Mohist官方支持文件GitHub原库

**Comment by Shawiizz** [comment]
I will remove the gitee mirror later.

**Comment by BlueFunny19** [comment]
Please add a new mirror thanks.
Most of Chinese download files from github so slow without VPN.

**Comment by Shawiizz** [comment]
I don't know any other mirror, sorry. If you know one (free) tell it to me please.

**Comment by Shawiizz** [comment]
For the moment I close this as it's not really an issue. I will try to find another way to upload the libraries to be faster for China.

**Comment by BlueFunny19** [comment]
ok 3q.
Maybe i can offer one for free next month.
(When I got the microsoft E5 subscription.)
