### ISSUE TITLE
Tile Entities are not being updated or ticked.

### ISSUE THREAD

**Issue by SekiAlpha** [Teneted/Tenet#936]
I'm using Mohist version 1.12.2-186, and it seems like when using Mohist tile entities sometimes don't get ticked so glitched like multi locks not being detected happen. Things like vanilla furnaces stop working too.

Server restarts seem like the only solution.

![image](https://user-images.githubusercontent.com/12445848/107868284-21003480-6e51-11eb-9b1d-3adcb05c292d.png)

**Comment by VOrlando520** [comment]
Can confirm that this issue is also happening with vanilla furnaces and such. Nothing in logs about it, so unsure how to fix it.

**Comment by joaoespanhol** [comment]
same problem last version 1.12.2-188

**Comment by KR33PYK1NG** [comment]
Fixed in 6d7e31d
