### ISSUE TITLE
World not saving on close - 1.12.2

### ISSUE THREAD

**Issue by VOrlando520** [Teneted/Tenet#939]
Using latest mohist for 1.12.2 and the world is not saving on close. Every reboot the server will roll back to the last manual save point done for the server.

**Comment by Shawiizz** [comment]
I don't have this issue. This is caused by a mod or a plugin. Please remove them 1 per 1 to see which is causing that bug.

**Comment by VOrlando520** [comment]
That's already been done, hence why I'm posting here. A couple fellow server owners are having the same issue as I as well.

**Comment by Shawiizz** [comment]
I just tested and i can't reproduce your issue.

**Comment by VOrlando520** [comment]
and you are on the latest mohist?

**Comment by Shawiizz** [comment]
Yes

**Comment by VOrlando520** [comment]
Alright after some testing today, it seems only chests are getting wiped and I've removed every plugin I can think of that would interact with chests and still can not figure out the issue.

**Comment by SekiAlpha** [comment]
I can confirm I'm getting this issue as well.

**Comment by Rabbit0w0** [comment]
You may save the data manually while we are checking this error

**Comment by Shawiizz** [comment]
I can't reproduce your issue. I tested to put things in a chest, i restarted my server and everything is fine.

**Comment by hoctz** [comment]
I'm having the same issue here

**Comment by Shawiizz** [comment]
I tested 3 times on 3 differents machine and i still can't reproduce this issue.

**Comment by Shawiizz** [comment]
Try with a fresh install and **without any plugins & mods**, you'll see that it saves chest content correctly.

**Comment by laboriens** [comment]
give your list of plugins and mods maybe you have one that also registers

**Comment by Shawiizz** [comment]
Try again to find which mod / plugin is causing that by removing them 1 per 1. I still can't reproduce this without any mod and plugin.

**Comment by VOrlando520** [comment]
Turns out it isnt world saving, but it seems to be a chest issue. It's not saving chest inventories and thats with just mohist and nothing else on the server

**Comment by Shawiizz** [comment]
Like I said, try with a clean install without any plugins and mods and you'll see that everything is fine.

**Comment by VOrlando520** [comment]
I just literally said that twice, i did that with a clean install. chests are not saving on any version above 159.

**Comment by joaoespanhol** [comment]
I don't have that problem.
I'm using the latest version.
My server resumes every 3 hours, and it has not been a problem so far.
I didn't even have complaints from the players.
I am use last version mohist. (11.12.2-192)

**Comment by SekiAlpha** [comment]
It's probably a mod issue but this doesn't occur with just forge. Figuring out what mod does this will be difficult.

**Comment by Shawiizz** [comment]
I close this since it's not reproduceable with a clean install. If needed, you can recreate the issue.
