### ISSUE TITLE
[1.16.5] Immersive Portals Mod Along when added to mods causing spawn 100% to keep on occurring

### ISSUE THREAD

**Issue by Rynxotic** [Teneted/Tenet#943]
**Using Mohist Version 192 (1.16.5)**

**Plugins Included:**  Essentials X, LuckPerms, Multiverse core, Multiverse Nether Portals, Multiverse Portals, Multiverse Sign Portals.
**Mods Included**: Immersive Portals (Forge Version) 1.16.4

When loading the server, the server gets stuck on loading spawn 100% and does not proceed further meaning the server never fully loads and players cannot join.

Currently there are no logs I can get as they are not shown as crash logs as the server never crashes, it just gets stuck on loading spawn. (If more info is needed I will be happy to try and get it when requested to)

**Comment by laboriens** [comment]
problem already reported

**Comment by Shawiizz** [comment]
Same as https://github.com/Mohist-Community/Mohist/issues/762
