### ISSUE TITLE
Its hard for me to download the lib

### ISSUE THREAD

**Issue by Kogasa-touhou** [Teneted/Tenet#948]
I try to download the libs
but got 404

Is there a offline lib pack?

**Comment by Shawiizz** [comment]
Hi, there is no offline lib pack. Can you give me your console output please ?

**Comment by Kogasa-touhou** [comment]
I tried again with a vpn.Its OK.
Sometimes it seems hard for us to download some libs in China.

**Comment by Shawiizz** [comment]
Yeah ik but I wait @Mgazul to update a lib on the gitee mirror. If Mgazul don't update coremod library, i will downgrade it and put and gitee mirror back.
