### ISSUE TITLE
More optimizations (multithreading and asynchronous)

### ISSUE THREAD

**Issue by CraftDream** [Teneted/Tenet#95]
Mohist now needs to have more optimizations based on the original compatibility (as far as I know, Mohist is good at tiles now?) , but that's not enough. If you're good at it, you're welcome to contribute code.

**Comment by z3nth10n** [comment]
Well, I reviewed this: https://github.com/PaperMC/Paper/pull/1397 it could be cool to be implemented on Mohist for 1.12 😄

**Comment by Mgazul** [comment]
#133
