### ISSUE TITLE
mohist 1.16.5 has problem runing on multicraft(libraries is complete)

### ISSUE THREAD

**Issue by mem0rz** [Teneted/Tenet#950]
config file

> [config]
name = [模组服]Mohist-1.16.5-Foge版本0042测试版
source = http://www.multicraft.org/download/jar/?file=spigot&version=latest&client=multicraft
configSource = http://www.multicraft.org/download/conf/?file=spigot.jar.conf
[encoding]
encode = utf-8
decode = utf-8
fileEncoding = utf-8
[start]
command = "{JAVA}" -Xmx{MAX_MEMORY}M -Xms{START_MEMORY}M -Djline.terminal=jline.UnsupportedTerminal -Dfml.readTimeout=90 -jar "{JAR}" nogui

log

> 18.02 11:36:54 [Multicraft] Received start command
18.02 11:36:54 [Multicraft] Loading server properties
18.02 11:36:54 [Multicraft] Starting server!
18.02 11:36:54 [Multicraft] Loaded config for "[模组服]Mohist-1.16.5-Foge版本0042测试版"
18.02 11:36:54 [Multicraft] Updating eula.txt file
18.02 11:36:54 [Server] INFO __ __ ______ __ __ __ ______ ______
18.02 11:36:54 [Server] INFO /\ "-./ \ /\ __ \ /\ \_\ \ /\ \ /\ ___\ /\__ _\
18.02 11:36:54 [Server] INFO \ \ \-./\ \\ \ \/\ \\ \ __ \\ \ \\ \___ \\/_/\ \/
18.02 11:36:54 [Server] INFO \ \_\ \ \_\\ \_____\\ \_\ \_\\ \_\\/\_____\ \ \_\
18.02 11:36:54 [Server] INFO \/_/ \/_/ \/_____/ \/_/\/_/ \/_/ \/_____/ \/_/
18.02 11:36:54 [Server] INFO Welcome to Mohist 1.16.5 ! - Mohist Developement Group
18.02 11:36:54 [Server] INFO Checking libraries, please wait...
18.02 11:36:55 [Server] INFO All libraries are nice :) !
18.02 11:36:55 [Server] INFO Checking the installation, please wait.
18.02 11:36:55 [Server] INFO An error occurs with the server start. You can ask for help to the Mohist support on Discord or GitHub.
18.02 11:36:55 [Multicraft] Server shut down (starting)
18.02 11:36:55 [Multicraft] Restarting crashed server in 5.0 seconds
18.02 11:36:55 [Multicraft] Looks like a crash, check the server console. Return value: 1
18.02 11:36:55 [Multicraft] Server stopped

**Comment by Shawiizz** [comment]
This is not related to Mohist but this is related to multicraft

**Comment by mem0rz** [comment]
> 
> 
> This is not related to Mohist but this is related to multicraft

But Mohist 1.12 is work.
