### ISSUE TITLE
[1.12.2] Server won't start

### ISSUE THREAD

**Issue by Skyere** [Teneted/Tenet#951]
[crash-2021-02-18_11.08.25-server.txt](https://github.com/MohistMC/Mohist/files/6002784/crash-2021-02-18_11.08.25-server.txt)

**Comment by Shawiizz** [comment]
Hello, please follow the issue template. The only thing i can tell you to do rn is to remove all mods 1 per 1 and plugins 1 per 1 to see which is causing that bug.

**Comment by Skyere** [comment]
I think that it follows with thaumic bases

**Comment by SekiAlpha** [comment]
> 
> 
> I think that it follows with thaumic bases

Well let us know if that's what's breaks mohist.
