### ISSUE TITLE
NullPointerException in JarLoader

### ISSUE THREAD

**Issue by gravit0** [Teneted/Tenet#952]
Using: Java 11:
`java -cp mohist-1.16.5-368-server.jar net.minecraftforge.server.ServerMain`
I guess this error:
```
An error occurs with the server start. You can ask for help to the Mohist support on Discord or GitHub.
```
This method is worked - `java -jar mohist-1.16.5-368-server.jar`. But this launch method is not suitable  
After, I found this error:
```
java.lang.NullPointerException
        at com.mohistmc.util.JarLoader.loadJar(JarLoader.java:34)
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:44)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:40)
```
This code:
```
                // If Java 9 or higher use Instrumentation
                //System.out.println(path);
                inst.appendToSystemClassLoaderSearch(new JarFile(path));
```
Not check `inst == null`. Maybe bring a friendly error message? As `please add -javaagent:mohist-1.16.5-368-server.jar`?

**Comment by KR33PYK1NG** [comment]
Implemented in e9c10ed
