### ISSUE TITLE
Server lag/freeze switch different world

### ISSUE THREAD

**Issue by WareZ57** [Teneted/Tenet#959]
Hello,

I use Multiverse for my different worlds / portals.

Unfortunately with each teleportation in another world, this one causes an error in the console and causes a freeze / lag few seconds and is  return to normal ..

Any idea ?

Server version : mohist-1.16.5-368

![image](https://user-images.githubusercontent.com/7504466/108606351-f7e42480-73b9-11eb-8a48-c0789e33f20b.png)
![image](https://user-images.githubusercontent.com/7504466/108606387-23670f00-73ba-11eb-8d60-3904f2bf801b.png)

**Comment by joaoespanhol** [comment]
post log do server.

**Comment by joaoespanhol** [comment]
Plugins are not yet supported

**Comment by Shawiizz** [comment]
![unknown](https://user-images.githubusercontent.com/55449195/108608418-156bbb00-73c7-11eb-980e-48b49650ed88.png)
