### ISSUE TITLE
[1.12.2]Server cannot start

### ISSUE THREAD

**Issue by EnterFor** [Teneted/Tenet#963]
mohist-1.12.2-192-server
https://paste.ubuntu.com/p/kcq4zYHKDb/
https://www.curseforge.com/minecraft/mc-mods/perfect-spawn

In the original Forge, it worked well.
I'm a little bit lost, can this be fixed?
I did not find a Mod that can replace it.

**Comment by SekiAlpha** [comment]
You could just find a spigot plugin that could do the same job.
