### ISSUE TITLE
The Player plugin for the PlaceholderAPI is not compatible

### ISSUE THREAD

**Issue by Maklith** [Teneted/Tenet#967]
placeholderAPI-2.10.9
mohist-1.16.5#370
PAPI-Expansion-Player.jar[1.7.2]
![image](https://user-images.githubusercontent.com/42534870/108871616-4b61a700-7634-11eb-89e0-67a1c5819067.png)
![image](https://user-images.githubusercontent.com/42534870/108871620-4c92d400-7634-11eb-9466-5db399f7acc7.png)
![image](https://user-images.githubusercontent.com/42534870/108871630-4dc40100-7634-11eb-84cd-e3d2ac0d0bb7.png)
This also feeds back into player-expansion
https://github.com/PlaceholderAPI/Player-Expansion/issues/43

**Comment by Shawiizz** [comment]
![unknown](https://user-images.githubusercontent.com/55449195/108872195-37994f00-75fa-11eb-9980-c7753516a208.png)
