### ISSUE TITLE
Server closes on startup

### ISSUE THREAD

**Issue by dylanspersad** [Teneted/Tenet#968]
no crash report 

mods:
SecurityCraft
Timber
Abnormals Core
Alex's Mobs
Aquaculture 2
Ars Nouveau
Biomes O' Plenty
Cat Jammies
Charms
Citadel
Comforts
Curios
Doggy Talents
Dungeon Crawl
Endergetic
GeckoLib
Mr.Crayfish Furniture
Outer End
Pam's HarvestCraft 2 Food Core
Pam's HarvestCraft 2 Food Extended
Pam's HarvestCraft 2 Crops
Pam's HarvestCraft 2 Trees
Patchouli
Performant
Paraglider
Random Patches
Serene Seasons
Spawner Fix
Towers of the Wild
Traveler's Backpack
Tumbleweed
Two Players One Mount
Valhelsia Structures
Waystones
Xaeros Minimap
Astiko Carts
Create
Macaw's Doors
Macaw's Bridges
Macaw's Roofs
Macaw's Windows
Quark
Spartan Sheilds
XP Tome
Botania
MumbleLink

Mohist Version: 371
[latest.log](https://github.com/Mohist-Community/Mohist/files/6030603/latest.log)

**Comment by Shawiizz** [comment]
Remove mods 1 per 1 and see which one is causing that

**Comment by dylanspersad** [comment]
so far ars nouveau isn't working and only the latest version of charm works
