### ISSUE TITLE
[1.16.5] WorldEdit Forge mod

### ISSUE THREAD

**Issue by Dokman** [Teneted/Tenet#970]
So as soon that i use //wand it doesn't appear.

![image](https://user-images.githubusercontent.com/2290904/108893388-56efa680-7611-11eb-8582-fc691fc69268.png)

This is the only log i have in console so... idk how i can fix it.

**Comment by flololan** [comment]
I use FastAsynWorldEdit, that works fine for me

**Comment by Dokman** [comment]
the last version?

**Comment by flololan** [comment]
FastAsyncWorldEdit-1.16-596

**Comment by Dokman** [comment]
> FastAsyncWorldEdit-1.16-596

With that version i am having this bug
![image](https://user-images.githubusercontent.com/2290904/109439308-1a1b1980-7a2e-11eb-8d64-748c49f58a47.png)

**Comment by KR33PYK1NG** [comment]
Fixed in abda529
