### ISSUE TITLE
Server don't stop after /stop command in console (1.16.5)

### ISSUE THREAD

**Issue by GDVE** [Teneted/Tenet#974]
The problem is that the server does not want to stop if there are plugins. 
I've tested with a lot of plugins, this problem persists even with my plugins.

**I am using the latest build 371.**
![image](https://user-images.githubusercontent.com/19783608/108934076-48c77780-765d-11eb-971f-9d030fcaf8d2.png)

**Comment by Shawiizz** [comment]
Same as #819
