### ISSUE TITLE
[1.16.5]Failed to load datapacks, cant proceed with server load

### ISSUE THREAD

**Issue by Xplodin** [Teneted/Tenet#975]
[latest.log](https://github.com/Mohist-Community/Mohist/files/6032910/latest.log)

i cant figure this one out

**Comment by Beshelmek** [comment]
Confirm. Same issue.

**Comment by Beshelmek** [comment]
@Xplodin The tetra mod causes this problem

**Comment by Xplodin** [comment]
Ahhh alright. Hopefully immersive portals gets compat tho too

**Comment by mickelus** [comment]
Afaik this has nothing to do with mohist, tetra crashes on startup due to a change in forge 36.0.41.
