### ISSUE TITLE
[1.12.2] Cannot download libraries from mgazul.cn/libraries/

### ISSUE THREAD

**Issue by vico93** [Teneted/Tenet#976]
I'm trying to run for the first time mohist (`mohist-1.12.2-192-server.jar`), i'm using CustomJAVA since i dont have Java 8 installed in my system (only 15), but everytime i try to run Mohist with the following command:

`path\to\java.exe -Xms2G -Xmx12G -jar mohist-1.12.2-192-server.jar nogui`

I got several download errors from mgazul.cn and mohist cant start.

I tried installing Forge 2855 to see if its installer can fetch all libraries but still there is some left which i cant download.

Using Windows 10 as OS.

**Comment by Shawiizz** [comment]
Cannot reproduce.

**Comment by vico93** [comment]
I think, at least for me, CustomJAVA/JRE shipped with Mojang launcher have issues connecting to internet. Downloading AdoptOpenJDK's Java 8 solved the problem. Sorry for the inconvenience.
