### ISSUE TITLE
An error is reported after the player enters[1.16.5]

### ISSUE THREAD

**Issue by Maklith** [Teneted/Tenet#983]
mohist 1.16.5 381
https://paste.ubuntu.com/p/TVBzVgwR5X/

**Comment by Maklith** [comment]
What more information do I need to provide

**Comment by Dokman** [comment]
plase put the log [here](https://haste.mohistmc.com/) and put a link with the log of the server, instead spamming the issue with all the log.

**Comment by Maklith** [comment]
[latest.zip](https://github.com/Mohist-Community/Mohist/files/6076660/latest.zip)
Because most of the logs were duplicate errors and the file was too large, I packaged it as a zip package

**Comment by Maklith** [comment]
https://haste.mohistmc.com/yabidunawe.apache

**Comment by Maklith** [comment]
> plase put the log [here](https://haste.mohistmc.com/) and put a link with the log of the server, instead spamming the issue with all the log.

https://haste.mohistmc.com/yabidunawe.apache
