### ISSUE TITLE
Not sure if bug. Server sometimes doesn't ping.

### ISSUE THREAD

**Issue by jreoka** [Teneted/Tenet#984]
This could very well be an issue with my firewall or setup, but is there a known bug of the server endlessly trying to ping sometimes, and other times it showing up?

Sorry if this isn't the right place for this.

**Comment by Shawiizz** [comment]
Hey, i don't think it's related to Mohist, i don't have this type of problem.

**Comment by jreoka** [comment]
@Shawiizz ok. Thank you for the feedback. I'll close the issue.
