### ISSUE TITLE
IC2的电线一段时间会连不起来，需要重新拆开重新放置

### ISSUE THREAD

**Issue by luluxiaoyu** [Teneted/Tenet#987]
IC2的电线一段时间会连不起来，需要重新拆开重新放置
![image](https://user-images.githubusercontent.com/58876608/109377693-f52c8680-7907-11eb-9ced-1ced6fcbbba6.png)

**Comment by KR33PYK1NG** [comment]
Duplicate of #936.
Potential fix is being worked on.
