### ISSUE TITLE
Beehives keep spawning bees

### ISSUE THREAD

**Issue by Silmoheru** [Teneted/Tenet#992]
Hi there im running a server with mohist. i have 2 plugins(stackmob and mcmmo) along with some mods. i have a problem when i place a beehive and have 3 bees go into said beehive when they come out they come out in swarms and the beehive keeps spwaning more bees and the bees then wont go into said beehive to make honey. i have loaded up a singleplayer to test it on there without plugins and it worked fine. so i took out the plugins on my server and even made several new servers to test it and it didnt work when i loaded my server. i then made just a forge server to test with the mods i had and it worked fine. so i have come to the conclusion that it is definitly mohist doing this. i have also changed the mohist config for entitites and for tiles and set the bees and beehive on 0. i also went i8nto the bukkit and spigot files and changed the spawning rules to vanillia rules and it still isnt working properly
https://cdn.discordapp.com/attachments/227493530006847490/815801110702718976/unknown.png

**Comment by KR33PYK1NG** [comment]
This was fixed earlier.
Are you sure you're using the latest build (377)?

**Comment by Silmoheru** [comment]
ok im on 360 it says there a 379 where can i find it

**Comment by KR33PYK1NG** [comment]
mohistmc.com

**Comment by Silmoheru** [comment]
yh its fixed woop thank you
