### ISSUE TITLE
Spawning in Void

### ISSUE THREAD

**Issue by TypicalB** [Teneted/Tenet#993]
Hello, I'm using the newest version of Mohist (mohist-1.12.2-192) I am also using the Multiverse Plugin as my World Manager. The issue is, whenever I create a new world and go to that world and log off and back in. I spawn in a void until I either tp to someone, tp out or /kill myself. This only happens with worlds that are not predefined in my console. So for example, if my main world that is predefined in console is named "World" and I logged out in the world "World" I would not get this issue. However every other world I would.

**Comment by Shawiizz** [comment]
If you're using SkinsRestorer, remove it and it will solve this problem.

**Comment by TypicalB** [comment]
SkinsRestorer? Is that a stand-alone mod/plugin?

**Comment by Shawiizz** [comment]
This is a plugin

**Comment by TypicalB** [comment]
ah ok, you kinda helped me here. In the CMI Plugin there is an option for Skins to Auto apply, when that is set to false the void goes away. Ty for guiding me.
