### ISSUE TITLE
authlib-injector-1.1.34.jar has been ignored - it is invalid

### ISSUE THREAD

**Issue by atogumo** [Teneted/Tenet#995]

**Comment by atogumo** [comment]
I use this mod to login through a skin website, but cmd shows waring:
[20:51:00 WARN]:Mod file Mod File: E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar is missing mods.toml file
[20:51:00 WARN]:File E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar has been ignored - it is invalid
[20:51:13 WARN]: Mods loaded with 1 warnings
[20:51:13 WARN]:File authlib-injector-1.1.34.jar is not a valid mod file

repository of the file:
https://github.com/yushijinhun/authlib-injector

**Comment by Shawiizz** [comment]
The mod is just invalid. I think the dev of this mod forgot something

**Comment by MCUmbrella** [comment]
> 
> 
> I use this mod to login through a skin website, but cmd shows waring:
> [20:51:00 WARN]:Mod file Mod File: E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar is missing mods.toml file
> [20:51:00 WARN]:File E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar has been ignored - it is invalid
> [20:51:13 WARN]: Mods loaded with 1 warnings
> [20:51:13 WARN]:File authlib-injector-1.1.34.jar is not a valid mod file
> 
> repository of the file:
> https://github.com/yushijinhun/authlib-injector

You used it in a wrong way.
Authlib Injector should be used as a Java agent - NOT A MOD.
For how to use, [refer to here](https://github.com/yushijinhun/authlib-injector/#%E9%83%A8%E7%BD%B2)

**Comment by atogumo** [comment]
Thanks a lot, I think I just misunderstand the way it should be used.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mohist-Community/Mohist"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 上午6:39
收件人:&nbsp;"Mohist-Community/Mohist"<Mohist@noreply.github.com&gt;;
抄送:&nbsp;"忒修斯之旅"<917451540@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mohist-Community/Mohist] authlib-injector-1.1.34.jar has been ignored - it is invalid (#995)





  
I use this mod to login through a skin website, but cmd shows waring:
 [20:51:00 WARN]:Mod file Mod File: E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar is missing mods.toml file
 [20:51:00 WARN]:File E:\Minecraft1_16_5\mods\authlib-injector-1.1.34.jar has been ignored - it is invalid
 [20:51:13 WARN]: Mods loaded with 1 warnings
 [20:51:13 WARN]:File authlib-injector-1.1.34.jar is not a valid mod file
 
repository of the file:
 https://github.com/yushijinhun/authlib-injector
  
You used it in a wrong way.
 Authlib Injector should be used as a Java agent - NOT A MOD.
 For how to use, refer to here
