### ISSUE TITLE
1.16.5 Stopping the server while loading the map

### ISSUE THREAD

**Issue by Draco-Zero** [Teneted/Tenet#996]
![sdaddsadd](https://user-images.githubusercontent.com/38159940/109545514-ff9e7a00-7ad9-11eb-8d79-bc86feabb9d3.PNG)
The server very often stops loading the map. It helps to delete the .mixin-out and plugins folders. This happens randomly with different versions of mohist.

**Comment by Gizmo0320** [comment]
I am having a similar issue. Except mine never fully loads.
It will load everything else just find and then it will stop preparing the world spawn at about 90% to 97%.

**Comment by Draco-Zero** [comment]
After yesterday's crash due to a bug in one mod, I also stopped loading the world at all, progress stops at 18%. I had to switch to pure forge.

**Comment by Shawiizz** [comment]
Hey, please try to allow more ram, and provide mods and plugins list

**Comment by Draco-Zero** [comment]
Mods:  <td><a href="https://www.curseforge.com/minecraft/mc-mods/search?search=abnormals_core" title="abnormals_core 3.0.6" target="_blank" class="badge badge-info">abnormals_core</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=appliedenergistics2" title="appliedenergistics2 8.2.0" target="_blank" class="badge badge-info">appliedenergistics2</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=ars_nouveau" title="ars_nouveau 1.11.4" target="_blank" class="badge badge-info">ars_nouveau</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=atmospheric" title="atmospheric 3.0.0" target="_blank" class="badge badge-info">atmospheric</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=bookshelf" title="bookshelf 9.3.25" target="_blank" class="badge badge-info">bookshelf</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=botania" title="botania 1.16.4-411" target="_blank" class="badge badge-info">botania</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=createaddition" title="createaddition 1.16.4-20210202a" target="_blank" class="badge badge-info">createaddition</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=create" title="create mc1.16.3_v0.3e" target="_blank" class="badge badge-info">create</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=curios" title="curios 1.16.4-4.0.3.5" target="_blank" class="badge badge-info">curios</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=eidolon" title="eidolon 0.2.7" target="_blank" class="badge badge-info">eidolon</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=endergetic" title="endergetic 3.0.0" target="_blank" class="badge badge-info">endergetic</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=fallingtree" title="fallingtree OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱" target="_blank" class="badge badge-info">fallingtree</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=fastleafdecay" title="fastleafdecay v25" target="_blank" class="badge badge-info">fastleafdecay</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=fluxnetworks" title="fluxnetworks 1.16.4-6.1.2.7" target="_blank" class="badge badge-info">fluxnetworks</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=forge" title="forge ANY" target="_blank" class="badge badge-info">forge</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=ftbguilibrary" title="ftbguilibrary 1604.1.1.26" target="_blank" class="badge badge-info">ftbguilibrary</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=geckolib3" title="geckolib3 3.0.13" target="_blank" class="badge badge-info">geckolib3</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=ironchest" title="ironchest 1.16.4-11.2.10" target="_blank" class="badge badge-info">ironchest</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=jei" title="jei 7.6.0.62" target="_blank" class="badge badge-info">jei</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=mcjtylib" title="mcjtylib 1.16-5.0.16" target="_blank" class="badge badge-info">mcjtylib</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=mekanism" title="mekanism 10.0.19" target="_blank" class="badge badge-info">mekanism</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=mekanismgenerators" title="mekanismgenerators 10.0.19" target="_blank" class="badge badge-info">mekanismgenerators</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=minecraft" title="minecraft 1.16.5" target="_blank" class="badge badge-info">minecraft</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=neoncraft" title="neoncraft 2.1" target="_blank" class="badge badge-info">neoncraft</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=observerlib" title="observerlib 1.16.4-1.5.1" target="_blank" class="badge badge-info">observerlib</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=patchouli" title="patchouli 1.16.4-48" target="_blank" class="badge badge-info">patchouli</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=performant" title="performant OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱" target="_blank" class="badge badge-info">performant</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=psi" title="psi 1.16-91" target="_blank" class="badge badge-info">psi</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolsbase" title="rftoolsbase 1.16-2.0.10" target="_blank" class="badge badge-info">rftoolsbase</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolsbuilder" title="rftoolsbuilder 1.16-3.0.16" target="_blank" class="badge badge-info">rftoolsbuilder</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolsdim" title="rftoolsdim 1.16-7.0.6-beta" target="_blank" class="badge badge-info">rftoolsdim</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolspower" title="rftoolspower 1.16-3.0.8" target="_blank" class="badge badge-info">rftoolspower</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolsstorage" title="rftoolsstorage 1.16-2.0.11" target="_blank" class="badge badge-info">rftoolsstorage</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=rftoolsutility" title="rftoolsutility 1.16-3.0.25" target="_blank" class="badge badge-info">rftoolsutility</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=simplylight" title="simplylight 1.16.4-1.1.2" target="_blank" class="badge badge-info">simplylight</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=spark" title="spark OHNOES😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱😱" target="_blank" class="badge badge-info">spark</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=trashslot" title="trashslot 12.2.1" target="_blank" class="badge badge-info">trashslot</a> <a href="https://www.curseforge.com/minecraft/mc-mods/search?search=waila" title="waila 1.10.11-B78_1.16.2" target="_blank" class="badge badge-info">waila</a></td>
No plugins were used.
With the allocation of memory was played and still with different settings, nothing changes from this.
