### ISSUE TITLE
[Plugin/Bug/] Compatibility of WE and FAWE

### ISSUE THREAD

**Issue by Dokman** [Teneted/Tenet#997]
It load the schematic but then have a try catch because something is unimplemented.
[Log](https://haste.mohistmc.com/hoxidonula.md)

![image](https://user-images.githubusercontent.com/2290904/109571899-9e33d680-7aec-11eb-94d1-464c4488f1de.png)

**Comment by MagnusHJensen** [comment]
I can't paste a schematic file with FAWE (Bukkit-1.17-442) 
It's a different error though now.
Mohist is 1.16.5 (889)

Logs: https://pastebin.com/Syvs2w0n

Even though it errored, it did still paste fine (I think)
Just had to reload the chunk.

I tried pasting the "Inn.schematic" from this pack. https://www.planetminecraft.com/project/medievalfantasy-building-bundle/

**Comment by Mgazul** [comment]
This issue will be the default issue for worldedit and fawe because there are too many duplicates

**Comment by Mgazul** [comment]
FastAsyncWorldEdit requires java17 to run, and forge-1.16.5 does not support java17, this is the main problem

**Comment by Dokman** [comment]
> FastAsyncWorldEdit requires java17 to run, and forge-1.16.5 does not support java17, this is the main problem

I'm running Mohist on Java 17 and have no troubles. I'm testing thourougly

**Comment by Dokman** [comment]
latest FAWE log

[https://haste.mohistmc.com/yacawikuto.sql](https://haste.mohistmc.com/yacawikuto.sql)

**Comment by SimonMage** [comment]
Exist a version of FAWE that supports java 11, this is not the main problem. The real problem is FAWE doesn't recognize Mohist API

**Comment by Dokman** [comment]
> Exist a version of FAWE that supports java 11, this is not the main problem. The real problem is FAWE doesn't recognize Mohist API

The main problem is that it has to patched like worldedit pbut it's not the same so i don't know how to make a working patch for Fawe Mohist now Supports Java 17 so it can be made out of the newest FAWE but it needs to be patched

**Comment by nailerua** [comment]
New ?

**Comment by Dokman** [comment]
> 

What new?

**Comment by XionioXMaster** [comment]
> 

Nothing

**Comment by fmichael98** [comment]
is this fixed yet?
i'm having the same issue on 1.19.2

**Comment by Dokman** [comment]
> is this fixed yet? i'm having the same issue on 1.19.2

it's not fixed just wait.

**Comment by JLSkyzer** [comment]
it's fixed for 1.16.5?

**Comment by Dokman** [comment]
nope just wait

**Comment by ReijinTail26** [comment]
Hello, any update on that issue ?

**Comment by Mgazul** [comment]
Fixed!
