### ISSUE TITLE
1.16.5 problem plugin CMI

### ISSUE THREAD

**Issue by joaoespanhol** [Teneted/Tenet#998]
log: https://mclo.gs/zY85jkp
Last version
when I give ./kill nicki he dies and I can't move the doll or talk about the chat
![image](https://user-images.githubusercontent.com/22871432/109567675-a89aa400-7add-11eb-9be9-61317a5bfb52.png)
![image](https://user-images.githubusercontent.com/22871432/109567700-b2240c00-7add-11eb-9c87-f78956c0e0b7.png)

**Comment by Xplodin** [comment]
This also happened to me when i was killed by an Iron Golem

**Comment by KR33PYK1NG** [comment]
Fixed in 58659e0

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/109930857-05ee4b00-7cc0-11eb-8842-71ff40cbe801.png)
is no fix,

good, the error continues, I can't speak or move, I have to leave the server and come back.
But do not generate console error.
it looks like it stayed inside the body, where to die.

You need reopen ticket @KR33PY

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/111024249-89512000-83d5-11eb-8eb0-de1007afaaa0.png)

**Comment by joaoespanhol** [comment]
new bugs:
https://mclo.gs/vJqJ918

**Comment by joaoespanhol** [comment]
![image](https://user-images.githubusercontent.com/22871432/111024747-5fe5c380-83d8-11eb-95b1-9ced31697d10.png)
problem death :(

**Comment by Chetok3** [comment]
I deleted cmi folder n it works. I think this is due to changes in the config

**Comment by joaoespanhol** [comment]
> Excluí a pasta cmi n funciona. Acho que isso se deve a mudanças na configuração

is a mohist problem, because spigot and paper will work well

**Comment by joaoespanhol** [comment]
is work fine last version mohist @KR33PY

**Comment by Xplodin** [comment]
Just had this bug on the latest mohist and cmi.
shortly after respawning it does the same thing
