### ISSUE TITLE
GriefPrevention + Create mod blockzapper, wand of symmetry and wrench events

### ISSUE THREAD

**Issue by muriplz** [Teneted/Tenet#999]
I've been on a server with the GriefPrevention plugin + Create mod and a lot of things bypass the protections. You can also click the bearings to start them up, hand cranks, etc.
FTBChunks also lets mechanical pistons move blocks into protections.
(might not be mohist fault, i don't know)

**Comment by KR33PYK1NG** [comment]
That's how it is and how it always was with combining protection plugins and Forge mods.
Be prepared to fix/mitigate protection-related problems individually for your server's needs.
